### ISSUE TITLE
Implement hash types removing dependency on ethereum_types

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#10]
Implement our own version of the types that are currently pulled from `ethereum_types` removing the create as a dependency.

**Comment by vlopes11** [comment]
Hello, I'll tackle this one.

I'll fork the code "as is", apply our style and remove the unused types (if any). Ok?

**Comment by paulhauner** [comment]
Hey @AgeManning, I suggest we close this issue for now. Partly because of the points raised in #132 and also because I don't think this is a priority at the moment. Thoughts?

**Comment by AgeManning** [comment]
Yep agreed. We can circle back when we need to.
