### ISSUE TITLE
Cleanup RPC Protocol Names

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1000]
## Description

As the RPC protocol names have become more complex it would be nicer to rely the rust type-system to handle correct implementation of all RPC protocols.

Currently we use static string constants and these are implemented in various codecs. These static strings should be converted into an enum type which we can match against in various parts of the code which allows the compiler to check that all code paths are implemented correctly. This should also be done for the RPC versions.

This is an extension to #987. 

More info provided on request :).

**Comment by divagant-martian** [comment]
i'm working on this
So far I made the protocol names (ping/metadata/status/etc) and the encoding(ssz/ssz_snappy) into enums, but I didn't find the constants used outside the RPC crate. is there something I'm missing?

**Comment by AgeManning** [comment]
Resolved in #1024
