### ISSUE TITLE
refer to datadir variable in docs

### ISSUE THREAD

**Issue by ethers** [sigp/lighthouse#1007]
## Description

To help with #1006 can the docs such as
https://lighthouse-book.sigmaprime.io/become-a-validator-source.html
refer to a variable such as $datadir ?

Instead of assuming defaults:
`This means you've successfully generated a new sub-directory for your validator in the .lighthouse/validators directory.`

Is ".lighthouse" the datadir?  If so, the docs should use "$datadir/validators" to clarify to users.

**Comment by paulhauner** [comment]
Thanks @ethers :)

I think we should figure out what we're going to do in #1006, then update the docs.

**Comment by paulhauner** [comment]
Closing this one since we've refactored the docs since it was created.
