### ISSUE TITLE
Investigate SSE with hyper

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1032]
## Description

In the Eth2 API standardisation efforts, SSE (server-side events) have been [suggested](https://github.com/ethereum/eth2.0-APIs/issues/25#issuecomment-611919302) to handle the seemingly necessary streaming endpoints.

AFAIK, hyper doesn't come out-of-the-box with support for SSE. That being said, a web search shows several crates purporting to provide SSE in hyper.

It would be great to know:

- Is it feasible to do SSE with our current hyper stack
- If it's feasible
  - What's the effort look like? (hours, days, weeks, etc)
  - Will it be elegant?

**Comment by adaszko** [comment]
Pick me, pick me!

**Comment by adaszko** [comment]
Done via https://github.com/sigp/lighthouse/pull/1107
