### ISSUE TITLE
Allow the "seen" caches to persist to disk

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1055]
## Description

#983 introduces several caches that stop objects we've already seen from propagating on the network. We can see all of them here:

https://github.com/sigp/lighthouse/blob/4285f227c43db6b2d6312bff225fc9fcc30f6033/beacon_node/beacon_chain/src/builder.rs#L432-L441

We should persist these caches to disk so they are retained through a restart. The typical way to go about this is to implement methods to allow them to go to/from SSZ bytes and then persist them on `Drop` of `BeaconChain` and load them from disk using the `BeaconChainBuilder` during startup.

For an example, see `HeadTracker`. We define to/from SSZ here:

https://github.com/sigp/lighthouse/blob/4285f227c43db6b2d6312bff225fc9fcc30f6033/beacon_node/beacon_chain/src/head_tracker.rs#L53-L88

The `HeadTracker` is persisted with the head and fork choice:

https://github.com/sigp/lighthouse/blob/4285f227c43db6b2d6312bff225fc9fcc30f6033/beacon_node/beacon_chain/src/beacon_chain.rs#L229

However, we don't need to do this with the "seen" caches. Like the `eth1_cache`, we only need to persist it on `Drop`:

https://github.com/sigp/lighthouse/blob/4285f227c43db6b2d6312bff225fc9fcc30f6033/beacon_node/beacon_chain/src/beacon_chain.rs#L2052

**Comment by paulhauner** [comment]
Blocked on #983, this issue is only valid once it has been merged.

**Comment by danielschonfeld** [comment]
So a few questions here: 

1) what do you mean by saying we don't need to do what is done in HeadTracker and mimic more of waht is done with the eth1 cache? Do you mean that we only need to implement the saving+restoring in Drop and BeaconChainBuilder only?  (as opposed to how ```persist_head_and_fork_choice``` is used in ```fork_choice_internal```in addition to the Drop trait?

2) I am seriously confused as to why all keys name are the same in the saving to the database operation:
https://github.com/sigp/lighthouse/blob/master/beacon_node/beacon_chain/src/beacon_chain.rs#L70-L74

3) I am not quite clear how exactly the first time load is handled, where the database is throwing errors that the key doesn't exist yet? I see the errors, and the ? meant to handle it.  But I don't understand how it affects the building of the BeaconChain struct

Thanks!

cc @paulhauner

**Comment by michaelsproul** [comment]
Regarding (2), all those keys get prefixed with different "columns" here: https://github.com/sigp/lighthouse/blob/e5fc6bab485fa54d7e518b325f4eb9201ba5c6a1/beacon_node/store/src/lib.rs#L132-L175

**Comment by paulhauner** [comment]
> Do you mean that we only need to implement the saving+restoring in Drop and BeaconChainBuilder only? (as opposed to how persist_head_and_fork_choice is used in fork_choice_internalin addition to the Drop trait?

Yep, that's right. The seen caches don't need to be periodically saved to disk throughout operation (like is done with `persist_head_and_fork_choice`). They can just be saved when the `BeaconChain` is dropped:

https://github.com/sigp/lighthouse/blob/e5fc6bab485fa54d7e518b325f4eb9201ba5c6a1/beacon_node/beacon_chain/src/beacon_chain.rs#L2179-L2200

> I am seriously confused as to why all keys name are the same in the saving to the database operation

Indeed this does seem a bit funny at first. The database is split into "columns". Since it's a flat key-value database we don't *really* have columns, instead we just add a prefix to each key to create separate name spaces:

https://github.com/sigp/lighthouse/blob/e5fc6bab485fa54d7e518b325f4eb9201ba5c6a1/beacon_node/store/src/lib.rs#L132-L175

For example, when you store a block in the database the key isn't `block_hash`, it's `concat("blk", block_hash)`.

> I am not quite clear how exactly the first time load is handled, where the database is throwing errors that the key doesn't exist yet?

I'm not sure I fully understand the question, but here's an example of the `BeaconChainBuilder` discovering that it doesn't have an existing canonical head stored to disk and instead using the genesis state:

https://github.com/sigp/lighthouse/blob/e5fc6bab485fa54d7e518b325f4eb9201ba5c6a1/beacon_node/beacon_chain/src/builder.rs#L461-L468

**Comment by danielschonfeld** [comment]
@paulhauner (and @michaelsproul) - I believe all my questions have been answered.  I'll try to have a draft PR ready tomorrow with just the `observed_attestations` cache, to gauge if i'm headed in the right direction.  If you guys agree it is, i'll continue with the rest of the caches in the same manner.

**Comment by paulhauner** [comment]
See https://github.com/sigp/lighthouse/pull/1912 for a partially-outdated, but still useful implementation of this.

**Comment by paulhauner** [comment]
I'm closing this for the same reason I closed #1912
