### ISSUE TITLE
RPC BlockByRange Rate Limit

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1056]
Peers can request large ranges of blocks during syncing and arbitrary amounts if they are malicious. 

The RPC protocol is structured in a stream manner where at the slowest speed we can respond with is one block every 10 seconds. Thus a peer could request 1M blocks and we can then determine the rate we wish to send blocks to this peer. If the peer performs multiple requests simultaneously, we can either further decrease the rate or disconnect the peer. Therefore, potentially we could establish a bandwidth of sorts, per-peer and send blocks matching the bandwidth. 
The rate at which we respond to peers may also be determined on the number of peers we are currently servicing.

Some initial thoughts around this:
We could set up a separate object that processes RPC Range requests in it's own task. If there is only one request, it processes it at maximum speed. It may have a maximum limit as to how many blocks it can send per second and distributes these based on peers. If a peer asks for many blocks we may slow it down and prioritise a peer that asks for fewer. We may also just put a fixed blocks/second limit per peer and disconnect. 

In terms of implementation, blocks by range requests end up here: https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/router/processor.rs#L322

This code currently fetches blocks from the db and sends them along the stream. If multiple requests occur simultaneously they are processed in order. Potentially spawning a new task here that takes the requests and handles or deals with the more advanced logic on a per-peer basis would be one way of implementing this. An issue with the current implementation, is a peer could ask for 1M blocks which would block this thread and prevent us servicing other peers until all blocks have been sent. Ideally we would want to handle new requests simultaneously and reduce the speed at which we send blocks to the peer that requests 1M blocks.

Another way, would be to simply record the number of requests per second from a peer and adjust the reputation if too many requests are received (and prevent requests over a certain size).

**Comment by divagant-martian** [comment]
:raising_hand: I'll take it

**Comment by divagant-martian** [comment]
Closed by #1402
