### ISSUE TITLE
Improved discovery handling for subnets

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1057]
## Description

The attestation service manages the timing logic for discovery and connecting to particular subnets for attached validators. Currently the service sends a discovery request for a subnet and leaves it at that. 

This is not great for a number of reasons. Firstly, if the search reveals no useful peers and we still have time before subscribing to the subnet, we should continue performing searches (perhaps a maximum of 3 searches before giving up). 
Secondly, we would like to keep track of the peers that we find and ensure we stay connected to them at least until the time they are needed for subscription to a subnet. 

To do this, I imagine the discovery request from the attestation service should include a time which indicates how long we should keep the discovered peers for. 

The discovery request itself should then keep track of its discoveries via an ID (which I will build into discv5 itself) i.e: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/discovery/mod.rs#L256
This function gets called for a request for discovery. It should now keep the Instant at which we need to keep peers. The query that gets sent will return a `QueryId` (I'll add this into discv5) so that we can match peers that get discovered for the `QueryId` (here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/discovery/mod.rs#L441) or repeat the query if an insufficient number of peers are found.)

Once peers are found for a specific query, we should tag them as being kept alive for the specific amount of time. This can be done via modifying the `PeerDb` which contains information about any given peer. 
See some use of it here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/discovery/mod.rs#L463

Adding something like `wanted_until: Option<Instant>` to `PeerInfo` : https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/peer_manager/peer_info.rs#L17

will allow the peer manager to decide to keep this peer if we need to prune our peers. This way, discovered peers for a particular subnet will not get dropped early.

**Comment by realbigsean** [comment]
I can work on this.

**Comment by AgeManning** [comment]
Closed in #1203
