### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1064]
Started familiarising myself with the codebase and picked up minor typos.

* (beacon_chain.rs, line 1536) "Returns an `Err` if the given block was invalid, or an error was encountered during" => incomplete sentence
* "a HTTP API" => "an HTTP API"
* "The block is malformed/invalid (indicated by all results other than `BeaconChainError`." => missing closing bracket
* "Perform the freezing operation on the database," => comma should be dot
* `min_genesis_delay: 86400` => `86_400` for consistency
* "If the block is is" => "If the block is"
* "//TODO" => "// TODO"
* "merkle proof" => "Merkle proof"
* "fok zeroed" => "fork zeroed"
* missing new line above `macro_rules! safe_sub_assign {`
* "when it it is" => "when it is"

**Comment by paulhauner** [comment]
This issue has dated and I'm not sure it's worth trying to find these typos in the code base anymore. Thanks for raising them though :)
