### ISSUE TITLE
Validator keypair handling

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1073]
This issue is an RFC regarding how we handle validator keypairs.

## Problem statement

Eth2 validators need to keep two keypairs (potentially the same):

- _Voting keypair_: a "hot" keypair used for voting on attestations/blocks and exiting.
- _Withdrawal keypair_: a "cold" keypair used for obtaining ETH after a validator has become withdrawable.

## Definitions

- Keypair: a BLS-381 keypair stored in an encrypted [EIP-2335](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md) keystore.
- `validator-dir`: a directory in the validator clients datadir that contains a director for each validator that is named after it's voting public key
  - E.g., `~/.lighthouse/validators/0x01ab..`

## Observations/Assumptions

- Voting keypair will need to be loaded into memory by the validator client so it can performing its duties.
- Withdrawal keypair is not used much, in fact it doesn't even have any purpose in phase 1 beyond being used in the initial deposit.
-  Voting keypair is sensitive because it can trigger a slashing.
- Withdrawal keypair is sensitive because it ultimately controls the fate of withdrawn ETH.

## Desired

- Support for common _or_ distinct keypairs for voting & withdrawal keypairs.
  - Default flow for separate voting & withdrawal keypairs.
- Support for distinct voting & withdrawal keypairs, but both encrypted with the same password
  - Default flow for distinct passwords.
- Easy to support multiple (10s, 100s) of validators in the same validator client.
- Flow should be sensible when conducted via CLI or via the HTTP API (in the case of a GUI staking interface).

### Flow: CLI key generation

- User runs `lighthouse account validator new` with the following flags:
  - `--specify-voting-password`: if present, the user is prompted to enter a password for the voting keypair. Otherwise it is generated randomly.
  - `--generate-withdrawal-password` if present, user is _not_ prompted for a withdrawal password and it is generated randomly/
  - other flags like `--count`, `--testnet-dir`, etc that aren't important to this example.

The user is then (maybe) prompted for the following password(s):

- If `--generate-withdrawal-password` **is not** specified, they should enter it in via CLI prompt.
- If `--specify-voting-password` **is** specified, they should enter it via CLI prompt.

In all scenarios, the encrypted keystore for the voting and withdrawal keypairs will be placed in the `validator-dir`.

In all scenarios, the password for the (hot) _voting keypair_ will placed in the `validator-dir`.

The password for the _withdrawal keypair_ will only be placed in the `validator-dir` if the `--generate-withdrawal-password` is supplied. Otherwise, we assume the user has backed it up elsewhere.

### Flow: API key generation

Basically the same as the CLI key generation, except we're going to need to pass the passwords along with the request.

Open question: do encrypt the passwords in the request or do we assume there's transport-level security (HTTPS)?

### Flow: CLI validator client start

Simply run `lighthouse vc` and then it will be able to load all the validators from `~/.lighthouse/validators` directory and decrypt the corresponding voting keystore using the adjacent password.

### Flow: validator withdrawal

We don't really know how this will work since it's not included in phase 0.

However, according to the previous flows the user has either (hopefully) backed it up or it has been placed inside the `validator-dir`.

### Why are we reading passwords from disk?

I can see three options to get the voting keypair into the validator client:

1. CLI flag: `lighthouse vc --password 1234`
1. Env variable: `export VALIDATOR_PASSWORD=1234; lighthouse vc`
1. Passwords as files: `lighthouse vc --password-dir ~/.lighthouse/passwords`

I'm hesitant with (1) since it commonly ends up exposing passwords in bash history, etc. It's also pretty much unmanageable for large validator counts with distinct passwords.

(2) is pretty standard, this is how AWS credentials are commonly handled. However, it doesn't scale so well for multiple validators either.

(3) scales well with multiple validators and it also avoids exposing secrets to the shell. It's also how eth1 does it now.

### Why are we putting the passwords inside the validator directory?

I can see two places we can put the passwords:

1. Inside the corresponding dir in the `~/.lighthouse/validators` directory (as proposed)
1. Put all the passwords in one big folder and then ensure that the name of the password file maps to a validator voting key.

IMO (1) will be easier for users since it uses a less complex password file name scheme. It also makes validator directories more portable.

(2) does mean your passwords aren't right next to the keystore, but what does that really gain? If you can do `cat password.txt` you can probably also do `cat ../passwords/password.txt`.

(1) is probably the easiest, however it means that your password is right next to the encrypted store. (2) means your passwords are in some other directory, however is that really worth anything?

### Why even bother password-encrypting the voting keypair if you put the password right next to it?

It just seems more flexible to me. Perhaps you can use file permissions to allow some user/group to read your keystore to obtain the pubkey but restrict it from accessing the password to read the privkey?

### Why is one flag --specify-... and the other --generate-..?

Thanks @pawanjay176 for raising this, its a good question.

My original thinking was that users were more likely to use a common withdrawal key and distinct voting keypairs. Perhaps this is an awkward, opinionated assumption; keen to hear thoughts.

**Comment by CarlBeek** [comment]
### On Mnemonics

Ideally a mnemonic serves as the core backup mechanism for validators. It is much easier for users to backup their keys via a mnemonic instead of via withdrawal keystore(s). Treatment of this is missing from this discussion.

### On Withdrawal keys

I think clients should avoid storing withdrawal credentials entirely. Reasoning:

* Forces users to remember extra password(s)
* Extra attack surface due to having additional keystores around (which are ancestors in the key-tree)
* Additional engineering work for clients
* Useless in Phase 0
* In Phase 2, withdrawals may be to contracts/arbitrary verification functions (not BLS)
* Potential to confuse users why they have extra keys
* EF's deposit UI does not provide withdrawal keystores
* Debates around whether to store 1 withdrawal key for all validators or 1 key per validator

### Passwords on Disk

Your proposal to store the passwords on disk inside the validator directory makes a lot of sense for the reasons you specify.

Storing the passwords next to the keystores also makes sense outside of the direct context of clients. Portability between client instances, PCs, backups, etc is better when security can be increased by having passwords separate from keystores.

**Comment by paulhauner** [comment]
Thanks @CarlBeek! I completely forgot about mnemonics when writing this :man_facepalming: 

Do you expect a separate mnemonic for voting and withdrawal keypair?

**Comment by CarlBeek** [comment]
So the idea is that there is one mnemonic from which all of the keys are derived.

From the mnemonic, a tree of keys is generated where all of the withdrawal and signing keys can be found. The way I defined it in [EIP #2334](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2334.md#eth2-specific-parameters) is that the `i`th withdrawal keys are at `m/12381/3600/i/0` and the corresponding signing keys are the `0`th child (`m/12381/3600/i/0/0`).

**Comment by paulhauner** [comment]
I think I'm going to need to think though this and come up with something that's based around hierarchical generation from a mnemonic.

Perhaps taking inspiration from @mcdee's very cool [ethdo](https://github.com/wealdtech/ethdo).

Thanks to @CarlBeek for your input and @protolambda for offline input.
