### ISSUE TITLE
Bug bounty plans

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1075]
Is Lighthouse planning to setup a bug bounty program, perhaps after the security review starting May 18? If so, do you know how much consensus bugs (bugs similar to [this one](https://github.com/sigp/lighthouse/issues/1065)) would be rewarded? 😂

**Comment by paulhauner** [comment]
We haven't discussed it formally, but it's definitely something we're interested it. It would certainly be post-security review.

> If so, do you know how much consensus bugs (bugs similar to this one) would be rewarded?

Not sure! Perhaps we'll consider this once you can find more bugs here than we have in the spec :P

**Comment by JustinDrake** [comment]
> Perhaps we'll consider this once you can find more bugs here than we have in the spec :P

🤣

**Comment by zedt3ster** [comment]
As @paulhauner said we're definitely keen on having substantial payouts for this type of bugs as part of our bounty program. We'll circle back once the security review(s) are completed :)
