### ISSUE TITLE
Unnecessary check in is_valid_indexed_attestation

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1077]
I believe the following code snippet in `is_valid_indexed_attestation` is redundant:

```rust
    // Verify max number of indices
    verify!(
        indices.len() <= T::MaxValidatorsPerCommittee::to_usize(),
        Invalid::MaxIndicesExceed(T::MaxValidatorsPerCommittee::to_usize(), indices.len())
    );
```

since the length of `indexed_attestation.attesting_indices` is bounded by `MaxValidatorsPerCommittee` by construction.

**Comment by paulhauner** [comment]
Yep, this seems redundant to me too.

Considering that every array access in Rust does a very similar check, I'm not sure this is going to make any observable performance impact. I'm generally in favor of keeping cheap safety checks, however this does seem particularly redundant so I'd be OK with removing it.

@michaelsproul anything I'm missing here?

**Comment by JustinDrake** [comment]
> I'm generally in favor of keeping cheap safety checks

One needs to be careful to not be too aggressive with checks. Being too aggressive could lead to consensus bugs where, for example, a block is rejected when it should be considered valid.

**Comment by paulhauner** [comment]
> One needs to be careful to not be too aggressive with checks. 

Agreed, the challenge is finding the balance :)

**Comment by michaelsproul** [comment]
This redundant check was removed in https://github.com/sigp/lighthouse/commit/fe03ff0f216ae92414c1b4a684b2e97d578006cc :tada:
