### ISSUE TITLE
Remove BlockProcessingOutcome struct

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1081]
## Description

The `BlockProcessingOutcome` struct is a legacy shim used to soften the impact of a big merge:

https://github.com/sigp/lighthouse/blob/1166231351709465a1c52615480e6e645129326e/beacon_node/beacon_chain/src/block_verification/block_processing_outcome.rs#L7

We should remove this so we can improve code quality.

Thanks to @JustinDrake in #1079 for highlighting this again.

**Comment by divagant-martian** [comment]
this was closed by #1327
