### ISSUE TITLE
Saturating arith on Slot/Epoch should fail state transition

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1100]
## Description

A long time ago, we declared add/sub on `Slot` and `Epoch` to be saturating. This was a good idea at the time (the great genesis slot debate of 2018/2019), however the spec has recently made itself clear on overflows during state trans:

> State transitions that cause a uint64 overflow or underflow are also considered invalid.

This means that there exist states/blocks that we should reject due to overflow but we accept through saturation.

Making a non-API-breaking change where we just change the behaviour of add/sub is likely to introduce all sorts of errors. Perhaps we could remove `+` and `-` for slot/epoch and _only_ have checked methods? This will certainly be annoying for testing though. It's clear that this solution requires some thought.

**Comment by paulhauner** [comment]
@michaelsproul we've fixed this right?

**Comment by michaelsproul** [comment]
Not yet, we should!

**Comment by michaelsproul** [comment]
We should also fix #1098 (related)

**Comment by michaelsproul** [comment]
I've started work on this, planning to roll out the changes in a backwards-compatible way. The `types` crate will have a feature flag to enable the saturating arith. We make sure that types and state_processing can compile without it (they must use safe arith). But the rest of the codebase can continue to use `+` and other ops on `Slot` and `Epoch` as if nothing happened.
