### ISSUE TITLE
Refactor RPC Handler with async-await

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1112]
## Description

In the stable futures upgrade the RPC handler has gotten unnecessarily complex. There is duplicate code and inbound state machine can be simplified. 

This issue is an exercise in async/await and future handling. I imagine the easiest way to handle the excessive states in the inbound substream state-machine is to build an async function that handles the polling, sending and flushing of a substream. This would return a Future that resolves to the underlying substream. This way the substream state would only have a `busy` variant containing the future that resolves to the substream.

**Comment by divagant-martian** [comment]
I like the
> an exercise in async/await and future handling

I'll get this one

**Comment by AgeManning** [comment]
Closed in #1325
