### ISSUE TITLE
Remove `types::ChainConfig`

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#113]
## Description

`types::ChainConfig` has been replaced by the `beacon_chain/spec` crate.

## Steps to resolve

- Remove the `types::ChainConfig` struct.
- Update all dependent code to use `spec::ChainSpec` instead.

**Comment by drozdziak1** [comment]
Decided to try tackle this one, let me know if there's anything extra I should know about this

**Comment by paulhauner** [comment]
Awesome. We're removing antiquated code quite frequently so this task should be getting easier and easier by the day, haha!
