### ISSUE TITLE
Bip39 crate doesn't use zeroize

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1130]
## Description

In #1117 we have introduced the `bip39` crate for mnemonics. Unfortunately that crate doesn't implement `Zeroize` on its sensitive information (from what I can see).

We should try and get a feature added upstream to support this.

## Additional Info

~~This issue is not relevant until #1117 is merged.~~

**Comment by realbigsean** [comment]
There's a recent PR for zeroization of `Seed`. I tried to also add zeroization for `Mnemonic` but was having trouble because I couldn't implement `Drop` due to the `into_phrase` method causing a move.

https://github.com/maciejhirsz/tiny-bip39/pull/20
