### ISSUE TITLE
API Content type header bug

### ISSUE THREAD

**Issue by mpetrunic** [sigp/lighthouse#1131]
## Description

Please provide a brief description of the issue.
If you send post request with header `'Content-Type': 'application/json;charset=utf-8'` to endpoint /validator/subscribe it will return bad request error with message:
> The provided content-type "application/json;charset=utf-8" is not available, this endpoint only supports json.

## Version

latest docker

## Present Behaviour

http error 400

## Expected Behaviour

http 200 OK

## Steps to resolve

Accept charset in content-type header and respect it.

**Comment by paulhauner** [comment]
Resolved via #1569
