### ISSUE TITLE
Remove `ActiveState` and `CrystallizedState`

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#115]
## Description

`types::ActiveState` and `types::CrystallizedState` have been deprecated in favor of `types::BeaconState` (see #113).

## Steps to resolve

- Remove both of these old types.
- Update any dependencies to use `BeaconState` instead.

**Comment by drozdziak1** [comment]
I'd be happy to hack on this, is #113 a blocker? What part of the spec would best give me context about how to hook stuff up together with `BeaconState`? (At first glance `BeaconState ≠ ActiveState + CrystallizedState` and I didn't read the whole spec yet)

**Comment by paulhauner** [comment]
Awesome. Let's wait on #126 and #114 for this one. They've cleared out a whole bunch of instances of the old states.

I should be able to get it out in the next few days. Dealing with some EoY and PM stuff presently.
