### ISSUE TITLE
Add testing for the account manager "deposit" command

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1161]
## Description

#1138 refactors the deposit submission code, placing it under the account manager as the `lighthouse account validator deposit` command.

It didn't previously have testing, but it should have some regardless.

To close this issue, add some integration tests that run the binary (like the other `/lighthouse/lighthouse/tests/account_manager.rs` tests) and check that functionality is as desired. The biggest obstacle here is getting access to an eth1 IPC in-process. We currently have the ability to spin up `ganache-cli` during testing, but AFAIK it only supports RPC via HTTP.

**Comment by b-m-f** [comment]
Does the IPC have to be genuine? Or can it be mocked?

**Comment by paulhauner** [comment]
Closing since we removed this command.
