### ISSUE TITLE
Consider caching eth1 votes as an optimisation

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1168]
## Description

As raised by @JustinDrake in #1093, a possible optimisation to the state transition could be to cache the count of `Eth1Data` votes so that an iteration over (up to) 1024 votes wouldn't be necessary every block. We _suspect_ this isn't actually a significant cost compared to the expensive operations like signing and hashing, but it's worth a look.

## Steps to resolve

1. Time the function `get_new_eth1_data` as a proportion of a block transition. If it's completed dominated by signing and hashing, come back here and close this issue.
2. If the time is significant, implement a cache that maps `Eth1Data` to the number of times it occurs in `state.eth1_data_votes`

**Comment by ethDreamer** [comment]
I can check this out this weekend. I'll time it with and without caching and see what happens.

**Comment by ethDreamer** [comment]
I've looked closer at this now and I'm working on timing the existing code. These are my initial thoughts:

I've been trying to interpret @michaelsproul statement:
> Time the function get_new_eth1_data as a proportion of a block transition

From the eth2.0 spec:
```
state_transition(..):             // renamed to do_transition?
    process_slots(..)             // renamed to per_slot_processing?
    verify_block_signature(..)    // this instead takes place inside process_block()
    process_block(..):            // renamed to per_block_processing?
        process_block_header()
        process_randao()
        process_eth1_data()       // <- this is what we're timing
        process_operations()
```
So are we timing this as a proportion of per_block_processing() or do_transition()?

I also noticed on @michaelsproul 's comment on #1093 about queued_deposits(). While queued_deposits() also calls process_eth1_data(), it looks like this is part of an unrelated codepath used by the validator which we are not timing?

I also found benchmarking code in consensus/state_processing/benches/per_epoch_processing/per_block_processing.rs

I'm not sure if you were thinking I'd use that or just find some manual way to time it. I'll keep digging either way and maybe the answers will turn up but any guidance is appreciated.

**Comment by ethDreamer** [comment]
So I just used std::time::Instant() and I timed all the lines inside [per_block_processing()](https://github.com/sigp/lighthouse/blob/master/consensus/state_processing/src/per_block_processing.rs#L80) as well as individually timing the call to [process_eth1_data()](https://github.com/sigp/lighthouse/blob/master/consensus/state_processing/src/per_block_processing.rs#L119). Then I blew away my beacon data_dir and started a resync and gathered timing on 100000 calls. It looks like **process_eth1_data()** is **less than 1%** of the time inside **per_block_processing()**.

  | per_block_processing() | process_eth1_data()
-- | -- | --
Median [μs] | 170 | 1
Average [μs] | 236.91781 | 1.92018

I did notice a small number of extreme cases where the runtime of **process_eth1_data()** was significantly longer than average for unknown reasons. 
process_eth1_data stats | count | percent
-- | -- | --
\>=10000 [μs] | 1 | 0.00%
\>=5000 [μs] | 2 | 0.00%
\>=1000 [μs] | 8 | 0.01%
\>=500 [μs] | 20 | 0.02%
\>=100 [μs] | 27 | 0.03%
\>=50 [μs] | 32 | 0.03%
\>=10 [μs] | 186 | 0.19%
\>=5 [μs] | 3714 | 3.71%
\>=4 [μs] | 8588 | 8.59%
\>=3 [μs] | 18746 | 18.75%
\>=2 [μs] | 40956 | 40.96%
\>=1 [μs] | 71964 | 71.96%
\>=0 [μs] | 100000 | 100.00%

If I've interpreted this issue correctly (meaning I've timed the right functions), it looks like caching would not provide a significant improvement here.

**Comment by JustinDrake** [comment]
> started a resync and gathered timing on 100000 calls

Thinking adversarially, the benchmarks should measure worst-case scenarios. That sync most likely doesn't capture the worst-case scenario.

**Comment by paulhauner** [comment]
> > started a resync and gathered timing on 100000 calls
> 
> Thinking adversarially, the benchmarks should measure worst-case scenarios. That sync most likely doesn't capture the worst-case scenario.

I think the worst-case could be achieved by:

- Define some arbitrary `Eth1Data`: `eth1_data`.
- Define some arbitrary `BeaconState`: `state`.
- Fill `state.eth1_data_votes` with copies of `eth1_data`.
- Call `process_eth1_data(state, eth1_data)`.

Also the case where `state.eth1_data_votes` is a list of random `Eth1Data` would be worth checking.

**Comment by paulhauner** [comment]
I'm going to close this one, it's pretty stale by this point and we never come across `process_eth1_data` when we're profiling.
