### ISSUE TITLE
Unable to open --base-dir: DirectoryDoesNotExist("/home/user/.lighthouse/wallets")

### ISSUE THREAD

**Issue by q9f** [sigp/lighthouse#1170]
## Description
Not specifying a wallet dir, defaults to a non existent directory and does not create it.

## Version
master @ ddd63c0de146133ce7877bee218710a2b41defd8

## Present Behaviour
```
~/.opt/sigp/lighthouse master*
❯ lighthouse account_manager validator create \
--at-most 32 \
--testnet-dir ~/.opt/goerli/witti/lighthouse \
--wallet-name "lh witti validators" \
--wallet-passphrase ~/.opt/goerli/witti/password.txt 
Unable to open --base-dir: DirectoryDoesNotExist("/home/user/.lighthouse/wallets")
```

## Expected Behaviour
It should either create the directory or ask the users to specify a valid path.

## Steps to resolve
`mkdir -p`

**Comment by q9f** [comment]
Hmmmm ....

```
~/.opt/sigp/lighthouse master*
❯ lighthouse account_manager validator create \
--at-most 32 \
--testnet-dir ~/.opt/goerli/witti/lighthouse \
--wallet-name "lh witti validators" \
--wallet-passphrase ~/.opt/goerli/witti/password.txt
Unable to open wallet: WalletNameUnknown("lh witti validators")
```

**Comment by q9f** [comment]
Maybe I should have consulted the documentation first, but it appears I have to create a "wallet" (whatever that is) before being able to create keypairs?

```
~/.opt/sigp/lighthouse master*
❯ lighthouse account_manager validator create \
--at-most 32 \
--testnet-dir ~/.opt/goerli/witti/lighthouse  
error: The following required arguments were not provided:
    --wallet-name <WALLET_NAME>
    --wallet-passphrase <WALLET_PASSWORD_PATH>

USAGE:
    lighthouse account_manager validator create --at-most <AT_MOST_VALIDATORS> --spec <TITLE> --testnet-dir <DIR> --wallet-name <WALLET_NAME> --wallet-passphrase <WALLET_PASSWORD_PATH>

For more information try --help
```

Impressive how much this changed in just 4 weeks. :D

**Comment by michaelsproul** [comment]
The wallet feature is very new, and we definitely have UX improvements to do! You probably found the docs about this, but for reference, the best source on the new HD wallets is:

https://lighthouse-book.sigmaprime.io/key-managment.html

**Comment by q9f** [comment]
Closing for now. I was just working through this backwards :)

Amazing how fast you squash new features.
