### ISSUE TITLE
Update the Development section on the book

### ISSUE THREAD

**Issue by divagant-martian** [sigp/lighthouse#1171]
## Description

The [development section on the book](https://lighthouse-book.sigmaprime.io/setup.html) could use some improvements. For instance:
- Refer to the [local testnet section](https://lighthouse-book.sigmaprime.io/local-testnets.html) or even move that one here.
- WRT to the local testnet, the development section refers to lighthouse's installation to ensure all deps are available, it would be good to describe how to achieve the same from source
- Related: `new-testnet` in the local testnet section is missing the required `--deposit-contract-address`
- Describe steps used to test different parts, for example list the sync sim
- There are probably some useful tools that you use to facilitate development, they could be listed here too (this may be too much but I leave that for your consideration)
- Include useful flags that you guys use: debug logs / flags for speed up / etc

**Comment by AgeManning** [comment]
Yep, I'll go through and do a full pass of the docs and run them. There's a few more features I want to get in, including setting up bootnodes without libp2p services.

**Comment by TAMustafa** [comment]
Under Raspberry Pi Key management (Section 4) the wallet name in the explanation doesn't match the name used in the code example. mywallet instead of wally?
![Screenshot 2020-06-14 at 08 21 21](https://user-images.githubusercontent.com/18684763/84586279-637ff600-ae18-11ea-9c6b-19f008a01933.png)

**Comment by paulhauner** [comment]
I'm closing this because the docs have been refactored since this issue was created.
