### ISSUE TITLE
Strip line endings from .pass files

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1175]
## Description

With the newly introduced HD wallets, we're often providing `.pass` files containing plaintext passwords on the CLI. Just now I generated one, edited it in Vim (adding a line ending), and found that it no longer worked: implying that if a user writes a password in a file manually, then the newline(s) will be considered part of the password! A somewhat counter-intuitive behaviour!

## Version

master @ `ddd63c0de146133ce7877bee218710a2b41defd8`

## Present Behaviour

Newlines are considered part of passwords read from `.pass` files.

## Expected Behaviour

Newlines (`\r`, `\n` or `\r\n`) at the end of the line should be stripped.

## Steps to resolve

Change the functions that read `.pass` files to strip newlines, and add some tests!

**Comment by roynalnaruto** [comment]
Hello @michaelsproul I have filed a [PR for this issue](https://github.com/sigp/lighthouse/pull/1199). Please review, thank you!
