### ISSUE TITLE
CORS headers on API

### ISSUE THREAD

**Issue by morrigan** [sigp/lighthouse#1177]
## Description

[CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) related headers are not customizable. Error when using API:

`Access to XMLHttpRequest at 'http://localhost:5052/beacon/validators' from origin 'http://localhost:2003' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

## Version

Docker image `sigp/lighthouse` 947bb6ea3cac

## Present Behaviour

App can't communicate with the HTTP API because of different URLs.

## Expected Behaviour

I can modify headers and pass `Access-Control-Allow-Origin`

**Comment by adaszko** [comment]
@morrigan Could you re-test using latest master and the new `--http-allow-origin` flag?

**Comment by paulhauner** [comment]
I've checked locally and I believe this was fixed in #1345
