### ISSUE TITLE
Cargo audit failing on rusqlite

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1194]
## Description

As raised by ToB in our review, `rusqlite` fails `cargo audit`. All it needs is a version bump and it will be fine again.

```
Error: Vulnerable crates found!

ID:       RUSTSEC-2020-0014
Crate:    rusqlite
Version:  0.22.0
Date:     2020-04-23
URL:      https://rustsec.org/advisories/RUSTSEC-2020-0014
Title:    Various memory safety issues
Solution:  upgrade to >= 0.23.0
```

This is currently blocking #1192.

**Comment by michaelsproul** [comment]
I'll fix this, I recall there being a versioning issue with `r2d2_sqlite` not supporting the latest `rusqlite`, but it looks like there was a new release 3 days ago.
