### ISSUE TITLE
Wallet directory defaults

### ISSUE THREAD

**Issue by protolambda** [sigp/lighthouse#1208]
## Description

The `account wallet create` command seems to ignore the global datadir option.

After trying different things and looking at help commands, and then reading through the source code, it turns out that the "datadir" option is not used. Even though it is repeated in every command help screen.

I needed the "base-dir" option under the account command.

## Version

`61496d8dad41525db95920737125c2942e07592c` (current master branch). Originally found on a merge of the ENR + health check PRs onto master. But all unrelated to the account cli work.

## Present Behaviour

`datadir` option is ignored, `base-dir` is only option for customization.

## Expected Behaviour

If this basedir is not specified, it should default to `{datadir}/wallets`, to adapt to the use of the custom datadir. Instead of going straight to `~/.lighthouse/wallets`. It's confusing to see it end up being used, even though the datadir was changed.

## Steps to resolve

Change the defaulting to use datadir option before completely falling back to the default (when base-dir is not specified)

**Comment by paulhauner** [comment]
I agree it's confusing. We need to reconsider the whole `datadir` concept IMO. #1006 also mentions this.

Next steps would be to create an RFC for clearly defining `datadir` and making sure its use is consistent.

**Comment by jburnett** [comment]
+1

I started from clean slate today, built from source (master @ commit 08e6b...), and followed book step 3 of _Start your beacon node_.

`~/s/g/s/lighthouse (master)> lighthouse beacon --eth1 --http
May 29 15:42:04.912 WARN Ethereum 2.0 is pre-release. This software is experimental.
May 29 15:42:04.912 INFO Using default testnet                   default: witti-v0-11-3
May 29 15:42:04.912 INFO Data directory initialised              datadir: /home/jb/.lighthouse
Failed to start beacon node: Unable to create /root/.lighthouse/beacon/chain_db: Permission denied (os error 13)
`
Note that output shows proper datadir (~/.lighthouse), but cmd fails on create dir at /root.

**Comment by paulhauner** [comment]
Closing this since the account manager now respects `--datadir` and `--base-dir` has been removed.
