### ISSUE TITLE
`vec_shuffle` test vectors are outdated

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#121]
## Description

The YAML test vectors for [utils/vec_shuffle](https://github.com/sigp/lighthouse/tree/master/beacon_chain/utils/vec_shuffle/src/specs) use blake2 instead of keccak.

## Steps to resolve

- Reach out on the gitter.im/ethereum/sharding gitter to find new test vectors.
- Implement test vectors.

If our code does not pass the tests, please raise a new issue.

**Comment by drozdziak1** [comment]
FYI started hacking on this

**Comment by drozdziak1** [comment]
@mratsim on ethereum/sharding pointed me to a repo containing this https://github.com/status-im/eth2-testgen/blob/master/test_vectors/test_vector_shuffling.yml, trying to hook it up with the `vec_shuffle` subcrate

**Comment by ralexstokes** [comment]
there is a test for this that is marked `#[should_panic]` when it should in fact not panic -- need to update for the new test vectors

**Comment by paulhauner** [comment]
Issue has been resolved :)
