### ISSUE TITLE
No log generated when validator fails to start

### ISSUE THREAD

**Issue by MysticRyuujin** [sigp/lighthouse#1231]
## Description

1. I have `--logfile` set
2. Validator fails to start
3. No log is generated

Even worse, I have 3 validators, one of the validators had a `.lock` file in the validator folder. When starting the client interactivly the console spit back:

```
Failed to init validator client: unable to decrypt all validator directories: ValidatorDirError(DirectoryLocked("/home/lighthouse/.lighthouse/validators/<validatorid>"))
```

Which means all 3 of my validators have been offline because 1 validator had a file lock on it. I had to run the client in an interactive console to know what was going on.

## Version
`Lighthouse 0.1.2`

## Present Behaviour

.lock file prevents all validators from starting. No log is generated.

## Expected Behaviour

I would expect the other 2 validators to still be brought online, and an error message for the failure. I'd also expect things that are displayed to the console interactively to also generate logs messages...

## Steps to resolve

Put a `.lock` file in a validator directory

**Comment by paulhauner** [comment]
Closing since we now log validator decryption failures and we provide the `--delete-lockfiles` flag to handle lingering lockfiles.
