### ISSUE TITLE
Filter out the Goobye RPC messages from the Behaviour emited events

### ISSUE THREAD

**Issue by divagant-martian** [sigp/lighthouse#1240]
## Description

If we get a Goodbye on the behaviour then we should request all rpc handlers to disconnect. With that we shouldn't need to propagate the Goodbye message. After the handlers have disconnected, we should get a ConnectionClosed Swarm event and with that send a "peer disconnected" event to the network

This is locked because making the handlers disconnect gracefully is a work in progress.

**Comment by AgeManning** [comment]
This looks closed to me.
