### ISSUE TITLE
Replace rust-crypto

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1245]
## Description

We're currently using `rust-crypto` in `eth2_key_derivation` and `eth2_keystore`. ToB pointed out that this is not maintained and that we should swap to something like https://github.com/RustCrypto/block-ciphers.

We've also seen another issue with `rust-crypto` in #1242.

## To resolve

Replace `rust-crypto` with https://github.com/RustCrypto/block-ciphers

**Comment by michaelsproul** [comment]
Tagged this for the Sept security review bc it seems relevant?

**Comment by divagant-martian** [comment]
Is this not already solved?

**Comment by paulhauner** [comment]
This was indeed already solved.
