### ISSUE TITLE
Make lambda API for head/wall-clock state

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1254]
## Description

In #1253 I noticed that several checks on single operations like voluntary exits and slashings require access to the wall clock state, which is constructed in a memory intensive way (cloned in the best case), used for a single check, and then discarded. A more efficient API would be something like:

```rust
beacon_chain.with_wall_clock_state(|state| { /* do stuff with state */ })
```

This could avoid cloning the state in the case where it's just the head ("most of the time").

Alternatively, this could be mitigated by reviving the [validator-tree-ethdenver](https://github.com/sigp/lighthouse/tree/validator-tree-ethdenver) branch that uses a design similar to Proto's remerkleable to make cloning states cheap and efficient. This would likely have other benefits IMO, but would be a more major undertaking.

**Comment by michaelsproul** [comment]
@paulhauner points out that this could be a security risk too, in that if there are network operations (like exits or slashings) which trigger intensive computation then that could be used to DoS the beacon node.

**Comment by paulhauner** [comment]
This function has been added here:

https://github.com/sigp/lighthouse/blob/9c9176c1d1c24de87e297aa4a90f9353dfab0405/beacon_node/beacon_chain/src/beacon_chain.rs#L496-L506
