### ISSUE TITLE
Rethink and test fork handling in op pool

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1255]
## Description

In #1253 I've revamped the fork handling for attester slashings so that it no longer requires the clunky `AttestationId` struct. The same could be done for attestations.

This issue isn't urgent, because any fork is some time away, but we should probably get it in before mainnet to avoid breaking changes to the op-pool on-disk format.

**Comment by paulhauner** [comment]
Hey @michaelsproul is this still relevant? :)

**Comment by paulhauner** [comment]
Following up @michaelsproul :)

**Comment by michaelsproul** [comment]
Sorry, this slipped through my notif filter.

I think this still relevant, but not high priority because I no longer think changing the on-disk format is such a terrible thing. We can always do a migration. I'm in favour of bumping this change to A1/post-mainnet.

**Comment by michaelsproul** [comment]
Closing this as stale. Our op-pool is now fork-aware.
