### ISSUE TITLE
Document Prometheus port in lighthouse-book

### ISSUE THREAD

**Issue by OisinKyne** [sigp/lighthouse#1256]
## Description

Hey guys, maybe a small bit of feedback on your docs. I struggled to figure out what port prometheus runs on for lighthouse.

At first, I couldn't find any reference to it in lighthouse-book.sigmaprime.io, and assumed to monitor lighthouse I would use the REST API.

Then I spotted it was mentioned in the readme as `Metrics via Prometheus.`. I also spotted it mentioned here: https://hub.docker.com/r/paulhauner/lighthouse and here https://github.com/sigp/lighthouse/pull/1197 So I knew it existed somewhere. I eventually figured out it runs on `:5052/metrics`  by looking at the docker-compose file in this repo. https://github.com/sigp/lighthouse-docker/blob/master/docker-compose.yml#L11

## Version

Docker `sigp/lighthouse:latest` with ID `7076af925f61`

## Present Behaviour

App works fine

## Expected Behaviour

Maybe just a mention of the default metrics port here https://lighthouse-book.sigmaprime.io/docker.html would work. Other clients allow you to specify a metrics port via CLI flag, but I don't particularly need that feature. 

## Steps to resolve

Just a bit of documentation :)

**Comment by paulhauner** [comment]
Resolved via #1569
