### ISSUE TITLE
New '/system' Rest endpoint + Socket Events

### ISSUE THREAD

**Issue by danielharrison** [sigp/lighthouse#1260]
## Problem

In order to confgure the the lighthouse client, the lighthouse front-end will require system information about the host machine which the lighthouse client is running on.

### Solution

Add a new endpoint (/system?) for providing information for the host machine, such as drives, space available, CPU, memory usage, network stats etc

Also provide a socket event as system info changes.

### REST Endpoints

/system/drives: List drives available including full paths, names etc
/system/stats: List all machine stats (CPU, memory, network etc)
/system: all above

### Socket Events

system_stats: Current machine stats (as above)

**Comment by danielharrison** [comment]
Potential packages to use: 

https://github.com/GuillaumeGomez/sysinfo
https://github.com/myfreeweb/systemstat

**Comment by paulhauner** [comment]
I'm closing this since it's pretty stale. We'll cover these requirements in the next round of the UI.
