### ISSUE TITLE
Update web3 to remove duplicate deps

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1264]
## Description

I started investigating crates with multiple versions present in our dep graph using [`cargo deny`](https://github.com/EmbarkStudios/cargo-deny), and found that our dependency on `web3` v0.11.0 is a source of many duplicated versions, including `tokio`, `hyper` (x2!) and `url`. An excerpt from the condensed dep graph for `tokio` is shown here:

![](https://i.imgur.com/7bcL2Be.png)

@AgeManning and @pawanjay176 may have known about this already from their quest to upgrade all ours deps to `std::future::Future`, but I figured I'd open this issue because it accounted for the majority of the 40 multiple-version crates in our dep graph.

It looks like this recent PR to `web3` https://github.com/tomusdrw/rust-web3/pull/351 will solve this perfectly! :star_struck:

**Comment by AgeManning** [comment]
Yeah, web3 was a huge killer in the dep upgrade

**Comment by michaelsproul** [comment]
I'm taking this

**Comment by michaelsproul** [comment]
Blocking this issue on the lack of IPC support in web3 v0.12.0

**Comment by michaelsproul** [comment]
I'm looking at crate duplication and compile time again, and `web3` is right there in the centre of everything causing trouble.

What if we axed IPC support? We mostly (only?) used it for Lighthouse's deposit functionality, which has now been removed in favour of the launchpad :thinking:

**Comment by michaelsproul** [comment]
This looks super feasible now actually. It seems web3 is only used for tests now :tada: But that means we can swap it out and improve our test compilation time

**Comment by michaelsproul** [comment]
Tracking IPC support in this issue: https://github.com/sigp/lighthouse/issues/1049
