### ISSUE TITLE
Can't find peers

### ISSUE THREAD

**Issue by lochuan** [sigp/lighthouse#1271]
The log shows some weird issue.

`Jun 16 09:38:15.787 DEBG Peer not known at dialed address        error: Pending connection: Transport error: Timeout has been reached, address: /ip4/176.9.51.216/tcp/13000, service: libp2p
Jun 16 09:38:15.787 DEBG Peer not known at dialed address        error: Pending connection: Transport error: Timeout has been reached, address: /ip4/176.9.51.216/tcp/9000, service: libp2p
Jun 16 09:38:15.788 DEBG Peer not known at dialed address        error: Pending connection: Transport error: Timeout has been reached, address: /ip4/176.9.51.216/tcp/30000, service: libp2p`

I've tried ping 176.9.51.216, all the ping requests fall in timeout. 

BTW, I'm located in China, Is it a firewall(GFW) problem?

**Comment by lochuan** [comment]
Addition: I also set up a Prysm beacon node, that one just works fine.

**Comment by q9f** [comment]
> I've tried ping 176.9.51.216, all the ping requests fall in timeout.

```
❯ ping -c3 176.9.51.216
PING 176.9.51.216 (176.9.51.216) 56(84) bytes of data.
64 bytes from 176.9.51.216: icmp_seq=1 ttl=54 time=13.2 ms
64 bytes from 176.9.51.216: icmp_seq=2 ttl=54 time=13.1 ms
64 bytes from 176.9.51.216: icmp_seq=3 ttl=54 time=13.2 ms

--- 176.9.51.216 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 13.093/13.189/13.245/0.068 ms
```

It must be a networking issue. Maybe it's the GFW?

**Comment by AgeManning** [comment]
This looks like a firewall issue. 

We require initial connections to bootnodes in order to bootstrap discovery to then find peers. If you cannot connect to the initial bootnodes you will not be able to find more nodes. 

I think potentially prysm may also use relay nodes in addition to the bootnodes? But I'm not sure. It's strange that a prysm node would work. What ports are the prysm nodes using?

**Comment by lochuan** [comment]
Prysm is using 13000.

Here is a log output:
INFO p2p: Peer Connected activePeers=33 direction=Outbound multiAddr=/ip4/3.19.237.5/tcp/13000/p2p/16Uiu2HAmNbf7hjzRxNZH8cDqLZycZ3H5nNzc9nksz1ciUuqU71FD peer=16Uiu2HAmNbf7hjzRxNZH8cDqLZycZ3H5nNzc9nksz1ciUuqU71FD

I've checked the Prysm's bootnodes config, it points to the same address as Lighthouse.

So wonder about why Prysm just working...

**Comment by lochuan** [comment]
> > I've tried ping 176.9.51.216, all the ping requests fall in timeout.
> 
> ```
> ❯ ping -c3 176.9.51.216
> PING 176.9.51.216 (176.9.51.216) 56(84) bytes of data.
> 64 bytes from 176.9.51.216: icmp_seq=1 ttl=54 time=13.2 ms
> 64 bytes from 176.9.51.216: icmp_seq=2 ttl=54 time=13.1 ms
> 64 bytes from 176.9.51.216: icmp_seq=3 ttl=54 time=13.2 ms
> 
> --- 176.9.51.216 ping statistics ---
> 3 packets transmitted, 3 received, 0% packet loss, time 2003ms
> rtt min/avg/max/mdev = 13.093/13.189/13.245/0.068 ms
> ```
> 
> It must be a networking issue. Maybe it's the GFW?

@q9f Prysm uses the same bootstrap address, but Prysm just works fine. That's weried.

**Comment by q9f** [comment]
> @q9f Prysm uses the same bootstrap address, but Prysm just works fine. That's weried.

Funny, I have the exact opposite issue.

https://github.com/prysmaticlabs/prysm/issues/6280

**Comment by AgeManning** [comment]
For some reason maybe the bootnodes are blocked from where you are. 

In lighthouse we store past nodes and repopulate the local routing table. If you are running lighthouse for the first time, it needs to bootnodes to bootstrap the routing table. 

Perhaps you've run prysm before but this is the first run of lighthouse? 

Have you tried removing the data directory of lighthouse and prysm and start them both from scratch? 

I'm quite curious if Prysm are doing something here that we are not that enables greater connectivity.

**Comment by AgeManning** [comment]
I'm going to consider this closed to either local set up or external firewall.
