### ISSUE TITLE
Discovery query grouping

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1281]
## Description

Discovery queries are computationally expensive and rather time consuming. The timeout for a query is currently set to 30 seconds. For large DHT's consisting of peer's that don't belong on our Eth2 chain/fork queries can take a couple of minutes to complete. 

When a validator client is attached to a beacon node, it requires the beacon node to search for peers for a subnet when required to perform specific duties. When many validators are connected to one node, the BN (beacon node) may need to perform many discovery queries. 

Lighthouse can run con-current queries, however we limit these to conserve resources. The current implementation sets a constant: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/discovery/mod.rs#L43
which indicates the number of concurrent queries. This will likely be set to 2 in the near future. 

This means that many subnet queries will queue before being processed. They queue in here: 
https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/discovery/mod.rs#L140
And get added when required here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/discovery/mod.rs#L241

The queue gets processed here: 
https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/discovery/mod.rs#L402

Ideally we should be smarter about processing subnet queries. If for example a query for subnet 1 and 3 were queued,  it doesn't make sense to search for peers for subnet 1 for 30 seconds then search for peers for subnet 3 (assuming a concurrency parameter of 1). Ideally we should group the queries, so that we do a single search for peers on either subnet 3 or subnet 1.

Currently, a query is re-inserted into the queue if sufficient peers are not found. Also queries search for a minimum number of peers. When grouping we need to increase the number of target peers to discover. But this can be ad-hoc because we cannot be certain which peers for which subnet will be returned. 

I think we should have a fixed constant of 6 peers as a target for a grouped query and we only group at most 3 queries. This should keep the query relatively fast (as it only needs to find 6 peers). Once the grouped query returns, if we find sufficient peers for one subnet but not another, we should re-queue the query's that are still required. 

This involves maintaining the min_ttl for each subnet. I guess this can be done by expanding the QueryType enum to include a GroupedQuery which maintains the min_ttl for each subnet.

**Comment by realbigsean** [comment]
I can work on this 👍

**Comment by AgeManning** [comment]
Resolved in #1364
