### ISSUE TITLE
Thread local sync network context

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1289]
## Description

Sync and range sync has a local `NetworkContext` which keeps track of the request Id for all sync requests. Currently this is passed as a parameter through many functions throughout the range sync. 

It would be cleaner to add the network context into the thread local storage with `thread_local`. This would save passing a reference around everywhere.

**Comment by ethDreamer** [comment]
i'll take a look at this

**Comment by AgeManning** [comment]
Oh yeah cool. This one just seems like it would be nicer having some of these variables stored in thread local. 

Let me know if you run into any issues or need further clarification

**Comment by ethDreamer** [comment]
I had some time to look into this but not enough to write a solution. I'm going on a vacation for 2 weeks so if someone wants to take this from me that's fine. Otherwise I'll resume work when I'm back :)

**Comment by paulhauner** [comment]
It this still relevant @agemanning? :)

**Comment by AgeManning** [comment]
Kind of. 

A lot of the code has changed. If @divagant-martian thinks this is a good idea, I think we should keep it. If she thinks its irrelevant, I think we should close.

**Comment by divagant-martian** [comment]
I don't think we need it for now
