### ISSUE TITLE
Fix restrictions on VC lockfiles and slashing protection

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1313]
## Description

Using ctrl+c on the VC before the `ProductionValidatorClient::new_from_cli` function has completed causes `ValidatorDir` lockfiles to linger. This is because `Drop` is not being called.

I'm going to add a hot-patch around this for Altona that allows for ignoring locked validator directories. This should be fine for mainnet, however it's not great for mainnet.

Once this issue is fixed, we should reconsider the `--strict` flag in the VC again.

**Comment by michaelsproul** [comment]
This is still relevant isn't it? Ctrl-Cing does leave lock files lying around and we still get warnings about them.

I'm also keen to get back something like `--strict`, in conjunction with https://github.com/sigp/lighthouse/issues/1584

**Comment by paulhauner** [comment]
> This is still relevant isn't it? Ctrl-Cing does leave lock files lying around and we still get warnings about them.
> 
> I'm also keen to get back something like `--strict`, in conjunction with #1584

Yeah sorry, I have another issue drafted but I got distracted trying to solve it. I'll get to it.

**Comment by paulhauner** [comment]
Resolved in #1586
