### ISSUE TITLE
Prevent double sending deposit tx if response was not received from eth1 node

### ISSUE THREAD

**Issue by ethDreamer** [sigp/lighthouse#1329]
## Description
Under most circumstances, when a deposit transaction is sent to an eth1 node (either via IPC or RPC), the node responds immediately with either an error or the tx hash. This is NOT true when the tx is signed with a hardware wallet; the node has to wait for the user to confirm.

When Altona launched, I used my ledger to sign the deposit transactions that lighthouse sent to my geth node. After confirming the first successful transaction with my ledger, I hit ctrl+c to stop lighthouse. BUT I didn't realize that lighthouse had received the first successful response from geth and sent a second transaction before I hit ctrl+c.

After I stopped lighthouse, my ledger was sitting on the confirm screen, and I confirmed the second transaction without realizing it.

Then the next time I ran the deposit subcommand, lighthouse re-sent the deposit transaction for that validator because it never received the successful response from geth.

This was the result:
https://altona.beaconcha.in/validator/1014#deposits

## Present Behaviour

Lighthouse doesn't remember that it sent a deposit tx and didn't record a response, so it'll just send another one :/

## Expected Behaviour

Should use a trap file and alert the user to check that the tx wasn't confirmed and remove it before sending another one.

**Comment by paulhauner** [comment]
Closing this since we removed the `lighthouse account validator deposit` command.
