### ISSUE TITLE
Domain-specific types

### ISSUE THREAD

**Issue by ralexstokes** [sigp/lighthouse#135]
Saw this in some code and got to thinking about crafting some domain specific types

```rust
/// The size of a validators deposit in GWei.
pub const DEPOSIT_GWEI: u64 = 32_000_000_000;
```

We can do something like
```rust
struct GWei(u64);
```

to get type-safety where we know we want units of Gwei.

The downside is ergonomics as now we either need to implement some number of traits (e.g. `std::ops::{Add,...}` or have a bunch of manual wrapping/unwrapping to do...

Figured I would bring this up for discussion...

**Comment by drozdziak1** [comment]
I say those should be macros, imagine all the code for all the math operations, and all that for a measly newtype.

**Comment by drozdziak1** [comment]
BTW What's the preferred 256-bit type we're going to use?

**Comment by paulhauner** [comment]
> BTW What's the preferred 256-bit type we're going to use?

The `ethereum-types` [U256](https://docs.rs/ethereum-types/0.4.0/ethereum_types/struct.U256.html), unless there are any objections.

> I say those should be macros, imagine all the code for all the math operations, and all that for a measly newtype.

The [num_derive](https://docs.rs/num-derive/0.2.3/num_derive/) library might be useful here. It gives things like `#derive(num_ops)` for newtypes (the inner type must already implement NumOps).

I haven't used it though, so I can't speak for it's quality.

**Comment by paulhauner** [comment]
Closing this in favor of #181.

We can address further newtypes as we go.
