### ISSUE TITLE
The --validator argument for the deposit subcommand is very difficult to use

### ISSUE THREAD

**Issue by ethDreamer** [sigp/lighthouse#1352]
## Description
When running the deposit subcommand, essentially the only valid value the user can pass to the --validator flag is "all".  The argument is supposed to let you specify which validator directory you want to use, but it currently requires an exact match.  What's worse, the string it tries to match against is very counter-intuitive.

## Version
master

## Present Behaviour
Here's two examples of what you'd need to match exactly (everything inside the []):

[\"/home/eth2/.lighthouse/validators/0xb4677e17fda50d24ce12941e4e44cbd6d7e346b52d83ff73ba396917f7c550ed090aa496ca9419edf3b362313beefd38\"]
[\"/home/eth2/.lighthouse/validators/0xa0235daaf12e2fd7313db413417816af3141705c9de22419399a8be0b6fa4bbe3e7836954f97003fdf166830f3e8b735\"]

So you you'd have to specify the fully expanded path, wrapped in quote characters.

## Expected Behaviour

You should really only need to specify a slice of the validator public key.

**Comment by paulhauner** [comment]
Fixed in #1332
