### ISSUE TITLE
Replace --slots-per-restore-point with --restore-points-per-historical-batch

### ISSUE THREAD

**Issue by adaszko** [sigp/lighthouse#1355]
## Description

CLI ergonomics could be improved by renaming `--slots-per-restore-point` to `--restore-points-per-historical-batch` and making it take only power of two arguments.  That way, higher value corresponds to more disk space consumed, and conversely, lower value to less disk space.  So the two are correlated.  Currently, with `--slots-per-restore-point`, there's negative correlation and the option is harder to parse mentally.

**Comment by michaelsproul** [comment]
Closing, as there are already docs about slots-per-restore-point (https://lighthouse-book.sigmaprime.io/advanced_database.html), and users seem to be accustomed to the concept now, so changing it offers little benefit.
