### ISSUE TITLE
What are the reasons for licensing under GPL?

### ISSUE THREAD

**Issue by chronaeon** [sigp/lighthouse#136]
## Description

Lighthouse is focusing on modularity, but if someone wants to include a Lighthouse module in their codebase, they are required to share the entire codebase. While this seems to work in favor of open source, enterprises and other commercial entities _will tend to not use Lighthouse_ because they won't see it worth the risk of sharing all of their code. This is a significant trade-off and should not be undertaken lightly. 

CPP Ethereum died because of this, because they couldn't get one of the authors to sign off on the re-license (away from GPL). The EEA would effectively not need to exist today if CPP-Ethereum had been successfully re-licensed in early 2017, as was attempted.

**Comment by chronaeon** [comment]
I can't speak for the EEA, I can only speak as someone who stood by and witnessed certain events. I have no idea if they'd want to use Lighthouse or not, and I'll leave that up to them. I was just using the situation of the GPL licensing debacle on CPP-Ethereum (which spawned the EEA) as an example of how copyleft can work against itself. 

Also I'm using it as a basis for deciding whether I want to contribute to Lighthouse or not. I really like the approach your team is taking in general (notwithstanding the licensing,) and before I give my support and volunteer time to improve an open-source project, I try to make sure my values line up with the the team's values so I don't waste their time or mine.

I think I have my answer, so unless you want to discuss further, feel free to close this. :)

**Comment by paulhauner** [comment]
Hey, sorry I missed this! I remember it showing up in a notification once but I couldn't find it! I was looking for it in eth2.0-specs as I saw Preston's name with it!

I stumbled across it by typing in the wrong URL, lucky!

Thanks for the response @prestonvanloon :)

@chronaeon, switching the lighthouse license has crossed my mind actually. We (foolishly) added GPL without much thought, before we'd established that the project was going anywhere.

Keen to hear the events you witnessed and a good reason to swap licenses before we obtain so many contributors it's infeasible.

**Comment by chronaeon** [comment]
No prob :)

After describing the events to prestonvanloon I realized it probably wasn't the best topic to put as an issue, since licensing debates can get dicey and cause divisions. Do you mind if we continue on a telegram chat?

**Comment by chronaeon** [comment]
@paulhauner I found your name in the ETH security group so I'll PM you

**Comment by prestonvanloon** [comment]
@chronaeon @paulhauner if you all have some compelling reasons to change from GPL, I'd love to hear them! I'm @prestonvanloon on telegram, if you'd like my input as well (no problem if not).

**Comment by AgeManning** [comment]
We are re-licencing in #326
