### ISSUE TITLE
Document TOML Config?

### ISSUE THREAD

**Issue by MysticRyuujin** [sigp/lighthouse#1363]
## Description

Currently there is no documentation about the TOML config file, or how to use it (assuming I can?). There is #905 that suggests that I can use a TOML config file (and optionally overwrite the values on the CLI). However, there's no indication that I can specify a config file from a CLI flag, and there's no documentation on how I might maintain one, especially in a docker image.

The primary reason that I'd choose to use a TOML file over CLI flags is that I can mount a TOML file or overwrite a TOML file outside of the docker container, then updating values becomes as simple as restarting the container, as opposed to trying to modify the CLI flags at launch or modifying ENV variables, etc.

## Version

Please provide your Lighthouse and Rust version. Are you building from
`master`, which commit?

`670672265e59`

## Present Behaviour

A TOML config seems to be used / usable but is completely undocumented

Actually, after poking around in the docker file system, now I'm not even sure if the toml file gets generated, or is used, even if placed into 'standard' directories...

## Expected Behaviour

I would expect this to be documented I guess.

## Steps to resolve

Document the use of the TOML config file, or allow me to pass one explicitly with a CLI flag?

**Comment by paulhauner** [comment]
Thanks for raising the issue @MysticRyuujin.

Unfortunately we deprecated the `beacon_node.toml` configuration file some weeks ago since it seemed to be causing more issues than it solved.

Perhaps the one you can see is lingering from an older version of Lighthouse?

I'll close this issue for now, feel free to open it if you're not satisfied :)
