### ISSUE TITLE
Downscore peers during gossip validation

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1386]
## Description

There are a number of validation criteria for blocks and attestations. 

Messages from the network hit the router and get validated by the beacon chain. The differing results from invalid messages should result in down-scoring the peer that sent us the message. 

There are varying degrees of scoring. We currently have a set of `PeerAction`'s (https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/peer_manager/score.rs#L35) which we should map to various validation results. 

See the error types here: https://github.com/sigp/lighthouse/blob/master/beacon_node/beacon_chain/src/attestation_verification.rs#L66
and here:
https://github.com/sigp/lighthouse/blob/master/beacon_node/beacon_chain/src/block_verification.rs#L86

@paulhauner might be interested in having a first pass at mapping these types, potentially we may need to add more PeerActions.

EDIT: Seems the attestations errors have already been mapped nicely here: https://github.com/sigp/lighthouse/blob/3c4daec9af993f3a9416c6b3141f2c9689c71418/beacon_node/network/src/router/processor.rs#L604-L793

**Comment by AgeManning** [comment]
Also we need to report these down to gossipsub 1.1 once built as per the specs here: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#global-topics

**Comment by paulhauner** [comment]
@AgeManning is this issue still relevant?

**Comment by AgeManning** [comment]
Yes. I'll clean up this misc issues today

**Comment by AgeManning** [comment]
Resolved in #1386
