### ISSUE TITLE
Fix incorrect end_after_checks flag to simulators

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1387]
## Description

As raised here https://github.com/sigp/lighthouse/pull/1385#discussion_r459239305 the `end_after_checks` flag to the simulator binaries is wrongly named.

## Steps to resolve

- Rename the flag to `continue_after_checks` (default `false` if not present)

**Comment by tobisako** [comment]
Hi, I'm beginner. May I work on this?

**Comment by michaelsproul** [comment]
@tobisako go for it! Let me know if you need help!

**Comment by tobisako** [comment]
@michaelsproul oh, yes. thank you! I'll try this.

**Comment by tobisako** [comment]
@michaelsproul hi. I have a question.

**(cli parameter) continue_after_checks (default false)**
a `./simulator eth1-sim`(not set)  -> **false (default)**
b `./simulator eth1-sim --continue_after_checks`(not value)  -> **true? false? or panic?**
c `./simulator eth1-sim --continue_after_checks=false`  -> **false**
d `./simulator eth1-sim --continue_after_checks=true`  -> **true**
e `./simulator eth1-sim --continue_after_checks=true2`  -> **panic!(normal)**

i don't understand this parameter case 'b'.
I think 'b' is default=false, but I think It's not natural. I feel.

**(reference) speed_up_factor (default 4)**
2a `./simulator eth1-sim`(not set) -> **4 (default)**
2b `./simulator eth1-sim --speed_up_factor`(not value)  -> **4 (default)**
2c `./simulator eth1-sim --speed_up_factor=5`  -> **5**
2d `./simulator eth1-sim --speed_up_factor=5b`  -> **panic!(normal)**

If this is a confusing explanation, I'm sorry. 
or this my question is another issue?
please help me.

**Comment by michaelsproul** [comment]
Hey @tobisako, I agree in the (b) case we should set it to `true`. My comment was referring to the (a) case (i.e. default to false when the flag is not provided at all).

**Comment by tobisako** [comment]
@michaelsproul ok, I understood! thank you.

**Comment by tobisako** [comment]
@michaelsproul hi. I'll check clap-spec, and I knew I was wrong. 
the (b) case isn't set it up by clap.

ideal (myself) -> I have no idea to implement with clap.
a `./simulator eth1-sim`(not set)  -> **false (default)**
b `./simulator eth1-sim --continue_after_checks`(not value)  -> **false** <- no idea
c `./simulator eth1-sim --continue_after_checks=false`  -> **false**
d `./simulator eth1-sim --continue_after_checks=true`  -> **true**
e `./simulator eth1-sim --continue_after_checks=true2`  -> **panic!(normal)**

I'm sent Discussions clap-2112
https://github.com/clap-rs/clap/discussions/2112

get off track.

this is other issue
I can implement 2 pattern.

pattern 1 ( takes_value(false) )
a `./simulator eth1-sim`(not set)  -> **false (default)**
b `./simulator eth1-sim --continue_after_checks`(not value)  -> **true**
c `./simulator eth1-sim --continue_after_checks false`  -> **clap error detect**
d `./simulator eth1-sim --continue_after_checks true`  -> **clap error detect**
e `./simulator eth1-sim --continue_after_checks true2`  -> **clap error detect**

pattern 2 (takes_value(true) )
a `./simulator eth1-sim`(not set)  -> **false (default)**
b `./simulator eth1-sim --continue_after_checks`(not value)  -> **clap error detect**
c `./simulator eth1-sim --continue_after_checks false`  -> **false**
d `./simulator eth1-sim --continue_after_checks true`  -> **true**
e `./simulator eth1-sim --continue_after_checks true2`  -> **panic!(normal)**

I think I'll implement pattern 1. thank you.
