### ISSUE TITLE
boot_node peer added to routing table but never dialled

### ISSUE THREAD

**Issue by acequicksilver** [sigp/lighthouse#1389]
## Description

boot_node added to beacon_node start-up option is never dialled but appears in the trace logs on startup with the message DEBG Adding node to routing table 

## Version

Lighthouse version: Lighthouse/v0.1.2-unstable/x86_64-linux
Rust 1.4.4
master, commit: 23a8f31f839ca457b97ee32932555500ec019a3e

## Present Behaviour

Added boot_node is never dialled.

## Expected Behaviour

All boot_node ENRs should be dialled.

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by pawanjay176** [comment]
@acequicksilver the bootnodes are dialed only if they have a tcp address, otherwise, they just participate in the peer discovery process and need not be dialed by libp2p.

**Comment by acequicksilver** [comment]
ok thanks, is it possible to set a tcp address for a lighthouse boot_node?

**Comment by AgeManning** [comment]
If you are using the `boot_node` CLI param. No. 

The idea of the boot-node is to simply run a discv5 server at not a full-blown lighthouse node. This way, all new peers will not try and sync from this one single boot_node, rather they will discover more peers randomly from the boot_node and start their sync in a more uniform distribution from the peer list. This prevents boot_nodes from being overloaded with RPC requests. 

If you want to run a "boot_node" that is also a ligthouse node (i.e has tcp and responds to RPC requests and gossip etc). You can run a regular lighthouse node with the `--enr-address` and `--enr-port` beacon node flags. Then use the resulting ENR as your "boot_node" (this will contain a TCP port) and newly connected nodes will connect to it.

**Comment by divagant-martian** [comment]
I think this is answered. Closing
