### ISSUE TITLE
Track gossip peers per topic

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1399]
## Description

Use the gossipsub subscription and unsubscription events to keep track of which peers are subscribed to which topic. 

Then build a HTTP API endpoint that collects number of peers per topic and include it as a metric in grafana. This will be nice to visually understand how connected we are to the attestation subnets at any given point in time. 

It will also make it easier for us to diagnose issues with discovering and connecting to peers on subnets and verify our attestation inclusion rate into blocks.

**Comment by divagant-martian** [comment]
I'll take it

**Comment by divagant-martian** [comment]
Closed by #1445
