### ISSUE TITLE
Make command gives Error 101

### ISSUE THREAD

**Issue by lidachao111222** [sigp/lighthouse#1407]
When running the make command within the Lighthouse folder (step 3 in the detailed instruction),
I get errors after it has succesfully compiled a few repositories.

The error stack trace looks like this within the console:

c@MacBook-Pro lighthouse % make
cargo install --path lighthouse --force --locked
  Installing lighthouse v0.1.2 (/Users/c/Desktop/lighthouse/lighthouse)
    Updating crates.io index
   Compiling eth2_testnet_config v0.2.0 (/Users/c/Desktop/lighthouse/common/eth2_testnet_config)
   Compiling deposit_contract v0.2.0 (/Users/c/Desktop/lighthouse/common/deposit_contract)
   Compiling remote_beacon_node v0.2.0 (/Users/c/Desktop/lighthouse/common/remote_beacon_node)
error: failed to run custom build command for `eth2_testnet_config v0.2.0 (/Users/c/Desktop/lighthouse/common/eth2_testnet_config)`

Caused by:
  process didn't exit successfully: `/Users/c/Desktop/lighthouse/target/release/build/eth2_testnet_config-a9a8daec41be83c6/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to download boot_enr.yaml: error sending request for url (https://raw.githubusercontent.com/sigp/witti/a94e00c1a03df851f960fcf44a79f2a6b1d29af1/altona/lighthouse/boot_enr.yaml): error trying to connect: tcp connect error: Connection refused (os error 61)', common/eth2_testnet_config/build.rs:23:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: failed to compile `lighthouse v0.1.2 (/Users/c/Desktop/lighthouse/lighthouse)`, intermediate artifacts can be found at `/Users/c/Desktop/lighthouse/target`

Caused by:
  build failed
make: *** [install] Error 101

Thanks for helping

**Comment by pawanjay176** [comment]
Looks like you might have had internet issues while running `make`. Could you please try once again? 
If it still doesn't work, it could be a firewall issue. Try visiting the url above and see if you can access it. (https://raw.githubusercontent.com/sigp/witti/a94e00c1a03df851f960fcf44a79f2a6b1d29af1/altona/lighthouse/boot_enr.yaml)

Also, are you running latest master branch?

**Comment by lidachao111222** [comment]
@pawanjay176  Thanks for reply, pawanjay176. I redownload the master branch, but the error still there. The weird thing is I can visit the https://raw.githubusercontent.com/sigp/witti/a94e00c1a03df851f960fcf44a79f2a6b1d29af1/altona/lighthouse/boot_enr.yaml. lol
