### ISSUE TITLE
Launchpad import does not work

### ISSUE THREAD

**Issue by l-hendriks** [sigp/lighthouse#1408]
## Description

I'm creating a validator from the Medalla launchpad page (https://medalla.launchpad.ethereum.org/lighthouse). After following all instructions, the lighthouse client crashes on this command:

`lighthouse account validator import --directory eth2.0-deposit-cli/validator_keys`

with the following error:

`error: Found argument 'import' which wasn't expected, or isn't valid in this context`

This is probably because the launchpad branch is not (yet) merged in master. If I check out to launchpad and build there, it works. However, when I run

`lighthouse vc`

I get the following error:

`Failed to init validator client: Unable to initialize config: The directory for validator passwords (--secrets-dir) does not exist: "/home/X/.lighthouse/secrets"`. After creating the folder it works.

I would expect that the manual works, instead of giving error when following the steps.

Additionally, the troubleshooting page does not exist (https://lighthouse-book.sigmaprime.io/validator-import-launchpad.html)

## Version

Installed Rust and Lighthouse from scratch. Master commit #9ae9df8

**Comment by michaelsproul** [comment]
Thanks for the bug report! We'll get to this tomorrow in https://github.com/sigp/lighthouse/pull/1381, and get that merged to `master` to minimise confusion

**Comment by michaelsproul** [comment]
Closed by #1381! :tada:

**Comment by MaxXor** [comment]
@michaelsproul I'm also building lighthouse from source using the latest commit from the master branch. But it's still showing:
> error: Found argument 'import' which wasn't expected, or isn't valid in this context

**Comment by michaelsproul** [comment]
Leaving this closed as I saw @MaxXor's issue was resolved on Discord
