### ISSUE TITLE
http service does not start despite --http flag

### ISSUE THREAD

**Issue by timjp87** [sigp/lighthouse#1409]
## Description

When I try to start the beacon chain with the REST API Endpoint enabled (--http) there is no mention in the logs that it's serving the http service via a specific port. Running a validator in parallel does not work as it complains that it's getting connection refused from http://localhost:5052/node/version.

## Version

I'm building from the medalla branch (7cf3c4fd8ba55da39e11f3e7dcd36abd95ef1147) on Arch Linux aarch64.
Rust version 1.45.0

## Present Behaviour

This is the startup message:

alarm@atlas01 ~/lighthouse (git)-[medalla] % lighthouse bn --http
Jul 28 17:17:04.900 WARN Ethereum 2.0 is pre-release. This software is experimental.
Jul 28 17:17:04.900 INFO Using default testnet                   default: medalla.beta.0
Jul 28 17:17:04.900 INFO Data directory initialised              datadir: /home/alarm/.lighthouse
Jul 28 17:17:04.934 INFO Waiting for eth2 genesis from eth1      deposit_contract: 0x07b39f4fde4a38bace212b546dac87c58dfe3fdc, contract_deploy_block: 3085928, eth1_endpoint: http://localhost:8545, service: beacon
Jul 28 17:17:04.934 INFO Importing eth1 deposit logs             service: beacon
Jul 28 17:17:05.273 INFO Imported deposit log(s)                 new: 2, total: 2, latest_block: 3086579, service: beacon
Jul 28 17:17:05.274 INFO Waiting for more deposits               valid_deposits: 0, total_deposits: 2, min_genesis_active_validators: 16384, service: beacon
Jul 28 17:17:12.599 INFO Imported deposit log(s)                 new: 2, total: 4, latest_block: 3094731, service: beacon
Jul 28 17:17:12.600 INFO Waiting for more deposits               valid_deposits: 1, total_deposits: 4, min_genesis_active_validators: 16384, service: beacon
Jul 28 17:17:33.769 INFO Imported deposit log(s)                 new: 1035, total: 1039, latest_block: 3100400, service: beacon
Jul 28 17:17:33.770 INFO Waiting for more deposits               valid_deposits: 1031, total_deposits: 1039, min_genesis_active_validators: 16384, service: beacon
Jul 28 17:18:23.610 INFO Imported deposit log(s)                 new: 3179, total: 4218, latest_block: 3105526, service: beacon
Jul 28 17:18:23.612 INFO Waiting for more deposits               valid_deposits: 4115, total_deposits: 4218, min_genesis_active_validators: 16384, service: beacon

## Expected Behaviour

Application should serve http API via port 5052 on localhost. For Altona I was able to easily set up a beacon node which connected to infura for Görli RPC and was serving the beacon node API on address 0.0.0.0 port 5052 in my local network so that other nodes could connect to it.

## Steps to resolve

n/a

**Comment by AgeManning** [comment]
When a testnet hasn't reached genesis, nodes cannot discover, connect or find each other.  The genesis for a testnet occurs 2 days before its launch and then a beacon node will start its networking and http services as prior to this there is nothing it can do. 

As the logs indicate here, your node is waiting for the eth2 genesis. We don't start the HTTP service until then, as there is nothing to output. 

We will be allowing the metrics HTTP server to start before a genesis node in the future however. For the time being this is expected behaviour.

**Comment by ChosunOne** [comment]
Would be useful to allow some kind of discovery to troubleshoot network issues prior to genesis.
