### ISSUE TITLE
No graffiti flag for validator client to receive POAP badge for the Medalla testnet

### ISSUE THREAD

**Issue by markrtgh** [sigp/lighthouse#1410]
## Description
  
No validator graffiti flag. Many users that join the Medalla testnet will want to receive a POAP badge for running a validator.  
  
There is a `--graffiti` flag for the lighthouse beacon client which appears to work, however, the instructions at the [POAP page](https://medalla.beaconcha.in/poap) only refers to the validator which will cause confusion for people using lighthouse.

## Version

Lighthouse 0.1.2-9ae9df80

## Present Behaviour

No graffiti flag for validator.

## Expected Behaviour

Graffiti flag option available for validator.

## Steps to resolve

Either:
1. Add a graffiti flag to the validator, or
2. Update the Lighthouse Book with instructions on how to add a beacon client graffiti flag to receive a POAP badge and reach out to medalla.beaconcha.in to update the instructions on the POAP page for lighthouse.

**Comment by AgeManning** [comment]
Thanks for this. 

As we are getting close to the medalla launch, we'll likely go with 2 for the time being as 1 would be a more substantial change.

Thanks for raising this

**Comment by torfbolt** [comment]
This seems to be closed by #1425 ?

**Comment by AgeManning** [comment]
Correct. Closing. Thanks!
