### ISSUE TITLE
RPCCodedResponse Error is not bounded

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1421]
## Description

According to this PR: https://github.com/ethereum/eth2.0-specs/pull/1837

We should bound the error response, however we still have it as a string type which is unbounded. 

See here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/rpc/codec/ssz.rs#L59
and here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/rpc/codec/ssz.rs#L318

**Comment by AgeManning** [comment]
New references: 

The error decoding is here:
https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/rpc/codec/ssz_snappy.rs#L405

The Error type we want is here: 
https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/rpc/methods.rs#L22

Currently this is decoding a string, sending it to the BaseOutboundCodec which then converts the string into the error type. It would be nicer to have the BaseOutboundCodec return the error type directly and check the length before decoding into a string. 

I.e I think we should just use the logic in the From impl here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2_libp2p/src/rpc/methods.rs#L24
directly in the decoding after checking the length and returning the ErrorType directly.

**Comment by paulhauner** [comment]
Closing since I think it's fixed in #1593. Feel free to reopen if that's not the case @AgeManning :)
