### ISSUE TITLE
Fix double builds on Docker Hub

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1426]
## Description

For some reason all our images are getting double built on Docker Hub at the moment, which wastes our build minutes and increases the time it takes for a new Docker image to get out.

This comment seems to imply it could be related to having duplicate webhooks on the repo: https://github.com/docker/hub-feedback/issues/936#issuecomment-428598187

**Comment by michaelsproul** [comment]
Age and I had to muck around with the builds today, and ended up deleting and recreating the main automated build, which seems to have caused the issue.

**Comment by paulhauner** [comment]
This was fixed in #1574, but that PR was reverted so this issue stays open.

**Comment by realbigsean** [comment]
fixed with the move to github actions
