### ISSUE TITLE
Two copies of validator_definitions.yml

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1427]
## Description

I'm seeing two copies of `validator_definitions.yml`, one in `~/.altona/` and the other in `~/.altona/validators` (`~/.altona` is my validator dir). I don't have time to investigate now, but it looks like there's something strange going on

## Version

Lighthouse 0.1.2-2ede9caa

**Comment by michaelsproul** [comment]
I'm fairly sure this will be resolved by #1532 (I had my datadirs confused)

**Comment by paulhauner** [comment]
Resolved via #1532 (I think?)

**Comment by michaelsproul** [comment]
Yep!
