### ISSUE TITLE
Avoid double Metadata requests

### ISSUE THREAD

**Issue by divagant-martian** [sigp/lighthouse#1429]
Lighthouse is sending a Metadata request when connecting to a peer and another one after a Ping if the Metadata response is not received before. This happens ms from each other, so this could give Lighthouse a bad score with peers implementing rate limiting

**Comment by paulhauner** [comment]
Hey @divagant-martian is this still relevant? :)

**Comment by divagant-martian** [comment]
We still do this

**Comment by divagant-martian** [comment]
we have not seen rate limiting related issues in a long time, thus closing
