### ISSUE TITLE
Add testnet configs to the repository

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1431]
## Description

I propose we add the testnet configs to the Lighthouse repository itself to prevent builds from failing when unable to access githubusercontent. 

Apparently from China accessing this is intermittent and causes the builds to fail sporadically.

**Comment by paulhauner** [comment]
I'm fine with this. The worst part IMO is that we'll need to add `genesis.ssz` which is a several-MB binary file. Perhaps we can compress this?

**Comment by AgeManning** [comment]
For this. 
When the CLI params select a known testnet, such as medalla or altona, this function gets called: https://github.com/sigp/lighthouse/blob/master/common/eth2_testnet_config/src/lib.rs#L79
And it returns the configuration struct for either testnet. 

Currently it obtains it from the downloaded version which happens when this crate gets built, see the build script: https://github.com/sigp/lighthouse/blob/master/common/eth2_testnet_config/build.rs

This issue, should remove the build script and add the required configuration files directly into the repository. However we may want to have them compressed in the repository and then have the build script decompress them rather than download them.

**Comment by AgeManning** [comment]
Resolved in #1603
