### ISSUE TITLE
Ensure lcli generates correct pre-genesis ENR

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1433]
## Description

NA

## Version

`master`

## Present Behaviour

When starting boot nodes prior to genesis (i.e., before a new testnet starts), we use `lcli generate-bootnode-enr` to create the `network/` dir with keys, ENR, etc.

This works well, however there is a conflict between this line (specifically `EnrForkId::default()`):

https://github.com/sigp/lighthouse/blob/3b5da8f35f1788972a205af3063a1f1448082d75/lcli/src/generate_bootnode_enr.rs#L33

And this section of [the spec](https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/p2p-interface.md#attestation-subnet-bitfield):

> One notable exception to this rule is the distribution of bootnode ENRs prior to genesis. In this case, bootnode ENRs SHOULD be initially distributed with eth2 field set as ENRForkID(fork_digest=compute_fork_digest(GENESIS_FORK_VERSION, b'\x00'*32), next_fork_version=GENESIS_FORK_VERSION, next_fork_epoch=FAR_FUTURE_EPOCH). After genesis values are known, the bootnodes SHOULD update ENRs to participate in normal discovery operations.

## Steps to resolve

Ensure that `generate_bootnode_enr.rs` creates the `EnrForkId` in a way that is faithful to specification before genesis is known.

**Comment by paulhauner** [comment]
@pawanjay176 perhaps you'd be interested in this one?

**Comment by pawanjay176** [comment]
Yep, I'll take this one!
