### ISSUE TITLE
Start from weak subjectivity state

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1435]
## Description

Lighthouse should be able to start from a "weak subjectivity state", that is a trusted `BeaconState` (and perhaps `BeaconBlock`) that is not genesis. This protects Lighthouse from long-range attacks from already exited validators. 

I believe that @adaszko is already working on this.

**Comment by realbigsean** [comment]
I'd be interested in picking this up

**Comment by paulhauner** [comment]
I've had some discussion out-of-band with @AgeManning and @michaelsproul regarding this.

We need to implement "starting from a weak subjectivity (WSJ) state" to protect ourselves from WSJ-based attacks. This means we need to be able to start a fresh LH database with the knowledge of some recent WSJ state/block root and ensure that we never contradict those values.

I see two immediate ways to do this:

## Solution 1. Start with head at WSJ state

In this scenario you load the entire WSJ state and block into the beacon node, then set it to your head. You sync forwards and maybe backwards.

This is the ideal scenario because it provides maximum protection from WSJ-based attacks *and* it provides fast sync-to-head times for users.

## Solution 2. Start head at genesis

In this scenario you load a `(wsj_slot, wsj_block_root)` tuple into the beacon node. It starts syncing from genesis (as we do now) and will fail if it reaches `wsj_slot` and `wsj_block_root` is not in the chain.

It needs to fail *very hard* if a contradicing WSJ point is finalized. Since you can cause rouge finalization with WSJ attacks, our databases and caches will all be compromised and/or invalid. I think we should kill the beacon node processes and the user will need to re-sync from scratch.

## Which scenario?

I think it's clear that scenario (1) is much better than (2), but it is much more work.

I think that WSJ is a significant security vuln that needs to be address before audit. Whilst I would love to see (1) implemented, it requires major changes to our code base and likely the networking specification.

I think that (2) is quite simple: we can pass this [`exit signal`](https://github.com/sigp/lighthouse/blob/e5fc6bab485fa54d7e518b325f4eb9201ba5c6a1/lighthouse/environment/src/lib.rs#L342) to the `BeaconChain` and do the WSJ slot/root check in [`process_block`](https://github.com/sigp/lighthouse/blob/e5fc6bab485fa54d7e518b325f4eb9201ba5c6a1/beacon_node/beacon_chain/src/beacon_chain.rs#L1446).

My feeling is that we should implement (2) now to patch the vuln prior. Then, we should starting working to implement (2), perhaps not achieving it until post-mainnet launch.

**Comment by michaelsproul** [comment]
Closed by #1675
