### ISSUE TITLE
Alex's transition helper bouquet

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#147]
## Description

Implement the following functions:

* `get_shard_committees_at_slot`: given a slot, returns the ShardAndCommittees for each shard.
* `get_block_root`: returns a hash from the state.
* `get_beacon_proposer_index`: returns the index of the beacon block proposer for a given slot.
* `get_effective_balance`: returns the validators "effective balance". This balance can never be higher that MAX_DEPOSIT (32 ETH presently).
* `get_fork_version`: gets the version from some ForkData.
* `get_domain`: returns a "domain" used for replay protection across forks/chains.

Note: this is a reactive issue as @ralexstokes is already working on these. Feel free to suggest a better issue title :)

**Comment by paulhauner** [comment]
Just a heads up to @ralexstokes and @g-r-a-n-t that the `get_domain` issue is likely related to #91.

**Comment by ralexstokes** [comment]
`get_shard_committees_at_slot` and `get_beacon_proposer_index` are done in #148 pending review

**Comment by ralexstokes** [comment]
rest of these helpers are in #178

**Comment by paulhauner** [comment]
Closing in favor of #182
