### ISSUE TITLE
logs: Failed to update eth1 cache

### ISSUE THREAD

**Issue by Joera** [sigp/lighthouse#1477]
Hi, i am following the tutorial on medium. Got lighthouse-beacon  running and while syncing i get these messages: 'ERRO Failed to update eth1 cache'. What do they mean? Anything critical?

Aug 06 10:05:39 Medalla lighthouse[174487]: Aug 06 10:05:39.714 ERRO Failed to update eth1 cache             error: Failed to update eth1 cache: RemoteNotSynced { next_required_block: 3085928, remote_highest_block: 0, follow_distance: 1024 }, retry_millis: 7000, service: eth1_rpc
Aug 06 10:05:45 Medalla lighthouse[174487]: Aug 06 10:05:45.073 INFO New block received                      hash: 0x7fd5…2af5, slot: 13528, service: router
Aug 06 10:05:46 Medalla lighthouse[174487]: Aug 06 10:05:46.714 ERRO Failed to update eth1 cache             error: Failed to update eth1 cache: RemoteNotSynced { next_required_block: 3085928, remote_highest_block: 0, follow_distance: 1024 }, retry_millis: 7000, service: eth1_rpc
Aug 06 10:05:50 Medalla lighthouse[174487]: Aug 06 10:05:50.000 INFO Synced                                  slot: 13528, block: 0x7fd5…2af5, epoch: 422, finalized_epoch: 420, finalized_root: 0x71d0…845d, peers: 54, service: slot_notifier
Aug 06 10:05:53 Medalla lighthouse[174487]: Aug 06 10:05:53.714 ERRO Failed to update eth1 cache             error: Failed to update eth1 cache: RemoteNotSynced { next_required_block: 3085928, remote_highest_block: 0, follow_distance: 1024 }, retry_millis: 7000, service: eth1_rpc
Aug 06 10:05:57 Medalla lighthouse[174487]: Aug 06 10:05:57.904 INFO New block received                      hash: 0x3117…eb57, slot: 13529, service: router
Aug 06 10:06:00 Medalla lighthouse[174487]: Aug 06 10:06:00.713 ERRO Failed to update eth1 cache 

Eth 1 is running

root@Medalla:~# sudo systemctl status geth
● geth.service - Ethereum go client
     Loaded: loaded (/etc/systemd/system/geth.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2020-08-05 14:05:54 UTC; 20h ago
   Main PID: 764 (geth)
      Tasks: 16 (limit: 4683)
     Memory: 2.0G
     CGroup: /system.slice/geth.service
             └─764 /usr/bin/geth --goerli --http --datadir /var/lib/goethereum

lighthousebeacon is running 

root@Medalla:~# sudo systemctl status lighthousebeacon
● lighthousebeacon.service - Lighthouse Beacon Node
     Loaded: loaded (/etc/systemd/system/lighthousebeacon.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-08-06 07:07:21 UTC; 3h 15min ago
   Main PID: 174487 (lighthouse)
      Tasks: 15 (limit: 4683)
     Memory: 678.5M
     CGroup: /system.slice/lighthousebeacon.service
             └─174487 /usr/local/bin/lighthouse beacon_node --datadir /var/lib/lighthouse/beacon-node --testnet medalla --http --eth1-endpoint http://127.0.0.1:8545 --graffiti xxxxxxx

Thanks, Joera

**Comment by pawanjay176** [comment]
@Joera Your geth node might not be synced yet. It looks like your geth node has been running for quite some time though. Usually takes ~1 hour to sync to goerli. Maybe there's a network issue with geth?

The errors will go away once it's synced.

**Comment by Joera** [comment]
Thanks Pawan! i now added the bootnodes to the gethnode as described in tutorial. It seems more active than before. Let's see if that helps.

**Comment by paulhauner** [comment]
Thanks for the response @pawanjay176. I hope this resolves it @Joera, please re-open the issue if not :)

**Comment by Joera** [comment]
Yes, i am now a proud validator for the testnet. Thanks.
