### ISSUE TITLE
Allow signature repetition in launchpad import

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1479]
## Description

@ralexstokes pointed out that it gets repetitive using `lighthouse account validator import` command when there are many keys with the same password.

## Steps to resolve

I think we could resolve this by:

- Determining key generation context by the filename, if the filename matches the launchpad-generated format. (I'm not sure how to do this, but I'm told it's possible).
- Adding a "repeat previous password" option.

**Comment by adetante** [comment]
I had the same experience when importing my medalla keys, I can look at this issue.

[Keystores generated by the launchpad](https://github.com/ethereum/eth2.0-deposit-cli/blob/de03fe361db7dbf23c97be475fc668c83a499e2b/eth2deposit/credentials.py#L87)  are stored in files of the form `keystore-{path}-{generationTimestamp}.json` with the (sanitized) `{path}` of the keystore. If several keys are generated, the account level of the path will take the values 0,1,2... etc.

The import command could use this pattern to detect a launchpad keystore, and reuse the previous password, even if a `--same-password` argument seems more natural to me?

**Comment by paulhauner** [comment]
Fixed by #1510
