### ISSUE TITLE
Implement/update `get_shuffling`

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#151]
## Description

Implement `get_shuffling` from the spec.

There is an [existing implementation](https://github.com/sigp/lighthouse/blob/master/beacon_chain/validator_shuffling/src/shuffle.rs) that I highly suspect has been outdated.

## Steps to complete

- Rename the existing function to `get_shuffling` (instead of `shard_and_committees_for_cycle`).
- Identify and fix any logic differences between the spec and our implementation.
- Test thoroughly.

**Comment by drozdziak1** [comment]
I'll try handling this one

**Comment by paulhauner** [comment]
Closing this as it was implemented in #180. Discussion exists at #157. Sorry!
