### ISSUE TITLE
Docker Images for arm64 releases (Raspberry Pi)

### ISSUE THREAD

**Issue by shalzz** [sigp/lighthouse#1512]
## Description
Hello,
Please also consider providing Docker Image releases for arm64/aarch64 platforms along with amd64 Docker Images on Docker Hub.

**Comment by paulhauner** [comment]
Good idea. Seems like dockerhub doesn't support it natively but we can do it via Github Actions: https://www.henry.wang/2019/12/05/arm-dockerhub.html

I don't have bandwidth for this at the moment, but I think it's worth doing.

**Comment by paulhauner** [comment]
Marked as `low-hanging-fruit` since it's a relatively simple way to make a material difference to users.

**Comment by paulhauner** [comment]
@realbigsean this might interest you :)

**Comment by realbigsean** [comment]
A few notes on making a multi-arch image:

- it's not doable using Dockerhub atm, but it is in their [roadmap](https://github.com/docker/roadmap/issues/109).  I also tried using a workaround using emulation, but their build servers are too old.
- it's doable using github actions and QEMU, but takes a looooong time (~5 hours).  I also went down the rabbit hole of trying to use cross-compilation to speed things up, but `cross` uses docker, so you end up needing to start a docker container within a docker build which gets hairy. (I think `cross` also uses QEMU so I don't know whether it'll speed stuff up)
- I think the solution that's the most straightforward and likely to result in the fastest builds is to run a docker builder node on an ARM64 and one on an AMD64 server and coordinate them

**Comment by michaelsproul** [comment]
> cross uses docker, so you end up needing to start a docker container within a docker build which gets hairy. (I think cross also uses QEMU so I don't know whether it'll speed stuff up)

Building an ARM binary with cross doesn't use QEMU, and is quite fast. I think we could do something like:

1. Build ARM binary using `cross`, on "bare metal" (no nested Docker, but probably under a hypervisor)
2. Copy that binary into a base image as we currently do in the 2nd stage of our build:

https://github.com/sigp/lighthouse/blob/c6baa0eed131c5e8ecc5860778ffc7d4a4c18d2d/Dockerfile#L9-L16

**Comment by realbigsean** [comment]
@michaelsproul I got something working in #2065 using `cross` first like you suggested and then `docker buildx` to cross-build the docker image, and then `docker manifest` to make the multi-arch image. Let me know your thoughts

It's way faster 🔥
