### ISSUE TITLE
Op pool should prioritise better attester slashings

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1548]
## Description

Presently the op pool throws attester slashings into blocks without any regard for profit maximisation (by maximising the number of slashed validators).

## Version

Lighthouse v0.2.4-93b7c3b7
BLS Library: blst

## Present Behaviour

We take valid slashings in no particular order: https://github.com/sigp/lighthouse/blob/fdc6e2aa8ec5aeeba6740b85df1d284caad526fa/beacon_node/operation_pool/src/lib.rs#L195-L252

## Expected Behaviour

We should choose the two best attester slashings! Although there's only two of them, this is an instance of the max cover problem for attestations! I can't believe it took me this long to notice :O

## Steps to resolve

Implement a maximum-coverage-based optimiser for attester slashings, using the existing trait in https://github.com/sigp/lighthouse/blob/master/beacon_node/operation_pool/src/max_cover.rs

**Comment by danielschonfeld** [comment]
I'm going to take a stab at this
