### ISSUE TITLE
Do not require subnet ID for /validator/attestations HTTP call

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#1550]
## Description

At current the HTTP API for /validator/attestations requires a tuple of [attestation, subnet ID] tuples, for example:

```
[[{"aggregation_bits":"0x0000020001","data":{"slot":4,"index":0,"beacon_block_root":"0x4785cedf475fabfe2007ec4d66c8b5ba7b0238ba5d66a2a094f3a499e9d5d6dc","source":{"epoch":0,"root":"0x0000000000000000000000000000000000000000000000000000000000000000"},"target":{"epoch":0,"root":"0x67e8f3bbea8ceb4e8edf51e4eab4f9adae6ea02d3161e9343ede833321dc4572"}},"signature":"0x93a56d422333e83876dda94cc0295a7a316638ae6c9ff15c636bd4740c4358f4842e49b90c8f498ab1f0368f743b9d5f083010f5e5c402a83aca71eeed0e53fe7a2d999c4054794f10b16036cd4a7efd0c488f4eb8afea240e5ad22c3598a2bd"},0]]
```

The requirement for the subnet ID appears spurious, in that the beacon node works out the subnet ID itself and complains if the supplied value is incorrect:

```
InvalidSubnetId { received: SubnetId(0), expected: SubnetId(4) }
```

Of course, if there is a good reason to pass and return the subnet ID then this request may be incorrect.

## Version

```
$ git rev-parse HEAD
fdc6e2aa8ec5aeeba6740b85df1d284caad526fa
```

## Present Behaviour

The subnet ID is required, and required to be correct, for the attestation to be processed.

## Expected Behaviour

The subnet ID should not be required for acceptance of the attestation.

## Steps to resolve

There are a couple of ways this could be addressed:
  - alter the API so that it does not require a subnet ID
  - ignore the supplied subnet ID value for validation, and use the one calculated by the beacon node for broadcast

The latter would be easier to accomplish, given that the HTTP API is likely to be replaced with the standard API at some point in the near future.

**Comment by paulhauner** [comment]
Resolved via #1569
