### ISSUE TITLE
Incorrect error handling resulting in swallowed errors

### ISSUE THREAD

**Issue by adaszko** [sigp/lighthouse#1554]
## Description

While investigating https://github.com/sigp/lighthouse/issues/1488, I came across incorrect error handling that results in unreported database errors.

## Present Behaviour

`unwrap_or_else()` at https://github.com/sigp/lighthouse/blob/51fbaefe415abd35305b798fc3772afeccceddf4/beacon_node/network/src/router/processor.rs#L219-L221

swallows an error (e.g. `MissingBeaconState(BeaconStateHash(0x3c9083c24dbafe5614369126c77549355de0563002a87dc20f69e5b53cbf3d19))`)

There are lots of other occurrences of `unwrap_or_else()` over there.  They also should be checked for proper error propagation/handling.

## Expected Behaviour

The error should be propagated/handled.

**Comment by paulhauner** [comment]
Resolved in #1654
