### ISSUE TITLE
beacon node gets killed after some time

### ISSUE THREAD

**Issue by ChuckNorrison** [sigp/lighthouse#1555]
## Description

I try to get into the medalla testnet with 2 validators. My beacon node instance gets killed after some time. The time it gets killed increased to some hours now. 

setup eth1 node and iam running a well configured lighthouse -vc, which acutally always results with:

> ug 20 17:29:48.050 ERRO Unable to connect to beacon node        error: "ReqwestError(reqwest::Error { kind: Request, url: \"http://localhost:5052/node/version\", source: hyper::Error(Connect, ConnectError(\"tcp connect error\", Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })) })"

the beacon node got started as lighthouse --testnet medalla beacon --eth1

results:

> Aug 20 17:25:26.000 INFO Synced                                  slot: 115926, block:    …  empty, epoch: 3622, finalized_epoch: 3618, finalized_root: 0x37e5…3542, peers: 49, service: slot_notifier
Aug 20 17:25:32.009 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 8047, slot: Slot(115870) }, service: router
Aug 20 17:25:32.130 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 20879, slot: Slot(115885) }, service: router
Aug 20 17:25:32.774 INFO New block received                      hash: 0x9fea…413f, slot: 115927, service: router
Aug 20 17:25:32.930 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 583, slot: Slot(115845) }, service: router
Aug 20 17:25:35.688 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 29520, slot: Slot(115791) }, service: router
Aug 20 17:25:35.953 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 29986, slot: Slot(115871) }, service: router
Aug 20 17:25:36.118 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 8618, slot: Slot(115886) }, service: router
Aug 20 17:25:36.574 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 5349, slot: Slot(115846) }, service: router
Aug 20 17:25:38.001 INFO Synced                                  slot: 115927, block: 0x9fea…413f, epoch: 3622, finalized_epoch: 3618, finalized_root: 0x37e5…3542, peers: 49, service: slot_notifier
Aug 20 17:25:41.891 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 8143, slot: Slot(115793) }, service: router
Aug 20 17:25:44.396 INFO New block received                      hash: 0x17ec…a97f, slot: 115928, service: router
Aug 20 17:25:46.090 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 24878, slot: Slot(115875) }, service: router
Aug 20 17:25:46.143 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 4711, slot: Slot(115887) }, service: router
Aug 20 17:25:46.681 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 24515, slot: Slot(115847) }, service: router
Aug 20 17:25:50.000 INFO Synced                                  slot: 115928, block: 0x17ec…a97f, epoch: 3622, finalized_epoch: 3618, finalized_root: 0x37e5…3542, peers: 48, service: slot_notifier

[...]
> Aug 20 17:31:14.001 INFO Synced                                  slot: 115955, block: 0x5a52…50c9, epoch: 3623, finalized_epoch: 3619, finalized_root: 0x6fbe…6b9d, peers: 49, service: slot_notifier
Aug 20 17:31:20.132 WARN Could not verify block for gossip       error: RepeatProposal { proposer: 4481, slot: Slot(115923) }, service: router
Aug 20 17:31:20.930 INFO New block received                      hash: 0x7cb6…6031, slot: 115956, service: router

## Version

`master` git pull and restart instance always done after a crash happens
Lighthouse v0.2.1-04e4389e

## Present Behaviour

Instance ends without much informations what has caused that issue

## Expected Behaviour

should not end without information from an unexpected state

## Steps to resolve

find the crash or reason why it ends and write some help to stdout

**Comment by ChuckNorrison** [comment]
some more console out while starting the beacon node:

> nice@helion:~/git/lighthouse$ lighthouse --testnet medalla beacon --eth1
Aug 20 17:36:38.032 WARN Ethereum 2.0 is pre-release. This software is experimental.
Aug 20 17:36:38.033 INFO Configured for testnet                  name: medalla
Aug 20 17:36:38.033 INFO Data directory initialised              datadir: /home/xxx/.lighthouse
Aug 20 17:36:38.195 INFO Starting beacon chain                   method: resume, service: beacon
Aug 20 17:36:40.122 INFO Block production enabled                method: json rpc via http, endpoint: http://localhost:8545
Aug 20 17:36:40.274 INFO Imported deposit log(s)                 new: 1, total: 38308, latest_block: 3257695, service: eth1_rpc
Aug 20 17:36:40.295 INFO Beacon chain initialized                head_slot: 115964, head_block: 0xb595…de59, head_state: 0x99bb…97c6, service: beacon
Aug 20 17:36:40.296 INFO Timer service started                   service: node_timer
Aug 20 17:36:40.297 INFO Libp2p Service                          peer_id: PeerId("xxx"), service: libp2p
Aug 20 17:36:40.297 INFO ENR Initialised                         tcp: Some(9000), udp: Some(9000), ip: Some(xxx), id: 0x650e..4bf7, seq: 7, enr: enr:-xxx-xxx-xxx-xxx, service: libp2p
Aug 20 17:36:40.298 INFO Listening established                   address: /ip4/0.0.0.0/tcp/9000/p2p/xxx, service: libp2p
Aug 20 17:36:40.298 INFO Subscribed to topics                    topics: [BeaconBlock, BeaconAggregateAndProof, VoluntaryExit, ProposerSlashing, AttesterSlashing], service: libp2p
Aug 20 17:36:41.529 INFO Sync state updated                      new_state: Syncing Head Chain, old_state: Stalled, service: sync
Aug 20 17:36:50.000 WARN Low peer count                          peer_count: 1, service: slot_notifier
Aug 20 17:36:50.000 INFO Syncing                                 est_time: --, speed: --, distance: 19 slots (3 mins), peers: 1, service: slot_notifier
Aug 20 17:36:53.863 INFO Sync state updated                      new_state: Synced, old_state: Syncing Head Chain, service: sync
Aug 20 17:37:02.000 INFO Synced                                  slot: 115984, block:    …  empty, epoch: 3624, finalized_epoch: 3621, finalized_root: 0x876b…cb7a, peers: 6, service: slot_notifier
Aug 20 17:37:14.001 INFO Synced                                  slot: 115985, block:    …  empty, epoch: 3624, finalized_epoch: 3621, finalized_root: 0x876b…cb7a, peers: 5, service: slot_notifier

shredded some keys here

**Comment by ChosunOne** [comment]
Your lighthouse version looks out of date.  Try ensuring you are using 0.2.6 or higher.

**Comment by ChuckNorrison** [comment]
Thanks man, i did not build 0.2.6, just pulled from git :)
