### ISSUE TITLE
export key stores to launchpad format for client swap

### ISSUE THREAD

**Issue by somuchid** [sigp/lighthouse#1559]
Seems like lighthouse double encrypt key stores. It encrypt plaintext password, then generate a specific secret for each key file, while launchpad only use plaintext password. Other clients can't import those key stores, although they are able to import launchpad's.

In the catastrophe similar to the one happened a few days ago in Medalla testnet, stakers running lighthouse client , batch generate key files and  batch deposit by lighthouse tool, won't be able to switch to other clients, because there is no tools available for them to move key files to other clients, which can't read those key files.

Alouthgh lighthouse can import launchpad's key file, launchpad can't do batch deposit.Worse yet, when lighthouse import launchpad's key file, it does not import deposit data, so after importing launchpad's key files, stakers can't do deposit by lighthouse tool on those imported key files.

There are two solutions:
1. lighthouse add import deposit data and be able to do batch deposit after import
2. lighthouse export the key stores back to launchpad

**Comment by paulhauner** [comment]
> Seems like lighthouse double encrypt key stores.

I'm not sure this is the case. We pass all the EIP-2335 test vectors, the standard used by the launchpad.

> Other clients can't import those key stores

Do you have some error logs or perhaps references for this? It certainly shouldn't be the case.

**Comment by somuchid** [comment]
prysm fixed the problem
