### ISSUE TITLE
Avoid printing binary graffiti to logs

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1566]
## Description

We seem to output block graffiti to the logs without escaping or removing unprintable characters, which causes text-based tools like `grep` to choke up:

```
$ grep 'graffiti' medalla_bn.log
Binary file medalla_bn.log matches
```

(You need to re-run with `grep --text`)

It looks like we make some attempt to sanitize the graffiti, but it doesn't seem to be working as intended. An alternative approach might involve stripping `\0` from the end of the string, and processing the rest with [`String::from_utf8_lossy`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy)

https://github.com/sigp/lighthouse/blob/dfd02d617953303cad98284f4e091d5d88241ec5/beacon_node/beacon_chain/src/beacon_chain.rs#L1305-L1306

**Comment by paulhauner** [comment]
Agreed! We also need to sanitize against weird terminal commands that can pose a security risk. I like the sound of utf8 :)

**Comment by AgeManning** [comment]
I think you'll find it's not the graffiti causing the issue. Potentially we are printing binary data via the graffiti, but I've found one of the causes to be this guy:
https://docs.rs/fixed-hash/0.6.1/src/fixed_hash/hash.rs.html#223

In the implementation of display of Hash256 we print this "..." character which registers as binary. So I think printing the debug version of hashes will resolve this.

**Comment by darcys22** [comment]
Thanks for the feedback!

Yeah I think I misunderstood what the problem was, will have another look at this.

Do you think there are any other areas doing this? or would it be solely the hash display function?

**Comment by AgeManning** [comment]
From what I've seen, it's just in the hash display function. I think its mainly when we display the block hash. We do it correctly (as debug) in some parts but in others we use the display. 

I think in the notifier (`beacon_node/client/src/notifier`) and the slot timer (`beacon_node/timer`) are where I've seen display used.

**Comment by michaelsproul** [comment]
The graffiti is causing an issue, if you try to print `\0`, grep doesn't like it:

```
$ echo -e "\0hello" | grep hello
Binary file (standard input) matches
```

I extracted some relevant lines from my node's log here, and you can check that grep will choke on this file:

https://sproul.xyz/eth2/graffiti.txt

I think we have to go beyond just santising to UTF8 (because we already do that), and look to strip non-printable characters. I suspect replacing `\0` with ` ` or `_` would get us 99% of the way there, but it seems a better solution would be to replace any character that isn't in the `Print` class using a regex, as is done here:

* In Java: https://stackoverflow.com/questions/11020893/remove-non-ascii-non-printable-characters-from-a-string
* Rust regex supports `\P{Print}` too: https://docs.rs/regex/1.3.9/regex/index.html#syntax

---

I don't think the ellipsis character is an issue based on this test:

```
$ echo "hello…" | grep hello
hello…
```

(that's using this character https://www.compart.com/en/unicode/U+2026)

**Comment by AgeManning** [comment]
Yeah cool. I've been using `cat -v` which replaces the "..." character and some of the grafiti. The fact that cat replaced it, lead me to assume grep would have issues. 

Sounds like you're on this.

**Comment by darcys22** [comment]
Confirming that when the graffiti hex has zeros it causes issues. For example the graffiti in this slot here:

https://beaconscan.com/slot/189885

`0x74656b752f76302e31322e362d6465762d643563323861393300000000000000`

In my logs comes across as this

![seandarcy_—_sean____dev____119_77_85_139_—_ssh_sean_192_168_1_98_—_Solarized_Dark_xterm-256color_—_120×33](https://user-images.githubusercontent.com/2188604/91679742-7f2fa880-eb8c-11ea-8dc1-ba27c15bbe3e.png)

I'll update the pull request to include a regex that filters out non printable characters.

**Comment by michaelsproul** [comment]
The graffiti was fixed by #1576, although I've noticed that we still print some unprintable chars in this message:

```
Sep 09 12:07:03.083 DEBG RPC Error                               score: 0.00, peer_id: 16Uiu2HAm1UMCesJdXKnonHkWD7Rp9PitnEXJFn5yfvWR1X4pZheY, client: Prysm: version: 0961fef727413165b418028f45eea9816cfc929d, os_version: unknown, err: RPC response was an error: The request was invalid with reason: rate limited, protocol: beacon_blocks_by_range, service: libp2p
```

`xxd` revealed bytes `0x04000000` immediately before the string `"rate limited"`

Sample here: https://sproul.xyz/eth2/rate_limited.txt

**Comment by darcys22** [comment]
So thats an error message flowing through as raw bytes somewhere i guess. 

I’ll have a dig and see where its coming from and hopefully we can just apply the same regex over it to fix it

**Comment by AgeManning** [comment]
Yeah. The error is a byte string. I think the best way to handle this is in a type conversion when leaving the networking stack. Such that we only output utf8 strings. 

I'll handle this

**Comment by AgeManning** [comment]
For the sake of handling issues. I'm going to close this and we can re-open if we find more.
