### ISSUE TITLE
Add trusted peers CLI param

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1581]
## Description

In some cases it is useful to add a set of trusted peers that avoid the scoring system (or always have the most positive score). This should be added as a CLI param. Peers that are considered trusted, do not get penalized in the scoring system and we therefore don't disconnect from them based on their behaviour.

**Comment by pawanjay176** [comment]
I'll take this.

**Comment by fomotrader** [comment]
Any docs on how to use this flag, I think I"m using it incorrectly and trying to spin up my client now

**Comment by pawanjay176** [comment]
Here are the docs for the flag. You can check with `lighthouse bn --help`
```
        --trusted-peers <TRUSTED_PEERS>
            One or more comma-delimited trusted peer ids which always have the highest score according to the peer
            scoring system.
```

Note that Lighthouse will not connect to this peer_id given the flag. Just that it will not remove it from it's peer list once connected. You can connect to it by passing it in the `--libp2p-addresses` flag

```
        --libp2p-addresses <MULTIADDR>
            One or more comma-delimited multiaddrs to manually connect to a libp2p peer without an ENR.
```
The multiaddr format is `/ip4/<IP-ADDR>/tcp/<PORT>`
