### ISSUE TITLE
upgrade the eth2_hashing to v0.1.1

### ISSUE THREAD

**Issue by yaanhyy** [sigp/lighthouse#1599]
## Description

Please provide a brief description of the issue.

use eth2_hashing 0.1.0 with  ring  0.14 is too old to match to other dependence

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

use eth2_hashing to v0.1.1 and use ring 0.16

**Comment by paulhauner** [comment]
Closing since it's covered in #1712
