### ISSUE TITLE
Discv5.1

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1605]
## Description

This is a tracking issue for implementing discovery v5.1 and integrating into lighthouse

**Comment by AgeManning** [comment]
The update has been completed in https://github.com/sigp/discv5/pull/39

It is as trivial matter to port this to lighthouse. https://github.com/sigp/discv5/pull/39 will be merged down once some further interoperability testing has been completed. 

This issue will be considered blocked until other clients can also support discv5.1

**Comment by paulhauner** [comment]
> This issue will be considered blocked until other clients can also support discv5.1

Bumping this to `A1` accordingly.
