### ISSUE TITLE
Gossipsub v1.1 Scoring Paramters

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1606]
## Description

Design, test and implement a set of scoring parameters for the Ethereum 2.0 network. 

Lighthouse currently has gossipsub v1.1 integrated without scoring. Once the parameters are set and tested and all client implementer teams agree, we should integrate into lighthouse. 

This is a tracking issue.

**Comment by AgeManning** [comment]
Although we have a set of usable scoring parameters, we have updated our gossip validation to require all messages to not have a seq_no, from or signature field as per: https://github.com/ethereum/eth2.0-specs/issues/1981

Other clients are yet to update to this logic and as a result most gossipsub messages appear invalid to us (as other clients are still forwarding these invalid messages). 

For this reason, we don't want to implement the scoring parameters into lighthouse just yet.

**Comment by paulhauner** [comment]
> For this reason, we don't want to implement the scoring parameters into lighthouse just yet.

Bumping to `A1` accordingly.

**Comment by paulhauner** [comment]
@AgeManning feel free to change to `A0` as you see fit

**Comment by blacktemplar** [comment]
Resolved by #1668
