### ISSUE TITLE
Resend attestation later on if beacon node was not reachable/offline

### ISSUE THREAD

**Issue by blacktemplar** [sigp/lighthouse#1611]
## Present Behaviour

If the beacon node is not reachable for a validator or offline in the time the validator wants to publish an attestation, then the validator logs a critical log line and does not try to publish this attestation again when the beacon node is reachable again/online again.

## Expected Behaviour

A better behaviour would be to retry publishing the attestation if the beacon node is reachable/online within 32 slots (which is the maximum allowed time range for publishing an attestation). This would allow for short periods of offline time for the beacon node (or maybe if also if the beacon node is out of sync for a short period).

**Comment by paulhauner** [comment]
I'm going to close this once since it seems well covered by fallback nodes.
