### ISSUE TITLE
validator import: `--datadir` not respected when running inside Docker container

### ISSUE THREAD

**Issue by ralexstokes** [sigp/lighthouse#1627]
## Description

I want to import keystores from the launchpad. I'm using the `docker-compose` infra via `sigp/lighthouse-docker`.

Volumes are used for persistent data across runs so it takes a little wrangling to do effectful things (like import a bunch of keystores) and have the writes not be discarded.

It seems that changing the `datadir` doesn't influence downstream decisions around where writes should take place. 

## Version

Using this docker image: https://hub.docker.com/layers/sigp/lighthouse/latest/images/sha256-da0c75a385e7309b8e9a87956e19ff9a4c15f46ed5948e688c88a383bbec8fa5?context=explore

And `lighthouse-docker` at this commit: 8ae637fccf5802763e8151a043c8aaf53ff3b99c

## Present Behaviour

I run:

```bash
docker-compose run -v ~/validator-keys:/validator-keys validator_client lighthouse account validator import --datadir /home/lighthouse/.lighthouse --directory /validator-keys --reuse-password
```

where the launchpad output is in `~/validator-keys`.

If this command is run without the `--datadir` flag, then seemingly nothing happens and some poking around reveals that `docker-compose run` executes as `root` so that `$HOME/lighthouse` is not where the external mount is set up (e.g. `./lighthouse-data:/home/lighthouse/.lighthouse`.

So then we explicitly set `--datadir` and it still fails as it seems we need to set `--validator-dir` as well:

e.g.

```bash
docker-compose run -v ~/validator-keys:/validator-keys validator_client lighthouse account validator import --datadir /home/lighthouse/.lighthouse --validator-dir /home/lighthouse/.lighthouse/validators --directory /validator-keys --reuse-password
```

and this works!

## Expected Behaviour

I expect setting `--datadir` to be contextual in the sense that if it is set, anything "beneath" it should respect the decision. I believe what was happening was that `--validator-dir` resolved to `$HOME/.lighthouse/validators` as `root` so that it was in `/root/.lighthouse` (which was not persisted).

I did not try running w/ _just_ `--validator-dir` but assume  that would work without `--datadir`. But my intuition on this is still that `--datadir` should override the top-level scope and everything else should fall underneath that.

## Steps to resolve

Review directory hierarchy construction to ensure that configuration at higher scopes influences configuration at enclosed scopes.

**Comment by ralexstokes** [comment]
I think this issue still stands although I see now that there are updates to `sigp/lighthouse-docker` that put everything under `/root` where I don't think I would have noticed this...

feel free to close if this is no longer relevant! :)

**Comment by paulhauner** [comment]
> feel free to close if this is no longer relevant! :)

Can do! Thank you :)
