### ISSUE TITLE
Propagate to the application (from the rpc) only one closing marker per request 

### ISSUE THREAD

**Issue by divagant-martian** [sigp/lighthouse#1634]
## Description

Inside the RPC we handle requests sent from out side over outbound substreams. When a request receives an end of stream signal or an error, the outbound substream state machine transitions to a closing state. This state only indicates that the substream must be closed, but we will hold it until actually closing it. Between both operations the substream could produce other errors: timeouts, peer sending additional stuff, etc. Those errors are only relevant inside the `Behaviour` for peer scoring, but for the application that sent the request, it is already finished and those additional messages are undesired noice. We should ensure that the application receives exactly one message that indicates the request is finished

## Version

master, 0.2.10

## Present Behaviour

it is possible for the application to receive more than one error for a request

## Expected Behaviour

receive just one :)

## Steps to resolve

check the code to ensure that if a substream is in a closing state, it has already sent a final chunk/error. And when checking timeouts or newly received responses, inform of the error to the behaviour but also indicate that the error should not be propagated to the application.

Small worry out of my head.. a handler might get shutdown before sending the errors, but I guess that's out of scope here

**Comment by paulhauner** [comment]
Hey @divagant-martian is this still relevant? :)

**Comment by divagant-martian** [comment]
The rpc still sends both errors and stream terminations to sync but we just handle it, Mayen we can close it?

**Comment by divagant-martian** [comment]
closing because this doesn't cause any issues even if technically true
