### ISSUE TITLE
When trying to build lighthouse V0.2.11 I am getting make: error 101

### ISSUE THREAD

**Issue by dvgnld** [sigp/lighthouse#1648]
## Version
I get errored out when trying to build lighthouse and I do not know how to work around this. I am a newb but amd willing to follow directions to resolve issue. Thank you. 
lighthouse V0.2.11 default
![image](https://user-images.githubusercontent.com/42664518/93931109-3d99a580-fcd3-11ea-870c-212ecc606b79.png)

**Comment by realbigsean** [comment]
It looks like you are running on Raspbian? That's a 32-bit OS and you need a 64-bit OS.

**Comment by dvgnld** [comment]
Thank you
