### ISSUE TITLE
protos build fails on Windows due to incorrect directory separator character

### ISSUE THREAD

**Issue by Feng94** [sigp/lighthouse#165]
## Description

When doing a cargo build in Windows it may fail.

This is due to the build.rs file in protos folder using a hardcoded backwards slash `/` character for a directory which is the opposite of Windows' (`\`). The build should work for both UNIX and Windows systems and therefore it should obtain the correct system directory separator.

## Present Behaviour

It uses a string literal "src/" for a folder, causing the build to fail on Windows.

## Expected Behaviour

It should use the appropriate directory separator character for the system.

## Steps to resolve

1.) Replace hardcoded slash with a dynamic system directory separator string.

**Comment by Feng94** [comment]
I think I don't have permission access the repo yet, but I made local commit for it. The screenshot below could give you guys a heads up review on what's coming.

![image](https://user-images.githubusercontent.com/8751189/51613837-74f10580-1f78-11e9-9e73-5d22a720c6f7.png)

**Comment by paulhauner** [comment]
Hey, looks good @Feng94! Thanks for building on Windows, this is a big help.

If you've solved it, [create a PR](https://www.dasblinkenlichten.com/how-to-create-a-github-pull-request-pr/) and we'll get it merged!
