### ISSUE TITLE
Add a CLI command for exiting validators

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1652]
## Description

Presently we don't have a way for validators to submit a `VoluntaryExit`. Once #1569 is merged, I think we should create a tool that uses the BN [`pool/voluntary_exits`](https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolVoluntaryExit) endpoint.

I expect it would look something like this:

```
lighthouse account validator exit --beacon-node http://localhost:5052 --keystore my-keystore.json --password-file my.pass
```

- If `--password-file` is not supplied, it should be requested interactively. 
- `--beacon-node` can have a default value.

## Additional Info

Here's a ready-made function to do a HTTP request to a beacon node: https://github.com/sigp/lighthouse/blob/f14e58b27493807c0fc628f05422271d438fb48d/common/eth2/src/lib.rs#L491-L507

**Comment by pawanjay176** [comment]
Taking this one
