### ISSUE TITLE
Add a flow for validator top-ups

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1653]
## Description

We currently have a flow for creating validator deposits (`lighthouse validator deposit`) but it doesn't gracefully handle top-ups.

I haven't put a lot of thought into how to resolve this. It would be easiest if we could modify the existing `deposit` command to suit, but I'm not sure how elegant that will be.

**Comment by pawanjay176** [comment]
I'll take this guy.

**Comment by paulhauner** [comment]
@pawanjay176 started work on this in #1694 but we closed it since we decided against doing Eth1 transactions from LH anymore. That PR could be revived so it just outputs the Eth1 tx data (without actually sending it).

**Comment by pawanjay176** [comment]
> That PR could be revived so it just outputs the Eth1 tx data (without actually sending it).

@paulhauner This should be doable. However, even if we do this, I'm not sure if there is any existing, tooling that would send the tx data to the correct deposit contract address and invoke the correct function in the contract. The launchpad `deposit_data*.json`
Would it make sense to have one without the other?

**Comment by paulhauner** [comment]
Closing this since we're not getting demand for it and we can leave it up to third-party tooling.
