### ISSUE TITLE
Compilation fails due to missing function "assembly" in blst dependency

### ISSUE THREAD

**Issue by christianscharr** [sigp/lighthouse#1659]
I am trying to install/compile to my RaspberryPi with Ubuntu 20.04.1 LTS following your installation instructions on https://lighthouse-book.sigmaprime.io/pi.html

```
[...]
Compiling lru-cache v0.1.2
Compiling quicksink v0.1.2
Compiling blst v0.1.1 (https://github.com/sigp/blst.git?rev=284f7059642851c760a09fb1708bcb59c7ca323c#284f7059)
error[E0425]: cannot find function 'assembly' in this scope
  --> /home/ubuntu/.cargo/git/checkouts/blst-4627ab328529f030/284f705/bindings/rust/build.rs:63:5
   |
63 |     assembly(&mut file_vec, &build_dir);
   |     ^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try 'rustc --explain E0425'.
error: could not compile 'blst'.
```

**Comment by michaelsproul** [comment]
Hi @christianscharr, this error indicates that your OS is 32-bit, when you need a 64-bit OS to compile and run Lighthouse. Sorry that the error is so obscure, I've opened another issue to track the improvement of that (https://github.com/sigp/lighthouse/issues/1661).

More info on getting up and running with a Pi is available here: https://lighthouse-book.sigmaprime.io/pi.html

I'll close your issue for now but please let us know if you have any further problems!
