### ISSUE TITLE
MacOS binary

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1674]
I'm trying to run the [Running Bird](https://github.com/sigp/lighthouse/releases/tag/v0.2.12) release for Spadina. It is the first time I try the precompiled binaries.

I tried to execute the binary "x86_64-unknown-linux-gnu: AMD/Intel 64-bit processors (most desktops, laptops, servers)" (both the portable and non-portable versions) and get a "cannot execute binary file" error:

```
Justins-MBP:Downloads justin$ ./lighthouse --help
-bash: ./lighthouse: cannot execute binary file
```

![Screenshot 2020-09-27 at 18 14 08](https://user-images.githubusercontent.com/731743/94371288-47654380-00ed-11eb-81fd-e978f2f5c6c5.png)

Are the precompiled binaries meant to work for MacOS?

**Comment by michaelsproul** [comment]
Hey @JustinDrake, at the moment we don't ship binaries for macOS, although we definitely should! I'll leave this issue open to track that task

It should just be a matter of adding a target to our cross-compilation toolchain

**Comment by paulhauner** [comment]
> It should just be a matter of adding a target to our cross-compilation toolchain

As discussed offline with @michaelsproul, it's not this easy as `cross` doesn't support `x86_64-apple-darwin`. We'll need to either figure out Linux > MacOS cross compile or build on an actual Mac.

**Comment by danielschonfeld** [comment]
doesn't Parity use sccache to achieve this?

**Comment by paulhauner** [comment]
> doesn't Parity use sccache to achieve this?

I'm not familiar with it. I had a look, I'm not sure if it relates specifically to MacOS?

**Comment by realbigsean** [comment]
PR in `cross` to support `x86_64-apple-darwin`: https://github.com/rust-embedded/cross/pull/480
