### ISSUE TITLE
What is verify_exit_time_independent_only used for?

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1676]
As far as I can tell `verify_exit_time_independent_only` (defined in verify_exit.rs) is not used anywhere. Is that correct? May be a nice simplification to remove both `verify_exit_parametric` and `verify_exit_time_independent_only`.

**Comment by michaelsproul** [comment]
You're quite right, it used to be used by the op pool to bypass some of the checks, but it's no longer necessary since the P2P spec defined validity conditions for accepting voluntary exits from the network.

**Comment by paulhauner** [comment]
Resolved via #2509
