### ISSUE TITLE
Enhancement - add --network parameter

### ISSUE THREAD

**Issue by yorickdowne** [sigp/lighthouse#1689]
## Description

Currently, lighthouse uses `--testnet <testnet>` to choose between medalla, spadina, "others".

Come main net, it would be useful to have a `--network <network>` parameter that can take main as well as medalla and other supported test networks.

Rationale: Makes life easier with docker-compose. The same entrypoint or command structure can be used for main and testnet, just the name of the network changes. Needing to choose between `--testnet <testnet>` and "something else" for mainnet is cumbersome via `.env`

**Comment by pawanjay176** [comment]
Agree, the `--testnet` flag aims to capture the network but was poorly named.
