### ISSUE TITLE
Peer scoring questions

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1700]
I have a couple questions about `score.rs`:

1) Is `PeerAction::_ValidMessage` used anywhere? (As far as I can tell it's not.) Does this mean peer scores always remain between `DEFAULT_SCORE` (0.0) and `MIN_SCORE` (-100.0)?
2) The "~15 occurrences will get the peer banned" comment for `PeerAction::HighTolerance` doesn't seem to match the code. Should it be ~50 occurrences instead?

**Comment by paulhauner** [comment]
> Is PeerAction::_ValidMessage used anywhere? (As far as I can tell it's not.) Does this mean peer scores always remain between DEFAULT_SCORE (0.0) and MIN_SCORE (-100.0)?

We used to provide positive scores, but found that they introduced a risk of gaming the system by pumping your score and then doing naughty things. Positive scoring has been abandoned until we can devise an appropriate scheme.

> The "~15 occurrences will get the peer banned" comment for PeerAction::HighTolerance doesn't seem to match the code. Should it be ~50 occurrences instead?

I'd have to defer to @AgeManning or @divagant-martian for this.

**Comment by divagant-martian** [comment]
> Is PeerAction::_ValidMessage used anywhere? (As far as I can tell it's not.) Does this mean peer scores always remain between DEFAULT_SCORE (0.0) and MIN_SCORE (-100.0)?
It's been awhile since I last dealt with scores, but as far as I can tell our scores only go down atm with an exponential decay of `2^[-(time since updated) /600]`. The original idea was either make scores go up with successfully received messages or wrt the time they have been connected to us. Since a successfully received message might actually be a bad message, I think we ditched that part. For for a final explanation @AgeManning will be more up to date.

> The "~15 occurrences will get the peer banned" comment for PeerAction::HighTolerance doesn't seem to match the code. Should it be ~50 occurrences instead?
You are right, this looks outdated, but I'm not sure what Age has in mind for this

Originally, the idea was either

**Comment by AgeManning** [comment]
Yep. The scoring system is still experimental. We are tweaking as we go. 

We've removed positive scoring as it was deemed to high of a risk and opens up lots of strategies to game the system. The negative scores (with decays) seem to be the safest approach for our current needs. It works such that we remove non-performant/malicious peers. 

It seems to work particularly well when user's port forward. Once we've reached our target peer count of 50 (by default) we allow an additional 10% to connect to us. Every 30 seconds we prune excess peers keeping those with better scores and some other heuristics. 

The comments need to be updated.

**Comment by AgeManning** [comment]
I'm considering this issue resolved.

**Comment by JustinDrake** [comment]
@AgeManning: Is point 2 resolved? As far as I can tell the comment "~15 occurrences will get the peer banned" still needs fixing.

**Comment by AgeManning** [comment]
Thanks for pointing this out. I'll update the comments in the PR I'm currently working on. Thanks!
