### ISSUE TITLE
Suboptimal voluntary exit pruning logic

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#1708]
The voluntary exit pruning logic seems a bit strange and suboptimal:

```rust
    pub fn prune_voluntary_exits(&self, finalized_state: &BeaconState<T>) {
        prune_validator_hash_map(
            &mut self.voluntary_exits.write(),
            |validator| validator.is_exited_at(finalized_state.current_epoch()),
            finalized_state,
        );
    }
```

Could it be more efficient and simpler (and more natural!) to check `validator.exit_epoch == FAR_FUTURE_EPOCH` (as opposed to `validator.is_exited_at(finalized_state.current_epoch())`)?

**Comment by paulhauner** [comment]
I agree, this seems a bit off. I haven't looked into it in detail, though.

**Comment by michaelsproul** [comment]
Yeah, agree we should prune all exits for `validator.exit_epoch != FAR_FUTURE_EPOCH`, so they get flushed out quicker and we don't need to wait for the exit epoch itself.
