### ISSUE TITLE
Out-of-date dependencies

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1712]
## Description

We currently have several out-of-date dependencies which cannot be updated for various reasons. Whilst there's no immediate cause for concern, it's ideal for us to unblock these updates. This issue tracks these blockers.

- `db-key`: cannot be upgraded since `leveldb` uses `0.0.5`.
- `ring`: cannot update since it requires a version of `cc` that cannot be reconciled with the `web3` crate
- ` web3`: cannot update since the later versions removed support for IPC and it has yet to be reintroduced.
- `enr`: we maintain this crate and have chosen not to update it at this time.
- `discv5`: as above.

**Comment by blacktemplar** [comment]
Update:

Some out of date dependencies get updated here: https://github.com/sigp/lighthouse/pull/2032

A list of out of date dependencies that can't get updated currently:



Dependency | Blocking Reson
-- | --
bytes 0.5.6→0.6.0 | reqwest requires bytes ^0.5 (https://github.com/seanmonstar/reqwest/pull/1076)
db-key 0.0.5→0.1.0 | leveldb requires db-key ^0.0.5
flate 1.0.14 → 1.0.19 | zip requires flate <= 1.0.14 (https://github.com/zip-rs/zip/blob/f5061c25e92c8808f27afbc7ea42f0bdc563c9c4/Cargo.toml#L15)
ring 0.16.12 → 0.16.18 | requires cc >= 1.0.61 which conflicts with web3 cc <=1.0.41 subdependency
tokio-tuil 0.4.0 → 0.5.0 | requires bytes ^0.6 which conflicts with libp2p bytes ^0.5
web3 0.11.0 → 0.13.0 | removed IPC support
tokio 0.2.22 → tokio 0.3.5 | httpmock requires tokio ^0.2
unsigned-varint fork | tokio-util updated to 0.4.0 + other updates (needed for tokio 0.3) (https://github.com/paritytech/unsigned-varint/pull/38)
libp2p fork | gossipsub implementation (https://github.com/libp2p/rust-libp2p/pull/1720)
warp fork | update to tokio 0.3 (https://github.com/seanmonstar/warp/pull/753, https://github.com/seanmonstar/warp/pull/741)
discv5 fork | ?
milagro_bls fork | why not submit to crates.io?
hyper fork | ?

**Comment by kirk-baird** [comment]
That's a good question, I'm happy to have it on crates.io, what are your thoughts @paulhauner?

Also it is worth updating `milagro_bls` to `v1.4.1` from `v1.4.0` as it fixes naming issues for windows users. (i.e. removes `:`)

**Comment by blacktemplar** [comment]
I just saw that the web3 got updated in https://github.com/sigp/lighthouse/pull/1989, updated the table :)

**Comment by michaelsproul** [comment]
> I just saw that the web3 got updated in #1989, updated the table :)

Mere hours after you did, they released a new version, 0.14! :weary: It doesn't help us much (no IPC, no Tokio 0.3), so I don't think we need to rush to update: https://github.com/tomusdrw/rust-web3/releases/tag/v0.14.0

**Comment by michaelsproul** [comment]
Closing this as it's out of date and I don't think we need it: we have `cargo audit` for urgent updates and gardening PRs like #3136 for ongoing maintenance updates.
