### ISSUE TITLE
Large enum variant in store

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1713]
## Description

There is an enum in the `store` which contains variants with largely varying sizes:

https://github.com/sigp/lighthouse/blob/d9f4819fe0adedd5e0a778b4f68189e8767977bb/beacon_node/store/src/lib.rs#L121-L130

Eyeballing this, it seems that clippy is right and we should definitely `Box` the block and possible the `Cow<BeaconState>` (I'm not sure if the `Cow` needs boxing).

**Comment by michaelsproul** [comment]
I've fixed this while working on #800
