### ISSUE TITLE
Standard HTTP API `validator` response values unquoted

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#1717]
The output of `/eth/v1/beacon/states/head/validators` in `v0.3.0-staging` commit `6ea3bc5e5214c3c625ef60ca4b325073bd0cfa4d` contains unquoted integers:

```
  "data": [
    {
      "index": "0",
      "balance": "31706219156",
      "status": "Active",
      "validator": {
        "pubkey": "0x8fcf28896a85e5e76ee9e508438e23e7253da1a23a6501e3a7d56182520dbcf4cdb44af3267318188f1f4168342146da",
        "withdrawal_credentials": "0x0010361af430aa7ab4a9567eaaca50ec5e02315ca1513d9ee8d73bde96370091",
        "effective_balance": 31000000000,
        "slashed": false,
        "activation_eligibility_epoch": 0,
        "activation_epoch": 0,
        "exit_epoch": 18446744073709552000,
        "withdrawable_epoch": 18446744073709552000
      }
    },
```

The fields `effective_balance`, `activation_eligibility_epoch`, `activation_epoch` and `withdrawable_epoch` should all be quoted.

**Comment by michaelsproul** [comment]
A comprehensive solution to quoting of slots and epochs in the API could involve reverting the changes made in https://github.com/sigp/lighthouse/pull/1597, which I intended to have redone once the new API was adopted (i.e. quote slots and epochs by default on serialisation).

**Comment by mcdee** [comment]
Now that 0.3.0 has been released and the old API has gone away is there a timeline to address this?  Worth pointing out that the current system is unusable for some situations (_e.g._  `exit_epoch` is returned as 18446744073709552000 which is not `FAR_FUTURE_EPOCH` 18446744073709551615 so active validators can be marked as exiting).

**Comment by michaelsproul** [comment]
Thanks @mcdee, that makes this big more severe than we initially realised. Will correct ASAP (the fix PR is up and will likely merge tomorrow)
