### ISSUE TITLE
Remove "unsafe" block in BLST bindings

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1720]
## Description

There is an `unsafe` block in our `crypto/bls` crate that I think should be moved into `blst`:

https://github.com/sigp/lighthouse/blob/32338bcafa90e481fc841a94bb7c9016fdc34664/crypto/bls/src/impls/blst.rs#L67-L73

## To resolve

Follow up on https://github.com/supranational/blst/issues/13

**Comment by ayushmishra2005** [comment]
@paulhauner I would like to pick this issue. As a first step, I have raised a PR in `blst` library https://github.com/supranational/blst/pull/52/files to expose safe blst_scalar constructors.

Once this PR gets merged, I would make corresponding changes here https://github.com/sigp/lighthouse/blob/32338bcafa90e481fc841a94bb7c9016fdc34664/crypto/bls/src/impls/blst.rs#L67-L73

**Comment by paulhauner** [comment]
I'm going to close this since BLST doesn't seem interested in providing the functionality.
