### ISSUE TITLE
Prepare deposit tools for mainnet

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1727]
## Description

Currently lighthouse provides two CLI tools which perform deposits on the eth1 chain:

- `lighthouse account validator deposit`
- `lighthouse account validator topup` (currently in #1694).

These two tools are suitable for testnets, but they need revisiting before we go to mainnet.

## Detail

Here are some known issues:

- Lockfiles are not cleaned up after a ctrl+c whilst waiting for a transaction to complete.
- The deposit data file is not written to disk until *after* the transaction is completed, this can lead to duplicate deposits.
- It relies upon the eth1 node to do the signing, which is generally avoided.

## Steps to resolve

I think we need to do a good re-think about how we currently handle submitting eth1 transactions. I am attracted to the idea of doing the eth1 tx signing *inside* lighthouse, but that means quite a bit of work on our end.

Another alternative is to never submit eth1 transactions with Lighthouse, instead only output transaction data which the user will need to sign and submit. A potential way to do this would be to define some standard eth1-transcation output (e.g., tx data, to address, amount in JSON) and then create a simple web interface for submitting these transactions via Metamask.

**Comment by danielschonfeld** [comment]
From what I understand the general concensus these days is that only audited deposit tools should be used, and as such some clients are removing above mentioned functionality (e.g Prysm)

**Comment by paulhauner** [comment]
> some clients are removing above mentioned functionality (e.g Prysm)

This thought did cross my mind as well. It's appealing.
