### ISSUE TITLE
Investigate simulator issues

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1729]
## Description

Although the simulator passes all its tests, this appears just to be because of Lighthouse's resilience to following head. The simulator actually appears to not perform as it was designed. 

There are two points in particular that should be investigated. 

1. The nodes do not discover each. The nodes in the simulator maintain a connection to the boot node and via the bootnode manage to stay in sync via gossip and rpc. The correct behaviour is for all the nodes to discover and connect to each other. I suspect one issue is that we have prioritised different kinds of discovery queries. As we have sped up the clock time, I think potentially we are constantly performing subnet discoveries and nodes never have a chance to to perform regular queries. 
If this hunch is correct, perhaps it is better logic to not prioritise discovery queries to allow nodes to also search for peers.

2. @blacktemplar has a set of logs which show that we are subscribing and immediately unsubscribing to subnets in the simulator. This seems to indicate an issue with the attestation service. We should only be unsubscribing after we have attested to the subnet. This issues needs further investigation.

**Comment by pawanjay176** [comment]
The discovery issue (nodes not discovering one other) seems to be because of badly configured udp ports in the simulator. 
Investigating the other issues.

**Comment by AgeManning** [comment]
Resolved in #1747
