### ISSUE TITLE
Simulator networking locking

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#1730]
## Description

The simulator shows that in short time frames potentially before genesis nodes are not responding to libp2p requests. This is indicative of a locked executor at some point, or incorrect polling of the network stack. 

Attached are some simulator logs demonstrating this. Notice that node_3 gets disconnected due to not responding to the boot-nodes ping requests. 

There is a blocking task (the UPnP task) running, but it seems to finish before the second ping and the node should respond. I'm not convinced its the UPnP task that is locking, but there is something here that prevents nodes from responding to requests. 

This could be a source of invalid lighthouse scores that @blacktemplar is seeing on testnets with 1.1 scoring params. 

Logs are attached.

[logs.txt](https://github.com/sigp/lighthouse/files/5325593/logs.txt)

**Comment by pawanjay176** [comment]
Fixed (hopefully) in #1747.
