### ISSUE TITLE
validator process fail to connect to beacon node from a different machine in LAN

### ISSUE THREAD

**Issue by somuchid** [sigp/lighthouse#1737]
two machines: beacon node ip 176, validator process ip 181

(1) from 176, beacon node

1.1 run  $ifconfig
inet 192.168.1.176

1.2 run $lighthouse bn --eth1 --datadir ~/lighthouseData --http-address 192.168.1.176 --http-port 5052

with/without
either --http-allow-origin=* 
or    --http-allow-origin=192.168.1.181

(2) from ip 181, validator process

2.1 run $ifconfig
inet 192.168.1.181

2.2 run $telnet 192.168.1.176 4000
Trying 192.168.1.176...
telnet: Unable to connect to remote host: Connection refused

2.3 run $lighthouse vc --server=http://192.168.1.176:5052
error message:
Oct 06 11:49:11.125 ERRO Unable to connect to beacon node        error: "ReqwestError(reqwest::Error { kind: Request, url: \"http://192.168.1.176:5052/node/version\", source: hyper::Error(Connect, ConnectError(\"tcp connect error\", Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })) })"

(3) run beacon node and validator process in the same box with non-default

3.1 from ip 176 beacon node
run $lighthouse bn --eth1 --datadir ~/lighthouseData --http-address 192.168.1.176 --http-port 5052

with/without
either --http-allow-origin=* 
or    --http-allow-origin=192.168.1.176   (allow ip is different with number 2)

3.2 from ip 181, validator process
run lighthouse vc --server=http://192.168.1.176:5052

error message same as number 2:
Oct 06 11:54:42.964 ERRO Unable to connect to beacon node        error: "ReqwestError(reqwest::Error { kind: Request, url: \"http://192.168.1.176:5052/node/version\", source: hyper::Error(Connect, ConnectError(\"tcp connect error\", Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })) })"

(4) in ip 176 beacon node, ubuntu firewall is on or off, no difference
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 5052/tcp                   ALLOW IN    Anywhere
[ 2] 5052/tcp (v6)              ALLOW IN    Anywhere (v6) 

(5) OK to run beacon node and validator process in the same box with default 127.0.0.1:5052

(6) OK to run prysm in same setup, separate validator and beacon node into two machines.

**Comment by pawanjay176** [comment]
@somuchid you are missing the `--http` flag in the beacon node. The other arguments will change the address, port and cross-origin policies for the server, but `--http` is still required to start the server.

**Comment by somuchid** [comment]
works now, in Oct. 8 build. Thanks a lot.
