### ISSUE TITLE
v0.3.0 doesn't create validator_definitions.yml if it's missing

### ISSUE THREAD

**Issue by yorickdowne** [sigp/lighthouse#1744]
## Description

Running cut-v0.3.0, when importing keys, assuming /var/lib/lighthouse exists and is given as a --datadir, the validator will not create the validator_definitions.yml file under it.

```
yorick@ethlinux:~/eth2-zinken-lh$ docker-compose run validator-import
Do all validator keys have the same password? (y/n) y
Running account manager for zinken testnet
validator-dir path: "/var/lib/lighthouse/validators"
Unable to open validator_definitions.yml: UnableToWriteFile(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

The entrypoint looks like this:

```
      - query-lh-validator-passwords.sh
      - lighthouse
      - account
      - validator
      - import
      - --datadir
      - /var/lib/lighthouse
      - --directory
      - /var/lib/lighthouse/validator_keys
      - --testnet
      - ${TESTNET}
```
where the shell script just decides whether to add `--reuse-password` to the command line and otherwise just runs `$@` as is.

**Comment by yorickdowne** [comment]
This might be instructive. If I call this with `--validator-dir /var/lib/lighthouse/validators` instead, I get this output:

```
yorick@ethlinux:~/eth2-zinken-lh$ docker-compose run validator-import
Do all validator keys have the same password? (y/n) y
Running account manager for zinken testnet
validator-dir path: "/nonexistent/.lighthouse/zinken/validators"
Unable to open validator_definitions.yml: UnableToWriteFile(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

It looks like it ignores the directory it's being given and tries to use the user's home directory, which doesn't exist

**Comment by pawanjay176** [comment]
@yorickdowne Thank you so much for testing this early :) We'll be pushing a fix soon!

**Comment by yorickdowne** [comment]
I wonder whether that PR will do it. I have /var/lib/lighthouse/validators existing and with 700 permissions to the user lighthouse runs at, and I get the below error when I move validator-dir a little earlier:

```
Running account manager for zinken testnet
validator-dir path: "/var/lib/lighthouse/validators"
Unable to open validator_definitions.yml: UnableToWriteFile(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by yorickdowne** [comment]
Take it back, this will work. validators subdir exists in docker, but docker-compose maps a volume in which masks it. Looking forward to seeing this and testing it.
