### ISSUE TITLE
Method not allowed after upgrade 0.3.0

### ISSUE THREAD

**Issue by ChuckNorrison** [sigp/lighthouse#1753]
## Description

Updated from last release to current release. 

- Moved my medalla testnet folders to the medalle subdirectory as proposed in the release docs. 
- Updated the validator_definitions.yml in /medalla/ folder with new path to the validators
- Run with `lighthouse b --testnet medalla --purge-db` without any issues and stopped 
- Started my systemd service with new datadir 

## Version

https://github.com/sigp/lighthouse/releases/tag/v0.3.0

## Present Behaviour

> Oct 09 16:01:35 ethereum lighthouse[158557]: Oct 09 16:01:35.011 WARN Error processing HTTP API request       method: GET, path: /beacon/head, status: 405 Method Not Allowed, elapsed: 165.665µs
> Oct 09 16:01:35 ethereum lighthouse[158557]: Oct 09 16:01:35.192 WARN Error processing HTTP API request       method: GET, path: /network/peers, status: 405 Method Not Allowed, elapsed: 93.683µs
> Oct 09 16:01:36 ethereum lighthouse[158557]: Oct 09 16:01:36.012 WARN Error processing HTTP API request       method: GET, path: /beacon/head, status: 405 Method Not Allowed, elapsed: 91.571µs
> Oct 09 16:01:37 ethereum lighthouse[158557]: Oct 09 16:01:37.013 WARN Error processing HTTP API request       method: GET, path: /beacon/head, status: 405 Method Not Allowed, elapsed: 125.442µs
> Oct 09 16:01:38 ethereum lighthouse[158557]: Oct 09 16:01:38.000 INFO Syncing                                 est_time: 12 hrs 22 mins, speed: 10.67 slots/sec, distance: 474995 slots (9 weeks 2 days), peers>
> Oct 09 16:01:38 ethereum lighthouse[158557]: Oct 09 16:01:38.014 WARN Error processing HTTP API request       method: GET, path: /beacon/head, status: 405 Method Not Allowed, elapsed: 112.175µs

## Steps to resolve

Check for outdated gRPC connections (i.e. eth2stats-client)

**Comment by ChuckNorrison** [comment]
zinken will start tomorrow and this issue will prevent me from testing this client

**Comment by pawanjay176** [comment]
@ChuckNorrison are you running the beacon node with `--staking` flag?

What command are you using to run the validator client?

**Comment by ChuckNorrison** [comment]
i do not use `--stacking`

Validators are running with:
`lighthouse vc --testnet medalla --debug-level info --secrets-dir /home/xxx/.lighthouse/medalla/secrets --datadir /home/xxx/.lighthouse/medalla`

**Comment by ChuckNorrison** [comment]
I restarted my service and cause purge-db is set for compatibility it needs another 8 hours for syncing to get this error and after this error it comes to that one https://github.com/sigp/lighthouse/issues/1757

Can anybody confirm basic functionality of this lighthouse client?

**Comment by pawanjay176** [comment]
You need to run the beacon node with the `--staking` flag to enable the http server. You are getting those errors because you don't have a http server running on the beacon node. Your validator command is correct.

**Comment by ChuckNorrison** [comment]
and why --http exists here?

**Comment by pawanjay176** [comment]
`--staking` is an alias for `--http --eth1`. Those are the 2 flags you need to run a staking validator which is what it seems that you want to do. 

`--staking` was introduced in an earlier release https://github.com/sigp/lighthouse/releases/tag/v0.2.12.

**Comment by ChuckNorrison** [comment]
whats wrong with this:
`lighthouse beacon_node --testnet medalla --http --eth1-endpoint http://m.y.i.p:8545 --datadir /home/xxx/.lighthouse/medalla`

**Comment by pawanjay176** [comment]
This should work too.

**Comment by ChuckNorrison** [comment]
and it doesnt anymore after upgrade 0.3.0 nd after downgrade 0.2.13 i got a new error #1757 even i use purge-db

**Comment by realbigsean** [comment]
@ChuckNorrison those logs indicate something is querying your node with the old API. If you are running an eth2stats clients, you should update it.

**Comment by ChuckNorrison** [comment]
Ok that true, iam running eth2stats docker client as third gRPC connection.

I will try to upgrade 0.3.0 again.

**Comment by michaelsproul** [comment]
Glad you got v0.3 working! I'll close this now as it's related to `eth2stats` rather than Lighthouse itself.
