### ISSUE TITLE
Could not send message to the sync service, error: channel closed

### ISSUE THREAD

**Issue by ChuckNorrison** [sigp/lighthouse#1757]
## Description

This console out appears unexpected without any informations whats wrong. 

## Version

0.2.13

## Present Behaviour
After i failed my upgrade to 0.3.0 i downgraded back to 0.2.13 and synced again with `--purge-db`. My beacon node gets started with following command:

`lighthouse beacon_node --testnet medalla --http --eth1-endpoint http://m.y.i.p:8545 --datadir /home/xxx/.lighthouse/medalla`

Console outs:
Oct 11 12:24:39 ethereum lighthouse[182165]: Oct 11 12:24:39.132 WARN Could not send message to the sync service, error: channel closed

**Comment by pawanjay176** [comment]
Can you give a little more context? 
What commands are you using for beacon node and validator client. A few more logs would be helpful.

**Comment by ChuckNorrison** [comment]
@pawanjay176 updated, thanks for your response

I restarted the service and it seems to work. This issue seems to happen after --purge-db was used and syncing the beacon chain with 0.2.13

**Comment by ChuckNorrison** [comment]
I upgraded to 0.3.0 successful, can be closed
