### ISSUE TITLE
Unable to initialize validators | LockfileExists

### ISSUE THREAD

**Issue by Joera** [sigp/lighthouse#1758]
Hi, i think i screwed up while changing the folder structure after upgrading to 0.3.0

the error i get is 

CRIT Failed to start validator client        reason: Unable to initialize validators: LockfileExists("/var/lib/lighthouse/medalla/validators/validator_key_cache.json.lock")

I tried removing that lock file, but it keeps coming back ((( 

Any idea where i might have gone wrong? 

Thanks, Joera

**Comment by realbigsean** [comment]
@Joera make sure the `voting_keystore_path` field in the `validator_definitions.yml` is correct. If it's not, the validator client will create the lockfile and exit before the lockfile is cleaned up

**Comment by ChuckNorrison** [comment]
You seen this flag from release notes?

> Lockfiles on EIP-2335 keypairs are now strictly enforced. The --delete-lockfiles flag can be used to recover from a scenario where the validator client detects existing lockfiles from a previous crash. Use --delete-lockfiles with caution and read the CLI help first.

**Comment by Joera** [comment]
Hi, thanks for your answers. Problem solved. I turned out that while making changes to validator_definitions.yml i had deleted a line. That prompted a 'shutdown' and creation of the .lock file.  (should have read the error log from top down instead of bottom up ;) )
