### ISSUE TITLE
Chrome requests failing for VC API

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1766]
## Description

I've had a report that a user is unable to make calls from a Chrome browser to the VC API (whilst the BN API works).

We can prove/disprove this bug by:

1. Starting a VC API `lighthouse vc --http --http-allow-origin "*"`
1. Getting Chrome to call `GET lighthouse/version`.

Chrome should report that a "pre-flight check" has failed.

## Notes

- I have not tried to replicate this.
- I would have expected the BN and VC to exhibit identical behaviour in this regard.
- I understand the the pre-flight check involves a HTTP `OPTION` call. I'm not sure how `warp` deals with this.

**Comment by danielharrison** [comment]
@realbigsean thanks for taking a look. I was the one who was having issues.

The problem I'm having is making the request via JS - using fetch. I can ping the endpoint OK by hitting the URL, but an actual JS request from 127.0.0.1 is failing with:

`Access to fetch at 'http://127.0.0.1:5062/lighthouse/version' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

To replicate, drop this piece of code in to any JS project running on a local server:
`
fetch(
	'http://127.0.0.1:5062/lighthouse/validators', 
	{ 
		method: 'GET', 
		headers: {
			'Authorization': 'Basic api-token-0x02b3fe41382d3e06ef4591be66da5a5e523e62cdf402245ea6f0b2ef5a2685e326',
			'Content-Type': 'application/json',
			'Origin': 'http://127.0.0.1:3000'
		}
	}
)
	.then(response => response.json())
	.then(({data}) => {
		console.log('passed', data)
	})
	.catch(e => {
		console.log('failed', e.message)
	})
`

Note: using the BN api works fine via js, but I'm not having to pass the auth header to the BN endpoint.

**Comment by danielharrison** [comment]
A small update: when making an api request using fetch, and including any type of headers, the system will make 2 requests, an initial preflight request (which is failing) and then the real one. 

You can see this in the console:

![Screen Shot 2020-10-14 at 12 37 11 pm](https://user-images.githubusercontent.com/3677220/95933333-002fc000-0e1a-11eb-8ccc-7689321e1f70.png)

**Comment by paulhauner** [comment]
Thanks @danielharrison, I've started on a fix in #1772.
