### ISSUE TITLE
Excessive pooled attestation count

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1769]
## Description

@protolambda has reported seeing a very high number of attestations on eth2stats:

![photo_2020-10-14_12-27-34](https://user-images.githubusercontent.com/6660660/95932901-c6aa8500-0e18-11eb-82bc-37569efdbf0c.jpg)

The metric here is being obtained by calling [`beacon/pool/attestations`](https://ethereum.github.io/eth2.0-APIs/#/Beacon/getPoolAttestations), which contains all attestations in the op pool and the naive aggregation pool:

https://github.com/sigp/lighthouse/blob/467de4c8d0bab31bcbbe2d830af31fd3ecedda75/beacon_node/http_api/src/lib.rs#L842-L853

## Notes

- There's likely duplicates because we don't dedup between op pool and naive aggregates.

**Comment by michaelsproul** [comment]
It's particularly bad at the moment because of the lack of finalisation

**Comment by michaelsproul** [comment]
Our attestation pruning is too conservative, it only deletes relative to the finalized state's epoch, but could safely use the current epoch IMO. I.e. prune attestations with targets older than or equal `current_epoch.saturating_sub(2)`.

I'll raise a PR
