### ISSUE TITLE
Fork choice timing attack

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1773]
## Description

There is an attack described at https://github.com/ethereum/eth2.0-specs/pull/2101 which is a general attack against the Eth2 protocol. In that issue are some steps outlined to protect against it.

This fix can be delayed until post-mainnet launch, if required. The EF will not consider us to be in violation of the spec.

**Comment by michaelsproul** [comment]
Upstream spec PR was closed, and we have a myriad of other fork choice attack mitigations these days :grin:, e.g. proposer boost
