### ISSUE TITLE
Howto batch-request multiple validator information with new API

### ISSUE THREAD

**Issue by computerlyrik** [sigp/lighthouse#1774]
## Description

i used `[POST] /beacon/validators` to retrieve information about my validators in one request.

The POST recieves a list of pubkeys (e.g. 0xdeadbeef) and returns a list of validator information.

This endpoint seems to have gone with newer lighthouse versions.
Now https://ethereum.github.io/eth2.0-APIs is in place

## Version

New version i use is `Docker v0.3.0`

## Present Behaviour

Response of the lighthouse beacon is `[405] Method not allowed`

## Expected Behaviour

Return with a List of validators

## Steps to resolve

see above, try to issue a POST request with a List of pubkeys (of validators) on the given endpoint.

Question: 

**How do i request multiple validator information within _one_ request?**

I see following alternatives, involving the endpoint https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateValidator

- GET ​/eth​/v1​/beacon​/states​/head​/validators​/0xdeadbeef
- GET ​/eth​/v1​/beacon​/states​/0xdeadbeef/validators​/0xdeadbeef

**Comment by paulhauner** [comment]
> How do i request multiple validator information within one request?

You can join supply multiple indices (or pubkeys) in the `id` param: 

```
GET /eth/v1/beacon/states/{state_id}/validators?id=1,2,3,4
```
