### ISSUE TITLE
Implement newtypes for `Slot` and `Epoch`

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#181]
## Description

Implement `Slot` and `Epoch` newtypes. To ensure we have type-safety between the two.

## Present Behaviour

The new `v0.1` spec makes "epochs first class citizens" and uses `Epoch` in some scenarios and `Slot` in others.

It is easy to get the two mixed up and this would result in significant, difficult-to-find errors.

## Expected Behaviour

Enforce type safety.

## Steps to resolve

Implement newtypes with the minimum required math/conversion/utility implementations (e.g., `From`, `Add`, `Sub`, etc)

**Comment by paulhauner** [comment]
I will be working on this next

**Comment by AgeManning** [comment]
This has been completed.
