### ISSUE TITLE
CRIT: Batch too large to ever be processed

### ISSUE THREAD

**Issue by latetot** [sigp/lighthouse#1825]
## Description

Receiving following critical message on my beacon node.  Seems to be otherwise functioning normally.  

Oct 25 10:04:01.866 CRIT Batch too large to ever be processed    protocol: beacon_blocks_by_range, service: libp2p_rpc, service: libp2p

Message is repeated every couple of minutes at variable times. 

## Version

3.1 (also present prior in earlier version 3.0)

**Comment by divagant-martian** [comment]
Since some time we penalize more blocks by range requests with large steps, so this CRIT no longer represents what it intended (a batch that was too large with a step of one shouldn't reach the rate limiter. This is now outdated so we'll downgrade the log
