### ISSUE TITLE
ValidatorPubkeyCacheLockTimeout, msg: unexpected condition in processing block.

### ISSUE THREAD

**Issue by SeaMonkey82** [sigp/lighthouse#1826]
## Description
Beacon no longer syncs.

## Version
Lighthouse 0.3.1
Rustup 1.22.1
Master 7453f39d68076b052df8abc4ab87fed8466b5e62
## Present Behaviour
```
Oct 25 12:47:39.116 WARN BlockProcessingFailure                  outcome: ValidatorPubkeyCacheLockTimeout, msg: unexpected condition in processing block.
```

## Expected Behaviour
Beacon syncs

**Comment by paulhauner** [comment]
This is commonly due to an overloaded CPU. Do you have some rough system specs and an idea of how much load your CPU has?

**Comment by SeaMonkey82** [comment]
That sounds right.  I'm trying to run all five validator clients.  I believe I was still running on my FX-4170 w/ 32GB RAM when I encountered this.  During the two long periods of non-finality, I've had to migrate everything over to my 9900K w/ 64GB RAM to maintain stability.

**Comment by etimoz** [comment]
Getting the same issue. CPU is overloaded (over 90%) but still syncing slowly.

Specs: Intel Celeron N4100, 8GB RAM, ssd
LOAD    4-core
 1 min:    7.75
 5 min:    7.18
15 min:   6.45

**Comment by paulhauner** [comment]
Thanks for the info. I'm going to close this since it's covered by #1096 already :)
