### ISSUE TITLE
"Failed to decode ProtoArrayForkChoice: InvalidByteLength { len: 168, expected: 184 }"

### ISSUE THREAD

**Issue by jamescbury** [sigp/lighthouse#1833]
## Description
Issue starting lighthouse beacon node after the upgrade to v0.3.1.  I've tried rebuilding several times, but no luck.  I've been following the steps on 'https://someresat.medium.com/guide-to-staking-on-ethereum-2-0-ubuntu-medalla-lighthouse-c6f3c34597a8'

## Version

lighthouse/v0.3.1-92c8eba8
rustc 1.47.0 (18bf6b4f0 2020-10-07)

## Present Behaviour

> Oct 26 23:45:49 house-computer-2 systemd[1]: Started Lighthouse Beacon Node.
> Oct 26 23:45:49 house-computer-2 lighthouse[9440]: Oct 26 23:45:49.844 WARN Ethereum 2.0 is pre-release. This software is experimental.
> Oct 26 23:45:49 house-computer-2 lighthouse[9440]: Oct 26 23:45:49.844 INFO Lighthouse started                      version: Lighthouse/v0.3.1-92c8eba8
> Oct 26 23:45:49 house-computer-2 lighthouse[9440]: Oct 26 23:45:49.844 INFO Configured for testnet                  name: medalla
> Oct 26 23:45:49 house-computer-2 lighthouse[9440]: Oct 26 23:45:49.844 INFO Data directory initialised              datadir: /var/lib/lighthouse/beacon-node
> Oct 26 23:45:50 house-computer-2 lighthouse[9440]: Oct 26 23:45:50.154 INFO Starting beacon chain                   method: resume, service: beacon
> Oct 26 23:45:50 house-computer-2 lighthouse[9440]: Oct 26 23:45:50.603 CRIT Failed to start beacon node             reason: Unable to parse persisted fork choice from disk: InvalidProtoArrayBytes("Failed to decode ProtoArrayForkChoice: InvalidByteLength { len: 168, expected: 184 }")
> Oct 26 23:45:50 house-computer-2 lighthouse[9440]: Oct 26 23:45:50.603 INFO Internal shutdown received              reason: Failed to start beacon node
> Oct 26 23:45:50 house-computer-2 lighthouse[9440]: Oct 26 23:45:50.603 INFO Shutting down..
> Oct 26 23:45:53 house-computer-2 systemd[1]: lighthousebeacon.service: Succeeded.
> Oct 26 23:45:58 house-computer-2 systemd[1]: lighthousebeacon.service: Scheduled restart job, restart counter is at 55.
> Oct 26 23:45:58 house-computer-2 systemd[1]: Stopped Lighthouse Beacon Node.
> 

## Expected Behaviour

Normally lighthouse beacon starts syncing after this.

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
Hey @jamescbury, this is a bit of an obscure looking error, but it means your data directory still has files lying around from v0.2.x. You need to delete them and resync to run v0.3.1.

You could manually `rm -r /var/lib/lighthouse/beacon-node/beacon`, or run the Lighthouse beacon node command with `--purge-db` (just once).

As you're running with a custom datadir, no other migration steps should be necessary, but if you run into trouble the release notes for v0.3.0 contain some more info about migrating: https://github.com/sigp/lighthouse/releases/tag/v0.3.0

**Comment by jamescbury** [comment]
@michaelsproul fantastic - it worked.  I had removed the build files, but not the datadir.  Thanks for the quick response.

And thanks for all the hard work you've put into this - lighthouse is great, can't wait to run it on the mainnet.
