### ISSUE TITLE
0.3.2: CPU incompatible error with Ubuntu AWS instance

### ISSUE THREAD

**Issue by gregbkr** [sigp/lighthouse#1842]
## Description

Hello!

Using the last version 0.3.2 with VPS ubuntu 20.04 on AWS (2CPU 4GB RAM):
```
wget https://github.com/sigp/lighthouse/releases/download/v0.3.2/lighthouse-v0.3.2-x86_64-unknown-linux-gnu.tar.gz
tar -xvf lighthouse-v0.3.2-x86_64-unknown-linux-gnu.tar.gz lighthouse

./lighthouse --testnet medalla beacon --http --http-address 0.0.0.0
CPU incompatible with optimized binary, please try Lighthouse portable build

uname -a
Linux ip-172-31-5-242 5.4.0-1024-aws #24-Ubuntu SMP Sat Sep 5 06:19:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## Version

0.3.2
It is fine with 0.3.0 or 0.3.1

## Present Behaviour

Error : `CPU incompatible with optimized binary, please try Lighthouse portable build`

## Expected Behaviour

It should work on this x64 VPS system.

## Steps to resolve

I will use 0.3.1 or the 0.3.2 portable then.

Thanks!

**Comment by michaelsproul** [comment]
It's strange that the previous non-portable builds worked for you, because in theory they should have been compiled with the same CPU features and would have just crashed with a SIGILL error on a CPU lacking those features. The explicit error is the main new part of 0.3.2

Either way, best to stick to the portable builds for that VPS. If you upgrade your VPS at some point you could see if you can get an instance with ADX instruction support, because that's what the fast build requires. I think the AWS "compute" instances have ADX.

I'll close this issue for now, but please let us know if you run into any other issues ☺️

**Comment by michaelsproul** [comment]
I just ran into this same issue on my Vultr VPS. It seems that the cheap VPS providers are spoofing the CPUID instruction, even on CPUs that support ADX. For example, `cat /proc/cpuinfo` shows a Skylake CPU, but no ADX!

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel Xeon Processor (Skylake, IBRS)
stepping        : 4
microcode       : 0x1
cpu MHz         : 2593.904
cache size      : 16384 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq clwb avx512cd avx512bw avx512vl xsaveopt arat pku ospke
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips        : 5187.80
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

And the CPUID instruction also returns `false` for the ADX flag:

```$ cpuid
extended feature flags (7):
      ...
      ADX instructions                         = false
```

I'm going to test now whether actually executing ADX instructions fails

**Comment by michaelsproul** [comment]
Executing ADX instructions works fine, at least on my VPS, so I've downgraded the error to a warning in this PR https://github.com/sigp/lighthouse/pull/1846
