### ISSUE TITLE
Email list to inform users of critical issues/updates

### ISSUE THREAD

**Issue by dankrad** [sigp/lighthouse#1851]
When critical updates are published, or there are urgent problems with the clients that need all stakers to intervene, there should be a way to quickly get this information out to all Lighthouse users. I recommend:
 *  Setting up an email list that stakers can subscribe to and on which highly critical information can be pushed
 * Additionally, setting up groups/accounts on other channels (twitter, telegram, etc.) can be helpful

Not all users can be expected to constantly monitor discussion channels such as discord, so having a low-noise direct channel that reliably reaches all stakers is essential.

**Comment by paulhauner** [comment]
You can find the mailing list here: https://mailchi.mp/3d9df0417779/lighthouse-dev-updates
