### ISSUE TITLE
Centralize the conditions to decide if a peer is relevant and their sync status

### ISSUE THREAD

**Issue by divagant-martian** [sigp/lighthouse#1856]
## Description

The conditions we use to decide if a peer is advanced, synced or behind, or relevant to the chain to begin with, are split over a couple of different parts of the code and it's not entirely clear how they get along. We should centralize this logic for maintainability and to reason about this more easily.

Parts that I identify:
1. We have [the `process_status` function in the router's processor](https://github.com/sigp/lighthouse/blob/0a0f4daf9d3539ad75e4c50a96ccb910337e3813/beacon_node/network/src/router/processor.rs#L189-L310). This function for some cases disconnects a peer, for others it informs the sync manager and for other ("naive" peer it does nothing else). This last part seems interesting since the sync manages does have the logic to deal with behind peers.
2. We also have the [`PeerSyncInfo`](https://github.com/sigp/lighthouse/blob/0a0f4daf9d3539ad75e4c50a96ccb910337e3813/beacon_node/network/src/sync/peer_sync_info.rs#L53-L108) where we get most of the sync status of a peer if it gets to the sync manager.
3. We have [additional logic in the `SyncManager`](https://github.com/sigp/lighthouse/blob/0a0f4daf9d3539ad75e4c50a96ccb910337e3813/beacon_node/network/src/sync/manager.rs#L279-L308) for when a peer is said to be Advanced wrt to the `PeerSyncInfo`

## Version
master 0a0f4daf9d3539ad75e4c50a96ccb910337e3813

**Comment by paulhauner** [comment]
@divagant-martian please feel free to set this to `A0` if you see fit :)

**Comment by AgeManning** [comment]
Yes. I agree it probably makes sense to group all this logic. 

In my mind these have been behaving as three layers of filters (in the order you have listed them). 

The first is a high level filter. This does basic fork checking and more obvious checks based on their status. If they pass this filter and have some use for sync, they then get further evaluated in `PeerSyncInfo`. 

Depending on this phase, the peer can be either synced, or we may need to start a long-range sync. If we need to do a long range sync we send the peer to that module which then gets further evaluated into the type of long range sync as listed in your point 3. 

There is some small additional logic in the `add_peer()` function in the sync manager also. 

I guess the logic is split as a peer progresses through the different modules router -> manager -> range-sync and each have their own "filtering" or identifying of the peer. 

Curious about how this could be re-structured. If we handle all logic in the router, I think we still have to send the peer -> manager -> range-sync if a range-sync is required.

**Comment by divagant-martian** [comment]
Closed by #1896
