### ISSUE TITLE
Align slasher runs to fixed point in each slot

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1861]
## Description

Presently the slasher (#1567) runs batch updates at a user configurable interval -- optimally once per slot. In future it might be nice to make it so that it runs, e.g. just after most attestations are expected to have been received, or just in time to finish before the next block proposal. This would ensure that a validator doesn't accidentally miss out 

Currently the slasher updates will often run for longer than 12 seconds (particularly when spinning up), so this issue is likely more relevant once we can guarantee its runtime within substantially less than 12 seconds.

**Comment by paulhauner** [comment]
@michaelsproul feel free to set `Ax` status as you see fit :)

**Comment by michaelsproul** [comment]
Working on this currently
