### ISSUE TITLE
Add slasher metrics

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#1863]
## Description

The slasher's internals are somewhat opaque and its performance is a bit mysterious. We should add some metrics to see how much overhead it imposes on the beacon node, and to measure the efficacy of tweaking parameters like `chunk_size` and `validator_chunk_size`.

**Comment by paulhauner** [comment]
@michaelsproul feel free to set `Ax` as you see fit :)

**Comment by michaelsproul** [comment]
Marking this as resolved. There exist several metrics for the slasher, and we can always add more as required.
