### ISSUE TITLE
Non consecutive eth1 deposit logs

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#1864]
## Description

Discord users have reported getting the following logs when trying to get deposit logs
```
ERRO Failed to update eth1 cache             error: Failed to update eth1 cache: FailedToInsertDeposit(NonConsecutive { log_index: 97025, expected: 97023 }), retry_millis: 7000, service: eth1_rpc
```

## Version

Received 2 reports so far
1. `Lighthouse/v0.3.2-36bd4d8` and `Geth/v1.9.23-stable-8c2f2715/linux-arm64/go1.15.3`
2. `Lighthouse v0.3.3-0cde4e2` and `Nethermind 1.9.14`.

## Present Behaviour

Investigated the issue with the geth version and found that it was returning incorrect number of logs for certain ranges of blocks.
Opened an issue for the same here https://github.com/ethereum/go-ethereum/issues/21770
Note: I cannot reproduce the issue locally on my geth node even with 2 resyncs.

Haven't looked into the nethermind issue yet.

Also looked into our deposit log insertion logic and couldn't find any immediate issues with it.

## Expected Behaviour

Shouldn't get non-consecutive logs.

## Steps to resolve

Should probably review our deposit insertion logic thoroughly first, since the issue has come up with multiple eth1 clients.
Check nethermind as well for any skipped logs.

cc @paulhauner

**Comment by mightypenguin** [comment]
I'm seeing this right now with nethermind.

`ERRO Failed to update eth1 cache             error: Failed to update eth1 cache: RemoteNotSynced { next_required_block: 3743587, remote_highest_block: 0, follow_distance: 2048 }, retry_millis: 7000, service: eth1_rpc`

**Comment by pawanjay176** [comment]
Forgot to link the Nethermind issue. Thanks @mightypenguin :)

**Comment by KaiRo-at** [comment]
I'm seeing this after I had to switch to a newly synched node (with OpenEthereum 3.2) due to the old node not being upgradeable to the Berlin HF for some reason that doesn't play a role in this issue report. Now I'm getting:
```
ERRO Failed to update eth1 cache             error: Failed to update eth1 deposit cache: "FailedToInsertDeposit(NonConsecutive { log_index: 118399, expected: 113439 })", retry_millis: 7000, service: eth1_rpc
```
with Lighthouse 1.2.2 (docker container)

**Comment by KaiRo-at** [comment]
We have a second beacon node that connects to the same ETH1 node(s) which interestingly did not show the issue. I fixed the bugged node by copying over the DB from the working node.

**Comment by realbigsean** [comment]
@KaiRo-at sorry missed this here, but `--eth1-purge-cache` might fix it on the original as well

**Comment by maurodelazeri** [comment]
same `--eth1-purge-cache` fixes it
