### ISSUE TITLE
Password length check too short

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1880]
## Description

This function fails to consider that some emojis can take up to 4 bytes each.

https://github.com/sigp/lighthouse/blob/b185d7bbd84deade495dbb5de4a57ff42d544194/common/account_utils/src/lib.rs#L143-L155

## Steps to resolve

Count characters instead of bytes (I don't know how to do this offhand).

**Comment by 0xf1d0** [comment]
That should do it :slightly_smiling_face:

**Comment by 0xf1d0** [comment]
@paulhauner I think, you can close this issue

**Comment by paulhauner** [comment]
Thank you!
