### ISSUE TITLE
Add "stable" docker tag

### ISSUE THREAD

**Issue by yorickdowne** [sigp/lighthouse#1902]
## Description

Currently, a versioned docker tag and a `latest` tag exist, where `latest` tracks development on `master`.

In addition to these two, a `stable` tag would be useful, that tracks latest release. This makes docker tooling easier,
as there's no need to change configuration files with a new release.

I have no opinion on the exact name of such a tag. There might be a `release-1.x` as well or instead, to go with semantic versioning and avoid pulling in breaking changes, similar to how geth has `stable` and `release-1.9`.

**Comment by realbigsean** [comment]
We resolved this by having `latest` track our `stable` branch, a `latest-unstable` docker tag which tracks our `unstable` branch, and version specific tags
