### ISSUE TITLE
Better information output on voluntary exit

### ISSUE THREAD

**Issue by remyroy** [sigp/lighthouse#1932]
## Description

The voluntary exit process is short on information that could be very useful to the user.

## Version

Lighthouse v0.3.4-46a0606
BLS Library: blst

## Present Behaviour

When doing a voluntary exit with the `account validator exit` command, no time is displayed. More information would also be welcomed.

## Expected Behaviour

It would be nice to display the current time of when the voluntary exit was published for logs and archiving. It would be nice to display when the expected exit is planned to actually happen (epoch and time delta). It would be nice to display some information saying that you still have to run your validator until the exit actually happens if you don't want to be penalized.

## Steps to resolve

- Change the output of the `account validator exit` command to include those information.
- An update to [the lighthouse-book page](https://lighthouse-book.sigmaprime.io/voluntary-exit.html) on this updated process would also be nice.

**Comment by remyroy** [comment]
It seems like the expected exit epoch information can already be obtained by querying the beacon on http://localhost:5052/eth/v1/beacon/states/head/validators/<validator-index> for instance.

**Comment by paulhauner** [comment]
Did you mean to reopen this @pawanjay176?

**Comment by pawanjay176** [comment]
Nope, I did want to close. Thought it gets closed magically when the PR lands on stable.
Closing now.
