### ISSUE TITLE
Running on Docker - How to pass ETH 1.0 Node URL by Parameter

### ISSUE THREAD

**Issue by javimaravillas** [sigp/lighthouse#1943]
## Description

On the documentation we have that for running on docker:

docker run -p 9000:9000 -p 127.0.0.1:5052:5052 -v $HOME/.lighthouse:/root/.lighthouse sigp/lighthouse lighthouse --testnet medalla beacon --http --http-address 0.0.0.0

I would like to know which ethereum 1.0 node is using by default the image. Also I would like to know if it is possible to pass by parameter the ethereum 1.0 node to use.

## Version

Lighthouse v0.3.5-48f73b21+
BLS Library: blst-portable

## Present Behaviour

No documentation related.

## Expected Behaviour

Expected documentation related.
## Steps to resolve

Update documentation if possible or implement it and document

**Comment by javimaravillas** [comment]
Solved, passing --eth1 argument

**Comment by javimaravillas** [comment]
Working:
lighthouse --testnet pyrmont  beacon_node --http --eth1  --eth1-endpoint  <ETH1_Address>

**Comment by eiabea** [comment]
Just in case someone is also having issues with this, here is an example to point out how the <ETH1_Address> should look like:

```
--eth1-endpoint http://192.168.0.13:8545
```
