### ISSUE TITLE
log still warns about testnet

### ISSUE THREAD

**Issue by latetot** [sigp/lighthouse#1964]
## Description

beacon node log provides warning about testnet / and says mainnet not recommended

## Version 1.0

version: Lighthouse/v1.0.0-c6baa0e

## Present Behaviour
Nov 24 13:19:10 ethgasstation lighthouse[111453]: Nov 24 13:19:10.152 INFO Configured for testnet                  name: mainnet
Nov 24 13:19:10 ethgasstation lighthouse[111453]: Nov 24 13:19:10.152 WARN The mainnet specification is being used. This not recommended (yet).

## Expected Behaviour

Should not say configured for testnet and should not warn about mainnet

**Comment by remyroy** [comment]
I was just about to post this same exact issue.

**Comment by michaelsproul** [comment]
Thanks for pointing this out. We'll fix it for the next release

**Comment by michaelsproul** [comment]
Another one

```
These are *not* mainnet validators! Submitting a mainnet deposit for this validator will result in lost ETH.
```
