### ISSUE TITLE
eth1 node returns incorrect chain id while syncing

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#1965]
## Description

`geth` returns `chainId=0` for mainnet when not synced. This is an issue because we are displaying the misleading log message
`Invalid eth1 chain id. Please switch to correct chain id` when we should be logging `RemoteNotSynced`.

## Expected Behaviour

We should log `RemoteNotSynced` or some other log message when we get `chainId=0`

## Steps to resolve

Just log RemoteNotSynced if `chainId = 0` (need to check if an unsynced mainnet node is the only case where we can get `chainId=0`).
If not, we might have to check the sync status and log accordingly.

cc @paulhauner

**Comment by grg350** [comment]
Although my geth is completely synced to mainnet, still seeing the error.
1. Lighthouse log
`Nov 25 02:13:10 eth2 lighthouse[14765]: Nov 25 02:13:10.292 CRIT Invalid eth1 chain id. Please switch to correct chain id, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID ETH1 CONNECTION, received: Custom(0), expected: Mainnet, service: eth1_rpc
Nov 25 02:13:10 eth2 lighthouse[14765]: Nov 25 02:13:10.526 INFO Waiting for genesis                     wait_time: 6 days 9 hrs, peers: 50, service: slot_notifier`
2. My geth and lighthouse flags
`/usr/bin/geth --datadir /datadrive/eth --http --syncmode fast`
`lighthouse bn --staking --metrics`
3. Logs showing geth is completely synced in mainnet
`Nov 25 02:16:00 eth2 geth[1040]: INFO [11-25|02:16:00.148] Imported new block headers               count=1    elapsed=7.292ms     number=11324796 hash="1861a2…0408c4"
Nov 25 02:16:05 eth2 geth[1040]: INFO [11-25|02:16:05.207] Imported new state entries               count=384  elapsed="2.9µs"     processed=248459947 pending=208921 trieretry=0   coderetry=0  duplicate=9256 unexpected=29350
$ date
Wed Nov 25 02:16:06 UTC 2020`
4. My geth and light house version
`$ lighthouse  --version
Lighthouse v1.0.0-c6baa0ee
BLS Library: blst
$ geth version
Geth
Version: 1.9.24-stable
Git Commit: cc05b050df5f88e80bb26aaf6d2f339c49c2d702
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: linux
GOPATH=
GOROOT=go
`

**Comment by michaelsproul** [comment]
@grg350 The line `Imported new state entries count=384 elapsed="2.9µs" processed=248459947 pending=208921 trieretry=0 coderetry=0 duplicate=9256 unexpected=29350` indicates that your Geth is still syncing state trie entries (see https://geth.ethereum.org/docs/faq).

You can tell it's full synced when you can attach to the Geth console and `eth.syncing` returns `false` (rather than an object).

**Comment by SomerEsat** [comment]
FYI, for mainnet I get:

> eth.syncing
{
  currentBlock: 11332441,
  highestBlock: 11332553,
  knownStates: 524499016,
  pulledStates: 524387987,
  startingBlock: 11330455
}

And:
Nov 26 07:08:19 ETH-STAKER-001 lighthouse[9439]: Nov 26 07:08:19.964 INFO Waiting for genesis                     wait_time: 5 days 4 hrs, peers: 51, service: slot_notifier
Nov 26 07:08:23 ETH-STAKER-001 lighthouse[9439]: Nov 26 07:08:23.690 CRIT Invalid eth1 chain id. Please switch to correct chain id, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID ETH1 CONNECTION, received: Custom(0), expected: Mainnet, service: eth1_rpc

Repeating constantly on the beacon node.

**Comment by ChuckNorrison** [comment]
observed this while testing with infura endpoint today. This issue is gone after a while. Seems the infura was syncing?! My local geth eth1 endpoint does not result with that CRITs, even he is some blocks behind and not always eth.syncing = false
