### ISSUE TITLE
Validator fails to start after hard reboot due to json.lock files 

### ISSUE THREAD

**Issue by Vitiell0** [sigp/lighthouse#1973]
## Description

If the validator experiences a hard reboot (power loss) when it comes back online it fails to start with the following error

```
INFO Lighthouse started                      version: Lighthouse/v1.0.0-c6baa0ee
INFO Configured for testnet                  name: pyrmont
INFO Starting validator client               validator_dir: "/var/lib/lighthouse/validators", beacon_node: http://localhost:5052/
INFO Completed validator discovery           new_validators: 0
ERRO Failed to initialize validator          validator: 0xb...., error: LockfileExists("/var/lib/lighthouse/validators/0xb..../keystore-m_12381_3600_1_0_0.json.lock")
CRIT Failed to start validator client        reason: Unable to initialize validators: LockfileExists("/var/lib/lighthouse/validators/0xb.../keystore-m_12381_3600_1_0_0.json.lock")
INFO Internal shutdown received              reason: Failed to start validator client
INFO Shutting down..

```

## Version

1.0.0

## Expected Behaviour

The application should be able to handle rebooting after a power loss. We could clean up the lock files automatically or find a way to handle them gracefully. 

## Steps to resolve

Deleting the lock files manually fixes the issue but is annoying to have to do every time the machine has a power loss.

**Comment by pawanjay176** [comment]
https://github.com/sigp/lighthouse/pull/1958 will fix the issue

**Comment by Vitiell0** [comment]
@pawanjay176 excellent that looks great!
