### ISSUE TITLE
1.0.0: "Address updated" notification with bogus port

### ISSUE THREAD

**Issue by SjonHortensius** [sigp/lighthouse#1974]
## Description

`lighthouse beacon_node` logs two "Address updated" entries, of which the second one seems bogus/random

This happens every time the "Address updated" message is printed. Funnily enough it used to print `1813`. I'm not sure what triggers the printing at all, the output is constant.

## Version

Build from `v1.0.0`

## Present Behaviour

```
INFO Address updated                         udp_port: 9000, ip: ***, service: libp2p
INFO Address updated                         udp_port: 1814, ip: ***, service: libp2p
```

## Expected Behaviour

Only a single line printed

## Steps to resolve

None

**Comment by AgeManning** [comment]
This is not much to worry about and seems to happen on a few routers. 

It means that outbound your router is sending packets with an external port 1814 and well as 9000. Your canonical address is chosen via a majority of peers who witness your outbound packets. 

This indicates half of your packets are sent outbound on 1814 and half on 9000 and the majority is oscillating.

I'll look further into either suppressing the warnings or adjusting the majority calculation to favour the 9000 port.

**Comment by AgeManning** [comment]
Could you also provide further information about current UPnP set up? I.e in your router does it have established routes or specific port forwards?

Potentially this may occur if there are multiple port forwards for a single host

**Comment by SjonHortensius** [comment]
@AgeManning thanks for your reply. I'm not worried but I do like to investigate where this originates.

As I prefer to punch the holes in my firewall myself, I have UPnP disabled and port 9000 has been manually mapped.
This is a local setup with a NAT router and a manual port forward.

I'd prefer to disable upnp in lighthouse for consistency but couldn't find the cli argument to do so, is this supported?

**Comment by SjonHortensius** [comment]
I just noticed something else; in my portmapping I only setup port 9000 for tcp traffic so the other port was "magically"? chosen for udp.

I've reconfigured the forward to apply to both tcp and udp.

**Comment by AgeManning** [comment]
Interesting. Let me know if the behaviour persists with the UDP port mapping. I've seen this happen with other users. 

I still find it strange the router would use alternating ports to send outbound UDP traffic. 

You can use the `--disable-upnp` flag to prevent lighthouse from attempting to use UPnP

**Comment by SjonHortensius** [comment]
Thanks for your help. After updating the portmapping (and coincidentally; updating the firmware of the router) I no longer get any messages and all traffic goes through port 9000 as expected. If I run into this again I'll start with looking at tcpdump and my local setup first - I don't think lighthouse needs to change anything
