### ISSUE TITLE
ETH1 Deposits timeout when retrieved for mainnet pre genesis

### ISSUE THREAD

**Issue by danielschonfeld** [sigp/lighthouse#1980]
## Description

Trying to start a mainnet beacon node before mainnet launch, I am getting the following error:

```ERRO Failed to update eth1 cache             error: Failed to update eth1 cache: GetDepositLogsFailed("Request failed: reqwest::Error { kind: Request, url: Url { scheme: \"http\", host: Some(Domain(\"192.168.1.202\")), port: Some(8545), path: \"/\", query: None, fragment: None }, source: TimedOut }"), retry_millis: 7000, service: eth1_rpc```

## Version

```Lighthouse v1.0.0-c6baa0ee```

## Present Behaviour

Timeout, no deposit logs are processed.

## Expected Behaviour

Process deposit logs

## Steps to resolve

It seems that changing the ```GET_DEPOSIT_LOG_TIMEOUT_MILLIS``` to double the amount solves the problem, however changing ```blocks_per_log_query``` down to ```250``` does not seem to?

**Comment by AgeManning** [comment]
I think #2008 may help address this

**Comment by pawanjay176** [comment]
Closing this as #2008 fixes this. Feel free to reopen if issue persists.
