### ISSUE TITLE
v1.0.1 fails with comma-separated --eth1-endpoints

### ISSUE THREAD

**Issue by jerryji** [sigp/lighthouse#1988]
## Description

v1.0.1

`/usr/local/bin/lighthouse beacon_node ... --eth1-endpoints https://mainnet.infura.io/v3/XXX,https://eth-mainnet.alchemyapi.io/v2/YYY`

fails --

`Error connecting to eth1 node. Trying fallback ..., endpoint: https://mainnet.infura.io/v3/XXX,https://eth-mainnet.alchemyapi.io/v2/YYY, service: eth1_rpc`

## Version

```
$ /usr/local/bin/lighthouse -V
Lighthouse v1.0.1-5a3b94cb
```

git pull master after v1.0.1 release, compiled on Ubuntu 20.04; same error with the pre-built release binary

## Present Behaviour

Fails

## Expected Behaviour

Should not fail

## Steps to resolve

NA

**Comment by rizoraz** [comment]
hi jerryji, i think this is another problem, because i can't work with infura also 1.0.0 and also 1.0.1.

were you able to get it running with infura on 1.0.0?

for me, with 1.0.0 and 1.0.1 i have this error message:

Nov 27 19:20:50.271 CRIT Error connecting to eth1 node. Please ensure that you have an eth1 http server running locally on http://localhost:8545 or pass an external endpoint using `--eth1-endpoint <SERVER-ADDRESS>`. Also ensure that `eth` and `net` apis are enabled on the eth1 http server, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID ETH1 CONNECTION, service: eth1_rpc

when i run agains my local eth1 node no problems


for reference

**1.0.0**
docker run -d --name libn ... lighthouse --network mainnet beacon --staking --http --http-address 0.0.0.0  --eth1-endpoint https://mainnet.infura.io/v3/xxx

**1.0.1**
docker run -d --name libn ... lighthouse --network mainnet beacon --staking --http --http-address 0.0.0.0  --eth1-endpoints https://mainnet.infura.io/v3/xxx

**Comment by dsmoljanovic** [comment]
Same here, but using docker-compose and local ETH node that runs on another docker. Works well with 1.0.0 but doesn't on 1.0.1

Tried both deprecated `--eth1-endpoint` and `--eth1-endpoints` parameter.

`CRIT Couldn't connect to any eth1 node. Please ensure that you have an eth1 http server running locally on http://localhost:8545 or specify one or more (remote) endpoints using `--eth1-endpoints <COMMA-SEPARATED-SERVER-ADDRESSES>`. `

**Comment by jerryji** [comment]
Hi @rizoraz , I don't use docker and my _single endpoint_ command lline `/usr/local/bin/lighthouse beacon_node ... --eth1-endpoints https://mainnet.infura.io/v3/XXX` works fine in v1.0.1 (and `--eth1-endpoint https://mainnet.infura.io/v3/XXX` has been working fine in v1.0.0)

**Comment by dsmoljanovic** [comment]
My issue ended up in eth1 really not being in sync. After a hours and eth1 ending the sync it started working OK. Different log output then in v1.0.0 caused a bit of confusion. 

You can check if eth1 is in sync by attaching to geth and executing `eth.syncing`

**Comment by jerryji** [comment]
The same problem still exists in v1.0.2 , I can't be the only one who's affected, can I? And it's not an issue with Infura as it works once I remove the alchemyapi.io endpoint --

```
$ /usr/local/bin/lighthouse --version
Lighthouse v1.0.2-f7183098

$ /usr/local/bin/lighthouse beacon_node ... --eth1-endpoints https://mainnet.infura.io/v3/XXX,https://eth-mainnet.alchemyapi.io/v2/YYY

Nov 29 10:43:20  lighthouse[61173]: Nov 29 10:43:20.406 INFO Waiting for genesis                     wait_time: 2 days 9 hrs, peers: 0, service: slot_notifier
Nov 29 10:43:20  lighthouse[61173]: Nov 29 10:43:20.900 WARN Error connecting to eth1 node. Trying fallback ..., endpoint: https://mainnet.infura.io/v3/XXX,https://eth-mainnet.alchemyapi.io/v2/YYY, service: eth1_rpc
Nov 29 10:43:20  lighthouse[61173]: Nov 29 10:43:20.902 CRIT Couldn't connect to any eth1 node. Please ensure that you have an eth1 http server running locally on http://localhost:8545 or specify one or more (remote) endpoints using `--eth1-endpoints <COMMA-SEPARATED-SERVER-ADDRESSES>`. Also ensure that `eth` and `net` apis are enabled on the eth1 http server, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID, SYNCED ETH1 CONNECTION, service: eth1_rpc
Nov 29 10:43:20  lighthouse[61173]: Nov 29 10:43:20.902 ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: https://mainnet.infura.io/v3/XXX,https://eth-mainnet.alchemyapi.io/v2/YYY => EndpointError(NotReachable)", retry_millis: 7000, service: eth1_rpc
Nov 29 10:43:25  lighthouse[61173]: Nov 29 10:43:25.433 INFO Sync state updated                      new_state: Synced, old_state: Stalled, service: sync
Nov 29 10:43:25  lighthouse[61173]: Nov 29 10:43:25.434 INFO Subscribed to topics                    topics: [BeaconBlock, BeaconAggregateAndProof, VoluntaryExit, ProposerSlashing, AttesterSlashing], service: network
Nov 29 10:43:25  lighthouse[61173]: Nov 29 10:43:25.435 INFO Sync state updated                      new_state: Stalled, old_state: Synced, service: sync
Nov 29 10:43:25  lighthouse[61173]: Nov 29 10:43:25.538 INFO Sync state updated                      new_state: Synced, old_state: Stalled, service: sync
Nov 29 10:43:27  lighthouse[61173]: Nov 29 10:43:27.830 WARN Error connecting to eth1 node. Trying fallback ..., endpoint: https://mainnet.infura.io/v3/XXX,https://eth-mainnet.alchemyapi.io/v2/YYY, service: eth1_rpc
Nov 29 10:43:27  lighthouse[61173]: Nov 29 10:43:27.832 CRIT Couldn't connect to any eth1 node. Please ensure that you have an eth1 http server running locally on http://localhost:8545 or specify one or more (remote) endpoints using `--eth1-endpoints <COMMA-SEPARATED-SERVER-ADDRESSES>`. Also ensure that `eth` and `net` apis are enabled on the eth1 http server, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID, SYNCED ETH1 CONNECTION, service: eth1_rpc
Nov 29 10:43:27  lighthouse[61173]: Nov 29 10:43:27.832 ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: https://mainnet.infura.io/v3/XXX,https://eth-mainnet.alchemyapi.io/v2/YYY => EndpointError(NotReachable)", retry_millis: 7000, service: eth1_rpc

```

**Comment by romanoLT** [comment]
I have the same issue with 1.0.2 in Docker

**Comment by jerryji** [comment]
It turns out I've **not** been using --eth1-endpoint**s** , but ``--eth1-endpoint`` in my systemd service file.

Sorry for the confusion.
