### ISSUE TITLE
could you tell me ,it can use or not

### ISSUE THREAD

**Issue by navy665180** [sigp/lighthouse#1998]
## Description
i want to know the guide of the net can use or not,thanks!
https://www.coincashew.com/coins/overview-eth/guide-or-how-to-setup-a-validator-on-eth2-mainnet

i try many times but every time have some misstakes .
eth1.0 can run.
eth2.0 use lighthouse,the step "make"  ,error.

 
error: failed to compile `lighthouse v1.0.1 (/home/ethereum/git/lighthouse/lighthouse)`, intermediate artifacts can be found at `/home/ethereum/git/lighthouse/target`

Caused by:
  failed to run custom build command for `deposit_contract v0.2.0 (/home/ethereum/git/lighthouse/common/deposit_contract)`

Caused by:
  process didn't exit successfully: `/home/ethereum/git/lighthouse/target/release/build/deposit_contract-80c2f7a5c6f6fec4/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'No abi file found. Failed to download from github: reqwest::Error { kind: Request, url: Url { scheme: "https", host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/ethereum/eth2.0-specs/v0.12.1/deposit_contract/contracts/validator_registration.json", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', common/deposit_contract/build.rs:38:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:20: install] Error 101

## Version
because make give error,i don't know the version of lighthouse 
**lighthouse --version**       
no lighthouse commond

Please provide your Lighthouse and Rust version. Are you building from
`master`, which commit?
https://www.coincashew.com/coins/overview-eth/guide-or-how-to-setup-a-validator-on-eth2-mainnet
## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.

## Expected Behaviour

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.
make step

**Comment by divagant-martian** [comment]
We've seen this issue happen to people located in China, is this your case?

**Comment by navy665180** [comment]
yes ,i am in china .so do you have some suggest for me to choose which validater client ??right now ,i choose  to openetherum to build eth1,and prysm to build eth2 by windows.
i can't connect the infura.so i have no choose bu to bulid a owner note.
do you have any suggests for me ??thanks!!

**Comment by divagant-martian** [comment]
The file the build script is trying to reach is this one: https://github.com/ethereum/eth2.0-specs/tree/v0.12.1/deposit_contract/contracts
Go there and download the contents of the `json` one. I'm not sure atm where you need to put the file but i'll get back to you if the content is accessible to you this way

**Comment by divagant-martian** [comment]
closing as a solution has been provided
