### ISSUE TITLE
type_length_limit error during FreeBSD build

### ISSUE THREAD

**Issue by gballet** [sigp/lighthouse#2003]
## Description

Building on `FreeBSD 12.1-RELEASE`, I hit some limit during the build of crates `eth1` and `lighthouse`. For example:

```
   Compiling lighthouse v1.0.1 (/usr/home/gballet/src/lighthouse/lighthouse)
error: reached the type-length limit while instantiating `std::pin::Pin::<&mut std::future...::Future>::poll::{{closure}}#0]>`
    |
    = note: consider adding a `#![type_length_limit="1405659"]` attribute to your crate

error: aborting due to previous error

error: failed to compile `lighthouse v1.0.1 (/usr/home/gballet/src/lighthouse/lighthouse)`, intermediate artifacts can be found at `/usr/home/gballet/src/lighthouse/target`
```

## Version

`stable` @ `5a3b94cbb4a82f999c2deb5c45146eaf58146957`

## Steps to resolve

As a workaround, I have set:

```rust
#![type_length_limit = "20364955"]
```
at the beginning of both `beacon_node/eth1/src/lib.rs` and `lighthouse/src/main.rs`.

**Comment by michaelsproul** [comment]
Which version of `rustc` are you compiling with?

I think newer versions (1.47.0+) should work without increasing the type length limit

**Comment by AgeManning** [comment]
We currently only support the latest stable rust. Updating rust to the latest stable should resolve this.
