### ISSUE TITLE
UPnP error with v1.0.2

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#2009]
## Description

```
Nov 29 12:20:20.699 INFO UPnP not available                      error: IO error: Resource temporarily unavailable (os error 35), service: UPnP
```

I believe this is the first time I see this error message.

## Version

v1.0.2

**Comment by zeb0x** [comment]
I saw this as well

**Comment by AgeManning** [comment]
This is fine. 

Potentially I should downgrade the log so the user doesn't see this. I made it an info as it's instructive to see if Lighthouse managed to automatically set up routes for you or not. 

This error indicates that your router does not support UPnP or doesn't have it enabled. Or doesn't support the protocol we use to configure UPnP ports (https://en.wikipedia.org/wiki/Internet_Gateway_Device_Protocol)

**Comment by janickm** [comment]
What about 

```
INFO UPnP not available                      error: IO error: Resource temporarily unavailable (os error 11), service: UPnP
```

given that error 11 should be EAGAIN, will setting up UPnP be retried in this case?

**Comment by AgeManning** [comment]
No we don't try again. 
I'm not sure about the OS errors returned from the library in this case. I can't think of a common reason why a router would not respond to UPnP requests if it is ready and accepts it. I would imagine these 11 errors to be recurring, or very unlikely. Not sure if its worth building the machinery to retry 5 times to get the same result.
Do you see this error on restart continuously?

**Comment by janickm** [comment]
>  Do you see this error on restart continuously?

Yes, it's persistent for every start of lighthouse - also, I'm not sure if the UPnP requests ever get executed thereafter - how could I check (so there is likely no re-try performed thereafter?). FWIW, I have configured my router to accept UPnP requests.

**Comment by AgeManning** [comment]
Yeah. The UPnP library I have found to be quite flakey. A bunch of routers don't respond the way the library expects. UPnP is really kind of a fallback to try and get some open ports when people are not configuring it themselves. If it fails, it will not try again, to avoid opening too many ports all over the place.

It sounds like this library doesn't support your router. You really should be manually port forwarding, if you are running a node for an extended period of time.

We are working on a custom automatic NAT hole-punching technique to by-pass router firewalls, but its probably still a few months off.

**Comment by janickm** [comment]
Great, thanks! I'm already forwarding the ports manually and using `--disable-upnp` for now.

> We are working on a custom automatic NAT hole-punching technique to by-pass router firewalls, but its probably still a few months off.

Could you update this issue / share the tracking issue on this one? I could help test it on my setup

**Comment by AgeManning** [comment]
Sure. 

The first step is an automatic hole-punching technique in our discovery protocol (discv5). The current associated PR is here: https://github.com/sigp/discv5/pull/134

We then need to either invent a new technique or leverage libp2p methods to handle hole punching of discovered nodes across TCP.
