### ISSUE TITLE
Insecure filesystem permissions on validator key files

### ISSUE THREAD

**Issue by bo0ohXae** [sigp/lighthouse#2012]
Just tried importing validator keys on the latest version 1.02 using the official docker images.  The keystore files were created with pretty insane permissions:

-rwxrwxrwx 1 root root  710 Nov 29 10:56 keystore-m_12381_3600_0_0_0-1604513689.json
-rwxrwxrwx 1 root root  710 Nov 29 10:56 keystore-m_12381_3600_1_0_0-1604513690.json

While I don't like that any user can read the files, I suppose its 'ok' since they are encrypted.  However any user on the system can write to the files, delete them or overwrite them!  The execute bit is just.. unnecessary.

Ideally it should be the same as the validator definitions file:
-rw------- 1 root root   855 Nov 29 10:56 validator_definitions.yml

**Comment by ChuckNorrison** [comment]
My imported keystores inherit permissions from parent folder, seems fine to me

**Comment by paulhauner** [comment]
The Lighthouse import command maintains the file permissions of the original keystores. I think this is quite reasonable behaviour.

The [`eth2.0-deposit-cli`](https://github.com/ethereum/eth2.0-deposit-cli) sets permissions that are, in my opinion, too wide but I've never seen them with `-rwxrwxrwx` before.

I suggest checking the permissions on the keystores generated by `eth2.0-deposit-cli`. If they are not to your satisfaction, I suggestion opening an issue on [that repo](https://github.com/ethereum/eth2.0-deposit-cli). If the permissions are different to the ones that Lighthouse imported (i.e., you believe Lighthouse *changed* the permissions) then please reopen this issue.

Thanks for raising this.

**Comment by bo0ohXae** [comment]
Oh I see.  I guess that makes sense.  In this case the original keystore was read from a USB stick (I think FAT32) which doesn't support file permissions, so the permissions were set that way.  

Might not hurt to do a sanity check, or just default to -rw------- as I suspect many people will store their keys offline.
