### ISSUE TITLE
Sign released binaries

### ISSUE THREAD

**Issue by aascft3** [sigp/lighthouse#2014]
Please sign the released binaries. I can see scammers trying to create modified versions of lighthouse, the way it recently happened with geth (https://github.com/ethereum/go-ethereum/issues/21687). 

It would be great to have your keys and to be able to verify the releases are actually from you.

**Comment by AgeManning** [comment]
Agreed. This has been on our to-do list for a while. Will add it asap

**Comment by AgeManning** [comment]
I've added signatures to the current release. We'll add it into our release procedure
