### ISSUE TITLE
Bug?: BAD_REQUEST: request epoch is ahead of the current epoch

### ISSUE THREAD

**Issue by b-m-f** [sigp/lighthouse#2030]
## Description
```
Dec 01 13:25:59 validator lighthouse[596]: Dec 01 13:25:59.111 ERRO Failed to download validator duties     error: Failed to get proposer indices: ServerMessage(ErrorMessage { code: 400, messa
ge: "BAD_REQUEST: request epoch 4 is ahead of the current epoch 3", stacktraces: [] }), service: duties
Dec 01 13:25:59 validator lighthouse[596]: Dec 01 13:25:59.115 ERRO Failed to download validator duties     error: Failed to get attester duties: ServerMessage(ErrorMessage { code: 400, messag
e: "BAD_REQUEST: request epoch 5 is more than one epoch past the current epoch 3", stacktraces: [] }), service: duties
```

## Version
1.0.3

## Present Behaviour

Attestations are working.

The error is thrown as epochs roll over from `N` to `N+1`

**Comment by realbigsean** [comment]
Hello a few questions (feel free to contact me privately via DM here or Discord if you'd prefer not to disclose here):

1. Is this mainnet or Pyrmont?
2. Has this been consistently occurring or did it only occur when starting up the beacon node?
3. Are your beacon node and validator client on the same machine? a system clock drift on one could cause this
4. how many validators do you have enabled and disabled (even just an estimate is fine)?

**Comment by b-m-f** [comment]
Hi @realbigsean 

1. main
2. consistent after genesis
3. split. Let me look into the clock drift!
4. very few. No disabled ones

**Comment by b-m-f** [comment]
@realbigsean 
Turned out to be an issue with `ntp`. Was able to fix. Thanks !
