### ISSUE TITLE
Remote graffiti provider

### ISSUE THREAD

**Issue by remyroy** [sigp/lighthouse#2031]
## Description

The current graffiti value is a constant value that cannot be easily changed.

## Version

Lighthouse v1.0.3-65dcdc36
BLS Library: blst

## Present Behaviour

When starting your validators, you can only provide a static and constant value for your graffiti.

## Expected Behaviour

It would be nice to provide a dynamic value for the graffiti with an external provider. Use cases for this include:

* Easier painting on [the beaconcha.in graffiti wall](https://beaconcha.in/graffitiwall)
* Playing the game number
* Displaying multi-line ASCII images in collaboration with other validators
* Pooling graffiti values together to achieve a common goal
* Other *fun* and unexpected games and use cases

It would also be nice to be able to change the graffiti without having to restart the validator client.

## Steps to resolve

A simple solution would be to provide a path to a file instead of a constant value for the graffiti. When the validator client needs to propose a block, it would read that file and include the content as the graffiti. An external application would have to monitor when a graffiti is included and change the content of that file for the next value.

Other solutions include client/server protocols, using an HTTP backend, other IPC solutions.

## Related

This is somewhat related to #1944 .

**Comment by remyroy** [comment]
Lighthouse could have graffiti fallbacks:

```
--> Use remote graffiti provider
  | (on fail/not available/empty/not defined)
  v
  --> Use constant per account graffiti
    | (on fail/not available/empty/not defined)
    v 
    --> Use globablly defined graffiti
      | (on fail/not available/empty/not defined)
      v
      --> Use default value (Client name + version)
```

**Comment by gak** [comment]
It would be useful for the external provider to know when a graffiti has been used in a proposal. For example the graffiti wall, when a pixel has been drawn, it could inform the provider to go to the next pixel.

**Comment by remyroy** [comment]
Things to consider:

* A push vs pull solution. Since block creation is time sensitive, it might be more interesting for the validator client to offer some kind of REST API instead of connecting to an external provider. This could be part of the [Validation Client API](https://lighthouse-book.sigmaprime.io/api-vc.html)(https://lighthouse-book.sigmaprime.io/api-vc.html).

**Comment by gak** [comment]
I'm casually investigating this, and have a few questions. I can see that both the bn and vc can specify a graffiti, and there is a rule where the vc overrides the bn configured graffiti if specified.

If one was to implement this issue, should this logic live in the vc?

Does the bn actually need this functionality?

**Comment by remyroy** [comment]
I believe the vc should ultimately be deciding the value of the grafiti. I'm not sure if it is still needed in the bn. Someone might want to run the bn alone just as a health benefit or for an explorer. In a way, if you want better role seperation, bn should not know about any grafiti value.

**Comment by gak** [comment]
Related PR https://github.com/sigp/lighthouse/pull/2044 for graffiti per validator in `validator_definitions.yml`.

**Comment by AgeManning** [comment]
It seems this feature is getting a bit of attention. 

I believe our current plan was to get the VC to read from a file before block production.

It might make sense to just add an endpoint to the VC HTTP API. However this API is restricted and should only be used locally for security reasons, so will limit its accessibility.

The VC is ultimately deciding the value of the graffiti (this is why it overrides any BN settings). The reason we had it in the BN is that by default it prints `Lighthouse` and the current BN version (which is very handy for debugging and identifying issues if things go wrong). We could shift the default behaviour to the VC, however the VC version is mostly irrelevant when debugging issues on the network and we really want to know the version of the BN (as it contains practically all the logic of the client). 

As it stands, having the default functionality to print the BN version in the BN doesn't really cause any harm (maybe a little bit of confusion) but it does help us identify and solve issues. There are flags to disable it and any graffiti set in a validator will override it.

**Comment by AgeManning** [comment]
#2074 is the relevant issue to track for this

**Comment by paulhauner** [comment]
I'm going to close this once since it hasn't had much interest for quite some time. Free free to re-open if you really desire this feature.
