### ISSUE TITLE
Feature Request: Sync Then Shutdown

### ISSUE THREAD

**Issue by AusIV** [sigp/lighthouse#2033]
## Description

For operational purposes, we want to be able to have a snapshotting process where a node starts up, syncs up with the blockchain, shuts down, and snapshots the disk. This way when we need to start new nodes, we can pull from a recent snapshot.

## Version

Lighthouse v1.0.3-65dcdc3

## Present Behaviour

Right now nodes keep running after they catch up with the chain, and we have to monitor the node via HTTP to determine when it is up to date.

## Expected Behaviour

Ideally there would be a flag we could set to shutdown automatically when a node is up to date. Most ETH 1 clients offer flags to this effect.

**Comment by paulhauner** [comment]
Resolved via #2519
