### ISSUE TITLE
validator API endpoint 400 vs 405 status

### ISSUE THREAD

**Issue by protolambda** [sigp/lighthouse#2035]
## Description

Minor API issue (sorry for nitpick), working on testing the whole lighthouse API surface for consistency with spec, and generating test vectors for bindings!

Issue: `/eth/v1/beacon/states/100/validators/morty` returns 405 (unknown route) status instead of 400 (invalid validator ID)

## Version

v1.0.3

## Present Behaviour

405

## Expected Behaviour

400

## Steps to resolve

Change routing logic to match any validator ID format, and only then return a correct error code when parsing in detail.

**Comment by realbigsean** [comment]
> working on testing the whole lighthouse API surface for consistency with spec, and generating test vectors for bindings!
Hero!

Thanks for pointing this out. I've made a PR for this that also updates some other endpoints where I think we had the same inconsistency.
