### ISSUE TITLE
Possible leak from length of truncated Git hash in graffiti

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#2037]
I looks like Lighthouse nodes have varying-length truncated Git hashes. This could leak information about the build process (e.g. Git version, OS, etc.). Standardising the length will also make it a bit cleaner to do statistics on the validator nodes based on the graffiti.

![Screenshot 2020-12-02 at 09 59 03](https://user-images.githubusercontent.com/731743/100857787-04c13e00-3485-11eb-824e-2ea6c7227c9d.png)

**Comment by michaelsproul** [comment]
Should be a matter of providing a length to `git describe --abbrev`, maybe 7 or 8.

**Comment by michaelsproul** [comment]
Including the hash at all is a leak too, but I guess most validators regularly updating to the latest version does something to help that

For those that value privacy there's `--private`

**Comment by pawanjay176** [comment]
Fixed in #2038
