### ISSUE TITLE
make: error

### ISSUE THREAD

**Issue by navy665180** [sigp/lighthouse#2043]
## Description
i am in china.
make 
error: failed to compile `lighthouse v1.0.3 (/home/ethereum/git/lighthouse/lighthouse)`, intermediate artifacts can be found at `/home/ethereum/git/lighthouse/target`

Caused by:
  failed to run custom build command for `deposit_contract v0.2.0 (/home/ethereum/git/lighthouse/common/deposit_contract)`

Caused by:
  process didn't exit successfully: `/home/ethereum/git/lighthouse/target/release/build/deposit_contract-e5ce5e3ab5e97da4/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'No abi file found. Failed to download from github: reqwest::Error { kind: Request, url: Url { scheme: "https", host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/ethereum/eth2.0-specs/v0.12.1/deposit_contract/contracts/validator_registration.json", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', common/deposit_contract/build.rs:38:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:20: install] Error 101

## Version

Please provide your Lighthouse and Rust version. Are you building from
`master`, which commit?
v1.0.3

## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.

## Expected Behaviour

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

i download the resouse by hand:
lighthouse-v1.0.3-x86_64-unknown-linux-gnu.tar
lighthouse-v1.0.3-x86_64-unknown-linux-gnu.tar.gz

the problem is 
where to put them??
put them in the right place,then re-make.will it work?
will it work by use tool : VPN? to avoid the error?
![make---error](https://user-images.githubusercontent.com/75147624/100987592-af228980-3589-11eb-8639-bbdb9f087815.png)

**Comment by javimaravillas** [comment]
In case you are having issues, you can use the compiled versions that are published, I recommend the portable version:

https://github.com/sigp/lighthouse/releases/download/v1.0.3/lighthouse-v1.0.3-x86_64-unknown-linux-gnu-portable.tar.gz

in case you want to do it from the source, make sure you clone de repository and you checkout the latest tag:
git checkout v1.0.3

**Comment by realbigsean** [comment]
> lighthouse-v1.0.3-x86_64-unknown-linux-gnu.tar.gz
> 
> the problem is
> where to put them??
> put them in the right place,then re-make.will it work?

If you are able to download that file, you can run `tar -xvf lighthouse-v1.0.3-x86_64-unknown-linux-gnu.tar.gz` to extract the `lighthouse` binary. No no need to re-make if you are installing this way. And as far as where you put it, that's up to you and how you want to run it. You can test with `./lighthouse --version`

like @javimaravillas mentioned if you run into issues (may be an error with something like `Illegal Instruction`) use lighthouse-v1.0.3-x86_64-unknown-linux-gnu-**portable**.tar.gz instead

**Comment by navy665180** [comment]
thank you! 
then 
i download https://github.com/sigp/lighthouse/releases/download/v1.0.3/lighthouse-v1.0.3-x86_64-unknown-linux-gnu-portable.tar.gz
put it at $ethereum/git/lighthouse
then run:run tar -xvf lighthouse-v1.0.3-x86_64-unknown-linux-gnu-portable.tar.gz
then:

![error](https://user-images.githubusercontent.com/75147624/101108057-aaec7f80-360e-11eb-9365-3db1f4fc93a1.png)

x-gnu-portable.tar.gz
lighthouse
tar: lighthouse: Cannot open: File exists
tar: Exiting with failure status due to previous errors

**Comment by michaelsproul** [comment]
@navy665180 That error indicates that there's already a `lighthouse` binary in the directory where you're extracting. You could delete it first like this:

```
rm ~/git/lighthouse/lighthouse
```

Or extract the tarball in a different directory
