### ISSUE TITLE
ERRO Banning a disconnected peer

### ISSUE THREAD

**Issue by MysticRyuujin** [sigp/lighthouse#2046]
## Description

Your documentation says that if we see any ERRO messages we should open an issue. I found an ERRO message :smile: 

`ERRO Banning a disconnected peer             peer_id: 16Uiu2HAm26rS8jsaqG68htn1A4KHJ2avxVKcTuAjr8DAzdvpceq4, service: libp2p`

## Version

Docker v1.0.3

## Present Behaviour

`ERRO Banning a disconnected peer             peer_id: 16Uiu2HAm26rS8jsaqG68htn1A4KHJ2avxVKcTuAjr8DAzdvpceq4, service: libp2p`

## Expected Behaviour

:man_shrugging:

## Steps to resolve

:man_shrugging:

**Comment by AgeManning** [comment]
Yeah, this can happen with events being built up and being processed spontaneously. This is harmless, but the situation wasn't considered when adding the error message in. 
I'll downgrade this.
