### ISSUE TITLE
Add altruistic broadcast to slasher

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2048]
## Description

Presently the Lighthouse slasher is like a greedy dragon, hoarding all of its precious slashings in the Lighthouse op pool and never sharing them with the rest of the network. We should add a flag like `--slasher-broadcast` or `--slasher-altruistic` that enables broadcasting attestations for the health of the ~kingdom~ network.

## Version

v1.0.3

**Comment by AgeManning** [comment]
The other question is what should be the default behaviour?

I'm down for leaving the selfish option the default until a whistleblower index gets included

**Comment by michaelsproul** [comment]
Agree, I'm quite fond of the selfish behaviour because I think it incentives more users to run slashers, which is a net win

**Comment by paulhauner** [comment]
I'm also in favor of greedy as the default. I think it encourages more slashers on the network, whilst still allowing concerned entities to be altruistic.

Another, more complex option would be to switch on `eth1_chain.is_some()`:

- `true`: we probably have stakers. Keep slashings private unless `--broadcast-slashings true`.
- `false`: probably no stakers. Publish slashings unless `--broadcast-slashings false`.

I'm not convinced the more complex version is worth it though, I think a single opt-in flag is sane.

**Comment by michaelsproul** [comment]
I'm starting work on this now
