### ISSUE TITLE
Running beacon node without eth1 endpoint even once makes eth1 sync fail forever

### ISSUE THREAD

**Issue by jtoomim** [sigp/lighthouse#2058]
If I run `./lighthouse bn` once (with no connected eth1 endpoint) and let the chain sync, then restart lighthouse with `./lighthouse bn --eth1 --http --staking`, I consistently get these error messages:

```
Dec 06 21:24:47.754 ERRO Failed to update eth1 cache             error: Failed to update eth1 cache: "FailedToInsertDeposit(NonConsecutive { log_index: 459, expected: 0 })", retry_millis: 7000, service: eth1_rpc
```

The log_index and expected are always the same (459, 0). I get the same error if I use an openethereum local node, a geth local node, or if I use the Infura API. On Infura, the error shows up less commonly -- about once every 3 minutes rather than once every 50 seconds.

This error shows up when I use the lighthouse 1.0.3 amd64 linux portable executable as well as the lighthouse 1.0.2 one. I also compiled from source with the same result.

As a result of this error, the eth1 block cache never gets synced.

However, if I delete the beacon chain -- `rm -r ~/.lighthouse/mainnet/beacon/` and restart using `./lighthouse bn --eth1 --http --staking`, the eth1 sync will work properly.

**Comment by pawanjay176** [comment]
@jtoomim the most likely cause for this is that your local node wasn't completely in sync when you tried the first time. However, LH should start importing the deposit caches once your eth1 node was fully synced. 

Could you share which node was running locally (openethereum or geth) before wiping the beacon db and which node was running locally after wiping the beacon db.

**Comment by Bombommi** [comment]
I use an openethereum local node and have same error...

`Dec 10 21:44:23 instance-2 lighthouse[85132]: Dec 10 21:44:23.166 INFO UPnP Attempting to initialise routes    service: UPnP
Dec 10 21:44:23 instance-2 lighthouse[85132]: Dec 10 21:44:23.193 INFO HTTP API started                        listen_address: 127.0.0.1:5052
Dec 10 21:44:23 instance-2 lighthouse[85132]: Dec 10 21:44:23.354 INFO Sync state updated                      new_state: Syncing Finalized Chain, old_state: Stalled, service: sync
Dec 10 21:44:23 instance-2 lighthouse[85132]: Dec 10 21:44:23.872 INFO Address updated                         udp_port: 9000, ip: 34.121.126.165, service: libp2p
Dec 10 21:44:26 instance-2 lighthouse[85132]: Dec 10 21:44:26.517 INFO Sync state updated                      new_state: Stalled, old_state: Syncing Finalized Chain, service: sync
Dec 10 21:44:26 instance-2 lighthouse[85132]: Dec 10 21:44:26.949 INFO Starting database compaction            new_finalized_epoch: 2, old_finalized_epoch: 0, service: beacon
Dec 10 21:44:27 instance-2 lighthouse[85132]: Dec 10 21:44:27.153 INFO Database compaction complete            service: beacon
Dec 10 21:44:28 instance-2 lighthouse[85132]: Dec 10 21:44:28.611 INFO Sync state updated                      new_state: Syncing Finalized Chain, old_state: Stalled, service: sync
Dec 10 21:44:33 instance-2 lighthouse[85132]: Dec 10 21:44:33.369 INFO UPnP not available                      error: IO error: Resource temporarily unavailable (os error 11), service: UPnP
Dec 10 21:44:35 instance-2 lighthouse[85132]: Dec 10 21:44:35.773 ERRO Failed to update eth1 cache             error: Failed to update eth1 cache: "FailedToInsertDeposit(NonConsecutive { log_index: 31373, expected: 0 })", retry_millis: 7000, service: eth1_rpc`

Delete database ~/.lighthouse/mainnet/beacon/ and restart lighthouse not working for me

**Comment by pawanjay176** [comment]
@Bombommi sorry for the late reply. OE nodes seem to have a lot of issues with receipts.
Warp syncs have a lot of missing receipts for certain ranges of blocks. You can use this script to check if your OE node has all receipts or not
https://github.com/pawanjay176/deposits-checker/blob/master/main.py
use it as
`python3 main.py <oe-endpoint> <trusted-endpoint (e.g. infura)>`

**Comment by paulhauner** [comment]
Closing since it seems to be an OE issue.
