### ISSUE TITLE
Beacon error: double free or corruption (out)

### ISSUE THREAD

**Issue by chonghe1** [sigp/lighthouse#2060]
## Description

Yesterday I saw a missed attestation in my validator, I checked and found that my beacon has the error: double free or corruption (out) at 13:30:16. Before that beacon has been running fine with consistent +-50 peers.

It restarted immediately and after that beacon running as usual.

Context: beacon running fine since 1st Dec before genesis and never got problem until this.

My system: Ubuntu desktop 20.04 LTS. Running beacon, validator and geth. 32GB ram and 1TB nvme SSD on Intel NUC10FNK
![beaconerrordetail](https://user-images.githubusercontent.com/44791194/101346713-ee234880-38c3-11eb-936b-bc2efb9e44a8.png)
![validator error](https://user-images.githubusercontent.com/44791194/101346861-27f44f00-38c4-11eb-9b33-63a2c70e420f.png)

## Version

v1.0.3. I downloaded the binary from github lighthouse-v1.0.3-x86_64-unknown-linux-gnu.tar.gz and runs it as a service file. ExecStart command (following Somer's guide, but I added metrics) =/usr/local/bin/lighthouse bn --network mainnet --datadir /var/lib/lighthouse --staking --metrics --eth1-endpoints http://127.0.0.1:8545,http://infura-endpoint,http://alchemy-endpoint

## Present Behaviour

It auto-restart and running normally now

**Comment by michaelsproul** [comment]
Thanks for the report!

Based on the NUC model number I guess your CPU is an Intel Core i5-10210U?

**Comment by chonghe1** [comment]
> Thanks for the report!
> 
> Based on the NUC model number I guess your CPU is an Intel Core i5-10210U?

Yes. thank you

**Comment by paulhauner** [comment]
I'm going to close this since we haven't seen this problem anywhere else and it seems unlikely we'll make progress from this point. Please re-open if you disagree :slightly_smiling_face:
