### ISSUE TITLE
We experienced some missed attestations this morning (Raspberry Pi 4 8 GB)

### ISSUE THREAD

**Issue by diglos** [sigp/lighthouse#2063]
## Description

We’ve experienced some missed attestations a few hours ago. It appears to be related to libp2p.

## Version

Lighthouse ARM64 1.0.3 official binary
HW: Raspberry Pi 4 8 GB + 1 TB Crucial SSD
Running Geth 1.9.24 + Lighthouse in the same node.

Hardware and performance seems fine and the validator has been doing great for 5 days in a row.

## Present Behaviour

We've been experiencing some missing attestations in the last hours. In particular, 10 out of 50. In every failed attestation, this message shows up before "INFO Successfully published attestations": 

**WARN Could not publish message      error: InsufficientPeers, service: libp2p**

Log of one missing attestation:

```
Dec  7 11:50:50 ethnode-f3b2bb7ac geth[2101]: INFO [12-07|11:50:50.188] Imported new chain segment               blocks=1  txs=185  mgas=12.491 elapsed=6.631s    mgasps=1.883   number=11405488 hash="8e8d95…225e43" dirty=644.38MiB
Dec  7 11:50:51 ethnode-f3b2bb7ac lighthouse[113993]: Dec 07 11:50:51.318 WARN Could not publish message               error: InsufficientPeers, service: libp2p
Dec  7 11:50:51 ethnode-f3b2bb7ac lighthouse[396483]: Dec 07 11:50:51.320 INFO Successfully published attestations     type: unaggregated, slot: 43152, committee_index: 2, head_block: 0xaa8eda0b0958896cd6e450facbac4f32d9f834d31bb005e39b864c66139a7b16, count: 1, service: attestation
Dec  7 11:50:53 ethnode-f3b2bb7ac lighthouse[113993]: Dec 07 11:50:53.000 INFO Synced                                  slot: 43152, block: 0xaa8e…7b16, epoch: 1348, finalized_epoch: 1346, finalized_root: 0xed0e…be0a, peers: 51, service: slot_notifier
Dec  7 11:50:53 ethnode-f3b2bb7ac lighthouse[396483]: Dec 07 11:50:53.010 INFO All validators active                   slot: 43152, epoch: 1348, total_validators: 1, active_validators: 1, proposers: 0, service: notifier
Dec  7 11:50:55 ethnode-f3b2bb7ac lighthouse[396483]: Dec 07 11:50:55.084 INFO Successfully published attestations     type: aggregated, slot: 43152, committee_index: 2, head_block: 0xaa8eda0b0958896cd6e450facbac4f32d9f834d31bb005e39b864c66139a7b16, signatures: 2, aggregator: 8271, service: attestation
Dec  7 11:50:56 ethnode-f3b2bb7ac geth[2101]: INFO [12-07|11:50:56.312] Deep froze chain segment
```

## Expected Behaviour

Publish all the attestations

## Steps to resolve

We did a validator restart that seemed to solve the issue but after 13 correct attestations, it got back.

A Beacon chain restart, though, seems to solve the problem (it is working fine now, at least for the last 40 attestations).

If you need us to enable debug mode or other tests, please let us know.

**Comment by glamperd** [comment]
I'm seeing similar behaviour, and I have a very similar hardware and software configuration. 
Seems to be related to a sudden drop in number of peers:
![image](https://user-images.githubusercontent.com/5004980/101404899-5fe2ad00-392b-11eb-82ad-3ed2396b400a.png)

The drop corresponds to these log messages from the beacon node:
```
Dec 08 03:15:33 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:33.756 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Dec 08 03:15:33 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:33.756 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Dec 08 03:15:33 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:33.756 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Dec 08 03:15:33 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:33.756 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Dec 08 03:15:33 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:33.757 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Dec 08 03:15:33 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:33.857 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Dec 08 03:15:34 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:34.097 INFO New block received                      hash: 0x5732…408e, slot: 44473
Dec 08 03:15:34 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:34.264 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Dec 08 03:15:34 ethnode-21eca8bd5 lighthouse[1547]: Dec 08 03:15:34.404 WARN Banning peer that is currently disconnecting, peer_id: 16Uiu2HAmESDcfBVYAtb4dJM9mWRbAzM4RrU3SjWtUVU3rsciiPBf, service: lib
```

**Comment by diglos** [comment]
Ummh, I can't see that in the logs or the Grafana Dashboard either. Libp2p shows a consistent peers connection (the missed attestations happened between 9-12 in the morning. The sudden lost of peers at 14:00 is because of the Beacon chain restart (which resolved the issue).

![image](https://user-images.githubusercontent.com/16838272/101409390-259eee80-38de-11eb-9f14-757a786ebdfd.png)

**Comment by AgeManning** [comment]
@glamperd - Your issue is distinct from this one. It looks like either your network has gone down, or your node froze for some reason (potentially processing something external). 

@diglos - The WARN message you are seeing, occurs when you don't have any peers that are also subscribed to your specific subnet. Under normal operation this should be unlikely but there are number of things that can potentially cause it. I can't know for sure without debug logs what has happened to you. 

It would good to always save debug logs so we can diagnose these issues. One thing to check is to ensure your clock is kept to sync with ntp.

**Comment by diglos** [comment]
Thanks!. We will enable debug mode and report here as soon as the issue comes back.

I would discard NTP as the Beacon restart solved the problem (it's been ok for more than 1 day now)

Regards!

**Comment by pawanjay176** [comment]
@diglos for the duration of the issue, were all attestations missed? or did you also get some successful attestations with a higher inclusion distance?

**Comment by diglos** [comment]
Not all were missing, some of them went through, even with 0 distance. See the screenshots below:

First missing attestations:

![image](https://user-images.githubusercontent.com/16838272/101942650-28555880-3bea-11eb-86e8-fedab5598739.png)

Then, it continues to miss some more until a Beacon restart is performed:

![image](https://user-images.githubusercontent.com/16838272/101942754-4f138f00-3bea-11eb-8b23-2d5aee34a471.png)

**Comment by riversyang** [comment]
I'm also facing the issue. After upgraded to v1.0.4, my bn node can only connected up to 3 ~ 6 peers, which caused only a few attestations can be published. The warning message is exactly the same as this issue.

WARN Could not publish message error: InsufficientPeers, service: libp2p 

I'm running lighthouse bn in a NAS server(in docker) which already made port forwarding(9000 tcp/udp) in my router.

**Comment by AgeManning** [comment]
We addressed some issues that could cause this in `v1.0.4`. If you could reach out to one of us on the discord server and provide some debug logs, we might be able to identify the issue. 
You should always find more than 3~6 peers and if not something is wrong.

**Comment by AgeManning** [comment]
I've noticed a similar thing initially. 

It looks like there are a lot of prysm peers in the DHT. So when your node tries to discover new peers, it finds a lot of prysm peers. Prysm, once they have reached their target peers do not accept new connections. So you discover lots of peers but just can never connect to them. And you must cycle through many peers until you find other client peers or peers that aren't full. 

I think I'll modify the Lighthouse DHT to remove peers that don't take on new peers so it should be easier to find non-full prysm peers.

**Comment by AgeManning** [comment]
I found after about 10-15 mins, I find some lighthouse nodes and easy reach the 50 peer target that I expect however.

**Comment by AgeManning** [comment]
Will try and improve initial discovery by filtering out the "full" peers from the DHT: https://github.com/sigp/lighthouse/issues/2107

**Comment by paulhauner** [comment]
The sudden drops in peer count are potentially related to #2155.

**Comment by paulhauner** [comment]
I'm going to close this since it seems stale and unlikely to progress from here. Please re-open if you feel differently.
