### ISSUE TITLE
Add validator balance Prometheus metric

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#2064]
## Description

Seems to be solid demand for this in Discord, some users have even made their own workarounds.

## Version

1.0.3

## Steps to resolve

Seems like the easiest way would be to query the standard API for balances on startup and then once per epoch for all enabled validators. And only do this if the VC has the `--metrics` flag.

It'd be adding some non-functional overhead by making completely new beacon node requests but I think if people are looking for validator metrics, this is one of the main one's they're after.

**Comment by isoosiss7** [comment]
I'll take this as an exercise.

**Comment by isoosiss7** [comment]
Pls review:
https://github.com/sigp/lighthouse/pull/2085
