### ISSUE TITLE
Remove constants from function parameters

### ISSUE THREAD

**Issue by drozdziak1** [sigp/lighthouse#208]
## Description
The spec defines several constants which currently are mostly placed in `ChainSpec`. This causes some of the spec-defined functions in Lighthouse to have different signatures - constants are passed instead of just being globally referenced (the `ChainSpec` has to be instantiated and my guess is it doesn't make sense to instantiate it every time)
## Present Behaviour
^^^^

## Expected Behaviour
We should be able to reference the necessary constants rightaway.

## Steps to resolve
1. Either:
* Break ChainSpec into individual const/static variables - a bit harder but way easier to maintain
* Instantiate a global instance of ChainSpec via lazy_static - a bit easier but less ergonomic and more bug-prone as Rust will complain about synchronization and make us use a Mutex which will need to be locked on every use. Deadlocks are also a possibility
2. Look for uses of ChainSpec and change accordingly. Mind lock lifetimes if the mutex approach is to be used

**Comment by paulhauner** [comment]
Closing this as I can't see us implementing this anytime soon.
