### ISSUE TITLE
EventSource missing chain_reorg

### ISSUE THREAD

**Issue by BeroBurny** [sigp/lighthouse#2088]
## Description

EventSource has missing `chain_reorg` topics [ETH2 Events spec](https://ethereum.github.io/eth2.0-APIs/#/Events/eventstream)

## Version

Lighthouse/v1.0.4-1abc70e/x86_64-linux (stable and unstable branch)

## Present Behaviour

return `400 Bad Request` on url `/eth/v1/events?topics=chain_reorg`

## Expected Behaviour

should work as every else topis from eth2 spec (head, block, attestation, voluntary_exit, finalized_checkpoint)

## Steps to resolve

implement `chain_reorg` event [(types.rs)](https://github.com/sigp/lighthouse/blob/1abc70e815a8dd078b8958450a7516e32cc693cd/common/eth2/src/types.rs#L744)

**Comment by michaelsproul** [comment]
Thanks for the report! This is being worked on in https://github.com/sigp/lighthouse/pull/2090

**Comment by paulhauner** [comment]
Resolved in #2090
