### ISSUE TITLE
eth1 node communication

### ISSUE THREAD

**Issue by memsido** [sigp/lighthouse#2093]
## Description

The beacon seems to be working fine, but reporting is all over the place (journalctl -fu over the lighthouse service):

Dec 15 16:28:49.139 INFO Synced                                  slot: 98842, block: 0x73c9…d616, epoch: 3088, finalized_epoch: 3086, finalized_root: 0x5041…8d1b, peers: 55, service: slot_notifier

Dec 15 16:28:49.139 WARN Syncing eth1 block cache                est_blocks_remaining: 11104, msg: sync can take longer when using remote eth1 nodes, service: slot_notifier

Dec 15 16:28:55.116 WARN Eth1 endpoint is far behind. Trying fallback ..., last_seen_block_unix_timestamp: 1607875086, endpoint: http://127.0.0.1:8545, service: eth1_rpc

Dec 15 16:28:55.116 CRIT Couldn't connect to any eth1 node. Please ensure that you have an eth1 http server running locally on http://localhost:8545 or specify one or more (remote) endpoints using `--eth1-endpoints <COMMA-SEPARATED-SERVER-ADDRESSES>`. Also ensure that `eth` and `net` apis are enabled on the eth1 http server, warning: BLOCK PROPOSALS WILL FAIL WITHOUT VALID, SYNCED ETH1 CONNECTION, service: eth1_rpc

Dec 15 16:28:55.116 ERRO Failed to update eth1 cache             error: Failed to update Eth1 service: "All fallback errored: http://127.0.0.1:8545 => EndpointError(FarBehind)", retry_millis: 7000, service: eth1_rpc

## Version
v1.0.4
lighthouse-v1.0.4-x86_64-unknown-linux-gnu.tar.gz

## Present Behaviour

geth used for eth1 endpoint is running with no errors
time synced (NTP service active)

Based on https://mainnet.beaconcha.in, the beacon is running and performing well.

**Comment by memsido** [comment]
Non-issue, something else is wrong. Reverted to older version, issue persists

**Comment by pawanjay176** [comment]
@memsido this error indicates that your eth1 node is not yet synced. Could you do `geth attach http://localhost:8545` and check `eth.syncing` in the json rpc console?

**Comment by memsido** [comment]
@pawanjay176 You are right, it is not synced! I am failing to understand how thats even possible. It was synced a week ago, I did not even think about checking that. Thank you, tho, now I have even more questions.

**Comment by pawanjay176** [comment]
There have been instances of geth needing to resync when there are power outages. You could have also lost peers for some reason.

**Comment by memsido** [comment]
Just an afterthought - would a restored time machine backup of a sandbox with a running virtual server work in this situation? Could such restored node sync from a backup?

Thank you for your insight.
