### ISSUE TITLE
v1.0.4 missing field `dependent_root`

### ISSUE THREAD

**Issue by winlin** [sigp/lighthouse#2097]
## Description
When I update from v1.0.3 into v1.0.4, the `validator_client` always print there error:

ERRO Failed to download validator duties     error: Failed to get proposer indices: Reqwest(reqwest::Error { kind: Decode, source: Error("missing field `dependent_root`", line: 1, column: 4928) }), service: duties

## Version
v1.0.4

**Comment by realbigsean** [comment]
@winlin make sure you update and restart both the validator client and the beacon node

**Comment by winlin** [comment]
> @winlin make sure you update and restart both the validator client and the beacon node

no we update the validator client first without update the beacon node.

does it need to update the beacon node first and then update the validator client? right?

**Comment by realbigsean** [comment]
From v1.0.3 to v1.0.4, the communication between the beacon node and validator client has changed. So you need to update both to v1.0.4 in order for them to communicate.

**Comment by winlin** [comment]
thanks for the help, it need to update both side.
