### ISSUE TITLE
Slasher error prevents BN startup on v1.0.5

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2119]
## Description

After updating to `v1.0.5`, many users have experience this error which prevents BN startup:

```
CRIT Failed to start beacon node             reason: Slasher open error: BincodeError(Io(Kind(UnexpectedEof)))
``` 

## Version

https://github.com/sigp/lighthouse/releases/tag/v1.0.5

## Work-around

You can one of two things to resolve this temporarily:

1. Delete the `~/.lighthouse/mainnet/beacon/slasher_db` directory, then restart the BN.
1. Omit the `--slasher` flag.

## Additional Info

I'm not sure if this is directly related to `v1.0.5` or if it's just the first reboot many have done since the slasher db wrapped-around. This requires more investigation.

**Comment by michaelsproul** [comment]
Damn it I think I know what this is. The broadcast PR added a field to the config (which is stored on disk) without updating the schema version or implementing a migration 😭 Sorry, that's my bad.

I can likely fix it once I'm back on Jan 4 for a v1.0.6 release.

**Comment by michael1011** [comment]
+1 can reproduce

**Comment by emilianobonassi** [comment]
Me too. Probably slasher db model changed. As per doc, slasher component is experimental and this is something which should happen.

TBH currently I wasn't able to slash anyone with the current setup.

**Comment by michael1011** [comment]
> As per doc, slasher component is experimental and this is something which should happen.

Yes, I am aware of that. But imho an upgrade to a new release should still not break your node and force you to downgrade again.

> TBH currently I wasn't able to slash anyone with the current setup.

Same. But that's not my major issue with lighthouse right now :sweat_smile:
