### ISSUE TITLE
Add Validator Index to "Published" VC Log Events

### ISSUE THREAD

**Issue by dlehenky** [sigp/lighthouse#2124]
## Description

Seems like essential info. Just add the validator index to "publish" events, so we know which key is responsible. This would be for both attestations and proposals.

## Version

master

## Present Behaviour

Information on specific validator is not present.

**Comment by paulhauner** [comment]
Thanks @dlehenky, but the API is not specified here. Instead, it's specified at https://github.com/ethereum/eth2.0-APIs so that multiple client implementations can collaborate. Lighthouse doesn't "own" the API definition.

Could you please raise this issue over there? Thanks.
