### ISSUE TITLE
Custom testnet validator fails pre-genesis

### ISSUE THREAD

**Issue by parithosh** [sigp/lighthouse#2127]
## Description

A custom testnet was setup with a genesis date in the future. The beacon and validator nodes were started with the custom spec. The validator crashes immediately stating genesis has not been observed yet (logs added below). 

## Version

The docker image of lighthouse, `sigp/lighthouse:v1.0.4`

## Present Behaviour

The validator docker image was started with the custom config found [here](https://gist.githubusercontent.com/parithosh/72b32ae41b0e016a6b546764754fc0be/raw/3836a3a08531fdcfb99addc6ea581f8a6c26dac8/custom_testnet_config.yaml)

The validator crashes with the log:
```
 INFO Initialized validators                  enabled: 100, disabled: 0
 INFO Connected to beacon node                version: Lighthouse/v1.0.4-1abc70e/x86_64-linux
 CRIT Failed to start validator client        reason: Unable to read spec from beacon node: ServerMessage(ErrorMessage { code: 404, message: "NOT_FOUND: Beacon chain genesis has not yet been observed.", stacktraces: [] })
 INFO Internal shutdown received              reason: Failed to start validator client
```

## Expected Behaviour

The validator should wait and continue to poll the beacon node till genesis has been observed. 

## Steps to resolve
- Copy the custom testnet config file, edit the genesis time to a time in the future
- Start the validator and beacon containers with `--testnet-dir=custom_testnet_config.yaml` and required flags
- Check logs of the validator container

**Comment by pawanjay176** [comment]
@parithosh could you paste the full commands you used to start the beacon and validator?
I think you could get this when bn and vc are using different configs.

**Comment by parithosh** [comment]
The beacon node was started with:
```
lighthouse --debug-level=debug --datadir=/data --testnet-dir=/data/custom_testnet_config bn --disable-enr-auto-update=true --enr-address=<redacted> --enr-tcp-port=9000 --enr-udp-port=9000 --port=9000 --discovery-port=9000 --target-peers=50 --boot-nodes=enr:-<redacted> --max-skip-slots=700 --eth1 --eth1-endpoints=<redacted> --http --http-address=0.0.0.0 --http-port=4001 --metrics --metrics-address=0.0.0.0 --metrics-port=8080
```

The validator was started with: 
```
lighthouse --testnet-dir=/data/custom_testnet_config vc --validators-dir=/data/validators --secrets-dir=/data/secrets --init-slashing-protection --server=http://localhost:4001/ --http --http-port=4002
```

**Comment by parithosh** [comment]
Retested on `v1.1.3` and it now behaves as expected. The validator doesn't crash anymore and instead waits + polls the beacon again.
