### ISSUE TITLE
Update to tokio v1.0

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#2129]
## Description

We are currently at tokio 0.3 and only some of the ecosystem updated to this intermediate version leaving us with scattered dependencies that we manually updated. 

Once all the ecosystem have updated to tokio v1 we should do a clean update across our dependencies that rely on tokio. 

The main ones are:
- [x] hyper
- [x] warp
- [x] discv5
- [ ] web3
- [x] reqwest

**Comment by hermanjunge** [comment]
Adding myself to this thread, as AFAIK `reqwest` is only used by testing in the Remote Signer. Maybe it'd be better to find an alternative for mock HTTP calls.

**Comment by pawanjay176** [comment]
Made a PR for discv5 here https://github.com/sigp/discv5/pull/57

**Comment by michaelsproul** [comment]
Reqwest has support now: https://github.com/seanmonstar/reqwest/releases/tag/v0.11.0

btw @hermanjunge `reqwest` is used by the `eth2` crate which wraps API access to the beacon node for the validator client (amongst other things).

**Comment by FelipeRosa** [comment]
web3 also updated to tokio 1.0: https://github.com/tomusdrw/rust-web3/releases/tag/v0.15.0

**Comment by pawanjay176** [comment]
warp seems good to go as well https://github.com/seanmonstar/warp/releases/tag/v0.3.0

**Comment by realbigsean** [comment]
Ive started working on this

**Comment by paulhauner** [comment]
Resolved in #2172
