### ISSUE TITLE
Support custom http headers for remote eth1 endpoints

### ISSUE THREAD

**Issue by elsesiy** [sigp/lighthouse#2139]
## Description

A user can either run a local eth1 endpoint via geth, oe, etc. or use a remote service such as Infura, Alchemy, etc. When opting for the latter, providers usually offer multiple layers to secure API access which is good practices especially if using a paid tier.

`--eth1-endpoints` allows the user to specify multiple endpoints but doesn't allow for additional configurations per endpoint such as custom HTTP headers. However, these are required to implement said additional security measures.

Infura example:
https://infura.io/docs/ethereum#section/Securing-Your-Credentials/Authenticating-using-a-Project-ID-and-Project-Secret

## Version
`v1.0.6-f183af2`

## Present Behaviour

A user is limited to whatever config can be provided via path params.

## Expected Behaviour

User should be able to specify custom HTTP headers per eth1 endpoint or general request modifications such as using a different (custom) user agent.

**Comment by jcracknell** [comment]
You may be able to authenticate using HTTP basic authentication by embedding it in the URL:

    https://:<project-secret>@<network>.infura.io/v3/YOUR-PROJECT-ID

Note the `:` indicating an empty username.

**Comment by elsesiy** [comment]
@jcracknell This won't work for `Bearer` or any other scheme afaik & it still won't be possible to specify e.g. a custom user agent

**Comment by omniproc** [comment]
@elsesiy true but what's the use case? You want to make sure requests are authenticated.  Infura offers the *option* to speficy a user-agent to somewhat limit access but that doesn't really protect you from much and it certainly isn't desireable over HTTP basic auth. Basic auth is as good as anything to fullfill the requirement you initially named. Why do you need bearer auth?

**Comment by paulhauner** [comment]
@elsesiy I'd be interested in the following:

- Are there any providers which *don't* work with the simple token-in-the-url scheme?
- Do the other eth2 or eth1 clients already provide this header functionality?

It's a reasonable amount of complexity to add these headers and I'm not sure exactly what's to gain. When using HTTPS the information in the URL is encrypted in exactly the same way as the header. If we add CLI flags to configure headers then they're going to be exposed to the shell in the same was as with the current scheme.

**Comment by paulhauner** [comment]
I'm going to close this for two reasons:

1. Inactivity
2. Since the merge, remote "eth1 endpoints" are no longer relevant. All users should have a local EE and I'm not sure why it would need further authentication.
