### ISSUE TITLE
Beacon-nodes optionally round-robin / random

### ISSUE THREAD

**Issue by joe-bowman** [sigp/lighthouse#2157]
## Description

Currently beacon node redundancy is ordered (which is a sensible default when your setup has a primary node, and a second one for failover scenarios); but in a situation where you have multiple beacon nodes for redundancy, and multiple validator nodes dependent on these, random assignment of beacon nodes would be preferable.

An optional parameter --bn-randomize (or similar), that treats all BNs equally and queries any one of them, rather than always in order, would be useful for balancing load.

It might be simpler to implement if this random sorting of the BNs happens at each slot (so you're sticky to 1 node per slot); but each nodes will randomly choose a _different_ order to the others (if that makes sense).

## Version
1.0.5

## Present Behaviour

BN preference is ordered (as per docs)

## Preferred Behaviour

BN preference is (optionally) randomised

## Steps to resolve

N/A

**Comment by paulhauner** [comment]
> but in a situation where you have multiple beacon nodes for redundancy, and multiple validator nodes dependent on these, random assignment of beacon nodes would be preferable.

I'm not convinced of on this one. Adding random choice adds a significant amount of complexity to the validator client, a critical component that we like to keep simple.

If you want to spread your VCs across BNs, I would suggest doing so at the devops layer (i.e., change the ordering of the `--beacon-nodes` flag manually). That way the user has more control and the VC is simpler.

In regards to load-balancing VCs across BNs through random choice, I'm not really sure that's something worth baking into LH either. There's quite a few edge-cases with swapping between BNs, seeing as they might be on different heads. It's *safe* for a VC to swap around BNs as much as it likes, but I really don't think its going to be efficient. We'll eventually run into issues where one BN is a block ahead of the other at an epoch boundary, causing different shuffling and therefore inefficiencies/errors with attestation production.

I'll leave this open for a bit to see if it gains a lot of interest, but my gut feeling is that this violates the KISS principle for the VC.

**Comment by joe-bowman** [comment]
> change the ordering of the --beacon-nodes flag manually

This was going to be my fall back; just adds a bunch of complexity my end :+1: 

> Adding random choice adds a significant amount of complexity to the validator client, a critical component that we like to keep simple.

Does it not just require shuffling the endpoint Vector in /common/lib.rs (although I guess this has a similar impact on eth1 nodes, and we probably want to be able to randomise one exclusively of the other).

**Comment by paulhauner** [comment]
> This was going to be my fall back; just adds a bunch of complexity my end +1

Yeah, I feel you. We use Ansible and had to deal with the assignment of VCs to BNs as well, it's a bit awkward. On our end we needed to ensure an even distribution, so randomness wouldn't work for us as there's a decent chance of a double-assignment.

> Does it not just require shuffling the endpoint Vector in /common/lib.rs (although I guess this has a similar impact on eth1 nodes, and we probably want to be able to randomise one exclusively of the other).

We could shuffle the incoming list, but we'd still have the behaviour where the first in the list is used the majority of the time (or, all of the time, if everything works perfectly).

You know your use-case better than me, but I would be a little cautious about randomly shuffling the `--beacon-nodes` flag. Each time you reboot the setup you're going to end up with a different topology, I find this type of behaviour can become quite frustrating when troubleshooting.

**Comment by paulhauner** [comment]
I'll close this for now, let me know if anyone really wants this feature.

**Comment by dong77** [comment]
I kinda do, but my setup is different:
 I have 4 BNs and 25 VCs. The 4 BNs are load-balanced via a k8s service, which means I only have one logical URI for `--beacon-nodes`. As of now, loads are routed to a fixed BN during a session and will switch to another one after 24 hours (k8s's longest session is 24 hours). My 2 ETH2 nodes are also behind a k8s service.

I'm not sure what the impact will be, especially after 2520 and I'm concerned.

Can we re-open this issue?

**Comment by mrabino1** [comment]
"I'm not convinced of on this one. Adding random choice adds a significant amount of complexity to the validator client, a critical component that we like to keep simple.

If you want to spread your VCs across BNs, I would suggest doing so at the devops layer (i.e., change the ordering of the --beacon-nodes flag manually). That way the user has more control and the VC is simpler."

FWIW.. I am personally less interested in load-balancing on an continual basis.. but rather only if node1 has an outage.. that it would randomly stick with ONE option of node2 / node3 ... until there is another outage...
