### ISSUE TITLE
Allow attesting to older slots

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2169]
## Description

#2130 resolves an immediate issue in a brute-force manner.

However, we could provide protection for the described attack whilst still allowing attestation production for *some* previous slots. If we have the head `BeaconState` then there's no reason we can't attest to earlier slots in it's current epoch or all slots in it's previous epoch (this is because the shuffling is known for these states).

This would have the affect of disabling attestations to *distant* slots, but still providing some support for past slots.

**Comment by kevlu93** [comment]
this one sounds interesting. wouldn't mind taking a stab at it.

**Comment by paulhauner** [comment]
> this one sounds interesting. wouldn't mind taking a stab at it.

Cool! Happy to help on the review :)

**Comment by paulhauner** [comment]
One of our primary goals is to avoid state reads whilst generating an attestation. To avoid this, we presently we only allow attesting for the current slot. However, this is too strict we could also expand it to include *some* prior slots.

To produce an attestation we need the following things from a `BeaconState`:

1. **The beacon committee length**: easily available for prev/current/next epoch
1. **The "head" root**: known for `SLOTS_PER_HISTORICAL_ROOT` (8,192) slots in the past via `state.block_roots`.
1. **The "source" epoch/root**: `state.current_justified_epoch` gives us the current epoch, `state.previous_justified_epoch` gives us the previous epoch, next epoch is unknown.
1. **The "target" epoch/root**: known for `SLOTS_PER_HISTORICAL_ROOT / 32` epochs in the past via `state.block_roots`.

Therefore, given some `BeaconState` (the *head state* in our case) it is possible to produce an attestation in the current and previous epochs without doing any state reads.

To achieve this, I think we'll need to modify some of the logic here to read values for the previous epch:

https://github.com/sigp/lighthouse/blob/3a24ca5f14c6e6d6612fd43eca82aa0c1e6aba16/beacon_node/beacon_chain/src/beacon_chain.rs#L961-L968

And then loosen this constraint:

https://github.com/sigp/lighthouse/blob/3a24ca5f14c6e6d6612fd43eca82aa0c1e6aba16/beacon_node/beacon_chain/src/beacon_chain.rs#L925-L950

**Comment by paulhauner** [comment]
If you're not still working on this @kevlu93, it might be a good one for @realbigsean.

**Comment by kevlu93** [comment]
Started working on this, but currently busy so haven't been able to spend time on it recently. Won't free up until after July 8. Would like to finish this but @realbigsean is more than welcome to take over

**Comment by realbigsean** [comment]
Hey @kevlu93, I'll start working on some other things might come back to this before then. But will let you know before I do

**Comment by paulhauner** [comment]
Hey all, I've had to start working on this since we're getting seeing some related errors on our Prater nodes :slightly_smiling_face:
