### ISSUE TITLE
bn /eth/v1/beacon/blocks/{block_id} return wrong information on skipped block

### ISSUE THREAD

**Issue by BeroBurny** [sigp/lighthouse#2186]
## Description

Making get request on skipped block return earliest not skipped block

## Version

**docker** sigp/lighthouse:v1.1.0

## Present Behaviour

GET /eth/v1/beacon/blocks/554465
https://pyrmont.beaconcha.in/block/554465

return information of block 554464
https://pyrmont.beaconcha.in/block/554464

## Expected Behaviour

GET /eth/v1/beacon/blocks/{block_id} (on skipped block)
should return 404

**Comment by paulhauner** [comment]
As an update to those watching, it's not immediately clear what the return result *should* be: https://github.com/ethereum/eth2.0-APIs/issues/126

However, I think it's reasonable for us to start returning 404 on skipped blocks. That seems to be what other clients have assumed.
