### ISSUE TITLE
Add caching for crosslink committee calculation

### ISSUE THREAD

**Issue by ralexstokes** [sigp/lighthouse#219]
## Description

The basic logic for computing crosslink committees at a given slot was implemented in #148. As per the spec, a production implementation will want to avoid re-computing the committees for each slot. This implies we want to add some caching of the crosslink committee calculation to the `BeaconState`.

## Present Behaviour

Every call computes the full committee assignment for a given epoch, even for slots in the same epoch.

## Expected Behaviour

The obvious place to cache is to only compute the shuffling for an epoch once. Once the shuffling for the previous epoch has passed, it can be dropped from the cache. The cache maintains two shufflings (for the previous and current epoch) this way, moving as a two-epoch window focused on the current epoch (and trailing into previous).

## Steps to resolve

Implement the required caching.

**Comment by paulhauner** [comment]
Now exists in `BeaconState` :)
