### ISSUE TITLE
Error compiling v1.1.1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by sandakersmann** [sigp/lighthouse#2203]
**Get this error while compiling:**

Compiling validator_client v0.3.5 (/home/ethereum/git/lighthouse/validator_client)
error[E0658]: use of unstable library feature 'bool_to_option'
  --> beacon_node/network/src/nat.rs:55:46
   |
55 |                     interface.ip().is_ipv4().then(|| interface.ip())
   |                                              ^^^^
   |
   = note: see issue #64260 <https://github.com/rust-lang/rust/issues/64260> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `network`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lighthouse v1.1.1 (/home/ethereum/git/lighthouse/lighthouse)`, intermediate artifacts can be found at `/home/ethereum/git/lighthouse/target`

Caused by:
  build failed
make: *** [Makefile:20: install] Error 101

_________________________________________________________________________________-

An unstable feature was used.

Erroneous code example:

```
#[repr(u128)] // error: use of unstable library feature 'repr128'
enum Foo {
    Bar(u64),
}
```

If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using rustup).

If you're using a nightly version of rustc, just add the corresponding feature
to be able to use it:

```
#![feature(repr128)]

#[repr(u128)] // ok!
enum Foo {

**Comment by realbigsean** [comment]
@sandakersmann can you check what version of rust you are compiling with? `rustc --version` you'd get this error if you haven't updated to `1.50.0`, which was recently released

**Comment by sandakersmann** [comment]
@realbigsean Thanks :) Updated Rust and now it works.
