### ISSUE TITLE
Cors wildcard panics

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#2205]
## Description

It seems like `--http-allow-origin` and `--metrics-allow-origin` can no longer parse `'*'`, as seen in #2204 .  I'm not sure about where we lost this ability but we had added a change to warp here a while ago: 

https://github.com/paulhauner/warp/commit/a7685b76d70c3e5628e31d60aee510acec3c5c30

In order to set the `Access-Control-Request-Headers` to `*` instead of `null`. 

## Version

v1.1.1

## Present Behaviour

Panics if you provide a wildcard for any CORS flag.

## Expected Behaviour

Parse the wildcard correctly.

## Steps to resolve

We can either update the sigp `warp` fork to 0.3 and add the wildcard header change back in, or we may be able to just use `null` instead of `*` for `Access-Control-Request-Headers`, but I don't remember if that had an impact on UI development? @paulhauner

**Comment by paulhauner** [comment]
I vaguely recall trying to use null but it had a different effect.

We might have to update our fork again.

**Comment by ChosunOne** [comment]
Just experienced this error myself.  This is pretty serious as I was starting to lose eth after upgrading.

**Comment by maurodelazeri** [comment]
Updated, looks good!

**Comment by paulhauner** [comment]
For the record, a fix has been released in https://github.com/sigp/lighthouse/releases/tag/v1.1.2
