### ISSUE TITLE
Add [--password-path] flag to [lighthouse account validator import] subcommand

### ISSUE THREAD

**Issue by mFarghaly** [sigp/lighthouse#2224]
## Description
Currently `lighthouse account validator import` subcommand only supports reading password interactively or reading from stdin.

## The problem
In environments like Kubernetes, container can't read input from stdin and can't work interactively

### Version
we're using latest released version `v1.1.3`

### Expected behavior
`lighthouse account validator import` should accept `--password-path` that reads password from file.

**Comment by paulhauner** [comment]
Thanks @mFarghaly, good suggestion.

After discussion with @realbigsean, there's two design questions here:

1. The `validator import` command can import multiple validators. How do we handle that?

I think the simplest solution would be to require `--reuse-password` when `--password-path` is supplied, meaning that the password file contains a single password which applies to all validators. Would that work for you @mFarghaly? The alternative is some sort of structured password file which I suspect may be annoying for users.

2. Should we copy the password into the `validator_definitions.yml` file, or should we tell the `validator_definitions.yml` file to always read the password from `--password-path`?

I think we should just copy the password into `validator_definitions.yml` and then tell the user the can delete the password file. I think this will be simpler for users: we don't want them to be surprised if the VC fails to start when they delete that file or had it on a temporary volume.

**Comment by mFarghaly** [comment]
> I think the simplest solution would be to require --reuse-password when --password-path is supplied

This works!

Another approach is `--password-path` can be used only with `--keystore` option to import a single keystone at a time. In other words `--password-path` can't be used with `--directory` option.


> Should we copy the password into the validator_definitions.yml file, or should we tell the validator_definitions.yml file to always read the password from --password-path?

Prioritizing security here, I prefer reading password content from password path, or copying the file to `{data dir}/secrets/{validator public key}` to make sure it won't cause an issue if user accidentally deletes the file.

**Comment by paulhauner** [comment]
> Prioritizing security here, I prefer reading password content from password path, or copying the file to {data dir}/secrets/{validator public key} to make sure it won't cause an issue if user accidentally deletes the file.

I'm not necessarily opposed to it, but that would be different to the current behaviour of `validator import`. What's the benefit you see for password in `{data dir}/secrets/{validator public key}` vs. `validator_definitions.yml`?

**Comment by mFarghaly** [comment]
gotcha! there's no big difference.

**Comment by realbigsean** [comment]
Closed in #2228
