### ISSUE TITLE
Feature request: add beacon node version to prometheus metrics

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#2225]
## Description

It would be handy to expose the version of the beacon node through a prometheus metric.

## Version

Feature request.

## Present Behaviour

The version is available through logs but that isn't so useful for remote monitoring.

## Expected Behaviour

A prometheus metric like:

```
lighthouse_info{version="1.1.3"} 1
```

would be nice. Additional labels can be added for other items if desired (commit hash or whatever).

**Comment by paulhauner** [comment]
I agree, great suggestion.

**Comment by paulhauner** [comment]
This would be a good spare-time task for @realbigsean, @pawanjay176 or @macladson :slightly_smiling_face:

**Comment by macladson** [comment]
Resolved in #2427. Also see [the corresponding PR](https://github.com/sigp/lighthouse-metrics/pull/25) in `sigp/lighthouse-metrics`.
