### ISSUE TITLE
feature request - Add a way to remove the deposit data

### ISSUE THREAD

**Issue by Jayhem** [sigp/lighthouse#2227]
## Description

In some cases the deposit data gets corrupted when running the beacon with redundant eth1 endpoints. When this happens the beacon cannot recover, it would be useful to give the user an option to remove the deposit data via a flag/option.

## Version
Lighthouse v1.1.3-46920a8
BLS Library: blst
Specs: mainnet (true), minimal (false), v0.12.3 (false)

## Present Behaviour

The only way to recover from this issue is to remove the whole database using the --remove-db flag. This 'solution' however means that in in addition to the deposit data, all of the eth2 data needs to be synchronized.

## Expected Behaviour
By providing a way to reset/erase the eth1 deposit data, the beacon can be back to a running state faster than when deleting the whole database.

## Steps to resolve

n/a

Additional thoughts: obviously it would be better if the beacon was able to recover from a situation where there is a gap in deposits. It looks to me that switching from one endpoint to another was the trigger for this behavior in my case.

**Comment by michaelsproul** [comment]
I think the `--eth1-purge-cache` flag solves your problem? (`lighthouse bn --eth1-purge-cache`)

Although I agree with your broad point that we should be able to recover from faulty Eth1 nodes more readily

**Comment by pawanjay176** [comment]
Ideally, the eth1 syncing should recover (should stop logging `NonConsecutive` errors) once you point it to a correctly synced endpoint. If you haven't yet purged your eth1 cache with the `--eth1-purge-cache` option yet, it'd be helpful if you could send us the output from
`curl localhost:5052/lighthouse/eth1/syncing`
`curl localhost:5052/lighthouse/eth1/deposit_cache`

**Comment by Jayhem** [comment]
> 
> 
> Ideally, the eth1 syncing should recover (should stop logging `NonConsecutive` errors) once you point it to a correctly synced endpoint. If you haven't yet purged your eth1 cache with the `--eth1-purge-cache` option yet, it'd be helpful if you could send us the output from
> `curl localhost:5052/lighthouse/eth1/syncing`
> `curl localhost:5052/lighthouse/eth1/deposit_cache`

I have erased the db and restarted a couple of days ago, so I cannot provide this info. 
I had it happen twice fairly quickly by simply having 2 remote eht1 endpoints configured, so maybe that is a configuration you would want to test out.

**Comment by pawanjay176** [comment]
> I had it happen twice fairly quickly by simply having 2 remote eht1 endpoints configured

I have somehow never been able to replicate this issue locally, even with OE and Nethermind nodes as fallbacks.

Closing this as we already have a way to remove deposit data, feel free to reopen :)
