### ISSUE TITLE
Spec v1.0.1

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2232]
## Description

[Spec v1.0.1](https://github.com/ethereum/eth2.0-specs/releases/tag/v1.0.1) claims it has some new tests:

> A few additional deposit consensus tests were added to ensure clients can process the 0x01 prefix as well as "malformed" prefixes/credentials.

I haven't looked at the tests, but we should review them and implement them (or declare why we aren't going to).

**Comment by paulhauner** [comment]
@michaelsproul you might find this interesting :)

**Comment by michaelsproul** [comment]
Oh yeah I'm happy to take this :+1: Should be straight-forward
