### ISSUE TITLE
beacon_node/store: potential deadlock in hot_cold_store.rs

### ISSUE THREAD

**Issue by Chain-Fox** [sigp/lighthouse#2245]
## Description

Following #1241, for parking_lot::RwLock, “attempts to recursively acquire a read lock within a single thread may result in a deadlock.” I found two pairs of locks that may have potential deadlocks through static analysis, both in beacon_node/store/src/hot_cold_store.rs.

https://github.com/sigp/lighthouse/blob/46920a84e857d6c086adf4b42810ac03de94ed3e/beacon_node/store/src/hot_cold_store.rs#L668-L674
The first pair:
In fn `load_cold_intermediate_state()`:
The first lock `split.read()` is at L674.
Following the path L682->L306 (or L682->L318->L625->L638->L682->L306),
the second lock `split.read()` is in `get_split_slot()` at L818.

The second pair:
In fn `load_cold_intermediate_state()`:
The lock `split.read()` at L674 may deadlock with itself.
The path is L682->L318->L625->L638.

## Version

stable

## Present Behaviour

None

## Expected Behaviour

None

## Steps to resolve

Maybe pass the lock result down to the callee to avoid the second lock? Or use `read_recursive()` instead of `read()` to make it reentrant.

**Comment by michaelsproul** [comment]
This is awesome, thank you! I'll look at implementing fixes this week, and will read some more about your tool to see if it's something we could incorporate into our CI process
