### ISSUE TITLE
Wrong block returned when you fetch information about orphaned/missed blocks

### ISSUE THREAD

**Issue by olelis** [sigp/lighthouse#2250]
## Description

When you fetch information about orphaned block, then it shows information about previous block,
For example, if you do following request: `/eth/v1/beacon/blocks/57223`, system will return information about slot `57222`

```
{
  "data": {
    "message": {
      "slot": "57222",
      "proposer_index": "9646",
      "parent_root": "0x88c6252f5b78acb8d3cc8dff83bf78cf2df5ceec542d16fa242f0351e2c1646e",
      "state_root": "0x6cfda48515ef47c4a8402ec4e195d884ba294a0b4af606f460baa6c715eff5b8",
      "body": {
.... 
```

Same happens for "missed" blocks, for example, query `/eth/v1/beacon/blocks/123` returns slot 122

However, this works fine for normal, existing blocks.

## Expected Behaviour

Return "missed" or "orphaned" information about slot.

**Comment by paulhauner** [comment]
Thanks @olelis. This exists at https://github.com/sigp/lighthouse/issues/2186 so I'll close this for now.
