### ISSUE TITLE
Feature Request: Add flag to validator client for custom CA certs 

### ISSUE THREAD

**Issue by djoyahoy** [sigp/lighthouse#2262]
## Description

I would like a flag to provide custom CA certificates to the validator client when connecting to the beacon http endpoint.

## Version

N/A

## Present Behaviour

Users need to have custom ca certs installed on the OS.

## Expected Behaviour

Users can supply a flag to the validator client to use custom ca certs.

**Comment by paulhauner** [comment]
This might be a good one for @macladson or @pawanjay176 in their spare time :slightly_smiling_face: 

We'll need this type of functionality for the remote signer, so it'll be nice to get it figured out beforehand.

**Comment by macladson** [comment]
Resolved in #2703. Should be available in the next release :slightly_smiling_face:
