### ISSUE TITLE
Consider being less strict about chain spec in VC

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2274]
## Description

Currently a Lighthouse VC will reject any unknown fields included in a chain spec fetched from its BN. This has caused Lighthouse VCs to stop working with Teku BNs hosted by Infura, which is unfortunate.

See the corresponding issue on the Teku repo for more information: https://github.com/ConsenSys/teku/issues/3749

## Version

Lighthouse v1.2.1

**Comment by paulhauner** [comment]
This seems reasonable to me. Something irks me about silently accepting and then ignoring a configuration value, but it seems like it's better than the alternative.

**Comment by paulhauner** [comment]
Resolved in #2277
