### ISSUE TITLE
/beacon/states/{state_id}/validators/validator_id returns incorrect error code

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#2275]
## Description

The eth2 api https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateValidator spec is a bit unclear as to what to return when the validator_id is not present in the given state. 
We return a 404 in this case. Teku seems to be returning 400. Found this incompatibility when testing a lighthouse pyrmont validator with a teku infura beacon node.
Got the error
```
ERRO Failed to resolve pubkey to index       pubkey: 0x81f939c047f01bd93fc777c896eb2204a31a72f9b1a8f6e6db8c7fdbf08db3e4a9d272c38321ad2cade108b4da9eaa85, error: All endpoints failed https://<INFURA-KEY>@eth2-beacon-pyrmont.infura.io/ => RequestFailed(StatusCode(400)), service: duties
```
## Version

unstable

## Expected Behaviour

Not sure as the spec seems ambiguous whether to return 400 or 404 in the case of a validator not present in the state.

## Steps to resolve

Fix in lighthouse/teku if spec is clear or open an issue to clarify in the specs repo.

**Comment by ethDreamer** [comment]
Opened a new issue:

* https://github.com/ethereum/eth2.0-APIs/issues/161

**Comment by ethDreamer** [comment]
@pawanjay176 see comment on the linked issue above. Looks like `404` is the correct code to return in this instance as one of the examples shown is `ValidatorNotFound`. We should inform teku.

**Comment by paulhauner** [comment]
It seems like LH is doing the right thing and returning 404, so I'll close this. Please feel free to reopen if I missed something.

Thanks @pawanjay176 and @ethDreamer.
