### ISSUE TITLE
Reduce eth_chainId and net_version calls to eth1 node

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2282]
## Description

I noticed that a significant portion (~30%) of our calls to eth1 nodes are to the `eth_chainId` and `net_version` endpoints. Here's a graph from Infura showing the usage from several BNs:

![infura](https://user-images.githubusercontent.com/6660660/112553865-66812b80-8e19-11eb-8e24-7d4adde0eae2.png)

Considering that Infura (and other services) are billed per-request, we could provide tangible cost savings to our users by reducing the number of requests. It seems that chain id and version are low hanging fruit, perhaps we only poll them on first request and every 100th request or so?

**Comment by pawanjay176** [comment]
Additionally, I think we can safely increase the auto update interval for all eth1 calls from 7 seconds to atleast 1 minute. Given the `ETH1_FOLLOW_DISTANCE` being significantly large and the eth1 block time being 14 seconds, polling the eth1 node every 7 seconds is a waste of resources imo (after we are synced with the eth1 chain).  We would need ~ 1/8th the current requests with a 1 minute update interval.

**Comment by macladson** [comment]
I'm jumping on this.

**Comment by paulhauner** [comment]
Resolved in #2340
