### ISSUE TITLE
eth_chainId may return an error for unsynced eth1 nodes

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#2293]
## Description

Earlier, geth used to return chainId as 0 when it was not fully synced. With https://github.com/ethereum/go-ethereum/pull/21686 , now it returns an error if it's not past the eip 155 block. Need to handle this error scenario.

## Version

Lighthouse stable, Geth 1.10

## Present Behaviour

We get an `Endpoint NotReachable` error on lighthouse when geth sync is not past the eip 155 block which is misleading.
 
## Expected Behaviour

Should handle the error case and return Not Synced error message.

## Steps to resolve

Handle the error case here 
https://github.com/sigp/lighthouse/blob/9eb1945136cc2e517bed47d7a8a1cb1c6915d23a/beacon_node/eth1/src/service.rs#L162-L164

**Comment by jmcph4** [comment]
@pawanjay176 Are you suggesting adding the "Not Synced" error condition to `EndpointError` here?

https://github.com/sigp/lighthouse/blob/9eb1945136cc2e517bed47d7a8a1cb1c6915d23a/beacon_node/eth1/src/service.rs#L45

**Comment by pawanjay176** [comment]
@jmcph4 the `EndpointError::FarBehind` implies that the eth1 node is not synced so we can use that instead. 

I think the simplest way to resolve this would be to return a `Eth1Id::Custom(0)` on getting the error message from the eth1 node since we return a `FarBehind` endpoint on getting chainId of 0 anyway
https://github.com/sigp/lighthouse/blob/9eb1945136cc2e517bed47d7a8a1cb1c6915d23a/beacon_node/eth1/src/service.rs#L167-L174

You will have to modify the get_chain_id function [here](https://github.com/sigp/lighthouse/blob/9eb1945136cc2e517bed47d7a8a1cb1c6915d23a/beacon_node/eth1/src/http.rs#L93) to return a `Eth1Id::Custom(0)` on the specific eip 155 error

Let me know if you have other questions

**Comment by jmcph4** [comment]
@pawanjay176 Thanks for the clarification. I'm currently just playing around with the various RPC calls and seeing how both Geth behaves and how Lighthouse handles responses.

Do you think `match`ing against the Geth error string in `eth_chain_id` is the way to go?

**Comment by pawanjay176** [comment]
> Do you think `match`ing against the Geth error string in `eth_chain_id` is the way to go?

Yep. This is the only case afaik where we need to parse an error from geth into something valid. If I remember correctly, Nethermind and OpenEthereum return the correct chain id right from when syncing starts, so this is a geth specific issue.

I can't think of a better way. @paulhauner any ideas?

**Comment by paulhauner** [comment]
Resolved in #2304
