### ISSUE TITLE
Minimum Outbound Peers

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#2325]
## Description

Although this usually happens due to the bootstrap process, we should make it explicit. Reserve a fraction of our target peer count for outbound-only connections. 

Implementing this comes in two forms. The first is continuing discovery queries until we have filled our outbound quota, and secondly, not removing peers if they will drop us below our outbound quota.

**Comment by kevlu93** [comment]
has anyone started working on this? can take a stab at it if not

**Comment by AgeManning** [comment]
Not yet, all yours. 

Let me know if you need some help or direction

**Comment by paulhauner** [comment]
Resolved in #2356
