### ISSUE TITLE
Apple Silicon M1 support?

### ISSUE THREAD

**Issue by Sajjon** [sigp/lighthouse#2329]
I would like to know if Lighthouse supports Apple Silicon M1 chip?

**Comment by estensen** [comment]
Not natively, but Lighthouse runs great with [Rosetta](https://support.apple.com/en-us/HT211861)

**Comment by michaelsproul** [comment]
It looks like we're mainly blocked on M1 support in the Rust compiler, which should hopefully appear in the next year or so: https://github.com/rust-lang/rust/issues/73908

If anyone with an M1 Mac would like to try compiling Lighthouse with the existing tier 2 support, you might be able to follow a similar process to the one described here: https://github.com/BurntSushi/ripgrep/issues/1737. Although, warning, _here be dragons_. This would mostly be for interest's sake (we can't support M1 until we have it on CI).

**Comment by cjuha** [comment]
I have been running Lighthouse compiled on rustc 1.51.0 (stable-aarch64-apple-darwin) successfully on a M1 Mac Mini. Lighthouse has compiled without problems to an arm64 binary since around version 1.1.1, and has been rock stable since version 1.2.2.

**Comment by Sajjon** [comment]
@cjuha Do you mean that you'r running Eth 2.0 beacon chain with 32 ETH staked using Lighthouse with you M1 machine? 

Or do you mean you have been running Lighthouse for bit and then shut it down, but not felt confident enough to actually stake your 32 ETH with it?

I'm contemplating on starting staking now on my M1 Mac mini or if I should wait until support... seams more offical/stable.

Thanks!

**Comment by cjuha** [comment]
@Sajjon I am staking with the M1 Mac Mini, and have been doing so for several months now. Since Lighthouse version 1.2.2, validator average effectiveness (as reported by Beaconcha.in) has constantly been 98-100%. I have been greatly liking the fact that the machine is very stable, silent, and energy efficient. I can see these becoming popular validator boxes in the future once the platform matures.

In case you want to hear more details, I'm present at the Lighthouse Discord server with this same nickname 🙂

**Comment by paulmillr** [comment]
Hey folks, this would be awesome to have. The chips are extremely efficient and silent. Nimbus already provides official binaries, now it's lighthouse turn!

**Comment by Sajjon** [comment]
@paulmillr Ive been running Lighthouse on my M1 for over three months now and it is super stable. I have 100% attestation rate.

**Comment by paulhauner** [comment]
> @paulmillr Ive been running Lighthouse on my M1 for over three months now and it is super stable. I have 100% attestation rate.

Good to hear, thanks for the feedback @Sajjon Are you using the aarch64 binaries we're publish with the releases, or building your own please?

Note: edited because I tagged the wrong person. Sorry.

**Comment by paulmillr** [comment]
@paulhauner aarch64 binaries you're publishing don't work with M1. aarch64 != arm64. See the outputs of file for lighthouse and for proper M1 app:

```
./lighthouse: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=96e8fd21b8f37397b70929aa550c25ecbdadfaac, with debug_info, not stripped

xcode (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by jtomanik** [comment]
For anyone interested in running lighthouse on M1.
I'm trying to submit a homebrew formula for lighthouse:
https://github.com/Homebrew/homebrew-core/pull/82893 

That would allow anyone to get it via `brew install lighthouse` but for the moment it's blocked until 1.5.0

**Comment by riptl** [comment]
I have picked up and finished @jtomanik's work.
Lighthouse is now available on Homebrew: https://formulae.brew.sh/formula/lighthouse

EDIT: Any M1 users are welcome to test.
