### ISSUE TITLE
Lighthouse attestations failing

### ISSUE THREAD

**Issue by nikihana** [sigp/lighthouse#2360]
## Description

Lighthouse attestations are failing per beaconcha.in
## Version

Please provide your Lighthouse and Rust version. Are you building from
`stable` or `unstable`, which commit?

Lighthouse version 1.3.0 and the latest version of rust (as of today)

## Present Behaviour

I am running lighhouse on an ubuntu 20.04 server with 6 GB RAM and 150 GB SSD. (I am using infura for eth1) It has been working fine since Dec2020, but the attestations started failing last week. Today I updated lighhouse from 1.02 to 1.3.0 this morning and I dont see any errors in the syslog - but the beaconcha.in is still reporting attestations are failing.

## Expected Behaviour

The Attestations should not fail.

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
As diagnosed on Discord, this is an instance of https://github.com/sigp/lighthouse/issues/2159, so I'll close this for now. We can help you sort it out on Discord.
