### ISSUE TITLE
rust error (E0257) while upgrading to 1.4

### ISSUE THREAD

**Issue by 0xPNZ** [sigp/lighthouse#2428]
Stats:
Ubuntu 20.02.2LTS, fully upgraded.
Geth 1.10.4
Lighthouse 1.3.0
rustc 1.53.0
Intel i7
Ram 32GB
SSD 2Tb

Upgrading to lighthouse v 1.4.0 via "make" command, the last job (861/861) gets:
error[E0257]: overflow evaluating the requirement...

full statement here:
https://controlc.com/b2957787

**Comment by pawanjay176** [comment]
there was a breaking change in rustc 1.53. You will have to downgrade to rustc 1.52.1 temporarily for it to work.
See this comment for more details #2420 (comment)

**Comment by michaelsproul** [comment]
I've pinned https://github.com/sigp/lighthouse/issues/2420 so that it's more visible on GitHub
