### ISSUE TITLE
File permissions for validator client API keys are insecure

### ISSUE THREAD

**Issue by dnkolegov** [sigp/lighthouse#2437]
## Description

A validator client uses two API keys: ".secp-sk" (secret key) and "api-token.txt" (the corresponding public key).
Both files are stored in a user directory with 644 permission bits.
So any user on the host can read them.

To reproduce the issue just run:

```
docker run -it -p 127.0.0.1:9000:9000 -p 127.0.0.1:5062:5062 -p 127.0.0.1:5052:5052 sigp/lighthouse /bin/bash

lighthouse beacon --http --http-address 0.0.0.0 &
lighthouse vc --http &
ls -laF ~/.lighthouse/mainnet/validators/{.secp-sk,api-token.txt}
```

## Version
Lighthouse/v1.4.0-3b600ac

## Expected Behaviour

Permission bits must be 600.

**Comment by paulhauner** [comment]
Resolved in #2499
