### ISSUE TITLE
Simplify repeated SSZ "round-trip" tests into macro

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#244]
## Description

Each type in `types` repeats a SSZ test for encoding then decoding the object.

https://github.com/sigp/lighthouse/blob/a1118e13ae1279d9bfcc7e4a9faff5a55da2507d/eth2/types/src/attestation.rs#L90-L99

https://github.com/sigp/lighthouse/blob/a1118e13ae1279d9bfcc7e4a9faff5a55da2507d/eth2/types/src/deposit.rs#L65-L74

This is a prime target for a macro.

## Steps to resolve

- Create a `eth2/types/src/macros.rs` file to house the macro.
- Create a `test_ssz_round_trip` macro, using the [slot and epoch ssz test macros](https://github.com/sigp/lighthouse/blob/a1118e13ae1279d9bfcc7e4a9faff5a55da2507d/eth2/types/src/slot_epoch_macros.rs#L548-L574) as inspiration.
- Replace all the duplicated `fn test_ssz_round_trip(..)` tests with the new macro.

**Comment by michaelsproul** [comment]
I've started working on this, it looks quite straight-forward (a macro already exists in `slot_epoch_macros`)
