### ISSUE TITLE
Altair CPU usage

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2440]
## Description

This issue provides a place to track the increased CPU usage when switching to Altair.

Here are some graphs when using https://github.com/paulhauner/lighthouse/commit/9db00d304b7fe2972e73427102ef90212d2def2b from https://github.com/paulhauner/lighthouse/tree/ad0-beta. You can see the increase after that Altair fork at ~19:12:

![altair-block-times](https://user-images.githubusercontent.com/6660660/124900758-baa8c800-e024-11eb-84a4-97a27f8fc9ac.png)
![altair-avg-load](https://user-images.githubusercontent.com/6660660/124900764-bb415e80-e024-11eb-8826-879900d13516.png)

It seems likely that #2415 will improve/fix these stats, especially the block processing ones.

**Comment by michaelsproul** [comment]
Another thing that'll help will be tree hash caches for the participation bits, which we lack currently

**Comment by michaelsproul** [comment]
#2415 doesn't seem to have helped a great deal, and tree hashing looks like it's running in <10ms.

**Comment by michaelsproul** [comment]
Current theory is that it might be to do with processing 512 sync committee messages every slot, at a cost of ~3ms each (on our AWS boxes). That's a whole 1.5 seconds of signature verification!

Using single signature verification seems to be marginally slower on our testnet nodes:

![message_signature_verif](https://user-images.githubusercontent.com/4452260/125246673-6e67cb80-e335-11eb-8a87-5b03edea4283.png)

(single verification enabled around 15:30)

We may need a batching approach like #2399

**Comment by michaelsproul** [comment]
Closing this, as I think we've solved all of the Altair CPU issues (notably #2560)
