### ISSUE TITLE
Vulnerability with `prost` (a libp2p dependency)

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2443]
## Description

In #2436 I've ignored the following `cargo audit` vuln: https://github.com/libp2p/rust-libp2p/blob/master/core/Cargo.toml

We need to upgrade to `prost >= 0.8.0` to resolve this vuln, however lip2p is still on `0.7`: https://github.com/libp2p/rust-libp2p/blob/master/core/Cargo.toml

## Steps to resolve

1. Wait for libp2p to update.
2. Remove [the ignore](https://github.com/sigp/lighthouse/blob/ab1e383233886e977123dbcd401ec156f111ab1e/Makefile#L145) from CI.

**Comment by mxinden** [comment]
@paulhauner rust-libp2p v0.39.1 uses prost v0.8:

https://github.com/libp2p/rust-libp2p/blob/b814231251a707f8efdff6b4a74019a7635ac470/core/Cargo.toml#L28

**Comment by paulhauner** [comment]
Resolved via #2493
