### ISSUE TITLE
Create derive macro for TreeHash

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#245]
## Description

Presently we manually implement `TreeHash` on all types.

https://github.com/sigp/lighthouse/blob/a1118e13ae1279d9bfcc7e4a9faff5a55da2507d/eth2/types/src/attestation.rs#L62-L71

This is a prime target for a procedural derive macro, like implemented in #242.

## Steps to resolve

- Add a `#[derive(TreeHash)]` macro in the `ssz_derive` crate.
- Replace manual implementations with the derive wherever possible.

~~(Note: `ssz_derive` is presently a PR in #242 and not in master)~~

**Comment by paulhauner** [comment]
@mjkeating you might find this interesting :)

**Comment by mjkeating** [comment]
Cool. I'll start looking at this.

**Comment by paulhauner** [comment]
Fixed in #251
