### ISSUE TITLE
Allow the VC to listen on 0.0.0.0 with a flag

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2454]
## Description

Presently, the VC doesn't accept the `--http-address` field for this reasoning:

https://github.com/sigp/lighthouse/blob/3b600acdc5bf9726367c18277a22486573b8b457/validator_client/src/cli.rs#L121-L128

This restriction has showed to be very annoying for Docker setups; you can't access the container from another container, even if you never intend to expose it to the internet. @dapplion raised this most recently.

I propose we make the following changes:

- Add the `--http-address` flag to the VC.
- Add the `---unencrypted-http-transport` flag, and require it to be present if `--http-address` is used.
    - In the help text for this flag we should clearly explain why it's unsafe.
    
 P.S., Don't forget to update the VC CLI tests! https://github.com/sigp/lighthouse/blob/stable/lighthouse/tests/validator_client.rs

**Comment by macladson** [comment]
Closed by #2467
