### ISSUE TITLE
Create derive macro for TestRandom

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#246]
## Description

Presently we manually implement `TestRandom` on all types.

https://github.com/sigp/lighthouse/blob/a1118e13ae1279d9bfcc7e4a9faff5a55da2507d/eth2/types/src/attestation.rs#L73-L82

This is a prime target for a procedural derive macro, like implemented in #242.

## Steps to resolve

- Create a `test_random_derive` library crate in `eth2/utils`, using `eth2/utils/ssz_derive` as inspiration.
- Add a `#[derive(TestRandom)]` macro in the `test_random_derive` crate.
- Replace manual implementations with the derive wherever possible.

~~(Note: `ssz_derive` is presently a PR in #242 and not in master)~~

**Comment by thojest** [comment]
work started :)

**Comment by paulhauner** [comment]
Fixed in #250
