### ISSUE TITLE
make failing on last step

### ISSUE THREAD

**Issue by hanpeternicholas** [sigp/lighthouse#2475]
## Description
'make' is failing on the last step and shows output:

## Version
Lighthouse v1.4.0
rustc 1.53.0 (53cb7b09b 2021-06-17)

## Present Behaviour
```
error: aborting due to previous error

For more information about this error, try `rustc --explain E0275`.
error: failed to compile `lighthouse v1.4.0 (/Users/hanpeter/lighthouse/lighthouse)`, intermediate artifacts can be found at `/Users/hanpeter/lighthouse/target`

Caused by:
  could not compile `lighthouse`

To learn more, run the command again with --verbose.
make: *** [install] Error 101



## Expected Behaviour
install lighthouse properly


## Steps to resolve
I've tried 'cargo clean' to no success

**Comment by paulhauner** [comment]
Thanks @hanpeternicholas, sorry to hear you're having issues.

I think some additional text from the failure would be useful. Specifically, it would be good to get the error that is being referred to by:

> error: aborting due to previous error

I suspect it would be just above the first line you shared :)

**Comment by michaelsproul** [comment]
`E0275` likely indicates the known issue of Lighthouse v1.4.0 not compiling with Rust 1.53.0: https://github.com/sigp/lighthouse/issues/2420. Please see that issue for instructions on temporarily downgrading the Rust compiler

**Comment by hanpeternicholas** [comment]
Thank you. I downgraded to Rust 1.52.1 and it worked!
