### ISSUE TITLE
upgrade mdbook to latest version

### ISSUE THREAD

**Issue by WALL-E** [sigp/lighthouse#2477]
## Description

The page `https://lighthouse-book.sigmaprime.io/key-recovery.html` , there are some rendering errors

## Present Behaviour

![image](https://user-images.githubusercontent.com/736927/126876687-14bad33c-96cd-43cc-8ddd-ac6a06f629a6.png)

## Expected Behaviour

![image](https://user-images.githubusercontent.com/736927/126876556-a3d6db12-5ad6-4cc4-8150-c488f7ad5d7a.png)

## Steps to resolve

upgrade mdbook to latest version,  I was tested in the *mdbook v0.4.10*, it's ok

**Comment by michaelsproul** [comment]
Thanks for the report! This seems to be fixed now with #2497 merged :tada:
