### ISSUE TITLE
Explicitly Declare Success of Fallback Node

### ISSUE THREAD

**Issue by SeaMonkey82** [sigp/lighthouse#2487]
## Description

When `WARN Error connecting to eth1 node endpoint  action: trying fallbacks` appears in the output, there is no INFO output explicitly stating that connection to the fallback node succeeded.  I think this would be reassuring, as I ended up running a tcpdump on my fallback node just to verify that traffic was hitting it.

## Version

lighthouse v1.4.0-3b600ac (stable)
rustc 1.53.0 (53cb7b09b 2021-06-17)

**Comment by paulhauner** [comment]
Sounds like a good idea!

> there is no INFO output explicitly stating that connection to the fallback node succeeded.

For whoever implements this, I think we should make sure we only log this `INFO` after we log that `WARN` to avoid the case where every HTTP call triggers an INFO log.

**Comment by paulhauner** [comment]
Resolved in #2490
