### ISSUE TITLE
Remote Signer Support

### ISSUE THREAD

**Issue by joe-bowman** [sigp/lighthouse#2498]
## Description

The current release contains a remote signer implementation, and internal libs to consume the remote signer endpoint, however, it appears that the only validator_definition supported is that of LocalKeystore - and that Lighthose cannot currently be configured to consume a Remote signer endpoint.

 ## Version
Lighthouse v1.4.0/stable
Rust v1.5.0

## Present Behaviour

LocalKeystore is hardcoded as the only validator_definition supported

## Expected Behaviour

RemoteKeystore should be configurable from the command line interface

## Steps to resolve

Implement logic integrating remote_signer_consumer and add RemoteSigner validator_definition.

**Comment by paulhauner** [comment]
This is on our radar and is planned for the next major release (announcement here https://lighthouse.sigmaprime.io/update-37.html).

It's a high priority for us, we just didn't have a public issue to track it. I'll leave this open to serve that purpose, thanks.

**Comment by paulhauner** [comment]
This will be addressed in #2522
