### ISSUE TITLE
Add tree hash caching for `inactivity_scores`

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2502]
## Description

To my surprise, I found a `FIXME(altair)` in our tree hashing code that I somehow missed when implementing #2459 :open_mouth:. I must have failed to scroll down after implementing the caching for the participation bits :man_facepalming: 

https://github.com/sigp/lighthouse/blob/ff85b052496860dede3d99b483533f0b4a963ef4/consensus/types/src/beacon_state/tree_hash_cache.rs#L316-L318

## Present Behaviour

On my machine, according to [these benchmarks](https://github.com/michaelsproul/lighthouse/commits/bench-altair-tree-hashing) we're wasting about 10ms hashing the inactivity scores! (with 200K validators)

* **Phase 0**: 13ms
* **Altair** (currently): 27ms
  + Balances: 2ms
  + Participation: 0-1ms
  + Inactivity Scores: 10ms
* **Altair** (ideal): 17ms

The 2ms increase in time required to hash balancess is expected, and was discovered by @dapplion (https://discord.com/channels/595666850260713488/595701173944713277/872768356703432774). It _may_ get optimised out via a spec change.

There's also another 1-2ms unaccounted for. It could be the hashes of the sync committees themselves. These are immutable for long periods, so caching would be super effective, but doing this is less urgent than fixing the `inactivity_scores`.

**Comment by paulhauner** [comment]
I'm working on this now :)

**Comment by paulhauner** [comment]
Resolved via #2504
