### ISSUE TITLE
Produce attestations after new head block

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2503]
## Description

[Attesting]: https://github.com/ethereum/eth2.0-specs/blob/v1.0.1/specs/phase0/validator.md#attesting
[`tokio::select!`]: https://docs.rs/tokio/1.9.0/tokio/macro.select.html

Presently, Lighthouse doesn't exactly follow the [Attesting] section of the honest validator guide. Specifically, we are slack in this section:

> A validator should create and broadcast the attestation to the associated attestation subnet when either (a) the validator has received a valid block from the expected block proposer for the assigned slot or (b) one-third of the slot has transpired (SECONDS_PER_SLOT / 3 seconds after the start of slot) -- whichever comes first.

We always wait for condition (b) and never check for condition (a). I think we should start checking for (a) in the dual interests of consistently following the spec and also because getting our attestations out early *seems* like it will result in better attestation inclusion stats.

For the record, we didn't implement this behaviour initially for the following reasons:

- Lack of streaming events (resolved by SSE events in the standard API)
- Lack of support for queuing attestations for unknown blocks (see #635)

These two points have been resolved and are no longer obstacles.

## Steps to Resolve

Presently, attestation production tasks in the VC are triggered after waiting until 1/3rd of the way through a slot:

https://github.com/sigp/lighthouse/blob/3b600acdc5bf9726367c18277a22486573b8b457/validator_client/src/attestation_service.rs#L142-L167

I propose we instead trigger `AttestationService::spawn_attestation_tasks` when *either* of these two conditions are met:

- It is 1/3rd through the slot (current behaviour).
- We have received a `/eth/v1/events` `head` SSE event where `data.slot == wall_clock_slot`.

This *"whichever comes first"* logic is well suited for [`tokio::select!`].

 I haven't looked deeply, but I *think* this should be a pretty straight-forward change which has little effect on the downstream unagg. and aggregate creation logic.
 
### Complication: Fallbacks

Consider the following setup:

1. A VC which has two BNs (i.e., a primary and one fallback)
1. An implementation where the `/eth/v1/events` subscriptions are created at startup and only re-established if there's a HTTP failure.

Now, imagine that during startup the primary node is unavailable and we happen to subscribe to the fallback. Then, the primary node becomes available.

From this point, we'd now be following the events of the backup whilst attesting with the primary. If the backup gets a block before the primary, then we'll end up creating premature attestations.

One solution might be to create a new subscription at the start of each slot. However, this might not interact so well with  `start_fallback_updater_service`. There might be edge cases there where we subscribe to the fallback, then the fallback-updater-service registers the primary as online, then we use it to create attestations.

Another solution might be to check the head before we create an attestation (only if that attestation was triggered from a head event). If, during that pre-attestation check, the head is inconsistent, wait until the typical 1/3rd through the slot and then attest. This is a bit more cumbersome but feels more consistent.

Further investigation will be required, I'm not yet convinced of the best solution.

**Comment by paulhauner** [comment]
Perhaps this would be interesting for @realbigsean?

**Comment by realbigsean** [comment]
Interested!

**Comment by realbigsean** [comment]
> One solution might be to create a new subscription at the start of each slot. However, this might not interact so well with start_fallback_updater_service. There might be edge cases there where we subscribe to the fallback, then the fallback-updater-service registers the primary as online, then we use it to create attestations.

Could we add to the fallback service, some idea of a "primary candidate" which is the candidate we are going to try first on the next request? Any request failure could update this.  We could maintain/re-establish the event subscription to this node. Might be a way to minimize the odds of having an inconsistency.

> Another solution might be to check the head before we create an attestation (only if that attestation was triggered from a head event). If, during that pre-attestation check, the head is inconsistent, wait until the typical 1/3rd through the slot and then attest. This is a bit more cumbersome but feels more consistent.

I generally like this idea better because even though it's a bit clunkier, I think it could perform better (at the very least seems like it couldn't cause a performance regression) and might actually be simpler to implement because we wouldn't be bogged down by tougher edge cases.

**Comment by realbigsean** [comment]
A Discord user brought up how this could impact certain setups. If someone has load-balancing for validator client requests across beacon nodes that circumvents the `--beacon-nodes` flag, our attempts at mitigating regressions won't have an impact, so I think we will always need a flag to either enable or disable this feature.

**Comment by paulhauner** [comment]
I'm going to close this since I don't see us implementing it anytime soon.
