### ISSUE TITLE
ChainSpec is fixed to foundation.

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#252]
## Description

The [ChainSpec](https://github.com/sigp/lighthouse/blob/master/eth2/types/src/chain_spec.rs) for the validator client is presently fixed to `foundation`.

`foundation` is the specification from the EF that is expected to be used in the production beacon chain.

This is not ideal as it doesn't allow for testnets.

## Steps to resolve

In the long-term, I think it would be best to load the ChainSpec from a local JSON file. However, I don't think this is immediately necessary as it will add overhead (e.g., generating the JSON, shipping it with the repo, updating it as the ChainSpec structure changes, etc).

I think the best approach for now would be to add a CLI flag that permits selection between the presently available `ChainSpec`s: `foundation` and `few_validators`. For example:

`$ lighthouse-validator -s few_validators` or
`$ lighthouse-validator -s foundation`

As we add new definitions to `ChainSpec` we can just manually update the list.

IMO, loading from JSON is a testnet requirement.

**Comment by thojest** [comment]
work started
