### ISSUE TITLE
Further VC Metric - Validator duties

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#2521]
## Description

Other clients expose the time/slot of when a validator needs to make an attestation next. Prysms api provides this information for each validator, indexed by their pubkey. This issue is to add a similar metric to our VC client. 

We could do one of the following:
1. Expose for each validator the slot of their next attestation (and potentially the committee/subnet)
2. A metric that indicates the slot (or wall time) of the earliest attestation of all known validators

I'd be leaning towards doing 1 to make it general. A user has requested we do at least 2, but perhaps we stick with the more general 1. for other potential users.

**Comment by paulhauner** [comment]
If we do (1), we'll have to test to make sure it works OK on our Prater/Pyrmont nodes with thousands of validators. I've had some issues with the validator monitor and thousands of validators before.

It's probably not a big deal and easily fixed somehow, I just wanted to raise it so we don't forget.

**Comment by AgeManning** [comment]
Yeah good point. Potentially we dont want to have a result with 50k values. 

Maybe we should make 1 and 2. This way, the user shouldn't hit 1 if its running many k's of vals and can just use 2. But users have access to 1 on a more realistic node with < 100 vals.

**Comment by AgeManning** [comment]
@pawanjay176 had interest in taking this on.
