### ISSUE TITLE
Fork schedule API not updated for Altair

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2524]
## Description

We accidentally missed updating `/eth/v1/config/fork_schedule` when implementing Altair, which is less than ideal and has broken tools like @mcdee's Vouch.

**Comment by realbigsean** [comment]
I can work on this today

**Comment by paulhauner** [comment]
I've pushed this to `v1.5.1`, since it's not an issue for mainnet.

**Comment by michaelsproul** [comment]
Fixed in `unstable`, will be part of v1.5.1
