### ISSUE TITLE
no matching package named `libp2p` found

### ISSUE THREAD

**Issue by alx** [sigp/lighthouse#2536]
## Description

I'm trying to update to `lighthouse v1.5.0` using `git`, and got the following error with the `make` command:

```
:~/git/lighthouse$ make
cargo install --path lighthouse --force --locked
  Installing lighthouse v1.5.0 (/home/eth/git/lighthouse/lighthouse)
error: no matching package named `libp2p` found
location searched: https://github.com/libp2p/rust-libp2p?rev=ce23cbe76a0382b6fcb0e49f1b2612df86f6465d#ce23cbe7
required by package `eth2_libp2p v0.2.0 (/home/eth/git/lighthouse/beacon_node/eth2_libp2p)`
make: *** [Makefile:23: install] Error 101
```

## Version

`git checkout v1.5.0`

## Present Behaviour

```
make: *** [Makefile:23: install] Error 101
```

## Expected Behaviour

`make` should return a success code.

**Comment by realbigsean** [comment]
I wasn't able to reproduce this. You could try running `cargo clean` from the lighthouse dir and deleting the `~/.cargo/git` and `~/.cargo/registry` directories (these locations could be different depending on your `CARGO_HOME`) in case you have something odd cached.

Also is it possible you had a network issue while buildling? Because the error seems to suggest cargo couldn't find that dependency on github

**Comment by memsido** [comment]
Same issue as OP.

Removed `~/.cargo/git` and `~/.cargo/registry`. Followed by `~/git/lighthouse cargo clean`. The issue still persists.

This is the error upon `make`:
cargo install --path lighthouse --force --locked
  Installing lighthouse v1.5.0 (/home/ethstaker/git/lighthouse/lighthouse)
    Updating crates.io index
    Updating git repository `https://github.com/sigp/milagro_bls`
    Updating git submodule `https://github.com/sigp/incubator-milagro-crypto-rust`
    Updating git repository `https://github.com/libp2p/rust-libp2p`
    Updating git repository `https://github.com/paulhauner/warp`
error: no matching package named `libp2p` found
location searched: https://github.com/libp2p/rust-libp2p?rev=ce23cbe76a0382b6fcb0e49f1b2612df86f6465d#ce23cbe7
required by package `eth2_libp2p v0.2.0 (/home/ethstaker/git/lighthouse/beacon_node/eth2_libp2p)`
make: *** [Makefile:23: install] Error 101

I also tried to remove lighthouse dir and get a new clone. But I am running into the same issue.

**Comment by michaelsproul** [comment]
What Rust version are you running @memsido @alx? I'm pretty sure I've seen this error before, but wasn't able to reproduce with 1.52.1, 1.51.0 or 1.54.0.

You can check with `rustc --version` in the `lighthouse` directory.

You can remove any override with:

```
rustup override unset
rustup update stable
```

**Comment by memsido** [comment]
I think you are onto something @michaelsproul. 

`~/git/lighthouse/rustc --version`  -> 1.50.0

`rustup update stable` updated me to 1.54.0
`make` is happily compiling now. Thank you 🙏

**Comment by alx** [comment]
I can confirm `rust update stable` command solves this issue.

This issue can be closed.

**Comment by michaelsproul** [comment]
Awesome! Hopefully this remains useful to anyone else who stumbles on it
