### ISSUE TITLE
Implement attester service

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#255]
## Description

The [`attester`](https://github.com/sigp/lighthouse/tree/master/eth2/attester) logic is not yet implemented in the validator client (however it does run in tests and simulations).

## Steps to resolve

- Implement the `attester` crate in a similar fashion to the `block_proposer` crate.

**Comment by thojest** [comment]
work started

**Comment by AgeManning** [comment]
This is resolved in #334
