### ISSUE TITLE
`libp2p` error while compiling - update compiler

### ISSUE THREAD

**Issue by bk-one** [sigp/lighthouse#2550]
## Description

I compile lighthouse manually, this worked until the 1.5 release for me (also won't work on 1.5.1). It complains about a missing libp2p package, even though the remote git is set.

```
benjamin@Node3:~/lighthouse$ git status
On branch stable
Your branch is up to date with 'origin/stable'.

benjamin@Node3:~/lighthouse$ cargo update
    Updating crates.io index
    Updating git repository `https://github.com/sigp/milagro_bls`
    Updating git repository `https://github.com/libp2p/rust-libp2p`
    Updating git repository `https://github.com/paulhauner/warp`
error: no matching package named `libp2p` found
location searched: https://github.com/libp2p/rust-libp2p?rev=ce23cbe76a0382b6fcb0e49f1b2612df86f6465d
required by package `eth2_libp2p v0.2.0 (/var/lighthouse/beacon_node/eth2_libp2p)`

benjamin@Node3:~/lighthouse$ make
cargo install --path lighthouse --force --locked
  Installing lighthouse v1.5.1 (/var/lighthouse/lighthouse)
error: no matching package named `libp2p` found
```

**Comment by bk-one** [comment]
I fixed the issue by updating rust to the latest version:

```
benjamin@Node3:~/lighthouse$ rustup update
```

Just leaving this here in case someone else encounters that problem. No action necessary.

**Comment by michaelsproul** [comment]
Thanks @bk-one. We've seen a few people stumble on this, so I'll leave this issue open and pin it for a while to give it better visibility (#2536 is a dupe, but is already closed).

**Comment by michaelsproul** [comment]
Closing this now, as we've had a release (v1.5.2) since then and most people seem to have updated
