### ISSUE TITLE
libp2p Peers per Client is Negative

### ISSUE THREAD

**Issue by JP-Ellis** [sigp/lighthouse#2553]
## Description

I have noticed that since version 1.5.0 (I believe) the metric `libp2p_peers_per_client` reports negative numbers which I find very odd.  They also don't add up to `libp2p_peer_connected_peers_total`.

![image](https://user-images.githubusercontent.com/3196162/131267862-b266e0ef-e442-4b8d-9fbe-08f04b12a450.png)

## Version

```
❯ lighthouse --version
Lighthouse v1.5.1-b0ac346
BLS library: blst-modern
SHA256 hardware acceleration: false
Specs: mainnet (true), minimal (false)
```

## Expected Behaviour

The `libp2p_peers_per_client` should be greater than 0 and the total should be equal to `libp2p_peer_connected_peers_total`.

**Comment by paulhauner** [comment]
Thanks @JP-Ellis, this is a bug and we'll fix it.

**Comment by AgeManning** [comment]
This looks like an oversight in the restructuring of the network behaviour. I'll add the fix in my current run of updating metrics.

**Comment by michaelsproul** [comment]
We haven't seen this since #2549 was merged, so I think it's fixed
