### ISSUE TITLE
LCLI docker push access denied 

### ISSUE THREAD

**Issue by BeroBurny** [sigp/lighthouse#2554]
## Description

after building `lcli` image its failed to push on docker hub

## Present Behaviour

there is no `lcli` image on the docker hub
https://github.com/sigp/lighthouse/runs/3439538667?check_suite_focus=true

(there is a known issue from a month still not resolved https://github.com/sigp/lighthouse/pull/2469#issuecomment-884186076)

## Expected Behaviour

able to use `lcli` docker image from docker hub

## Steps to resolve

add permissions for pushing image and re-run all failed pushes

**Comment by paulhauner** [comment]
Sorry for the delay, I've manually pushed the image and created the repo (using 5a3bcd290):

https://hub.docker.com/r/sigp/lcli

We can leave this open until we see CI update it successfully.

**Comment by michaelsproul** [comment]
It seems it's still broken https://github.com/sigp/lighthouse/runs/3502705442

**Comment by paulhauner** [comment]
Oh, bummer. I modified the permissions of the lcli dockerhub repo. Hopefully that works :crossed_fingers:

**Comment by BeroBurny** [comment]
> Oh, bummer. I modified the permissions of the lcli dockerhub repo. Hopefully that works

seems still is a issue :see_no_evil: 
https://github.com/sigp/lighthouse/runs/3539814672?check_suite_focus=true

**Comment by michaelsproul** [comment]
Looks like it just needed a new commit to `unstable`, working now :tada: https://github.com/sigp/lighthouse/runs/3577392749
