### ISSUE TITLE
Load genesis_time from the beacon node.

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#256]
## Description

`genesis_time` is required to determine the present slot.

Presently, the val client assumes that the `genesis_time` is known, this will not be the case whilst we're waiting for the deposit contract to fill up and emit a chain-start event.

## Steps to resolve

- Implement some service that can poll the beacon node and determine (a) if a `genesis_time` exists and (b) what it is.

**Comment by AgeManning** [comment]
I'm considering a service which is akin to an `info()`. This requests basic information from the beacon node, to initiate the validator client. Information would include, 
```
version, // beacon node version 
chain_id / network_id, 
genesis_time, // possibly genesis_hash also, as we could hard-code known hashes for chains in the future for added security.
... // maybe other things (no of peers maybe, validators might want to choose different nodes..)
```

**Comment by spble** [comment]
I think this is a good idea, and should also possibly include a `syncing` status, or `currentBlockNumber` and `highestBlockNumber` (to infer if it's syncing)

**Comment by paulhauner** [comment]
Yep, agreed. Including the `fork` info in there would be relevant. It's the BLS signature equivalent of `network_id`.
