### ISSUE TITLE
Add syncing ETA in Beacon Node API response

### ISSUE THREAD

**Issue by remyroy** [sigp/lighthouse#2564]
## Description

It would be nice to add syncing time ETA in Beacon Node API response. That value is present in the logs, but it would be nice to make it visible in the API. This is related to https://github.com/ethereum/beacon-APIs/issues/166 .

## Version

Lighthouse/v1.5.1-b0ac346/x86_64-linux

## Present Behaviour

The `/eth/v1/node/syncing` API does not expose syncing time ETA in the response.

## Expected Behaviour

A field exposing syncing time ETA is present in the `/eth/v1/node/syncing` API endpoint response when the beacon node is syncing.

## Steps to resolve

A new field is added in the `/eth/v1/node/syncing` API endpoint to include syncing time ETA when the beacon node is syncing.

**Comment by paulhauner** [comment]
Considering that `/eth/v1/node/syncing` is a standard API, we (Lighthouse) don't really have the ability to do anything until https://github.com/ethereum/beacon-APIs/issues/166 is actioned.

@remyroy what are your thoughts on closing this issue and using the beacon-APIs repo as the forum to get this change through to the standard API? Once the standard API updates we can re-open this issue.

**Comment by remyroy** [comment]
Sure, we can close and focus on the standard API.
