### ISSUE TITLE
How reduce ligthhouse bandwich

### ISSUE THREAD

**Issue by Bombommi** [sigp/lighthouse#2567]
v1.5.1-b0ac346
Building from sources
Use BN+VC in one machine (Ubuntu 20.04)
ETH 1.0 in another one

How i can reduce ligthhouse bandwich? 
Version start from v1.4.0 starting eat to much upload bandwich.
With same configs
v1.5.1 right now eat ~1mb/s
v1.3.0 it only 100-150KB/s 

If i  try to reduce target-peers low that 15
`WARN Could not publish message               error: InsufficientPeers, service: libp2p`

Can help someone to reduce ligthhouse bandwich?
Thank you.

**Comment by AgeManning** [comment]
I am currently working on this. I will link a PR where you can follow updates and run experimental code if you are interested.

**Comment by AgeManning** [comment]
Are you running on a testnet or mainnet?

**Comment by michaelsproul** [comment]
Closing as overly broad. Our bandwidth is mostly a function of the spec, and there is work being done on that in other repos
