### ISSUE TITLE
Signature domains are not generated correctly

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#257]
## Description

The validator client is presently using dummy values for the `domain` parameter required for BLS signatures.

Determining this value requires knowledge of the current [`Fork`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#fork) struct for the present `BeaconState`. See ['get_domain'](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#get_domain) for more info on domain generation.

Currently, the val client has no way of reading this info from the beacon node. We should provide the capability from the `BeaconNode` traits in the val client, and eventually add the functionality to the GRPC interface.

## Expected Behaviour

- Allow for the val client to pull the required fork data from the beacon node.
- Ensure all signatures in the val client use this fork data.

## Additional Info

We could consider two different methods for the validator to get this info:

1. Request the `domain` from the beacon node (for some supplied `epoch` and `domain_type`).
2. Request the `Fork` info form the beacon node and generate the domain locally.

I'm leaning towards (1) at the moment, as it keeps more logic in the beacon node. Open to alternative suggestions.

**Comment by AgeManning** [comment]
What if we modified, `produce_beacon_block()` on the `BeaconNode` to return a tuple `(block, domain)`. 
On a quick glance, it seems to only be used in `BlockProposer` when signing blocks.

**Comment by paulhauner** [comment]
@AgeManning I'm guessing this has been rectified?

**Comment by paulhauner** [comment]
Resolved at some point in the past
