### ISSUE TITLE
Fork name decoding should be case insensitive

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2583]
## Description

I just checked in on my little Teku-Lighthouse Pyrmont validator for the first time in a while and found that it had failed to produce a few blocks with:

```
Sep 04 14:31:31.686 CRIT Error whilst producing block            message: All endpoints failed https://eth2-beacon-pyrmont.infura.io/ => RequestFailed("Error from beacon node when producing block: Reqwest(reqwest::Error { kind: Decode, source: Error(\"Invalid fork name: ALTAIR\", line: 1, column: 19) })"), service: block
```

Specifically Teku BNs uppercase the fork name:

```
Invalid fork name: ALTAIR
```

This should be a one-line fix, a simple `fork_name.lower()` here:

https://github.com/sigp/lighthouse/blob/b0ac3464ca5fb1e9d75060b56c83bfaf990a3d25/consensus/types/src/fork_name.rs#L61-L65

Plus a test.

**Comment by mstallmo** [comment]
Sorry I forgot to include the `Resolves/Closes` keyword in my PR so this issue will have to be closed manually! 😅
