### ISSUE TITLE
Add regression tests for `boot_node`

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2602]
## Description

There are regression tests for the CLI flags for the `beacon_node`, `validator_client` and `account_manager` but none for `boot_node`. The `boot_node` is mostly used internally, and for testnets, but it would still be nice to have its CLI interface protected from regression.

## Steps to resolve

The CLI regression tests are here https://github.com/sigp/lighthouse/tree/stable/lighthouse/tests

We would need to add a new submodule called `boot_node`, drawing inspiration from the existing modules (bonus points: factor out a common `CommandLineTest` struct). The `boot_node` command itself would need to be extended with `immediate-shutdown` and `dump-config` flags similar to the others, e.g. 

https://github.com/sigp/lighthouse/blob/f9bba92db3468321b28ddd9010e26b359f88bafe/lighthouse/src/main.rs#L338-L345

The main difficulty will be that the bootnode currently doesn't use the `TaskExecutor`, so it doesn't have a shutdown sender, and it doesn't expose its config before `::run` is called. We would have to refactor it to be more like the other tasks, _or_ more simply, push the config dumping down into `boot_node::run`.

**Comment by ackintosh** [comment]
This issue have been resolved via #2749 and #2887. 👍
