### ISSUE TITLE
Check proposer index when producing a block

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2612]
## Description

It came to my attention that it's possible for the VC to publish a block with an invalid signature. Here's the flow:

1. VC gets proposer duties from the BN
1. BN re-orgs
1. VC requests block from the BN, signs it and returns it.
1. BN publishes it, then verifies it and realises that the block is signed by the wrong validator index.

## Solutions

There are two checks we can implement to prevent this:

1. Verify the `randao_reveal` in the BN when [producing a block](https://github.com/sigp/lighthouse/blob/f9bba92db3468321b28ddd9010e26b359f88bafe/beacon_node/beacon_chain/src/beacon_chain.rs#L2604-L2623). Presently we verify the block [without checking signatures](https://github.com/sigp/lighthouse/blob/f9bba92db3468321b28ddd9010e26b359f88bafe/beacon_node/beacon_chain/src/beacon_chain.rs#L2782) to speed up block publishing times. If we checked the `randao_reveal` we'd notice that it was signed by the wrong proposer.
1. In the VC, after we [get the block from the BN](https://github.com/sigp/lighthouse/blob/f9bba92db3468321b28ddd9010e26b359f88bafe/validator_client/src/block_service.rs#L269-L273), check that the proposer index matches our request.

(2) is trivial to implement in terms of runtime cost. (1) is less trivial, but that signature verification should take only a few ms so I think it's worth it.

**Comment by pawanjay176** [comment]
@paulhauner Are you saying we need to implement both the checks? Just one of them should do right?

Also, I assume the correct duty is sent to proposer_duties in case of a re-org and that's why it's safe to just reject the bad block without doing anything else?

**Comment by paulhauner** [comment]
> Are you saying we need to implement both the checks? Just one of them should do right?

It might be worth doing both, then we protect both the VC and BN as separate pieces of software.

> Also, I assume the correct duty is sent to proposer_duties in case of a re-org and that's why it's safe to just reject the bad block without doing anything else?

Yep, that's right. We assume that if the re-org means another block should be produced soon (unlikely), then we'll do that.
