### ISSUE TITLE
/eth/v1/validator/contribution_and_proofs rejecting input

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#2639]
## Description

/eth/v1/validator/contribution_and_proofs is rejecting an input which I believe is valid.

## Version

1.5.2

## Present Behaviour

Attempting to send a contribution and proof body, for example:

```
[
  {
    "message": {
      "aggregator_index": "231020",
      "contribution": {
        "slot": "1354636",
        "beacon_block_root": "0x89fe35ad3aad99fdb96d48d06ca33d515443277278afd7c7388f43945e52703d",
        "subcommittee_index": "2",
        "aggregation_bits": "0xfeffffafe7ffffb7dfffbf7fffffffff",
        "signature": "0x8fef3be0d0f56d5ac375eeb227b92b77816df13e2098ec4d4e9e771e9edae7757ffd1e024a5a0bb2e128cb9b2a9ae989071f0a16786a430bef2e7949c529b197e20ce0475f97021b08bb15e14aa882fa12bed1cfac78c66d3f5b7c272749f058"
      },
      "selection_proof": "0x950949aca6637d79d4e9e6544c7e1df3f3c128eef6674c0c8a6742680f5ba713579f7f29809ee0aefe9089da1349f4e315ccdfa89a47be6a86d4a03fe6b08ff7c8ee2ebce79f9cf907538af78b8407e001595e4b464935f26f60c297c1b60c95"
    },
    "signature": "0xaec70ea3927fb9afc87c77c3692b81ce41241c17f7839a7141fb3b8596accdc5c0e00b54e69b596c439bb00195006a2f0b77bbe34f456a5c763912360c16aa2194528e58dc5228704afae95cd0a63ae5e44edb997e22caf20bb739f55765c2a9"
  }
]
```

returns an error:

```
{
  "code": 400,
  "message": "BAD_REQUEST: error processing contribution and proofs",
  "failures": [
    {
      "index": 0,
      "message": "Verification: InvalidSignature"
    }
  ]
}
```

## Expected Behaviour

As far as I can tell, the contribution is valid and should be accepted.

## Steps to resolve

Unknown.  There is nothing in the lighthouse log that suggests why the signature is invalid, and local testing suggests that it is good (although it's all coming from the same codebase so a bad assumption could be carried across both the initial work and the testing):

```
Valid data structure: ✓
Validator known: ✓
Validator in sync committee: ✓
Validator is aggregator: ✓
Signature has valid format: ✓
Signature is valid: ✓
```

**Comment by mcdee** [comment]
After more investigation I believe that another client may be returning a bad contribution.  Is it possible for the error message returned to be more explicit over which signature is failing verification?

**Comment by paulhauner** [comment]
> After more investigation I believe that another client may be returning a bad contribution. Is it possible for the error message returned to be more explicit over which signature is failing verification?

Unfortunately not, it verifies them in a batch so we have no indication as to which signature is invalid.

**Comment by mcdee** [comment]
Sorry, that was unclear of my.  I meant the two separate signatures within the structure, the one within `contribution`and the one at the top level f the JSON, as opposed to the signatures that make up the contribution signature.  Or do you batch verify those two as well?

**Comment by michaelsproul** [comment]
> Or do you batch verify those two as well?

We verify them all in one batch. I have commented out the sig sets one by one during debugging, you could try that if you want to isolate which signature is invalid in this specific instance (not sure if that's valuable info, I can do it for you if it would be):

https://github.com/sigp/lighthouse/blob/f9bba92db3468321b28ddd9010e26b359f88bafe/beacon_node/beacon_chain/src/sync_committee_verification.rs#L582-L618

**Comment by mcdee** [comment]
This is due to another client generating a bad contribution.  Lighthouse is correctly rejecting it, so closing this issue.  Thanks.
