### ISSUE TITLE
Implement "interop" standard metrics

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2644]
## Description

There is a list of standard metrics here which should be implemented by all consensus clients:

https://github.com/ethereum/beacon-metrics/blob/master/metrics.md#interop-metrics

We do not implement any of these metrics, and we're currently behind the other teams:

![interop-metrics](https://user-images.githubusercontent.com/6660660/135064292-814aa51a-77bf-4c4e-8555-efbbc2d7ebc6.png)

## Steps to Resolve

I believe we already support all of these metrics and export them under different names.

I propose that we implement all the "Interop Metrics" as separate values, retaining our existing ones. At some point in the future we could consider deprecating the duplicates, but they're of very low cost for the time being.

**Comment by michaelsproul** [comment]
Fixed in #2645
