### ISSUE TITLE
lighthouse using yanked zeroize_derive v1.1.0

### ISSUE THREAD

**Issue by newearthmartin** [sigp/lighthouse#2655]
## Description
When running make, a warning shows up that the package `zeroize_derive` is yanked. I'm not familiar with Rust but it seems that yanked packages should not be used. https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-yank . There is a 1.2.0 version available for this package.

```
$ make
cargo install --path lighthouse --force --locked
  Installing lighthouse v1.5.2 (/home/martin/opt/lighthouse/lighthouse)
    Updating crates.io index
warning: package `zeroize_derive v1.1.0` in Cargo.lock is yanked in registry `crates.io`, consider running without --locked
    Finished release [optimized] target(s) in 6.59s
   Replacing /home/martin/.cargo/bin/lighthouse
    Replaced package `lighthouse v1.5.2 (/home/martin/opt/lighthouse/lighthouse)` with `lighthouse v1.5.2 (/home/martin/opt/lighthouse/lighthouse)` (executable `lighthouse`)

```
## Version

stable v1.5.2 f9bba92db3468321b28ddd9010e26b359f88bafe

**Comment by michaelsproul** [comment]
Thanks for reporting! We have a new release candidate coming out in <12h which updates that dependency. All being well it will become a full release next week
