### ISSUE TITLE
Auto-generate CLI documentation for Lighthouse book

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2679]
## Description

It would be nice to have an online reference for `lighthouse --help`, `lighthouse bn --help`, etc. This has been discussed before, but nobody has yet had time to implement it.

There are two ways I can think of implementing it currently:

1. A basic version could be put together by collecting the output of `lighthouse --help` and putting it into a `<code>` block in some HTML. This would be a bit unsightly
2. We could update our CLI parsing library `clap` to v3, which includes a crate for writing custom generators: https://docs.rs/clap_generate/3.0.0-beta.4/clap_generate/index.html. This would be a bit more work, but we could iterate the subcommands and flags for Lighthouse programmatically and write them out in nicely formatted HTML.

## Version

Lighthouse v2.0.0

**Comment by paulhauner** [comment]
This is potentially a duplicate of #1876.

**Comment by michaelsproul** [comment]
Ah yes! I went looking but didn't find that, will close
