### ISSUE TITLE
Create optimised lmd-ghost fork choice from bitwise-lmd-ghost

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#269]
## Description

Currently we have bitwise_lmd_ghost which as an optimised fork choice rule. This will be useful in phase 1 of the spec. Currently we require an optimised version of lmd-ghost for phase 0. This can be easily created from bitwise-lmd-ghost by modifying the `choose_best_child` function: https://github.com/sigp/lighthouse/blob/8671c5790c453a9a945469baa4f15c4a8157956b/eth2/fork_choice/src/bitwise_lmd_ghost.rs#L206 
to simply select the child that has the most votes, rather than performing the search over the binary hash. 

This new fork-choice should be created as  a new algorithm in the `ForkChoiceAlgorithms` enum. 

If you are interested in taking up this issue, hit up @AgeManning on gitter for more detailed info :).

**Comment by 192-sean** [comment]
im interestd in taking on this issue.

**Comment by AgeManning** [comment]
Hey @192-sean. Currently I think @pawanjay176 had started this issue. 

However there is a more advanced fork-choice project I could help you with, if you are interested.

**Comment by 192-sean** [comment]
Alright sounds good

**Comment by AgeManning** [comment]
@192-sean - See #296 :). 

If you think it may be too difficult, I can find something else :).

**Comment by AgeManning** [comment]
Closed in #297
