### ISSUE TITLE
Inbound Stream Termination Edge Case

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#2701]
## Description

I saw some inbound stream timeouts. I'm suss on them because they seem to be resolved, but not registered in the handler. I saw these logs:
```
Oct 11 14:25:18.359 DEBG Received BlocksByRange Request          step: 1, start_slot: 2156384, count: 64, peer_id: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ
Oct 11 14:25:18.359 DEBG Received BlocksByRange Request          step: 1, start_slot: 2156704, count: 64, peer_id: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ
Oct 11 14:25:18.360 DEBG Received BlocksByRange Request          step: 1, start_slot: 2156768, count: 64, peer_id: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ
Oct 11 14:25:18.599 DEBG BlocksByRange Response sent             returned: 64, requested: 64, current_slot: 2258224, start_slot: 2156384, peer: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ
Oct 11 14:25:18.609 DEBG BlocksByRange Response sent             returned: 63, requested: 64, current_slot: 2258224, start_slot: 2156704, msg: Failed to return all requested blocks, peer: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ
Oct 11 14:25:18.610 DEBG BlocksByRange Response sent             returned: 62, requested: 64, current_slot: 2258224, start_slot: 2156768, msg: Failed to return all requested blocks, peer: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ
Oct 11 14:25:18.670 DEBG Received BlocksByRange Request          step: 1, start_slot: 2156832, count: 64, peer_id: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ
Oct 11 14:25:18.937 DEBG BlocksByRange Response sent             returned: 64, requested: 64, current_slot: 2258224, start_slot: 2156832, peer: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ
Oct 11 14:25:29.054 DEBG RPC Error                               direction: Incoming, score: 0, peer_id: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ, client: Prysm: version: 29d48dfe7eb38959752048aec700f31c3abf7484, os_version: unknown, err: Stream Timeout, protocol: beacon_blocks_by_range, service: libp2p
Oct 11 14:25:29.054 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Oct 11 14:25:30.690 DEBG RPC Error                               direction: Incoming, score: 0, peer_id: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ, client: Prysm: version: 29d48dfe7eb38959752048aec700f31c3abf7484, os_version: unknown, err: Stream Timeout, protocol: beacon_blocks_by_range, service: libp2p
Oct 11 14:25:30.691 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
Oct 11 14:25:30.691 DEBG RPC Error                               direction: Incoming, score: 0, peer_id: 16Uiu2HAmHJt8Hsqd8oJZkiz9i3Thiy8V7D7g9LDoqGvEmhCPnBTZ, client: Prysm: version: 29d48dfe7eb38959752048aec700f31c3abf7484, os_version: unknown, err: Stream Timeout, protocol: beacon_blocks_by_range, service: libp2p
Oct 11 14:25:30.691 WARN Timed out to a peer's request. Likely too many resources, reduce peer count, service: libp2p
```

These were the only BBRange requests and they get answered very shortly after. The worker seems to be sending the stream termination to the network task. I doubt the network task is halted for 10 seconds, so I would assume the stream termination makes it into the RPC Handler. 

Now the question is why is the RPC Handler not removing the inbound stream from the delay queue?

I had a quick look through the handler and didn't see anything off. It looks like for stream terminations we start attempting to close the substream and once the substream is closed we remove it from the delay queue. Potentially there is some hold up in closing the stream, but I think also maybe we are missing some edge case where potentially the stream gets closed before we attemtp to close it or some race condition that leads us to not remove the substream from the delay queue. 

I think it requires some investigation.

**Comment by AgeManning** [comment]
I've seen this with a different node also, and it also seems to be from a BlocksByRange request, which is a bit suss. 

The handler doesn't really distinguish between different RPCMethods, so this could just be a coincidence. I doesn't seem like we are locking on the db, because the logs indicate the worker completes the request. 

This might have something to do with expected chunks remaining in the handler?

**Comment by divagant-martian** [comment]
I think it might have to do with how the handler is polled. My hypothesis would be that when a response is received for an outbound request, the swarm polls the handler and this is processed immediately. When the handler gets a (lh) event injected it gets polled but if we need to queue items, those would be sent until the next poll. I'll check how to (dis)prove this. If this is it then the solution is probably to store a waker.
This would explain why it's only happening with inbound requests for which `remaining_chunks > 1`

---------------

Did some tests with enough load to force the handler to queue chunks (Sometimes as many as a complete batch - 64) and can't make it timeout, so maybe it's something else.
