### ISSUE TITLE
How to reenter after voluntary exit, and eventually withdraw

### ISSUE THREAD

**Issue by ethcurious** [sigp/lighthouse#2705]
First of all, thank you for building this great tool.

A couple of things aren't clear to me from the (otherwise excellent) documentation:
1. Is it possible to do a voluntary exit then reactivate the validator (ie, if i know my node needs to go offline for a few days)?
2. After the merge, how can we use a BLS withdrawal keypair to withdraw staked eth?

Staking is a big commitment and I'd feel much more comfortable diving in if I saw some public documentation (either lighthouse-specific, or general) that clarifies those two issues, but I can't find any.

**Comment by michaelsproul** [comment]
> Is it possible to do a voluntary exit then reactivate the validator (ie, if i know my node needs to go offline for a few days)?

Voluntary exits are permanent. If you want to go offline for a few days you can either soak up the penalty or use a fallback node. For short periods of time the losses from being offline should approximately equal the rewards from being online, so being offline for 2 days can be cancelled out by being online again for 2 days.

> After the merge, how can we use a BLS withdrawal keypair to withdraw staked eth?

This hasn't been specified exactly yet, and won't be included in the merge hard fork. It will likely be some variant of signing an Eth1 (160-byte) address with your BLS withdrawal key, and then withdrawing the funds to the execution layer. We expect that this will ship in the fork following the merge (i.e. mid-late 2022).

> Staking is a big commitment and I'd feel much more comfortable diving in if I saw some public documentation (either lighthouse-specific, or general) that clarifies those two issues, but I can't find any.

Fair point. I guess you saw the page on [Voluntary Exits](https://lighthouse-book.sigmaprime.io/voluntary-exit.html), I agree it could do with some clarification that exits are irreversible, other than in the CLI message.

[The Launchpad](https://launchpad.ethereum.org/) includes a better message on step 7 of the first page:

![launchpad](https://user-images.githubusercontent.com/4452260/137027477-22bc75db-3a55-4c7d-82ba-f22dd34b8abb.png)

**Comment by ethcurious** [comment]
Thanks for the quick reply. I guess uncertainty comes with the territory.
I thought of one more question:
What's the recommended workflow to upgrade Lighthouse if a hardfork is imminent? For example, do stable clients released near-ish to hardforks have the post-hardfork protocol updates already written in, but dormant until the client detects (based on blocknumber/epoch) the fork has been reached, at which point the client starts using the updated protocols and follows the right fork automatically? If that's how the client works, as long as I'm careful to update it before each fork, I should be ok. If that's NOT how it works, I'm not sure what I should do.

**Comment by ethcurious** [comment]
Thanks for the quick response! I guess uncertainty is the nature of this beast. I thought of one more question, but I'll put that in a separate issue for better visibility.
