### ISSUE TITLE
How to obtain next sync period's members?

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#2770]
## Description

The API does not return information for the next sync period's members when requested.

## Version

2.0.1

## Present Behaviour

There appears to be a relatively low maximum lookahead for blocks, so for example if `head` is at 2425664 then the following occurs:

```
$ curl -H 'Accept: application/json' http://localhost:15200/eth/v1/beacon/states/2433024/sync_committees
{"code":404,"message":"NOT_FOUND: beacon state at slot 2433024","stacktraces":[]}
```

## Expected Behaviour

Ideally the lookahead should be a full sync committee period, so that sync committee information can be retrieved for period _n_ at any time whilst in period _n-1_.

**Comment by michaelsproul** [comment]
You have to pass the `epoch` query parameter, which can be any epoch from the current or next period of the respective state

**Comment by michaelsproul** [comment]
https://gist.github.com/michaelsproul/17d1653ace9bd40b7b684a1d7c2a379d

**Comment by mcdee** [comment]
Yeah, given I wrote that API I should have remembered how to use it.  Apologies for wasting your time.

**Comment by michaelsproul** [comment]
No worries haha, happens to all of us from time 😅
