### ISSUE TITLE
Simulator Irregularities

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#2775]
## Description

I ran the eth1-simulator and saw a bunch of things that don't seem right, which probably warrants some investigation.

Running locally I see
```
Nov 04 15:26:07.003 ERRO No valid eth1_data votes, `votes_to_consider` empty, outcome: casting `state.eth1_data` as eth1 vote, genesis_time: 1635999745, earliest_block_timestamp: 1635999579, lowest_block_number: 0, service: beacon, service: boot_node
```

And also:

```
Nov 04 15:26:07.004 WARN Offline beacon node                     endpoint: http://127.0.0.1:42423/, error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(42423), path: "/eth/v1/node/version", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }), service: validator_0
```

for validator_0 and validator_1

Could be related to that fact that for all nodes, we have this:
```
Nov 04 15:26:28.002 WARN Syncing eth1 block cache                est_blocks_remaining: 32, service: slot_notifier, service: node_1
```

This could likely be superficial. It might be nice to modify the sim to handle these

**Comment by AgeManning** [comment]
I guess while someone is in there, it would be nice to reduce the target--peer count to the number of simulated nodes and also remove discovery's packet filtering (if we're currently doing that).

**Comment by divagant-martian** [comment]
Disabling discovery and setting the explicit nodes could work too to reduce the noise

**Comment by pawanjay176** [comment]
The `Offline beacon node` warn is expected as we are testing the eth1 fallback logic by providing a non-existent http endpoint on port 42423. 

The others are concerning, seems like some unexpected eth1 block times is throwing off the candidate blocks calculation. Looking into it.
