### ISSUE TITLE
Events API beacon spec inconsistency

### ISSUE THREAD

**Issue by mempirate** [sigp/lighthouse#2812]
## Description
There is a bug in the events API, specifically when subscribing to multiple events. The [Beacon-API spec](https://ethereum.github.io/beacon-APIs/#/Events/eventstream) specifies that the URL for subscribing to multiple events should be in the form of `/eth/v1/events?topics=<topic1>&topics=<topic2>`. This is currently not the case.

## Version
`Lighthouse/v2.0.1-fff01b2/x86_64-linux`

## Present Behaviour
If we want to subsribe to both `block` and `finalized_checkpoint` subscriptions, the API only works with the following request: `/eth/v1/events?topics=block,finalized_checkpoint`. This does not conform to the spec.

## Expected Behaviour
According to the beacon spec, the URL should be the following: `/eth/v1/events?topics=block&topics=finalized_checkpoint`.

**Comment by michaelsproul** [comment]
Thanks for the report!

We should confirm that any fix for https://github.com/sigp/lighthouse/issues/2739 fixes this too 👍
