### ISSUE TITLE
Incorect value of validator_monitor_prev_epoch_attestation_block_inclusions metric when validator is off

### ISSUE THREAD

**Issue by selfuryon** [sigp/lighthouse#2820]
## Description

Hello! I am faced with an issue: I turn off one of my validators but `validator_monitor_prev_epoch_attestation_block_inclusions` still shows `1` value which means what beacon node see attestation from my validator in new blocks.
![image](https://user-images.githubusercontent.com/2993917/142390693-cc28e301-3e7d-4f34-a584-cd7515e5a6a9.png)
![image](https://user-images.githubusercontent.com/2993917/142390905-c07e1018-04d8-47be-9cc4-56e81f6f4512.png)

## Version

Docker image: sigp/lighthouse:v2.0.1 

## Present Behaviour

This metric always shows `1` despite the validator is not working.

## Expected Behaviour

This metric should show `0`

## Steps to resolve

Turn off validator and after that check that metric in beacon node

**Comment by selfuryon** [comment]
In the same time `validator_monitor_attestation_in_block_total` counter shows that we didn't see any attestation in a new block via gossip:
![image](https://user-images.githubusercontent.com/2993917/142394117-117a64f8-d618-45a1-b0d1-aece181f6a0f.png)

**Comment by macladson** [comment]
Fixed in #2911
