### ISSUE TITLE
Proposer boosting in fork choice

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2838]
## Description

Tracking issue for the implementation of proposer boosting in fork choice: https://github.com/ethereum/consensus-specs/pull/2730

## Current Status

I've started on an implementation here: https://github.com/michaelsproul/lighthouse/commit/2aca02a9a8c08910247ee64a368277928a38531c

I think the best way to capture the sub-slot timing is to pass the `block_delay` in as a `Duration` to `on_block`. I experimented with making the fork choice store aware of `Duration`s rather than slots, but it got quite messy, and the fork choice store ended up requiring a copy of the slot clock. That approach is in this commit if we wish to revive it: https://github.com/michaelsproul/lighthouse/commit/000ca67bb5b8cf9d9b317b8e038864c05f2207b0.

### Apply boost weight

The major TODO is implementing the proposer boost's influence on fork choice via the proto array.

I'm not super familiar with the Proto fork choice internals, but I think we could implement the boost in `ProtoArrayForkChoice::find_head`, by adding it (or subtracting it) as a delta before calling `apply_score_changes`.

----

Initially I thought something like this would work:

* Keep track of the `proposer_boost_root` and its associated weight in the `ProtoArray`. I.e. a field like `proposer_boost: (Hash256, u64)`.
* When `on_block` is called with a new boosted block, compute the boost weight and _add_ it to the boosted block's `ProtoNode.weight`.
* When `on_block` is called with _any block_, invalidate any previous boost by looking up the node corresponding to the previous value of `ProtoArray.proposer_boost` and _subtracting_ the boost.

 However I'm not sure if changes to the child weights would be correctly applied when the boost is removed, which is why I'm leaning towards the `compute_deltas`/`apply_score_changes` approach.
 
 ### Optional boosting
 
 Ideally we can turn proposer boosting off in the CLI
 
 ### Migrations
 
 I've left a `FIXME(boost)` about migrating the fork choice store to contain the `proposer_boost_root`. It could be added as part of the same migration from https://github.com/sigp/lighthouse/pull/2822, or a separate one (I think I prefer the same migration).

**Comment by realbigsean** [comment]
Since the `proposer_boost_root` is tracked in the `store`, I think we'll need to pass it into the `find_head` method, similar to how we pass in information about the justified and finalized checkpoints. Otherwise we don't easily have a means of updating `ProtoArray` from the `on_tick` method. Then a route we could go is storing a `previous_proposer_boost: (Hash256, u64)` in the `ProtoArray` and on every call to `find_head` use the previous proposer boost to create a negative delta and calculate the current proposer boost and apply it as a positive delta. Then update `previous_proposer_boost` with the freshly calculated one.

**Comment by michaelsproul** [comment]
> Otherwise we don't easily have a means of updating ProtoArray from the on_tick method. 

Ah of course, we need to make sure that the boost is removed if there's a skipped slot immediately after a boosted block.

I think storing the `previous_proposer_boost` in `ProtoArray` and then subtracting it from `find_head` sounds good :+1:

**Comment by realbigsean** [comment]
> I experimented with making the fork choice store aware of Durations rather than slots, but it got quite messy, and the fork choice store ended up requiring a copy of the slot clock. That approach is in this commit if we wish to revive it: michaelsproul@000ca67.

Seems like this might make integrating the EF tests easier, so I might try to revive it

Edit: Nevermind, don't think it's necessary

**Comment by michaelsproul** [comment]
Closed by #2822 :tada:
