### ISSUE TITLE
[VC] Allow correcting keystore password via re-import

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2854]
## Description

@LefterisJP writes:

> I imported a validator and made a mistake somehow and the password was wrong and it was ignored. When opening lighthouse vc it exited with a warning that password was missing for that validator. When I tried to reimport (from the directory) and successfully entered the password the validator was not imported. It says skipped 1 validator.
The only way to input the password was to manually edit the validator_definitions.yml
So I guess it would make sense to re-import the validator if the password is missing in validator_definitions.yml, right?

We could check in `lighthouse account import` whether the existing password (if any) is correct and replace it by the one from the import command if that one _is_ correct.

## Version

Lighthouse v2.0.1

**Comment by eklm** [comment]
I would like to pick this up. 
Import doesn't allow to enter wrong password. So I assume reimport case for the above: 
no_password -> valid_password.

I can think of other possible updates:
valid_password -> no_password
valid_password1 -> valid_password2 ( if the key was regenerated from the seed phrase and encrypted with another password)
Should we also reimport in these cases?

**Comment by michaelsproul** [comment]
I think just handling `no_password -> valid_password` is good for now! You're right that it shouldn't be possible to end up with an incorrect password in the validator definitions (unless they're manually edited).

Thanks!

**Comment by michaelsproul** [comment]
Closed by #2868, will be included in the next release. Thanks `eklm`!
