### ISSUE TITLE
SignedRoot macro could be more flexible

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#287]
## Description

In the `ssz_derive` crate, there is a `SignedRoot` macro which implements the `SignedRoot` trait.

## Present Behaviour

Definition: `fn signed_root(&self) -> Hash256`

The macro will serialize each field until it finds one where the type path (e.g., `types::Signature`) ends with either `"Signature"` or `"AggregateSignature"`. Note: it's checking for the text, not the actual type -- a type alias will break the function.

## Expected Behaviour

New definition `fn signed_root(&self, signature_field: String) -> Hash256`

The macro could build a function that determines which field to stop serialization at during runtime. Here's some pseudo-code that could be generated by the macro:

```rust
fn signed_root(&self, signature_field: String) -> Hash256 {
    let mut should_continue = true;
    
    if (signature_field == "one") && should_continue {
        // add `self.one` to root
    } else { should_continue = false }
    ...
}
```

## Steps to resolve

- Update the `SignedRoot` trait definition in the `ssz` crate.
- Update the `SignedRoot` macro in the `ssz_derive` crate.
- Update all uses of the `signed_root()` fn in the wider codebase.

**Comment by djrtwo** [comment]
note: `signature_field` is removed in v0.5.0. The convention is to have signature last and for `signed_root(obj)` to slice off the last field and do a`hash_tree_root`

**Comment by paulhauner** [comment]
Thanks Danny!

Given this, I think we should ditch my earlier proposal and use a field attribute to mark the "stop hashing" field.

E.g.,

```rust
#[derive(SignedRoot)]
struct Things {
  pub sign_this: Thing,
  pub and_this: Thing,
  #[signed_root(end)]
  pub dont_sign_this: Signature,
  pub or_this: Thing,
}
```
Example: [this commit](https://github.com/sigp/lighthouse/pull/308/commits/01bfd386375f69e20bc157c8bc26217077b8e97b) allows test random to support the changes introduced in [this later commit](https://github.com/sigp/lighthouse/pull/308/commits/c648491c45fdf858c55006a57cd4b48db6e08a91).

**Comment by seansu4you87** [comment]
@paulhauner I'm interested in taking this on if no one else has started.

Just to make sure I'm understanding this correctly, is the idea for only fields before #[signed_root(end)] to be used in a call to hash_tree_root?  So in your example of
```
#[derive(SignedRoot)]
struct Things {
  pub sign_this: Thing,
  pub and_this: Thing,
  #[signed_root(end)]
  pub dont_sign_this: Signature,
  pub or_this: Thing,
}
```

We would only pass `sign_this` and `and_this` to `hash_tree_root` to get the signed root of a `Things` struct, and skip `dont_sign_this` and `or_this`?

Are there structs you want me to apply this functionality to?

**Comment by mjkeating** [comment]
So, to get the hash_tree_root of an object we call `hash_tree_root` of its member structs and then `merkle_hash` the resulting list of hashes. This is currently done in the `TreeHash` macro in `szz_derive`. We should be able to add this change to the `TreeHash` macro. In the macro, we simply stop hashing the object's member fields when we see the field name 'signature'.  So:

```
if fieldname == `signature` then stop_hashing_fields
```
  
This should work since the macro hashes the fields in the order in which the are declared in the object.

**Comment by seansu4you87** [comment]
@mjkeating I see, so the desired functionality is to stop hashing implicitly when we detect a field name in the struct named `signature`?

In terms of comparing the implicit stop based on a field name, vs an explicit `#[signed_root(end)]`, I personally think that the explicit annotation is preferable.  I feel like the implicit interface can lead to unexpected behavior and bugs for the user.  However, I don't have much context here, so I'm happy to either.  Thoughts?

**Comment by mjkeating** [comment]
Sure, using the annotation sounds good to me.
