### ISSUE TITLE
Gossipsub Unsubscribe backoff

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#2870]
## Description

This is technically an issue for `rust-libp2p` but I'm adding it here to track. 

We need to implement an unsubscription backoff which works in conjunction with a prune-backoff. Details are in the specs here: https://github.com/libp2p/specs/pull/383/

**Comment by divagant-martian** [comment]
Closed by [rust-libp2p 2403](rhttps://github.com/libp2p/rust-libp2p/pull/2403)

**Comment by divagant-martian** [comment]
Closed by [rust-libp2p 2403](https://github.com/libp2p/rust-libp2p/pull/2403)
