### ISSUE TITLE
Excessive penalties for attestations with unknown head

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2902]
## Description

Presently, I believe we are being too strict on peers who send attestations for an unknown head block.

We can see that we do a -10 penalty for a peer if `reprocess_tx.is_none()`:

https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/network/src/beacon_processor/worker/gossip_methods.rs#L1403

Here we can see that we set `reprocess_tx` to `None` when re-processing attestations that were queued due to an unknown head:

https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/network/src/beacon_processor/mod.rs#L1499

So, nodes incur a -10 penalty for *each attestation* where we were unable to find the head block. This penalty might be applied to peers who weren't even asked for the block, or peers who were asked but we were unable to process their response yet (e.g., on an overloaded node).

## How to Solve

The simplest method would be to just remove this line:

https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/network/src/beacon_processor/worker/gossip_methods.rs#L1403

However, we still need to apply some penalty to nodes who provided us an attestation but not the head block. I assume this is possible, but I haven't thought it out yet.

**Comment by pawanjay176** [comment]
We already penalise the peer that gave us the attestation but didn't give us the correct head block in sync manager.

https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/network/src/sync/manager.rs#L510-L513

So removing the penalty in `gossip_methods` seems okay to me.

**Comment by divagant-martian** [comment]
What about a middle ground: use a debounce strategy to give HighToleranceErrors (a tenth of the LowT one) for these errors and giving a harsher penalty for not providing the block in sync?

**Comment by paulhauner** [comment]
> We already penalise the peer that gave us the attestation but didn't give us the correct head block in sync manager.

This seems good to me, I'm happy to roll with this. @AgeManning are you also on-board with this?

> What about a middle ground: use a debounce strategy to give HighToleranceErrors (a tenth of the LowT one) for these errors and giving a harsher penalty for not providing the block in sync?

Peers can send us several hundred attestations, so we can still get a ban from a single incident. I considered saying "one attestation-related penalty per epoch", but if @pawanjay176 is right I think we can just drop the penalty for unknown head attn.

**Comment by paulhauner** [comment]
> We already penalise the peer that gave us the attestation but didn't give us the correct head block in sync manager.

I can see it will penalize the peer if they return a block that's invalid. I'm not sure what happens if they don't respond at all, will they get a penalty for timing-out on an RPC request?

**Comment by michaelsproul** [comment]
I think completely removing the penalty on attestations might make us vulnerable to a spam attack.

1. Malicious peers send attestations with junk data in the `beacon_block_root`
2. Upon processing their attestations, we try to look up the `beacon_block_root`s using single block lookups
3. Honest peers don't know the blocks, and respond with empty blocks by root responses
4. _The malicious peers also respond with empty blocks by root responses_
5. Malicious peers aren't distinguished from honest peers, and can keep spamming

The code for the honest peers sending empty responses is [here](https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/network/src/beacon_processor/worker/rpc_methods.rs#L123-L152) for reference.

**Comment by paulhauner** [comment]
> I think completely removing the penalty on attestations might make us vulnerable to a spam attack.

I also agree, I didn't realise there was a way around the penalty with an empty response.

We still need to figure out how to fix this issue though. Presently we're banning honest peers.

**Comment by AgeManning** [comment]
If the node doesn't respond it counts as a failure. Given enough failures it seems we penalize all peers. 

I think the approach we should take is something similar to sync. Whereby all peers that say a particular block exists, go into a pool. When requesting the block, we sample the pool. If after say 3 attempts, we can't get the block, the entire pool gets penalized. 

I'll knock up a PR for this.

**Comment by michaelsproul** [comment]
Noting that the attack I described isn't viable because we only ever ask peers that sent us the attestation for the block, and we penalise empty blocks by root responses in that case (thanks @pawanjay176 for working this out)
