### ISSUE TITLE
Remove `disabled_forks` field

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2923]
## Description

There's a redundant field on the `BeaconChain` called `disabled_forks` that was once part of our fork-aware networking (https://github.com/sigp/lighthouse/pull/953) but which is no longer used and could be deleted.

https://github.com/sigp/lighthouse/blob/fff01b24ddedcd54486e374460855ca20d3dd232/beacon_node/beacon_chain/src/beacon_chain.rs#L306-L307

## Steps to resolve

Remove all references to `disabled_forks` so that the code compiles and `git grep disabled_forks` returns no results.

**Comment by RishiKumarRay** [comment]
I would like to do, please assign me , also do i have to delete every line where disabled_forks is present

**Comment by michaelsproul** [comment]
> I would like to do, please assign me , also do i have to delete every line where disabled_forks is present

Thank you! Yeah, you will have to delete all the lines where `disabled_forks` is mentioned.

**Comment by RishiKumarRay** [comment]
@michaelsproul please do review
