### ISSUE TITLE
Error building 2.10: feature edition2021 is required

### ISSUE THREAD

**Issue by PerfectDark99** [sigp/lighthouse#2941]
## Description

When trying to build I get below error:

    error: failed to get libp2p as a dependency of package lighthouse_network v0.2.0 (/home/abc/lighthouse/beacon_node/lighthouse_network)

    Caused by: failed to load source for dependency libp2p

    Caused by: Unable to update https://github.com/libp2p/rust-libp2p?rev=17861d9cac121f7e448585a7f052d5eab4618826#17861d9c

    Caused by: failed to parse manifest at /home/abc/.cargo/git/checkouts/rust-libp2p-98135dbcf5b63918/17861d9/swarm/Cargo.toml

    Caused by: feature edition2021 is required

    this Cargo does not support nightly features, but if you switch to nightly channel you can add cargo-features = ["edition2021"] to enable this feature make: *** [Makefile:28: install] Error 101

## Version

lighthouse: 2.1.0
rust: 1.58.0

**Comment by realbigsean** [comment]
`edition2021` features should be available by default in rust 1.56.0 or later, so I'd double check your rust version with `rustc --version`

**Comment by PerfectDark99** [comment]
I think the issue somehow was cargo not being updated correctly as I had version 1.54.0 with rustc 1.58.0.  did some googling and I ran:

rustup default nightly && rustup update
followed by
rustup default stable && rustup update

And now its compiling and I have cargo 1.58.0
