### ISSUE TITLE
Snapshots cloned during sync

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2944]
## Description

Since https://github.com/sigp/lighthouse/pull/2832 Lighthouse will clone a snapshot from the cache whenever there's a skipped slot. This is designed to help during live block processing, but _also_ gets applied during sync where it isn't very useful.

## Present Behaviour

The condition here trips regardless of whether or not Lighthouse is syncing:

https://github.com/sigp/lighthouse/blob/79db2d4deb6a47947699d8a4a39347c19ee6e5d6/beacon_node/beacon_chain/src/snapshot_cache.rs#L256-L258

## Expected Behaviour

Lighthouse should always move the snapshot from the cache during sync in order to prevent unnecessary cloning and extra memory usage.

**Comment by macladson** [comment]
Closed by #3271
