### ISSUE TITLE
Don't poll for sync committee duties with 0 validators

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2953]
## Description

Presently the validator client will poll for sync committee duties even if it doesn't have any validators activated. This causes a `WARN` with a Nimbus BN:

```
Jan 25 09:40:28.264 WARN Failed to download sync committee duties, error: All endpoints failed http://testing.mainnet.beacon-api.nimbus.team/ => Unavailable(Offline), http://testing.mainnet.beacon-api.nimbus.team/ => RequestFailed(StatusCode(400)), sync_committee_period: 369, service: duties
```

The response from the endpoint is:

```
$ curl -X POST -H "Content-Type: application/json" --data '[]' "http://testing.mainnet.beacon-api.nimbus.team/eth/v1/validator/duties/sync/94208"
{"code":"400","message":"Empty validator's index array","stacktraces":[]}
```

This only occurs when the Lighthouse VC has 0 validators, so it doesn't prevent Lighthouse from working with Nimbus. However the warning _can_ be logged on start-up when Lighthouse is in the process of decrypting keystores and has 0 _active_ validators.

## Steps to resolve

We should add a check that the local validators vec is non-empty before POSTing to the BN, and confirm that this removes the WARN when running against Nimbus.

**Comment by tthebst** [comment]
hey hey! I would like to work on this. Any gotchas?

**Comment by michaelsproul** [comment]
Awesome, thank you!

I can't think of any gotchas off the top of my head, but if you get stuck please let us know ☺️

**Comment by tthebst** [comment]
I tried to verify my code changes today and I was wondering about the best approach. How is the workflow when testing lighthouse with other VC and BN (for lighthouse BN <-> lighthouse VC I can use the scripts)? 
In the case of nimbus I found a few [public](https://githubhelp.com/status-im/infra-nimbus) testing BN. For other clients I haven't found anything similar. If you do testing do you run these BN or VC locally (or use infura or alchemy)?

**Comment by michaelsproul** [comment]
At the moment we just test manually. In this case I'd be satisfied with a manual test against the public Nimbus node(s).

I also have a collection of Prater validators that I run against Infura

We'll be looking to improve this testing process in future with more managed deployments of the Lighthouse VC running against the other clients on Prater

**Comment by tthebst** [comment]
I submitted a PR. It seems to be just a small change that is needed. I added some alternatives on how to implement the change depending on your preferences.
