### ISSUE TITLE
Apple M1 Monterey compatibility question

### ISSUE THREAD

**Issue by Sajjon** [sigp/lighthouse#2959]
I'm a Lighthouse on Apple Silicon user since last year, I'm very happy with Lighthouse on Apple Silicon. 

My Mac Mini M1 is still running macOS Big Sur, I was wondering if anyone have tried out Lighthouse on an Apple Silicon Mac running macOS Monterey?

**Comment by realbigsean** [comment]
I haven't tried this personally, but we do push lighthouse to homebrew, which tests building on Monterey M1:

https://github.com/Homebrew/homebrew-core/runs/4939129200?check_suite_focus=true
