### ISSUE TITLE
Make tests compatible with latest ganache

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#2961]
## Description

As pointed out by @tthebst in discord, eth1 tests are not compatible with the latest `ganache-cli` version

## Version

`v2.1.1`

## Present Behaviour

```
thread 'persist::test_persist_caches' panicked at 'should start eth1 environment: "Timed out waiting for ganache to start. Is ganache-cli installed?"', beacon_node/eth1/tests/test.rs:762:18
```

## Expected Behaviour

Tests run successfully.

## Steps to resolve

Not sure yet what exactly is breaking

**Comment by pawanjay176** [comment]
Fixed in #3056
