### ISSUE TITLE
Ensure all caches are built during checkpoint sync startup

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#2962]
## Description

I've seen this a few times, mostly on low-powered devices:

```
Jan 26 01:06:21.024 WARN BlockProcessingFailure                  outcome: BlockSignatureVerifierError(BeaconStateError(CommitteeCacheUninitialized(Some(Previous)))), msg: unexpected condition in processing block.
```

It occurs immediately after starting with checkpoint sync. I think we must be missing a call to initialize all of the caches on the checkpoint state before making it the head.

**Comment by paulhauner** [comment]
I think there might be some other caches we're missing too. I've noticed cache misses right after startup too.

Ensuring the caches primed can avoid state reads from the DB which can make tangible improvements to the memory footprint.
