### ISSUE TITLE
Run image as non-root

### ISSUE THREAD

**Issue by jmcruz1983** [sigp/lighthouse#2971]
## Description

Current docker image runs as root user as default.
```
docker run -it sigp/lighthouse:v2.1.1 sh
# id
uid=0(root) gid=0(root) groups=0(root)
```
I would suggest to add a custom user to avoid to run as root as recommended by best practices.

**Comment by michaelsproul** [comment]
Closing as a duplicate of https://github.com/sigp/lighthouse/issues/1905
