### ISSUE TITLE
lighthouse beacon does not start after upgrade to 2.1.1

### ISSUE THREAD

**Issue by SalBlas** [sigp/lighthouse#2972]
## Description

I was running lighthouse beacon node and validator 2.0.1 in ubuntu 20.04. I downloaded the last release as usual (lighthouse-v2.1.1-x86_64-unknown-linux-gnu.tar.gz) after that I stop the services lighthouse validator and lighthouse beacon in that order, I update the executable and relaunch again: first lighthouse beacon and then lighthouse validator.

The beacon validator seems to be running correctly, but beacon node fails.

```
INFO Data directory initialised              datadir: /var/lib/lighthouse
WARN Running HTTP server on port 5052
INFO Deposit contract                        address: 0x00000000219ab540356cbb839cbe05303d7705fa, deploy_block: 11184524
WARN Unable to migrate to database schema 7, re-initializing fork choice, error: SchemaMigrationError("BeaconStateError(MissingBeaconBlock(SignedBeaconBlockHash(0x277b6a464a43abcc5f1a2c69f59fae1f5f894719e860f3fdbc14dcb6278a9575)))")
CRIT Failed to start beacon node             reason: Unable to open database: SchemaMigrationError("Missing anchor beacon state")
INFO Internal shutdown received              reason: Failed to start beacon node
INFO Shutting down..                         reason: Failure("Failed to start beacon node")

``` 

## Version

```
lighthouse --version
Lighthouse v2.1.1-5f628a7
BLS library: blst-modern
SHA256 hardware acceleration: false
Specs: mainnet (true), minimal (false)

```
What should I do?

**Comment by michaelsproul** [comment]
Sorry it looks like your database has become corrupted.

For now the best thing to do is delete it by adding `--purge-db` to your beacon node flags and resyncing the database with checkpoint sync: https://lighthouse-book.sigmaprime.io/checkpoint-sync.html

Before deleting it could be helpful to us if you could save the logs from `/var/lib/lighthouse/beacon/logs` and send them to us (DM me on Discord, or email them to `$firstname@sigmaprime.io`)

Thanks

**Comment by paulhauner** [comment]
I'm going to close this, but please feel free to re-open if there is any more information to be shared :pray:

**Comment by SalBlas** [comment]
Of course. Thanks again for your help.
