### ISSUE TITLE
v2.1.1 crashes on startup

### ISSUE THREAD

**Issue by ryny24** [sigp/lighthouse#2979]
## Description

I've upgrade every version with no problem, but this one will not run with error "Task panic. This is a bug! ". LOG entry below.

## Version

lighthouse-v2.1.1-aarch64-unknown-linux-gnu

## Expected Behaviour

Start up normal without a bug error.

## Steps to resolve

Rolled back and works fine.

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: FromHexError { inner: InvalidStringLength }', consensus/types/src/chain_spec.rs:694:10
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at ./rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: types::chain_spec::default_terminal_total_difficulty
   4: <serde::__private::de::FlatMapDeserializer<E> as serde::de::Deserializer>::deserialize_struct
   5: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
   6: <&mut serde_json::de::Deserializer<R> as serde::de::Deserializer>::deserialize_struct
   7: serde_json::de::from_slice
   8: validator_client::beacon_node_fallback::CandidateBeaconNode<E>::refresh_status::{{closure}}
   9: <futures_util::future::join_all::JoinAll<F> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: validator_client::ProductionValidatorClient<T>::new::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  16: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: std::thread::local::LocalKey<T>::with
  19: tokio::runtime::thread_pool::worker::Context::run_task
  20: tokio::runtime::thread_pool::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::thread_pool::worker::run
  23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jan 31 19:50:31.241 CRIT Task panic. This is a bug!              advice: Please check above for a backtrace and notify the developers, message: <none>, task_name: validator_client

**Comment by michaelsproul** [comment]
Thanks for getting in touch. This is a known issue when running a v2.1.1 validator client against a v2.0.1 beacon node, please see https://github.com/sigp/lighthouse/issues/2958 and https://github.com/sigp/lighthouse/pull/2957#issuecomment-1021150217.

The fix is to upgrade all the beacon nodes to v2.1.1 before upgrading the validator client to v2.1.1.

This bug has been fixed in `unstable` and the bugfix will be available in the forthcoming v2.1.2 release in the next few days.

**Comment by ryny24** [comment]
Ok thank you. I found which node was the issue and removed it. It's running now.
