### ISSUE TITLE
Check new CLI flags introduced by Bellatrix

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2982]
## Description

I know there were some new CLI arguments added to support merge testnets. I'm pretty sure some of these are untested and I'm not certain they all match the spec now.

To resolve this issue, check out a [diff between v2.0.1 and v2.1.0](https://github.com/sigp/lighthouse/compare/v2.0.1...v2.1.0) and see which CLI arguments have changed. For each:

- Ensure it matches any existing standards,
- Ensure it is tested in [`lighthouse/tests`](https://github.com/sigp/lighthouse/tree/stable/lighthouse/tests) tests, to some degree.

**Comment by ethDreamer** [comment]
on it

**Comment by paulhauner** [comment]
Resolved in #2986
