### ISSUE TITLE
Retrospective transition block checking

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2983]
## Description

The "transition block" is the first block in a chain that includes a non-empty `ExecutionPayload`. This is effectively the first *merging* of the proof-of-work chain into the proof-of-stake chain.

This block requires some [additional verification](https://github.com/sigp/lighthouse/blob/5f628a71d4b2a7e7761b30e726338bba07617cd2/beacon_node/beacon_chain/src/execution_payload.rs#L72-L139) when compared to pre- and post-transition blocks; the consensus client must check that the PoW chain has reached the terminal total difficulty and/or some other criteria.

These additional verifications are challenging during optimistic sync. We can't perform them during sync, since the execution client might not be synced enough to respond to the requests. So, we *optimistically* accept the transition block and promise to come back later and check it once the execution client is synced.

Presently, Lighthouse happily optimistically accepts the transition block, but it fulfills the promise to verify it. Therefore, Lighthouse needs:

- A way to cache optimistic transition blocks as we come across them during sync.
	- This cache must persist across reboots, so it needs to be saved to the DB.
- A way to know that the EL is synced and it's therefore time to check all the blocks in the cache.
- Interaction with #2837 to invalidate any blocks where the tranisition *fails* the retrospective check (talk to @paulhauner)

**Comment by ethDreamer** [comment]
I ran into some related stuff when working on the engine-api upgrade so I'm going to put all the block conditions here:
 - [eth2 spec transition block validation conditions](https://github.com/ethereum/consensus-specs/blob/v1.1.9/specs/bellatrix/fork-choice.md#validate_merge_block)
 - [EIP-3675 transition block validation conditions (EE side)](https://eips.ethereum.org/EIPS/eip-3675#transition-block-validity)
 - [Invalid transition block response from EE (see #2)](https://github.com/ethereum/execution-apis/blob/v1.0.0-alpha.6/src/engine/specification.md#payload-validation)

You'll notice there's a new status `INVALID_TERMINAL_BLOCK` in the response to `newPayloadV1` (formally `executePayloadV1`) from the execution engine.. not sure how that changes what you've discussed here @paulhauner

**Comment by paulhauner** [comment]
> You'll notice there's a new status INVALID_TERMINAL_BLOCK in the response to newPayloadV1 (formally executePayloadV1) from the execution engine.. not sure how that changes what you've discussed here @paulhauner

I don't think that changes anything here, thanks for pointing it out though.

**Comment by paulhauner** [comment]
I'm thinking that perhaps we want logic along the lines of this:

1. Whenever a transition block is optimistically imported, insert it into an "optimistic transition blocks" (OTB) column in the database.
1. Periodically run a routine that:
    1. Loads all blocks roots from the OTB column.
    1. Removes any blocks from the OTB column that conflict with the finalized checkpoint.
    1. For remaining OTB block roots that are finalized, check them against the EL and kill the client if they're invalid.
    1. For remaining OTB blocks that are not-yet-finalized, run [`BeaconChain::process_invalid_execution_payload`](https://github.com/sigp/lighthouse/blob/267d8babc8cfe20f5b27327f16823324ed0b45a9/beacon_node/beacon_chain/src/beacon_chain.rs#L3200-L3203) for any invalid blocks.
    1. For any blocks that are found to be valid, remove them from the OTB table.

**Comment by paulhauner** [comment]
Resolved via #3372 :tada:
