### ISSUE TITLE
Update to execution-apis v1.0.0-alpha.6

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2985]
## Description

There is a new version of the execution API :tada: https://github.com/ethereum/execution-apis/releases/tag/v1.0.0-alpha.6

We need to ensure Lighthouse is updated to match the new JSON structures and semantics.

It would be sensible to coordinate this with other EL and CL teams. If you're not sure how to go about this, reach out to me :)

**Comment by ethDreamer** [comment]
I might as well do this since I did the last one :)

**Comment by paulhauner** [comment]
FYI over in #2837 I made some changes to ensure we thread the `latest_valid_hash` back up to the `BeaconChain`, we'll have to make sure we do the same for the new execute payload response variants.

**Comment by paulhauner** [comment]
Resolved in #3018
