### ISSUE TITLE
Crash with Unable to create directory (lighthouse vc)

### ISSUE THREAD

**Issue by ChuckNorrison** [sigp/lighthouse#2990]
## Description

lighthouse vc instance results with

> Unable to create directory: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

## Version

2.1.1 build from source

## Present Behaviour

lighthouse vc start and crashed with Permission denied after update was done

## Expected Behaviour

this should start without any errors. Missing more details which folder failed to create.

## Steps to resolve

Replace `--validators-dir` and `--secrets-dir` arguments with `--datadir`

**Comment by skylenet** [comment]
I'm having the same problem. My lighthouse process is only allowed to write into a `/data`  directory. 
So I had my validators configured with `--validator-dir` and `--secrets-dir` using some sub directories under `/data`.

I started seeing that error, so I thought that lighthouse is probably trying to create something in the default datadir.
So I tried to set my `--datadir` to `/data` , but it looks like that the flag is mutual exclusive with the other 2 directory flags. 

So I had to end up moving the validators to `/data/validators` and the secrets to `/data/secrets` and just use the `--datadir=/data`  as a workaround.

**Comment by michaelsproul** [comment]
Ahh, I think know what the story is here.

Since v2.1.0 Lighthouse will now log in the background by default, to `$datadir/validators/logs`. The logging can be disabled with `--logfile-max-number 0`, or the location can be changed with `--logfile`.

**Comment by ChuckNorrison** [comment]
@michaelsproul thanks for this hint. Add `--logfile` works. 

The logfile behaviour should respect the `--validators-dir` argument automatically. Seems it tries to write into a non existent datadir. `.lighthouse` per default, which is missing on my instances. 

Thanks for your support. I prefer to use only `--datadir` in the future to simplify the setup for me.

**Comment by macladson** [comment]
Closed by #3003
