### ISSUE TITLE
v2.1.2 Release Notes "InsuffucientPeers" Typo

### ISSUE THREAD

**Issue by jerryji** [sigp/lighthouse#2991]
## Description

In v2.1.2 release notes Summary contains mis-spelled word "InsuffucientPeers", which should have been "InsufficientPeers"

## Version

v2.1.2

## Present Behaviour

NA

## Expected Behaviour

NA
![Selection_067](https://user-images.githubusercontent.com/83122/152283740-b57aef1b-544b-45f6-8582-730910ed9223.png)

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
Thank you!

Fixed it just now
