### ISSUE TITLE
Collecting fee recipients from pre-merge validators

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2994]
## Description

After Bellatrix, it will eventually be necessary for Lighthouse to know one more detail for each validator: the `suggested_fee_recipient` (SFR) for producing an execution payload ("eth1 block").

For new validators, it makes sense to add a SFR to the `lighthouse account validator` commands that create a validator.

In #2924, the `suggested_fee_recipient` can be loaded from CLI, from file and from the `validator_definitions.yml` file. To me, it seems like the clearest strategy would be to get users to edit the `validator_definitions.yml`. Perhaps it would be nice if we wrote a `lighthouse account` tool that can be pointed at a `validator_definitions.yml` file and it will request a SFR for each validator and update the file.

**Comment by paulhauner** [comment]
Here is Teku's work along these lines: https://github.com/ConsenSys/teku/pull/4894

**Comment by james-prysm** [comment]
Here is Prysm's implementation that follows something similar https://github.com/prysmaticlabs/prysm/issues/10292

**Comment by michaelsproul** [comment]
Closing this as we now support the fee recipient HTTP API and fee recipients in the validator definitions YAML

**Comment by djbakerman** [comment]
for the SFR would that be an ETHv1 or ETHv2 address? Any reason why it should not be the same as the validator public address?

**Comment by michaelsproul** [comment]
@djbakerman We just added an FAQ on this exact point! You can give it a test drive here: https://lighthouse-book.sigmaprime.io/suggested-fee-recipient.html#why-do-i-have-to-nominate-an-ethereum-address-as-the-fee-recipient

Let us know if that helps or if you think there's anything you think we should add

**Comment by djbakerman** [comment]
Thank you that was helpful.  Perhaps obvious, but it's worth mentioning something like: "If the execution node is testnet, ensure the ETHv1 address is a testnet address"
