### ISSUE TITLE
Beacon chain genesis not happening

### ISSUE THREAD

**Issue by RohitAudit** [sigp/lighthouse#2996]
## Description

I have started my own beacon chain connected to smart contract deployed on Goerli testnet. The genesis is not happening though it meets the genesis criteria.
To setup the chain I ran following config
```
lcli --spec mainnet new-testnet --deposit-contract-address 0x27c495e778386b57e9e9F309f4cF99DFc3103e1F --deposit-contract-deploy-block 6306850 --effective-balance-increment 100000000 --ejection-balance 1600000000 --eth1-follow-distance 16 --genesis-fork-version 0x00000751 --max-effective-balance 3200000000 --min-deposit-amount 100000000 --min-genesis-active-validator-count 1  --testnet-dir ~/.lighthouse/schlesi --min-genesis-time 1644073828 --genesis-delay 120 --eth1-id 5
```

## Version

v2.1.2

## Present Behaviour

Following are the logs printed from the beacon client:
```
Feb 05 15:10:52.806 INFO Waiting for adequate eth1 timestamp     latest_eth1_timestamp: 1644073668, genesis_time: 1644073828, genesis_delay: 120, service: beacon
Feb 05 15:10:59.819 INFO Waiting for adequate eth1 timestamp     latest_eth1_timestamp: 1644073668, genesis_time: 1644073828, genesis_delay: 120, service: beacon
Feb 05 15:11:06.845 INFO Waiting for adequate eth1 timestamp     latest_eth1_timestamp: 1644073683, genesis_time: 1644073828, genesis_delay: 120, service: beacon
Feb 05 15:11:13.858 INFO Waiting for adequate eth1 timestamp     latest_eth1_timestamp: 1644073683, genesis_time: 1644073828, genesis_delay: 120, service: beacon
Feb 05 15:11:20.884 INFO Waiting for adequate eth1 timestamp     latest_eth1_timestamp: 1644073698, genesis_time: 1644073828, genesis_delay: 120, service: beacon
Feb 05 15:11:27.897 INFO Waiting for adequate eth1 timestamp     latest_eth1_timestamp: 1644073698, genesis_time: 1644073828, genesis_delay: 120, service: beacon
Feb 05 15:11:34.929 INFO Waiting for more validators             valid_deposits: 2, total_deposits: 4, active_validators: 0, min_genesis_active_validators: 1, service: beacon
Feb 05 15:11:41.942 INFO Waiting for more validators             valid_deposits: 2, total_deposits: 4, active_validators: 0, min_genesis_active_validators: 1, service: beacon
Feb 05 15:11:48.974 INFO Waiting for more validators             valid_deposits: 2, total_deposits: 4, active_validators: 0, min_genesis_active_validators: 1, service: beacon
Feb 05 15:11:55.987 INFO Waiting for more validators             valid_deposits: 2, total_deposits: 4, active_validators: 0, min_genesis_active_validators: 1, service: beacon
Feb 05 15:12:03.000 INFO Waiting for more validators             valid_deposits: 2, total_deposits: 4, active_validators: 0, min_genesis_active_validators: 1, service: beacon
Feb 05 15:12:10.033 INFO Waiting for more validators             valid_deposits: 2, total_deposits: 4, active_validators: 0, min_genesis_active_validators: 1, service: beacon
Feb 05 15:12:17.047 INFO Waiting for more validators             valid_deposits: 2, total_deposits: 4, active_validators: 0, min_genesis_active_validators: 1, service: beacon
Feb 05 15:12:24.079 INFO Waiting for more validators             valid_deposits: 2, total_deposits: 4, active_validators: 0, min_genesis_active_validators: 1, service: beacon

```

Can someone guide me what I have been doing wrongly.

**Comment by paulhauner** [comment]
From a glance, it's not clear what the issue is here. Notably, it appears there are 2 valid deposits and 2 invalid deposits.

I would try running with at least 32 validators, the beacon chain doesn't make a whole lot of sense for really small validator counts.

Try upping the validator count. If that doesn't work, could you try using `--debug-level debug` and share those logs?

**Comment by RohitAudit** [comment]
So, I started the chain in debug mode. I am making the deposit correctly but the validators are not marked as active.
```
Feb 07 12:14:26.426 INFO Waiting for more validators             valid_deposits: 16, total_deposits: 22, active_validators: 0, min_genesis_active_validators: 16
Feb 07 12:14:33.433 DEBG No new deposits found                   total_deposits: 22, latest_block: 6337018
Feb 07 12:14:33.439 DEBG Downloading eth1 blocks                 last: None, first: None
Feb 07 12:14:33.439 DEBG No new eth1 blocks imported             cached_blocks: 1, latest_block: 6337266
Feb 07 12:14:33.439 DEBG Imported eth1 blocks                    count: 0, cache_head: 6337266, latest_block_timestamp: 1644235968
Feb 07 12:14:33.439 INFO Waiting for more validators             valid_deposits: 16, total_deposits: 22, active_validators: 0, min_genesis_active_validators: 16
Feb 07 12:14:40.453 DEBG Imported deposit logs chunk             logs: 0
Feb 07 12:14:40.453 DEBG No new deposits found                   total_deposits: 22, latest_block: 6337018
Feb 07 12:14:40.458 DEBG Downloading eth1 blocks                 last: Some(6337267), first: Some(6337267)
Feb 07 12:14:40.465 DEBG Imported eth1 block(s)                  new: 1, total_cached_blocks: 2, latest_block: 6337267, latest_block_age: 1 mins
Feb 07 12:14:40.465 DEBG Imported eth1 blocks                    count: 1, cache_head: 6337267, latest_block_timestamp: 1644235983
Feb 07 12:14:40.491 TRCE Insufficient active validators          eth1_block_number: 6337267, active_validators: 0, min_genesis_active_validator_count: 16
Feb 07 12:14:40.492 INFO Waiting for more validators             valid_deposits: 16, total_deposits: 22, active_validators: 0, min_genesis_active_validators: 16
```
Can you suggest what I may be doing wrong.
As mentioned in the above issue I am making a deposit of 3.2 eth for every validator.
Do I need to run multiple boot nodes as well or 1 is enough?

**Comment by RohitAudit** [comment]
So,
I went through code, added some print statements. It seems the binary was not setting the MAX_EFFECTIVE_BALANCE from the config file. Its still taking MAX_EFFECTIVE_BALANCE as default one ,i.e., 32 eth

**Comment by michaelsproul** [comment]
> It seems the binary was not setting the MAX_EFFECTIVE_BALANCE from the config file. Its still taking MAX_EFFECTIVE_BALANCE as default one ,i.e., 32 eth

That's right. `MAX_EFFECTIVE_BALANCE` is part of the [preset](https://github.com/ethereum/consensus-specs/tree/dev/presets) so can only be configured at compile-time. The list of available runtime config options is here: https://github.com/ethereum/consensus-specs/tree/dev/configs.

It's probably easiest to just stick to 32 ETH deposits so that you don't need to modify the code (that's what the Gnosis chain does too).

**Comment by RohitAudit** [comment]
I was testing the system and enough enough test eth on any testnet is a pain. So, I have changed the preset to 3.2 eth and compiled the code. Is there anything else I need to change or can I proceed the further testing with the current compiled version?

**Comment by michaelsproul** [comment]
Ok cool. It should be OK if you've just updated it in the preset. If you change any of the other preset params that are also type-level constants you'll need to change them on the `EthSpec` too (e.g. `MAX_ATTESTATIONS`).

_Just in case_ you haven't seen it already, it's also possible to run testnets against a local version of Ganache using the scripts here: https://github.com/sigp/lighthouse/tree/stable/scripts/local_testnet. I understand you might have good reason to test against a real execution testnet though :+1:

**Comment by RohitAudit** [comment]
Thanks. Yup tested it with local npx hardhat node setup. Wanted to run on testnet for staging environment.
