### ISSUE TITLE
VC option to pass subscriptions to fallback nodes

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3001]
## Description

Following from [this thread](https://github.com/sigp/lighthouse/issues/2888#issuecomment-1008788775), it would be nice if the VC had an opt-in flag to publish subscriptions to all backup endpoints (or maybe even *specific* endpoints :thinking:). This means that backup BNs don't need to run with subscribe-all-subnets to be reliable.

I'm cautious of incurring usage on third-party nodes, that's why I suggested opt-in.

**Comment by lfinbob** [comment]
I'm very much in favor of this. With the post-merge reality setting in we'll have a lot of staking enthusiasts using a simple fall back EL+CL. Rocket Pool makes this dead simple for example.
They will assume that a fall back beacon node works automatically and without missing attestations (proposals, sync commitees). But it doesn't. Unless you specify `--subscribe-all-subnets` which is wasteful to home stakers' bandwidth.

**Comment by maninthecryptosuit** [comment]
I'm also in favour of this, it would help significantly reduce CPU, RAM, bandwidth and power usage on the backup node.

**Comment by michaelsproul** [comment]
Implemented in https://github.com/sigp/lighthouse/pull/3529 and will be part of the next release 🎉
