### ISSUE TITLE
`validators-dir` flag is inconsistent with `validator-dir` flag

### ISSUE THREAD

**Issue by macladson** [sigp/lighthouse#3020]
## Description

I noticed some confusion on Discord around the `validators-dir` CLI flag which might be worth rectifying.

For example. The CLI flag's name in the `validator_client`/`vc` subcommand is `validators-dir` whereas the CLI flag's name in the `account_manager validator` subcommand is `validator-dir` while they both refer to the `validators` directory.

I'm not really sure if this is something even worth changing, but thought it was worth pointing out, as it has caused at least 1 instance of confusion.

#### Pros
- There are more occurances of `validator-dir` than `validators-dir` so this would end up with the least lines changed. 
#### Cons
- ~This would make the `validator_client` CLI backwards incompatible.~
- It will also highlight an inconsistency with the directory containing the validators being called `validators` while the commands to interact with it are `validator_client` and `validator-dir`.

#### Pros
- ~This would only make the `account_manager` CLI backwards incompatible.~
- Would be consistent with the `validators` directory.
#### Cons
- It is much more involved as the `validator-dir` notation is baked into other parts of the code. The main example of this is the `validator_dir` crate in `common/validator_dir`.  
- It would also highlight the inconsistency of the `validator_client` not containing the plural whereas the other instances do.

### Option 3: Alias the commands together

As @michaelsproul pointed out, if we simply aliases the commands to each other in both services it would remove the inconsistencies on the CLI side (which is where the confusion is anyway)
This is probably the best solution. It's backwards compatible and is much easier than the other options.

**Comment by michaelsproul** [comment]
Could we alias one to the other and keep both? That would be backwards compatible

**Comment by macladson** [comment]
> Could we alias one to the other and keep both? That would be backwards compatible

Oh yeah, of course. Good point!

---

I've added a 3rd option. If someone was looking to jump onto this, that's the direction I'd recommend going

**Comment by macladson** [comment]
Closed by #3034
