### ISSUE TITLE
Add the `execution_optimistic` flag to HTTP responses

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3031]
## Description

We should implement the changes in https://github.com/ethereum/beacon-APIs/pull/190, since I believe/hope they are going to become canonical. Our implementation will help discover anything I've missed in that previous PR.

Teku are also indicating they'll implement this API too: https://github.com/ConsenSys/teku/issues/4968

**Comment by paulhauner** [comment]
Anyone starting work on this should base their work upon https://github.com/sigp/lighthouse/pull/2837. I expect it to be merged in the coming days.

**Comment by paulhauner** [comment]
I believe @macladson is working on this!

**Comment by macladson** [comment]
Implemented in #3070.
