### ISSUE TITLE
Check for terminal block during proposer preparation

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3058]
## Description

The *merge transition block* is the first post-Bellatrix block to include a non-default `ExecutionPayload`. The `execution_payload.parent_hash` value is computed here:

https://github.com/sigp/lighthouse/blob/c3a793fd73a3b11b130b82032904d39c952869e4/beacon_node/beacon_chain/src/execution_payload.rs#L264-L267

According to the [validator guide](https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/validator.md#block-proposal), we're supposed to call forkchoiceUpdated (fcU) before producing that block with the `head_block_hash` set to the value returned from `ExecutionLayer::get_terminal_pow_block_hash`.

In #3043, I've added the functionality to give the EL a "heads-up" for payload production via a `PayloadAttributes` value in a fcU call. However, I haven't handled the edge-case of the transition block.

To handle the edge case, I think we need to call `ExecutionLayer::get_terminal_pow_block_hash` in [`BeaconChain::prepare_proposer_async`](https://github.com/sigp/lighthouse/blob/76a1d1d561f3f7f06175aaa91a8c9e2918afe3e3/beacon_node/beacon_chain/src/beacon_chain.rs#L3703-L3919) whenever we're post-Bellatrix but the head block does not have execution enabled. If we get a terminal pow block hash, then we should use *that* value as the `head_block_root` rather than the value that's presently on the head block.

We might actually be able to do it a bit cleaner, where the call to `get_terminal_pow_block_hash` is done in `BeaconChain::update_execution_engine_forkchoice_async`. I'm not sure what the best implementation is, yet.

Importantly, with our current implementation, we'll just fail to give advance notice of the terminal block. However, we'll still produce a block since we'll do a valid fcU call immediately before we try to produce the transition payload.

**Comment by ethDreamer** [comment]
I'll take this one

**Comment by ethDreamer** [comment]
Diagram of execution flow for reference
![FCU_Flow](https://user-images.githubusercontent.com/37123614/157724254-ba8ccdc2-de42-42c4-bba4-cb8ba579386e.png)
