### ISSUE TITLE
Adopt standard remote key manager API

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3068]
## Description

We should implement the standard [Remote Key Manager](https://ethereum.github.io/keymanager-APIs/#/Remote%20Key%20Manager) API in Lighthouse.

## Steps to resolve

* We can hook into the authenticated routing for the existing VC APIs [here](https://github.com/sigp/lighthouse/blob/c475499dfe9c2df52b2810054ed2c3b59d4988f8/validator_client/src/http_api/mod.rs#L537).
* The POST method should be quite similar to [`create_validators_web3signer`](https://github.com/sigp/lighthouse/blob/c475499dfe9c2df52b2810054ed2c3b59d4988f8/validator_client/src/http_api/create_validator.rs#L166).
* The DELETE method will be more involved, but similar to the non-web3-signer [`delete`](https://github.com/sigp/lighthouse/blob/c475499dfe9c2df52b2810054ed2c3b59d4988f8/validator_client/src/http_api/keystores.rs#L211). It would be good to re-use [`delete_definition_and_keystore`](https://github.com/sigp/lighthouse/blob/c475499dfe9c2df52b2810054ed2c3b59d4988f8/validator_client/src/initialized_validators.rs#L443) between the two implementations. It will need slight modifications to remove the error [here](https://github.com/sigp/lighthouse/blob/c475499dfe9c2df52b2810054ed2c3b59d4988f8/validator_client/src/initialized_validators.rs#L463).

## Version

v2.1.3

**Comment by divagant-martian** [comment]
@sonicskye will handle this one

**Comment by tthebst** [comment]
I would like to do this and if I comment here the probability increases that I will do it :)

**Comment by michaelsproul** [comment]
Thank you @tthebst, love your work!
