### ISSUE TITLE
SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY wrong type in API

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#3073]
## Description

A call to `/eth/v1/config/spec` returns a value for `SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` that is an unquoted integer.

## Version

kiln (c45e6291)

## Present Behaviour

The value is returned as an unquoted integer.

## Expected Behaviour

The value should be a quoted integer (assuming it's meant to be in the spec at all).

**Comment by realbigsean** [comment]
Thanks! 

> (assuming it's meant to be in the spec at all)

Even though optimistic sync is an optional feature I think this config should be in the spec because it impacts fork choice

**Comment by michaelsproul** [comment]
Fixed in #3074 and v2.1.4
