### ISSUE TITLE
Guide to run a node on Kiln does not work

### ISSUE THREAD

**Issue by tdelabro** [sigp/lighthouse#3075]
## Description

I'm trying to run a node on Kiln, following this tutorial: https://notes.ethereum.org/qrDBhhydTsyKFmGaBl2COQ?view#Lighthouse
It's the one provided on the ethereum R&D discord, section Merge.

I followed the instruction. Built Lighthouse (you guys should specify the minimum required rust version, or at least ask to run cargo update. Otherwise people will bother you with issues like I did on #3072)
Then I run the prompted instruction
```
lighthouse \
          --spec mainnet \
          --testnet-dir ./ \
          --debug-level info \
          beacon_node \
          --datadir ./testnet-lh1 \
          --eth1 \
          --http \
          --http-allow-sync-stalled \
          --metrics \
          --merge \
          --execution-endpoints http://127.0.0.1:8551 \
          --enr-udp-port=9000 \
          --enr-tcp-port=9000 \
          --discovery-port=9000 \
          --jwt-secrets="/tmp/jwtsecret" \
          --boot-nodes="enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk"
```

And it fail.

## Version

```
rustc -V
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

I build the kiln branch, as specified by the guide.

## Present Behaviour

I get the following error:
```
Unable to open testnet dir at "./merge-testnets/kiln/geth-datadir": Unable to open deploy_block.txt: Os { code: 2, kind: NotFound, message: "No such file or directory"
```

## Expected Behaviour

The binary should run.

## Steps to resolve

Make better instruction

First you prompt to `cd ..` and then `lightouse [...]`. But the path should be `.target/release/bin/lighthouse`
Which made me convinced that nobody actually followed this tutorial and that the author just copy pasted some commands somebody sent him, but out of context.
So you have to do step by step tutorial, with each new instruction being valid in the context it will be executed by the user following the guide.

**Comment by pawanjay176** [comment]
Hey @tdelabro sorry for the trouble. 
We have baked in the kiln config in the kiln branch so you can use the `--network kiln` flag and don't need to bother with specifying the right `testnet-dir`.

So the command should be
```
lighthouse \
          --spec mainnet \
          --network kiln \
          --debug-level info \
          beacon_node \
          --datadir ./testnet-lh1 \
          --eth1 \
          --http \
          --http-allow-sync-stalled \
          --metrics \
          --merge \
          --execution-endpoints http://127.0.0.1:8551 \
          --enr-udp-port=9000 \
          --enr-tcp-port=9000 \
          --discovery-port=9000 \
          --jwt-secrets="/tmp/jwtsecret"
```

I'll get the hackmd updated. Thanks for bringing this to our attention.

**Comment by tdelabro** [comment]
Hey,
Thanks a lot for taking the time to fix this. In the meantime this guide was release:https://github.com/remyroy/ethstaker/blob/main/merge-devnet.md
It's for linux but it's no problem if you launch the binary manually instead of using services.
