### ISSUE TITLE
Prometheus beacon parse error "second HELP line for metric name "gossipsub_accepted_messages_per_topic"

### ISSUE THREAD

**Issue by m0n5t3r** [sigp/lighthouse#3087]
## Description

Parsing metrics from the beacon with the telegraf prometheus input fails with 

```
E! [inputs.prometheus] Error in plugin: error reading metrics for http://127.0.0.1:5054/metrics: reading text format failed: text format parsing error in line 2632: second HELP line for metric name "gossipsub_accepted_messages_per_topic"
```
Apparently this is an error, and a quick `curl | awk` confirms the said `HELP` line appears twice (also, the `TYPE` line for the same metric appears twice - the rest of the metrics are fine

```
$ curl -s http://127.0.0.1:5054/metrics | awk '$1 == "#" { counters[$2 " " $3] += 1}; END { for(label in counters){ if(counters[label] > 1) print label " " counters[label]; } }'
HELP gossipsub_accepted_messages_per_topic 2
TYPE gossipsub_accepted_messages_per_topic 2
```

## Version

Lighthouse v2.1.3-c3a793f
BLS library: blst-modern
SHA256 hardware acceleration: true
Specs: mainnet (true), minimal (false), gnosis (true)

## Present Behaviour

Can't get metrics into influxdb

## Expected Behaviour

Output whatever the prometheus standard says it should (I'm not a specialist)

## Steps to resolve

Check if separate metrics ended up with the same name due to copy & paste.

**Comment by pawanjay176** [comment]
Hey, thanks for the report. Made a PR to fix it upstream here https://github.com/libp2p/rust-libp2p/pull/2558

**Comment by paulhauner** [comment]
Closing as resolved via https://github.com/libp2p/rust-libp2p/pull/2558
