### ISSUE TITLE
import validator while VC is running ?

### ISSUE THREAD

**Issue by garyng2000** [sigp/lighthouse#3098]
currently it seems that when the VC is running, I cannot import new validators in the command line(db locked error). Is it possible to do this while VC is running ?

**Comment by michaelsproul** [comment]
You can't do it from the CLI, but you can use the HTTP API.

I'd recommend using the `POST /eth/v1/keystores` endpoint from the standard VC API:

https://ethereum.github.io/keymanager-APIs/#/Local%20Key%20Manager/ImportKeystores

To invoke that API you need to enable the API on the VC and supply the authorization token with the request, as described [here](https://lighthouse-book.sigmaprime.io/api-vc.html).

There's also a web UI that you can use to interact with that API: https://github.com/joaquim-verges/eth2-keymanager-frontend

---

There's also a Lighthouse-specific API which we haven't quite deprecated yet, but will probably deprecate eventually: https://lighthouse-book.sigmaprime.io/api-vc-endpoints.html#post-lighthousevalidatorskeystore. I'd recommend the standard API over that one.

**Comment by garyng2000** [comment]
thanks, I would look into the key manager API
