### ISSUE TITLE
Complete state transition logic

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#31]
TBD: https://github.com/ethereum/eth2.0-specs/blob/master/specs/casper_sharding_v2.1.md#state-recalculations-every-cycle_length-blocks

**Comment by paulhauner** [comment]
This is partially included in PR #66.

Active state "extensions" are supported (adding to the active state throughout a cycle), however crystallized state transitions are not yet implemented.

**Comment by ralexstokes** [comment]
I'm working on some of this if anyone needs to coordinate work w/ what i'm doing

**Comment by paulhauner** [comment]
Addressed in #180
