### ISSUE TITLE
No version info in homebrew package

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3102]
The homebrew package builds without the full git sources, which leads to its version showing as `Lighthouse unknown`. We should work out a way to inject the version from homebrew, or switch homebrew to use git (I suspect they won't want to do this due to the increased size)

**Comment by ackintosh** [comment]
How about using `env!("CARGO_PKG_VERSION")` as [the fallback](https://github.com/sigp/lighthouse/blob/aa72088f8fc91d41106a8afce7a0179cde64ce5d/common/lighthouse_version/src/lib.rs#L20)?

I will file a PR if it looks good to you. 😃

**Comment by realbigsean** [comment]
I think this would result in us displaying the version of the `lighthouse_version` crate, which is `0.1.0` right now.. but maybe we should actually track this version with our lighthouse release version? Would just need to add it to the `change_version.sh` script

**Comment by ackintosh** [comment]
I noticed that the `change_version.sh` script does the replacing below:

https://github.com/sigp/lighthouse/blob/46a06069c605842111d68b85b3e9aeea1974e202/scripts/change_version.sh#L34

the `VERSION_CRATE` variable points `lighthouse_version/src/lib.rs`:

https://github.com/sigp/lighthouse/blob/46a06069c605842111d68b85b3e9aeea1974e202/scripts/change_version.sh#L17

---

Therefore we don't need to use `env!("CARGO_PKG_VERSION")`, just hard code the version number. 💡 

```diff
pub const VERSION: &str = git_version!(
    args = [
        "--always",
        "--dirty=+",
        "--abbrev=7",
        // NOTE: using --match instead of --exclude for compatibility with old Git
        "--match=thiswillnevermatchlol"
    ],
    prefix = "Lighthouse/v2.2.1-",
-   fallback = "unknown"
+   fallback = "Lighthouse/v2.2.1" // Note: unlike `prefix`, the trailing hyphen was striped.
);
```
