### ISSUE TITLE
Gnosis Client Inter-Op issue?

### ISSUE THREAD

**Issue by beegmon** [sigp/lighthouse#3111]
## Description

Lighthouse v2.1.5 validators running via the sigp docker container, Lighthouse beacon client via sigp docker container, and GBC Prysm beacon client -- https://github.com/gnosischain/gbc-prysm.

The lighthouse beacon client and validators are configured with --network gnosis and the gbc pysm client is configured using this config.yaml file per the gnosis node operator docs -- https://github.com/gnosischain/prysm-launch/blob/master/config/config.yml.

## Present Behaviour

Lighthouse validators when connecting to the GBC prysm beceacon client log the following error

`Mar 22 21:02:14.004 ERRO The minimal/mainnet spec type of the beacon node does not match the validator client. See the --network command., endpoint: http://prysm.chain:8080/`

When digging into the chain specs reported by the beceaon API from each beacon client they appear to differ significantly:

AAA is the lighthouse chain spec, BBB is the GBC prysm chain spec

`n [26]: aaa.difference(bbb)
Out[26]: 
{('BELLATRIX_FORK_VERSION', '0x02000064'),
 ('DEPOSIT_CONTRACT_ADDRESS', '0x0b98057ea310f4d31f2a452b414647007d1645d9'),
 ('PRESET_BASE', 'gnosis'),
 ('SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY', '128'),
 ('TERMINAL_TOTAL_DIFFICULTY',
  '115792089237316195423570985008687907853269984665640564039457584007913129638912')}

In [27]: bbb.difference(aaa)
Out[27]: 
{('BELLATRIX_FORK_VERSION', '0x02000000'),
 ('DEPOSIT_CONTRACT_ADDRESS', '0x0B98057eA310F4d31F2a452B414647007d1645d9'),
 ('DOMAIN_CONTRIBUTION_AND_PROOF', '0x09000000'),
 ('DOMAIN_SYNC_COMMITTEE', '0x07000000'),
 ('DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF', '0x08000000'),
 ('INACTIVITY_PENALTY_QUOTIENT_MERGE', '16777216'),
 ('MIN_ANCHOR_POW_BLOCK_DIFFICULTY', '4294967296'),
 ('MIN_SLASHING_PENALTY_QUOTIENT_MERGE', '32'),
 ('PRESET_BASE', 'mainnet'),
 ('PROPORTIONAL_SLASHING_MULTIPLIER_MERGE', '3'),
 ('PROPOSER_WEIGHT', '8'),
 ('SHARDING_FORK_EPOCH', '18446744073709551615'),
 ('SHARDING_FORK_VERSION', '0x03000000'),
 ('SYNC_COMMITTEE_SUBNET_COUNT', '4'),
 ('SYNC_REWARD_WEIGHT', '2'),
 ('TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE', '16'),
 ('TERMINAL_TOTAL_DIFFICULTY', '0'),
 ('TIMELY_HEAD_FLAG_INDEX', '0x02'),
 ('TIMELY_HEAD_WEIGHT', '14'),
 ('TIMELY_SOURCE_FLAG_INDEX', '0x00'),
 ('TIMELY_SOURCE_WEIGHT', '14'),
 ('TIMELY_TARGET_FLAG_INDEX', '0x01'),
 ('TIMELY_TARGET_WEIGHT', '26'),
 ('TRANSITION_TOTAL_DIFFICULTY', '0'),
 ('WEIGHT_DENOMINATOR', '64')}`

This appears to the root of the issue in regards to the lighthouse validators not seeing the GBC prysm beacon client as being on the right net. I am unsure which spec is correct, of if these specs are different per client but correct for their operation on the gnosis mainnet and thus at present lighthouse validators cannot use GBC prysm as a beacon endpoint and vice versa for gnosis operations.

## Expected Behaviour

Chain specs should likely match I would think, and ideally a node operator should be able to use the lighthouse validator with a GBC prysm beacon endpoint.

**Comment by michaelsproul** [comment]
I think it makes sense to use a different name for the Gnosis preset, as the Gnosis preset is not equal to the mainnet preset due to having changed `SLOTS_PER_EPOCH` to 16: https://github.com/sigp/lighthouse/blob/stable/consensus/types/presets/gnosis/phase0.yaml

If Prysm could update their Gnosis config to use `PRESET_BASE: "gnosis"` then I think the Lighthouse VC would be able to interop with the Prysm BN once more.

The GBC devs should also choose and standardise on a value for `BELLATRIX_FORK_VERSION`, as that will be approaching kind of soon.

cc @k1rill-fedoseev @terencechain

**Comment by michaelsproul** [comment]
Closing as stale, let us know if this is still an issue
