### ISSUE TITLE
Adding `charset` header in a request results in incorrect error for some REST API requests

### ISSUE THREAD

**Issue by marioevz** [sigp/lighthouse#3115]
## Description

Adding `charset` header in a request results in incorrect error for some REST API requests, e.g.:

Requests:
`curl -X GET http://<BEACON_IP>:4000/eth/v2/beacon/blocks/head -H "Content-Type: application/json; charset=utf-8" -H "Accept: application/json; charset=utf-8"`
`curl -X GET http://<BEACON_IP>:4000/eth/v2/beacon/blocks/head -H "Content-Type: application/json; charset=utf-8" -H "Accept: charset=utf-8"`
return error:
`{"code":400,"message":"BAD_REQUEST: Unsupported endpoint version: v2","stacktraces":[]}`

While request:
`curl -X GET http://<BEACON_IP>:4000/eth/v2/beacon/blocks/head -H "Content-Type: application/json; charset=utf-8" -H "Accept: application/json"`

returns no error and returns the head block successfully.

## Version

Docker: sigp/lighthouse:latest-unstable

## Present Behaviour

`{"code":400,"message":"BAD_REQUEST: Unsupported endpoint version: v2","stacktraces":[]}`

Is not the correct response expected

## Expected Behaviour

Block should be successfully returned regardless of the `charset` header.

**Comment by michaelsproul** [comment]
Thanks for reporting! This is indeed an issue with our parsing of `Accept` directives. We have another really similar issue reportedly recently, so we'll track progress there: https://github.com/sigp/lighthouse/issues/3114
