### ISSUE TITLE
Re-write RPC over Libp2p

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#312]
## Description

The current implementation mixes the RPC commands with the lower level libp2p protocol. This was originally done to perform the SSZ decoding as we receive packets. 

It is cleaner and has better logic separation to perform the decoding and RPC logic in its own module which deals with the associated functions, separating it from the networking stack.

This needs a re-write and re-design.

**Comment by pawanjay176** [comment]
would love to help out on this issue

**Comment by AgeManning** [comment]
Oh cool. This one is tricky because it refers to the libp2p RPC spec (RPC across the network for nodes to directly communicate) which is still being debated. 
I've written an initial version, and am not happy with it. The re-write will need to happen after I jig around with the rest of the networking. 

I'll let you know when its ready to re-implement. 

In the meantime, we still need to write and define the standard RPC interface that links the node locally to the validator client. I'll have a look into that and make some clear issues surrounding it :)

**Comment by paulhauner** [comment]
Closing as this is now irellevant
