### ISSUE TITLE
Strip newline from jwt secret (or better error)

### ISSUE THREAD

**Issue by lightclient** [sigp/lighthouse#3128]
## Description

When starting `lighthouse` with a jwt secret that ends in a new line (e.g. `0x1234..5678\n`), I get the following error

```console
CRIT Failed to start beacon node             reason: unable to start execution layer endpoints: InvalidJWTSecret("Invalid hex s
tring: OddLength")
```

It seems that it would be better to either i) strip this or ii) suggest the user remove the trailing newline. For additional context, `go-ethereum` is happy to strip the newline and carry on about it's day.

## Version

`unstable`

**Comment by pawanjay176** [comment]
Thanks for the issue. I thought we already strip newlines but apparently we don't. 
Will make a PR.
