### ISSUE TITLE
Restrict sync committee messages to optimistic blocks

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3151]
## Description

The [optimistic sync spec](https://github.com/ethereum/consensus-specs/blob/dev/sync/optimistic.md) declares:

> An optimistic validator MUST NOT participate in sync committees (i.e., sign across the DOMAIN_SYNC_COMMITTEE, DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF or DOMAIN_CONTRIBUTION_AND_PROOF domains).

We need to ensure that a Lighthouse BN/VC pair will not sign sync committee messages that reference an optimistic `beacon_block_root`.

## Steps to resolve

The first change is to return an error in [`BeaconChain::get_aggregated_sync_committee_contribution`](https://github.com/sigp/lighthouse/blob/bac7c3fa544495a257722aaad9cd8f72fee2f2b4/beacon_node/beacon_chain/src/beacon_chain.rs#L1451-L1459) whenever the `sync_contribution` being return references an optimistic `beacon_block_root` (see #3140 to see how this was done for attestations).

The second, more complicated change is to stop the VC from producing a `SyncCommitteeMessage` whenever that block references an optimistic head:

https://github.com/sigp/lighthouse/blob/bac7c3fa544495a257722aaad9cd8f72fee2f2b4/validator_client/src/sync_committee_service.rs#L233-L241

We can't just refuse to accept the already-signed `SyncCommitteeMessage` at the BN HTTP API for two reasons:

- The message is dangerous and should never be signed, we need to prevent it being signed before it is submitted to the BN.
- We don't want to restrict *already signed* messages, since we assume that the VC must have good advice from some other BN that the `beacon_block_root` is valid (e.g. when using multiple BNs).

I can see two options, both are blocked on #3070:

1. Pass the `execution_optimistic` values around with the [sync duties](https://github.com/sigp/lighthouse/blob/bac7c3fa544495a257722aaad9cd8f72fee2f2b4/validator_client/src/duties_service.rs#L112) in the VC
    - Pros: doesn't require extra calls to the BN.
    - Cons: it's hard to ensure the `execution_optimistic` are up-to-date without frequent polling.
2. Call [`/eth/v1/beacon/headers`](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlockHeaders) before producing the `SyncCommitteeMessage` and checking the `execution_optimistic` value before signing
    - Pros: always gets the latest info.
    - Cons: requires an extra call.
    
I'm leaning towards (2), since it's the easiest to implement and gives us the most up-to-date info. The call to `beacon/headers` should be nice and fast, so I don't think it's too much of a bottleneck.

**Comment by paulhauner** [comment]
@michaelsproul I know you've done a lot of work on sync committees, so I'd be interested to know if what I've written makes sense and if you have a better suggestion? :pray: :relaxed:

**Comment by michaelsproul** [comment]
Looks good, and I favour option (2) as well. I don't even think we need an extra request because I think we could read the optimistic status when we fetch the block root here:

https://github.com/sigp/lighthouse/blob/db0beb51788576565cef9534ad9490a4a498b544/validator_client/src/sync_committee_service.rs#L177-L187

**Comment by macladson** [comment]
Implemented in #3191
