### ISSUE TITLE
VC metrics for number of beacon nodes

### ISSUE THREAD

**Issue by fireduck64** [sigp/lighthouse#3154]
## Description

For this log line, are these numbers in the metrics as well?  I can't find them.

Apr 08 17:25:17.000 INFO Connected to beacon node(s)             synced: 4, available: 4, total: 4, service: notifier

I'd like to set an alert on number of beacon nodes.

## Version

Lighthouse/v2.2.0-bac7c3f (from docker)

## Present Behaviour

The data line appears in the logs but not the metrics (unless I just missed it)

## Expected Behaviour

I would like the number of beacon nodes to appear in the vc metrics (synced, available, total)

**Comment by paulhauner** [comment]
That seems like a good idea and fairly simple to implement!

**Comment by macladson** [comment]
Resolved by #3193
