### ISSUE TITLE
Check `fee_recipient` returned from EE

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3156]
## Description

It's possible that an EE will return a different fee recipient to the one provided (the `suggested_fee_recipient`) in [`get_payload`](https://github.com/sigp/lighthouse/blob/bac7c3fa544495a257722aaad9cd8f72fee2f2b4/beacon_node/execution_layer/src/lib.rs#L563-L702). Whilst this is legal behaviour, I think it would make sense to raise some sort of log whenever the EE returns a different value. It might help users detect when their fees are being hijacked.

I'm not sure the log level, I'm tempted to go with an `ERRO` but I'm open to suggestion.

**Comment by michaelsproul** [comment]
IMO we might want a flag that prevents the VC from signing any block with a divergent fee recipient. This would apply to blocks from builders too, which I think the check from #3202 does not. _Filtering_ available blocks by their fee recipient would be superior, but I don't think the current builder APIs really allow that (unless you use multiple relays?).

(I've been thinking about this in the context of MEV smoothing: https://twitter.com/sproulM_/status/1548900364342009857)

**Comment by realbigsean** [comment]
> IMO we might want a flag that prevents the VC from signing any block with a divergent fee recipient

I agree! 

If we add this flag, we can make a fee recipient mismatch on a block from the builder API a `BlockError::Recoverable` error in the block service, so we will use full block endpoints as a fallback (a local execution engine, which will probably respect the fee recipient).

> Filtering available blocks by their fee recipient would be superior, but I don't think the current builder APIs really allow that (unless you use multiple relays?).

Yeah, this one sounds like it'd be a good feature in `mev-boost` though.

**Comment by paulhauner** [comment]
Resolved via #3363 :tada:
