### ISSUE TITLE
`eth2_hashing` v0.3.0 is not published

### ISSUE THREAD

**Issue by ackintosh** [sigp/lighthouse#3166]
## Description

[eth2_hashing - Rust](https://docs.rs/eth2_hashing/latest/eth2_hashing/)

Current latest version of `eth2_hashing` is [v0.3.0](https://github.com/sigp/lighthouse/blob/stable/crypto/eth2_hashing/Cargo.toml#L3), but that is not published on crates.io.

I noticed that a release procedure is defined in the [publish-crate](https://github.com/sigp/lighthouse/blob/stable/.github/workflows/publish-crate.yml#L12) workflow in this repo.

I would appreciate it if you can publish the latest version, because I want use the version in my personal project. 😃 

(Update)
I noticed that these are also not published:
- tree_hash = "0.4.1"
- eth2_serde_utils = "0.1.1"
- eth2_ssz = "0.4.1"
- eth2_ssz_types = "0.2.2"

**Comment by ackintosh** [comment]
Currently, this is no longer an issue for me. 😃

**Comment by mksh** [comment]
Note for anyone who could be stumbled upon this: to use customized Lighthouse version of crates, you need to have `patch.crates-io` section in `Cargo.toml` to point to Lighthouse source, as described in https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section

e.g.

```
[dependencies]
eth2_hashing = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
eth2_wallet = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}

[patch.crates-io]
eth2_hashing = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
eth2_serde_utils = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
eth2_ssz = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
tree_hash = { git = "https://github.com/sigp/lighthouse", rev = "df51a73272489fe154bd10995c96199062b6c3f7"}
```
