### ISSUE TITLE
`Peer sent invalid block in single block` seems to cause beacon node desync (malicious ?)

### ISSUE THREAD

**Issue by GerardBri** [sigp/lighthouse#3169]
## Description

My node seems to receive 28 invalid block, and some minutes after, my node is desynced :(
Since March~April, my node get more and more desync/crash and i have to purge-db and restart all the node, so this time, i keep the logs, and try to understand why :)

the typical log which seems to be the root cause is : 
```
WARN Peer sent invalid block in single block lookup, peer_id: 16Uiu2HAmBR1wNeooCA4PpnmAqH7K1ECkMqwMrqMZKvXFnUWbeeb8, error: StateRootMismatch { block: 0x2f6d4166f1b0c705d02d31603b96b9fe818eede3e6187b81bc44a0d32f301849, local: 0x2b7b7b26a2932990eb8eab627c80c153e40873b423e3c4bcd5b520eced91aefe }, root: 0xdefa…3529, service: sync
```

## Version

Release from github : **Lighthouse v2.2.1-aa72088**

## Present Behaviour

in summary in logs, i've got this : 

- **everything is fine**
```
INFO New block received
INFO Synced
```

- **bad block received**
_\~ May 05 05:08_
```
WARN Peer sent invalid block in single block lookup (x28)
```

- **beacon node alert on sync stated**
_\~ May 05 05:14_
```
INFO Sync state updated                      new_state: Syncing Head Chain, old_state: Synced, service: sync
WARN Batch failed to download. Dropping chain scoring peers, batch_epoch: 116915
INFO Syncing                                 est_time: --, distance: 34 slots (6 mins)
```
these **6 mins** match exactly time of the bad block received

- **API request dying**
after a distance of 256 slots failing to sync, i've got WARN on HTTP API request like that
```
WARN Error processing HTTP API request       method: POST, path: /eth/v1/validator/duties/attester/116924, status: 503 Service Unavailable, elapsed: 9.228091ms
WARN Error processing HTTP API request       method: GET, path: /eth/v1/validator/duties/proposer/116924, status: 503 Service Unavailable, elapsed: 10.509452ms
WARN Error processing HTTP API request       method: POST, path: /eth/v1/validator/duties/attester/116925, status: 503 Service Unavailable, elapsed: 53.445µs
```

➡️ my node stop syncing, and then i couldn't validate any new blocks

## Expected Behaviour

i should keep syncing blocks, even if i receive bad/invalid/malicious blocks

## Steps to resolve

I've just restart the node with a `purge-db` parameter and everything is well synced after.

## ❓⚠️ Is it possible that someone try to hack the PoS consensus layer with malicious blocks or network packets ?
By this way, i think it's possible to identify an IP with new failed validators, so attackers could get a table with IP <=> validators and keep growing this table to throw a full attack later ?

### full log
🗒️ [attaq.log](https://github.com/sigp/lighthouse/files/8630557/attaq.log)

**Comment by pawanjay176** [comment]
Hey @GerardBri can you share the debug logs from `$datadir/beacon/logs/beacon.log`?

**Comment by GerardBri** [comment]
sure @pawanjay176 ,

full logs are in attachment below (truncated, because it's heavy, it starting from 03:00) and here is a summary of the first bad block received, i think
first bad blocks start at **03:07:47.396** 

```
May 05 03:07:47.396 INFO New block received, root: 0xdefaf9755ead4b7b3829374eac750b3c24d63a797f7d75762aae387f3a903529, slot: 3741337, module: network::beacon_processor::worker::gossip_methods:721
May 05 03:07:47.444 DEBG Invalid gossip beacon block, block slot: 3741337, block root: 0xdefaf9755ead4b7b3829374eac750b3c24d63a797f7d75762aae387f3a903529, outcome: Err(InvalidSignature), module: network::beacon_processor::worker::gossip_methods:947
May 05 03:07:47.444 DEBG Peer score adjusted, score: -5.00, peer_id: 16Uiu2HAm6jLQLBPkKGWZxeDL1pC8AB7V9GS4FrZexJN2TxVgmZMB, msg: bad_gossip_block_ssz, service: libp2p, module: lighthouse_network::peer_manager::peerdb:537
May 05 03:07:47.461 DEBG Searching for block, block: 0xdefa…3529, peer_id: 16Uiu2HAmL3CCckemM1BFAcZfcRPatmBNwQb1oeLSyDcke3TjJF3D, service: sync, module: network::sync::block_lookups:83
May 05 03:07:47.981 DEBG Missed snapshot cache, block_delay: Some(391.605168ms), parent_root: 0xc591cbe17318c7cb530d02cc73ae9af9bd22af1a3d3f2bbf0a83d516d5743395, parent_slot: 3741336, slot: 3741337, service: beacon, module: beacon_chain::block_verification:1592
May 05 03:07:48.375 WARN Peer sent invalid block in single block lookup, peer_id: 16Uiu2HAmL3CCckemM1BFAcZfcRPatmBNwQb1oeLSyDcke3TjJF3D, error: StateRootMismatch { block: 0x2f6d4166f1b0c705d02d31603b96b9fe818eede3e6187b81bc44a0d32f301849, local: 0x2b7b7b26a2932990eb8eab627c80c153e40873b423e3c4bcd5b520eced91aefe }, root: 0xdefa…3529, service: sync, module: network::sync::block_lookups:422
May 05 03:07:48.382 DEBG Sync reporting peer, action: Mid Tolerance Error, peer_id: 16Uiu2HAmL3CCckemM1BFAcZfcRPatmBNwQb1oeLSyDcke3TjJF3D, service: sync, module: network::sync::network_context:230
May 05 03:07:48.383 DEBG Peer score adjusted, score: -5.00, peer_id: 16Uiu2HAmL3CCckemM1BFAcZfcRPatmBNwQb1oeLSyDcke3TjJF3D, msg: single_block_failure, service: libp2p, module: lighthouse_network::peer_manager::peerdb:537
May 05 03:07:48.926 DEBG Missed snapshot cache, block_delay: Some(391.605168ms), parent_root: 0xc591cbe17318c7cb530d02cc73ae9af9bd22af1a3d3f2bbf0a83d516d5743395, parent_slot: 3741336, slot: 3741337, service: beacon, module: beacon_chain::block_verification:1592
```

my previous logs are time with GMT+2, here we've got GMT

### debug log 
🗒️ starting from 03:00:00 : [mybeacon.log.zip](https://github.com/sigp/lighthouse/files/8631187/mybeacon.log.zip)

**Comment by pawanjay176** [comment]
Thank you! Can you share your hardware setup as well? Looks like your node did the state transition correctly the second time around (after you purged the db) so I'm guessing some sort of temporary db corruption.

**Comment by GerardBri** [comment]
well, there isn't the purge in the log, i've restart with `--purge-db` only hours after :) 

the beacon node run in a proxmox VM with 4 full CPU, 8GiB RAM, 300 GiB disk
default BIOS : SeaBIOS, 
default machine : i440fx,
default SCSI controller : VirtIO SCSI,
QEMU guest agent : enabled

**Comment by GerardBri** [comment]
In addition, i have all the grafana dashboard with prometheus records
some captures here could help perhaps
(we can see starting issue at **\~ 05:20** (03:30 in UTC logs) and the purge db / restart at **\~ 11:00*

![screen_2022-05-05 16-03-10](https://user-images.githubusercontent.com/83615406/166942987-c275c1a3-ec40-45c4-b7f1-64680658279e.png)
![screen_2022-05-05 16-05-23](https://user-images.githubusercontent.com/83615406/166943218-e980719e-fbd3-43fe-9723-b9caf83423f2.png)
![screen_2022-05-05 16-05-02](https://user-images.githubusercontent.com/83615406/166943311-87a52168-c641-445f-86bf-77db5ce5ff87.png)

**Comment by michaelsproul** [comment]
Hi @GerardBri,

There's definitely something very unusual going on with your node. This is the sort of issue we only see a handful of times per year, and usually it's very difficult to get to the root cause.

Some basic things to start with:

1. Try running a memory test within the VM. You could use [memtester](https://linux.die.net/man/8/memtester), or the memory-intensive mode of [Prime95](https://www.mersenne.org/download/). Instructions on how to run them are available online.
2. Try running a memory test on the host. The best tool for testing memory is [Memtest86+](https://www.memtest.org/), which needs to be booted directly (you could maybe try running it in the VM, but I think you'd get better results running it on the host).
3. Check the integrity of your filesystems using `fsck`.

If none of the above show any issues, then we can start digging into more exotic causes. We've seen a similar issue in the past caused by a bug in Proxmox VM's handling of native instructions. You could try disabling all native instruction flags in your Proxmox VM settings, as shown [here](https://pve.proxmox.com/wiki/Qemu/KVM_Virtual_Machines#qm_cpu). In particular, the instruction we had issues with in the past was AES-NI, although I think your issues are more likely related to hashing ([SHA native instructions](https://en.wikipedia.org/wiki/Intel_SHA_extensions)) or signature verification (which uses ADX). You will need to use a [portable](https://lighthouse-book.sigmaprime.io/installation-binaries.html#portability) build of Lighthouse as well to retain compatibility with the basic CPU.

Let us know if that helps, and we can go from there

**Comment by GerardBri** [comment]
Thanks for your help @michaelsproul :pray: 
Well i've run `Memtest86+` on the host while 1 hour without any issues.
So i decided to check proxmox VM settings, and the cpu was set as a `host` cpu, so i've changed to default `kvm64`, we'll see if it's better in future

**Comment by GerardBri** [comment]
Hello there ! 
My crash still occur :'( 

My investigation was the following : 
- running `Memtest86+` :heavy_check_mark: 
- change the proxmox cpu type from `host` to default `kvm64` :heavy_check_mark: 
- use the portable version of lighthouse Lighthouse/v2.2.1-aa72088 :heavy_check_mark: 

But i've got still the crash with this message **Peer sent invalid block in single block** :negative_squared_cross_mark: 


the first lines of logs in the last boot :
```
May 07 10:57:07 beacon-node-prod systemd[1]: Started eth2 beacon chain service.
May 07 10:57:08.120 INFO Logging to file                         path: "/var/lib/lighthouse/beacon/logs/beacon.log"
May 07 10:57:08.127 INFO Lighthouse started                      version: Lighthouse/v2.2.1-aa72088
May 07 10:57:08.127 INFO Configured for network                  name: mainnet
May 07 10:57:08.137 INFO Data directory initialised              datadir: /var/lib/lighthouse
May 07 10:57:08.137 WARN Running HTTP server on port 5052
May 07 10:57:08.137 INFO Deposit contract                        address: 0x00000000219ab540356cbb839cbe05303d7705fa, deploy_block: 11184524
May 07 10:57:11.229 INFO Hot-Cold DB initialized                 split_state: 0xcdd3dde3e88641dbef6eed69b19c5b8ae7d7b04d67b2a2344fb1bed682e3303a, split_slot: 3757984, service: freezer_db
May 07 10:57:11.389 INFO Starting beacon chain                   method: resume, service: beacon
May 07 10:57:50.606 INFO Block production enabled                method: json rpc via http, endpoints: ["https://mainnet.infura.io/", "https://eth-mainnet.alchemyapi.io/", "https://nodes.mewapi.io/", "https://mainnet.eth.cloud.ava.do/"]
May 07 10:57:52.244 INFO Beacon chain initialized                head_slot: 3758075, head_block: 0x214e…196c, head_state: 0x5c71…eee7, service: beacon
May 07 10:57:52.256 INFO Timer service started                   service: node_timer
May 07 10:57:52.257 INFO UPnP Attempting to initialise routes    service: UPnP
May 07 10:57:52.274 INFO Libp2p Starting                         bandwidth_config: 3-Average, peer_id: XXXXXXXXXXX, service: libp2p
May 07 10:57:52.285 INFO ENR Initialised                         tcp: Some(9000), udp: None, ip: None, id: 0x77ea..2a88, seq: 1020, enr: enr:-K-4QC....., service: libp2p
May 07 10:57:52.291 INFO Listening established                   address: /ip4/0.0.0.0/tcp/9000/p2p/XXXXXXXXXXX, service: libp2p
May 07 10:57:52.352 INFO HTTP API started                        listen_address: 127.0.0.1:5052
May 07 10:57:52.354 INFO Metrics HTTP server started             listen_address: 0.0.0.0:5054
May 07 10:57:52.979 INFO Sync state updated                      new_state: Synced, old_state: Stalled, service: sync
May 07 10:57:52.982 INFO Subscribed to topics                    topics: ["/eth2/afcaaba0/beacon_block/ssz_snappy", "/eth2/afcaaba0/beacon_aggregate_and_proof/ssz_snappy", "/eth2/afcaaba0/voluntary_exit/ssz_snappy", "/eth2/afcaaba0/proposer_slashing/ssz_snappy", "/eth2/afcaaba0/attester_slashing/ssz_snappy", "/eth2/afcaaba0/sync_committee_contribution_and_proof/ssz_snappy"], service: network
May 07 10:57:59.631 INFO Started monitoring validator            validator: XXXX, pubkey: 0x......, service: val_mon
May 07 10:58:02.350 INFO UPnP not available                      error: IO error: Resource temporarily unavailable (os error 11), service: UPnP
May 07 10:58:03.668 INFO New RPC block received                  hash: 0x1980…49af, slot: 3758076
May 07 10:58:05.001 INFO Synced                                  slot: 3758088, block:    …  empty, epoch: 117440, finalized_epoch: 117437, finalized_root: 0xddbb…d294, exec_hash: n/a, peers: 9, service: slot_notifier
```

In [journalctl-log-2022-06-11.txt](https://github.com/sigp/lighthouse/files/8884094/journalctl-log-2022-06-11.txt), the first log of **Peer sent invalid block in single block lookup** occurs at **07:24:01.338** 

Then the process crash with 
**CRIT Beacon block processing error           error: DBError(SszDecodeError(OffsetsAreDecreasing(4125900))), service: beacon**

I've added the `$datadir/beacon/logs/beacon.log` in the same time window

[detailed-beacon.log](https://github.com/sigp/lighthouse/files/8884095/detailed-beacon.log)

this issue is annoying because, i've had to purge the db everytime
Thanks for your help !

**Comment by paulhauner** [comment]
I'm closing this one due to inactivity, please feel free to re-open if the issue persists.
