### ISSUE TITLE
Test committee building with registry update

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#317]
## Description

Add a new test case for committee building.

## Details

The specification has a [`get_crosslink_committees_at_slot`](https://github.com/ethereum/eth2.0-specs/blob/v0.5.0/specs/core/0_beacon-chain.md#get_crosslink_committees_at_slot) function with returns a list of crosslink committees for that slot.

Our implementation is a little different -- we build all the committees for all the slots in an epoch at the same time then cache them all. Or function named `get_crosslink_committees_at_slot` just reads the cache.

Our cache implementation is [here](https://github.com/sigp/lighthouse/blob/733722ea0d28b548a25f3476b8d5b464417d1be8/eth2/types/src/beacon_state/epoch_cache.rs#L29) and it's built using the [`EpochCrosslinkCommitteesBuilder`](https://github.com/sigp/lighthouse/blob/733722ea0d28b548a25f3476b8d5b464417d1be8/eth2/types/src/beacon_state/epoch_cache.rs#L200).

In our [testing](https://github.com/sigp/lighthouse/blob/733722ea0d28b548a25f3476b8d5b464417d1be8/eth2/types/src/beacon_state/epoch_cache/tests.rs#L99-L149) of the `EpochCache` we don't have a test case that covers the committee that's generated for `RelativeEpoch::NextWithRegistryChange` (we only have current epoch, previous epoch and next _without_ registry change).

## Steps to resolve

- Manually generate the inputs to [`setup_sane_cache_test`](https://github.com/sigp/lighthouse/blob/733722ea0d28b548a25f3476b8d5b464417d1be8/eth2/types/src/beacon_state/epoch_cache/tests.rs#L67) for the `RelativeEpoch::NextWithRegistryChange` scenario and ensure our implementation is sane.

Note: there are two paths when building the next epoch _with_ a registry update. The `if` statement that creates that fork is [here](https://github.com/sigp/lighthouse/blob/733722ea0d28b548a25f3476b8d5b464417d1be8/eth2/types/src/beacon_state/epoch_cache.rs#L256-L257).

**Comment by paulhauner** [comment]
@g-r-a-n-t I heard you might be interested in this :)

**Comment by g-r-a-n-t** [comment]
Hey @paulhauner, you've heard right. Can pick this up and start working on it over the weekend.

**Comment by paulhauner** [comment]
Awesome, let me know if I can help!

**Comment by paulhauner** [comment]
Closing this as spec 0.6.0 does not have the with/without registry change path.
