### ISSUE TITLE
Don't mark EL as offline if non-essential API call fails

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3176]
## Description

If payload reconstruction or another non-critical call to the EL fails I think we should avoid marking the EL as offline. Currently there is an incompatibility with ethereumjs that results in Lighthouse & ethereumjs stalling due to the inability to reconstruct payloads. IMO we should keep running and issuing forkchoiceUpdated/notifyNewPayload messages while ignoring the getBlockByHash failures.

The relevant ethereumjs issue is https://github.com/ethereumjs/ethereumjs-monorepo/issues/1880

## Version

Lighthouse v2.2.1 with #3157

**Comment by paulhauner** [comment]
Sounds like a good idea. Once we implement #3118, we might not even track the online/offline state at all! We'll just try anything anytime and see how it pans out.

**Comment by paulhauner** [comment]
This should be resolved in #3324

**Comment by paulhauner** [comment]
Resolved in #3324
