### ISSUE TITLE
Request to add support for RPC API: /eth/v2/debug/beacon/states/

### ISSUE THREAD

**Issue by z3n-chada** [sigp/lighthouse#3187]
## Description

There is currently no support for the /eth/v2/debug/beacon/states API call.

## Version

all (currently built on unstable:db8a6f81ea25ceaca1842e030f9dd1331a5ac28b)

## Present Behaviour

Requests to this endpoint over http result in: 

"BAD_REQUEST: Unsupported endpoint version: v2"

## Expected Behaviour

A dump of the beaconstate object.

## Steps to resolve

Implement this API for eth/v2

**Comment by michaelsproul** [comment]
Lighthouse does already implement the API at v2, you can see the code for that [here](https://github.com/sigp/lighthouse/blob/aa72088f8fc91d41106a8afce7a0179cde64ce5d/beacon_node/http_api/src/lib.rs#L1602-L1613).

However, our implementation is currently affected by two bugs which will cause it to return a 405 if a complex `Accept` header is provided, see https://github.com/sigp/lighthouse/issues/3114 and https://github.com/sigp/lighthouse/issues/3112. My guess is that your request is setting an accept header that Lighthouse doesn't parse correctly. It would be helpful to see the headers on your HTTP request to confirm this is why it's failing.

**Comment by michaelsproul** [comment]
I'm going to close this, please re-open if you have more info to indicate that it isn't a duplicate
