### ISSUE TITLE
Implement Dynasty Transitions

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#32]
TBD: https://github.com/ethereum/eth2.0-specs/blob/master/specs/casper_sharding_v2.1.md#dynasty-transition

**Comment by paulhauner** [comment]
This is semi-implemented here: https://github.com/sigp/lighthouse/blob/master/beacon_chain/validator_change/src/lib.rs

It's not complete as the specification isn't complete. Will close this so that when the spec is updated we can re-open.
