### ISSUE TITLE
Error after upgrade from 2.2.1 to 2.3.0 (Docker)

### ISSUE THREAD

**Issue by amaurer** [sigp/lighthouse#3230]
## Description

Changed the version in docker-compose.yml from 2.2.1 to 2.3.0, watched logs and saw failures. I changed back to 2.2.1 and beacon and validators started properly.

## Version
2.3.0

## Present Behaviour

```
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /cargo/registry/src/github.com-1ecc6299db9ec823/slog-async-2.7.0/lib.rs:303:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: slog_async::AsyncBuilder<D>::build
   4: environment::EnvironmentBuilder<E>::initialize_logger
   5: lighthouse::main::{{closure}}
   6: lighthouse::main
```

## Expected Behaviour

Upgrade from 2.2.1 without error

## Steps to resolve

- Synced mainnet beacon chain with validators on same node, both running 2.2.1
- Change version from 2.2.1 to 2.3.0 in docker-compose.yml on both validators and beacon
- Docker compose has depends_on : beacon for validators to start. 
- witness logs

**Comment by MysticRyuujin** [comment]
I got this same error on my validator going from 2.2.0 to 2.3.0

**Comment by MysticRyuujin** [comment]
Updating Docker and restarting fixed it

**Comment by pawanjay176** [comment]
This seems to be a consequence of us using `ubuntu:latest` as our base docker image which has some issues with the `clone3` syscalls on older docker engine versions https://docs.docker.com/engine/release-notes/#201010 . 

Updating your docker should fix it as @MysticRyuujin pointed out. We'll probably move to stabler base images in our dockerfile from next release onwards. Sorry for the trouble!

**Comment by amaurer** [comment]
Confirmed, upgraded docker from 19 to 20 and the instance started. Thanks.

**Comment by pablomendezroyo** [comment]
For anyone looking for a temporary fix, add the following to the `docker-compose.yml` file or find a way to add it to the Docker image provided by the lighthouse team.

This may entail security assumptions, make sure you are aware of them before implement it on production
```
    security_opt:
      - "seccomp:unconfined"
```
