### ISSUE TITLE
SSZ Length for bytesN

### ISSUE THREAD

**Issue by kirk-baird** [sigp/lighthouse#324]
## Description

SSZ List items are to be prepended with 4 bytes to show the length.
Should Address, Bitfield, PublicKey, Hash256, and Signature, AggregateSiganture have the length prepended?

## Present Behaviour

Currently the following prepend the length bytes:
- Bitfield (N bytes)
- Signature (96 bytes)
- AggregateSignature (96 bytes)
- PublicKey (48 bytes)

While the following types do not prepend length:
- Hash256 (32 bytes)
- Address (20 bytes)

## Expected Behaviour

My interpretation is that all of the types should have the lengths prepended. 
See https://github.com/ethereum/eth2.0-specs/issues/837 for a final answer.

## Steps to resolve

Following an answer to the above either add or remove length to the ssz encoding/decoding if required.

**Comment by kirk-baird** [comment]
The verdict is that any types with a fixed number of bytes can be considered tuples hence do not prepend the length e.g. Signatures, Addresses,...
Those with a variable number of bytes e.g. Bitfield will require the length to be prepended.

# TODO
Remove encoding/decoding of length from
- Signature
- Aggregate Signature
- PublicKey
- Any other types with fixed number of bytes
Ensure Bitfield and other variable length objects have length prepended.

**Comment by paulhauner** [comment]
Closing -- I understand this has been fixed.
