### ISSUE TITLE
Remove equivocating validators from fork choice

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3241]
## Description

The latest consensus spec includes a fortification of fork choice against attacks involving equivocating validators.

We should implement the changes as described in https://github.com/ethereum/consensus-specs/pull/2845 and the latest version of the fork choice spec: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/fork-choice.md

## Steps to resolve

* Update fork choice so that it tracks the set of equivocating indices
* Add a new version to the on-disk fork choice store so that it stores the equivocating indices. This will require a database schema upgrade (see https://github.com/sigp/lighthouse/tree/stable/beacon_node/beacon_chain/src/schema_change). We should also implement a database schema downgrade (it can simply drop the equivocating indices).
* Add the new `on_attester_slashing` handler to fork choice and wire it into the `beacon_processor`.

**Comment by michaelsproul** [comment]
I'll take this for v2.5.0

**Comment by paulhauner** [comment]
Resolved via #3371 :tada:
