### ISSUE TITLE
Update EF consensus tests to v1.2.0

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3242]
## Description

We should update the EF tests to v1.2.0-rc.1 which was recently released: https://github.com/ethereum/consensus-specs/releases/tag/v1.2.0-rc.1.

Most of the tests should pass without any modifications. We may need to skip a few fork choice tests until https://github.com/sigp/lighthouse/issues/3241 is implemented.

**Comment by michaelsproul** [comment]
Tentatively adding this for v2.5.0, as it's closely related to https://github.com/sigp/lighthouse/issues/3241

**Comment by paulhauner** [comment]
Resolved via #3371 :tada:
