### ISSUE TITLE
Ropsten testnet invalid ttd error.

### ISSUE THREAD

**Issue by MinwooJ** [sigp/lighthouse#3247]
## Description

The ropsten testnet ttd is changed to `50000000000000000` but when I run the geth node and connected latest stable version of lighthouse(v2.3.0), I get invalid ttd error from the engine api. I saw the PR(https://github.com/sigp/lighthouse/pull/3240) you have updated. When will this update be released for docker image? Or is there any running command to config ttd?

## Version

stable v2.3.0 (docker image)

## Present Behaviour

```
error: ServerMessage { code: -32000, message: "invalid ttd: execution 50000000000000000 consensus 0x152d02c7e14af6800000" } }]), service: exec
```

## Expected Behaviour

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
If you use the `:latest-unstable` tag for your docker images then you'll pull in the latest patch which includes the TTD

you can also use the TTD override flags with v2.3.0:

* for the beacon node: `--terminal-total-difficulty-override=50000000000000000`
* and for the validator client: `--terminal-total-difficulty-override=50000000000000000`

**Comment by MinwooJ** [comment]
I used that TTD override flag to run the client. Thank you!
