### ISSUE TITLE
HTTP API tests do not work for Bellatrix fork

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3251]
## Description

As @macladson discovered while testing https://github.com/sigp/lighthouse/pull/3070, the `http_api` tests are incompatible with the Bellatrix fork due to the interactions between async and blocking tasks. This is now picked up by the linter introduced in https://github.com/sigp/lighthouse/pull/3250 as well.

This is a tracking issue with several follow-up items, to ensure we don't forget to make the linter more comprehensive after fixing the known issues.

## Steps to resolve

- [x] Fix the issues with async/blocking tasks (@paulhauner is onto this in https://github.com/sigp/lighthouse/pull/3244).
- [ ] Update the linter's Makefile target to run with `--release` (and remove the FIXME)
- [ ] Merge #3070

**Comment by paulhauner** [comment]
Perhaps we can close this if/when #3325 merges without waiting for #3070?

**Comment by paulhauner** [comment]
Resolved via #3325
