### ISSUE TITLE
Lighthouse re-licensing: GPL 2.0 -> Apache 2.0

### ISSUE THREAD

**Issue by zedt3ster** [sigp/lighthouse#326]
Sigma Prime core contributors (@paulhauner , @AgeManning , @spble , @kirk-baird, @michaelsproul and others) have recently been discussing licensing for Lighthouse. We would like to change the licensing on Lighthouse to a more permissive, less restrictive license: Apache 2.0 (presently GPL 2.0).

We would like to request our [contributors](https://github.com/sigp/lighthouse/graphs/contributors) to provide their approval for this change. If you approve this re-licensing, please comment in this issue with the sentence "_I agree with re-licensing my work on this project to Apache 2.0_" or similar.

If you disagree with this change and would like to discuss further, please feel free to do so here or reach out to us on [Gitter](https://gitter.im/sigp/lighthouse).

Thank you all for helping make Lighthouse an even more open project!

**Comment by zedt3ster** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by paulhauner** [comment]
I agree with re-licensing my work on this project to Apache 2.0

**Comment by AgeManning** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by kirk-baird** [comment]
I agree with the change to Apache 2.0.

**Comment by NatoliChris** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by spble** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by michaelsproul** [comment]
I agree with re-licensing my work on this project to Apache 2.0

**Comment by mjkeating** [comment]
I agree with re-licensing my work on this project to Apache 2.0!!

**Comment by paulhauner** [comment]
> I agree with the change to Apache 2.0.

Gotta be different, eh? :laughing:

**Comment by thojest** [comment]
I agree with re-licensing my work on this project to Apache 2.0

**Comment by g-r-a-n-t** [comment]
I agree with re-licensing my work on this project to Apache 2.0

**Comment by darrenlangley** [comment]
I agree with re-licensing my work to Apache 2.0

**Comment by aj07** [comment]
I agree

**Comment by drozdziak1** [comment]
I agree

**Comment by seansu4you87** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by ralexstokes** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by Feng94** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by terenc3t** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by chronaeon** [comment]
I agree with re-licensing my work on this project to Apache 2.0

**Comment by johnomarkid** [comment]
I agree with re-licensing my work on this project to Apache 2.0.

**Comment by pawanjay176** [comment]
I agree with re-licensing my work on this project to Apache 2.0

**Comment by ltfschoen** [comment]
I agree with re-licensing my work on this project to Apache 2.0

**Comment by zedt3ster** [comment]
Thanks to everyone who agreed to this re-licensing! We're only missing one approval from @pinkiebell to move to Apache 2.0!

@pinkiebell - could you please let us know if you agree with this? Many thanks!

**Comment by pinkiebell** [comment]
@zedt3ster 👍 Never got a notification until yet :)

Here it comes:

I agree with re-licensing my work on this project to Apache 2.0. 

🎉

**Comment by zedt3ster** [comment]
Thank you so much everyone! This is a big step in making this project even more open!
