### ISSUE TITLE
Improve merge UX by removing `--merge` and adding preparedness indicators

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3260]
## Description

Here's a plan to improve merge UX:

- [x] deprecate the `--merge` flag, by enabling everything it does currently by default
- [x] clean up the logs for merge-related functionality so that:
  - if a Bellatrix epoch is set, we log loudly about the absence of EE endpoints, suggested fee recipients, etc
  - if no Bellatrix epoch is set, we _do not_ log loudly about the absence of merge-related config (this might involve disabling some services that were previously enabled by the `--merge` flag)
- [x] add an HTTP endpoint and/or routine log message to reassure users that their node is "merge ready", which checks the presence of all necessary flags

**Comment by paulhauner** [comment]
> deprecate the --merge flag, by enabling everything it does currently by default

This was completed in #3214 :tada:

**Comment by ronaldjmaas** [comment]
Also relating to #3315 : as Lighthouse does not support multiple execution endpoints anymore, please update the description for the following arguments accordingly:
--execution-endpoints <EXECUTION-ENDPOINTS>
--jwt-secrets <JWT-SECRETS>

and post merge:
--eth1-endpoints <HTTP-ENDPOINTS>

**Comment by michaelsproul** [comment]
@ronaldjmaas The `--help` for those flags has already been updated, in fact they're absent from `--help` as they are now just aliases to the new flags. The release notes for the next release will note this backwards-incompatible change.

```
        --execution-endpoint <EXECUTION-ENDPOINT>
            Server endpoint for an execution layer jwt authenticated HTTP JSON-RPC connection. Uses the same endpoint to
            populate the deposit cache. Also enables the --merge flag.If not provided, uses the default value of
            http://127.0.0.1:8551
```

```
        --execution-jwt <EXECUTION-JWT>
            File path which contains the hex-encoded JWT secret for the execution endpoint provided in the --execution-
            endpoint flag.
```

I think `--eth1-endpoints` needs its description updated soon too.

**Comment by pawanjay176** [comment]
> add an HTTP endpoint and/or routine log message to reassure users that their node is "merge ready", which checks the presence of all necessary flags

This was completed in #3349 :tada:

**Comment by michaelsproul** [comment]
I think the original purpose of this issue has been accomplished! We can continue tweaking merge UX over the next few weeks
