### ISSUE TITLE
Wrong `sync_committee_bits` value from beacon block rpc on kiln testnet

### ISSUE THREAD

**Issue by hujw77** [sigp/lighthouse#3265]
## Description
On kiln testnet, `sync_committee_bits` value from beacon block rpc always is `0xf7fffeefebd6ff6faf7ffffd7dfffffe6ff6bfbfffdedefffffff7fff5f77dace7fffb7fddffaefdfffffeffefffbdfffffbe6fb5fffb7fefd7f3fffffffbffb`
the value would not change. This seems to be an obvious bug.
## Version

stable

## Present Behaviour

shell script to reproduce it
```sh
~ curl -X GET http://127.0.0.1:5052/eth/v2/beacon/blocks/651772 -H  "accept: application/json" | jq -r '.data.message.body.sync_aggregate.sync_committee_bits'

0xf7fffeefebd6ff6faf7ffffd7dfffffe6ff6bfbfffdedefffffff7fff5f77dace7fffb7fddffaefdfffffeffefffbdfffffbe6fb5fffb7fefd7f3fffffffbffb
```

## Expected Behaviour

<img width="1048" alt="Screen Shot 2022-06-13 at 12 02 20" src="https://user-images.githubusercontent.com/6929585/173277410-4337d565-988d-4795-8cb4-846df9830ddb.png">

The correct value should be `0xefff7ff7d76bfff6f5feffbfbeffff7ff66ffdfdff7b7bffffffefffafefbe35e7ffdffebbff55bffbdf7ffff7ffbdffffdf67dffaffed7fbffefcfffeffdddf`

## Steps to reproduce

```sh
~ curl -X GET http://127.0.0.1:5052/eth/v2/beacon/blocks/N -H  "accept: application/json" | jq -r '.data.message.body.sync_aggregate.sync_committee_bits'
```
If you change the block N, the result would not change.

**Comment by michaelsproul** [comment]
This isn't a bug in Lighthouse, that's how sync committee bitvectors are encoded. The spec defines bitvector serialisation here: https://github.com/ethereum/consensus-specs/blob/dev/ssz/simple-serialize.md#bitvectorn.

The 0xf7 at the start of the bitfield corresponds to 0b11110111 in MSB-first binary, or 0b11101111 in LSB-first binary (which is what your screenshot of the explorer shows). Either way, this bitfield means that all sync committee validators in positions 0-7 signed the message except for index _3_.

You can convert from the serialised form to the bits in increasing order form using an expression like this (Python):

```python
"".join(format("{:08b}".format(byte)[::-1]) for byte in 0xf7fffeefebd6ff6faf7ffffd7dfffffe6ff6bfbfffdedefffffff7fff5f77dace7fffb7fddffaefdfffffeffefffbdfffffbe6fb5fffb7fefd7f3fffffffbffb.to_bytes(64, "big"))
```

```
11101111111111110111111111110111110101110110101111111111111101101111010111111110111111111011111110111110111111111111111101111111111101100110111111111101111111011111111101111011011110111111111111111111111111111110111111111111101011111110111110111110001101011110011111111111110111111111111010111011111111110111010110111111111111111111111101111111111111111111011111111111101111011111111111111111110111110110011111011111111110101111111111101101011111111011111111111110111111001111111111111111111111111111110111011111
```

There are cross-client standard test vectors that stress the hex-encoding and SSZ serialization here: https://github.com/sigp/lighthouse/tree/stable/testing/ef_tests
