### ISSUE TITLE
suggested_fee_recipient erroneous log warning

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#3267]
## Description

#3202 generates a lot message when there is a suspected mismatch between expected and actual fee recipient, however this only considers the value supplied on the command line and not that provided by the standard API endpoint.

## Version

2.3.1

## Present Behaviour

Warnings are raised when there is a mismatch between the suggested fee recipient supplied on the command line and that used for the beacon node of the form:

```
Jun 14 13:20:24.052 WARN Inconsistent fee recipient              suggested_fee_recipient: 0x1234...5678, fee_recipient: 8765...4321, proposer_index: xxxxx, msg: The fee recipient returned from the Execution Engine differs from the suggested_fee_recipient set on the beacon node. This could indicate that fees are being diverted to another address. Please ensure that the value of suggested_fee_recipient is set correctly and that the Execution Engine is trusted., service: exec
```

## Expected Behaviour

This log message should not be displayed when the fee recipient matches the address supplied in the `prepare_beacon_proposers` API call for the validator.

**Comment by paulhauner** [comment]
Resolved via #3363 :tada:
