### ISSUE TITLE
error: failed to compile `lighthouse v2.3.1 (/root/lighthouse/lighthouse)`, intermediate artifacts can be found at `/root/lighthouse/target`

### ISSUE THREAD

**Issue by tamaszl** [sigp/lighthouse#3274]
## Description

Please provide a brief description of the issue.

make
cargo install --path lighthouse --force --locked --features ""
  Installing lighthouse v2.3.1 (/root/lighthouse/lighthouse)
    Updating crates.io index
   Compiling lighthouse v2.3.1 (/root/lighthouse/lighthouse)
error: failed to compile `lighthouse v2.3.1 (/root/lighthouse/lighthouse)`, intermediate artifacts can be found at `/root/lighthouse/target`

Caused by:
  could not compile `lighthouse`

## Version

Please provide your Lighthouse and Rust version. Are you building from
`stable` or `unstable`, which commit?
stable v2.3.1

## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.

error: failed to compile `lighthouse v2.3.1 (/root/lighthouse/lighthouse)`, intermediate artifacts can be found at `/root/lighthouse/target`

Caused by:
  could not compile `lighthouse`

Caused by:
  process didn't exit successfully: `rustc --crate-name lighthouse --edition=2021 lighthouse/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C metadata=a7c616944a3d9a97 -C extra-filename=-a7c616944a3d9a97 --out-dir /root/lighthouse/target/release/deps -L dependency=/root/lighthouse/target/release/deps --extern account_manager=/root/lighthouse/target/release/deps/libaccount_manager-7c98c4762fcf89a1.rlib --extern account_utils=/root/lighthouse/target/release/deps/libaccount_utils-3efbaf09707d22ed.rlib --extern beacon_node=/root/lighthouse/target/release/deps/libbeacon_node-ec95e10ddbb11875.rlib --extern bls=/root/lighthouse/target/release/deps/libbls-482d0d75912b11ec.rlib --extern boot_node=/root/lighthouse/target/release/deps/libboot_node-075f1414a51dad8b.rlib --extern clap=/root/lighthouse/target/release/deps/libclap-6d07c913669099ce.rlib --extern clap_utils=/root/lighthouse/target/release/deps/libclap_utils-bfba433baabedb3c.rlib --extern database_manager=/root/lighthouse/target/release/deps/libdatabase_manager-9365219628dffecf.rlib --extern directory=/root/lighthouse/target/release/deps/libdirectory-5b2bd8067ebbfac4.rlib --extern env_logger=/root/lighthouse/target/release/deps/libenv_logger-a6988fc7e5e04d3b.rlib --extern environment=/root/lighthouse/target/release/deps/libenvironment-5304d3469ae4de1b.rlib --extern eth2_hashing=/root/lighthouse/target/release/deps/libeth2_hashing-a67d742e7449899b.rlib --extern eth2_network_config=/root/lighthouse/target/release/deps/libeth2_network_config-0a7243ab85667e12.rlib --extern futures=/root/lighthouse/target/release/deps/libfutures-6d53b20fd3acc7e7.rlib --extern lazy_static=/root/lighthouse/target/release/deps/liblazy_static-21549e276c465028.rlib --extern lighthouse_metrics=/root/lighthouse/target/release/deps/liblighthouse_metrics-14ec56ea692a8db2.rlib --extern lighthouse_version=/root/lighthouse/target/release/deps/liblighthouse_version-b4ac81eee5188a0a.rlib --extern malloc_utils=/root/lighthouse/target/release/deps/libmalloc_utils-97f97f242ee234a4.rlib --extern serde=/root/lighthouse/target/release/deps/libserde-fec03baa445c3e85.rlib --extern serde_json=/root/lighthouse/target/release/deps/libserde_json-0e4e0abf18dea1e6.rlib --extern serde_yaml=/root/lighthouse/target/release/deps/libserde_yaml-7965f93ccdc81060.rlib --extern slog=/root/lighthouse/target/release/deps/libslog-ea191462b76d0a17.rlib --extern sloggers=/root/lighthouse/target/release/deps/libsloggers-3c4d982c0d3ed130.rlib --extern task_executor=/root/lighthouse/target/release/deps/libtask_executor-99ec407c1cce3f96.rlib --extern types=/root/lighthouse/target/release/deps/libtypes-6cd7eb612d666ffc.rlib --extern unused_port=/root/lighthouse/target/release/deps/libunused_port-adb11df34cbcf673.rlib --extern validator_client=/root/lighthouse/target/release/deps/libvalidator_client-72dc9903f431f16f.rlib -L native=/root/lighthouse/target/release/build/blst-669f9b2ca5886106/out -L native=/root/lighthouse/target/release/build/ring-cd7196c72019a9fb/out -L native=/root/lighthouse/target/release/build/libsqlite3-sys-38f0e27a67d702cc/out -L native=/root/lighthouse/target/release/build/libz-sys-feb3a3ee75e35c13/out/lib -L native=/root/lighthouse/target/release/build/libz-sys-feb3a3ee75e35c13/out/lib -L native=/root/lighthouse/target/release/build/openssl-sys-62c8149e3041c406/out/openssl-build/install/lib -L native=/root/lighthouse/target/release/build/leveldb-sys-4899e8d450255432/out/lib -L native=/root/lighthouse/target/release/build/mdbx-sys-f4745435c4864c0e/out` (signal: 9, SIGKILL: kill)
make: *** [Makefile:25: install] Error 101

## Expected Behaviour

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
Are you compiling on a memory-constrained device? If you check `sudo dmesg -T` after the compilation failure it might mention that rustc was killed by the out-of-memory (OOM) killer.

If you have another machine with more RAM available you can also cross-compile: https://lighthouse-book.sigmaprime.io/cross-compiling.html

**Comment by tamaszl** [comment]
[Wed Jun 15 21:48:48 2022] Out of memory: Killed process 56601 (rustc) total-vm:2934036kB, anon-rss:1563564kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:5528kB oom_score_adj:0
