### ISSUE TITLE
Add timeout for POST `SignedContributionAndProof`

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3276]
## Description

We presently don't have a timeout for publishing contribution and proofs:

https://github.com/sigp/lighthouse/blob/564d7da656803f5e06e53a303972580be54500bf/common/eth2/src/lib.rs#L898-L913

It would be nice if we could have a shortened timeout like for attestations:

https://github.com/sigp/lighthouse/blob/564d7da656803f5e06e53a303972580be54500bf/common/eth2/src/lib.rs#L748-L749

This would mean that we can try some other BNs before the slot expires and the message becomes invalid. This is particularly impactful on Gnosis which has a short slot time.

**Comment by sragss** [comment]
Can I take this? 

Are there existing networking integration tests?

**Comment by michaelsproul** [comment]
@sragss that would be great, thanks!

The main test of VC<->BN interaction is via the `simulator` crate, which runs a mini network under ideal conditions. It doesn't currently test the `--beacon-nodes` fallback however

edit: link to simulator: https://github.com/sigp/lighthouse/blob/stable/testing/simulator/src/main.rs

**Comment by michaelsproul** [comment]
Resolved in #3291
