### ISSUE TITLE
[builder API] Make gas limit configurable

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3295]
## Description

Currently we are hard-coding , this should be configurable on a per-validator basis. We will likely want to track this in the validator definitions file, and allow users to update it via the HTTP API.

**Comment by mrabino1** [comment]
Interesting.. so the 30MM gas limit would be variable.. I would hope that we have a parameter to allow for the default to be 30MM

**Comment by realbigsean** [comment]
There's some discussion around it here: https://github.com/ethereum/builder-specs/issues/17

But yes, I think we'd keep 30MM as a default, just want to make sure it's possible for validators to set it if they wish

**Comment by michaelsproul** [comment]
I've opened a PR to add a standard HTTP API for the gas limit too: https://github.com/ethereum/keymanager-APIs/pull/39

I'll open a Lighthouse issue for its implementation if the feedback is favourable
