### ISSUE TITLE
[builder API] Enable Web3Signer tests for validator registration

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3296]
## Description

We currently run tests against the Consensys web3 signer. We have tests in https://github.com/sigp/lighthouse/pull/3194 that are commented out until the functionality for validator registration signatures are implemented.
[This is the relevant Consensys issue.](https://github.com/ConsenSys/web3signer/issues/577)

**Comment by siladu** [comment]
Hi @realbigsean web3signer validator registration support is available on master now.
If you use docker it's on the develop tag: `docker pull consensys/web3signer:develop`

We're expecting to release web3signer 22.7.0 this week or next with this in.

The shape of the signing request is documented here under the `VALIDATOR_REGISTRATION` type: https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Signing

**Comment by realbigsean** [comment]
Thanks @siladu !

**Comment by siladu** [comment]
Hi again @realbigsean this has now been released: https://github.com/ConsenSys/web3signer/releases/tag/22.7.0

Note, since my last message, the request format has changed: we no longer require an epoch to be sent.

**Comment by realbigsean** [comment]
Completed in 7aa2a74da7b54325445b88efb345d910b11b2c32
