### ISSUE TITLE
Compile fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by matthewdarwin** [sigp/lighthouse#3306]
## Description

Compile fails on Ubuntu 18.04.  leveldb will not compile with "parallel 20" option. cmake is version 3.10.2-1ubuntu2.18.04.2 

and tries to run
```
"cmake" "--build" "." "--target" "install" "--config" "Release" "--parallel" "20"
```

Manually changing into the build directory and running without the "--parallel" "20" will compile that component correctly.

## Version

unstable, from just now.

## Present Behaviour

Will not compile

## Expected Behaviour

Should compile

**Comment by michaelsproul** [comment]
The minimum version of CMake needed to compile Lighthouse is v3.12, although it's interesting that you got it to compile by just removing a single flag.

We're not inclined to change our dependencies to support earlier versions of CMake, so we recommend updating CMake if you'd like to compile on 18.04.

Another option is to use our cross-compilation toolkit, which does a better job of maintaining compatibility with older systems. It compiles on Ubuntu 16.04 but uses a recent version of CMake. The resulting binaries will run on 18.04: https://lighthouse-book.sigmaprime.io/cross-compiling.html

**Comment by matthewdarwin** [comment]
Sure.  It would be helpful if the required version was documented.  Doesn't say anything about minimum cmake version on https://lighthouse-book.sigmaprime.io/installation-source.html

**Comment by michaelsproul** [comment]
Good point, opened a PR https://github.com/sigp/lighthouse/pull/3310
