### ISSUE TITLE
Remove redundancy in the ulrs in the execution layer' config

### ISSUE THREAD

**Issue by divagant-martian** [sigp/lighthouse#3307]
## Description

After removing the fallback for engines in the execution_layer crate, we don't need the `secret_files` and `execution_endpoint` to be able to hold more than one in each field. Those could be changed to be options or even mandatory fields.

The relevant code is [here](https://github.com/sigp/lighthouse/blob/748475be1ded2c9a29cbd8b985f6ae2980720a36/beacon_node/execution_layer/src/lib.rs#L119-L123)

**Comment by AndyBarnard** [comment]
between the code example and this issue I can't tell - are you saying `execution_endpoints` and `secret_files` don't need to be vectors, and can be `Option`s, or are you saying just `builder_url` should be an `Option`?

**Comment by divagant-martian** [comment]
`builder_url` is not related to this issue. Just `execution_endpoints` and `secret_files`. Happy to help if you want to give this a go

**Comment by AndyBarnard** [comment]
ah my fork didn't have `builder_endpoints` as an `Option`, got a little mixed up there. I'll give it a go now!

**Comment by divagant-martian** [comment]
little checkup for whoever is interested. Still relevant to this date

**Comment by iamit-singh** [comment]
Hi @divagant-martian, please review my [PR](https://github.com/sigp/lighthouse/pull/5588) for this issue, thanks!

**Comment by michaelsproul** [comment]
Fixed by 

- #5588
