### ISSUE TITLE
Failover not working for execution API in Sepolia test network

### ISSUE THREAD

**Issue by ronaldjmaas** [sigp/lighthouse#3315]
## Description

During testing the transition from PoW to Pos on Sepolia I noticed that failover to another execution client is not working as expected for the execution API

## Version

Lighthouse v2.3.2-rc.0-45b2eb1

## Present Behaviour

I setup Lighthouse Beacon Node + Besu on localhost and Geth on a 2nd machine. Both eth1 endpoints and execution API end points are configured to connect to both Besu and Geth instances. Command line to start Lighthouse:

/home/lighthouse/lighthouse-v2.3.2-rc0/sepolia/lighthouse bn --datadir /mnt/ethereum/lighthouse@/sepolia --network sepolia --port 9004 --eth1-endpoints http://localhost:8545,http://192.168.1.106:8545 --execution-endpoints http://localhost:8551,http://192.168.1.106:8551 --jwt-secrets /mnt/ethereum/lighthouse@/sepolia/jwt-besu-sepolia,/mnt/ethereum/lighthouse@/sepolia/jwt-geth-sepolia --staking --http

After PoW > PoS transition first I shutdown the Geth (192.168.1.106) node and Lighthouse was working as expected. Then I started Geth and after a few minutes I shutdown the Besu (localhost), Lighthouse was unable to fail over to the Geth node and therefore unable to run without errors. Only after starting Besu Lighthouse was able to sync again.

Second experiment using a another command with Besu and Geth nodes reversed:

/home/lighthouse/lighthouse-v2.3.2-rc0/sepolia/lighthouse bn --datadir /mnt/ethereum/lighthouse@/sepolia --network sepolia --port 9004 --eth1-endpoints http://192.168.1.106:8545,http://localhost:8545 --execution-endpoints http://192.168.1.106:8551,http://localhost:8551 --jwt-secrets /mnt/ethereum/lighthouse@/sepolia/jwt-geth-sepolia,/mnt/ethereum/lighthouse@/sepolia/jwt-besu-sepolia --staking --http

Now with both Geth and Besu running Lighthouse was able to work as expected. Shutting down Besu (localhost) and Lighthouse keeps working as expected. Starting Besu and after a few minutes shutting down Geth (192.168.1.106) Lighthouse again was not able to failover to the working Besu node. Only after starting Geth Lighthouse was able to sync again. During this Besu continued printing a warning that no consensus layer client was connected to it.

## Expected Behaviour

Lighthouse in the setup describe above should work properly when either Besu or Geth or both are up and running.

## Steps to resolve

Hope you can investigate / fix why failover is not working when multiple nodes are specified in the --execution-endpoints and --jwt-secrets arguments. Thank you in advance.

**Comment by michaelsproul** [comment]
Hey, sorry to hear you're having issues.

Execution engine failover never worked particularly well and has been removed in our `unstable` branch as of this PR: https://github.com/sigp/lighthouse/pull/3214. The full rationale for removing this is described here: https://github.com/sigp/lighthouse/issues/3118. The solutions for multi-EL that exist today are:

- https://github.com/karalabe/minority
- https://github.com/TennisBowling/executionbackup

**Comment by ronaldjmaas** [comment]
Thanks for quick reaction. I understand the rationale and for the upcoming Goerli merge I make sure I setup 2 Lighthouse BNs each connecting to a single EL node.

Only ask for you and your team can do is updating the Lighthouse documentation + help text describing the --execution-endpoints and --jwt-secrets arguments.

**Comment by michaelsproul** [comment]
Thanks, updating the docs is on our TODO list (tracked by this issue: https://github.com/sigp/lighthouse/issues/3260).
