### ISSUE TITLE
Transition payload production might fail if the TTD block timestamp coincides with the slot time

### ISSUE THREAD

**Issue by marioevz** [sigp/lighthouse#3316]
## Description

Transition payload production might fail with the following error if the TTD block matches the slot time, because lighthouse attempts to produce a payload with `timestamp==parent.timestamp`:
(Geth/v1.10.20-stable-8f2416a8)
```
TRACE[07-07|17:12:38.009] Engine API request received              method=ForkchoiceUpdated head=c9c45b..aa9829 finalized=000000..000000 safe=c9c45b..aa9829
ERROR[07-07|17:12:38.010] Failed to create empty sealing payload   err="invalid timestamp, parent 1657213958 given 1657213958"
WARN [07-07|17:12:38.010] Served engine_forkchoiceUpdatedV1        conn=172.17.0.2:55382 reqid=1 duration="224.703µs"        err="Invalid payload attributes"           errdata="{Error:invalid timestamp, parent 1657213958 given 1657213958}"
DEBUG[07-07|17:12:38.010] Served eth_syncing                       conn=172.17.0.2:55382 reqid=1 duration="27.382µs"
TRACE[07-07|17:12:38.012] Engine API request received              method=ForkchoiceUpdated head=c9c45b..aa9829 finalized=000000..000000 safe=c9c45b..aa9829
ERROR[07-07|17:12:38.012] Failed to create empty sealing payload   err="invalid timestamp, parent 1657213958 given 1657213958"
WARN [07-07|17:12:38.012] Served engine_forkchoiceUpdatedV1        conn=172.17.0.2:55382 reqid=1 duration="214.23µs"         err="Invalid payload attributes"           errdata="{Error:invalid timestamp, parent 1657213958 given 1657213958}"
```

Using branch https://github.com/marioevz/hive/tree/all-tests-plus-cl-clients and the following command reproduces the issue every time:
```
./hive --client go-ethereum,lighthouse-bn,lighthouse-vc --sim eth2/engine --sim.loglevel 5 --sim.limit "/equal-timestamp-terminal-transition-block"
```

Note: Test checks for no failures on the response of `engine_forkchoiceUpdatedV1`, so test might still fail if, for example, lighthouse detects the issue and retries the command.

## Version
Lighthouse/v2.3.2-rc.0-5dbfb37

## Present Behaviour
Lighthouse might fail to produce a transition payload with 1/12 probability (On mainnet SECONDS_PER_SLOT time).

## Expected Behaviour
Lighthouse should produce a transition payload consistently.

**Comment by paulhauner** [comment]
Resolved via #3331. Thanks for raising this one @marioevz, great find :heart:
