### ISSUE TITLE
Beacon client fails with suggested-fee-recipient set in execution line, not in yaml definitions

### ISSUE THREAD

**Issue by adv0r** [sigp/lighthouse#3329]
## Description
The `suggested-fee-recipient` is added to the  `lighthouse/mainnet/validators/validator_definitions.yml` as indicated in the docs. 

Lighthouse bc works just fine. 

So I tried to add it also as a parameter `--suggested-fee-recipient` to the Exec line, for redundancy, and it causes an error:  
`The following required arguments were not provided:    --merge` 

So I'm wondering, why doesn't it require it anyway, since it was reading it from the yaml file earlier? 

## Version

v2.3.1-564d7da

## Present Behaviour

requires the --merge flag only if suggested-fee-recipient is set in CLI, not in yaml. 

## Expected Behaviour

fail/succeed in both cases?

**Comment by michaelsproul** [comment]
This should be fixed as of the latest commit to unstable. The `merge` flag is no longer necessary (for anything)

**Comment by michaelsproul** [comment]
Closing this as resolved, let me know if you manage to reproduce the issue on `unstable`
