### ISSUE TITLE
BLS serialization is not consistent

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#337]
## Description

The following test fails (when run in the `eth2/utils/bls` crate).

```rust
#[test]
    pub fn key_of_830() {
        let sk = SecretKey::from_bytes(&int_to_bytes48(830)).unwrap();
        let original = PublicKey::from_secret_key(&sk);

        let bytes = ssz_encode(&original);
        let (decoded, _) = PublicKey::ssz_decode(&bytes, 0).unwrap();

        assert_eq!(original, decoded);
        assert_eq!(ssz_encode(&original), ssz_encode(&decoded));
        assert_eq!(
            original.as_uncompressed_bytes(),
            decoded.as_uncompressed_bytes()
        );
    }
```
It only fails on the third `assert_eq`.

## Steps to resolve

Figure out what's causing this.

**Comment by paulhauner** [comment]
Here's a branch with the failing test: https://github.com/sigp/lighthouse/tree/failing-bls

**Comment by pawanjay176** [comment]
I'll pick this up

**Comment by hwwhww** [comment]
Hey, as discussed yesterday, I tried to run this case in `py_ecc`:
```python
def test_privkey_830():
    privkey = int.from_bytes(((830).to_bytes(48, 'little')), 'little')  # just try to reproduce your test; in py_ecc, the privkey is `int`.
    assert privkey == 830
    original = bls.privtopub(privkey)
    print('original:', original.hex())
    encoded = ssz.encode(original, ssz.sedes.bytes48)
    print('encoded:', encoded.hex())  # bytes48 vector just returns the same input
    decoded = ssz.decode(encoded, ssz.sedes.bytes48)
    assert original == decoded
    assert ssz.encode(original, ssz.sedes.bytes48) == ssz.encode(decoded, ssz.sedes.bytes48)
    assert bls.utils.pubkey_to_G1(original) == bls.utils.pubkey_to_G1(decoded)
    print('bls.utils.pubkey_to_G1(original:', bls.utils.pubkey_to_G1(original))
```

We don't have API as `as_uncompressed_bytes`, so I only tried `pubkey_to_G1` instead.

Output
```python
original: 96e108a8ac7aa8522c4447f091f78cdc1814ddf31d3ea9fa6e605a3ff034763749fe53dcc357a1e9c156531af67f9631
encoded: 96e108a8ac7aa8522c4447f091f78cdc1814ddf31d3ea9fa6e605a3ff034763749fe53dcc357a1e9c156531af67f9631
bls.utils.pubkey_to_G1(original: (3521406296023103111408692011802051237538185282649417142853203752598594154949005629166201815771914073589371048531505, 661855166479205040239580294057573726944340033014371846511483552532122177247237805222474873068914205407884926981738, 1)
```

Do we get the same `pubkey` here?

**Comment by pawanjay176** [comment]
The pubkey seems to be different. 
```
pub fn key_of_830() {
        let sk = SecretKey::from_bytes(&int_to_bytes48(830)).unwrap();
        let original = PublicKey::from_secret_key(&sk);
        println!("{:?}", original);
}
```

Output
`PublicKey(PublicKey { point: (11C772735AB6055C672F116CDEFBBF26F7AD6DDA775F105A3CBB49C12FFDF3B4A6AE62F7F048571CED1271DE9F9626BF,0D801F73ED1A7B916F0E00286008306A52B7BE06E9BB3985C8F0BF321D85E140C010ADF6AC8805D2B3D9A76ED3A8498A) })`

**Comment by kirk-baird** [comment]
Hey guys, I just found out why this was happening it's because `int_to_bytes48()` converts it to little endian whereas `SecretKey::from_bytes()` is big endian. 

Why the the conversion too / from uncompressed bytes occurs when fails when using little endian - 830 I'm not sure but my guess would be something funky happening as you have a secret key bigger than the curve order. Theoretically that shouldn't be an issue but we'll have to look into the amcl library `SecretKey::from_bytes()`

**Comment by paulhauner** [comment]
Thanks @kirk-baird!

I'm thinking we should either:

1. Leave this issue open to ensure we investigate.
2. Open a new, more specific issue to examine the point you raise.

Happy to take your guidance Kirk.

**Comment by kirk-baird** [comment]
I'll leave this one here for now :)

This should be done in https://github.com/sigp/signature-schemes/blob/master/src/keys.rs

We have two options:
a) Have `SecretKey::from_bytes()` include modulus curve order before returning the secret key. 
b) Having a check to ensure `0 <= secret_key < curve order` and returning Err() if not

I'm leaning more towards b) as it's bad practice to have secret keys outside a curve order and modulate them in.

**Comment by kirk-baird** [comment]
The solution to the issue is:
https://github.com/sigp/signature-schemes/pull/26

Note we will be required make release "0.7.0" in the signature schemes library and update the tag in eth2/utils/bls/Cargo.toml to match.

**Comment by paulhauner** [comment]
Hey @kirk-baird, can you please confirm that this is solved and we can close the issue? :)

**Comment by kirk-baird** [comment]
Yep this is solved in the `milargo_bls` library.
