### ISSUE TITLE
Remove `INVALID_TERMINAL_BLOCK` status and handling

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3379]
## Description

The latest spec has removed the `INVALID_TERMINAL_BLOCK` status. We should update Lighthouse according to the changes described here: https://github.com/ethereum/execution-apis/pull/217. Our version of this status is called `InvalidTerminalBlock`, and grepping for it currently yields 22 results

## Version

v2.4.0

**Comment by paulhauner** [comment]
Resolved via #3385 :tada:
