### ISSUE TITLE
`crypto/bls`: redundant `blst` non-optional dependency

### ISSUE THREAD

**Issue by sept-en** [sigp/lighthouse#3386]
## Description

`crypto/bls` crate supports two external crates for BLS signatures operations: `blst` and `milagro_bls`. `blst` is used by default and `milagro_bls` is optional. However, the current implementation implies that even though `milagro_bls` is used, `blst` will be compiled and included in the `bls` library. 

## Version

Rust version: 1.62.0
Lighthouse version: `unstable` branch, at https://github.com/sigp/lighthouse/commit/25f0e261cb37ca1945c7ec581da0c7cf09ad4c95

## Present Behaviour

`blst` crate dependency is not optional, included by default, even if the crate is compiled with `--no-default-features` flag and `milagro_bls` feature.

## Expected Behaviour

`blst` crate dependency is optional but included by default. When `--no-default-features` flag and `milagro_bls` feature are applied, only `milagro_bls` crate is included for BLS signatures.

## Steps to resolve

* make `blst` crate `optional`
* include `blst` dependency into `supranational` feature
* hide `blst`-related code with `supranational` feature

**Comment by paulhauner** [comment]
Resolved via #3387 (please correct me if I'm wrong :pray:)
