### ISSUE TITLE
Don't log "ready for the merge" if beacon node isn't synced

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3398]
## Description

A user on Discord identified that Lighthouse will log `INFO Ready for the merge` even when Lighthouse itself is not synced.

## Steps to resolve

Extend the logic added in #3339 to take into account Lighthouse's sync status. We could add a new variant to the `MergeReadiness` enum like `BeaconNodeNotSynced` (and rename `NotSynced` to `ExecutionNodeNotSynced`).

Alternatively we could just leave things as-is. Users running validators will see a lot of errors if their BN isn't synced and should know that this is an indicator that their node is _not_ merge ready.

**Comment by paulhauner** [comment]
I might close this once since we're done with the merge (I hope??).

Feel free to re-open if you disagree :relaxed:
