### ISSUE TITLE
Change the gRPC interface to allow for lighthouse specific errors

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#340]
## Description

Currently we are handling all BeaconNode errors are RPCStatus errors. Which are handled in the validator client as `BeaconNodeError(string)`. It would be more useful to have specific errors which allows the validator client to perform error-specific handling. 

For example, if we request a slot that is in the future, the beacon node could return an error of, slot in the future. The validator client could then wait and re-submit. 

We should modify the protobuf schema to include messages of the form 
```
message Response
    uint32 success = 1; 
    ...
```
where `success` has 0 as success and integers representing lighthouse-specific errors. 

This could go hand in hand with #338

**Comment by spble** [comment]
This issue is no longer relevant as the gRPC interface will be replaced with a RESTful HTTP interface.
