### ISSUE TITLE
Rename `--private-tx-proposals` to something builder-y

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3405]
## Description

I was looking for the flag to enable blinded/builder payloads on the VC and was expecting something along the lines of `--builder`. I know it's been a while since we added the `--private-tx-proposals` flag so I thought maybe we could consider renaming it and adding a backwards-compatible alias to `--private-tx-proposals`.

I'm creating this issue rather than a PR since I'm a bit behind on the builder efforts; perhaps `--private-tx-proposals` is already established?

**Comment by realbigsean** [comment]
It's actually currently named `--builder-proposals` and has an alias to `--private-tx-proposals`

**Comment by realbigsean** [comment]
Does that name seem reasonable?

**Comment by paulhauner** [comment]
Ooh nice, that's perfect!
