### ISSUE TITLE
Implement Retries for block / attestation production

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#341]
## Description

If we request a future block, the validator client will return an `RpcStatus::OutOfRange` error. 

For the remaining duration of the block, we should get the validator to re-attempt to produce a block/attestation. 

This can happen if the node is busy processing logic and hasn't updated the state, when the validator asks it to produce output. 

This would likely require #340 so that we can determine the exact kind of error before re-attempting to produce a block/attestation.

**Comment by paulhauner** [comment]
Closing this since we've heavily refactored the BN and VC since this issue.
