### ISSUE TITLE
VC: Update subnet subscription and attestation aggregation for all connected BNs

### ISSUE THREAD

**Issue by torfbolt** [sigp/lighthouse#3422]
## Description

As a Ethereum validator I would like to be able to use a Lighthouse validator client with redundant beacon nodes, without subscribing to all subnets.

## Version

2.5.1

## Present Behaviour

A Lighthouse VC can currently connect to several BNs for redundancy. However, it does not keep all of these BNs informed about its duties, only the currently preferred one. It is therefore required to [configure](https://lighthouse-book.sigmaprime.io/redundancy.html#configuring-a-redundant-beacon-node) the fallback beacon node with the `--subscribe-all-subnets` and `--import-all-attestations` flags, leading to an increased resource consumption.

## Expected Behaviour

The VC should send update messages to all connected beacon nodes, so that all of them behave as if they were the only BN connected to the VC.

**Comment by michaelsproul** [comment]
Resolved by #3529

Will be in the next release :tada:
