### ISSUE TITLE
The Linux binaries for the latest version 2.5.1 provided https://github.com/sigp/lighthouse/releases do not work.

### ISSUE THREAD

**Issue by ch4r10t33r** [sigp/lighthouse#3431]
## Description

The Linux binaries for the latest version 2.5.1 provided https://github.com/sigp/lighthouse/releases do not work.

## Version

Binary of v2.5.1 present in URL https://github.com/sigp/lighthouse/releases

## Present Behaviour

The binaries present in both the zip files (https://github.com/sigp/lighthouse/releases/download/v2.5.1/lighthouse-v2.5.1-x86_64-unknown-linux-gnu.tar.gz and https://github.com/sigp/lighthouse/releases/download/v2.5.1/lighthouse-v2.5.1-x86_64-unknown-linux-gnu-portable.tar.gz) fail with the following error

```
partha@ip-10-9-1-134:~$ ./lighthouse --help
-bash: ./lighthouse: cannot execute binary file: Exec format error
```

## Expected Behaviour

lighthouse executable should work

## Steps to resolve

I believe both the zip files contain the executable for the wrong architecture. I am able to generate the executable when I build from the source.

**Comment by michaelsproul** [comment]
Do you have an ARM CPU? I just downloaded the v2.5.1 binary and it's definitely an x86-64 binary:

```
$ tar xf lighthouse-v2.5.1-x86_64-unknown-linux-gnu.tar.gz
$ file lighthouse
lighthouse: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=2f60063bb9b861ae216c2210de801dce2ea97a05, with debug_info, not stripped
```

```
$ lighthouse --version
Lighthouse v2.5.1-df51a73
BLS library: blst-modern
SHA256 hardware acceleration: true
Specs: mainnet (true), minimal (false), gnosis (true)
```
