### ISSUE TITLE
File `validator_definitions.yml` constantly being overwritten, preventing secure setup

### ISSUE THREAD

**Issue by greg7mdp** [sigp/lighthouse#3436]
## Description

I'm trying to setup a secure system, where the validator password is stored in a Aegis Secure Key, so if the system in disconnected from power, it will not start validating when being plugged back in (see https://technicallynottechnical.medium.com/guide-to-securing-an-ethereum-2-0-validator-wallet-from-getting-slashed-due-to-theft-ubuntu-linux-89ad9233a67e),

The idea is that `validator_definitions.yml`, containing the password, is a symbolic link to the actual file stored in the Aegis Secure Key. I can setup this, but upon running it looks like lighthouse replaces the file `validator_definitions.yml`, so the symbolic link is replaced by the actual file.

## Version

Lighthouse v2.1.4-98f7404
BLS library: blst-modern
SHA256 hardware acceleration: false
Specs: mainnet (true), minimal (false), gnosis (true)

## Expected Behaviour

 `validator_definitions.yml` should not be constantly rewritten, or there should be a command-line option allowing to specify its location (different from `--datadir`).

## Steps to resolve

If you have a suggestion, I'd like to know!

**Comment by ghost** [comment]
Instead of putting the whole `validator_definitions.yml` on the secure storeage and symlinking, you could replace  `voting_keystore_password: <password>` in `validator_definitions.yml`  with `voting_keystore_password_path: /secure_storage/password.txt` The VC should fail to start up if it has no access to `/secure_storage/password.txt`

**Comment by michaelsproul** [comment]
We use a setup similar to what @aascft3 describes for some of our validators, although we use a `--secrets-dir` to point to the encrypted volume (same idea though).

**Comment by greg7mdp** [comment]
Fantastic! Thanks for the tip @aascft3 and @michaelsproul !

**Comment by greg7mdp** [comment]
Works great. Closing the issue. Thanks again. 
PS: Lighthouse rocks. I tried Teku but the cpu temp average went up by 10 degrees (compared to prysm). So I switched to lighthouse and my temps went back down to the prysm level.
