### ISSUE TITLE
Validator registrations submitted before validator activation

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3440]
## Description

[Brought up in Discord](https://discord.com/channels/605577013327167508/618981555985186827/1006309353730625648)

This line sneakily makes sure we don't include pre-activation validators in our prepare beacon proposer requests https://github.com/sigp/lighthouse/blob/stable/validator_client/src/preparation_service.rs#L269

Because there's no validator index necessary for the equivalent validator registration message, we lose this filtering https://github.com/sigp/lighthouse/blob/stable/validator_client/src/preparation_service.rs#L293

**Comment by michaelsproul** [comment]
Resolved by #3441
