### ISSUE TITLE
Getting fee recipient for unknown validator pubkey results in 405

### ISSUE THREAD

**Issue by yorickdowne** [sigp/lighthouse#3442]
## Description

When calling `eth/v1/validator/$__pubkey/feerecipient` with an unknown or malformed pubkey, a 405 method not allowed is returned.

```
yorick@ethlinux:~/eth-docker-devel$ docker-compose run --rm validator-keys get-recipient 0x9449c954822a6b836fdf1be20a27c3d4ff88d887e3619e998818ffa534b15a1a410d367da0d4ded4984ac747bfb074e5
Unexpected return code. Result: {"code":405,"message":"METHOD_NOT_ALLOWED","stacktraces":[]}
```

Should this be 404 as per https://github.com/ethereum/keymanager-APIs/blob/master/apis/local_keystores.yaml ?

**Comment by michaelsproul** [comment]
Yeah it should be. We're fighting a battle with our HTTP library to get it not to morph 404s into 405s. The tracking issue for that is here: https://github.com/sigp/lighthouse/issues/3112

**Comment by michaelsproul** [comment]
Closing this in favour of the other issue
