### ISSUE TITLE
POST query returns METHOD_NOT_ALLOWED

### ISSUE THREAD

**Issue by HikaruG** [sigp/lighthouse#3472]
## Description
I'm struggling to use the POST queries of both the eth1 standard / the lighthouse endpoints.

## Version
Lighthouse v2.5.1-df51a73
Here is the lighthouse cmd I'm using: 
`lighthouse --network prater vc --beacon-nodes http://<some_beacon_node_ip>:5052 --datadir /var/lib/lighthouse/validator --http --http-address 0.0.0.0 --unencrypted-http-transport --suggested-fee-recipient <some_testnet_address>
`
## Present Behaviour
So far I've tried the `/lighthouse/validators/keystore` and the `/eth/v1/keystores` queries, but both of them returned:
> {"code":405,"message":"METHOD_NOT_ALLOWED","stacktraces":[]}

I'm currently using the following curl cmd for testing purpose: 
`curl -X POST -H "Authorization: Bearer api-token-<some_api_token>" -d @val_ex_2.json  localhost:5062/lighthouse/validators/keystore` 

I've tested the GET queries and they seemed to work, so I'm assuming this issue is unrelated to the api-token. 

Have I forgotten to unlock the POST queries in the lighthouse parameters? Or am I missing something else? 
Any help is very much appreciated! 

## Expected Behaviour

Returns something similar to the expected response body: 
```
{
  "data": {
    "enabled": true,
    "description": "",
    "voting_pubkey": "0xb0d2f05014de27c6d7981e4a920799db1c512ee7922932be6bf55729039147cf35a090bd4ab378fe2d133c36cbbc9969"
  }
}

```

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
I ran into the same thing today, you unfortunately need to set the `Content-Type: application/json` header for it to work

**Comment by HikaruG** [comment]
Thank you for your prompt answer, it worked as expected!
