### ISSUE TITLE
Travis build is exceeding 50min maximum

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#348]
## Description

Travis has a 50min max run-time for tests and we're exceeding it, causing builds to fail.

I suspect we can improve this disabling some complex tests in debug (only running them in release).

## Steps to resolve

Move some long-running tests to release-only

**Comment by paulhauner** [comment]
I will have a fix for this today.

**Comment by michaelsproul** [comment]
@paulhauner, I was thinking we could consider _only_ running the tests in `--release`? In #345 I've had to add yet-another test configuration (`--release` with `--features fake_crypto`), so I was thinking we could do something like:

Travis:

* Run most  tests in `--release`
* Run small state transition tests with `--release --features fake_crypto`

Jenkins:
* Run all tests in `--release` (using `--ignored` and the `#[ignored]` attrib)
* Run all state transition tests with `--release --features fake_crypto --ignored`

**Comment by michaelsproul** [comment]
i.e. do away with running anything in debug mode

**Comment by michaelsproul** [comment]
Oh, but we'd lose panic-on-overflow behaviour :(

**Comment by paulhauner** [comment]
> Oh, but we'd lose panic-on-overflow behaviour :(, so maybe we could run the tests in debug mode on Jenkins

Hmm, this is a good point. The issue with Jenkins is that it only runs for "contributors" because if you edit the Dockerfile in this repo you basically have root on our Jenkins box.

I've been chatting to @spble to try and figure out a way that we can have fast, public CI.

I have a PR over at #349, maybe we can kick the can down the road a bit with it.

**Comment by michaelsproul** [comment]
Yeah I think that should be good for now
