### ISSUE TITLE
Prater does not merge with goerli when goerli is syncing, even if goerli has reached TTD

### ISSUE THREAD

**Issue by wjmelements** [sigp/lighthouse#3480]
## Description

Prater does not merge with goerli

## Version

rust 1.63
stable 2.5.1
geth 1.10.21

## Present Behaviour
Prater:
```
Aug 18 13:17:30 pine lighthouse[2071394]: Aug 18 18:17:30.000 INFO Syncing                                 est_time: 5 days 22 hrs, speed: 5.33 slots/sec, distance: 2741735 slots (54 weeks 2 days), peers: 65, service: slot_notifier
Aug 18 13:17:30 pine lighthouse[2071394]: Aug 18 18:17:30.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Aug 18 13:17:30 pine lighthouse[2071394]: Aug 18 18:17:30.001 WARN Not ready for merge                     info: The execution endpoint is connected and configured, however it is not yet synced, service: slot_notifier
```
Görli:
```
Aug 18 13:18:00 pine geth[2071393]: INFO [08-18|13:18:00.696] Legacy sync reached merge threshold      number=7,382,819 hash=7c38fc..3fd3cd td=10,790,002 ttd=10,790,000
Aug 18 13:18:01 pine geth[2071393]: INFO [08-18|13:18:01.036] Legacy sync reached merge threshold      number=7,382,819 hash=7c38fc..3fd3cd td=10,790,002 ttd=10,790,000
Aug 18 13:18:02 pine geth[2071393]: INFO [08-18|13:18:02.259] Legacy sync reached merge threshold      number=7,382,819 hash=7c38fc..3fd3cd td=10,790,002 ttd=10,790,000
Aug 18 13:18:02 pine geth[2071393]: WARN [08-18|13:18:02.259] Local chain is post-merge, waiting for beacon client sync switch-over...
```
Görli `eth_syncing`:
```
> eth.syncing
{
  currentBlock: 7382818,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 7382822,
  startingBlock: 7382810,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0
}
```

## Expected Behaviour

It should merge.

## Steps to resolve

Sync goerli and try to merge with prater. Seems that it won't work if goerli has ever heard of a post-merge block before.

**Comment by wjmelements** [comment]
Seems to be because Prater is not synced, but weird that the error calls out the execution client as not synced when it doesn't get any more synced than that.

**Comment by wjmelements** [comment]
Interestingly it starts out saying it is ready. Here is where it goes from saying it is ready for the merge to where it says it is not ready:
```
Aug 18 13:48:42 pine lighthouse[2085637]: Aug 18 18:48:42.001 INFO Syncing                                 est_time: --, distance: 2739427 slots (54 weeks 2 days), peers: 59, service: slot_notifier
Aug 18 13:48:42 pine lighthouse[2085637]: Aug 18 18:48:42.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Aug 18 13:48:42 pine lighthouse[2085637]: Aug 18 18:48:42.004 INFO Ready for the merge                     current_difficulty: 10790001, terminal_total_difficulty: 10790000, service: slot_notifier
Aug 18 13:48:51 pine lighthouse[2085637]: Aug 18 18:48:51.033 WARN Execution endpoint is not synced        action: trying fallback, last_seen_block_unix_timestamp: 1660182298, endpoint: http://localhost:8555/, auth=true, service: deposit_contract_rpc
Aug 18 13:48:51 pine lighthouse[2085637]: Aug 18 18:48:51.033 ERRO No synced execution endpoint            advice: ensure you have an execution node configured via --execution-endpoint or if pre-merge, --eth1-endpoints, service: deposit_contract_rpc
Aug 18 13:48:51 pine lighthouse[2085637]: Aug 18 18:48:51.033 ERRO Error updating deposit contract cache   error: "All fallbacks errored: http://localhost:8555/, auth=true => EndpointError(FarBehind)", retry_millis: 60000, service: deposit_contract_rpc
Aug 18 13:48:54 pine lighthouse[2085637]: Aug 18 18:48:54.001 INFO Syncing                                 est_time: --, distance: 2739428 slots (54 weeks 2 days), peers: 61, service: slot_notifier
Aug 18 13:48:54 pine lighthouse[2085637]: Aug 18 18:48:54.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Aug 18 13:48:54 pine lighthouse[2085637]: Aug 18 18:48:54.004 INFO Ready for the merge                     current_difficulty: 10790001, terminal_total_difficulty: 10790000, service: slot_notifier
Aug 18 13:49:06 pine lighthouse[2085637]: Aug 18 18:49:06.001 INFO Syncing                                 est_time: --, distance: 2739429 slots (54 weeks 2 days), peers: 55, service: slot_notifier
Aug 18 13:49:06 pine lighthouse[2085637]: Aug 18 18:49:06.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Aug 18 13:49:06 pine lighthouse[2085637]: Aug 18 18:49:06.004 INFO Ready for the merge                     current_difficulty: 10790001, terminal_total_difficulty: 10790000, service: slot_notifier
Aug 18 13:49:18 pine lighthouse[2085637]: Aug 18 18:49:18.001 INFO Syncing                                 est_time: --, distance: 2739430 slots (54 weeks 2 days), peers: 56, service: slot_notifier
Aug 18 13:49:18 pine lighthouse[2085637]: Aug 18 18:49:18.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier
Aug 18 13:49:18 pine lighthouse[2085637]: Aug 18 18:49:18.002 WARN Not ready for merge                     info: The execution endpoint is connected and configured, however it is not yet synced, service: slot_notifier
Aug 18 13:49:30 pine lighthouse[2085637]: Aug 18 18:49:30.001 INFO Syncing                                 est_time: --, distance: 2739431 slots (54 weeks 2 days), peers: 66, service: slot_notifier
```

**Comment by wjmelements** [comment]
I have verified that your code will prevent merging on any non-false value, so this is the issue. I am working around by treating all values as synced but this won't work for others.

```
diff --git a/beacon_node/execution_layer/src/engine_api/http.rs b/beacon_node/execution_layer/src/engine_api/http.rs
index a8eb4297..320bc499 100644
--- a/beacon_node/execution_layer/src/engine_api/http.rs
+++ b/beacon_node/execution_layer/src/engine_api/http.rs
@@ -602,7 +602,7 @@ impl HttpJsonRpc {
          */
         match result.as_bool() {
             Some(false) => Ok(()),
-            _ => Err(Error::IsSyncing),
+            _ => Ok(()),
         }
     }

```

**Comment by pawanjay176** [comment]
This is normal with genesis sync. The merge will happen when lighthouse also reaches the slot corresponding to the ttd. Right now, your geth node is synced upto ttd but lighthouse is still catching up. Once lighthouse reaches ttd, it will start feeding execution payloads to geth which will result in lighthouse and EE syncing in lockstep from that point onwards.

An alternative is to use checkpoint sync https://lighthouse-book.sigmaprime.io/checkpoint-sync.html . With checkpoint sync, it will proceed as follows:
1. Lighthouse checkpoint syncs to the weak subjectivity checkpoint
2. Lighthouse sends a `forkChoiceUpdated` to geth with the head of the chain.
3. Geth starts reverse syncing from head to the genesis block
4. Lighthouse starts downloading historical blocks while continuing to follow head in optimistic sync mode https://github.com/ethereum/consensus-specs/blob/dev/sync/optimistic.md

This is way faster as execution clients can use their highly optimised sync strategies like snap sync to sync faster without needing to go in lockstep with CL clients. Lighthouse syncs faster too as backfilling blocks from a checkpoint requires fewer checks to be secure.

**Comment by SwaroopH** [comment]
Ran into this issue a week agowhen my geth db got corrupted post sync. A fresh sync was waiting for beacon client sync switch-over after reaching TTD. And Lighthouse wouldn't proceed since execution endpoint wasn't up to date.

Running a `--purge-db` and using `--checkpoint-sync-url` from a 3rd party helped get back into sync

**Comment by SwaroopH** [comment]
Unfortunately, it looks like our geth <> lighthouse keeps going out of sync. I need to keep forcing the checkpoint to get back in sync.

**Comment by michaelsproul** [comment]
@SwaroopH There's a bug in the latest Geth release that causes it to mark valid blocks as invalid, and Lighthouse currently isn't designed to recover from this. Lighthouse remembers the invalid blocks and refuses to re-process them as valid. It's implemented this way as a defensive measure against execution layer consensus faults, which we expect to be rare and in need of manual attention (e.g. resyncing the node).

We might make some changes to Lighthouse to better support resetting the head on an EL, as it seems like a useful feature. There's more discussion of that in this thread on the Eth R&D Discord: https://discord.com/channels/595666850260713488/892088344438255616/1011594089847869440

**Comment by michaelsproul** [comment]
@wjmelements Do you mind if I close this issue? It seems there's no actionable change required by Lighthouse in response to what you observed, except maybe to change the "Ready for the merge" log to indicate that Lighthouse isn't ready to merge until it has finished syncing (and I would prefer to open a targeted issue for that).

**Comment by SwaroopH** [comment]
> @SwaroopH There's a bug in the latest Geth release that causes it to mark valid blocks as invalid, and Lighthouse currently isn't designed to recover from this. Lighthouse remembers the invalid blocks and refuses to re-process them as valid. It's implemented this way as a defensive measure against execution layer consensus faults, which we expect to be rare and in need of manual attention (e.g. resyncing the node).
> 
> We might make some changes to Lighthouse to better support resetting the head on an EL, as it seems like a useful feature. There's more discussion of that in this thread on the Eth R&D Discord: https://discord.com/channels/595666850260713488/892088344438255616/1011594089847869440

I was using an older version. Anyway, I did use the new hotfix from today and that too runs into the same issue eventually and I have to purge lighthouse db to kickstart syncing.

**Comment by michaelsproul** [comment]
> Anyway, I did use the new hotfix from today and that too runs into the same issue eventually and I have to purge lighthouse db to kickstart syncing.

Is your Geth database getting continuously corrupted? If so, Lighthouse needs to re-sync when that happens

**Comment by SwaroopH** [comment]
> > Anyway, I did use the new hotfix from today and that too runs into the same issue eventually and I have to purge lighthouse db to kickstart syncing.
> 
> Is your Geth database getting continuously corrupted? If so, Lighthouse needs to re-sync when that happens

No, the corruption was a one off. I have a freshly synced node that stops syncing after a few hours of consensus updates from lighthouse.

Geth warning:
`Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!` 

Lighthouse error:
`ERRO No synced execution endpoint`

At this stage, the only option I have is to purge lighthouse db use checkpoint sync to get geth to start syncing again.

**Comment by michaelsproul** [comment]
> No, the corruption was a one off. I have a freshly synced node that stops syncing after a few hours of consensus updates from lighthouse.

Ok this is more interesting. Can you please DM or email me Lighthouse's debug logs from when this occurred? You can find debug logs in `$datadir/beacon/logs/beacon.log`. You can DM me on Discord (`@sproul#3907`) or my email is `<firstname>@sigmaprime.io`.

**Comment by wjmelements** [comment]
> @wjmelements Do you mind if I close this issue? It seems there's no actionable change required by Lighthouse in response to what you observed, except maybe to change the "Ready for the merge" log to indicate that Lighthouse isn't ready to merge until it has finished syncing (and I would prefer to open a targeted issue for that).

Sounds fine to me so long as you do open that targeted issue. It should be clear why the merge isn't happening in this situation, and mis-attribution can waste a lot of time.

**Comment by michaelsproul** [comment]
Ah, there's already an issue for the logging issue here: https://github.com/sigp/lighthouse/issues/3398

I'll close this issue now so we can keep it focussed.

It seems @SwaroopH's issues stem from a reverse proxy getting in the way, and I'm helping him debug that via Discord DMs.
