### ISSUE TITLE
Maintain attestation subnet peers

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#3482]
## Description

Currently, for attestation subnets, we find peers in the required subnet from discovery and give it to the peer manager to dial. If we connect to all the discovered peers in that subnet then they disconnect before the attestation duty for some reason, we might get in a situation where we don't have enough peers in that subnet to publish the message.

To fix this, we could modify the `maintain_sync_committee_peers` function in the peer manager to also maintain peers for attestation subnets.

https://github.com/sigp/lighthouse/blob/df51a73272489fe154bd10995c96199062b6c3f7/beacon_node/lighthouse_network/src/peer_manager/mod.rs#L801

This way, we won't be affected by random disconnects by subnet peers for attestations.

**Comment by oxlime** [comment]
Is this still open. I'd like to tackle this issue.

**Comment by divagant-martian** [comment]
closing this in favor of https://github.com/sigp/lighthouse/issues/2981
