### ISSUE TITLE
Documentation: Post Merge instructions unclear

### ISSUE THREAD

**Issue by Sajjon** [sigp/lighthouse#3501]
Pre-Merge I used to run lighthouse in two terminal tabs, one `lighthouse bn --staking` tab and and one `lighthouse vc` tab.

The Handbook has a special section for Post-Merge setup, it explicitly states that

```
lighthouse \
    --network mainnet \
    beacon_node \
    --http \
    --eth1-endpoints http://localhost:8545,https://TOKEN@eth2-beacon-mainnet.infura.io
```

should be migrated to:

```
lighthouse \
    --network mainnet \
    beacon_node \
    --http \
    --execution-endpoint http://localhost:8551
    --execution-jwt ~/.ethereum/geth/jwtsecret
```

I guess this is what I've previously used `lighthouse bn --staking` for.

But what is the recommended new command for `lighthouse -vc`? Is it not needed anymore?

**Comment by michaelsproul** [comment]
`lighthouse vc` is still required, and its configuration can remain mostly the same. The only change necessary to the VC is the addition of the `--suggested-fee-recipient`. That's bullet point 2 here: https://lighthouse-book.sigmaprime.io/merge-migration.html#necessary-configuration

**Comment by Sajjon** [comment]
@michaelsproul nice, I believe lots of people would love that in the handbook, something like:

> The `vc` command can remain the same post-merge

or similar.

**Comment by michaelsproul** [comment]
Yeah good idea. I'll try find some time tomorrow to add that

**Comment by Sajjon** [comment]
> `lighthouse vc` is still required, and its configuration can remain mostly the same. The only change necessary to the VC is the addition of the `--suggested-fee-recipient`. That's bullet point 2 here: https://lighthouse-book.sigmaprime.io/merge-migration.html#necessary-configuration

@michaelsproul how should I use `--suggested-fee-recipient` arg? does it take a value? looks in code like it does, should that value be in quotation marks? or not? start with leading "0x"? I have not found any documentation about an **example usage** of this arg, that would be very helpful!

Take a look at https://lighthouse-book.sigmaprime.io/suggested-fee-recipient.html 

I would like to see a change from current:

```
Assuming trustworthy nodes, the priority for the three methods is:

validator_definitions.yml
--suggested-fee-recipient provided to the VC.
--suggested-fee-recipient provided to the BN.
```

to 

```
Assuming trustworthy nodes, the priority for the three methods is:

validator_definitions.yml
`--suggested-fee-recipient "<PLAIN_OLD_ETH_ADDRESS>"` provided to the VC.
`--suggested-fee-recipient "<PLAIN_OLD_ETH_ADDRESS>"` provided to the BN.
```

And analogoulsy for section 2 and 3:

Change from:
```
The --suggested-fee-recipient can be provided to the VC to act as a default value for all validators where a suggested_fee_recipient is not loaded from another method.
```

to

```
The `--suggested-fee-recipient "<PLAIN_OLD_ETH_ADDRESS>"` can be provided to the VC to act as a default value for all validators where a suggested_fee_recipient is not loaded from another method.
```

Or without quotation marks if that is the case...?

**Comment by michaelsproul** [comment]
I've updated the docs in this PR: https://github.com/sigp/lighthouse/pull/3509

Regarding the fee recipient: 0x-prefix or no prefix will both work. Quotes are fine if you're running in a shell as the shell will strip them. In general, avoid quotes as Lighthouse won't parse them, and won't work if they're passed through verbatim from a `docker-compose` config, etc.
