### ISSUE TITLE
Try new robust Accept header parser

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3510]
## Description

It seems a robust parser for Accept headers has finally emerged. We have rudimentary Accept header parsing but it's incorrect in case of quoted commas. For more context see: https://github.com/sigp/lighthouse/pull/3185#discussion_r875285613.

In the fullness of time we should delete our `.split(',')` implementation in favour of the `MediaTypeList` implementation: https://docs.rs/mediatype/latest/mediatype/struct.MediaTypeList.html

## Version

Lighthouse v3.0.0

**Comment by MaboroshiChan** [comment]
Hi. I think I have a fix for this issue using the tool you've provided, and have added a test case in which a parameter is a string which contains a quoted comma. This will be my very first commit.

**Comment by iamit-singh** [comment]
Hi, I can work on suggested changes on @MaboroshiChan's [PR](https://github.com/sigp/lighthouse/pull/3520).. this will be my first commit.
