### ISSUE TITLE
Allow users to set a fee cutoff to determine whether or not to use a block supplied by the builder API

### ISSUE THREAD

**Issue by allboxes** [sigp/lighthouse#3517]
## Description

User's are required to make a binary choice between using a centralized block builder or forgoing MEV.

## Expected Behaviour

Allow user's to set a fixed fee (e.g. 0.2 ETH) under which they will use a locally produced block.

In this way validators can gain exposure to large MEV opportunities while still contributing to decentralized block building when MEV is small/non existent.

Additionally, as the CL does not currently have a view into the value of a locally produced block, this provides some protection to user's from relay's producing very low value blocks.

In the future this can be enhanced by comparing the value of the locally built block vs. the remote builder's submission and using a fee delta instead of a fixed fee.

**Comment by michaelsproul** [comment]
I like this idea a lot!

**Comment by allboxes** [comment]
[ajsutton](https://github.com/ajsutton) suggested I submit this to MEV-Boost instead.  Ill update this issue if they implement/reject handling it there.

**Comment by realbigsean** [comment]
I think we should add this in lighthouse because MEV-boost won't have the ability to do the local vs. relay comparison because it doesn't connect to a local EE.  We'll need the execution APIs to eventually add a post-transaction fee recipient balance field to the `getPayload` response in order to support it.  But I think this feature on its own lays the groundwork nicely!

**Comment by metachris** [comment]
If there's wider interest in this feature as part of mev-boost, please signal your interest with a 👍 on https://github.com/flashbots/mev-boost/issues/273

**Comment by metachris** [comment]
btw, totally agree that ELs should provide a way to get the validator feeRecipient balance difference to be able to compare the value locally! would be important to keep pushing on this
