### ISSUE TITLE
Log fee recipient addresses

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3524]
Several users have requested a log in the VC and/or BN with the fee recipient for each validator.

We could log the value of the fee-recipient flag if set, or else the value from the validator definitions.

Logging in the BN could occur upon first receiving a proposer preparation message.

**Comment by pawanjay176** [comment]
Should we provide an optional flag to turn the logging off if the vc is running a lot of validators? would be a lot of logs otherwise.

**Comment by michaelsproul** [comment]
Yeah I think that would be a good idea

**Comment by xtc0r** [comment]
Are you exposing the full ETH address or just the first and last 4 to 6 digits?
The latter might be enough and keeps the users save when posting logs.

**Comment by pawanjay176** [comment]
It is the latter, this is a sample log

```
Aug 30 03:47:09.922 INFO Validator exists in beacon chain        fee_recipient: 0xab97_ad88, validator_index: 213615, pubkey: 0xb542b69ba14ddbaf717ca1762ece63a4804c08d38a1aadf156ae718d1545942e86763a1604f5065d4faa550b7259d651, service: duties
```

**Comment by pawanjay176** [comment]
Completed in #3526
