### ISSUE TITLE
Manual checkpoint sync question

### ISSUE THREAD

**Issue by artjoma** [sigp/lighthouse#3533]
Could you please advice. According to documentation: 

```
https://lighthouse-book.sigmaprime.io/checkpoint-sync.html?highlight=checkpoint-block#manual-checkpoint-sync
```
```
--checkpoint-state: accepts an SSZ-encoded BeaconState blob
--checkpoint-block: accepts an SSZ-encoded SignedBeaconBlock blob
```

Where I can get BeaconState blob and SignedBeaconBlock blob files. Export from lighthouse node or how ?

**Comment by realbigsean** [comment]
Check the standard beacon API endpoints. Make sure to use the correct header to get SSZ encoding.

> To indicate that SSZ data is required in response to a request the header "Accept: application/octet-stream" should be sent. Note that only a subset of requests can respond with data in SSZ format; these are noted in each individual request.

https://ethereum.github.io/beacon-APIs/#/Debug/getStateV2

**Comment by michaelsproul** [comment]
Closing as resolved
