### ISSUE TITLE
--monitoring-endpoint cuts off the rest of the command parameters?

### ISSUE THREAD

**Issue by FabianSchuessler** [sigp/lighthouse#3539]
## Description

I noticed some really weird and reproducible behaviour regarding the order the of command options. It seems like when you put monitoring-endpoint before execution-endpoint, then this command option will be cut off.
It doesn't seem like a C&P error on my side.

## Version
v3.1.0-aa022f4 and at least v3.0.0
always stable

## Present Behaviour

```
ethereum@NUC:~$ lighthouse bn --staking --metrics --network mainnet --validator-monitor-auto --monitoring-endpoint https://beaconcha.in/api/v1/client/metrics?apikey=abc --execution-endpoint http://127.0.0.1:8551/ --execution-jwt /secrets/jwtsecret
[1] 4498
Sep 03 14:12:58.731 INFO Logging to file                         path: "/home/ethereum/.lighthouse/mainnet/beacon/logs/beacon.log"
Sep 03 14:12:58.733 INFO Lighthouse started                      version: Lighthouse/v3.1.0-aa022f4
Sep 03 14:12:58.733 INFO Configured for network                  name: mainnet
Sep 03 14:12:58.733 INFO Data directory initialised              datadir: /home/ethereum/.lighthouse/mainnet
Sep 03 14:12:58.734 WARN Running HTTP server on port 5052
Sep 03 14:12:58.734 INFO Deposit contract                        address: 0xabc, deploy_block: abc
--execution-endpoint: command not found
ethereum@NUC:~$ Sep 03 14:12:59.574 INFO Hot-Cold DB initialized                 split_state: 0xabc, split_slot: abc, service: freezer_db
Sep 03 14:17:40.133 INFO Starting monitoring api                 endpoint: https://beaconcha.in/, service: monitoring_client
Sep 03 14:17:40.140 INFO Starting beacon chain                   method: resume, service: beacon
```

`lighthouse bn --staking --metrics --network mainnet --validator-monitor-auto --execution-endpoint http://127.0.0.1:8551/ --execution-jwt /secrets/jwtsecret --monitoring-endpoint https://beaconcha.in/api/v1/client/metrics?apikey=abc `
works

## Expected Behaviour

The command parameter order should not matter.

**Comment by michaelsproul** [comment]
I think the explanation posted on Discord that this is due to your shell interpreting the `?` character as a control character and terminating the command early makes sense. You can see the shell trying to run the text after the URL as a separate command:

```
--execution-endpoint: command not found
```

Quoting the monitoring endpoint URL should alleviate this.

I'll close this for now but please feel free to re-open if you find new info
