### ISSUE TITLE
beacon: `WARN Error signalling fork choice waiter` 

### ISSUE THREAD

**Issue by Sajjon** [sigp/lighthouse#3541]
## Description

My `lighthouse beacon_node` reported - `WARN Error signalling fork choice waiter`:

```sh
006 INFO Ready for the merge                     current_difficulty: 58032850106454143299480, terminal_total_difficulty: 58750000000000000000000, service: slot_notifier
Sep 05 16:07:58.955 WARN Error signalling fork choice waiter     slot: 4630837, error: ForkChoiceSignalOutOfOrder { current: Slot(4630838), latest: Slot(4630837) }, service: beacon
Sep 05 16:07:59.424 INFO New block received                      root: 0xa0ad91e36da164dca6458c2233ce21ea64b665bad785a9075ba4862d635b52b5, slot: 4630838
Sep 05 16:08:04.942 INFO Synced
```

## Version

3.1.0 Stable:

```
lighthouse --version
Lighthouse v3.1.0-aa022f4
BLS library: blst
SHA256 hardware acceleration: false
Specs: mainnet (true), minimal (false), gnosis (false)
```

## Present Behaviour

`WARN Error` in logs

## Expected Behaviour

I would have hoped to see no warnings messages just before the merge.

## Steps to resolve

Dunno....

**Comment by michaelsproul** [comment]
this warning is harmless, but usually indicates the clock readjusting, or fork choice taking too long to run due to resource constraints

if it only happens infrequently it isn't an issue, but would point to clock sync issues or resource constraints
