### ISSUE TITLE
Clarify "awaiting activation" logs when doppleganger protection enabled

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3548]
## Description

Currently the validator client logs `Awaiting activation` when doppelganger protection is enabled, which is a bit confusing because it's the same message for validators that aren't active at all. I think we should override this message when doppelganger protection is enabled to say something more informative like `Validators paused while waiting for doppelganger detection, reactivation_epoch: <epoch>`

## Version

Lighthouse v3.1.0

**Comment by aga7hokakological** [comment]
I would like to take up this issue. 
As far as I understand I just need to make changes in [notifier.rs](https://github.com/sigp/lighthouse/blob/stable/validator_client/src/notifier.rs#L120-L128) right?

**Comment by aga7hokakological** [comment]
@michaelsproul what should be the reactivation epoch? It should be the next one right?

**Comment by aga7hokakological** [comment]
@michaelsproul I have made a pull request. What should be the reactivation epoch? It should be the next one right?
According to the documentation it is 
> DP takes 2-3 epochs, which is approximately 12-20 minutes. 

so I am adding it as 3 epochs. 

How should test for this. test script (./doppelganger_protection.sh success) won't show notification from the rust file?
