### ISSUE TITLE
Error updating deposit contract cache: BadTransaction WrongNonce

### ISSUE THREAD

**Issue by chaseadam** [sigp/lighthouse#3554]
## Description

Syncing fresh prater beacon using Goerli Akula execution node. Get the following error after Akula is synced:

```
Sep 07 23:06:54.001 WARN Syncing deposit contract block cache    est_blocks_remaining: initializing deposits, service: slot_notifier   Sep 07 23:06:59.671 ERRO Error updating deposit contract cache   error: Failed to update deposit cache: "All fallbacks errored: http://
127.0.0.1:8552/, auth=true => GetDepositLogsFailed(\"eth_getLogs call failed ServerMessage { code: -32000, message: \\\"BadTransaction 
{ index: 0, error: WrongNonce { account: 0x45b224f0cd64ed5179502da42ed4e32228485b3b, expected: 539662, got: 89626 } }\\\" }\")", retry_millis: 60000, service: deposit_contract_rpc
```

This may be a bad sync or an Akula problem. I am syncing another fresh instance of Akula to see if I can reproduce.

## Version

Commit 18c61a5e8be3e54226a86a69b96f8f4f7fd790e4 container build with `podman` running in rootless `podman` container

## Present Behaviour

Synced fresh prater node
Synced fresh Goerli Akula node
Lighthouse WrongNonce error

## Expected Behaviour

Expect success of "Syncing deposit contract block cache" stage.

## Steps to resolve

Unknown at this time

**Comment by michaelsproul** [comment]
I suspect this is an issue on Akula's side, as far as I know we've never seen this error from any other execution client. If you want to check whether it resolved itself after Akula synced some more you could try purging Lighthouse's view of Akula's logs using `--eth1-purge-cache` as an argument to `lighthouse bn`.

**Comment by michaelsproul** [comment]
I'll close this assuming this is an Akula bug. Feel free to re-open if new info emerges to suggest otherwise
