### ISSUE TITLE
Modification of agent version for Lodestar

### ISSUE THREAD

**Issue by philknows** [sigp/lighthouse#3561]
## Description

Reference: https://github.com/ChainSafe/lodestar/issues/4465

Lodestar is looking to modify the agent version gossiped from the default libp2p string `js-libp2p/0.36.2` to `lodestar/version`. We are requesting an update to your client on how you identify Lodestar nodes for better tracking and referencing of Lodestar peers on the network for debug purposes. We will not implement until it has been completed between all the various clients on the network.

**Comment by philknows** [comment]
Hey @michaelsproul ! Any ideas on when this may get implemented in Lighthouse? Thanks!

**Comment by AgeManning** [comment]
Oh yeah, will make a PR for this ASAP

**Comment by AgeManning** [comment]
Should be good to go next release.
