### ISSUE TITLE
Tests fail on IPV6 enabled machines because of ganache fork endpoint

### ISSUE THREAD

**Issue by alex88** [sigp/lighthouse#3562]
## Description

On IPV6 enabled machines tests involving ganache fork fails because localhost resolves to `::1` instead of `127.0.0.1` which is the default ganache listening address.

## Version

Unstable cfa518a

## Present Behaviour

Tests fail with:

```
failures:

---- fallbacks::test_fallback_when_offline stdout ----
thread 'fallbacks::test_fallback_when_offline' panicked at 'should start eth1 environment: "Timed out waiting for ganache to start. Is ganache installed?"', beacon_node/eth1/tests/test.rs:889:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- fallbacks::test_fallback_when_node_far_behind stdout ----
thread 'fallbacks::test_fallback_when_node_far_behind' panicked at 'should start eth1 environment: "Timed out waiting for ganache to start. Is ganache installed?"', beacon_node/eth1/tests/test.rs:1031:18
```

## Expected Behaviour

Tests should pass

## Steps to resolve

Change the ganache fork endpoint hostname from `localhost` to `127.0.0.1` to match the ganache default listening address.
Will provide PR for the change.

**Comment by michaelsproul** [comment]
Resolved by #3563, thanks!
