### ISSUE TITLE
Block Processing Tests - Deposits

### ISSUE THREAD

**Issue by darrenlangley** [sigp/lighthouse#357]
# Detail

Block processing lives in the `state_processing` crate, specifically in the `per_block_processing.rs` file and `per_block_processing/` dir.

Tests are implemented in the file: ... `state_processing/src/per_block_processing/tests.rs`.

The task will primarily consist of:

For each test, modify the valid block (or state?) to trigger some invalidity condition and assert that that condition was triggered by inspecting the error chain (i.e., ensure the returned Result is erroneous and the Error is correct).

## Deposits Errors

- [ ] Invalid::MaxDepositsExceeded

_verify_deposit_
- [ ] Invalid::BadProofOfPossession
- [ ] Invalid::BadMerkleProof

_verify_deposit_index_
- [ ] Invalid::BadIndex

**Comment by jzaki** [comment]
Still getting my head around the code, and will look into this.

**Comment by jzaki** [comment]
Updating above:
- [ ]  Invalid::DepositCountInvalid
_verify_deposit_merkle_proof_
    - [ ]  Invalid::BadMerkleProof
_verify_deposit_index_
    - [ ]  Invalid::BadIndex
_verify_deposit_signature_
    - [ ]  Invalid::BadSignature

**Comment by paulhauner** [comment]
@jzaki thanks for jumping onto this, these tests are important!

I think it might be a good idea to wait on @michaelsproul's input before going too far. The state transition code is his domain and we're updating to `v0.8.0` now.

**Comment by pscott** [comment]
So I'm trying to work on this, but I'm stuck here. Here's the sample code I'm working with:
```rust
fn max_deposits_exceeded() {
    let spec = MainnetEthSpec::default_spec();
    let mut builder = get_builder(&spec);

    let deposit_num = 7;

    // need temp_state to pass it as arg in insert_deposit.
    // cloning because .build() consumes the builder.
    let builder_copy = builder.state_builder.clone();
    let temp_state = builder_copy.build().0;

    // insert deposit_num deposits
    for i in 0..deposit_num {
        builder.block_builder.insert_deposit(32_000_000, i as u64 , &temp_state, &spec);
    }

    let (block, mut state) = builder.build(None, None, &spec);

    let result = per_block_processing(
        &mut state,
        &block,
        None,
        BlockSignatureStrategy::VerifyIndividual,
        &spec,
    );

    // assertion will fail
    // should get a MaxDeposits error
    assert_eq!(result, Ok(()));
}
```

Now obviously this code won't work, as I have not updated `eth1_data` (meaning the expected number of deposits == 0).

So I add this right after deposit_num declaration :
```rust
   // generate a random keypair that will serve as keys for all validators.
   let keypair = Keypair::random();

    // Modifying the state_builder and inserting deposit_num deposits in eth1_data.
    builder.state_builder = TestingBeaconStateBuilder::from_single_keypair(deposit_num, &keypair, &spec);
```

But now I'm getting
```thread 'per_block_processing::tests::max_deposits_exceeded' panicked at 'called `Result::unwrap()` on an `Err` value: CommitteeCacheUninitialized(Current)', src/libcore/result.rs:999:5```

So I'm clearly missing something. Is my test architecture fine? Am I missing a step before inserting deposits? Thanks!
