### ISSUE TITLE
Contract creation tx in execution integration tests is invalid

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#3573]
## Description

In the execution engine integration tests, we use the `ethers-rs` library to generate dummy transactions to check the payload reconstruction logic. While trying to integrate `ethers` ganache-cli replacement, I found that the deposit contract creation transaction is actually invalid (`tx_receipt.status == 0` for that transaction). 

The transaction is created here. 
https://github.com/sigp/lighthouse/blob/aa022f46855df2a1420a6a80a788c73dc2779aa7/testing/execution_engine_integration/src/transactions.rs#L59-L63

We need to figure out why the transaction is actually invalid and fix it. It'd be nice to have a mix of valid and invalid txs in the integration tests so that we can check decoding for both scenarios.

**Comment by michaelsproul** [comment]
Resolved by #3592
