### ISSUE TITLE
Block Processing Tests - Transfers

### ISSUE THREAD

**Issue by darrenlangley** [sigp/lighthouse#359]
# Detail

Block processing lives in the `state_processing` crate, specifically in the `per_block_processing.rs` file and `per_block_processing/` dir.

Tests are implemented in the file: ... `state_processing/src/per_block_processing/tests.rs`.

The task will primarily consist of:

For each test, modify the valid block (or state?) to trigger some invalidity condition and assert that that condition was triggered by inspecting the error chain (i.e., ensure the returned Result is erroneous and the Error is correct).

## Transfer Errors

- [ ] Invalid::MaxTransfersExceed

_verify_transfer_
- [ ] Invalid::FromValidatorUnknown
- [ ] Invalid::FeeOverflow
- [ ] Invalid::FromBalanceInsufficient (amount)
- [ ] Invalid::FromBalanceInsufficient (fee)
- [ ] Invalid::InvalidResultingFromBalance
- [ ] Invalid::TransferSlotInPast
- [ ] Invalid::StateSlotMismatch
- [ ] Invalid::FromValidatorUnknown
- [ ] Invalid::FromValidatorIneligableForTransfer
- [ ] Invalid::WithdrawalCredentialsMismatch
- [ ] Invalid::BadSignature

**Comment by pscott** [comment]
Seems like we can skip these for the moment, as MAX_TRANSFERS is set to 0 in the current spec.
