### ISSUE TITLE
Add flag to lengthen execution layer timeouts

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3607]
## Description

The engine API spec mandates that we time out after 8 seconds on any call to `newPayload` or `forkchoiceUpdated`. The problem is that on slow hardware this can seemingly lead to a livelock/death spiral (as reported by @jclapis and other Raspberry Pi enthusiasts). If some messages take say 8.1 seconds to process then the node will be stuck forever as it times out trying to process them. The reason the spec includes these timeouts is because arguably such a node is not viable, however there are two reasons to prefer longer timeouts (or no timeouts at all):

- The slow processing may be transient, due to a particularly heavy block, load on the machine, or some other factor.
- Not all nodes are used to support validators, so having nodes follow the chain with occasional periods of slowness might be OK.

## Steps to resolve

Add a flag to the beacon node like `--execution-timeout-multiplier N` which takes an integer value and extends timeouts by a factor of `N`.

In the code, it should have the effect of lengthening the timeouts used here:

https://github.com/sigp/lighthouse/blob/aa022f46855df2a1420a6a80a788c73dc2779aa7/beacon_node/execution_layer/src/engine_api/http.rs#L22-L38

**Comment by GeemoCandama** [comment]
I'd like to work on this issue. How could I write a good test for this feature? I have it set up to test whether the flag is being set correctly, but would like to test whether the timeouts are really being increased. 
https://github.com/GeemoCandama/lighthouse/tree/flag-to-up-EL-timeouts

**Comment by michaelsproul** [comment]
I think a CLI test to read the timeout from config would be sufficient for now. We can conduct some manual testing on low-spec devices to determine the impact

**Comment by paulhauner** [comment]
Resolved via #3631
