### ISSUE TITLE
VC does not fallback for sync sigs when primary BN is optimistic

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3612]
## Description

When the VC attempts to publish a sync committee signature it will try and get the head block root from the first BN that returns a response, regardless if that BN is optimistic or not:

https://github.com/sigp/lighthouse/blob/01e84b71f524968f5b940fbd2fa31d29408b6581/validator_client/src/sync_committee_service.rs#L177-L209

I think the ideal behaviour would be trying to find a BN that has a *non-optimistic* head block root. At first glance I think this would be pretty easy to achieve by pushing the `execution_optimistic` checks inside the `first_success` function.

**Comment by clifton** [comment]
is `ERRO Unable to publish proposer preparation` a related issue? I get that when one of my beacon nodes is optimistic and the other is synced.

**Comment by michaelsproul** [comment]
@clifton Yeah, it is. That also falls under the scope of the tracking issue to improve VC fallback behaviour: https://github.com/sigp/lighthouse/issues/3613
