### ISSUE TITLE
Block with an incorrect fee recipient

### ISSUE THREAD

**Issue by PacoBits** [sigp/lighthouse#3617]
Our setup has produced a block with an incorrect fee recipient: https://etherscan.io/block/15616137

We have been producing blocks correctly and after that incident it is still producing blocks with the fee recipient correctly.

We have a 3-layer configuration with the validator client, the Beacon node, a fallback beacon node and the execution client running separately.

These are our versions and fee recipent setup:

```
Validator set up - version: Lighthouse/v3.1.0-aa022f4
--graffiti "Block by Stakely Lido09"
--suggested-fee-recipient 0x388C818CA8B9251b393131C08a736A67ccB19297
```

```
Beacon MAIN node set up - teku/v22.9.1/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
"--validators-graffiti='Block by Stakely.io - btk01'",
"--validators-proposer-default-fee-recipient=0x7188D41ea11aBf3e95040ba1823E861A62644AC2"
```

```
Beacon FALLBACK node set up -(version: Lighthouse/v3.1.0-aa022f4)
--graffiti "Block by Stakely - lh01"
suggested-fee-recipient  is not set up
```

`Execution Client - Erigon/v2022.09.3-stable-32bd69e5/linux-amd64/go1.18.3`

The attached logs shows block was generated by erigon-teku correctly and sent to the validator, but at that moment there was a disconnection of teku and the validator:
Validator client log - disconected beacon:
`node09 | Sep 26 07:44:29.001 INFO Connected to beacon node(s) synced: 2, available: 2, total: 3, service: notifier
`
So the validator client continues the publication in the fallback beacon (Lighthouse beacon). This beacon does not have a default fee recipient set due to a problem.

Validator client log - publised block and reconnected to teku:

```
node09         | Sep 26 07:44:29.001 INFO All validators active                   slot: 4779520, epoch: 149360, total_validators: 500, active_validators: 500, current_epoch_proposers: 1, service: notifier
node09         | Sep 26 07:44:30.208 INFO Successfully published block            slot: 4779520, graffiti: Some("Block by Stakely Lido09"), attestations: 128, deposits: 0, block_type: Full, service: block
node09         | Sep 26 07:44:34.023 INFO Connected to beacon node                endpoint: httpxxx://x.x.x.x:xxxx/, version: teku/v22.9.1/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
```
We can see Lighthouse FALLBACK beacon node  log the problem:

`lighthouse_beacon_node_1 | Sep 26 07:44:27.178 CRIT Fee recipient unknown proposer_index: 366592, msg: the suggested_fee_recipient was unknown during block production. a junk address was used, rewards were lost! check the --suggested-fee-recipient flag and VC configuration., service: exec`

We set up a suggested-fee-recipient as work around, but in case of beacon node failover while the block generation process , validator client should send the suggested-fee-recipient and not only the graffity. 

[Valc09_26092022.log](https://github.com/sigp/lighthouse/files/9658376/Valc09_26092022.log)
[erigon_26092022.log](https://github.com/sigp/lighthouse/files/9658377/erigon_26092022.log)
[Lighthouse_Beacon_26092022.log](https://github.com/sigp/lighthouse/files/9658378/Lighthouse_Beacon_26092022.log)
[teku_26092022.log](https://github.com/sigp/lighthouse/files/9658379/teku_26092022.log)

**Comment by realbigsean** [comment]
Yes our validator doesn't send proposer preparation information to fallback at the moment, so a poorly timed fallback but will cause this, the fix is being worked on in this PR: https://github.com/sigp/lighthouse/pull/3529

For now, use setting the config directly in the fallback BN is the best workaround
