### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by rcketscientist** [sigp/lighthouse#3618]
## Description

I'm currently burning through almost 200MB of logs daily, mostly:

DEBG Failed incoming connection, error: Connection error: Connection limit: 72/72., from: /ip4/x.x.x.x/tcp/13000, our_addr: /ip4/x.x.x.x/tcp/9000, service: libp2p, module: lighthouse_network::service:350

Is this expected?

## Version

latest docker

## Expected Behaviour

Not burning through storage?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by pawanjay176** [comment]
The log is fairly common. The latest version of libp2p should hopefully reduce the occurrence of this particular log.
If you don't want to store that many logs, you can use non-default values for the following flags. This can also be found with `lighthouse bn --help | less`

```
        --logfile <FILE>
            File path where the log file will be stored. Once it grows to the value specified in `--logfile-max-size` a
            new log file is generated where future logs are stored. Once the number of log files exceeds the value
            specified in `--logfile-max-number` the oldest log file will be overwritten.
        --logfile-debug-level <LEVEL>
            The verbosity level used when emitting logs to the log file. [default: debug]  [possible values: info,
            debug, trace, warn, error, crit]
        --logfile-max-number <COUNT>
            The maximum number of log files that will be stored. If set to 0, background file logging is disabled.
            [default: 5]
        --logfile-max-size <SIZE>
            The maximum size (in MB) each log file can grow to before rotating. If set to 0, background file logging is
            disabled. [default: 200]

```

**Comment by AgeManning** [comment]
Yeah, that log is saying others are trying to connect to you but you already have too many peers. 

There's a lot of nodes out there and this log is useful to help identify if you are under a DOS attack or not. I think limiting the log file size as @pawanjay176 has suggested is the best solution for the time being.
