### ISSUE TITLE
Allowing more than one execution client

### ISSUE THREAD

**Issue by newearthmartin** [sigp/lighthouse#3627]
## Description

Please allow more than one execution client so that they can all receive PoS headers.

## Present Behaviour

Nowadays, clients like Erigon will not do anything unless a beacon node is connected to them (because they are missing PoS headers). This prevents having a backup EL client because only one EL client will be synced at a given time. 

This is important for client diversity. 

Example: I'm using Geth but would like to use Erigon, so I need to sync Erigon. But I don't want to miss attestations, so I would like to sync Erigon while Geth is running. Currently, if I wanted to do that, I would need to connect Lighthouse to Erigon and miss all attestations while Erigon is syncing. I also don't want to go to the trouble of setting up another instance of lighthouse and duplicating the lighthouse db in my system.

## Expected Behaviour

Ideally, there could be one main EL client but Lighthouse could have other EL clients so that they can receive PoS headers for syncing.

The other EL clients could be used as backup in case the main EL client fails.

**Comment by mrabino1** [comment]
So basically a passive engagement to ensure they have the headers only? (and not an active engagement)

**Comment by newearthmartin** [comment]
Yes, one active engagement and multiple optional passive engagements. Not sure if it's possible to use them as a failover mechanism as well.

**Comment by newearthmartin** [comment]
Not sure also why this is not implemented at the ethereum protocol level. The PoS headers could be requested by the EL client, instead of injected into them. But this is beyond the scope of this feature request :)

**Comment by newearthmartin** [comment]
Ah there is a discussion about this here https://github.com/sigp/lighthouse/issues/3118

**Comment by paulhauner** [comment]
This can be achieved with a third-party proxy like https://github.com/TennisBowling/executionbackup.

I appreciate that there's demand for this, but I prefer that this functionality is implemented in a stand-alone, works-with-any-client implementation rather than all the consensus clients implementing it individually. You can see more reasoning in #3318.

I'm going to close this as a "wont-fix" since I strongly believe that this functionality is not a responsibility of Lighthouse.

**Comment by newearthmartin** [comment]
Ok thanks for answering. The benefits that I see is are: a matter of trust, and also syncing. Installing another program requires trust in that developer. But also what if lighthouse updates something, and the other client not yet, or viceversa and there is a mix up between messages.
