### ISSUE TITLE
could not compile `simulator`

### ISSUE THREAD

**Issue by culda** [sigp/lighthouse#3636]
## Description

Getting the following during `cargo build`

![image](https://user-images.githubusercontent.com/48595067/194937393-728771e6-6e56-4e66-b358-4f8be858efdb.png)

System: 
Ubuntu 20.04.5 LTS

## Version

Please provide your Lighthouse and Rust version. Are you building from
`stable` or `unstable`, which commit?

rustc 1.64.0
stable: 01e84b71f524968f5b940fbd2fa31d29408b6581

## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.

## Expected Behaviour

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
Hey @culda. It looks like your machine probably ran out of memory during compilation. If you check `sudo dmesg -T` you'll probably see a log from the OOM killer saying that `rustc` was sent a SIGKILL.

It should work if you free up some memory and re-run it. If that doesn't work then a `cargo clean` will sometimes fix compiler caching issues.

**Comment by culda** [comment]
@michaelsproul thanks that was it. I was hoping to run this on an 8gb box, but I guess I'll try 16gb.
