### ISSUE TITLE
verkle trees: add 2 fields to ExecutionData

### ISSUE THREAD

**Issue by gballet** [sigp/lighthouse#3639]
## Description

With the verge, proofs and witness of the pre-state of an (EL) block execution are included in the blocks. As discussed with Mac and Paul, I am creating this tracking issue to create a branch with the required fields to be added to the `ExecutionData`.

## Expected Behaviour

The `ExecutionData` needs to have  two more, optional fields:

 * `VerkleProof`, a byte array of variable length
 * `VerkleKeyVals`, an array of (key, value) pairs, in which the `key` is a 32-byte vector, and `value` is a byte vector of length either 0 (missing value) or 32.

If present, these two fields should be propagated over the network with the rest of the `ExecutionData` so that other clients can inject these fields in their verkle-enabled EL.

It is currently sufficient if these fields are expected to be present since genesis, as this is for a testnet (i.e. no fork implementation is currently necessary).

**Comment by macladson** [comment]
Hi Guillaume, thanks for writing this up!

I have a basic implementation of this here: https://github.com/macladson/lighthouse/tree/verkle-trees and from my local testing it is backwards compatible with standard Geth (just passing around empty Verkle fields).

I have a few clarifying questions:
- By `ExecutionData` I assume you mean `ExecutionPayload`?
- What is the maximum length of `VerkleProof`?
- What is the maximum length of `VerkleKeyVals`?

Also, is there a PoS + Verkle enabled version of Geth that I can use for testing in my own local testnets? Something I can use to make sure that fully populated `VerkleProof` and `VerkleKeyVals` fields are being passed around correctly. If you could point me in the right direction that would be good.

Thanks!

**Comment by gballet** [comment]
> Hi Guillaume, thanks for writing this up!

And thank you for working on it!

> I have a basic implementation of this here: https://github.com/macladson/lighthouse/tree/verkle-trees and from my local testing it is backwards compatible with standard Geth (just passing around empty Verkle fields).

:tada: 

> 
> I have a few clarifying questions:
> 
>     * By `ExecutionData` I assume you mean `ExecutionPayload`?

I do!

> 
>     * What is the maximum length of `VerkleProof`?
> 
>     * What is the maximum length of `VerkleKeyVals`?

Both are arbitraty-length, but if you want a maximum number that is safe, set them to 75K each for now.

> 
> Also, is there a PoS + Verkle enabled version of Geth that I can use for testing in my own local testnets? Something I can use to make sure that fully populated `VerkleProof` and `VerkleKeyVals` fields are being passed around correctly. If you could point me in the right direction that would be good.

There isn't, I naively thought it'd be easier for you to make a cl without an el than the other way around :sweat: I'll ping you when I got it to work.

**Comment by gballet** [comment]
@macladson I have created a test branch here https://github.com/gballet/go-ethereum/pull/136 with the instructions on how to test it with your branch. Let me know if you encounter any issue.

**Comment by macladson** [comment]
Will close this for now. Refer to https://github.com/sigp/lighthouse/issues/4042
