### ISSUE TITLE
Track block proposals in the validator monitor

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3643]
## Description

Making the [validator monitor](https://github.com/sigp/lighthouse/blob/stable/beacon_node/beacon_chain/src/validator_monitor.rs) track block proposals would help us raise alerts if there has been a missed proposal by a local/monitored validator. This has been requested several times and makes a lot of sense, especially now we have builders as an additional failure point.

## Implementation

Considering this briefly, I think we could track missed proposals in two ways:

1. Use [ValidatorMonitor::process_valid_state](https://github.com/sigp/lighthouse/blob/01e84b71f524968f5b940fbd2fa31d29408b6581/beacon_node/beacon_chain/src/validator_monitor.rs#L294-L296) to reading the proposers for the current epoch and then look at `latest_block_roots` for skip slots.
2. Add a new `ValidatorMonitor::process_head_state` method which works similar to the previous method, but only takes states which were elected as the head (rather than *all* states).

The issue with (1) would be that relatively weight-less, obscure heads may trigger a rather alarming "missed block" alert.

A downside both approaches is that it would only register a missed block once a subsequent block has been imported. I'm not hugely concerned with this since we should already be raising CRIT logs whenever a block production fails. The edge-case here would be a failure in block *propagation*, which presently raises no logs. All this considered, we'd likely be registering the proposal failure within 12-24s and given the relatively infrequent nature of block proposal I'm comfortable with this slight delay.

**Comment by michaelsproul** [comment]
Sounds like a nice addition. @tthebst has done some related work in https://github.com/sigp/lighthouse/pull/3635 which we could build on to track misses as you suggest

**Comment by paulhauner** [comment]
#3727 and #3728 are some small changes to the validator monitor that I want to get included before we start on this one.

**Comment by paulhauner** [comment]
Closing as a duplicate with #3414
