### ISSUE TITLE
Release CI: `set-output` is deprecated and will be disabled

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3656]
## Description

The `release` CI is giving [this error](https://github.com/sigp/lighthouse/actions/runs/3324632202/jobs/5496437389#step:2:10):

```
Run echo "::set-output name=VERSION::$(echo ${GITHUB_REF#refs/tags/})"
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

I haven't looked into this, but I assume we need to make some change.

**Comment by michaelsproul** [comment]
started showing on the test-suite recently too

**Comment by michaelsproul** [comment]
I'm going to fix this while making our protobuf install requests use the github token (continuation of https://github.com/sigp/lighthouse/pull/3621)
