### ISSUE TITLE
Beacon node fails to send metrics to remote endpoint

### ISSUE THREAD

**Issue by gsvpers** [sigp/lighthouse#3667]
## Description

Beacon node configuration that used to be capable of sending metrics to beaconcha.in now fails. Validator uses the same configuration and works fine.

## Version
3.1.2, 3.2.0, 3.2.1

## Present Behaviour

ERRO Failed to send metrics to remote endpoint, error: StatusCode(400), service: monitoring_client

## Expected Behaviour

Should only be seeing the log: INFO Sending metrics to remote endpoint.   endpoint: https://beaconcha.in

## Steps to resolve

Validated this configuration: 

lighthouse bn \
  --staking \
  --validator-monitor-auto \
  --metrics \
  --network mainnet \
  --datadir /home/me/thedir \
  --builder http://127.0.0.1:18550 \
  --execution-endpoint http://127.0.0.1:8551 \
  --jwt-secrets="/the/secret" \
  --monitoring-endpoint https://beaconcha.in/api/v1/client/metrics?apikey=THEKEY

Looks like it should work. Minor issue given that there is no impact to staking.

**Comment by michaelsproul** [comment]
The beaconcha.in devs have indicated that the free plan only includes one process worth of metrics, and they occasionally change how they meter this.

The workaround is to reduce the frequency that Lighthouse sends metrics: https://lighthouse-book.sigmaprime.io/advanced_metrics.html#update-period

**Comment by brddd** [comment]
> The beaconcha.in devs have indicated that the free plan only includes one process worth of metrics, and they occasionally change how they meter this.
> 
> The workaround is to reduce the frequency that Lighthouse sends metrics: https://lighthouse-book.sigmaprime.io/advanced_metrics.html#update-period

While this is true, I'm part of the "goldfish" plan which allows monitoring of two machines, and still seeing this while monitoring only one machine.

Butta mentioned a lighthouse double send bug today in the beaconcha.in discord:   https://discord.com/channels/1020286473938927627/1020286475352424482/1042358746883555338 

```
Is your app reflecting the data correctly regardless?
it's possible that this is similar to the Lighthouse-monitoring "bug" where it sends the requests twice and causes this error; but the mobile app just displays everything as expected
the limit is 1req/min , so maybe you can adjust the publish interval flag?
```

I have tweaked the metrics update period to reduce the number of errors, but still see it.   Is the above lighthouse monitoring "bug" known?

**Comment by gsvpers** [comment]
same.
