### ISSUE TITLE
Add standard API for fork choice nodes

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3669]
## Description

There's a new HTTP API for dumping fork choice that we should implement: https://github.com/ethereum/beacon-APIs/pull/232.

## Version

Lighthouse v3.2.1

**Comment by kausikds** [comment]
@michaelsproul Can you give some more context of what should be the functionality of the API?

**Comment by michaelsproul** [comment]
Hey @iKausik, happy to provide more context.

Fork choice is the process by which Lighthouse chooses the head block. To do this it keeps an in-memory store of all the blocks and attestations that it has seen in a [`ForkChoice`](https://github.com/sigp/lighthouse/blob/6d5a2b509fac7b6ffe693866f58ba49989f946d7/consensus/fork_choice/src/fork_choice.rs#L341-L353) struct, which internally contains a [`ProtoArray`](https://github.com/sigp/lighthouse/blob/6d5a2b509fac7b6ffe693866f58ba49989f946d7/consensus/proto_array/src/proto_array.rs#L139-L150).

The new API will give us a way to view this data in a standard format, allowing it to be used with tools like visualisers. There's already a Lighthouse-specific API at `/lighthouse/proto_array` which dumps the proto array in a _non-standard_ format, so the implementation of the new API can draw inspiration from its implementation [here](https://github.com/sigp/lighthouse/blob/6d5a2b509fac7b6ffe693866f58ba49989f946d7/beacon_node/http_api/src/lib.rs#L2764-L2779). The main difference is that the `ProtoNode`s of our `ProtoArray` need to be mapped into the `Node` type defined by the spec here: https://github.com/ethereum/beacon-APIs/blob/ff896567205d6256e1cc69b0cdcd007a9f61adda/types/fork_choice.yaml#L1-L31. We also need to add in the `justified_checkpoint` and `finalized_checkpoint` from the `ForkChoiceStore`.

**Comment by yuroitaki** [comment]
Hi I am interested in taking this up! So far I have successfully installed lighthouse and the local development environment, read about lighthouse architecture and its relationship with execution clients, played around with ganache — am ready to look into this issue and will post any questions in Discord!

**Comment by michaelsproul** [comment]
Closed by #4003
