### ISSUE TITLE
Add a guide to running a full node to the book

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3672]
## Description

Now that the merge has occurred, our docs look a bit strange, because the instructions for running a node are split between several pages, including [Merge Migration](https://lighthouse-book.sigmaprime.io/merge-migration.html). I think it would be nice to have a page that steps through setting up a full node at a high-level, including checkpoint sync and connecting to the EL.

This would also be useful for users who want to run nodes without validating, for whom the current [Become a validator](https://lighthouse-book.sigmaprime.io/mainnet-validator.html) page is not relevant.

## Steps to resolve

* Write up a nice new page for the book on how to run a full node, including how to use checkpoint sync and connect to the execution layer. I think this should be written in a style that centres the `lighthouse` binaries and its flags, with no reference to e.g. `systemd` or Docker.
* Link the new page high in the table of contents. I think a sensible order might be:
  1. Introduction
  2. Installation
  3. How to run a node
  4. How to become a validator
  5. \<everything else\>
* Establish redirects from old page names to relevant new ones. The deprecated pages could live in a separate section at the very end of the book (or be hidden from the ToC?).

**Comment by kevinbogner** [comment]
I'm able to help here since I just did the setup a few days ago:)

PR should be created this week.

**Comment by michaelsproul** [comment]
Implemented in #3681! :tada:

We can still come back to refactor the "Become a validator" docs so I'll leave this issue open until then
