### ISSUE TITLE
Feature request: extend global validator metrics

### ISSUE THREAD

**Issue by agermain** [sigp/lighthouse#3678]
## Description

Currently, `validator_monitor_validators_total` is a useful metric that can help infer the amount of expected attestations. However, Lighthouse emits high-cardinality metrics (validator-granularity) that make it an expensive operation (both to store and to query) to calculate the overall included/produced attestations by all managed validators.

## Version

N/A

## Present Behaviour

One would need to do a Prometheus `count()` over a metric like `validator_monitor_prev_epoch_attestation_block_inclusions`.

## Expected Behaviour

It would be a great feature to have some metrics along the lines of `validator_monitor_produced_attestations_total`/`validator_monitor_expected_attestations_total`/`validator_monitor_included_attestations_total`.

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by paulhauner** [comment]
Resolved via #3728 🎉
