### ISSUE TITLE
`publish-crate` CI is failing

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#3679]
## Description

I just pushed the `eth2-ssz-v0.4.1` tag to trigger a publish to crates.io, however the [run failed](https://github.com/sigp/lighthouse/actions/runs/3381566007/jobs/5615610385) with:

```
Run ./scripts/ci/publish.sh consensus/ssz eth2_ssz "$TAG"
Verifying if eth2_ssz v0.4.1 can be released
expected to release version 0.4.1, but Cargo.toml contained ///home/runner/work/lighthouse/lighthouse/consensus/ssz#eth2_ssz@0.4.1
Error: Process completed with exit code 1.
```

I think it's an issue with [this line](https://github.com/sigp/lighthouse/blob/6d5a2b509fac7b6ffe693866f58ba49989f946d7/scripts/ci/publish.sh#L29). Locally, I get:

```
cargo pkgid | sed -n 's/.*:\(.*\)/\1/p'
///home/paul/development/lighthouse/consensus/ssz#eth2_ssz@0.4.1
```

I suspect that we need to modify the regex to capture what's following the the `@`. However, when looking at the structure of the current regex, I'm wondering what has changed to break this :thinking:

**Comment by michaelsproul** [comment]
I wonder if we should add crate publishing to the release CI?

We could version the deps by Lighthouse's version and bump them all in one go. It would violate semantic versioning for the deps and lead to some versions with the same content and different version numbers, but at least the crates would get published consistently. Users downstream might also like the match between Lighthouse versions and crate versions.

**Comment by jimmygchen** [comment]
Closing this as the publish crate workflow no longer exists in this repo, and is now in individual repos with its own CI workflows.
