### ISSUE TITLE
Execution block generator usable across forks

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3690]
## Description

The execution block generator has become integral to a lot of our local testing. Currently it can only produce blocks with merge payload, but we should make sure it is able to work correctly across forks, and produce valid/invalid blobs as well. This will be important to fleshing out our internal testing across the new forks.

https://github.com/sigp/lighthouse/blob/stable/beacon_node/execution_layer/src/test_utils/execution_block_generator.rs

**Comment by michaelsproul** [comment]
I think I've got this working in https://github.com/sigp/lighthouse/pull/2860. I cherry-picked @pawanjay176's changes from #2755 and made a few tweaks to get the tests passing.

**Comment by realbigsean** [comment]
Beast! Good reminder for me to re-review that PR 😅

I think there might still be some 4844 specific work to test blob validation, so I'll leave the issue open for now

**Comment by realbigsean** [comment]
resolved for deneb in #4223
