### ISSUE TITLE
Local payload comparison 

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3699]
## Description

https://github.com/sigp/lighthouse/issues/3517 implemented an absolute comparison of a configured value to the value in a claimed "builder bid", but once https://github.com/ethereum/execution-apis/issues/307 is added, we can change the configurable value to be the margin a builder bid has to exceed the local payload by.

**Comment by pawanjay176** [comment]
Related https://github.com/sigp/lighthouse/pull/3646

**Comment by michaelsproul** [comment]
Labelling this `capella` as we've added the blockValue field on the `capella` branch but are not yet utilising it

**Comment by michaelsproul** [comment]
Completed in #3934 :tada:

**Comment by allboxes** [comment]
@michaelsproul @ethDreamer , does #3934 repurpose `--builder-profit-threshold` to allow users to set a margin by which the builder bid has to exceed the local payload?  As best I could tell `--builder-profit-threshold` is still only used in the original separate flow comparing builder block value to a fixed block value.  If that's the case could this be reopened to make `--builder-profit-threshold` (or a new flag) a margin by which the remote block value has to exceed to local block value?

**Comment by ethDreamer** [comment]
> @michaelsproul @ethDreamer , does #3934 repurpose `--builder-profit-threshold` to allow users to set a margin by which the builder bid has to exceed the local payload?  As best I could tell `--builder-profit-threshold` is still only used in the original separate flow comparing builder block value to a fixed block value.  If that's the case could this be reopened to make `--builder-profit-threshold` (or a new flag) a margin by which the remote block value has to exceed to local block value?

Correct, I hadn't repurposed the flag yet. I'll have to add that as well. Thanks
