### ISSUE TITLE
Use optimistic execution processing when syncing the finalized chain

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3704]
## Description

Presently Lighthouse will always send execution payloads to the EL, even while syncing.

This results in sync being really slow when it has any substantial distance to cover, with speeds usually sitting below the 1 slot/second mark because of how long the EL takes to respond.

I think we could drastically improve this situation by _not_ sending the execution payloads while syncing the finalized portion of the chain. In other words, we could import blocks optimistically while syncing and then mark them valid only on occasional calls to fork choice (which will usually give us a `VALID` response, or an `INVALID` response with a latest block hash that we can backtrack to). From the consensus-side, I think all the machinery is already there to support this.

## Steps to resolve

I think we can modify the `PayloadNotifier` to set the `payload_verification_status` to `Optimistic` based on a parameter threaded through from sync:

https://github.com/sigp/lighthouse/blob/aa022f46855df2a1420a6a80a788c73dc2779aa7/beacon_node/beacon_chain/src/execution_payload.rs#L45-L72

Threading that parameter through might be more involved as it will have to go through all of `block_verification`. A new type like `FinalizedSignatureVerifiedBlock` might be necessary.

## Version

Lighthouse v3.2.1

**Comment by pawanjay176** [comment]
This is really cool :ok_hand:

**Comment by michaelsproul** [comment]
Implemented in #3738 and will be in the release following v3.3.0!
