### ISSUE TITLE
Add `finalized` to HTTP API responses

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3708]
## Description

We should implement https://github.com/ethereum/beacon-APIs/pull/254.

## Steps to resolve

We can likely use a slot comparison against fork choice's `finalized_checkpoint.epoch` for most of these.

**Comment by danielrachi1** [comment]
I'd like to solve this :)

I'm currently trying to understand how beacon_node/http_api works and how could I implement the new flag. I'll probably be able to open a PR this weekend.

**Comment by michaelsproul** [comment]
Great! Thank you!

Let us know if you need any help

**Comment by michaelsproul** [comment]
@danielrachi If you'd like to put up a draft PR with the approach you're taking I'd be happy to check over it before you go to the effort of threading it through all the APIs. Sometimes handling the lock ordering and atomicity for these sorts of things can be a bit nuanced. The `execution_optimistic` flag demonstrates the sorts of patterns we usually use.

**Comment by danielrachi1** [comment]
Hi, I was busier than expected during the weekend, so I couldn't work on this. I'll follow your suggestion and open a draft PR as soon as I make any progress / decide an approach. (I expect to start working on this again on Wednesday.)

I hope this taking longer than expected is not a problem.

**Comment by michaelsproul** [comment]
Not a problem at all, we are very glad of any help :blush: If you weren't working on it, the issue would probably be sitting here neglected

**Comment by michaelsproul** [comment]
Closed by #3753! :tada:
