### ISSUE TITLE
JSON log output for testing

### ISSUE THREAD

**Issue by mslipper** [sigp/lighthouse#374]
## Description

Hi Lighthouse team,

Antoine Toulmne and I are working on an ETH2 test runner that needs access to the state of the clients under test at each block. Currently, we're doing this by exposing a JSON log with the following format:

```
{
   "date":1557296388510,
   "index":1,
   "slot":1,
   "epoch":0,
   "block_root":"0x774D273A6A67482FAA5627A3F3CD3D55E2074EC89BDCC448873DA7B0F3F52C1B",
   "block_parent_root":"0x73F42156F0E9611F710891CFB059EDFCA7CB18CBFF60DC0A6CB2ED39678B4782",
   "block_body":"0x0DE2E04B0BF89EFEC669C00EF41BE42E8F93218B85CC6272C6CCD95B8399648D",
   "last_justified_block_root":"0x73F42156F0E9611F710891CFB059EDFCA7CB18CBFF60DC0A6CB2ED39678B4782",
   "last_justified_state_root":"0x38F7F34A166FB777C8647C66725F12454DCED268024BA5054C20ABF31CE7A213",
   "last_finalized_block_root":"0x73F42156F0E9611F710891CFB059EDFCA7CB18CBFF60DC0A6CB2ED39678B4782",
   "last_finalized_state_root":"0x38F7F34A166FB777C8647C66725F12454DCED268024BA5054C20ABF31CE7A213",
   "validators":[
      {
         "pubkey":"(05209b1ea72bd2c1a430cda13d79cfbe617694c18b374a0fbf2a85aa74f6f582373f4ace1ac7b996969bc7540125ce84,08b081dc8249ef361d17510d17a193a7aee28940a9ab1fba742c1f7f9a3f9cf1288a767efcd37c750e91a8d0cf408b1f)",
         "balance":"32000000000"
      }
   ]
}
```

We were thinking that the log would be exposed by either:

1. A CLI flag to write the log to the specified directory.
2. A JSON-RPC endpoint to get the log at a specified block.

Which would your team find more amenable, and what do you think of this approach in general? To make things easier, we're happy to implement this and open a PR. I've also opened a similar issue against Prysm (https://github.com/prysmaticlabs/prysm/issues/2574).

## Present Behaviour

As far as I am aware, there is no present behaviour to support this feature.

## Expected Behaviour

N/A - not a bug.

## Steps to resolve

N/A - not a bug.

**Comment by paulhauner** [comment]
Hi @mslipper,
  Thanks for reaching out!

I'll start with our present plans for APIs, then ask a couple of questions about this format.

We are intending to provide two APIs average users just care about (1) and advanced users can use (2):

1. HTTP-REST (JSON) "General Purpose" API: Basically the same functionality as existing Eth1 clients. Provides information about the canonical chain and allows, allows DB lookups, etc. (There's a [spec issue](https://github.com/ethereum/eth2.0-specs/issues/1012) around this.
2. Websocket stream: Verbose stream of blocks, attestations, etc along with some judgements about them (valid, invalid, etc).

In your format, does `block_root` refer to the clients "best" block root (the latest in the canonical chain)? If so, what are you thoughts about querying this info from the REST API (1) or the Websocket API (2)?

I guess there's two things to unpack in that question:

- Do either of those APIs match your requirements, or are your requirements unique?
- If either of these APIs do suit, what do you think about using these transport methods? (They're both very "web standard".)

Keen to hear your thoughts :)

P.S. I think you missed a find-replace in the first line :smile:

**Comment by mslipper** [comment]
Man, my bad for that find-replace. That's what I get for not proofreading. Hope I didn't come across as impersonal.

`block_root` does refer to the client's "best" block root (@atoulmne can you confirm?). Regarding the Websocket API, if it streams the same information as is currently included within the proposed JSON schema then I'm all for using it. It's relatively trivial for us to write a wrapper that consumes the Websocket API and dumps it into the appropriate JSON format. Have you implemented the WS API already, or is that something you'd like help with?

**Comment by paulhauner** [comment]
No worries, happens to the best of us! I appreciate you reaching out.

We don't have the WS API yet, nor have we spec'd it out. I imagine that'll happen in the coming weeks. However, I'm thinking that your request sounds like it would be best served from the HTTP API, considering you're after _canonical_ info, not just _all_ info, do you agree?

Luke has been specifying the validator HTTP API via OpenAPI [here](https://github.com/ethereum/eth2.0-specs/pull/1069) and is going to start our implementation next week. Perhaps we could work together to define the endpoint in OpenAPI and see if the other clients would be open to standardising on it? I'm wary not to try and scope-creep your task, just thowing ideas around :)

**Comment by paulhauner** [comment]
Just looking at the equivalent issue on the Prysm repo and saw this:

> I believe we'd process it post test run.

For testing we have been using a function we (inelegantly) named "chain dump". It produces an array of these objects, from genesis through to head:

```python
(
  "beacon_block": BeaconBlock,
  "beacon_block_root": Hash256,
  "beacon_state": BeaconState,
  "beacon_state_root": Hash256,
)
```
Perhaps this is the info you're after?

**Comment by mslipper** [comment]
Yes, this is the info we're after! How shall I call that method? Is it accessible via CLI/RPC, or is it something I'll have to write a tool to link against?

**Comment by paulhauner** [comment]
I'm going to close this one, I feel like it's no so relevant anymore.

Feel free to re-open if you disagree :)
