### ISSUE TITLE
Fix multiline output for release notes on CI

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3750]
## Description

The release CI crashes when outputting the multiline string for the release notes. We should use a "here document" like `<<<EOF` to escape the mulitline string.

CI crashing: https://github.com/sigp/lighthouse/actions/runs/3537291461

Fix (option 2): https://trstringer.com/github-actions-multiline-strings/

Testing will require running the release flow on a dummy release on someone's fork.

## Version

Should be fixed before v3.4.0

**Comment by paulhauner** [comment]
Resolved via #3813
