### ISSUE TITLE
GUI - Grafiti Api

### ISSUE THREAD

**Issue by rickimoore** [sigp/lighthouse#3766]
## Description

The UI design has a feature for viewing and editing validator graffiti. Ui will need possibly two endpoints: GET, POST to the validator graffiti.

<img width="773" alt="Screenshot 2022-12-01 at 16 21 07" src="https://user-images.githubusercontent.com/12932889/205105186-7e3ab437-d49d-46db-a44a-257c47100361.png">

## Expected Behaviour

- Be able to see current validator's graffiti
- Be able to update said graffiti

**Comment by AgeManning** [comment]
Maybe for the MVP we just make this a GET. 

This should be implemented on the VC and it just responds with a list of validator index's and their corresponding graffiti. 

I.e The graffiti that would be used for the next block.

**Comment by jimmygchen** [comment]
GET graffiti implemented in #3779 and PATCH graffiti implemented in #4417
Closing this 🎉
