### ISSUE TITLE
Enforce minimum validator count

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#379]
## Description

There are assumptions some assumptions made about the minimum validator count (e.g., there is at least one validator for each slot per epoch).

Presently we do not enforce a minimum validator count, we just don't spin up systems with too few validators. This works for testing, but will soon become frustrating. We should throw a major error (effectively a panic) if a chain is started without enough validators.

**Comment by michaelsproul** [comment]
Definitely agree, the errors you get at the moment with too few validators are very strange

**Comment by paulhauner** [comment]
There has been some progress towards this here: 399ad6e

**Comment by paulhauner** [comment]
Closing this since we basically never spin up *really* small networks anymore and it's not relevant for mainnet
