### ISSUE TITLE
Make logs for invalid executon blocks louder

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3814]
## Description

We sometimes only log debug-level `Batch processing failed` logs for errors like `ParentExecutionPayloadInvalid` when we should log at `WARN` level or higher.

See: https://discord.com/channels/605577013327167508/605577013331361793/1053210521991651348

## Steps to resolve

Modify the error handling in the beacon processor so that these errors (which usually indicate a corrupt EL database) are surfaced in a more obvious way.

**Comment by danaAmin23** [comment]
I have the fix
