### ISSUE TITLE
Implement a flag for logging to file

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#382]
## Description

We use `slog` to log to CLI for both the `beacon_node` and `validator_client`.

It's working well but we also need the option to log to file so we can examine the logs later.

I think the best UX would be adding a CLI flag that allows setting the debug level for the log file, then dumping into some JSON file.

## Steps to resolve

1. Figure out if there's some established flag by geth/parity for logging to file. If so, use that.
1. See if there's some standard "logging" directory accessible in `std::path` (or w/e). If so, use that. Alternatively, add another flag to specify where the logs should go with a sensible default -- probably in the `~/.lighthouse` dir.(If there's some Eth1.x standard here, go for it).
1. Figure out how to make `slog` dump to JSON.

FYI, all the CLI flags and `slog` init code is [here](https://github.com/sigp/lighthouse/blob/master/beacon_node/src/main.rs#L10).

**Comment by AgeManning** [comment]
Hit me up if you have any issues with CLI options or misc beacon client things.

**Comment by paulhauner** [comment]
This was completed in #414
