### ISSUE TITLE
Update `eth2_ssz` version on crates.io

### ISSUE THREAD

**Issue by mempirate** [sigp/lighthouse#3824]
## Description

In this repo, the current version of the `eth2_ssz` crate is `0.4.1`, but on crates.io, the last published version is `0.4.0`.
## Version

Latest

## Present Behaviour

When downloading dependencies that rely on `0.4.1`, like the `lighthouse_network` crate ([`Cargo.toml`](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/Cargo.toml)), cargo throws an error because it can't find said version on crates.io.

## Expected Behaviour

There should be no issues when requiring `eth2_ssz = "0.4.1"` in Cargo.toml.

## Steps to resolve

Publish the latest version of the `eth2_ssz` crate to crates.io.

**Edit**
The crates below also have outdated versions:
* eth2_ssz_types
* eth2_serde_utils
* eth2_hashing
* tree_hash

**Comment by mempirate** [comment]
I see that they're patched in the root Cargo.toml, so it's not that important unless we're trying to work with separate modules

**Comment by michaelsproul** [comment]
Hi @jonasbostoen, we're in the process of extracting the common crates into their own repos, partly to ensure they remain up to date on crates.io. I'm on leave now, but in a few weeks I'll finish publishing them. So far we've just published `ethereum_hashing`.

You're right that using `[patch]` is the way to work around this. Example here: https://github.com/michaelsproul/blockdreamer/blob/main/Cargo.toml

**Comment by michaelsproul** [comment]
SSZ crates are published now, will take me a bit longer to get to the others: https://crates.io/crates/ethereum_ssz

**Comment by mempirate** [comment]
Thanks for the quick response!
