### ISSUE TITLE
Deposit signatures & pubkeys may not be valid BLS

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#384]
## Description

The deposit contract does not verify BLS signatures or pubkeys and therefore they may contain arbitrary bytes.

Presently we would fail to parse any `Deposit` with an invalid signature or pubkey, this is a consensus-breaking bug.

## Steps to resolve

My suggestion is to create a `MaybeInvalidSignature` (or more aptly named) wrapper around `Signature` that permits parsing invalid bytes and implement it only for `Deposit`. That way we get to keep our parsing safety for other objects.

EDIT: I updated this issue because it needs to cover `PublicKey` as well as `Signature`.

**Comment by michaelsproul** [comment]
A wrapper around `Signature` sounds like a good option

**Comment by kirk-baird** [comment]
You could have a struct `SignatureBytes([u8; 96])` and implement a few methods such as
- `toSignature()`
- `isValid()`

**Comment by blacktemplar** [comment]
I will have a look into this :)

**Comment by paulhauner** [comment]
Thanks for the initiative @blacktemplar!

@pawanjay176 is working on the deposit processing over in #463, so the eth1-rpc side of things is not in the code-base presently.

We could still create a wrapper struct and update state processing as such, however, that should be done off the `v0.8` branch. If you can wait a day or two we'll have v0.8 in master. Alternatively, you could work off the `v0.8` branch :)

**Comment by paulhauner** [comment]
`v0.8` has been merged into master now, so as long as you're based off `master` you'll be fine :)
