### ISSUE TITLE
implementation CLI request on 4844

### ISSUE THREAD

**Issue by mrabino1** [sigp/lighthouse#3843]
please allow for a CLI parameter to let lighthouse to use a different data directory for the 4844 data.

eg

./lighthouse bn --4844-data-dir /path/to/4844storage  

Reason: The 4844 data structure is designed to not be processed and rather just be temporarily stored. Further this data should have a low disk read write access requirement so another non-SSD media could be used. 

@realbigsean

**Comment by pawanjay176** [comment]
Do you mean a separate datadir for blobs?

**Comment by mrabino1** [comment]
yes, that is the thinking.

**Comment by realbigsean** [comment]
I think this is definitely a feature to prioritize, it'll probably make it much easier for stakers to upgrade their setup

**Comment by michaelsproul** [comment]
One case to cover that I was just discussing with @emhane

We need to remember whether a separate blob freezer is in use and ensure that this continues to be the case. I.e. if a user has their blobs separate we record that in the hot DB and error on start-up if no separate freezer is provided. Conversely if a user _doesn't_ have a separate blob freezer we record _that_ on disk and error if they try to provide one. I think a `bool` in `BlobInfo` should do it.

Later on we can implement clever things like copying between DBs, if that proves desirable. I suspect some users will also be happy with the existing hot/freezer split for managing storage (e.g. you could move your freezer to a slower drive before 4844 and then when 4844 happens all your old blobs will end up there too).

**Comment by realbigsean** [comment]
completed in https://github.com/sigp/lighthouse/pull/3869
