### ISSUE TITLE
Accept local `SignedBlsToExecutionChange` into op pool pre-Capella

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3882]
## Description

Currently, we gossip validate local (from the beacon HTTP API) `SignedBlsToExecutionChange` messages before adding them to the op pool. This means we ignore pre-Capella messages. I think the UX would be improved if you could submit locally at any point before the capella fork. It sounds like this is what Prysm intends to implement.

**Comment by michaelsproul** [comment]
Completed in #3892
