### ISSUE TITLE
Disallow v14/v15 schema downgrade after Capella

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3899]
## Description

We currently have a database schema downgrade for the Capella schema (v14). Due to the recent addition of the `HistoricSummaries` column in the freezer database it will be unsafe to apply this schema downgrade once Capella has occurred. As such we should adjust the `downgrade_from_v14` logic to error if Capella has already arrived.

https://github.com/sigp/lighthouse/blob/26787412cd5e5447f00123b4e4afe5d779765b0f/beacon_node/beacon_chain/src/schema_change/migration_schema_v14.rs#L40-L43

**Comment by paulhauner** [comment]
I believe this was fixed in #4004, please re-open if I'm wrong 🙏
