### ISSUE TITLE
Can't change EPOCHS_PER_ETH1_VOTING_PERIOD on local testnet

### ISSUE THREAD

**Issue by samlaf** [sigp/lighthouse#3930]
## Description

I'm working with the [local_testnet](https://github.com/sigp/lighthouse/tree/stable/scripts/local_testnet) scripts.
I'm trying to test deposits and withdrawal_credentials repointing, so I need to change `EPOCHS_PER_ETH1_VOTING_PERIOD` because I simply can't wait the default 64 epochs before a deposit is even considered.

However, nothing seems to work.
the [lcli new-testnet](https://github.com/sigp/lighthouse/blob/38514c07f222ff7783834c48cf5c0a6ee7f346d0/scripts/local_testnet/setup.sh#L26) command does not have a --epochs-per-eth1-voting-period (I tried grepping a bunch of related terms), and manually adding `EPOCHS_PER_ETH1_VOTING_PERIOD: "1"` to the generated config file `~/.lighthouse/local-testnet/testnet/config.yaml` doesn't work either.

When I run `curl localhost:$VN_HTTP_API_PORT/lighthouse/spec -H "Authorization: Bearer $(curl localhost:$VN_HTTP_API_PORT/lighthouse/auth | jq .token_path | xargs cat)" | jq .data.EPOCHS_PER_ETH1_VOTING_PERIOD` I always get 64. Is it even possible to change this variable in lighthouse? How else should I go about integration testing deposits + withdrawals?

## Version

```
Lighthouse v3.4.0
BLS library: blst
SHA256 hardware acceleration: false
Specs: mainnet (true), minimal (false), gnosis (false)
```

**Comment by michaelsproul** [comment]
The deposit voting period is a compile-time constant. In Ethereum spec terms it's part of the [preset](https://github.com/ethereum/consensus-specs/tree/dev/presets), which is represented in Lighthouse by the `EthSpec` trait and the types that implement it:

https://github.com/sigp/lighthouse/blob/stable/consensus/types/src/eth_spec.rs

We support 3 presets: minimal, mainnet and Gnosis. You could use the minimal preset which sets `EPOCHS_PER_ETH1_VOTING_PERIOD` to `4`. On `lcli` you can do this by supplying `--spec minimal`. You'll need to make sure that you compile Lighthouse with minimal spec support, as we usually only use the minimal preset for tests and our released binaries have it disabled. The feature is called `spec-minimal` and can be enabled using the `FEATURES` env var when building, see: https://lighthouse-book.sigmaprime.io/installation-source.html#feature-flags

You might also be interested in #3033, which goes in to more detail about how we could improve this in future.

**Comment by samlaf** [comment]
Hah, thanks for explaining! I've flipped through the specs a hundred times already, but never realized the difference between presets and configs. Feels weird that presets being compile-time is mandated by the specs... is the code really that different between the three supported specs that most of the spec variables couldn't be passed at runtime without significantly affecting resource usage?

So it seems like right now the best way to test a full deposit->withdrawal loop is to use the minimal present and the configs in the local_testnet, which should give deposit times of 32 seconds (`EPOCHS_PER_ETH1_VOTING_PERIOD` * `SLOTS_PER_EPOCH` = 4 * 8). And if I need faster than that I would need to create a new custom spec and build from source.

Thanks, I'll give the minimal preset a spin.

**Comment by michaelsproul** [comment]
> Feels weird that presets being compile-time is mandated by the specs... is the code really that different between the three supported specs that most of the spec variables couldn't be passed at runtime without significantly affecting resource usage?

It's not that it's _mandated_ but allowed. Having compile-time values lends itself nicely to incorporating those values into types like `VariableList<T, N>` and `FixedVector<T, N>`, which saves passing `N` (the length/max length) around at runtime and enables simpler generic code. We _could_ change everything to be dynamic at runtime for minimal performance impact but it would be a huge refactor at this point as the compile-time constants are everywhere. Some other clients do the same as us (Nimbus) while others are dynamic (AFAIK Lodestar, maybe some others).

**Comment by michaelsproul** [comment]
Closing as dupe
