### ISSUE TITLE
Remove Router/Processor Code

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#3938]
## Description

As Lighthouse has evolved the `network::Router` and `network::Processor` have more or less become redundant. They could be grouped into a single object or maybe removed entirely.

The enums being used to relay information between the `lighthouse_network` crate and the `network` crate, specifically in sync, could probably be revisited as we are discovering in-elegant edge cases with large network upgrades.

**Comment by danielrachi1** [comment]
I'd like to take this.

I'll start by checking out `beacon_node/network/src/router/processor.rs` and `beacon_node/network/src/router/mod.rs` and see what can I do from there.

**Comment by divagant-martian** [comment]
Let me know if you need help. This should be a big but straightforward refactor

**Comment by danielrachi1** [comment]
@divagant-martian I started working on this at #4002.

This far I've merged both types and deleted some redundant functions. I'm not sure about what to do next, so any feedback would be appreciated.
