### ISSUE TITLE
Error updating deposit contract cache

### ISSUE THREAD

**Issue by hungzinza** [sigp/lighthouse#3939]
## Description

I deployed lighthouse + nethermind on k8s without _--checkpoint-sync-url._
I used this list param for lighthouse container:
```
["--testnet-dir=/data/lighthouse/network_config", "--datadir=/data/lighthouse", "beacon_node", "--port=9000",
      "--http", "--disable-upnp", "--http-address=0.0.0.0", "--http-port=4000",
      "--boot-nodes=enr:-L64QOijsdi9aVIawMb5h5PWueaPM9Ai6P17GNPFlHzz7MGJQ8tFMdYrEx8WQitNKLG924g2Q9cCdzg54M0UtKa3QIKCMxaHYXR0bmV0c4j__________4RldGgykDE2cEMCAABv__________-CaWSCdjSCaXCEi5AaWYlzZWNwMjU2azGhA8CjTkD4m1s8FbKCN18LgqlYcE65jrT148vFtwd9U62SiHN5bmNuZXRzD4N0Y3CCIyiDdWRwgiMo",
        "--execution-jwt=/data/lighthouse/jwtsecret", "--execution-endpoint=http://127.0.0.1:8551"]
```

this is network config I added:
```
#!/bin/sh

rm -rf /data/lighthouse/network_config
mkdir -p /data/lighthouse/network_config
cd /data/lighthouse/network_config
echo "Init LIGHTHOUSE....."
wget https://github.com/gnosischain/configs/raw/main/chiado/config.yaml &&
wget https://github.com/gnosischain/configs/raw/main/chiado/genesis.ssz &&
wget https://github.com/gnosischain/configs/raw/main/chiado/deploy_block.txt

```
After I deployed, lighthouse show this error:

_**ERRO Error updating deposit contract cache   error: Failed to get remote head and new block ranges: EndpointError(FarBehind), retry_millis: 60000, service: deposit_contract_rpc**_

## Version
Docker image: sigp/lighthouse:v3.4.0

Please help me. Thank you so much

**Comment by michaelsproul** [comment]
Once your Nethermind node finishes syncing receipts then Lighthouse will be able to index the deposit contract logs. In the meantime you'll still be able to attest (assuming Nethermind has finished state sync).
