### ISSUE TITLE
REST API integers not quoted

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#3949]
## Description

The capella state fields `next_withdrawal_index` and `next_withdrawal_validator_index` are not quoted in the REST API.

## Version
Built from source for zhejiang

```
lighthouse --version
Lighthouse v3.4.0-f615fb0
BLS library: blst
SHA256 hardware acceleration: true
Allocator: jemalloc
Specs: mainnet (true), minimal (false), gnosis (false)
```

## Present Behaviour

```
curl -s http://localhost:5052/eth/v2/debug/beacon/states/head|jq .data.next_withdrawal_index,.data.next_withdrawal_validator_index
92250
48032
```

## Expected Behaviour

Values should be quoted integers.

**Comment by michaelsproul** [comment]
Thanks! One day we'll make an API that you don't find quoting issue in :sweat_smile:

Will be fixed by #3967

**Comment by aertoria** [comment]
Overall what's the status for Capella support in lighthouse?

**Comment by michaelsproul** [comment]
@aertoria We have 99% implemented in the `capella` branch and are preparing to merge that to `unstable` for imminent release on testnets

**Comment by aertoria** [comment]
Awesome. Once that's done. Please ping us the stable version id and we will launch it in our node provider platform

**Comment by michaelsproul** [comment]
@aertoria There'll be lots of fanfare on our Discord announcements channel, Twitter and mailing list :tada:
