### ISSUE TITLE
Validator client `first_success` swallows intermediate errors

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#3985]
## Description

In the validator client's `first_success` function, errors are collected as different endpoints are tried. If several endpoints are tried before one that succeeds, the details of those errors will be lost when the function returns early here:

https://github.com/sigp/lighthouse/blob/38514c07f222ff7783834c48cf5c0a6ee7f346d0/validator_client/src/beacon_node_fallback.rs#L428

In the logs from #3963 it seems like an offline primary BN caused delays when proposing via the secondary BN, possibly due to timeouts & errors at this stage.

It would be good to have logs (at least at `debug!` level) of errors as they occur in this function. However, this may be (partially) obsoleted by @macladson's improvements for #3613.

**Comment by fl3x1324** [comment]
Any advice on how to reproduce this? I've put a debug message in the Err branch to log on each failure, but I want to check and see if it's actually logging.

**Comment by michaelsproul** [comment]
@fl3x1324 Thanks! You could try running a VC with a dodgy first beacon node. It could be one that's still syncing, or you could kill it repeatedly, or try turning it off entirely. And then have a second beacon node that _is_ working.

**Comment by fl3x1324** [comment]
@michaelsproul can you try and add the ready-for-review and val-client tags? Github doesn't allow me to.

**Comment by dapplion** [comment]
- This issue should be closed, fixed by https://github.com/sigp/lighthouse/pull/4036
