### ISSUE TITLE
error during building

### ISSUE THREAD

**Issue by MaddyCrowle** [sigp/lighthouse#3987]
## Description

bash `cd lighthouse`, `make`

throws error:

`error: failed to run custom build command for `mdbx-sys v0.11.6-4 (https://github.com/sigp/libmdbx-rs?tag=v0.1.4#096da80a)``

```
Caused by:
  process didn't exit successfully: `/home/me/dev/tools/lighthouse/target/release/build/mdbx-sys-71dac4685a623d71/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"MDBX_version_info_struct_(unnamed_at_/home/me/_cargo/git/checkouts/libmdbx-rs-c1b523f5b64ff08c/096da80/mdbx-sys/libmdbx/mdbx_h_611_3)" is not a valid Ident', /home/me/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.49/src/fallback.rs:756:9
```

## Version

CentOS 7
rustc 1.67.1 (d5a82bbd2 2023-02-07)
lighthouse v3.4.0
gcc (GCC) 10.4.0

stable

I checked the file mdbx.h line 611:

```
struct {
    const char *datetime; /**< committer date, strict ISO-8601 format */
    const char *tree;     /**< commit hash (hexadecimal digits) */
    const char *commit;   /**< tree hash, i.e. digest of the source code */
    const char *describe; /**< git-describe string */
  } git;
```

Could you pls help me to resolve this issue?

**Comment by michaelsproul** [comment]
We've got this open PR to make it possible to disable MDBX: #3888. We're pinned on an old version so there's not much else we can do.

Which OS are you on? Can you use a pre-built binary?

The other reported instance of this issue was on FreeBSD.

**Comment by MaddyCrowle** [comment]
My OS is CentOS 7
Ok, got it, thanks. I'll try using pre-built binary

**Comment by michaelsproul** [comment]
Just saw another report of this for 64-bit Windows 11. I'm tempted to say we should disable MDBX by default when building from source
