### ISSUE TITLE
Blob signing HTTP endpoints

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3993]
Assigned to @jimmygchen
- implementation PR: https://github.com/sigp/lighthouse/pull/3979
- spec PR: https://github.com/ethereum/beacon-APIs/pull/302
- involves creating a cache in the beacon node for full blobs, and only sending blinded blobs to the VC

**Comment by jimmygchen** [comment]
@realbigsean 
Full blob signing flow implemented in #4075 and #4083 
I have created a new issue to track signing for the blinded flow as spec is not finalised yet. I believe we can close this one as it no longer block testing for blob decoupling?

**Comment by jimmygchen** [comment]
Blob signing for blinded flow issue: https://github.com/sigp/lighthouse/issues/4103

**Comment by realbigsean** [comment]
Completed in https://github.com/sigp/lighthouse/pull/4083
