### ISSUE TITLE
Blob signing Validator client functionality

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3994]
Assigned to @jimmygchen
- Add a new blob signing domain (this should be explicit in the new spec)
- This will eventually involve updates related to the web3signer but I don't think this will be spec'd for a bit

**Comment by jimmygchen** [comment]
Implementation in PR https://github.com/sigp/lighthouse/pull/3979

**Comment by jimmygchen** [comment]
unblinded blob signing implemented here: https://github.com/sigp/lighthouse/pull/4096

**Comment by realbigsean** [comment]
Completed in #4096
