### ISSUE TITLE
Don't try to subscribe to blob topics for Capella

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4006]
## Description

The `capella` branch currently prints a warning when it subscribes to topics after sync:

> Feb 20 06:37:04.347 WARN Failed to subscribe to topic            error: NotAllowed, topic: /eth2/988197af/beacon_block_and_blobs_sidecar/ssz_snappy, service: libp2p
> Feb 20 06:37:04.347 WARN Could not subscribe to topic            topic: /eth2/988197af/beacon_block_and_blobs_sidecar/ssz_snappy, service: network

We should modify `capella`/`unstable` so that this subscription is not attempted.

**Comment by paulhauner** [comment]
Resolved via #4016
