### ISSUE TITLE
Consider using `PublicKey` in `BlsToExecutionChange`

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#4010]
## Description

I noticed that we're using `PublicKeyBytes` in `BlsToExecutionChange`:

https://github.com/sigp/lighthouse/blob/0b6850221edca109318b227bacb5b2ebb0d89ad0/consensus/types/src/bls_to_execution_change.rs#L23-L28

I wonder if it would be more consistent and performant to use `PublicKey` (i.e., the decompressed version) instead.

The conversion from `PublicKeyBytes` -> `PublicKey` is required for signature verification and it's a crypto operation which takes *some* CPU time. Not a whole lot of CPU time IIRC, but it's nice to avoid especially when we might have 16 in a block.

If we use `PublicKey` then decompression happens during SSZ deserialization and then never again. If we use `PublicKeyBytes` then decompression happens each time we verify the signature (e.g., once we we receive it on gossip and then once when we include it in a block).

I think the only case for using `PublicKeyBytes` would be if we need to accept messages which have *invalid* public keys (like we do with `Deposit`). I don't think that's ever the case.

I don't think this is a high enough priority to be included in the `v3.5.0` release.

**Comment by michaelsproul** [comment]
Closing as @macladson decided this probably wasn't a substantial optimisation while implementing it in https://github.com/sigp/lighthouse/pull/4190. It is even less likely to be impactful now that BLS to execution changes are so infrequent
