### ISSUE TITLE
Attestation rewards endpoint returns error on pre-altair epochs on sepolia

### ISSUE THREAD

**Issue by peterbitfly** [sigp/lighthouse#4026]
## Description

The new attestation rewards epoch returns an error when querying the attestation rewards for pre-altair epochs (up to epoch 48) on the sepolia network

## Version
v3.5.0

## Present Behaviour
```
curl -s -H "Content-Type:application/json" localhost:4000/eth/v1/beacon/rewards/attestations/40 -d '[]' | jq .
{
  "code": 500,
  "message": "INTERNAL_SERVER_ERROR: unexpected error: BeaconStateError(IncorrectStateVariant)",
  "stacktraces": []
}
```

## Expected Behaviour
Rewards should be shown and no error should be thrown

**Comment by michaelsproul** [comment]
Ah, this isn't a bug so much as an unimplemented feature. Sorry, we should have publicised that the attestation rewards API is only working post-Altair. If this is a blocker for the explorer we can try to find some time to implement it.

**Comment by peterbitfly** [comment]
Thanks for your quick response. Yes we are currently in progress of migrating to the new rewards api for the rewards & income details we display on beaconcha.in. For sepolia it is not a big issue as we can export the few pre-altair epochs using our old system, but for goerli/prater it would be great to have the full api available.

**Comment by peterbitfly** [comment]
@michaelsproul with the Shanghai upgrade on Sepolia now completed we are moving to prepare the update to goerli/prater. As prater has around 36000 epochs pre-altair it would be great for us if you can update the api to resolve this issue so that we can proceed with the upgrade preparation. Some background, we decided to use the rewards api in order to calculate all validator cl income stats on the explorer (instead of working with balance changes like we did up to now) as it gives us much more granularity on the individual rewards level.

**Comment by michaelsproul** [comment]
@peterbitfly Can't make any promises we'll get it done in time for the Goerli release sorry. Is there a way you can stub the explorer to not display rewards for those old epochs, or use your previous impl? I imagine not many users are interested in historic rewards data from so long ago.

**Comment by peterbitfly** [comment]
Yeah, no worries we will use our current method for those periods if in time no release is available. Thanks for your quick response.

**Comment by peterbitfly** [comment]
@michaelsproul do you maybe have an estimation if this will be available before the mainnet fork in April?

**Comment by michaelsproul** [comment]
@peterbitfly Probably not at this stage

**Comment by michaelsproul** [comment]
I haven't started on the impl yet, and I've got a few other things I need to do before the fork (tree-states, blockprint, etc).

**Comment by peterbitfly** [comment]
Hello @michaelsproul, any update on that issue?

**Comment by michaelsproul** [comment]
I still haven't started on the impl sorry, I've been thinking of trying to get back to it but keep getting drawn onto other things. I might see if there's anyone else who wants to take it

**Comment by K-Luffy** [comment]
Hello @michaelsproul,  When can I expect an update?

**Comment by michaelsproul** [comment]
Nobody working on it currently, sorry, we've all been drawn into higher priority things. Maybe in a month or so

**Comment by jimmygchen** [comment]
Completed in #4474 🎉
