### ISSUE TITLE
Implement expected_withdrawals HTTP API

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4029]
## Description

There's a new HTTP API on the block for builders: https://github.com/ethereum/beacon-APIs/issues/301

I think @realbigsean might already have an implementation to support `mock-relay`, so we should probably base the standard impl on that. I'm happy to go hunting for the branch and porting it across next week, as Sean is on leave.

**Comment by marshalys** [comment]
When can this api implement?

**Comment by michaelsproul** [comment]
@marshalys Maybe for v4.1.0, what do you want it for? If you're doing builder stuff I'd reccommend the SSE `payload_attributes` event instead. For API docs see [spec](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Events/eventstream) and for example usage see [`dummy_builder`](https://github.com/michaelsproul/dummy_builder).

**Comment by marshalys** [comment]
> @marshalys Maybe for v4.1.0, what do you want it for? If you're doing builder stuff I'd reccommend the SSE `payload_attributes` event instead. For API docs see [spec](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Events/eventstream) and for example usage see [`dummy_builder`](https://github.com/michaelsproul/dummy_builder).

OK, thank you! I'll see it.

**Comment by eserilev** [comment]
i'd like to pick this one up if its still relevant

**Comment by michaelsproul** [comment]
Thanks @eserilev, that would be great!
