### ISSUE TITLE
Exit validator on zhejiang

### ISSUE THREAD

**Issue by Piradoxlanieve** [sigp/lighthouse#4031]
## Description

I'm trying to request a voluntary departure but it seems that lighthouse doesn't recognize the network --zhejiang, can someone tell me how to request a voluntary departure?
I hope you understand my English.

## Version
lighthouse --version
Lighthouse v3.4.0-9c81be8
BLS library: blst
SHA256 hardware acceleration: true
Allocator: jemalloc
Specs: mainnet (true), minimal (false), gnosis (false)

```
lighthouse account validator exit \
--keystore /var/lib/lighthouse/validators/zhejiang/validators/0xxxxxxxxxxxxx/keystore-m_12381_3600_0_0_0-1677014338.json \
--beacon-node http://localhost:5052 \
--network zhejiang
error: 'zhejiang' isn't a valid value for '--network <network>'
        [possible values: gnosis, goerli, kiln, mainnet, prater, ropsten, sepolia]
```

**Comment by michaelsproul** [comment]
Use the `--testnet-dir` flag like you do for `lighthouse bn` and `lighthouse vc`

**Comment by Piradoxlanieve** [comment]
@michaelsproul thanks your your help.
:)
