### ISSUE TITLE
How to use stdin-inputs?

### ISSUE THREAD

**Issue by 0x8f701** [sigp/lighthouse#4032]
## Description

While import validator, I try to pass password to lighthouse container, though it doesn't seem to work:

```
echo "password"  | docker run          -v "validator1-data:/data"         -v "$(pwd)/app:/app"         --rm sigp/lighthouse:capella         lighthouse         account validator import                 --datadir "/data/lighthouse/validator-data"         --keystore /app/keystore/ethereum2/xxxx --stdin-inputs
```

## Version

Please provide your Lighthouse and Rust version. Are you building from
`stable` or `unstable`, which commit?

## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.

## Expected Behaviour

How _should_ the application behave?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by 0x8f701** [comment]
I also tried to use password-file then it asks me to add missing `--reuse-password` flag. Though I dont think this flag is  useful to me since I'm passing only one single keystore file using `--keystore`

**Comment by michaelsproul** [comment]
@GopherJ You can use the `--reuse-password` flag even if you've only got 1 keystore. It's required when using `--password-file`.

The reason your first command didn't work is that Docker won't attach stdin to stdin on your host by default. You can make it attach by using `--attach stdin` in the `docker run` flags as described here: https://docs.docker.com/engine/reference/commandline/run/#attach

**Comment by 0x8f701** [comment]
@michaelsproul thanks! let me try today and get back to you.

**Comment by 0x8f701** [comment]
Hi @michaelsproul I just tried another command and it seems still not working yet:

```
echo "my account secret" | \
 docker run -v "validator3-data:/data" \
  -v "$(pwd)/app:/app" \
  --attach stdin \
  --rm sigp/lighthouse:capella \
  lighthouse \
  account validator import \
  --stdin-inputs \
  --datadir "/data/lighthouse/validator-data" \
  --keystore /app/keystore/ethereum2/f9c40819-4226-4530-b279-64f90c0354cc/c379657b-b90a-4ea7-b053-9590b2b62b3b
```
this command is executed inside `shelljs`, after the execution I still cannot find `voting_keystore_password` inside validator_definitions.yml

**Comment by michaelsproul** [comment]
Closing as stale because this is old. Sorry I never responded but I'm going to assume you got this sorted
