### ISSUE TITLE
EngineError when requesting block at slot 43200 on Zhejiang testnet

### ISSUE THREAD

**Issue by peterbitfly** [sigp/lighthouse#4035]
## Description
When requesting the block body at slot 80646 via the beacon api `curl -v http://localhost:4000/eth/v1/beacon/blocks/43200` we get the following error:
```
{"code":500,"message":"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0x1c5f2c9cbaa2e7c7abdb6fa73e7562beea21ce6af8a0e52a5634f6283db07418, EngineError(Api { error: Json(Error(\"missing field `withdrawals`\", line: 0, column: 0)) }))","stacktraces":[]}
```

This is also the case for all successive blocks up to block 91765 after which the api returns again valid results.

We are using lh version v3.5.0 together with erigon (latest devel)

## Version
 v3.5.0

## Present Behaviour
Beacon API returns an error when requesting a certain range of block bodies from the Zhejiang testnet (43200 to 91765)

## Expected Behaviour
API should return a block body for all requested blocks

## Steps to resolve
See description

**Comment by michaelsproul** [comment]
That's an Erigon issue. It will be resolved by https://github.com/sigp/lighthouse/pull/4028 assuming Erigon implements the PayloadBodies methods (I think they will, or may already).

You could also work around this by running Lighthouse with `--prune-payloads false` (and syncing from genesis).

**Comment by peterbitfly** [comment]
Thanks for your quick response, will open an issue with erigon then.

**Comment by michaelsproul** [comment]
Closing as resolved
