### ISSUE TITLE
Can't start Gazorpazorpfield

### ISSUE THREAD

**Issue by skliarovartem** [sigp/lighthouse#4039]
Trying to start lighthouse by the following command:
`./lighthouse --network=sepolia --execution-endpoint=http://localhost:8551 --execution-jwt=(somepath) --checkpoint-sync-url=https://sepolia.checkpoint-sync.ethdevops.io`
Have this error:
`error: Found argument '--execution-endpoint' which wasn't expected, or isn't valid in this context`

**Comment by pawanjay176** [comment]
You missed the `beacon_node` subcommand. It should be 
```
./lighthouse --network=sepolia beacon_node --execution-endpoint=http://localhost:8551 --execution-jwt=(somepath) --checkpoint-sync-url=https://sepolia.checkpoint-sync.ethdevops.io
```
