### ISSUE TITLE
v3.5.1: Error building Gnosis feature

### ISSUE THREAD

**Issue by PierrickGT** [sigp/lighthouse#4062]
## Description

I'm having an issue compiling v3.5.1 from source for Gnosis.
It works perfectly for Mainnet.

Here is the error:

```
error[E0275]: overflow evaluating the requirement `Pin<Box<(dyn Future<Output = std::result::Result<(warp::reply::Json,), warp::reject::Rejection>> + Send + 'static)>>: Unpin`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "512"]` attribute to your crate (`lighthouse`)
```

```
error: could not compile `lighthouse` due to previous error
make: *** [Makefile:48: install] Error 101
```
## Version

v3.5.1

## Present Behaviour

It fails to compile from source for Gnosis.

## Expected Behaviour

It should compile for Gnosis

**Comment by michaelsproul** [comment]
You may be able to fix this by twiddling the compiler version. The error is basically the compiler saying "too many deeply-nested types to compile, I give up".

Which version of rustc is this and on which arch?

**Comment by PierrickGT** [comment]
@michaelsproul thanks for the tip.
I've updated to `rustc 1.68.0 (2c8cc3432 2023-03-06) (from rustc 1.65.0 (897e37553 2022-11-02))` and it worked.
