### ISSUE TITLE
Remove "next epoch" committee cache

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#407]
## Description

On the `BeaconState` we store three committee caches:

- `RelativeEpoch::Previous`: for `state.current_epoch() - 1`
- `RelativeEpoch::Current`: for `state.current_epoch()`
- `RelativeEpoch::Next`: for `state.current_epoch() + 1`

I propose that the `RelativeEpoch::Next` is unnecessary whilst `MIN_SEED_LOOKAHEAD < 2` (it is presently `1`).

As we process randao reveals during `state.current_epoch()`, we're updating the randao mix for `state.current_epoch() + MIN_SEED_LOOKAHEAD`. Therefore, whilst `MIN_SEED_LOOKAHEAD == 1`, the randao mix (and therefore the shuffling seed) for `RelativeEpoch::Next` cannot be known until the last block has been applied to the current epoch.

There's no case where we _must_ know the shuffling for the next epoch and it seems that having the usually-invalid next-epoch shuffling hanging around is likely to entice bugs.

## Steps to resolve

Change [`CACHED_EPOCHS`](https://github.com/sigp/lighthouse/blob/8afe8b3569085d05eba78a0cb11399485320405b/eth2/types/src/beacon_state.rs#L27) to `2`, leaving only the `Previous` and `Current` committee caches. Remove all code for the `Next` committee cache.

**Comment by michaelsproul** [comment]
This is probably not a great first issue until the linked eth-specs issue is resolved

**Comment by paulhauner** [comment]
Consider it blocked!

**Comment by michaelsproul** [comment]
Closing as v0.8.1 of the spec fixes the off-by-one error and makes the next epoch cache viable again!

**Comment by paulhauner** [comment]
MNECVA!
