### ISSUE TITLE
Tidy Cargo dependencies

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#408]
## Description

Cargo dependencies (`Cargo.toml`) could use some love.

I suggest we:

- Remove any unused dependencies (I suspect there are many).
- ~~Add a caret (`^`) to deps we want to keep upgrading.~~
- Add `Cargo.lock` to git.

**Comment by michaelsproul** [comment]
Deps without any signifier are implicitly taken to be caret dependencies, so bullet (2) may not be necessary: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio

**Comment by paulhauner** [comment]
Related to #403

**Comment by jzaki** [comment]
[cargo fix with unused_imports lint](https://github.com/rust-lang/rust/pull/56645)
