### ISSUE TITLE
Blob signing HTTP endpoints for the builder (blinded) flow

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4103]
## Description

The blob signing HTTP endpoints for the normal / unblinded flow has been implemented in #4075 and #4083 , however there isn't a decision yet on how the blinded flow for blobs look like.

Beacon API spec: https://github.com/ethereum/beacon-APIs/pull/302
Builder spec: https://github.com/ethereum/builder-specs/pull/61

**Comment by realbigsean** [comment]
The endpoints are there at this point, so I think it's ok to close this and track the builder API generaly here https://github.com/sigp/lighthouse/issues/3689
