### ISSUE TITLE
Tracking: v0.0.1 milestone

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#411]
## Description

This issue should track the features we want to include/exclude from the `v0.0.1` release milestone.

**Tentative date: 15/7/19**

## Required Features:

- A phase 0 testnet that can run on 1s slot times for 2 days.
- VC/BN communications via HTTP.
- A HTTP API beyond that of the minimal validator requirements.
- Should not bypass any significant part consensus (except deposit contract).
- Discovery via libp2p-discv5
- Eth2-RPC re-write (Request/Responses via substreams rather than byte prefix)

## Excluded Features:

- Full deposit contract functionality.
- Slashing detection or protection.

## Info

Deposit contract is excluded as significant changes are expected to be introduced around spec-freeze (raised by J.Drake in an Eth2 call).

**Comment by paulhauner** [comment]
I think we should push this date back. I propose the 25/07 but I'm flexible.

@AgeManning, @spble, @michaelsproul keen to hear your thoughts :)

**Comment by spble** [comment]
Agreed, 25th July sounds good!
