### ISSUE TITLE
Discovery returns no results when peering with any prysm client due to discv5 implementation

### ISSUE THREAD

**Issue by bretep** [sigp/lighthouse#4147]
## Description

When lighthouse is configured with bootnodes that are prysm, `discv5` does not work properly. LH will peer with the bootnode but the discovery request will return `Discovery query yielded no results`

## Version

v3.3.0 - v4.0.1

## Present Behaviour

`DEBG Discovery query yielded no results.     service: libp2p`

The prysm bootnode:
![tg_image_2667874591](https://user-images.githubusercontent.com/787344/228972814-929c230d-680e-4f81-8aeb-51c0b136d2d1.jpeg)

## Expected Behaviour

`DEBG Discovery query completed               peers_found: 16, service: libp2p`

## Steps to resolve

I tracked it down to the protocoIId not being valid

dsicv5 rejected that packet as an invalid packet header

Prysm uses go-ethereum v5wire for validation: https://github.com/ethereum/go-ethereum/blob/a236e03d0094fd2703cecfb235d91e1e36d0b276/p2p/discover/v5wire/encoding.go#L645

The expected protocolID: `protocolID = [6]byte{'d', 'i', 's', 'c', 'v', '5'}`
https://github.com/ethereum/go-ethereum/blob/a236e03d0094fd2703cecfb235d91e1e36d0b276/p2p/discover/v5wire/encoding.go#L103

**Comment by bretep** [comment]
Using lighthouse as a bootnode works as expected because there is no check for the protocolId

**Comment by bretep** [comment]
I was hoping this would be resolved with the `4.0.1` release:
https://github.com/sigp/lighthouse/blob/a53830fd60a119bf3f659b253360af8027128e83/beacon_node/lighthouse_network/Cargo.toml#L8

Which had this fix:
https://github.com/sigp/discv5/blob/d20340164ae558287db55de32122a89b2ccd2757/src/packet/mod.rs#L35

However, for the discovery, prysm is still throwing the `err="invalid packet header"` error.

**Comment by bretep** [comment]
It appears that the `FindPeers` query is the request being sent that has an invalid packet header
https://github.com/sigp/lighthouse/blob/a53830fd60a119bf3f659b253360af8027128e83/beacon_node/lighthouse_network/src/discovery/mod.rs#L348

**Comment by bretep** [comment]
It seems that the libp2p has not implemented the `FindPeers`, only the `FindNode`. I wonder if they are the same, but logically one developer decided `FindPeers` was more descriptive, and another developer used`FindNode` which everyone else uses for discv5.
https://github.com/ethereum/go-ethereum/blob/d0fbb10658a85f0b2bd4466892747758bacddaf7/p2p/discover/v5wire/msg.go#L124

I see no reference to `FindPeers` on the v5wire library that prysm uses from the go-ethereum library

**Comment by bretep** [comment]
@AgeManning can you take a look at this?

**Comment by AgeManning** [comment]
Hey, haven't had a chance to look at this yet. But are you sure the bootnode ENR matches the node you are connecting to?

If prysm changes their node-id/peer-id on restart and it differs from the original ENR bootnode you are connecting to, then you are likely to see an error like this. 
Alternatively if the boot-node ENR points to the same IP address as another node with a different id you may see a simiar issue. 

Can you please check the node-id/peer-id of the bootnode ENR matches the prysm node that you are connecting to

**Comment by divagant-martian** [comment]
Thanks @bretep for your report

There are a couple of clarifications to be made so that we can get to the bottom of the issue.
1. `FindPeers` is a LH query type, the corresponding query in discv5 (after some rather long code paths) is [`FindNode`](https://github.com/sigp/discv5/blob/b86e45de3f5900fca23eac68652912d37fb6e383/src/rpc.rs#L72-L75). The fact that lighthouse models a query that (in some way) wraps this as a dependent of the `discv5` crate should not be an issue. 
2. The default protocol id has always been `discv5`. It's appended on every package [here](https://github.com/sigp/discv5/blob/d20340164ae558287db55de32122a89b2ccd2757/src/packet/mod.rs#L108-L109) and decoded as well, there is a check for expected protocol id and version [here](https://github.com/sigp/discv5/blob/d20340164ae558287db55de32122a89b2ccd2757/src/packet/mod.rs#L455-L466)

I just ran the `discv5` [`find_node` example](https://github.com/sigp/discv5/blob/d86707d79c1183b14b8cf31ef62a8a74ef9cd3e4/examples/find_nodes.rs) against three prysm mainnet bootnodes and it works as expected. Run example
 ```bash
 cargo run --example find_nodes -- --remote-peer enr:-Ku4QP2xDnEtUXIjzJ_DhlCRN9SN99RYQPJL92TMlSv7U5C1YnYLjwOQHgZIUXw6c-BvRg2Yc2QsZxxoS_pPRVe0yK8Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQMeFF5GrS7UZpAH2Ly84aLK-TyvH-dRo0JM1i8yygH50YN1ZHCCJxA
 ```

Now building latest master from `discv5` and `geth` I run a lh `discv5` node as
```bash
$ cargo run --example find_nodes -- --enr-ip4 127.0.0.1 --events
# INFO find_nodes: Base64 ENR: <generated local enr>
```

And then run geth's `discv5` test suite against this node
```bash
./devp2p discv5 test <generated local enr from prev command>
# -- RUN Ping
# .. 
# -- OK Ping (9.3ms)
# -- RUN PingLargeRequestID
# ..
# -- OK PingLargeRequestID (303.6ms)
# -- RUN PingMultiIP
# ..
#  got WHOAREYOU for new session as expected
# ..
#  got WHOAREYOU for new session as expected
# -- OK PingMultiIP (35.3ms)
# -- RUN PingHandshakeInterrupted
# ..
#  expected WHOAREYOU, got read udp 127.0.0.1:53554: i/o timeout
# -- FAIL PingHandshakeInterrupted (305.4ms)
# -- RUN TalkRequest
# ..
# -- OK TalkRequest (21.5ms)
# -- RUN FindnodeZeroDistance
# ..
# -- OK FindnodeZeroDistance (23.1ms)
# -- RUN FindnodeResults
# ..
#  remote returned 5 nodes for distance list [254 256 253 255]
#  all 5 expected nodes were returned
# ..
# -- OK FindnodeResults (13.1108s)
# 6/7 tests passed.
```
Notably, the interrumpted ping test fails, but this isn't really an issue, every test regarding communication between the nodes, including the Findnode test, passes.

As such, I don't identify an issue that looks like what you describe. Perhaps if you could provide commands that generate a reproducible test environment that fails we could further look into it.

**Comment by bretep** [comment]
> Hey, haven't had a chance to look at this yet. But are you sure the bootnode ENR matches the node you are connecting to?
> 
100% sure. I grep by my lighthouse IP address on the prysm logs. 

> If prysm changes their node-id/peer-id on restart and it differs from the original ENR bootnode you are connecting to, then you are likely to see an error like this. Alternatively if the boot-node ENR points to the same IP address as another node with a different id you may see a simiar issue.
> 
> Can you please check the node-id/peer-id of the bootnode ENR matches the prysm node that you are connecting to

We're not using mainnet bootnodes. These are on our own network.

Some notes:
LH peers with all three bootnodes:
```
# PulseChain Official (aws-us-east-1)
- enr:-MK4QC37TFAfc973oOezRlVoOCygtjT-rlOoKbbuZNmrJ5dhXS-IfrsH3yhjNP0dfy3-UpyFZy2hy6lOE__ykFfj3lKGAYa95Co5h2F0dG5ldHOIAAAAAAAAAACEZXRoMpBbnJIGAAAJRP__________gmlkgnY0gmlwhAPsylWJc2VjcDI1NmsxoQOpEhsSXVShFW4yvaww_SI0A-H0pix0aJlOdYJgyIgbjYhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
- enr:-MK4QM1JpOXnj-zpjfPvG1GkCEvjYMg8dEk6t7VLtpFuionhBz59n2ZIwixpO2exzoNLMV4_v7jCHGQqi0zYtc-Gp3OGAYa94lhqh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBbnJIGAAAJRP__________gmlkgnY0gmlwhCzKVYOJc2VjcDI1NmsxoQK24rqFwR7W3HJgLVVGDSMy8PiMculxF6VOJgAlG4wmXohzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
- enr:-MK4QBAlroGpM1xtk7WzWP8lbKnI2UjVpoQNsKJeNRS-kVvFCswNyVRBZHwMOvfW2G3j0qaaDsUpMxXY-t9LdGAZgQGGAYa94IQmh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBbnJIGAAAJRP__________gmlkgnY0gmlwhK6BYN-Jc2VjcDI1NmsxoQJNoBFGkhcAMKIbrDPHoI7dYVAY99Z832TimlqhpoYo7YhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A
```
https://gitlab.com/pulsechaincom/lighthouse-pulse/-/blob/rebase-upstream-v4.0.1/common/eth2_network_config/built_in_network_configs/pulsechain-testnet-v3/boot_enr.yaml

All three are prysm nodes. 

To make things easier, I'm only going to focus on the last ENR in the list.

### https://enr-viewer.com/
```
Signature: 0x1025ae81a9335c6d93b5b358ff256ca9c8d948d5a6840db0a25e3514be915bc50acc0dc95441647c0c3af7d6d86de3d2a69a0ec5293315d8fadf4b7460198101
seq: 1678222853158
attnets: 0x0000000000000000
eth2: 0x5b9c920600000944ffffffffffffffff
id: v4
ip: 174.129.96.223
secp256k1: 0x024da0114692170030a21bac33c7a08edd615018f7d67cdf64e29a5aa1a68628ed
syncnets: 0x00
tcp: 13000
udp: 12000

Derived Fields
node id: b42e8e7cdb610cc36238195704aa923f243da0a6a74dd090e9040a3eb5cb07e4
peer id: 16Uiu2HAkzegwK4y2UtAtMXi1sPSsptmbn6Hko6svJ4so8KY7EotY
tcp4 multiaddr: /ip4/174.129.96.223/tcp/13000/p2p/16Uiu2HAkzegwK4y2UtAtMXi1sPSsptmbn6Hko6svJ4so8KY7EotY
udp4 multiaddr: /ip4/174.129.96.223/udp/12000/p2p/16Uiu2HAkzegwK4y2UtAtMXi1sPSsptmbn6Hko6svJ4so8KY7EotY
```
### Bootnode:
```
curl -1s http:/127.0.0.1:3500/eth/v1/node/identity | jq
{
  "data": {
    "peer_id": "16Uiu2HAm1vNgVmv3W9YQLaBJcFeJnT6ArXnmwjsFZxzwMnSAhqjG",
    "enr": "enr:-MK4QJjQTAXVWXESp_dilbbaJr7VhUFc6oTmqb6M-VyToqdOBweaaUT5ys8SONJs5Eb_0mlOJumrvkJVqJTrSbOn_6OGAYcm5RmUh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBbnJIGAAAJRP__________gmlkgnY0gmlwhK6BYN-Jc2VjcDI1NmsxoQJggGfmwto714VLc0bCjw5j8G4yiy1LvtAinB5sVVvwA4hzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A",
    "p2p_addresses": [
      "/ip4/10.0.6.24/tcp/13000/p2p/16Uiu2HAm1vNgVmv3W9YQLaBJcFeJnT6ArXnmwjsFZxzwMnSAhqjG",
      "/ip4/174.129.96.223/tcp/13000/p2p/16Uiu2HAm1vNgVmv3W9YQLaBJcFeJnT6ArXnmwjsFZxzwMnSAhqjG",
      "/ip4/174.129.96.223/tcp/13000/p2p/16Uiu2HAm1vNgVmv3W9YQLaBJcFeJnT6ArXnmwjsFZxzwMnSAhqjG"
    ],
    "discovery_addresses": [
      "/ip4/174.129.96.223/udp/12000/p2p/16Uiu2HAm1vNgVmv3W9YQLaBJcFeJnT6ArXnmwjsFZxzwMnSAhqjG"
    ],
    "metadata": {
      "seq_number": "1",
      "attnets": "0x0000000000000000"
    }
  }
}
```

**Comment by bretep** [comment]
These are the logs when peering with the prysm boot nodes: (I don't get any neighbors/peers)
[LH_client_prysm_bootnode.log](https://github.com/sigp/lighthouse/files/11117239/LH_client_prysm_bootnode.log)

If I add a lighthouse peer:

```
--boot-nodes=enr:-L64QNIt1R1_ou9Aw5ci8gLAsV1TrK2MtWiPNGy21YsTW0HpA86hGowakgk3IVEZNjBOTVdqtXObXyErbEfxEi8Y8Z-CARSHYXR0bmV0c4j__________4RldGgykFuckgYAAAlE__________-CaWSCdjSCaXCEA--2T4lzZWNwMjU2azGhArzEiK-HUz_pnQBn_F8g7sCRKLU4GUocVeq_TX6UlFXIiHN5bmNuZXRzD4N0Y3CCIyiDdWRwgiMo
```


Then I get this log: (I get all the neighbors/peers)
[lighthouse_LH_trace.txt](https://github.com/sigp/lighthouse/files/11117248/lighthouse_LH_trace.txt)

**Comment by AgeManning** [comment]
Yeah, the ENR you looked at doesn't have the same peer-id as the node you got the ID from. This is your problem. 

The ENR does not match the node you are connecting to.

**Comment by AgeManning** [comment]
The ENR used as a boot-node did not match the node it was connecting to. The receiving node cannot decrypt packets that were not meant for it. This is as expected.

**Comment by bretep** [comment]
The boot node peer id did change.

Incase other run into this @AgeManning gave an explanation to as why:
```
All communication is encrypted via the network key. The peer-id and node-id are the public keys of the network secret key which is used to encrypt all traffic

The reason you get a bad packet error is because you are encrypting messages to a node id which cannot be decrypted by the receiving node (as it has the wrong node-id)
```

Documentation about discv5 and encryption can be found here: https://github.com/ethereum/devp2p/blob/master/discv5/discv5-rationale.md
