### ISSUE TITLE
Windows unrestricted perms on logs differ from Linux

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4162]
Regarding the `--logfile-no-restricted-perms` flag added in #3747:

> @michaelsproul I think the flag help text is a bit misleading. When using this flag on Windows, the log file permissions are inherited from the parent folder (as expected), which does not necessarily mean "world-readable". It depends on the permissions set on the parent folder, which can be totally secure.

_Originally posted by @ostracoder in https://github.com/sigp/lighthouse/issues/3747#issuecomment-1495018738_

**Comment by michaelsproul** [comment]
We could either fix this by:

- Documenting that the behaviour is different on Windows, or
- Changing the permissions used on Windows so that they're closer to world-readable

I think the former is probably better given the name of the flag

**Comment by eserilev** [comment]
hi, i'd like to take a stab at this. to document that the flags behavior is different on windows I was planning on updating the flag help text to:

"If present, log files will be generated as world-readable meaning they can be read by any user on the machine. Note that logs can often contain sensitive information about your validator and so this flag should be used with caution. **For Windows users, the log file permissions will be inherited from the parent folder.**"
 
PR: https://github.com/sigp/lighthouse/pull/4165

**Comment by chong-he** [comment]
Close with #4165
