### ISSUE TITLE
SSZ Partials API

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#417]
## Description

High-level discussion about implementing SSZ partials in Lighthouse.

## API Design

I have thought of two potential designs, one has stronger type-level guarantees whilst the other is simpler to implement on a struct.

My preference is **API 1**.

The code provided is intended as a rough example, it wouldn't compile.

I'm keen for input/feedback.

### API 1: Not wrapping all the fields

Characteristics: 

- Simpler implement: there are no "wrapper" structs around each field, implementation is a single proc derive macro.
- Less type safety: the type system does not enforce that some value has been loaded and is not default.

```rust
#[derive(SszPartial)]
struct Foo {
  a: usize
}

#[derive(SszPartial)]
struct Foo {
  a: usize
}

#[derive(SszPartial)]
struct MyStruct {
  foo: Foo,
  bar: Bar
}

//
// Encoding
//

let random = MyStruct::random();
let foo_bytes: Vec<u8> = random.get_serialized_partial("foo.a").unwrap();
let bar_bytes: Vec<u8> = random.get_serialized_partial("bar.a").unwrap();

//
// Decoding
//

// Supplied path must be rooted in `trusted_root`. Ensures the authenticity of `bytes`.
let trusted_root = random.tree_hash_root();  
let mut partial = MyStruct::default();
partial.load_serialized_path(trusted_root, "foo.a", foo_bytes).unwrap();

assert!(partial.path_was_loaded("foo.a"), "safety check to ensure foo.a has been loaded");
assert_eq!(random.foo.a, partial.foo.a, "foo.a was loaded from proof");
assert_eq!(partial.bar, Bar::default(), "bar.a was not loaded from proof");

// Load bar.a from proof.
partial.load_serialized_path(trusted_root, "bar.a", bar_bytes).unwrap();

assert_eq!(random.bar.a, partial.bar.a, "bar.a was loaded from proof");
```

### API 2: Wrapping all the fields

Characteristics:

- Implementation is intrusive: all supported field must be wrapped in a `SszPartial` type.
- Provides type-level assurance that each field was loaded from bytes and is not some default value.

```rust
use ssz_partial::SszPartial;
use ssz_partial_derive::SszPartial;

#[derive(SszPartial)]
struct Foo {
  a: SszPartial<usize>
}

#[derive(SszPartial)]
struct Foo {
  a: SszPartial<usize>
}

#[derive(SszPartial)]
struct MyStruct {
  foo: SszPartial<Foo>,
  bar: SszPartial<Bar>
}

//
// Encoding
//

let full: SszPartial<MyStruct> = SszPartial::from(MyStruct::new());
let foo_bytes: Vec<u8> = full.get_serialized_partial("foo.a").unwrap();

//
// Decoding
//

// Supplied path must be rooted in `trusted_root`. Ensures the authenticity of `bytes`.
let trusted_root = full.tree_hash_root();  
let partial = MyStruct::from_serialized_partial(trusted_root, "foo.a", foo_bytes).unwrap();

assert!(partial.foo.a.is_some());
assert!(partial.bar.is_none());
```

**Comment by paulhauner** [comment]
Re-opening. I closed the issue because I accidentally posted it before I completed writing it.

**Comment by c-o-l-o-r** [comment]
This is great, thanks Paul!

I think the first API would be a great place to start. Here are my thoughts on it:

* the simplicity is great
* the lack of type-level make me feel like there are better solutions
* most of the work for this interface would need to be implemented anyways for more complex interfaces
* I don't see a major use case for accessing elements via their path vs. the dot syntax in Rust (e.g. we'll know paths we want to access at compile time
* I think that serializing and deserializing entire objects (or merkle multi proofs) will be more prevalent than individual branches


With that said, I still thing this is a good starting point. How do you feel about me going ahead with API 1 and then once that is complete we can take a second look (hopefully with some new insights from the initial implementation) at improving it?

I'll also include what I was originally imagining below -- but I'm seeing how the implementation will be much heavier.

```rust
// The commented code will derive to the uncommented code via the SszPartial macro.
//
// #[derive(SszPartial)]
// struct Foo {
//   a: usize
// }

// #[derive(SszPartial)]
// struct Bar {
//   a: Vec<usize>
// }

// #[derive(SszPartial)]
// struct MyStruct {
//   foo:  Foo,
//   bar: Bar
// }

struct Foo {
  a: SszPartial<usize>
}

struct Bar {
  a: SszPartial<PartialHashMap<usize>>
}

struct MyStruct {
  foo: SszPartial<Foo>
  bar: SszPartial<Bar>
}

let my_struct = MyStruct::random();
let foo_bytes: Vec<u8> = my_struct.foo.a.get_serialized_partial().unwrap();
let bar_bytes: Vec<u8> = my_struct.bar.a.get_serialized_partial().unwrap();

let trusted_root = random.tree_hash_root();
let mut partial = MyStruct::load_serialized_partial(trusted_root, foo_bytes).unwrap();
assert_eq!(my_struct.foo.a.unwrap(), partial.foo.a.unwrap());

partial.foo.a.set(100);
let new_root = partial.tree_hash_root();
assert_nq!(new_root, trusted_root);
```

**Comment by axic** [comment]
For prototyping reasons I'd argue **API 1** is a good starting point, assuming it won't take too much time to implement compared to **API 2**.

We can experiment with this API within execution environments, which should give a good indication whether individual leaf nodes or bigger branches are accessed more frequently and should also clarify how frequently unavailable nodes are accessed (e.g. those set to defaults).

**Comment by paulhauner** [comment]
Cool! Seem's we agree :)

I'll close this for now, feel free to open up if you want to discuss
