### ISSUE TITLE
Validator `exit` command crashes for local testnet

### ISSUE THREAD

**Issue by john-risk-adigium** [sigp/lighthouse#4172]
## Description

I started a local blockchain using geth and lighthouse and --testnet-dir. The chain has been in PoS and producing blocks for a few weeks.
When I try to exit the validator, it crashes with the error `network should have valid genesis state: "Genesis state is unknown"`

## Lighthouse commands used on this node

- lighthouse **beacon** --testnet-dir ./data/testnet --datadir ./data/consensus/0 --http --eth1 --staking
- lighthouse account validator **import** --testnet-dir ./data/testnet --datadir ./data/validator/0 --directory ./ValidatorKeys
- lighthouse **validator** --testnet-dir ./data/testnet --datadir data/validator/0 --beacon-nodes http://localhost:5052 --suggested-fee-recipient 0x...
- lighthouse account validator **exit** --testnet-dir ./data/testnet --beacon-node http://localhost:5052 --keystore ./keystore-... .json

## Version

- Lighthouse v3.5.0-0fb58a6 prebuilt binaries
- Lighthouse v4.0.1-a53830f compiled, rustup 1.25.2 (17db695f1 2023-02-01), rustc 1.67.1 (d5a82bbd2 2023-02-07)

## Present Behaviour

When I try to exit the validator, using the command:
```
lighthouse --testnet-dir ./data/testnet account validator exit \
	--datadir ./data/validator/0 --beacon-node http://localhost:5052 --keystore ../keystore-m_12381_3600_0_0_0-1673523562.json
```

it gives the following error:
```
thread 'main' panicked at 'network should have valid genesis state: "Genesis state is unknown"', /project/account_manager/src/validator/exit.rs:129:10
stack backtrace:
   0: rust_begin_unwind at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5

   3: account_manager::validator::exit::publish_voluntary_exit::{{closure}}
   4: account_manager::validator::exit::cli_run
   5: account_manager::run
   6: lighthouse::main::{{closure}}
   7: lighthouse::main
```

## Expected Behaviour

The validator should start the exit process, and lighthouse exit command should not crash

## Config.yaml

CONFIG_NAME: mainnet
PRESET_BASE: mainnet

GENESIS_FORK_VERSION: "0x00000000"
GENESIS_DELAY: "10"
ALTAIR_FORK_VERSION: "0x01000000"
ALTAIR_FORK_EPOCH: "0"
BELLATRIX_FORK_VERSION: "0x02000000"
BELLATRIX_FORK_EPOCH: "1"

TERMINAL_TOTAL_DIFFICULTY: 32
TERMINAL_BLOCK_HASH: "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: "18446744073709551615"
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: "8"
MIN_GENESIS_TIME: 1680856005
DEPOSIT_CHAIN_ID: "333333"
DEPOSIT_NETWORK_ID: "333333"
DEPOSIT_CONTRACT_ADDRESS: "0x92e51e9a023e33d98e23706d7e7e0d6bfc3523b5"

SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY: "128"
SECONDS_PER_SLOT: "12"
SECONDS_PER_ETH1_BLOCK: "14"
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: "256"
SHARD_COMMITTEE_PERIOD: "256"
ETH1_FOLLOW_DISTANCE: "10"
INACTIVITY_SCORE_BIAS: "4"
INACTIVITY_SCORE_RECOVERY_RATE: "16"
EJECTION_BALANCE: "16000000000"
MIN_PER_EPOCH_CHURN_LIMIT: "4"
CHURN_LIMIT_QUOTIENT: "65536"
PROPOSER_SCORE_BOOST: "40"

## Geth genesis.json

{
        "config": {
                "ChainName": "Oone Chain Testnet",
                "chainId": 333777,
                "consensus": "clique",
                "homesteadBlock": 0,
                "daoForkSupport": true,
                "eip150Block": 0,
                "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "eip155Block": 0,
                "eip158Block": 0,
                "byzantiumBlock": 0,
                "constantinopleBlock": 0,
                "petersburgBlock": 0,
                "istanbulBlock": 0,
                "muirGlacierBlock": 0,
                "berlinBlock": 0,
                "londonBlock": 0,
                "terminalBlockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "arrowGlacierBlock": 0,
                "grayGlacierBlock": 0,
                "clique": {
                        "period": 5,
                        "epoch": 30000
                },
                "terminalTotalDifficulty": 32
        },
        "difficulty": "1",
        "gasLimit": "30000000",
        "extradata": "0x0000000000000000000000000000000000000000000000000000000000000000D1efaaC3a45A3af7521D336198c0fB3Ed9ddC4450000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "alloc": {
...

**Comment by michaelsproul** [comment]
Is there a genesis.ssz in your testnet directory? That would fix this. I'm surprised you can run the `bn` without the genesis state

**Comment by john-risk-adigium** [comment]
There is no genesis.ssz :)

I generated the testnet folder using `lcli`, then used the testnet folder which contained `config.yaml, boot_enr.yaml and deploy_block.txt` to start beacons and validators.

Now I created the genesis.ssz using `lcli eth1-genesis` and it solved my problem.
