### ISSUE TITLE
ERRO Error during execution engine upcheck error

### ISSUE THREAD

**Issue by WALL-E** [sigp/lighthouse#4176]
## Description

> ERRO Error during execution engine upcheck error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(8551), path: "/", query: None, fragment: None }, source: TimedOut }), service: exec

## Version

Geth 1.11.5-stable
Lighthouse v4.0.1-a53830f

## Present Behaviour

> [50974577.173133] Out of memory: Kill process 30651 (geth) score 553 or sacrifice child
> [50974577.179483] Killed process 30651 (geth) total-vm:17717724kB, anon-rss:8810628kB, file-rss:0kB, shmem-rss:0kB
> [50974578.038730] oom_reaper: reaped process 30651 (geth), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

## Steps to resolve

unable to reproduce test

**Comment by michaelsproul** [comment]
Geth ran out of memory. If you can't add more RAM to the machine (I'm guessing it has 16GB) then you can minimize Lighthouse's memory usage by setting `_RJEM_MALLOC_CONF="abort_conf:true,narenas:1"` as an environment variable when running Lighthouse. You might also be able to tweak Geth's `--cache` size, but that may cause severe performance degradation if you go too low.

You may also have some other processes running that are eating up your RAM. Lighthouse and Geth should fit comfortably in 16GB.

**Comment by WALL-E** [comment]
If there are no other memory-consuming applications, a computer with 8 cores and 16GB of memory can fully support both Geth and Lighthouse running on the same node ?

Additional information: It has been running smoothly for the past three months (8core16g), but in the last week, there were three instances of OOM (Out Of Memory) after upgrading Geth and Lighthouse to the latest version.

**Comment by michaelsproul** [comment]
How much RAM is Lighthouse using usually? It looks like Geth OOMed at 8.4 GiB, which implies Lighthouse was using the rest (~7 GiB). Normally Lighthouse will use 2-4 GiB.

Have a look in `htop`, or if you want to monitor it over time try the Jemalloc Grafana dashboard: https://github.com/sigp/lighthouse-metrics/blob/master/dashboards/MallocInfoJemalloc.json. If you do, post some screenshots so we can interpret what Lighthouse is doing.

Which OS are you running on?

**Comment by WALL-E** [comment]
Operating System: Amazon Linux 2

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/736927/230761565-aa3536bb-4014-4338-a3d3-866b4eaa0f75.png">

**Comment by michaelsproul** [comment]
I can see the memory usage of Lighthouse spiked on our fleet around 9:40am UTC 2023-04-06, is this around the time you saw the OOM?

As a temporary workaround you could set some swap space on your machine, so that it just slows down a bit if memory spikes, rather than crashing entirely. See: https://linuxize.com/post/create-a-linux-swap-file/

**Comment by WALL-E** [comment]
Thank you for the reminder. I increased the swap partition yesterday, and it did indeed solve the problem.

These are some logs I found that may help to locate the issue.
This system has been running for 591 days already, only three instances of OOM were found.

```
[2023/03/30 06:36:48] [50169379.082990] Killed process 16680 (lighthouse) total-vm:27597140kB, anon-rss:12025384kB, file-rss:0kB, shmem-rss:0kB
[2023/04/08 14:16:46] [50974577.179483] Killed process 30651 (geth) total-vm:17717724kB, anon-rss:8810628kB, file-rss:0kB, shmem-rss:0kB
[2023/04/09 14:36:19] [51062149.719775] Killed process 15606 (geth) total-vm:17238460kB, anon-rss:8926140kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by WALL-E** [comment]
The screenshot captured just now, lighthouse beacon total-vm is ~29G

<img width="928" alt="image" src="https://user-images.githubusercontent.com/736927/230816734-a8ab480d-2822-4243-8781-5fc785b6714e.png">

**Comment by michaelsproul** [comment]
The amount of virtual memory doesn't matter, it just represents address space used. The relevant number for how much RAM is being used is the resident set size (RES). For more info on this see https://www.baeldung.com/linux/resident-set-vs-virtual-memory-size

**Comment by WALL-E** [comment]
Lighthouse beacon use ~9 GiB when syncing, much greater than 4G @michaelsproul 

<img width="910" alt="image" src="https://user-images.githubusercontent.com/736927/231339908-68c7905d-cab3-4d88-875e-a3b88fefa267.png">

**Comment by michaelsproul** [comment]
@WALL-E Interesting! What sort of syncing? Checkpoint sync? Sync from genesis? Reconstructing states?

**Comment by michaelsproul** [comment]
Can you try the `_RJEM_MALLOC_CONF="abort_conf:true,narenas:1"` environment variable?

**Comment by WALL-E** [comment]
> @WALL-E Interesting! What sort of syncing? Checkpoint sync? Sync from genesis? Reconstructing states?

Started with systemd, sync from genesis

```
[Unit]
Description=Lighthouse Consensus Client BN (Mainnet)
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=lighthousebeacon
Group=lighthousebeacon
Restart=always
RestartSec=5
ExecStart=/usr/local/bin/lighthouse beacon_node \
  --network mainnet \
  --datadir /var/lib/lighthouse \
  --slots-per-restore-point 8192 \
  --http \
  --metrics \
  --execution-endpoint http://192.168.0.128:8551 \
  --execution-jwt /var/lib/lighthouse/beacon/jwtsecret

[Install]
WantedBy=multi-user.target
```

**Comment by WALL-E** [comment]
> Can you try the `_RJEM_MALLOC_CONF="abort_conf:true,narenas:1"` environment variable?

I'll give it a try. @michaelsproul

**Comment by WALL-E** [comment]
@michaelsproul 

###  lighthouse version 

```
Lighthouse v4.0.1-a53830f
BLS library: blst-portable
SHA256 hardware acceleration: false
Allocator: jemalloc
Specs: mainnet (true), minimal (false), gnosis (true)
```

### environment variable
```
cat /proc/`pgrep lighthouse`/environ  | tr '\0' '\n'

LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
HOME=/home/lighthousebeacon
LOGNAME=lighthousebeacon
USER=lighthousebeacon
SHELL=/sbin/nologin
_RJEM_MALLOC_CONF=abort_conf:true,narenas:1
```

### after 5 minutes of startup
<img width="813" alt="image" src="https://user-images.githubusercontent.com/736927/231630549-0f925f7a-9b48-4ab3-b0a8-f2c859bf07e7.png">

**Comment by michaelsproul** [comment]
That looks a bit better @WALL-E. Have you also seen the latest v4.0.2-rc.0 release? It fixes an issue with exit processing that was causing memory spikes

Btw, if you checkpoint sync and use reconstruct-historic-states that's usually faster than syncing from genesis. We no longer optimise for syncing from genesis

**Comment by WALL-E** [comment]
###  lighthouse version 

```
Lighthouse v4.0.2-rc.0-35d8c98
BLS library: blst-portable
SHA256 hardware acceleration: false
Allocator: jemalloc
Specs: mainnet (true), minimal (false), gnosis (true)
```

### after 5 minutes of startup
<img width="813" alt="image" src="https://user-images.githubusercontent.com/736927/231635633-4cd22274-debd-4370-8756-ef10fec042a9.png">

@michaelsproul  Memory usage has indeed decreased significantly
