### ISSUE TITLE
Feature Request: Sign voluntary exit without broadcast

### ISSUE THREAD

**Issue by alex-miller-0** [sigp/lighthouse#4205]
Now that withdrawals are enabled, I would like to generate pre-signed voluntary exit messages as insurance against a nuclear meltdown on my staking box, i.e. something that would cause a long offline period (e.g. natural disaster, hardware failure, etc). This could generate a JSON file with the signed data, which could be backed up on another device and later broadcast to any available beacon node (e.g. there are [public nodes](https://beaconcha.in/tools/broadcast) which could be used to broadcast without an active staking box). Obviously this would be for emergencies only, as I would be signing up for ~4 days of penalties prior to exiting, but it would bound the risk of running a staker.

Currently, [voluntary exits on Lighthouse](https://lighthouse-book.sigmaprime.io/voluntary-exit.html) assume you are exiting immediately - it would be much appreciated if you could add a flag to decouple this from the actual signing process (e.g. `--prepare-offline`).

**Comment by michaelsproul** [comment]
This will be available in v4.1.0 via the VC HTTP API, docs: https://ethereum.github.io/keymanager-APIs/?urls.primaryName=dev#/Voluntary%20Exit/signVoluntaryExit.

We're also working on CLI tooling for interacting with the VC API, in this PR: https://github.com/sigp/lighthouse/pull/3502.

**Comment by alex-miller-0** [comment]
Haha amazing timing on that release. Just tested and it works great - thanks!

Closed by #4119

**Comment by mrabino1** [comment]
is there any documentation on how to use (via CLI) what you are planning on the lighthouse book? or other source? eg.. what is the command? thx
