### ISSUE TITLE
Underflow in verify_transfer

### ISSUE THREAD

**Issue by kirk-baird** [sigp/lighthouse#421]
## Description

In `eth2/state_processing/src/per_block_processing/verify_transfer.rs`
Verifying the balance of `sender` should check against `amount + fee` rather just `amount`.

## Present Behaviour

Currently the code has a check `sender_balance >= transfer.amount`
```rust
    // Verify the sender has adequate balance.
    verify!(
        time_independent_only || sender_balance >= transfer.amount,
        Invalid::FromBalanceInsufficient(transfer.amount, sender_balance)
    );
```
Which does not account for the fee.

## Expected Behaviour

`sender_balance >= total_amount`

## Steps to resolve

Change `transfer.amount` to `total_amount` to also account for the fee.

**Comment by paulhauner** [comment]
Closed via #457
