### ISSUE TITLE
Simplify fork choice's `calculate_committee_fraction`

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4211]
## Description

The v1.3.0 spec simplified the calculation of proposer boost in a way that is almost equivalent to the previous definition. We are still using the old definition but could update at any time to the simpler version.

Our impl:

https://github.com/sigp/lighthouse/blob/a53830fd60a119bf3f659b253360af8027128e83/consensus/proto_array/src/proto_array.rs#L1054-L1068

Spec: https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/phase0/fork-choice.md#get_weight

Discussion: https://github.com/ethereum/consensus-specs/pull/3034#discussion_r1063879124

## Version

v4.0.1

**Comment by eserilev** [comment]
@michaelsproul hi, i'd like to pick this one up

so if I'm understanding the spec correctly, the additional  calculations of `average_balance` and `committee_size` can be removed

instead `committee_weight` is just simply `total_effective_balance` which is the sum of the effective balance of all validators in the network that are in a given "justified" state

**Comment by michaelsproul** [comment]
yep!

**Comment by michaelsproul** [comment]
Closed by #4213
