### ISSUE TITLE
Error updating deposit contract cache error

### ISSUE THREAD

**Issue by tejareddy8888** [sigp/lighthouse#4212]
## Description

Hi @michaelsproul ,

I have similar issue with lighthouse beacon node as in this [3664](https://github.com/sigp/lighthouse/issues/3664)

`ERRO Error updating deposit contract cache   error: Failed to get remote head and new block ranges: EndpointError(FarBehind), retry_millis: 60000, service: deposit_contract_rpc`

Context:
I have created a private local network using lighthouse and geth combination.

where GETH is not syncing with reason:
`WARN [04-19|22:35:00.865] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!`

due to a storage issue, the client has stopped abruptly. Now, I don't want to delete the datadir.

Are there any alternative solutions apart from deleting the datadir and restarting ?

## Version
Lighthouse v3.3.0-bf533c8+
BLS library: blst
SHA256 hardware acceleration: false
Specs: mainnet (true), minimal (false), gnosis (false)

**Comment by pawanjay176** [comment]
Could you share your testnet configs? My guess is there's some config issue where perhaps you are starting geth with a post merge config but lighthouse with a pre-merge config. 
We have updated our post merge testnet scripts in this PR which should get merged sometime soon https://github.com/sigp/lighthouse/pull/3807
It might be helpful if you are trying to create a local post merge testnet.

**Comment by tejareddy8888** [comment]
@pawanjay176 , Thanks for the response.

Yes, I am trying to create a local post merge testnet. After seeing your PR, I realize that I have used the pre-merge config. 

Anyhow, please verify the attached config and start script used. 

[start_lighthouse.txt](https://github.com/sigp/lighthouse/files/11295915/start_lighthouse.txt)
[vars.txt](https://github.com/sigp/lighthouse/files/11295916/vars.txt)

**Comment by cppfuns** [comment]
I have the same problem

**Comment by mistergibson** [comment]
I have the same issue

**Comment by 0x366** [comment]
for those having same error - make sure the firewall port for p2p is opened (default one is 9000)
