### ISSUE TITLE
Ensure the checkpoint-sync-url refers to a node for the correct network

### ISSUE THREAD

**Issue by tsaol** [sigp/lighthouse#4227]
## Description

When I start a lighthouse node with the following command, an error will be prompted

> CRIT Failed to start beacon node, reason: Unable to parse SSZ: OffsetSkipsVariableBytes(388). Ensure the checkpoint-sync-url refers to a node for the correct network,

## Version

version：lighthouse-v3.5.1-x86_64-unknown-linux-gnu.tar.gz

## Present Behaviour

Describe the present behaviour of the application, with regards to this
issue.
`/usr/local/bin/lighthouse bn --network mainnet --execution-endpoint http://localhost:8551 --execution-jwt /tmp/jwtsecret --checkpoint-sync-url=https://mainnet.checkpoint.sigp.io  --disable-deposit-contract-sync`

```
ubuntu@ip-172-18-1-230:~$ /usr/local/bin/lighthouse bn --network mainnet --execution-endpoint http://localhost:8551 --execution-jwt /tmp/jwtsecret --checkpoint-sync-url https://mainnet.checkpoint.sigp.io  --disable-deposit-contract-sync
Apr 22 02:41:19.928 INFO Logging to file                         path: "/home/ubuntu/.lighthouse/mainnet/beacon/logs/beacon.log"
Apr 22 02:41:19.929 INFO Lighthouse started                      version: Lighthouse/v3.5.1-319cc61
Apr 22 02:41:19.929 INFO Configured for network                  name: mainnet
Apr 22 02:41:19.929 INFO Data directory initialised              datadir: /home/ubuntu/.lighthouse/mainnet
Apr 22 02:41:19.929 INFO Deposit contract                        address: 0x00000000219ab540356cbb839cbe05303d7705fa, deploy_block: 11184524
Apr 22 02:41:19.962 INFO Starting checkpoint sync                remote_url: https://mainnet.checkpoint.sigp.io/, service: beacon
Apr 22 02:41:21.606 CRIT Failed to start beacon node             reason: Unable to parse SSZ: OffsetSkipsVariableBytes(388). Ensure the checkpoint-sync-url refers to a node for the correct network
Apr 22 02:41:21.606 INFO Internal shutdown received              reason: Failed to start beacon node
Apr 22 02:41:21.606 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
```

I try to change the check point URL to https://sync.invis.tools , but still the same error

**Comment by michaelsproul** [comment]
You need to use Lighthouse v4 or greater. Lighthouse v3.x doesn't know about the Capella fork that happened last week
