### ISSUE TITLE
Payload cache is not idempotent

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4239]
## Description

When a payload is fetched from the payload cache it is permanently removed, meaning that it may not be able to be fetched again.

https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/beacon_node/execution_layer/src/lib.rs#L375-L378

I think this is most relevant for local blocks which have been blinded and stored in the cache, but it could also apply to blocks from relays which can't be re-fetched after a deadline.

## Expected Behaviour

Re-fetching a payload is of dubious usefulness, but it might be useful in redundant setups or for distributed validators. It would be a minor change to leave the cache entry intact after serving the payload, and rely on the LRU mechanism to evict it. The only downside would be a `clone` instead of a move.

**Comment by michaelsproul** [comment]
To clarify, this is an issue only for DVT setups and only for blinded local payloads

**Comment by eserilev** [comment]
i'd like to pick this one up

**Comment by michaelsproul** [comment]
Thanks @eserilev, that'd be great!
