### ISSUE TITLE
Move away from deprecated bors-ng

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4251]
## Description

The Bors bot that we're using has been deprecated and will soon stop working: https://github.com/apps/bors.

They suggest using Github's own "merge queue" implementation instead, which seems to me like a good solution.

## Steps to resolve

According to Github's docs someone with the highest level of privileges (@paulhauner) needs to _require_ merge queues on the `unstable` branch: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#managing-a-merge-queue

I think for the settings we want:

- Merge method: squash
- Only merge non-failing pull requests: **false** (so we can batch two fixes that might pass together but not individually)
- Timeout: 3 hours, per:

https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/bors.toml#L28

We also need to add the `merge_group` event to the test-suite YAML (I'll raise a PR to do this now).

- [x] Enable merge queues
- [x] Merge #4252 using queue
- [x] Merge #4917 using mergify queue
- [x] Delete `bors.toml` 🫡

**Comment by michaelsproul** [comment]
PR here: https://github.com/sigp/lighthouse/pull/4252. I reckon we should enable the merge queue and then try to merge that PR via the queue.

**Comment by michaelsproul** [comment]
I'm taking a break from this for now because of the issue where Github's merge queue requires CI to finish before queueing (more here: https://github.com/sigp/lighthouse/pull/4254#issuecomment-1532322008).

If GitHub fix this soon we'll be able to switch over. If not we might want to host Bors ourselves

I found some more information about the Bors deprecation from its creator here: https://bors.tech/newsletter/2023/05/01/tmib-76/

**Comment by michaelsproul** [comment]
I commented on the public feedback: https://github.com/orgs/community/discussions/46757#discussioncomment-5786544

**Comment by michaelsproul** [comment]
Another workaround would be to _skip_ the long-running jobs on pull requests, then run them only on the merge queue.

I was having a poke around some other people's workflow YAML to see what they do, and it seems this is a common approach, e.g.

- `determine` job to calculate what to run: https://github.com/bytecodealliance/wasmtime/blob/85cbaa5220fd4028dfc5203171ebd92375949d16/.github/workflows/main.yml#L110-L120
- `status` job to report a unified status based on everything that did run: https://github.com/bytecodealliance/wasmtime/blob/85cbaa5220fd4028dfc5203171ebd92375949d16/.github/workflows/main.yml#L661-L713

**Comment by jimmygchen** [comment]
It was mentioned in [this blog post](https://bors.tech/newsletter/2023/07/01/tmib-78/) that the bors server will be shutdown once Github merge queue is out of beta. GitHub merge queue [went out of beta in July](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/) as well, so probably worth looking into this soon.

@michaelsproul suggested another option is to self host our own Bors instance.
