### ISSUE TITLE
Add ssz content type for /eth/v1/beacon/blinded_blocks endpoint

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#4262]
## Description

The `/eth/v1/beacon/blinded_blocks` beacon api endpoint supports both ssz and json bodies. However, Lighthouse only supports json. This can cause missed blocks when a non-lighthouse VC hits that api with a ssz payload. Moreover, we return a 500 error when we should be returning 415  (The supplied content-type is not supported).

## Version

stable

## Steps to resolve

Easiest way to fix would be to accept ssz bodies on the endpoint. However, we could also return the correct error type as a temporary quick fix.

**Comment by michaelsproul** [comment]
NB: workaround if you're running the Teku VC is to add this flag: `--beacon-node-ssz-blocks-enabled=false`

**Comment by eserilev** [comment]
since I'm already working on a similar feature: https://github.com/sigp/lighthouse/issues/4457

i'd be happy to pick this one up as well

**Comment by jimmygchen** [comment]
Completed in #4504 🎉
