### ISSUE TITLE
No gossip validation before block broadcast

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4264]
## Description

While working on the spec for `broadcast_validation` (https://github.com/ethereum/beacon-APIs/pull/317) I realised that Lighthouse is in violation of the current spec:

> Instructs the beacon node to broadcast a newly signed beacon block to the beacon network, to be included in the beacon chain. A success response (20x) indicates that **the block passed gossip validation** and was successfully broadcast onto the network. **[emphasis mine]**

Presently we don't do any verification of blocks before broadcast :eyes: :

https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/beacon_node/http_api/src/publish_blocks.rs#L50-L54

Arguably this isn't so bad, as the gossip validation would mostly protect the proposer from publishing junk to the network which would reduce their peer score. Given that the beacon node HTTP API is assumed private, an attacker would need access in order to trick the BN into publishing junk. I don't think this poses a significant risk beyond the risk already posed by unfettered access to a beacon node's API.

## Steps to resolve

We could do nothing, or we could add gossip validation in the process of implementing `broadcast_validation`.

There are potentially interactions with the gossip seen cache which could be beneficial. The handling of duplicates and slashable blocks would require special consideration.

## Version

Lighthouse v4.1.0

**Comment by eserilev** [comment]
would it be enough to check if `is_optimistic_or_invalid_block` returns false before broadcasting the block to the network?

**Comment by michaelsproul** [comment]
@eserilev No because that will only return a result for blocks that are already imported, and we need to check the block prior to it being imported

I think we'd need to form a `GossipVerifiedBlock` for the block before broadcasting it, and then import this after broadcast.

@jmcph4 is working on `broadcast_validation` currently, so might make sense to handle it in his PR

**Comment by michaelsproul** [comment]
Closed by #4316
