### ISSUE TITLE
Add consensus version to `submitBlindedBlock` request header

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4284]
## Description

Consider providing fork name via a `Eth-Consensus-Version` HTTP header when sending `submitBlindedBlock` request to remote builder. (or potentially all remote builder requests?)

This change has been included in `builder-specs` v0.3.0, although it's an optional tag:

https://github.com/ethereum/builder-specs/blob/7b269305e1e54f22ddb84b3da2f222e20adf6e4f/apis/builder/blinded_blocks.yaml#L15

This header would help the endpoint provider (relays) discriminate the type the request payload when decoding.

**Comment by Gua00va** [comment]
hey @jimmygchen , is this related to #4525 ?

**Comment by jimmygchen** [comment]
This is a different one, this is for the `submitBlindedBlock` **request**  from the Beacon Node to the Builder in the builder block proposal flow, i.e. `POST /eth/v2/builder/blinded_blocks
` in the below diagram. 

We currently don't send this HTTP header in the request, and is an optional header [in the spec](https://github.com/ethereum/builder-specs/blob/7b269305e1e54f22ddb84b3da2f222e20adf6e4f/apis/builder/blinded_blocks.yaml#L15) that would make it easier for the builder to deserialize the request body.

```mermaid
sequenceDiagram
    participant validator
    participant beacon_node
    participant mev_boost
    Title: Block Proposal with Builder API
    validator->>beacon_node: GET v2/validator/blinded_blocks/{slot}
    beacon_node->>mev_boost: GET v1/builder/header/{slot}/{parent_hash}/{pubkey}
    mev_boost-->>beacon_node: returns bid & blinded payload
    beacon_node-->>validator: returns blinded block
    Note over validator: signs the blinded block
    validator->>beacon_node: POST beacon/blinded_blocks
    beacon_node->>mev_boost: POST /eth/v2/builder/blinded_blocks
    Note right of beacon_node: sends signed blinded beacon block
    mev_boost-->>beacon_node: returns revealed payload
    Note over beacon_node: construct block and broadcast block
```

**Comment by Gua00va** [comment]
hey @jimmygchen, how do I get access to `ChainSpec`  type here https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/builder_client/src/lib.rs#L141
It is required to get the fork name here: 
https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/consensus/types/src/signed_beacon_block.rs#L89

**Comment by Gua00va** [comment]
hey @jimmygchen, how do I get access to some object of `ChainSpec` type here:

https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/beacon_node/builder_client/src/lib.rs#L141


It is required to get fork version here:
https://github.com/sigp/lighthouse/blob/dfcb3363c757671eb19d5f8e519b4b94ac74677a/consensus/types/src/signed_beacon_block.rs#L89

**Comment by jimmygchen** [comment]
Hi @Gua00va 

`ChainSpec` is available on the `BeaconChain` object, you should be able to obtain the `fork_name` when constructing the block, perhaps here:

https://github.com/sigp/lighthouse/blob/071dd4cd9c0ba4ef62f37d52895b83b15adbb36c/beacon_node/http_api/src/publish_blocks.rs#L267-L277

and then pass it to the `post_builder_blinded_blocks` function.

**Comment by jimmygchen** [comment]
I think this is probably not super useful unless the header is mandatory, perhaps revisit this if a new v2 version of the endpoint is added with SSZ support.

**Comment by jimmygchen** [comment]
Closing this. See comment above.

**Comment by michaelsproul** [comment]
I think we actually implemented this header recently off the back of a bug report by JGM:

- https://github.com/sigp/lighthouse/issues/5405

Impl in:

- https://github.com/sigp/lighthouse/pull/5407

**Comment by jimmygchen** [comment]
Nice!
