### ISSUE TITLE
Add more Sepolia bootnodes

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4288]
## Description

Currently Lighthouse has only 1 bootnode for Sepolia, operated by the EF. With this configuration users have reported being unable to find peers.

We should add more bootnodes, e.g. Prysm list 2 more run by the EF and Teku:

https://github.com/prysmaticlabs/prysm/blob/09e22538f9698824b0e9f3664b8a5cfbe3dd544f/config/params/testnet_sepolia_config.go#L12-L16

I've cross-checked this list against https://github.com/eth-clients/sepolia

**Comment by int88** [comment]
We could fix this by using the address list to update:

https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/common/eth2_network_config/built_in_network_configs/sepolia/boot_enr.yaml#L1

Maybe with some setup and test, right? @michaelsproul

**Comment by michaelsproul** [comment]
@int88 Yep we just need to update that list. We can test manually, there's no code for testing the bootnodes

**Comment by int88** [comment]
Let me fix this 😃 @michaelsproul

**Comment by michaelsproul** [comment]
It's all yours, thanks!

**Comment by michaelsproul** [comment]
Fixed in #4297
