### ISSUE TITLE
Update node health endpoint

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4292]
## Description

As suggested by @jmcruz1983 [here](https://github.com/sigp/lighthouse/issues/3613#issuecomment-1545530292) we should update the `/eth/v1/node/health` endpoint to account for the execution node's sync status.

I think we should change the semantics to return syncing if:

```
let unhealthy = syncing || el_offline || optimistic
```

Currently it's just checking the BN's sync status.

## Additional Info

Related to #4291, which will add the `el_offline` field.

**Comment by eserilev** [comment]
i'd like to pick this one up

**Comment by michaelsproul** [comment]
thanks @eserilev! let us know if you need any pointers

the EL offline methods added in #4291 can probably be used for the `el_offline` part
