### ISSUE TITLE
Implement `broadcast_validation` API

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4293]
## Description

The beacon-apis spec recently added a v2 block publishing endpoint which includes the ability to validate blocks before broadcasting them: https://github.com/ethereum/beacon-APIs/pull/317

It is expected that this will be used by MEV relays in order to mitigate unbundling attacks.

Currently the relays are running forks of Prysm and Lighthouse: https://github.com/sigp/lighthouse/pull/4168.

## Steps to resolve

Drawing on the existing implementation from @realbigsean's branch, implement the new `POST /eth/v2/beacon/blocks` and `POST /eth/v2/beacon/blinded_blocks` endpoints. We also need to add some tests of the basic scenarios: trying to broadcast a block that is gossip-valid but holistically invalid (e.g. has an invalid state root), trying to broadcast a block that is valid but equivocates.

In terms of parts of the codebase affected:

- `beacon_node/http_api/src/publish_blocks.rs`: this is where the impl of the API should happen. We should try to share as much as possible between the v1 and v2 endpoints.
- `beacon_node/http_api/src/lib.rs`: wiring for the v1/v2 endpoints
- `common/eth2`: HTTP client implementation (for accessing the new API).
- `beacon_node/http_api/tests/interactive_tests.rs`: probably the best place for the tests (or maybe `lib.rs`, or a new file).

One complication I foresee with the equivocation test is controlling the timing: we want the honest block to pass gossip validation _before_ the equivocating block is processed. But then we want the equivocating block to be processed _before_ the honest block attempts broadcast. We may need to manually inject some events/state in order to simulate this (aside from just supplying the blocks).

**Comment by michaelsproul** [comment]
@jmcph4 has expressed interest in this! Thanks Jack!

**Comment by jmcph4** [comment]
Test cases for this (as discussed with @michaelsproul):

 - [x] `broadcast_validation=gossip`
   - [x] Invalid (400)
   - [x] Full Pass (200)
   - [x] Partial Pass (202)
  - [x] `broadcast_validation=consensus`
    - [x] Invalid (400)
    - [x] Only gossip (400)
    - [x] Only consensus pass (i.e., equivocates) (200)
    - [x] Full pass (200)
  - [x] `broadcast_validation=consensus_and_equivocation`
    - [x] Invalid (400)
    - [x] Invalid due to early equivocation (400)
    - [x] Only gossip (400)
    - [x] Only consensus (400)
    - [x] Pass (200)
  
These are duplicated for the blinded case.

**Comment by Gua00va** [comment]
I would like to work on this.

**Comment by michaelsproul** [comment]
Sorry @Gua00va the implementation has already been done by @jmcph4

**Comment by jmcph4** [comment]
Closed by #4316 -- support landed in [4.3.0 (Priest Witherspoon)](https://github.com/sigp/lighthouse/releases/tag/v4.3.0).
