### ISSUE TITLE
Update operation pool to use correct attestation inclusion reward

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#430]
## Description

The operation pool needs to take the effective balances of the validators into account when calculating which attestations will yield the most rewards.

## Present Behaviour

Previously, we had misunderstood the spec and were paying proposers rewards proportional to their own effective balance, when the correct reward is: `get_base_reward(state, attester_index) // PROPOSER_REWARD_QUOTIENT` as shown in the [spec](https://github.com/ethereum/eth2.0-specs/blob/v0.8.0/specs/core/0_beacon-chain.md#rewards-and-penalties-1). That bug will be fixed as part of the update to v0.8, but we also need to update the op pool, which is the point of this issue.

## Expected Behaviour

Operation pool selects (approximately) optimal attestations to include, based on the reward we will be paid for including them.

## Steps to resolve

The operation pool should use the correct reward value as the weight of each attestation when running the max coverage algorithm, rather than the number of new attesters as it currently does.

**Comment by jzaki** [comment]
I'll join on this one...

**Comment by michaelsproul** [comment]
If someone feels like tackling this, I'm happy to mentor. Otherwise I'll get to it in a little while

**Comment by 192-sean** [comment]
I'd like to tackle this.

**Comment by michaelsproul** [comment]
Hey @192-sean! Thanks for offering to take this on!

Here's a rough plan for how you might get started if you'd like some tips:

1. Add a field to [`AttMaxCover`](https://github.com/sigp/lighthouse/blob/master/eth2/operation_pool/src/attestation.rs) which stores a mapping from fresh validator index to those validators' effective balances (or rewards). Something like `fresh_validator_rewards: HashMap<u64, u64>`.
2. To construct appropriate `AttMaxCover` structs, write a new function that calls `earliest_attestation_validators`, and then converts that bitfield into validator indexes and the effective balances of those validators. To convert the bitfield indices, something like `BeaconState::get_crosslink_committee_for_shard` will be necessary.
2. Modify the `MaxCover` instance for `AttMaxCover` so that it uses the newly added `fresh_validator_rewards` as the `Set` type and updates it appropriately when other attestations are included in the solution (which will remove validators from the map, but never modify their balances). The weight should be the sum of the rewards for all the validators in the fresh validators map.

I don't _think_ any modifications to the `MaxCover` trait itself should be required, but if you need to thread more state through somewhere we can consider modifying it.

Let me know if you have any questions or if you get stuck on anything!

**Comment by michaelsproul** [comment]
You mean once you've called `get_crosslink_committee_for_shard` and have a `CrosslinkCommittee`? The validator indices are in the `committee: Vec<usize>` field of the `CrosslinkCommittee`, with the `i`th entry of the vec corresponding to the `i`th validator of the bitfield.

If you want to chat in real-time, join us on Discord and send me a message (`@sproul`): https://discord.gg/MCvg6ty. I tend to be online 12am-8am UTC

**Comment by michaelsproul** [comment]
Hey @192-sean, I'm interested in taking over this issue to get it done in the next week or so. Are you still working on it? If you want to push what you have so far, I'd be happy to finish it off

**Comment by paulhauner** [comment]
Hey @michaelsproul, is this still relevant? :)

**Comment by michaelsproul** [comment]
We still need to do it at some point, but I don't consider it essential for testnet

**Comment by pscott** [comment]
I can work on that! :)

**Comment by michaelsproul** [comment]
Awesome! Ping me if you have any questions :)
