### ISSUE TITLE
Invalid `eth1_data` returned by /eth/v2/beacon/blocks/{block_id} endpoint

### ISSUE THREAD

**Issue by peske** [sigp/lighthouse#4311]
## Description

I'm trying to get the corresponding Ethereum 1.0 block hash of Ethereum 2.0 _slot_, and for this purpose I'm using `/eth/v2/beacon/blocks/{block_id}` HTTP endpoint. For example. to get the data for slot `6000000`, I'm doing something like:

```console
curl -X 'GET' \
  'http://lighthouse-http-api-url/eth/v2/beacon/blocks/6000000' \
  -H 'accept: application/json'
```

I'm getting the JSON response with the expected structure, but it turned out that `data.message.body.eth1_data` part is always the same for hundreds and thousands of adjacent slots. Other parts of the response look ok (i.e. `data.message.proposer_index` doesn't repeat), but ETH1 block hash is the same.

## Version

```console
Lighthouse v4.1.0-693886b
BLS library: blst-portable
SHA256 hardware acceleration: false
Allocator: jemalloc
Specs: mainnet (true), minimal (false), gnosis (true)
```

Lighthouse is started with the following options:

```console
lighthouse \
  beacon_node \
  --http \
  --http-address=0.0.0.0 \
  --execution-endpoint=http://geth-url \
  --execution-jwt=/root/jwttoken/jwtsecret.hex \
  --slots-per-restore-point=512
```

## Present Behaviour

`/eth/v2/beacon/blocks/{block_id}` HTTP endpoint returns the same ETH1 block hash for many (thousands) adjacent slots. For example for almost all the slots between `6331283` and `6333514` I'm getting the same ETH1 block hash `0x5cfdf5f18f99ce0fb3989f58ae78818134b06c5523bd92ea01afa2f575ce9513`. Surprisingly enough, for one slot from this range (`6331285`) I'm getting different ETH1 block hash (`0x6ed1a1280316c5ec856ba478e572aa72542bcd614d56ba6b1b2c81ea9ebfaae5`). 

## Expected Behaviour

`/eth/v2/beacon/blocks/{block_id}` HTTP endpoint should return different ETH1 block hash for different slots.

## Steps to resolve

I don't know.

**Comment by michaelsproul** [comment]
The eth1_data is the data for the deposit contract, which gets voted on with a delay.

You want the `block.message.body.execution_payload.block_hash`, or the whole execution payload itself, which is the execution layer block.

**Comment by peske** [comment]
@michaelsproul Thanks for trying to help!

> The eth1_data is the data for the deposit contract, which gets voted on with a delay.

I'm getting duplicates no matter the delay. For example, I'm getting the same `eth1_data.block_hash` for slots 3200 - 3400 that are way back in history. But anyway, if I understand your answer correctly this field doesn't refer to the block I need but instead to deposit block.

To be very precise, what I need is to calculate _execution rewards_ for particular slot, and for this reason I need block hash or block number of the execution block that corresponds to this slot. If I understand well, I should get that from `block.message.body.execution_payload.block_hash` instead. But this doesn't exist in `/eth/v2/beacon/blocks/{block_id}` response. Should I use some other HTTP endpoint instead? I couldn't find something like that in [Beacon API spec](https://ethereum.github.io/beacon-APIs).

Thanks!

**Comment by peske** [comment]
@michaelsproul Thanks for your help!

Still bit confused with `eth1_data` because it contains duplicates even for very old slots. But obviously this field is for some other purpose, not the one I need.

I've managed to use `block.message.body.execution_payload.block_hash` and accomplish what I want.

Thanks!

**Comment by michaelsproul** [comment]
@peske Great to hear!

The duplicates are there because the validators are _voting_ on what they see the `eth1_data` as. Each block contains a vote, and once a majority in a 2048 slot period have the same vote, it gets enshrined as canonical. All the gory details are described here if you're curious: https://eth2book.info/capella/part2/deposits-withdrawals/deposit-processing/
