### ISSUE TITLE
Avoid re-locking head during builder health checks

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4314]
## Description

During the builder health checks we lock the head 3 times:

https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/beacon_node/beacon_chain/src/beacon_chain.rs#L5705-L5708

https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/beacon_node/beacon_chain/src/beacon_chain.rs#L5736-L5738

https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/beacon_node/beacon_chain/src/beacon_chain.rs#L5741-L5745

## Steps to resolve

We could load the cached head once at the start of the function and reuse that value. This doesn't require us to _hold_ the lock, the cached head is a small value that's cheap to copy (its large parts are behind an `Arc`).

**Comment by int88** [comment]
I'd like to work on it 😃 @michaelsproul

**Comment by michaelsproul** [comment]
great, thank you @int88 !
