### ISSUE TITLE
Configurable URL length limit

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4333]
## Description

It may be useful to have a way of bumping the URL length limit for the HTTP API. Some VCs will use long query strings to determine the validator indices of a bunch of pubkeys, e.g. Nimbus: https://github.com/status-im/nimbus-eth2/issues/4980.

## Version

v4.2.0

**Comment by aoikurokawa** [comment]
Hello.
I am trying to work on this issue. 
I have one question. I want to decrease the number of validators to query like [here](https://github.com/status-im/nimbus-eth2/pull/5082/files).
So I don't know where to define this number 30 instead of 1024. Do you have any suggestion?
Thank you so much!

**Comment by aoikurokawa** [comment]
@michaelsproul 
Hello.

I am considering to work on this issue. I have checked some libraries like warp and hyper so far.
Then I found this code in hyper. 
https://github.com/hyperium/hyper/blob/96d54b10689042222032f312216ce1df457982f8/src/proto/h1/role.rs#L155-L157

We can not request like 1024 validator's public key as query. 

So I think we have to handle 414URI Too Long error in handle_rejection function. 
https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/common/warp_utils/src/reject.rs#L144

**Comment by michaelsproul** [comment]
Thanks for looking into this @aoikurokawa.

I think the best thing would be to reply with a 414 when the request is too large.

To address the underlying issue of not being able to request _enough_ validators, I've opened a PR to the spec: https://github.com/ethereum/beacon-APIs/pull/367

And a draft impl in Lighthouse: https://github.com/sigp/lighthouse/pull/4872

**Comment by michaelsproul** [comment]
Closing as obsoleted by #4872.
