### ISSUE TITLE
Save ENR to disk on shutdown

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#434]
## Description

ENR's will likely get updated due to a changing IP address when connecting with other nodes. The updated ENR should be saved for future use.

**Comment by b-m-f** [comment]
Hi @AgeManning,

Could https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/discovery.rs#L297 be used for this? 

If yes, what would be an appropriate place to extract this functionality to? 

And the moment this should happen would probably be somewhere after https://github.com/sigp/lighthouse/blob/master/beacon_node/src/run.rs#L130 ?

**Comment by AgeManning** [comment]
Hi @b-m-f , 
Exactly! Sorry I didn't give extra detail in the issue, I should have been more verbose, but you've tracked it down it seems!

I've just had a quick look at this, and my first thought too was to save on shutdown. However, it's quite important for discovery that we don't lose our updated ENR's, which we might do for ungraceful shutdowns. 

Also, I realize that I don't expose the updated ENR, so we don't actually have anything to save :p. 

I think perhaps, the best way, would be to save it, when it gets updated. So I will modify this: 
https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/discovery.rs#L204
to return the ENR instead of the socket. Then we could perform the save when our ENR gets updated. 

I'll make the changes to this shortly (the next day or two and let you know). 

After the modification, it shouldn't be too hard to save when the ENR gets updated :).

**Comment by b-m-f** [comment]
Cheers. I will give it a try.

**Comment by b-m-f** [comment]
Hi @AgeManning,

I just opened https://github.com/sigp/lighthouse/pull/443 . Havent tested it yet, will get around to it this weekend. 

Maybe you have some feedback already, then Id be happy to update the PR. 
I am new to both Rust and the ETH spec :)

**Comment by AgeManning** [comment]
Completed in #443
