### ISSUE TITLE
Combine poll_fn's in Network service

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#435]
## Description

A cleaner approach to polling the network channel as well as driving the libp2p service is to combine both poll fn's rather than forming a loop over them.

**Comment by b-m-f** [comment]
@AgeManning Would love to give this a go if no one is working on it

**Comment by AgeManning** [comment]
Hey, yep. I've had another think about this. Perhaps we don't need to actually combine the poll_fn's rather, revert them back to two separate loops (I had this before, I can't think of reason not to at the moment). 

Currently, we ensure that the two Poll's are not ready, before returning NotReady: see here: https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/service.rs#L110

I think perhaps it is sufficient to loop over the first poll and break on not ready, then loop over the second poll. 

It is important to test to see there is no lag if we do this. Running two nodes with a single validator and watching blocks propagate instantly is a test that this should still work. 

I'm yet to have the time to build a proper test suite for all the networking, but it's on the to-do list. :). 

Let me know if you need more information.

**Comment by AgeManning** [comment]
Resolved in #471
