### ISSUE TITLE
Enable `--slasher-broadcast` by default

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4350]
## Description

These days hoarding slashings is no longer a viable strategy. Prysm already default their slasher to broadcast by default, and I've been meaning to do the same for Lighthouse for a long time.

I think we should change the semantics of the `--slasher-broadcast` flag as follows:

- `<no flag>`: enable broadcast (new default).
- `--slasher-broadcast`: same as present, enable broadcast.
- `--slasher-broadcast=false`: disable broadcast (new argument).
- `--slasher-broadcast=true`: enable broadcast (new argument).

I think this can be achieved using `clap`'s `.default()` method.

## Steps to resolve

- [x] Modify the CLI parsing logic for `--slasher-broadcast`
- [x] Add/adjust tests for the 4 configurations of flags described above

**Comment by Gua00va** [comment]
If this issue is still open I would like to work on this issue.
