### ISSUE TITLE
sigp/lcli container image only built for modern x86 CPUs

### ISSUE THREAD

**Issue by dboreham** [sigp/lighthouse#4370]
## Description

The lcli binary shipped in the [sigp/lcli container image](https://hub.docker.com/r/sigp/lcli/tags) is built to run on a CPU with extensions (probably AVX2?) that are not present on all x86 CPUs. The result is that when the tool is run on such a machine, it throws an illegal instruction exception.

Such CPUs are not particularly rare : we have encountered the issue both in GitHub runners and in VMs in our internal build infra.

## Version

Tested [this container image](https://hub.docker.com/layers/sigp/lcli/latest/images/sha256-37097766174d577210244d0f3164a8878ccee8e1eac5866eea3e22471568fb3c?context=explore) and also a local built from the current stable branch.

## Present Behaviour

The `lcli` tool, when run with the `insecure-validators` subcommand, throws an illegal instruction exception on some CPUs.

e.g.:

```
$  ./lcli insecure-validators --count 4 --base-dir $(pwd) --node-count 4
Validator 1
Illegal instruction (core dumped)
```

## Expected Behaviour

Should not throw illegal instruction exception.

## Steps to resolve

The lcli container should be built with a portable compiler target, but it isn't.

**Comment by dboreham** [comment]
It appears that although the [Dockerfile](https://github.com/sigp/lighthouse/blob/stable/lcli/Dockerfile#L7) has the arg `PORTABLE` [which is set](https://github.com/sigp/lighthouse/blob/stable/.github/workflows/docker.yml#L145) `=true` in the build script, `PORTABLE` doesn't actually do anything:

```
$ grep -R PORTABLE .
./.github/workflows/docker.yml:                      --build-arg PORTABLE=true \
./lcli/Dockerfile:ARG PORTABLE
./lcli/Dockerfile:ENV PORTABLE $PORTABLE
```

**Comment by dboreham** [comment]
Related: https://github.com/sigp/lighthouse/issues/1395

**Comment by dboreham** [comment]
This fixes it for me:

```
diff --git a/lcli/Dockerfile b/lcli/Dockerfile
index 98f33f215..485ebfd5b 100644
--- a/lcli/Dockerfile
+++ b/lcli/Dockerfile
@@ -6,7 +6,7 @@ RUN apt-get update && apt-get -y upgrade && apt-get install -y cmake libclang-de
 COPY . lighthouse
 ARG PORTABLE
 ENV PORTABLE $PORTABLE
-RUN cd lighthouse && make install-lcli
+RUN if [ "$PORTABLE" = true ] ; then export FEATURES=portable; fi && cd lighthouse && make install-lcli

 FROM ubuntu:22.04
 RUN apt-get update && apt-get -y upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*
```


```
$ ./lcli-fixed insecure-validators --count 4 --base-dir $(pwd) --node-count 4
Validator 1
WARN: Scrypt parameters are too weak (n: 2, p: 1, r: 8), we recommend (n: 262144, p: 1, r: 8)
Validator 2
WARN: Scrypt parameters are too weak (n: 2, p: 1, r: 8), we recommend (n: 262144, p: 1, r: 8)
Validator 3
WARN: Scrypt parameters are too weak (n: 2, p: 1, r: 8), we recommend (n: 262144, p: 1, r: 8)
Validator 4
WARN: Scrypt parameters are too weak (n: 2, p: 1, r: 8), we recommend (n: 262144, p: 1, r: 8)
```

**Comment by michaelsproul** [comment]
Good catch, thanks

Would you mind opening a PR to fix it? My preffered fix would be to remove the `PORTABLE` arg and pass `FEATURES` through from the Dockerfile. The existing makefile will then use those features here:

https://github.com/sigp/lighthouse/blob/c547a11b0da48db6fdd03bca2c6ce2448bbcc3a9/Makefile#L53-L58

We should also update the Github action that builds the image so that it uses `FEATURES=portable` instead of `PORTABLE=true`:

https://github.com/sigp/lighthouse/blob/c547a11b0da48db6fdd03bca2c6ce2448bbcc3a9/.github/workflows/docker.yml#L131-L148
