### ISSUE TITLE
EN-BN connection state check

### ISSUE THREAD

**Issue by vankop** [sigp/lighthouse#4379]
## Description

Is it possible to check EN-BN connection health? [/lighthouse/eth1/syncing](https://lighthouse-book.sigmaprime.io/api-lighthouse.html#lighthouseeth1syncing) doesnt work without `--eth1` flag. For prysm there is `/eth/v1alpha1/node/eth1/connections` that allows to check connection status

## Version

4.2

**Comment by michaelsproul** [comment]
Does `/eth/v1/node/syncing` cover your use-case? The `el_offline` field indicates whether the execution node is connected and healthy

**Comment by vankop** [comment]
thanks, `el_offline` is fine
