### ISSUE TITLE
Implement v0.8 optimized cached tree hash

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#440]
## Description

As mentioned in #432, spec v0.8.0 changes Merkleization to have significantly more padding nodes than previous specs.

Our current tree hash caching implementation wastes space by storing padding nodes. 

## Notes

I've discussed this with @michaelsproul who expressed some interest in taking this issue. We have some strategies in mind, but I won't go to the effort of detailing them unless someone wants to hear them.

**Comment by paulhauner** [comment]
We should ensure we test the new cached tree has in the `ssz_static` EF tests.

See: https://github.com/sigp/lighthouse/blob/bbde06eb9f2b7a5ae00a3c6f41295bb8f1fcd083/tests/ef_tests/src/cases/ssz_static.rs#L124-L135

**Comment by michaelsproul** [comment]
Assigning myself with some intention of working on this soon (maybe in the lead up and during DevCon, but not necessarily before the 0.0.1 release)

**Comment by michaelsproul** [comment]
Getting into this now
