### ISSUE TITLE
Shift networking configuration into configs

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#4401]
## Description

The following consensus PRs shift some of the network constants into the configuration files:
- https://github.com/ethereum/consensus-specs/pull/3394
- https://github.com/ethereum/consensus-specs/pull/3375

We should move these constants also. 

Our configuration setup is located here: https://github.com/sigp/lighthouse/blob/stable/consensus/types/src/eth_spec.rs

We need to modify this to incorporate constants and in the associated code. Please hit me up for further info/help if needed :)

**Comment by AgeManning** [comment]
The configurations we need to add are:
| name | default value | location in code to replace |
|------|-----|-----|
|`gossip_max_size` | 10485760 | [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/config.rs#L23)  EDIT: We use the 10x version as the default and divide by 10 for the pre-merge version.  |
|`max_request_blocks`| 1024 | [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/rpc/methods.rs#L21) |
|`epochs_per_subnet_subscription`| 256 - I think this is already there | N/A |
|`min_epochs_for_block_requests`| 33024 | I dont think we have this, but it should go in [this function](https://github.com/sigp/lighthouse/blob/stable/beacon_node/network/src/beacon_processor/worker/rpc_methods.rs#L285) and the blocks_by_root. @pawanjay176  can help here|
|`max_chunk_size`| 1048576| [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/rpc/protocol.rs#L113)|
|`ttfb_timeout`| 5| [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/rpc/protocol.rs#L120) | 
|`resp_timeout`| 10 | [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/rpc/handler.rs#L35) |
|`attestation_propagation_slot_range`|  32|  This is currently not configureable, but we can add it [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/beacon_chain/src/attestation_verification.rs#LL1053C32-L1053C32) - check with @michaelsproul |
|`maximum_gossip_clock_disparity`|  500 |  [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/beacon_chain/src/beacon_chain.rs#L213) @michaelsproul  might be able to help with this one| 
|`message_domain_invalid_snappy`| 0x00000000 | we don't use it, but it's [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/config.rs#L43)|
|`message_domain_valid_snappy`| 0x01000000 | [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/config.rs#L44) |
| `subnets_per_node` | 2 - already there I think | N/A |


So what we need to do, is add these fields into the ChainSpec: https://github.com/sigp/lighthouse/blob/stable/consensus/types/src/chain_spec.rs#L32

We should add them into the networking section here: https://github.com/sigp/lighthouse/blob/stable/consensus/types/src/chain_spec.rs#L165

Then for each of the hard-coded networks, i.e mainnet, put in the default values: https://github.com/sigp/lighthouse/blob/stable/consensus/types/src/chain_spec.rs#L473

For all the networks, just use the defaults listed above. 


Then for all the places where we have these values being used in the code, replace them with the values from the chain spec. 

Most places should have access to a generic `EthSpec` type. You can get `ChainSpec` values via: EthSpec::default_spec(). 

So for example, the first one is `gossip_max_size`. The location for that variable is [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/config.rs#L23). We should remove that constant (and the one underneath it, as its just 10x the value. 

Then in the code that we are using it, like here: https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/config.rs#L47 and here: https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/config.rs#L457 we need to accept an EthSpec. 

So, ideally the function could require the generic, i.e 
```rust
pub fn gossipsub_config<TSpec:EthSpec>(...) { ... }
```
It gets used [here](https://github.com/sigp/lighthouse/blob/stable/beacon_node/lighthouse_network/src/service/mod.rs#L242): so you can pass the TSpec into the function. 

That should resolve the first one. 

@pawanjay176 should be able to help with all of these.

**Comment by Gua00va** [comment]
I would like to take up this issue.
