### ISSUE TITLE
Add QUIC support

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#4402]
## Description

Initial tests show significant performance improvements (bandwidth and latency) with the QUIC protocol. Lighthouse is capable of supporting this amongst itself with other compatible lighthouse nodes. We can therefore test this transport fairly easily and see the results. 

This requires our own ENR standard, we also need to add some metrics that indicate the type of transport used in order to effectively evaluate the difference between this transport and regular TCP. 

This will be fully backwards compatible.

**Comment by ameya-deshmukh** [comment]
@AgeManning is this something still on your radar? Would love to see if I can work on this!

**Comment by AgeManning** [comment]
Hey @ameya-deshmukh 

Thanks for the interest. It is on my radar and is a fairly trivial update. I was just waiting for us to update to the latest libp2p, making sure that is stable then adding in quic support. 

Supporting QUIC is a fairly trivial change (we just add an extra transport) and we need to specify a new ENR field. The rest is mainly documentation and testing. 

If this is something you'd like to do, feel free make a PR (probably best for just the transport) then we can discuss how we want the ENR to look and also whether it is on by default. I was thinking a default port of 9090.

**Comment by ameya-deshmukh** [comment]
Sure!

**Comment by jxs** [comment]
addressed on #4577
