### ISSUE TITLE
Simplify next_epoch_start_shard

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#442]
## Description

`next_epoch_start_shard` could be implemented in terms of `get_epoch_start_shard`, using `RelativeEpoch::Next` now that we definitely have a stable committee cache for the next epoch.

**Comment by blacktemplar** [comment]
I had a look into this issue (my first work on this repo here), but it seems that the committee cache for the next epoch is not always initialized.

I created a small test (see https://github.com/blacktemplar/lighthouse/blob/5ebcd445ab132114b4f42a4b3eff4bfa925b2b58/eth2/types/src/beacon_state.rs#L310) for this and for example the following test run prints some uninitialized messages:

`cargo test --package beacon_chain --release finalizes_with_full_participation -- --nocapture`

Am I doing something wrong or is this another bug?

**Comment by michaelsproul** [comment]
Welcome! Thanks for checking us out!

You're on exactly the right track. It's true that on `master` the cache isn't always initialised. However, that's changing as part of our move to v0.8 of the spec (PR #444). We'll probably merge that PR on Monday, at which point we'll be ready for a PR from you on this issue :)

**Comment by michaelsproul** [comment]
Fixed in the update to v0.8.3 some time ago (removed entirely)
