### ISSUE TITLE
Depecate `exchangeTransitionConfiguration` functionality

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#4442]
## Description

EL clients log errors if we don't query this endpoint, but they are making releases that remove this error logging. After those are out we can stop calling it, after which point EL teams will remove the endpoint entirely. I don't think this necessarily has to be done in the deneb release but should be done before it. 

https://hackmd.io/@n0ble/deprecate-exchgTC

**Comment by Gua00va** [comment]
@realbigsean ,
 https://github.com/sigp/lighthouse/blob/stable/beacon_node/execution_layer/src/engine_api/http.rs#L937C6-L937C6
This is the endpoint that is to be deprecated, right?

**Comment by michaelsproul** [comment]
@Gua00va Yeah that's right!

**Comment by Gua00va** [comment]
@realbigsean Should I just return an error or a log whenever the function is called? If yes, what kind.

**Comment by realbigsean** [comment]
Hey, @Gua00va ! We want to make sure we aren't calling it at all anymore, so I'd just delete it and anywhere we're using it

**Comment by jimmygchen** [comment]
Completed in #4517  🎉
