### ISSUE TITLE
Getting shuffling efficiently in gossip blobs signature verification

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#4447]
## Description

If we get a cache miss in the `beacon_proposer_cache`, we need a way to get the state which provides the shuffling for the blob. In block processing we fall back to the snapshot cache, and then remove the state from the snapshot cache (in the normal case), and attach it to the block for use during block processing. 

This means if we're getting the block first and getting a proposer cache miss, when verifying blobs we'd be likely to load the state and parent block from the db when we shouldn't have to because they're in memory.  We do prime the`beacon_proposer_cache` after finding shuffling for the block, but there's some raciness there with blob arrival/verification.

**Comment by jimmygchen** [comment]
This is the relevant WARN log we're getting:
> Aug 21 01:27:12.431 WARN Snapshot cache miss for blob verification, index: 3, block_root: 0xfd7c…a70a, service: beacon

@realbigsean mentioned that `tree-states` actually fixes this issue, but it's likely to be merged after deneb, so it would be good to fix this now. I'll take a deeper look.

**Comment by jimmygchen** [comment]
Completed in #4646 . Tested this on devnet-8, sent a few blobs and didn't see any cache miss 🎉
