### ISSUE TITLE
Support signing BlobSidecar with Web3Signer

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4453]
## Description

Support Web3Signer signing for blob sidecars. Depends on this Web3Signer issue: https://github.com/ConsenSys/web3signer/issues/726

Once the schema and signing is implemented in Web3Signer, the VC needs to construct a `Web3SignerObject` here:
https://github.com/sigp/lighthouse/blob/4c9fcf1e83c10d7115af1a98f6e1a97bad1114c6/validator_client/src/signing_method.rs#L187-L190

**Comment by jimmygchen** [comment]
Remote signing api spec PR merged here: https://github.com/ethereum/remote-signing-api/pull/4

TL;DR: 
> For blob sidecar signing we can use the blinded sidecar type for both using the blob_root instead of the full blob.

**Comment by realbigsean** [comment]
Closing due to deprecation of blob signing
