### ISSUE TITLE
Support SSZ request body for POST /beacon/blocks endpoints (v1 & v2)

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4457]
## Description

The `/eth/v1/beacon/blocks` and `/eth/v2/beacon/blocks` beacon api endpoint supports both ssz and json bodies ([spec here](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/publishBlock)). However, Lighthouse only supports json. This can cause missed blocks when a non-lighthouse VC hits that api with a ssz payload. Moreover, we return a 500 error when we should be returning 415 (The supplied content-type is not supported).

There is a separate issue for blinded blocks endpoints in #4262 

## Version

stable

## Steps to resolve

Add SSZ request body support, use the supplied `Eth-Consensus-Version` HTTP request header to decode the SSZ bytes.

**Comment by eserilev** [comment]
would adding ssz request body support for these endpoints look something like:

defining post routes where the `Content-Type` header matches `application/octet-stream`

```
in beacon_node/http_api/src/lib.rs starting around line 3879

let routes = warp::get()
.and( ... )
.boxed()
.uor(
    warp::post().and(
       warp::header::exact("Content-Type", "application/octet-stream").and(
           post_beacon_blocks
               .uor(post_beacon_blocks_v2_ssz)
               .uor(post_beacon_blocks_v1_ssz),
                ),
            ),
      )
.uor(...)
```
then parsing the request body as ssz and executing the post beacon block logic in the relevant 'route handler' i.e. in `post_beacon_blocks_v2_ssz` and `post_beacon_blocks_v1_ssz`

**Comment by jimmygchen** [comment]
Hi @eserilev 

I don't think we have any endpoint that supports SSZ request body yet, so I'm not exactly sure how it would look like, will probably need to look into the docs. 

I think you got the idea though - we do need to define a separate route(s) for this. In your above example, I _think_ the existing `post_beacon_blocks` json endpoint should probably be placed outside the `application/octet-stream` header matcher, otherwise it won't route the json requests to that handler. (I could be wrong though)

**Comment by eserilev** [comment]
great, I think i have a general understanding of this feature. I'd be happy to work on it

**Comment by jimmygchen** [comment]
Completed in #4479 🎉  Thanks @eserilev
