### ISSUE TITLE
Fork choice should examine beacon_block_root rather than target.root

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#447]
## Description

Fork choice looks at the epoch boundary block (`attestation.data.target.root`) rather than the most recent Beacon block when determining the head (`attestation.data.beacon_block_root`), here: https://github.com/sigp/lighthouse/blob/bbde06eb9f2b7a5ae00a3c6f41295bb8f1fcd083/beacon_node/beacon_chain/src/fork_choice.rs#L135

## Steps to resolve

We should change fork choice to use the `beacon_block_root` of the attestation instead, as per the spec: https://github.com/ethereum/eth2.0-specs/blob/v0.8.1/specs/core/0_fork-choice.md#on_attestation

**Comment by paulhauner** [comment]
Fixed in #451

https://github.com/sigp/lighthouse/blob/177df12149f2719c305958a76bcdca71ee7e83e4/beacon_node/beacon_chain/src/fork_choice.rs#L130
