### ISSUE TITLE
Lighthouse fails to start with Capella fork at Epoch 0 in Genesis State

### ISSUE THREAD

**Issue by barnabasbusa** [sigp/lighthouse#4476]
## Description
As we are approaching Deneb, it would be great if clients would be able to start from a Capella state instead of Bellatrix.

## Version
'ethpandaops/lighthouse:boxed-blobs-d534ac0'

## Present Behaviour
If `capella_fork_epoch=0` lighthouse produces this error message: 
```
CRIT Failed to start beacon node             reason: Unable to parse genesis state SSZ: OffsetOutOfBounds(626773674)
```

## Expected Behaviour
Lighthouse should be able to handle capella at epoch 0

## Steps to resolve
Create a testnet where you configure the genesis file and set the capella fork epoch at 0.

**Comment by michaelsproul** [comment]
Did you get this sorted @barnabasbusa?

**Comment by barnabasbusa** [comment]
I realized that I generated the genesis file with bellatrix, now I'm testing with new genesis file generation. 
However it looks like the issue still persist, I'll reopen the issue once I'm more confident that it's not just a misconfig on my side.
Would you expect this to just work out of the box?

**Comment by michaelsproul** [comment]
Yeah it should work out of the box, we've run local testnets with Capella from genesis. If you're getting SSZ decode errors that's more likely to be a misconfig

**Comment by barnabasbusa** [comment]
Issue has been resolved. It was a config issue on my end. Sorry for the noise.
