### ISSUE TITLE
Prefer `test_logger` over `null_logger`

### ISSUE THREAD

**Issue by jmcph4** [sigp/lighthouse#4499]
## Description

There's likely no case where `null_logger` is preferable over `test_logger` as the latter allows runtime configuration of logging output whereas the former hardcodes us into discarding logging output no matter what.

## Version

0c7eed5

## Present Behaviour

```
$ grep -rin "null_logger" --exclude-dir=target | wc -l
37
```

## Expected Behaviour

```
$ grep -rin "null_logger" --exclude-dir=target | wc -l
0
```

## Steps to resolve

Probably just a `sed` job realistically, although some areas may be slightly more involved to patch (I haven't checked very thoroughly at this stage).

**Comment by TouchstoneTheDev** [comment]
Hi Do I have to "Find all occurrences of null_logger in the codebase & Replace all occurrences of null_logger with test_logger." to solve this issue ?

**Comment by jmcph4** [comment]
> Hi Do I have to "Find all occurrences of null_logger in the codebase & Replace all occurrences of null_logger with test_logger." to solve this issue ?

Yeah more or less -- like I said in the ticket, I haven't confirmed but it should be pretty straightforward. 

Are you wanting to take it on?

**Comment by TouchstoneTheDev** [comment]
yeah might be can i first sub a PR

**Comment by iamit-singh** [comment]
Hi @jmcph4, is this still relevant? can I take this?

**Comment by dapplion** [comment]
Note, we should consistently use `test_logger` feature to toggle the logger on/off instead of having to manually edit a bool

**Comment by jimmygchen** [comment]
Completed in #6013 🥳
