### ISSUE TITLE
Add Deneb spec tests for v1.4.0-beta.0

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4519]
## Description

The following Deneb EIPs have been implemented under #4518, and we should be ready to tests these with the latest spec tests ([Spec tests for v1.4.0-beta.0](https://github.com/ethereum/consensus-spec-tests/releases/tag/v1.4.0-beta.0)) .

- EIP-7044: Lock voluntary exit domain on capella https://github.com/ethereum/consensus-specs/pull/3288
- EIP-7045: Increase max attestation inclusion slot https://github.com/ethereum/consensus-specs/pull/3360
- EIP-4788: Expose parent beacon block root in EL https://github.com/ethereum/consensus-specs/pull/3421

**Comment by realbigsean** [comment]
Completed in https://github.com/sigp/lighthouse/pull/4518
