### ISSUE TITLE
Use standard "liveness" endpoint in the VC

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#4522]
## Description

We have two implementations of "liveness" detection in the BN API:

1. [`lighthouse/liveness`](https://lighthouse-book.sigmaprime.io/api-lighthouse.html#lighthouseliveness)
1. [`/eth/v1/validator/liveness/{epoch}`](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v2.4.0#/Validator/getLiveness) (implemented in #4343)

I think we should switch the VC to use (2) rather than (1). However, we should heed [this comment](https://github.com/sigp/lighthouse/issues/4243#issuecomment-1525071775):

> Deciding how to handle it in the VC is slightly more complicated. We could switch to the standard endpoint as soon as it's available, but this would break compatibility with older versions of the Lighthouse BN. Alternatively we could wait a release or two before switching over the VC. I think I prefer switching immediately, as most users will update VC+BN together anyway.

I'm open to either strategy. If we get to implementing it in the VC before #4343 is released, then all is good. Otherwise, we're also fine.

**Comment by Gua00va** [comment]
I would like to work on this!

**Comment by jimmygchen** [comment]
Completed in #4853 🎉
