### ISSUE TITLE
Add a flag to store blobs for a longer period of time

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4523]
## Description

Currently blobs are stored for 4096 epochs ~18 days (`MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS`) before they are pruned according to the spec. It would be good have a flag (hidden?) that allows extending this, as it'd be useful to retain blobs for a longer period of time for testing / debugging.

**Comment by Gua00va** [comment]
Hey, I would like to work on this.

**Comment by jimmygchen** [comment]
Thanks @Gua00va ☺️   just double checking before you start - @ethDreamer have you started work on this?

**Comment by ethDreamer** [comment]
nope - all yours @Gua00va :D

**Comment by michaelsproul** [comment]
This is already implemented as `--blob-prune-margin-epochs`:

```rust
                .help("The margin for blob pruning in epochs. The oldest blobs are pruned \
                       up until data_availability_boundary - blob_prune_margin_epochs.")

```

That covers the database side. Maybe there's some extra plumbing to make these blobs available to peers? We can re-open if that's the case.

(Blob pruning with margins is tested and working as of https://github.com/sigp/lighthouse/pull/4693).
