### ISSUE TITLE
Lighthouse `v4.3.0` doesn't send `Eth-Consensus-Version` header

### ISSUE THREAD

**Issue by xenowits** [sigp/lighthouse#4525]
## Description

The `/eth/v1/validator/blinded_blocks` [endpoint](https://ethereum.github.io/beacon-APIs/#/Validator/produceBlindedBlock) doesn't send the `Eth-Consensus-Version` header in the latest lighthouse release `v4.3.0`.

This breaks compatibility with [clients](https://github.com/attestantio/go-eth2-client/blob/master/http/http.go#L271-L275) that consume this API which errors when it can't find the `Eth-Consensus-Version` header in the response.

## Version

Lighthouse/v4.3.0-dfcb336/x86_64-linux

## Present Behaviour

Lighthouse BN **doesn't** return the `Eth-Consensus-Version` header in the response to API call to `/eth/v1/validator/blinded_blocks` endpoint.

See this screenshot:
<img width="1402" alt="Screenshot 2023-07-20 at 20 58 44" src="https://github.com/sigp/lighthouse/assets/43061995/ed040bee-86b8-49a6-8eda-39e71288f236">

```
curl --location 'http://lighthouse-bn-v4.3.0/eth/v1/validator/blinded_blocks/{slot}?randao_reveal=0xc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&skip_randao_verification='
```

## Expected Behaviour

Lighthouse BN should return the `Eth-Consensus-Version` header in the response to API call to `/eth/v1/validator/blinded_blocks` endpoint.

## Steps to resolve

None.

**Comment by jimmygchen** [comment]
Thanks for raising this bug! It looks like we're also missing the `Eth-Consensus-Version` header in the `GET /eth/v1/validator/blocks` endpoint as well.

**Comment by eserilev** [comment]
can i pick this one up?

**Comment by Gua00va** [comment]
I would like to work on this issue.

**Comment by jimmygchen** [comment]
Completed in #4528  🎉
