### ISSUE TITLE
Improve logging format

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#453]
## Description

I think the logs would be nicer if we have a dedicated space between the message title and the key-values associated with `slog`. 

An example of this format is in geth. 

```
INFO [07-26|12:31:47.821] Maximum peer count                       ETH=25 LES=0 total=25
INFO [07-26|12:31:47.826] Starting peer-to-peer node               instance=Geth/v1.9.0-unstable-78d90c47/linux-amd64/go1.12.3
INFO [07-26|12:31:47.826] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
```

This issue involves changing the format of the `slog::Logger`. Hopefully a single change in `main.rs` will propagate this format through the codebase :).

**Comment by blacktemplar** [comment]
I took a take on this, see: #461. Not sure if this is the most elegant way to do it, but it does what we want. Although there are quit many logs which have a quite long message, so it looks not totally aligned. We can also change the width of the alignment, at the moment it is 30 characters for the message. I just saw your geth example uses 40 characters, I can increase that if you want.
