### ISSUE TITLE
Add SSZ support to validator block production endpoints

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4531]
## Description

Recently we've had a few users reporting that the `POST beacon/block` endpoints in Lighthouse don't support SSZ request bodies, and this is currently being worked on in issue #4457. It seems like some validator clients are now using SSZ for the block proposal flow.

To support the block proposal flow using SSZ end-to-end, we should also add SSZ support to the following block production endpoints:
- GET `/eth/v2/validator/blocks/{slot}`
- GET `/eth/v1/validator/blinded_blocks/{slot}`

It might be worth getting this implemented soon, looking at the benchmarks from this issue:
https://github.com/ethereum/builder-specs/issues/53

> SSZ seems 40-50x faster
Considering 20-40ms per coding on average, that's up to 200-300ms JSON latency (or more).
> 
> Sending the data SSZ encoded could reliably shave 200-250ms off each getPayload roundtrip.

There is also a related issue to use SSZ in builder API queries: #3701

**Comment by eserilev** [comment]
id be happy to pick this one up

**Comment by jimmygchen** [comment]
That'd be great, thanks @eserilev! ☺️

**Comment by ghost** [comment]
Would be awesome to add to be able to support running Teku VC with Lighthouse BN to help with client diversity!  Thanks guys!

Context: https://discord.com/channels/605577013327167508/605577013331361793/1134130514232623255

Looks like same issue with Prysm VC <> Lighthouse BN, see https://github.com/prysmaticlabs/prysm/issues/12467#issuecomment-1654253463 for context

**Comment by jimmygchen** [comment]
Completed in #4534 🎉
