### ISSUE TITLE
Add logic to handle whether to drop peers given their protocol support

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#454]
## Description

Currently lighthouse will disconnect from peers that do not support all the libp2p protocols that we do (Gossipsub / Ping / All Eth 2 RPC's). Note: We will be removing Ping in favour of discv5 ping in the near future. 

This issue is about adding specific logic around which minimal protocols a peer can support that we accept without disconnecting. 

Potentially we should allow a subset of the RPC protocols and decide if we should support peers that don't support gossipsub.

**Comment by b-m-f** [comment]
Hi @AgeManning,

I found https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/sync/simple_sync.rs#L169 ,  https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/message_handler.rs#L246 and https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/sync/simple_sync.rs#L115 as places where a peer is or could be disconnected.

Is there any other place I am missing? 
From what I see the disconnect could happen by checking the remote clients capabilities on a handshake, or if an RPC of a specific kind returns with a ErrorResponse?

And for clients that do not support gossiping, does this mean that they will have to be stored in a separate data structure, for which a request will need to be sent to each Peer in it, when an important update has to be broadcast?

**Comment by AgeManning** [comment]
This one is a little more involved in libp2p land. We should solidify this issue as we progress with interop. For now, I think we just let peers support arbitrary protocols so clients don't drop others instantly. 

When negotiating protocols, if an error occurs when negotiating an outbound request the peer gets dropped. This logic needs to be handled in our fork of rust-libp2p for gossipsub, and occurs here: 
https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/handler.rs#L260

I'm currently working a branch for interop which allows clients to not support protocols. 

I'll have to rewrite some of our networking side to match the recently merged ethereum 2.0 network specification. 

I guess we decide on the logic of this after we have a few clients talking I think.

**Comment by divagant-martian** [comment]
Don't we already do this to some extent? we have [this](https://github.com/sigp/lighthouse/blob/850a2d5985cc08e978b5b492bb0cb90a47359605/beacon_node/eth2_libp2p/src/peer_manager/mod.rs#L345)

**Comment by AgeManning** [comment]
Yes we do in some extent for the RPC. 

I think there may be crawlers on the network that only support gossipsub for example. I guess as the network grows we will adjust and change these. 

Until specific implementations complain, lets just keep what we have and we can adapt as we go.
