### ISSUE TITLE
Client Diversity: Teku VC <> Lighthouse BN does not work

### ISSUE THREAD

**Issue by ghost** [sigp/lighthouse#4550]
See comment here: https://github.com/Consensys/teku/issues/7397#issuecomment-1655586084
> Hi @ybstaked this incompatibility is because we have implemented the config spec changes as per [ethereum/consensus-specs#3375](https://github.com/ethereum/consensus-specs/pull/3375). It seems like Lighthouse hasn't implemented those yet. It's worth raising this issue on their Github, since we wouldn't revert to supporting old versions. In the meantime, instead of `auto` can just point to a specific network on the Teku VC side.

## Client Versions
```
Teku VC: Version: 23.6.2
Lighthouse BN: Version: v4.3.0
```

### Teku VC
```
teku validator-client --network=auto --log-include-validator-duties-enabled=true --log-include-events-enabled=true --metrics-enabled=true --metrics-host-allowlist=* --metrics-port=8081 --metrics-interface=0.0.0.0 --data-path=/data --validators-external-signer-public-keys="http://$POD_IP:5050/api/v1/eth2/publicKeys" --beacon-node-api-endpoint="http://cl-lighthouse-beacon.eth2-prater:5052" --validators-early-attestations-enabled=false --validators-external-signer-url="http://$POD_IP:5050" --validators-external-signer-timeout=5000 --log-color-enabled=false --validators-proposer-config=/data/new-fee-recipient.json --validators-builder-registration-default-enabled=true --validators-proposer-blinded-blocks-enabled=true
```

## Errors
```
Failed to retrieve network spec from beacon node endpoint 'http://cl-lighthouse-beacon.eth2-prater:5052/'.
Details: Missing value for spec constant 'GOSSIP_MAX_SIZE'
```

## Related
- https://github.com/Consensys/teku/issues/7397
- https://github.com/prysmaticlabs/prysm/issues/12467
- https://github.com/sigp/lighthouse/issues/4531

**Comment by michaelsproul** [comment]
This is mostly an issue with Teku's VC, which as noted can be worked around by using `--network=mainnet` (rather than `auto`). So, it's not a hard incompatibility.

Even so, Lighthouse will gain the new config parameters on `/eth/v1/config/spec` when this PR is merged: https://github.com/sigp/lighthouse/pull/4426.

**Comment by michaelsproul** [comment]
Teku VC + Lighthouse BN should be working now, or at least isn't broken beacuse of this issue 😅 

Closing, but please re-open if this is still a problem
