### ISSUE TITLE
Implement `Decode` for `SignedBlockAndBlobSidecars`

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#4580]
See description here: https://github.com/sigp/lighthouse/pull/4578

**Comment by PatStiles** [comment]
Interested in trying this over the next week @realbigsean . If I haven't made progress someone else feel free to pick it up!

**Comment by realbigsean** [comment]
Sounds good!

**Comment by jimmygchen** [comment]
Hi @PatStiles, since we haven't heard back from you, I'm going to pick this one up, hope you don't mind! ☺️

**Comment by PatStiles** [comment]
No problem! Life got busy happy it got over the line

**Comment by jimmygchen** [comment]
Completed in #4744
