### ISSUE TITLE
"too many subscriptions per request" Error on Deneb local testnet

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4581]
## Description

A Discord user (Stefan) reported getting this error on a deneb-devnet-7 local testnet for lighthouse. The nodes on the network had `--subscribe-all-subnets` enabled:

```
[     964] [    36.090282] [service_lighthouse-nethermind-0--lighthouse-bn] [I] [2023-08-04T10:05:46Z ERROR libp2p_gossipsub::behaviour] Subscription filter error: too many subscriptions per request; ignoring RPC from peer 16Uiu2HAmDL3NPvDTYk6d3U59HeJ66aTJNpWUhr8R5pDWj13tHTcf
```

Stefan also referenced the limit set here:

https://github.com/sigp/lighthouse/blob/4ca101e085e2a88805cc4788e6f875ff65998b6c/beacon_node/lighthouse_network/src/service/mod.rs#L242-L244

The comment above is interesting, because a node, when subscribe to all attestation subnets, could go over the limit during fork transition, i.e. 2 epochs before  & after a fork, where lighthouse is subscribed to both the current fork topics and next fork topics (total of 162 topics as calculated above). I think the `max_subscriptions_per_request` may need to be bumped over 162 to prevent this error, otherwise the peer's subscription request could be ignored.

@pawanjay176 @realbigsean could you please confirm my understanding above?

Credits to @qu0b for reporting this! 🙏

**Comment by qu0b** [comment]
Thanks for writing this up @jimmygchen and shout out to [antithesis](https://antithesis.com/). 

I received the messages when the CL nodes came up and started connecting with other peers, but also a bit before forks.

There were two types of log messages. The one that you posted above where there are too many topic subscriptions in a request and another one below where the client tries to subscribe to a new topics, but already has too many subscriptions:

```
[   35812] [   761.715855] [service_lighthouse-besu-0--lighthouse-bn]       [I] [2023-08-04T10:17:52Z ERROR libp2p_gossipsub::behaviour] Subscription filter error: too many subscribed topics; ignoring RPC from peer 16Uiu2HAmMd144JvTzK5wVYC8HywSkZ2tvxRTnHwHKqw6Wc4shGPC
```

Both limits `max_subscribed_topics` and `max_subscriptions_per_request` are being hit.

**Comment by jimmygchen** [comment]
Completed in #4588, thanks @qu0b !
