### ISSUE TITLE
Fix HTTP error handling in VC API

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4597]
## Description

The VC API is affected by the same issue as the BN: https://github.com/sigp/lighthouse/issues/3404

For the BN fix see: https://github.com/sigp/lighthouse/pull/4595

We should port similar changes to the VC API.

**Comment by protocolwhisper** [comment]
Hello @michaelsproul, I've created a PR that I believe resolves this issue. I'm looking forward to receiving your feedback💙

**Comment by chong-he** [comment]
Closed by #5529
