### ISSUE TITLE
Clippy Error in package boolean-bitfield

### ISSUE THREAD

**Issue by blacktemplar** [sigp/lighthouse#460]
## Description

I ran today clippy on the whole project and got an error in the package boolean-bitfield.

## Present Behaviour

After running `cargo clippy --package boolean-bitfield` we get:

```
    Checking boolean-bitfield v0.1.0 (/home/benedikt/private/lighthouse/eth2/utils/boolean-bitfield)
error: you are deriving `Hash` but have implemented `PartialEq` explicitly
  --> eth2/utils/boolean-bitfield/src/lib.rs:16:24
   |
16 | #[derive(Debug, Clone, Hash)]
   |                        ^^^^
   |
   = note: #[deny(clippy::derive_hash_xor_eq)] on by default
note: `PartialEq` implemented here
  --> eth2/utils/boolean-bitfield/src/lib.rs:166:1
   |
166| / impl cmp::PartialEq for BooleanBitfield {
167| |     /// Determines equality by comparing the `ssz` encoding of the two candidates.
168| |     /// This method ensures that the presence of high-order (empty) bits in the highest byte do not exclude equality when they are in fact representing the same information.
169| |     fn eq(&self, other: &Self) -> bool {
170| |         ssz::ssz_encode(self) == ssz::ssz_encode(other)
171| |     }
172| | }
   | |_^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_hash_xor_eq

error: aborting due to previous error

error: Could not compile `boolean-bitfield`.
```

## Expected Behaviour

Successfully finish with no error.

## Steps to resolve

If I understand the comment in https://github.com/sigp/lighthouse/blob/b5af73d056e896c6ed8d1033c9e9cbc562cf6ec8/eth2/utils/boolean-bitfield/src/lib.rs#L168 
correctly, than this means that two boolean bitfields may be considered equal although their underlying data structure is not equal, therefore we need to implement Hash to satisfy `k1 == k2 ⇒ hash(k1) == hash(k2)`. Or we drop Hash at all if is not needed.

**Comment by michaelsproul** [comment]
Nice find! We're actually deleting that boolean-bitfield implementation as part of the move to v0.8, so I'm going to close this issue. Lighthouse is a fast-moving target at the moment! 🚀
