### ISSUE TITLE
The wait time for fetching historical data about validator states is too lengthy

### ISSUE THREAD

**Issue by filips121** [sigp/lighthouse#4630]
## Description

When you try to fetch validator states from blocks that aren't the latest (head), the wait times can be extremely long. 
For some blocks you only get the result after making multiple attempts.

For example, the next request takes too much time to retrieve the results:
curl -X GET "http://public-mainnet-node.ethereum.org/eth/v1/beacon/states/4768640/validators" -H  "accept: application/json" | jq

**Comment by michaelsproul** [comment]
We're aware of this and have a new alpha version that overhauls the database and state representation to make it faster. You can build the `tree-states` branch (this PR: https://github.com/sigp/lighthouse/pull/3206) to try it out. There are release notes for a previous alpha [here](https://github.com/sigp/lighthouse/releases/tag/v4.2.990-exp) although I would recommend running the latest branch as we've fixed a few bugs.

The alternative running stable Lighthouse is to configure the `--slots-per-restore-point` lower. But this will use _a lot_ of disk space, 4TB+ for the fastest setting of `--slots-per-restore-point 32`. More on that here: https://lighthouse-book.sigmaprime.io/advanced_database.html

Our schedule for releasing tree-states is sometime shortly after the Deneb hard fork.
