### ISSUE TITLE
Update deneb builder bids

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#4665]
## Description

This PR was merged https://github.com/ethereum/builder-specs/pull/87

This means we can remove the `BuilderKzgCommitments` type alias and replace it everywhere with `BeaconBlobBodyCommitments` (we can probably rename this back to `KzgCommitments` since we no longer have to differentiate the two).

This change is breaking in the builder API since it changes the hash tree root these bids are signed over so there will need to be some degree of coordination on devnets, I don't think that has been discussed across teams yet. My guess is this would be devnet 9

**Comment by realbigsean** [comment]
Gonna mark this as blocked on discussion about when relays should implement this

**Comment by jimmygchen** [comment]
This has been implemented by a few clients (Teku & Lodestar) so I think should be good to go. I've updated it in #4710.

**Comment by jimmygchen** [comment]
Completed in #4710
