### ISSUE TITLE
mev-boost timeout

### ISSUE THREAD

**Issue by xanatos** [sigp/lighthouse#4709]
I use mev-boost 1.6 and lighthouse v4.3.0-dfcb336 on Windows 11

These weeks I had two blocks that timed out in the call to mev-boost. It seems that lighthouse has a hard timeout of 1sec, and twice mev-boost was a little slower (1.1-1.2sec).

Is it possible to increase this timeout?

(I'll add that the block was still generated internally by lighthouse, without the MEV)

The log files of lighthouse and mev-boost:

Lighthouse: Sep 06 xx:34:11.300 INFO Requesting blinded header from connected builder
Lighthouse: Sep 06 xx:34:12.313 INFO Requested blinded execution payloadlocal_response_ms: 10, ..., relay_response_ms: 1013, relay_fee_recipient: request failed, service: exec
Lighthouse: Sep 06 xx:34:12.313 WARN Builder error when requesting payload   relay_error: HttpClient(url: http://localhost:18550/, kind: timeout, detail: operation timed out), info: falling back to local execution client, service: exec
Lighthouse: Sep 06 xx:34:12.557 INFO Reconstructing a full block using a local payload, block_hash: ...

MevBoost: time="2023-09-06Txx:34:11.608+02:00" level=info msg="getHeader request start - 608 milliseconds into slot ..." genesisTime=.... slotTimeSec=12 ua=Lighthouse/v4.3.0-dfcb336 version=v1.6
MevBoost: time="2023-09-06Txx:34:12.446+02:00" level=info msg="best bid" blockHash=... blockNumber=.... method=getHeader ... relays="[https://aestus.live/](https://0xa15b52576bcbf1072f4a011c0f99f9fb6c66f3e1ff321f11f461d15e31b1cb359caa092c71bbded0bae5b5ea401aab7e@aestus.live/)" slot=7265869 ua=Lighthouse/v4.3.0-dfcb336 value=... version=v1.6
MevBoost: time="2023-09-06Txx:34:12.446+02:00" level=info msg="http: GET /eth/v1/builder/header/.../..../... 200" duration=0.838280 method=GET path=/eth/v1/builder/header/.../.../... status=200 version=v1.6

I'll add that I've looked for the duration=... in the mev-boost log, and the last blocks that it relayed had:

duration=0.540568
duration=0.363306
duration=0.504703
duration=0.573797
duration=0.367252
duration=0.499827
duration=0.754806 <- Timeout on lighthouse
duration=0.355462
duration=0.838280 <- Timeout on lighthouse

**Comment by xanatos** [comment]
Annotation: it seems that Nimbus uses 1500ms: https://github.com/status-im/nimbus-eth2/issues/5090
In lighthouse the timeout is set here: https://github.com/sigp/lighthouse/blob/2841f60686d642fcc0785c884d43e34e47a800dc/beacon_node/builder_client/src/lib.rs#L17-L18

**Comment by michaelsproul** [comment]
we'll add a new CLI flag: `--builder-header-timeout-ms`

**Comment by eserilev** [comment]
Completed in #5857
