### ISSUE TITLE
Validator client shouldn't request aggregate with no aggregators

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4712]
## Description

The validator client's logic for forming aggregate attestations will currently request an aggregate from the BN _before_ checking whether there are any aggregators that need to sign it:

https://github.com/sigp/lighthouse/blob/2841f60686d642fcc0785c884d43e34e47a800dc/validator_client/src/attestation_service.rs#L494-L518

This is inefficient, but also liable to cause issues with other clients, which may not be expecting to produce an aggregate when they are not subscribed to the attestation subnet. Thanks to @nflaig from Lodestar for finding and reporting this bug.

## Steps to resolve

Check whether there are any aggregators (at least one selection proof that is `Some`) before requesting an aggregate from the BN.

**Comment by michaelsproul** [comment]
This also affects Lighthouse VC with a Prysm BN.

For easy searchability, the error produced is:

> CRIT Error during attestation routine

**Comment by jimmygchen** [comment]
Completed in #4774.
