### ISSUE TITLE
Genesis state download sometimes panics

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4738]
## Description

We've identified a bug in the downloading of genesis states that is used on Holesky and Chiado (introduced in #4653).

The problem is that we use the `reqwest::blocking::Client` to download the state, [which can panic if called from an async context](https://github.com/seanmonstar/reqwest/blob/a4e8ab694c639f889a110831041fdc93d924e504/src/blocking/client.rs#L845-L859):

https://github.com/sigp/lighthouse/blob/2841f60686d642fcc0785c884d43e34e47a800dc/common/eth2_network_config/src/lib.rs#L17

https://github.com/sigp/lighthouse/blob/2841f60686d642fcc0785c884d43e34e47a800dc/common/eth2_network_config/src/lib.rs#L378-L386

We call it from an async context via `genesis_state` here:

https://github.com/sigp/lighthouse/blob/2841f60686d642fcc0785c884d43e34e47a800dc/beacon_node/client/src/builder.rs#L259

and here:

https://github.com/sigp/lighthouse/blob/2841f60686d642fcc0785c884d43e34e47a800dc/beacon_node/client/src/builder.rs#L279

and here:

https://github.com/sigp/lighthouse/blob/2841f60686d642fcc0785c884d43e34e47a800dc/beacon_node/client/src/builder.rs#L380

i.e. in all the cases where we are starting the client for the first time: genesis sync, and checkpoint sync from state on-disk or a URL

## Version

Lighthouse v4.4.1

## Impact

- Has so far only been observed in debug mode (not `--release`).
- Only occurs on first start-up. Once the state is downloaded it is subsequently read from the DB.
- Can be worked around.

## Workaround

Instead of `--network holesky`, use `--testnet-dir` pointed to the [custom_config_data](https://github.com/eth-clients/holesky/tree/main/custom_config_data) for Holesky.

## Steps to resolve

- Option 1: wrap the calls in `spawn_blocking` or similar.
- Option 2: use the async reqwest client in `Eth2NetworkConfig` and propagate the async-ness (this might be painful).

**Comment by michaelsproul** [comment]
For reference the panic includes this message:

> panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.'

Thanks @jmcph4 for reporting, and assisting debug alongside @jimmygchen

**Comment by jimmygchen** [comment]
I'd like to work on this one - be good to have this fixed before holesky relaunch.

**Comment by jimmygchen** [comment]
Fixed in #4753
