### ISSUE TITLE
VC won't start without latest LH beacon connected to it

### ISSUE THREAD

**Issue by stefa2k** [sigp/lighthouse#4740]
## Description

Updated vc to `4.4.1` and it wouldn't properly do the liveness check and therefore stuck in doppelgänger.

```
ERRO Liveness query omitted validators       requested: 500, current_epoch_response: 0, previous_epoch_response: 0, service: doppelganger
CRIT Failed current epoch liveness query     current_epoch: 229461, error: Some endpoints failed, num_failed: 10 http://a.a.a.a:5052/ => Unavailable(Offline), http://b.b.b.b:5051/ => Unavailable(Offline), http://c.c.c.c:5052/ => Unavailable(Offline), http://d.d.d.d:9596/ => Unavailable(Offline), http://e.e.e.e:3500/ => Unavailable(Offline), http://a.a.a.a:5052/ => RequestFailed("Failed query for validator liveness: StatusCode(404)"), http://b.b.b.b:5051/ => RequestFailed("Failed query for validator liveness: StatusCode(404)"), http://d.d.d.d:5052/ => Unavailable(Offline), http://e.e.e.e:9596/ => Unavailable(Offline), http://f.f.f.f:3500/ => RequestFailed("Failed query for validator liveness: StatusCode(404)"), service: doppelganger
```

Node a (Nimbus, latest version), node b (Teku, latest version), node f (Prysm, latest verion) are online and in sync. Teku beacon got liveness check enabled.

## Version

`4.4.1`

## Present Behaviour

Vc stuck with doppelgänger

## Expected Behaviour

Vc should be able to use nimbus/teku/prysm for doppelgänger check

## Steps to resolve

Add lighthouse beacon

**Comment by michaelsproul** [comment]
I don't think this worked before. We didn't change anything in the Lighthouse VC doppelganger detection for v4.4.1, so it's still using the custom `/lighthouse/liveness` endpoint, same as previous versions. This should never have worked with Prysm/Nimbus/Teku or any other client apart from Lighthouse.

Support for using the standard liveness endpoint from the VC is being tracked here https://github.com/sigp/lighthouse/pull/4539, which we'll try to include in the next release. It's a recent addition to the API, and we just haven't switched the VC over to using it yet (and when we do it will break compatibility with old versions of Lighthouse that don't have the endpoint implemented).

Let me know if I've missed something
