### ISSUE TITLE
Fix state queries for slot 0 and `finalized` prior to genesis

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4751]
## Description

Currently prior to genesis queries for the genesis state will only succeed if made using the `genesis` tag. This causes nodes configured with a checkpoint sync URL to fail, which is a bit annoying.

The error is:

```
> curl "http://localhost:5052/eth/v2/debug/beacon/states/justified"
{"code":500,"message":"UNHANDLED_ERROR: UnableToReadSlot","stacktraces":[]}
```

Should be simple enough to fix.

**Comment by jimmygchen** [comment]
Completed in #4761 🎉
