### ISSUE TITLE
Prevent Overflow LRU Cache from blowing up due to large state sizes

### ISSUE THREAD

**Issue by ethDreamer** [sigp/lighthouse#4757]
## Description

The [OverflowLRUCache](https://github.com/sigp/lighthouse/blob/665334e9368f8c7399a495f85b7409c78ccbc160/beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs#L380) was created to prevent lighthouse from using up too much memory in the event that the chain stops finalizing and blocks remain perpetually unavailable. Unfortunately I had failed to realize during its design that part of the [PendingComponents](https://github.com/sigp/lighthouse/blob/665334e9368f8c7399a495f85b7409c78ccbc160/beacon_node/beacon_chain/src/data_availability_checker/overflow_lru_cache.rs#L54) which are stored in memory [include a `BeaconState`](https://github.com/sigp/lighthouse/blob/665334e9368f8c7399a495f85b7409c78ccbc160/beacon_node/beacon_chain/src/block_verification_types.rs#L264) which are significantly larger than any of the `BlobSidecar` objects.

This will remain true until tree-states is merged but in the meantime the cache needs an update to prevent the states from consuming all the memory if blocks are perpetually unavailable.

### Goals

1. Don't consume excess memory
2. Don't consume excess disk
3. Minimize impact on attestation performance during average network conditions
4. Perform acceptably during adverse network conditions
5. Design fix so that it can be ripped out easily once tree-states is merged

### Design

After some initial investigation the following design emerged:

1. Hold at most 2-4 `BeaconStates` in memory for the `LRUCache` (there are various ways to do this)
2. If more than this threshold of states are floating around, write the LRU state to disk using hot state summaries
3. Recover the states when needed by replaying blocks (this code will need to be modified as it assumes necessary blocks are imported)

**Comment by realbigsean** [comment]
resolved in https://github.com/sigp/lighthouse/pull/4801
