### ISSUE TITLE
Holeksy relaunch updates

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4759]
## Description

- [x] Update S2 genesis state
- [x] Update holeky config, genesis state hashes #4760 
- [x] Update ENRs
- [x] Update SigP ENR in Lighthouse #4763 
- [x] Update SigP ENRs in https://github.com/eth-clients/holesky [PR](https://github.com/eth-clients/holesky/pull/78)

**Comment by paulhauner** [comment]
Resolved by #4760 and #4763
