### ISSUE TITLE
Remove interval timers from Deneb?

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4787]
## Description

For the reasons outlined in #3518 I wonder if we should remove `interval_at` usage from Deneb. A prominent example is `spawn_delayed_lookup_service` which runs at an offset of `single_lookup_delay` in each slot. It is currently using an interval timer, which makes it liable to get out of phase if the hardware clock drifts.

**Comment by realbigsean** [comment]
makes a lot of sense! hadn't seen the linked issue

**Comment by realbigsean** [comment]
no longer necessary due to https://github.com/sigp/lighthouse/pull/4992
