### ISSUE TITLE
Use `validator/blocks` v3 endpoint in the VC

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4812]
## Description

The `validator/blocks` v3 implementation is currently being worked on in #4629. Once that's ready we should switch the VC to use the v3 endpoint.

A few other clients are also in the process of implementing the endpoint, so we'd need to come up with a sensible upgrade strategy. 
- we probably want to ship this together with #4629 and encourage user to update both Lighthouse BN and VC
- if user uses a different CL client that does not support V3 yet, do we introduce a flag to allow user to override the behaviour?
  - @michaelsproul suggested that we could use it by default once Deneb is enabled (all clients would have it ready by then), or have a flag to enable it prior to Deneb, so like:

```rust
if deneb_already_happened || config.use_v3 {
   beacon_node.get_v3(..)
} else {
   beacon_node.get_v2(..)
}
```

Beacon API spec:
- https://github.com/ethereum/beacon-APIs/pull/339

**Comment by eserilev** [comment]
i'd like to pick this one up

**Comment by jimmygchen** [comment]
Completed in #4813 🎉
