### ISSUE TITLE
update the ETH1_BLOCK_HASH value in vars.env according to the genesis.json in the Start the local testnet

### ISSUE THREAD

**Issue by zyDevoted** [sigp/lighthouse#4814]
## Description

How to update the ETH1_BLOCK_HASH value in vars.env according to the genesis.json in the Start the local testnet?

## Version

Lighthouse v4.4.1-2841f60 cargo 1.72.1 (103a7ff2e 2023-08-15)

## Present Behaviour

when I modify the genesis.json and then start the local testnet, the chain is not working beacuse of the wrong ETH1_BLOCK_HASH, so I want to modify this hash value, but i do not know how.

**Comment by chong-he** [comment]
After you modified `genesis.json`, you can obtained the updated `ETH1_BLOCK_HASH` with `geth init genesis.json`, which will generate a new genesis state that you can enquire with `
eth.getBlock('latest')`. From there you get the hash, and update it in `vars.env`.

Hope this helps

**Comment by chong-he** [comment]
Closing this issue as the question has been answered
