### ISSUE TITLE
Validate Versioned Hashes During Optimistic Sync

### ISSUE THREAD

**Issue by ethDreamer** [sigp/lighthouse#4831]
## Description

The consensus specs [instruct us to verify](https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/beacon-chain.md#modified-verify_and_notify_new_payload) the execution payload `block_hash` and `versioned_hashes` before sending `engine_newPayload` to the EE. This is because the EE could be syncing, putting us into optimistic sync mode. These checks only need to be performed during optimistic sync.

We already verify the `block_hash` and now we just need the `versioned_hashes` for `deneb`.

**Comment by jimmygchen** [comment]
Completed in #4832
