### ISSUE TITLE
Enable Deneb in doppelganger tests

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4847]
## Description

I don't want to block the Deneb merge on this, so I'm opening an issue. We should (correctly) enable Deneb+Cancun in the doppelganger tests. See https://github.com/sigp/lighthouse/pull/4054#discussion_r1360084323 for detail.

**Comment by realbigsean** [comment]
added in https://github.com/sigp/lighthouse/pull/5137
