### ISSUE TITLE
Validator manager commands for standard key-manager APIs

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4854]
## Description

The Lighthouse validator manager `import` command takes a [`Vec<ValidatorSpecification>`](https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/validator_manager/src/common.rs#L42) as input, which makes it unsuitable for use with keystores from non-Lighthouse sources.

It would be great to have a command that can import standard keystore files, with options for passwords, etc. Basically an analogue of the old _account-manager_ import command that works with the keymanager API.

For completeness it would also be good to have basic commands for the other key-manager APIs like list, delete, etc, which don't use any Lighthouse-specific extensions. This would allow interop with non-Lighthouse VCs, and provide a nicer front-end to the KM APIs that doesn't involve crafting JSON by hand.

## Version

Lighthouse v4.5.0

## Steps to resolve

Add new commands to `lighthouse validator-manager` which _just_ use the standard APIs.

**Comment by pahor167** [comment]
I created following https://github.com/sigp/lighthouse/pull/5347 - this is my first PR, please let me know if anything is missing

**Comment by jimmygchen** [comment]
@chong-he I think we can now close this one?

**Comment by chong-he** [comment]
Closed in #6261
