### ISSUE TITLE
`eth/v1/node/peer_count` can take upwards of 18s

### ISSUE THREAD

**Issue by yorickdowne** [sigp/lighthouse#4857]
## Description

After running successfully for days/weeks, our archive Lighthouse may take upwards of 18s to return results of `eth/v1/node/peer_count`. This messes with our haproxy liveness check a bit, which runs every 10s.

Restarting Lighthouse will resolve this for a very short while.

Resyncing Lighthouse will resolve this for days/weeks, and then it occurs again.

## Version

`v4.5.222-exp-f1f76f2` - this is used for oDAO queries and otherwise is not fast enough

**Comment by chong-he** [comment]
Is this still an issue now? 

I have tested with `Lighthouse/v5.1.222-exp-2cd0e60/x86_64-linux` and the query is fast, takes <50ms

**Comment by yorickdowne** [comment]
I am unsure. We’ve switched Lighthouse out for Nimbus on that machine. I’ll take your word it’s fixed, good work!

**Comment by michaelsproul** [comment]
We didn't change anything on tree-states, so it's probably not "fixed".

**Comment by michaelsproul** [comment]
The problem is probably quite fundamental: when Lighthouse has a lot of work to do it queues HTTP requests by type and will take a long time to respond to priority 1 requests. We may tweak how this works in future, but there's nothing obviously actionable, so I'm happy to leave this issue closed.
