### ISSUE TITLE
Disable validator slashing protection

### ISSUE THREAD

**Issue by jmcruz1983** [sigp/lighthouse#4890]
## Description

When using centralised signing with web3signer,
we can have a centralise slashing protection, 
so for that we would like to have a parameter to 
disable the local slashing protection in the lighthouse validator

Thanks

**Comment by michaelsproul** [comment]
This may also be alleviated by https://github.com/sigp/lighthouse/issues/1914, which I'm hoping to solve... any day now

**Comment by michaelsproul** [comment]
Implemented in https://github.com/sigp/lighthouse/pull/4981 but will need very thorough testing and review before we merge (i.e. won't make it for 4.6)

**Comment by ricardolyn** [comment]
@michaelsproul, thank you for the update. We've started testing and encountered an inconsistency: despite setting `--disable-slashing-protection-web3signer`, it appears that `--init-slashing-protection` is still required in the absence of a slashing protection database, even though we're using web3signer and it won't be utilized.

Could `--init-slashing-protection` be made optional when `--disable-slashing-protection-web3signer` is enabled? Thanks.

**Comment by michaelsproul** [comment]
@ricardolyn Good point! We can probably make that work. Do you mind opening a new issue?

Thanks

**Comment by ricardolyn** [comment]
thank you, created https://github.com/sigp/lighthouse/issues/5310
