### ISSUE TITLE
Add beacon API support for light client bootstrap

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4894]
## Description

Add support for the `/eth/v1/beacon/light_client/bootstrap/{block_root}` API endpoint.

Beacon API spec: https://ethereum.github.io/beacon-APIs/#/Beacon/getLightClientBootstrap

## Additional Notes

The `GetLightClientBootstrap` p2p support was added in #3711 (Altair only). Capella / Deneb support can be implemented separately.

**Comment by eserilev** [comment]
I'd like to pick this one up

**Comment by jimmygchen** [comment]
Hey @eserilev, I'm sorry I didn't realize @GeemoCandama's already covered this endpoint as part of #3954 (you're too quick! 🔥 ). Although this was a while ago and pre-Altair,  so let's keep your PR open for now while we review the other PR.

**Comment by eserilev** [comment]
All good! Maybe I can help with some of the capella/deneb lightclient spec changes when the time comes. Will keep my PR open for now, thanks!

**Comment by jimmygchen** [comment]
Completed in #3954
