### ISSUE TITLE
Add beacon API support for light client updates by range

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4895]
## Description

Add support for the `/eth/v1/beacon/light_client/updates` API endpoint.

Beacon API spec: https://ethereum.github.io/beacon-APIs/#/Beacon/getLightClientUpdatesByRange

## Additional Notes

There is an open issue for `LightClientUpdatesByRange` p2p support #3886  (Altair only). Probably make sense to merge that one first before starting this one.

**Comment by eserilev** [comment]
I believe https://github.com/sigp/lighthouse/pull/5545 included adding support for this api endpoint

see diff here:
 https://github.com/sigp/lighthouse/pull/5545/files#diff-0aec0f89455da3fc1b452417ec63873cd95bd4ee3319e386233535544f47ab30R2489-R2502
 
 so I think we should be good to close this one

**Comment by jimmygchen** [comment]
Nice!  🚀 
Closing, thanks
