### ISSUE TITLE
`/eth/v1/beacon/blob_sidecars/` return 404 errors instead of empty list for blocks without blob data

### ISSUE THREAD

**Issue by wangwzhou** [sigp/lighthouse#4901]
## Description

Beacon API endpoint `/eth/v1/beacon/blob_sidecars/` returns 404 `Not Found` errors for blocks without blob data in holesky/mainnet networks. Should it return empty list instead?

## Version

```
"data": {
    "version": "Lighthouse/v4.5.0-441fc16/x86_64-linux"
  }
```

## Present Behaviour

```
curl -X 'GET' https://{beacon_url}/eth/v1/beacon/blob_sidecars/head  -H 'accept: application/json'

{
  "code": 404,
  "message": "NOT_FOUND",
  "stacktraces": []
}

```

## Expected Behaviour

Should it return an empty list for blocks without blob data?

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
Lighthouse v4.5.0 does not have that API, which is why you're getting a 404.

Blocks prior to Deneb _will_ result in an empty list on that endpoint (if you run Lighthouse `unstable` or v4.6.0 once it comes out).

Will close this issue once I've double-checked that with a test

**Comment by michaelsproul** [comment]
On the `tree-states` branch (which includes Deneb changes) on mainnet:

```
> curl -H "Accept: application/json" "http://localhost:5052/eth/v1/beacon/blob_sidecars/head"
{"data":[]}
> curl -H "Accept: application/json" "http://localhost:5052/eth/v1/node/version"
{"data":{"version":"Lighthouse/v4.5.444-exp-1aca484/x86_64-linux"}}
```

**Comment by wangwzhou** [comment]
@michaelsproul Thanks for taking a look. Just curious, any ETA of v4.6.0?

**Comment by michaelsproul** [comment]
> any ETA of v4.6.0?

Probably after Devconnect at this stage. Early December

**Comment by wangwzhou** [comment]
> Probably after Devconnect at this stage. Early December

I assume that the upgrade for public testnets will be planned after this newer version v4.6.0?

**Comment by michaelsproul** [comment]
> I assume that the upgrade for public testnets will be planned after this newer version v4.6.0?

Yeah. The spec is undergoing a major change at the moment, so it will be at least a few months before we deploy Deneb on a public testnet.

**Comment by wangwzhou** [comment]
@michaelsproul wondering is there any update for this v4.6.0 release ETA? thanks

**Comment by michaelsproul** [comment]
@wangwzhou We're planning a release candidate for 4.6 next week, which will be used for Goerli. Then a proper 4.6 that will probably be used for Deneb on Sepolia/Holesky. There are some extensive changes that still require more testing, which is why we didn't release in December.

**Comment by wangwzhou** [comment]
@michaelsproul Just want to confirm that after release 4.6, the responses of `blob_sidecars` API will either be an empty list (without blobs) or a list of blobs data, right? And customers won't receive `NOT_FOUND` error code even for post-Deneb blocks?

**Comment by michaelsproul** [comment]
@wangwzhou No, unfortunately the same problems as in your other issue apply: https://github.com/sigp/lighthouse/issues/4904.

As a workaround, if you know the block exists and is stored in the Lighthouse DB, the `blob_sidecars` endpoint should always return 200 (including for pre-Deneb blocks)

**Comment by wangwzhou** [comment]
@michaelsproul Are you referring to that for all non-skipped blocks, the response of `blob_sidecars` should always be 200 eventually? while for skipped blocks, the `blob_sidecars` will return `404 not found` error?

**Comment by michaelsproul** [comment]
> Are you referring to that for all non-skipped blocks, the response of blob_sidecars should always be 200 eventually? while for skipped blocks, the blob_sidecars will return 404 not found error?

Yeah, that's right
