### ISSUE TITLE
Add more block v3 endpoint tests

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#4905]
## Description

@eserilev added a couple tests here, laying the groundwork for more tests: https://github.com/sigp/lighthouse/pull/4902

We should include all the blinded and non-blinded scenarios. They should be very similar to their v2 counterparts but we'll be able to more clearly determine whether a block came from the builder or local in the fallback tests (🚀). Instead of checking the local cache, the returned type will tell us where it came from.

**Comment by eserilev** [comment]
sounds great, I'd like to pick this up

**Comment by realbigsean** [comment]
of course! Thanks @eserilev !

**Comment by realbigsean** [comment]
closed in https://github.com/sigp/lighthouse/pull/4939
