### ISSUE TITLE
Key manager API: implement standard Graffiti management APIs

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#4947]
## Description

New `GET`, `POST`, `DELETE` graffiti endpoints are being added to Key Manager API spec and needs to be implemented: 
https://github.com/ethereum/keymanager-APIs/pull/63

Lighthouse already implement some custom APIs to manage graffitis:
- `GET /lighthouse/ui/graffiti`
- `PATCH /lighthouse/validators/:voting_pubkey`

These existing endpoints should remain unchanged as they are used by the Siren UI and are slightly different to the standard APIs. For the new `POST` endpoint, we should implement a similar logic when updating the validator graffiti to [the existing `PATCH` endpoint](https://github.com/sigp/lighthouse/pull/4417):
> This endpoint updates the graffiti in both the [validator definition file](https://lighthouse-book.sigmaprime.io/graffiti.html#2-setting-the-graffiti-in-the-validator_definitionsyml) and the in memory InitializedValidators. In the next block proposal, the new graffiti will be used.
> 
> Note that the [--graffiti-file](https://lighthouse-book.sigmaprime.io/graffiti.html#1-using-the---graffiti-file-flag-on-the-validator-client) flag has a priority over the validator definitions file, so if the caller attempts to update the graffiti while the --graffiti-file flag is present, the endpoint will return an error (Bad request 400).

^ and perhaps return `403` instead of `400` to be more spec compliant.

**Comment by eserilev** [comment]
I'd like to pick this up

**Comment by jimmygchen** [comment]
That's great, thanks @eserilev !

**Comment by jimmygchen** [comment]
Completed in #4951 , thanks @eserilev !
