### ISSUE TITLE
ask: Can multiple builder urls be configured?

### ISSUE THREAD

**Issue by rayn316** [sigp/lighthouse#4963]
## Description
Can the `--builder` parameter be configured with multiple URLs, such as the following configuration? Is this valid? I don’t seem to see any errors.
`--builder https://boost-relay-holesky.flashbots.net,https://docs.titanrelay.xyz/,https://relay-holesky.edennetwork.io/info`

```
serviceName=holesky-lighthouse-vc
serviceCmd="/node/full/holesky/bin/lighthouse vc --builder-proposals -d /node/full/holesky/lighthouse --network holesky --beacon-nodes http://127.0.0.1:39037"

serviceName=holesky-lighthouse
serviceCmd="/node/full/holesky/bin/lighthouse bn -d /node/full/holesky/lighthouse --network holesky --execution-endpoint 'http://127.0.0.1:39033' --execution-jwt '/node/full/holesky/geth/geth/jwtsecret' --checkpoint-sync-url=https://holesky.beaconstate.info --port 39039 --http --http-port 39037 --builder https://boost-relay-holesky.flashbots.net,https://docs.titanrelay.xyz/,https://relay-holesky.edennetwork.io/info"
```

**Comment by michaelsproul** [comment]
No, that won't work, you should use `mev-boost` if you want to connect to multiple builders.

**Comment by michaelsproul** [comment]
The warning logged tells you it won't work:

> Nov 30 09:33:42.119 WARN Multiple values provided                flag: --builder, count: 3, info: multiple values are deprecated, only the first value will be used
