### ISSUE TITLE
Remove yanked deps before 4.6

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4989]
## Description

There are some yanked deps:

> warning: package `ahash v0.7.6` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
warning: package `ahash v0.8.3` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked

I don't think it's a matter of just `cargo update` to fix them. They seem to be part of the dep tree via some old versions of `hashbrown` which I don't think has patch versions to fix this (see #4935 which I think did a `cargo update`). Some investigation will be required to work out how to get rid of them (i.e. updating the hashbrown minor version through whatever crates depend on `hashbrown`).

**Comment by jimmygchen** [comment]
I'll take a look at this one

**Comment by michaelsproul** [comment]
Fixed in #4994
