### ISSUE TITLE
Implement fork choice filter change for Deneb

### ISSUE THREAD

**Issue by mkalinin** [sigp/lighthouse#4990]
Implement the following fork choice change and bundle it with the Deneb upgrade:
* https://github.com/ethereum/consensus-specs/pull/3431

More details on the way to release this change are [here](https://github.com/ethereum/consensus-specs/issues/3466), TL; DR:
* Bundle the change with the Deneb upgrade
* Merge the spec PR when `DENEB_FORK_EPOCH` is set for the mainnet

Tests: https://github.com/ethereum/consensus-specs/pull/3431#issuecomment-1727615639

**Comment by jimmygchen** [comment]
Thanks for raising the issue! Existing tracking issue here #4566

**Comment by michaelsproul** [comment]
My bad, I asked Mikhail to open this!

**Comment by jimmygchen** [comment]
ah cool, I haven't progress on that issue because I was waiting for the PR to be merged, but now I just read that the PR is only blocked by the deneb fork epoch. Will start working on this soon.
