### ISSUE TITLE
Feature: Implement keymanager graffiti API endpoint

### ISSUE THREAD

**Issue by yorickdowne** [sigp/lighthouse#4991]
## Description

Users cannot set a per-validator graffiti without manually changing json files

Implement keymanager graffiti endpoints so user can use `ethd keys get|set|delete-graffiti`

Very similar to the `gas-limit` endpoint. See https://ethereum.github.io/keymanager-APIs/?urls.primaryName=dev#/Graffiti

**Comment by michaelsproul** [comment]
We merged just yesterday! https://github.com/sigp/lighthouse/pull/4951

That feature will be in v4.6.0 (coming soon 🔜)
