### ISSUE TITLE
QUIC zero port error

### ISSUE THREAD

**Issue by macladson** [sigp/lighthouse#5004]
## Description
Running Lighthouse with `--port 0` causes a permissions error and then fails to startup. Manually assigning the quic port or using `--disable-quic` resolves the error.

This occurs since [by default, the quic port is set as as `port + 1`.](https://github.com/sigp/lighthouse/blob/unstable/beacon_node/src/config.rs#L971). When using `--port 0`, we are telling the operating system to choose a free port, however by doing so, the quic port is then set to `0 + 1`.

Only the `root` user is able to bind to ports which are <1024 and thus we get a permissions error.

## Steps to resolve

One solution would be to add a larger offset such that the port gets bound to above `1024`.

Another solution would be to assign the quic port to 0 if the `port` is also 0. `if port == 0 { quic_port = 0 }`

**Comment by ackintosh** [comment]
I'm working on this. 🙂

**Comment by ackintosh** [comment]
The fix has been released in v4.6.0 🎉
