### ISSUE TITLE
error trying to connect: tcp connect error: Connection refused

### ISSUE THREAD

**Issue by Parikalp-Bhardwaj** [sigp/lighthouse#5022]
![image](https://github.com/sigp/lighthouse/assets/53660958/0d8ff95a-c9c8-42a7-91e7-650c34fa1078)

## Description

for execution client i am using Reth

reth node --chain ./genesis.json --datadir ./node1 -vvvvv -d --http.addr 0.0.0.0 --ws.addr 0.0.0.0 --authrpc.addr 0.0.0.0 --discovery.port 30303 --port 30303 --http --http.port 8545 --authrpc.jwtsecret ./consensus/secrets/jwt.hex --ws.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots --http.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots --ws.port 8546

The beacon node was started with:

lighthouse bn --datadir ./lighthouse-datadir/ --http --execution-endpoint http://192.168.253.108:8551 --execution-jwt ./consensus/secrets/jwt.hex --metrics --http-address=0.0.0.0 --metrics-address=0.0.0.0 --enr-udp-port=9000 --enr-tcp-port=9000 --discovery-port=9000 --purge-db --http-port=4001 --metrics-port=8080 --testnet-dir=./consensus --disable-deposit-contract-sync --enable-private-discovery --subscribe-all-subnets --debug-level=trace --target-peers=0 --max-skip-slots=1  --http-allow-origin=* --eth1 --import-all-attestations

The validator was started with:

lighthouse --datadir=./lighthouse-datadir/ vc --secrets-dir=./consensus/secretes --init-slashing-protection --http --http-port=4002 --metrics --metrics-address=0.0.0.0 --metrics-port=5064 

## Version
lighthouse version v4.5.0-441fc16

**Comment by chong-he** [comment]
This is because you have set `--http-port=4001` in your beacon node. 

By default, the `vc` connects to the `bn` via `http://localhost:5052` (port 5052). So in your case, you need to specify in the vc, `--beacon-nodes http://localhost:4001` to connect to the `bn`

**Comment by Parikalp-Bhardwaj** [comment]
@chong-he 
now i am not using --http-port=4001
The error message "NOT_FOUND: Beacon chain genesis has not yet been observed" indicates that the beacon chain genesis has not been found. 

![image](https://github.com/sigp/lighthouse/assets/53660958/f405e6cf-5cfb-4407-b3ec-0326b8286315)

**Comment by chong-he** [comment]
> @chong-he now i am not using --http-port=4001 The error message "NOT_FOUND: Beacon chain genesis has not yet been observed" indicates that the beacon chain genesis has not been found.
> 
> ![image](https://private-user-images.githubusercontent.com/53660958/292383971-f405e6cf-5cfb-4407-b3ec-0326b8286315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzI3MzMsIm5iZiI6MTcwMzIzMjQzMywicGF0aCI6Ii81MzY2MDk1OC8yOTIzODM5NzEtZjQwNWU2Y2YtNWNmYi00NDA3LWIzZWMtMDMyNmI4Mjg2MzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA4MDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOGEwNjNjYjU4MWVmMGQzNDFjZTUxZjFhZmRkMWI5N2FmZjBlZDdjNDEwMDMwNjlkMTFhMThiZGE3NTM4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EQAfVtDHVqykVFeMbzQPp5JKzvYPR1CeA6vC1VJXH0Y)

Is this on a local testnet? What does the beacon node log? 

How do you start the testnet? Which parameters you change?

**Comment by Parikalp-Bhardwaj** [comment]
@chong-he I am using for private chain and using ./genesis.json on execution layer

these are my beacon node logs 
![image](https://github.com/sigp/lighthouse/assets/53660958/8618f946-f622-4fb7-bfd4-c745233e938b)

Beacon node started with 
./lighthouse bn --datadir ./lighthouse-datadir/ --http --execution-endpoint http://192.168.253.108:8551 --execution-jwt ./consensus/secrets/jwt.hex --metrics --http-address=0.0.0.0 --metrics-address=0.0.0.0 --enr-udp-port=9000 --enr-tcp-port=9000 --discovery-port=9000 --purge-db --metrics-port=8080 --testnet-dir=./consensus --disable-deposit-contract-sync --enable-private-discovery --subscribe-all-subnets --debug-level=trace --target-peers=0 --max-skip-slots=1  --http-allow-origin=* --eth1 --import-all-attestations

and validator started with
./lighthouse --datadir=./lighthouse-datadir/ vc --secrets-dir=./consensus/secretes --init-slashing-protection --http --http-port=4002 --metrics --metrics-address=0.0.0.0 --metrics-port=5064 --graffiti="House Stark Dev"


##Note
I have previous experience with Prism, where we had to generate genesis.ssz with the help of genesis.json and config.yaml.

**Comment by chong-he** [comment]
> @chong-he I am using for private chain and using ./genesis.json on execution layer
> 
> these are my beacon node logs ![image](https://private-user-images.githubusercontent.com/53660958/292468704-8618f946-f622-4fb7-bfd4-c745233e938b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDQzNzQsIm5iZiI6MTcwMzI0NDA3NCwicGF0aCI6Ii81MzY2MDk1OC8yOTI0Njg3MDQtODYxOGY5NDYtZjYyMi00ZmI3LWJmZDQtYzc0NTIzM2U5MzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDExMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZjUxMzA3ZDdhMDliNjM3ZGJjMGMxODJjNzUwYzQwYTI1NmM1YWIyMmU1ODEwNzM3YzQ3OTJhZjE1M2VlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qwosvonnbQDsLG0pP9wosEN_k45SEbjjE3PoyWFRiss)
> 
> Beacon node started with ./lighthouse bn --datadir ./lighthouse-datadir/ --http --execution-endpoint http://192.168.253.108:8551 --execution-jwt ./consensus/secrets/jwt.hex --metrics --http-address=0.0.0.0 --metrics-address=0.0.0.0 --enr-udp-port=9000 --enr-tcp-port=9000 --discovery-port=9000 --purge-db --metrics-port=8080 --testnet-dir=./consensus --disable-deposit-contract-sync --enable-private-discovery --subscribe-all-subnets --debug-level=trace --target-peers=0 --max-skip-slots=1 --http-allow-origin=* --eth1 --import-all-attestations
> 
> and validator started with ./lighthouse --datadir=./lighthouse-datadir/ vc --secrets-dir=./consensus/secretes --init-slashing-protection --http --http-port=4002 --metrics --metrics-address=0.0.0.0 --metrics-port=5064 --graffiti="House Stark Dev"
> 
> ##Note I have previous experience with Prism, where we had to generate genesis.ssz with the help of genesis.json and config.yaml.

The network doesn't progress due to no validators present (as shown on the validator client). The beacon node also confirms this as it is waiting for deposits. Do you have validators enabled/imported prior to starting the testnet?

**Comment by Parikalp-Bhardwaj** [comment]
@chong-he  i have created validator keys folder with the help of staking deposit cli, and imported validator keys to lighthouse
lighthouse account validator import --directory ./validator_keys

**Comment by Parikalp-Bhardwaj** [comment]
hello @chong-he happy new year, hope you are doing well, I wanted to follow up on my previous message regarding the creation of the validator keys folder and the import process into Lighthouse. I would appreciate it if you could take a moment to check and share any insights or guidance.



for execution using these flags
reth node --chain ./genesis.json --datadir ./node1 -vvvvv -d --http.addr 0.0.0.0 --ws.addr 0.0.0.0 --authrpc.addr 0.0.0.0 --discovery.port 30303 --port 30303 --http --http.port 8545 --authrpc.jwtsecret ./consensus/secrets/jwt.hex --ws.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots --http.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots --ws.port 8546


for beacon using these flags

lighthouse bn --datadir ./lighthouse-datadir/ --http --execution-endpoint http://192.168.253.108:8551 --execution-jwt ./consensus/secrets/jwt.hex --metrics --http-address=0.0.0.0 --metrics-address=0.0.0.0 --enr-udp-port=9000 --enr-tcp-port=9000 --discovery-port=9000 --purge-db --metrics-port=8080 --testnet-dir=./consensus/ --disable-deposit-contract-sync --enable-private-discovery --subscribe-all-subnets --debug-level=trace --target-peers=0 --max-skip-slots=1  --http-allow-origin=* --eth1 --import-all-attestations  --validator-monitor-auto --disable-upnp --disable-backfill-rate-limiting --slots-per-restore-point=32

![Beacon node](https://vaimm.slack.com/files/U05N4RG2TGV/F06C9KNSEGY/image.png)

for validator i am using these flags
lighthouse --testnet-dir=./consensus vc --secrets-dir=./consensus/secretes --init-slashing-protection --http --http-port=4002 --metrics --metrics-address=0.0.0.0 --metrics-port=5064 --graffiti="House Stark Dev" --validator-dir=./staking-deposit-cli/validator_keys --beacon-node=http://192.168.253.108:5052/

![Validator Scrrenshot](https://vaimm.slack.com/files/U05N4RG2TGV/F06BZFG80JV/image.png)
