### ISSUE TITLE
[Feature Request] Add confirmation prompt for `--purge-db`

### ISSUE THREAD

**Issue by SeaMonkey82** [sigp/lighthouse#5028]
I've accidentally restarted lighthouse with `--purge-db` in my command line  on my testing machine enough times that I need a safety net to prevent me from being dumb.

**Comment by macladson** [comment]
I can work on this. I think it will need to be a separate flag so we don't break compatibility with automated scripts.
Something like `--purge-db-safe`.

**Comment by macladson** [comment]
Implemented in #6154
