### ISSUE TITLE
CLI strategy

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#503]
## Problem

We have several months of testing ahead of us that's going involve starting and restarting the `beacon_node` binary  in all different configurations. E.g., during the interop event we're going to be using several different configurations per day.

The CLI interface is getting a little cluttered and it's not clear as to what's going to happen. For example:

- What happens if I give a different `--spec` flag to whats in the on-disk config?
- What if I already have a database initialized with a different genesis state?
- How do I know what params I need to give in order to start from some interop method?

## Proposal

I say there's two main use cases:

- **Resuming** an existing node (e.g., load from an existing datadir/DB).
- Starting a **new node** from one of many genesis-procedures (HTTP bootstrap, genesis yaml, etc) with some spec (e.g., minimal, mainnet, custom).

To suite these two purposes, we utilize clap `subcommands` to separate between these two tasks:

- `$ ./beacon_node` (no args): is a "resume" operation.
  - If there is a datadir and DB, it's business as usual.
  - If there's no existing DB we throw an error and tell the user to use the `testnet` subcommand.
  - Once we have a big testnet or mainnet, we can make the assumption that if no DB exists, they want to connect to this testnet.
  - Does not accept a `--spec` flag. You're either using the default or an existing config. No choice for you.
- `$ ./beacon_node testnet`: is a "new node" operation. 
  - If the `datadir` already exists, return an error (avoids overwriting, confusion about whether or not TOML files will be effective).
  - We can specify a `--force` flag that will remove any existing `datadir`.
  - We can also specify a `--tmp` flag that just crates a random datadir in the `/tmp` dir.
  - Accepts a `--spec` flag. Can haz choice here.

### Testnet examples

Start a testnet node from the given YAML file and the minimal spec:
```
$ ./beacon_node testnet yaml ~/genesis_state.yaml --spec mainnet
```

Start a testnet node with 100 nodes using "recent genesis" and mainnet spec:
```
$ ./beacon_node testnet recent 100 --spec mainnet
```

Start a testnet node from another lighthouse node using Bootstrap™
```
$ ./beacon_node testnet bootstrap http://192.168.1.2
```

##  Pros

- You don't ever accidentally start from an existing DB when you wanted to start anew.
- Using `subcommands` we get name-spacing for CLI flags. E.g., if `bootstrap` needs the `--ssl` flag, we can add it to that subcommand without it showing up everywhere else.
- It'll be very obvious when you're missing a flag required for an interop method (clap can know some flag is required for a subcommand).
- You only ever need to worry about the TOML files if you want to change them.
- Doesn't over-write config files.
- Doesn't ignore config files.

## Cons

- Having to type `testnet` is additional work.
- Need to think about whether or not you're starting new or not (arguably a pro).

**Comment by AgeManning** [comment]
I like the idea of subcommands for CLI parameters that we can group into them. I agree we have a few different ways to start the client and I like the testnet subcommand idea for setting up various forms of the network.

I don't think we should throw and error for all new users who run `./beacon_node` however. I think we should make it as simple and easy for new users to use lighthouse. Therefore I think the functionality of no CLI parameters would be run existing db and chains if they exist on file, otherwise create them with default mainnet parameters. 

This will prevent all new users wanting to join mainnet to having an error thrown at them, then having to type the word 'testnet' when they really want to connect to mainnet. I think this could throw off a few people

**Comment by paulhauner** [comment]
> I don't think we should throw and error for all new users

Agreed, that's what I meant by this:

> Once we have a big testnet or mainnet, we can make the assumption that if no DB exists, they want to connect to this testnet.

I just think that whilst the default setting is unclear (i.e., no testnet, no mainnet), we just throw an error.

**Comment by AgeManning** [comment]
Yeah cool. 

Let's do this then. As things evolve, this part is really easy to change so if we go down a different path later, not much time is lost :)

**Comment by paulhauner** [comment]
I'll roll this in with some of the interop works I'm doing.
