### ISSUE TITLE
what happens if an execution endpoint is shared by two beacon nodes?

### ISSUE THREAD

**Issue by zhiqiangxu** [sigp/lighthouse#5032]
> Secondly, there is a strict one-to-one relationship between Lighthouse and the execution engine; only one Lighthouse node can connect to one execution engine.

I can understand the possible mis-behavior if one beacon node connects to two execution endpoints(like new_payload calls one, but get_payload calls the other), but what will happen if two beacon nodes connect to the same execution endpoint?

Is there any particular reason or just to be precautious?

**Comment by michaelsproul** [comment]
If the beacon nodes agree it's fine, but if they choose different heads for any reason then the execution node will flip flop between them, which causes expensive unwinding.

We have a solution for multiple BNs sharing one EL in `eleel`: https://github.com/sigp/eleel

**Comment by zhiqiangxu** [comment]
> If the beacon nodes agree it's fine, but if they choose different heads for any reason then the execution node will flip flop between them, which causes expensive unwinding.
> 
> We have a solution for multiple BNs sharing one EL in `eleel`: https://github.com/sigp/eleel

Thanks for the reply!

Good to know that there's a solution for this situation, wonder how does `eleel` avoid the flip flop when shared by multiple BNs ?

**Comment by chong-he** [comment]
> > If the beacon nodes agree it's fine, but if they choose different heads for any reason then the execution node will flip flop between them, which causes expensive unwinding.
> > We have a solution for multiple BNs sharing one EL in `eleel`: https://github.com/sigp/eleel
> 
> Thanks for the reply!
> 
> Good to know that there's a solution for this situation, wonder how does `eleel` avoid the flip flop when shared by multiple BNs ?

`eleel` acts as the "middleman" between the EL and CL, like below:

Without eleel:  CL < -- > EL (directly)
With eleel: CL < -- > `eleel` < -- > EL

There is one controlling beacon node is `eleel` that drives the node to sync, and then multiple beacon nodes can be connected to it.

**Comment by zhiqiangxu** [comment]
> > > If the beacon nodes agree it's fine, but if they choose different heads for any reason then the execution node will flip flop between them, which causes expensive unwinding.
> > > We have a solution for multiple BNs sharing one EL in `eleel`: https://github.com/sigp/eleel
> > 
> > 
> > Thanks for the reply!
> > Good to know that there's a solution for this situation, wonder how does `eleel` avoid the flip flop when shared by multiple BNs ?
> 
> `eleel` acts as the "middleman" between the EL and CL, like below:
> 
> Without eleel: CL < -- > EL (directly) With eleel: CL < -- > `eleel` < -- > EL
> 
> There is one controlling beacon node is `eleel` that drives the node to sync, and then multiple beacon nodes can be connected to it.

@chong-he Thanks for the reply, let's clarify this with an example:

Let's suppose there're two beacon nodes that don't agree, after they request `eleel`, how does `eleel` avoid the flip flop?
It seems unavoidable if there's only one `EL` node.

**Comment by michaelsproul** [comment]
> Let's suppose there're two beacon nodes that don't agree, after they request eleel, how does eleel avoid the flip flop?
It seems unavoidable if there's only one EL node.

Eleel always uses the fork choice updates of the BN that's nominated as the _controller_. So in case of a conflict, the controller's fork choice update wins, and gets passed to the EL. The fork choice updates from _follower_ nodes are never sent to the EL. The followers will receive a `VALID` responses _if_ their fork choice update agrees with the controller, otherwise if they're on a different chain they'll get a  `SYNCING` response and go into optimistic sync.
