### ISSUE TITLE
increased memory causes OOM

### ISSUE THREAD

**Issue by erfinbadrian** [sigp/lighthouse#5034]
## Description

For several minutes memory usage always increases until it causes OOM

## Version

stable - v4.0.1

## Present Behaviour
![image](https://github.com/sigp/lighthouse/assets/70316635/84e80b39-f756-4780-a1ca-82cf04bd7580)

Command : 
./lighthouse bn --disable-upnp --network mainnet --execution-endpoint http://localhost:8551 --execution-jwt /home/ozard/nodes/prysm/jwt.hex --debug-level=info --metrics --validator-monitor-auto --suggested-fee-recipient 0x90D9bA78BdebE13B91426210E6F7e802A4E640fE --checkpoint-sync-url=https://beaconstate.info

## Expected Behaviour

Stable

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
We are tracking this here (https://github.com/sigp/lighthouse/issues/4918) and working on a new release to fix it as a matter of high urgency.

**Comment by michaelsproul** [comment]
In your screenshot, Lighthouse is only using 4.5GB of memory (the RES column), so maybe you have something else that contributes to the OOM as well.
