### ISSUE TITLE
Expose more builder_boost_factor settings in VC

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#5039]
## Description

In https://github.com/sigp/lighthouse/pull/4813 we are adding the `--produce-block-v3` flag for using the v3 block production APIs in the VC. We are supporting the existing `builder_proposals: bool` config for backwards compatibility, by translating `builder_proposals: false` to `builder_boost_factor=0`.

As described by @eserilev here (https://github.com/sigp/lighthouse/pull/4813#issuecomment-1877266739) it would be good to have some more expressive options in the VC like:

- `prefer_builder_proposals: bool`: shorthand for `builder_boost_factor=u64::MAX`
- `builder_boost_factor: u64`: support for other values configured on a per-validator basis

I don't think we necessarily need `--local-always` as this is what I was forced to translate `builder_proposals: false` to. If we deprecate `builder_proposals` then the "local always"/"prefer local" naming may be clearer.

**Comment by eserilev** [comment]
I'd like to pick this up

**Comment by michaelsproul** [comment]
Thanks Eitan, it's all yours!

**Comment by paulhauner** [comment]
Heyo, we're lining up for a v4.6.0 release by Tuesday (23rd Jan) driven by the need to include the Deneb upgrades for Sepolia and Holesky.

One of the blockers on this release is reinstating `--always-prefer-builder-payload`. Our RocketPool friends rely on this flag, it's critical to them.

@eserilev, I appreciate this is a tight timeframe so we're happy to get this sorted internally if you don't have the time for this. We'd ideally need to have something ready for testing this week or Monday. No pressure from our end, just let us know 🙏

**Comment by eserilev** [comment]
@paulhauner i should have something ready for review in a few hours!

**Comment by jimmygchen** [comment]
Completed in #5086
