### ISSUE TITLE
Windows stdio in console mode does not support writing non-UTF-8 byte sequences

### ISSUE THREAD

**Issue by enet2006** [sigp/lighthouse#5043]
Failed to start beacon node
reason: Failed to start network: Error(Libp2p(Msg("Io(Os { code: 10048, kind: AddrInUse, message: \"thread '<unnamed>' panicked at 'slog::Fuse Drain: Error { kind: InvalidData, message: "Windows stdio in console mode does not support writing non-UTF-8 byte sequences" }', C:\Users\ContainerAdministrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\slog-2.7.0\src\lib.rs:1944:33

**Comment by michaelsproul** [comment]
How are you running the beacon node? Is it running as a Windows service? Can you provide the full list of beacon node flags?

**Comment by enet2006** [comment]
Windows 11 run cmd 
---------------------------- 
lighthouse bn --datadir F:\lighthouse\data --execution-endpoint http://localhost:8551 --execution-jwt F:\lighthouse\jwtsecret

**Comment by chong-he** [comment]
Running on Windows 10 Powershell with 
```
lighthouse bn --datadir D:\lighthouse\data --execution-endpoint http://localhost:8551 --execution-jwt D:\lighthouse\jwtsecret 2> text.txt
```
and it works. Have you tried with Windows 10 before?

The error you get is ` kind: AddrInUse`, it is worth checking if Windows is using any port on that?

**Comment by enet2006** [comment]
I don’t know when it will appear. I have encountered it twice. I can only restart the computer before it can work.

**Comment by chong-he** [comment]
Maybe you have started some processes that use the same address, which cause the error
