### ISSUE TITLE
When requesting rpc, sometimes it will report 502

### ISSUE THREAD

**Issue by wetezos** [sigp/lighthouse#5051]
## Description

We run the holesky network. When requesting rpc, sometimes it is normal, and sometimes it will report 502

## Version

Lighthouse v4.5.0-441fc16

**Comment by wetezos** [comment]
![photo_2024-01-09_17-25-52](https://github.com/sigp/lighthouse/assets/40154568/346cbdd7-2499-4c94-8a3d-fefcd946816e)

**Comment by michaelsproul** [comment]
Lighthouse will never return a 502 with an HTML page like that. That must be coming from some middleware like a reverse-proxying web server (nginx by the looks of it)
