### ISSUE TITLE
Lint book markdown

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#5053]
## Description

This PR https://github.com/sigp/lighthouse/pull/5029 reformatted large portions of the book due to the author's editor settings. It would be beneficial if we could define a standard format for the markdown, and check this on CI. I suspect there are several markdown linters/formatters we could choose from.

## Steps to resolve

- Pick a markdown formatter and add a CI job that applies it to the book
- Ensure that the chosen formatter is consistent with the editorconfig settings (maybe we can also lint based on editorconfig)

**Comment by ackintosh** [comment]
I would suggest [MarkdownLint](https://github.com/igorshubovych/markdownlint-cli). I think that's the standard linter for markdown format. Also, [GitHub Super Linter](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/) contains MarkdownLint so we can use it out of the box.

**Comment by chong-he** [comment]
Closed by #5494
