### ISSUE TITLE
Blocks v3 endpoint incorrect content type

### ISSUE THREAD

**Issue by mcdee** [sigp/lighthouse#5061]
## Description

The `/eth/v3/validator/blocks/{slot}` endpoint is returning an unexpected content type.

## Version

```
lighthouse --version
Lighthouse v4.6.0-rc.0-2e8e160
BLS library: blst-modern
SHA256 hardware acceleration: true
Allocator: jemalloc
Profile: maxperf
Specs: mainnet (true), minimal (false), gnosis (true)
```

## Present Behaviour

A call to the above endpoint with an `Accept: application/octet-stream` returns a content type of `application/ssz`

## Expected Behaviour

The content type should be `application/octet-stream` as per the beacon API specs.

**Comment by michaelsproul** [comment]
Good find! We will fix this up ASAP

**Comment by chong-he** [comment]
Close by #5062
