### ISSUE TITLE
Delete `lighthouse/beacon/states/{state_id}/ssz` endpoint

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#5063]
## Description

`lighthouse/beacon/states/{state_id}/ssz`

This endpoint is redundant and no longer required, because equivalent endpoints now exist in the standard beacon API.

## Version

Lighthouse v4.6.0-rc.0

**Comment by hoseincc** [comment]
Hi

**Comment by Doomersan** [comment]
Hello, may I be assigned to complete this one?
Is it just a matter of removing this [function](https://github.com/sigp/lighthouse/blob/stable/beacon_node/http_api/src/lib.rs#L4184)
and this [line](https://github.com/sigp/lighthouse/blob/stable/beacon_node/http_api/src/lib.rs#L4562)

**Comment by michaelsproul** [comment]
Sorry @Doomersan, already done here https://github.com/sigp/lighthouse/pull/5065
