### ISSUE TITLE
Lighthouse returning `blobs pruned within boundary` on non-mainnet config

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#5092]
## Description

We got a report that a non-mainnet config for this field: `MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 16384` results in this message from LH peers: `blobs pruned within boundary`. The nodes look to be working ok otherwise. We should make sure we're properly loading and utilizing `MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS` when serving blob requests.

**Comment by michaelsproul** [comment]
Could this be downstream of https://github.com/sigp/lighthouse/issues/5114? I haven't thought it through

**Comment by realbigsean** [comment]
Yes, I think that's probably it. This is how we would respond to blob requests by root or range to peers if we don't have blobs within the DA period. We'd be checking the blobs db to respond to these requests. So anything backfilled and erroneously stored, we wouldn't find and assume we must have pruned.

**Comment by realbigsean** [comment]
fixed in https://github.com/sigp/lighthouse/issues/5114
