### ISSUE TITLE
Upgrade to sequential processing of batch sync and correct thread handling

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#511]
## Description

The current sync strategy downloads sequential batches of blocks from known peers. Once an entire chain that is linked to our finalized head block is identified, all downloaded blocks are processed. 

This is undesirable for a number of reasons. 

1. We need to maintain, potentially large memory stores of downloaded blocks before processing
2. The processing of all blocks at one period of time, locks the beacon_chain with constant write locks
3. The current head doesn't update until all blocks are downloaded, making syncing with other peers inefficient

The better behavior is to process batches as they are downloaded. This is not always possible if batches do not form a known chain back to our finalized head. In such instances batches should be downloaded backwards until a common ancestor is reached, processed, then sequentially processed and downloaded until we reach the peers head. 

Block processing should also be able to be terminated via the ctrl+c exit.

**Comment by paulhauner** [comment]
@AgeManning is this still relevant?

**Comment by AgeManning** [comment]
Resolved in the Silky Smooth Syncs PR (#816)
