### ISSUE TITLE
[Sepolia network] Deneb fork support (Jan 30th)

### ISSUE THREAD

**Issue by luarx** [sigp/lighthouse#5115]
## Description

Is the upcoming Deneb fork supported by Lighthouse in Sepolia network happening on **Jan 30th**?
I see some RC that support Goerli but nothing for Sepolia

Thanks in advance!

**Comment by realbigsean** [comment]
Hi @luarx!

We're planning to release `v4.6.0` with Sepolia support within the next ~24 hours

**Comment by luarx** [comment]
Great! Thanks for answering @realbigsean 
Looking forward 😄
