### ISSUE TITLE
Logfile error: initializing rolling file appender failed: InitError  kind: AlreadyExists, message: "File exists"

### ISSUE THREAD

**Issue by luboremo** [sigp/lighthouse#5116]
## Description

After upgrading, lighthouse won't start with error: 

"initializing rolling file appender failed: InitError { context: "failed to create log directory", source: Os { code: 17, kind: AlreadyExists, message: "File exists" } }"

## Version
v4.6.0-rc.0

## Present Behaviour

Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]: Jan 23 12:37:55.679 INFO Logging to file                         path: "/srv/lighthouse/log/validator.log"
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]: thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-appender-0.2.3/src/rolling.rs:154:14:
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]: initializing rolling file appender failed: InitError { context: "failed to create log directory", source: Os { code: 17, kind: AlreadyExists, message: "File exists" } }
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]: stack backtrace:
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    0:     0x55d8701e903c - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    1:     0x55d8702186bc - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    2:     0x55d8701e490e - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    3:     0x55d8701e8e24 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    4:     0x55d8701ea6d3 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    5:     0x55d8701ea3f4 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    6:     0x55d8701eac55 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    7:     0x55d8701eab51 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    8:     0x55d8701e9566 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:    9:     0x55d8701ea8a2 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   10:     0x55d86db0e345 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   11:     0x55d86db0e823 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   12:     0x55d86f272124 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   13:     0x55d86f2748b2 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   14:     0x55d86e70d723 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   15:     0x55d86e70bc05 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   16:     0x55d86ea55b93 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   17:     0x55d86e4ef819 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   18:     0x55d8701dadeb - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   19:     0x55d86e70f3b5 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   20:     0x7facb81671ca - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   21:     0x7facb8167285 - __libc_start_main
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   22:     0x55d86db0eb51 - <unknown>
Jan 23 13:37:55 eth-validator-primary validator.sh[3390888]:   23:                0x0 - <unknown>
Jan 23 13:37:55 eth-validator-primary systemd[1]: lighthouse-validator.service: Main process exited, code=exited, status=101/n/a
Jan 23 13:37:55 eth-validator-primary systemd[1]: lighthouse-validator.service: Failed with result 'exit-code'.

## Expected Behaviour

It should run as previously with already loaded validator keys.

## Steps to resolve

changing flags from:
	--logfile ${_DIR}/log/validator.log \
	--logfile-max-number 5 \
	--logfile-max-size 200 

to:
	--logfile-max-number 0

**Comment by chong-he** [comment]
Closed by #5117
