### ISSUE TITLE
Fedora/RHEL/CentOS build instructions

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#5124]
## Description

It would be nice to have build from source dependencies documented for `yum` distributions, being the other major family of distributions apart from Debian and Arch.

## Steps to resolve

1. Build Lighthouse on Fedora and document the dependencies that are required (e.g. `perl-IPC-Cmd` is apparently required).
2. Add a section to the docs on these dependencies

Building Lighthouse inside a Fedora docker image would probably be the easiest way to accomplish this.

**Comment by chong-he** [comment]
Closed by #5225
