### ISSUE TITLE
EIP-7002: EL Triggerable Exits

### ISSUE THREAD

**Issue by macladson** [sigp/lighthouse#5129]
## Description

EIP -> https://eips.ethereum.org/EIPS/eip-7002

Was confirmed for Electra in latest ACD consensus call.
This will require some coordination from EL teams in order to do testing, etc.

## Implementation

As per the EIP, the flow is:

- New operation `ExecutionLayerExit`
- Will show up in `ExecutionPayload` as an SSZ List bound by length `MAX_EXITS_PER_BLOCK`
- New function in `process_execution_layer_exit` that has similar functionality to process_voluntary_exit but that can fail validations (e.g. validator is already exited) without the block failing (similar to deposit coming from EL)
- `process_execution_layer_exit` called in `process_operations` for each `ExecutionLayerExit` found in the `ExecutionPayload`

**Comment by dapplion** [comment]
There was strong agreement for inclusion? At this point is okay to spend dev resources on it for sure, but I would refrain from merging it into unstable/electra branch for at least 2-3 ACDCs

**Comment by macladson** [comment]
> There was strong agreement for inclusion? At this point is okay to spend dev resources on it for sure, but I would refrain from merging it into unstable/electra branch for at least 2-3 ACDCs

For now just going off of [this PR/commit](https://github.com/ethereum/EIPs/pull/8121/commits/80548bf853cd6e54d995af205bd031c93fbf82ee). My aim is to keep these issues updated as things change

**Comment by realbigsean** [comment]
It sounded like EL teams had already OK'd 6110 and 7002 on the last ACDE

> but I would refrain from merging it into unstable/electra branch for at least 2-3 ACDCs

Seems reasonable!
