### ISSUE TITLE
EIP-7549: Move committee index outside Attestation

### ISSUE THREAD

**Issue by macladson** [sigp/lighthouse#5130]
## Description

EIP -> https://eips.ethereum.org/EIPS/eip-7549
Specs -> https://github.com/ethereum/consensus-specs/pull/3559

Was confirmed for Electra in ACD call 126.
This does not require any changes from the EL.

## Implementation

Move `index` field from `AttestationData` to `Attestation`
It was loosely agreed that the original `index` field in `AttestationData` should be set to 0 after the fork, instead of removed.

**Comment by eserilev** [comment]
if no one else has started on this, i'd like to pick this one up
