### ISSUE TITLE
Clean up naming of `VariableList`/`FixedVector` on tree-states

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#5141]
## Description

At the moment `tree-states` has a confusing mix of type aliases for the `VariableList`/`FixedVector` types. To remedy the situation I'm proposing to instead use these names:

- `VariableList`/`FixedVector`: same as on `stable`, refer to types from `ssz_types`
- `List`/`Vector`: unmodified `milhouse` type names

Alternatively, we could alias _both_ libraries with new names:

- `TreeList`/`TreeVector`: type aliases for `milhouse` types
- `FlatList`/`FlatVector`: type aliases for `ssz_types` types

However I think avoiding aliases altogether is probably clearer.

**Comment by dapplion** [comment]
> - VariableList/FixedVector: same as on stable, refer to types from ssz_types
> - List/Vector: unmodified milhouse type names

+1
