### ISSUE TITLE
Make `execution-endpoint` required on the CLI

### ISSUE THREAD

**Issue by zhiqiangxu** [sigp/lighthouse#5159]
Here's the command to run `bn` without `execution-endpoint`:

```bash
lighthouse bn --network sepolia  --http --allow-insecure-genesis-sync
```

Then I see lots of `ExecutionLayerMissing` errors:

<img width="1646" alt="image" src="https://github.com/sigp/lighthouse/assets/1265027/d400437f-1824-4ba0-91ae-41a0df24d285">

Not sure whether it's the expected behaviour? But IMO if user didn't specify the `execution-endpoint`, these errors should not be shown since assumed.

**Comment by chong-he** [comment]
`--execution-endpoint` must be supplied for a beacon to sync; if it is not supplied, the beacon will complain about it because it can't sync

**Comment by zhiqiangxu** [comment]
> `--execution-endpoint` must be supplied for a beacon to sync; if it is not supplied, the beacon will complain about it because it can't sync

Well, why not report an error and quit when started if `--execution-endpoint` must be supplied?

**Comment by michaelsproul** [comment]
> Well, why not report an error and quit when started if --execution-endpoint must be supplied?

This is leftover from the pre-Merge era when we went from making `--execution-endpoint` optional, to making it mandatory. We could make the CLI flag `.required(true)` now that all networks have merged

**Comment by Parikalp-Bhardwaj** [comment]
Hi @michaelsproul , I was wondering if this issue is still open or if there's been any update on it?

**Comment by jimmygchen** [comment]
Completed in #5165 🎉
