### ISSUE TITLE
chain_db folder keeps growing.

### ISSUE THREAD

**Issue by aBMania** [sigp/lighthouse#5167]
## Description

On certain lighthouse instances, my chain_db folder keeps growing. 

```shell
$ du -h /beacon
384K	/beacon/blobs_db
1.4G	/beacon/logs
  16K	/beacon/network
229G	/beacon/chain_db
118G	/beacon/freezer_db
348G	/beacon
```

My instance is launched with the following command:

```
/usr/local/bin/lighthouse beacon_node \
    --datadir=/beacon \
    --disable-upnp \
    --slots-per-restore-point=512 \
    --genesis-backfill \
    --reconstruct-historic-states \
    --historic-state-cache-size=4 \
    --checkpoint-sync-url=https://holesky.beaconstate.ethstaker.cc/ \
    --enr-address=... \
    --port=9100 \
    --http \
    --http-address=... \
    --listen-address=... \
    --http-port=3500 \
    --execution-jwt=/beacon/erigon-jwt.hex \
    --metrics \
    --metrics-address=... \
    --metrics-port=6070  \
    --network=holesky \
    --execution-endpoint=http://127.0.0.1:8551 \
    --validator-monitor-auto
```

Nothing out of the ordinary in the logs, but keep in mind that the instance is in "State reconstruction in progress" state: 
`INFO State reconstruction in progress        remaining: 580607, slot: 124928, service: freezer_db`

Is it normal behavior ? 
My other instance (not run with `--historic-state-cache-size` and `--genesis-backfill`) seems to be working fine

## Version

`Lighthouse/v4.6.0-1be5253`

## Behavior

![image](https://github.com/sigp/lighthouse/assets/6453558/df929ed2-b2ab-471e-8821-da6621766342)
_store_disk_db_size_

The upper curve is my problematic lighthouse instance chain db size.
The bottom curve is my other lighthouse instance.

**Comment by michaelsproul** [comment]
Yeah, this is a known behaviour. There's an issue here to cover it: https://github.com/sigp/lighthouse/issues/3026

We've fixed that on the tree-states branch, which will be getting merged down to `stable` soon (TM) [after Deneb on mainnet]

**Comment by michaelsproul** [comment]
You can check the current slot of the "split" point using this command: `curl http://localhost:5052/lighthouse/database/info`. You'll notice that the `split.slot` is quite old. This means all states stored since that slot are stored used the less-efficient "hot" database format, while prior states are stored using the "cold" format. Once your node finishes reconstructing states it will rewrite the states from the hot to the cold, and the disk usage will drop.

**Comment by aBMania** [comment]
Alright, thanks for the quick response !
