### ISSUE TITLE
Update simulator for all forks

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#5173]
## Description

@dapplion pointed out that the simulator only forks up to Bellatrix currently and we haven't updated it since then.

We should update the simulator such that it works for all current and future forks. We could have it such that it always starts from bellatrix. It should fail if we added a new fork but failed to update the config to support the fork.
For deneb, we should add blob support such that the simulator is able to produce blocks with blobs.

**Comment by jimmygchen** [comment]
Updated in #5520 🎉
