### ISSUE TITLE
Issue in README "Simple Local Testnet"

### ISSUE THREAD

**Issue by djrtwo** [sigp/lighthouse#519]
## Description

When going to Step 3 ([Start Another Beacon Node](https://github.com/sigp/lighthouse#3-start-another-beacon-node)) in the readme simple testnet instructions, the second node fails due to a collision in the RestAPI port.

## Present Behaviour

The current behaviour is that `./beacon_node` defaults to having the Rest API enabled due to the following default config.

https://github.com/sigp/lighthouse/blob/c4ced3e0d25f40e14c2f47a43285da4faf350a01/beacon_node/rest_api/src/config.rs#L16-L24

Because both `beacon_node` programs are attempting to run with the default port (5052), the second has a collision and crashes. You can run the second with `--api-port <no-5052>` as a quick fix.

More importantly, the way `--api` command line option is configured, you can't actually turn the rest api server _off_ because this value defaults to `enabled` when no param is given. When the param is given, `--api` just triggers it to be on, so it's on always.

## Expected Behaviour

Should be able to just run the commands in the quickstart without error. The quickfix is to just add an `--api-port` command to the quickstart step 3. 

The deeper fix is to reconsider how the rest api should be controlled.

Should probably do one of the following:
- `--api` should accept True/False
- `--api` should be swapped for a flag that disables the api server (eg `--no-api` or `--api-off`)
- the API server should be turned off by default with the `--api` flag turning it on

## Steps to resolve

- fix quickstart instructions
- fix up `--api` so it can actually be turned on and off

Please describe the steps required to resolve this issue, if known.

**Comment by AgeManning** [comment]
Hey Danny. Thanks for this. This has been fixed on our local branches but not pushed to master. Will correct in next merge.
