### ISSUE TITLE
Remove more gossipsub duplicate warnings

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#5197]
## Description

This PR https://github.com/sigp/lighthouse/pull/5163 removes some warnings, but doesn't cover this case:

> WARN Gossip message publish failed on retry  error: Duplicate, topic: beacon_attestation, service: libp2p

Relevant code is here:

https://github.com/sigp/lighthouse/blob/c7e5dd1098a145c0d2174dc65bd23faeb5074249/beacon_node/lighthouse_network/src/service/mod.rs#L1222-L1245

There are 3 cases, and I think we should warn in at most 2 of them:

- Message published successfully on retry: warn? because it was probably published late? no warn? because these logs are annoying af?
- Message failed to publish because it was a duplicate: no warn.
- Message failed to pubish at all: warn.

## Version

Lighthouse v4.6.0

## Additional Info

The `Gossip message publish failed on retry` is _much_ more common on our infra, with 50M occurrences in the last month across our infra. By comparion, `Gossip message published on retry` has only 27k occurrences, it seems mostly after a node restarting.

**Comment by paulhauner** [comment]
Resolved via #5235
