### ISSUE TITLE
Docs for attestation simulator

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#5200]
## Description

Paul has a blog post coming soon on the attestation simulator, but there are no docs for it.

We could devote a section of the _Validator Monitor_ docs to it, briefly explain how it works, what logs it produces, and what metrics to check.

## Version

Lighthouse v4.6.0

**Comment by chong-he** [comment]
I would like to work on this

**Comment by chong-he** [comment]
Added the info in #5364
