### ISSUE TITLE
`local_testnet` script fails to setup a devnet with Capella enabled from genesis

### ISSUE THREAD

**Issue by ferranbt** [sigp/lighthouse#5211]
## Description

Hello, I was using the [local testnet setup](https://github.com/sigp/lighthouse/tree/c7e5dd1098a145c0d2174dc65bd23faeb5074249/scripts/local_testnet) from the repository and it does not work if the capella fork is enabled at epoch 0. The bash script fails to load the `genesis.ssz` file to update the time in `setup_time.sh`.

## Version

Main

## Present Behaviour

The local testnet script cannot start a network with Capella enabled from genesis.

## Expected Behaviour

I would expect that the local script could start a network with both Capella and Deneb enabled at genesis.

## Steps to resolve

```
$ cd ./scripts/local_testnet
```

Update `CAPELLA_FORK_EPOCH` in `vars.env` to 0 and run:

```
./start_local_testnet.sh genesis.json
```

**Comment by realbigsean** [comment]
Hello! 

I believe you need to install the version of `lcli` from this PR https://github.com/sigp/lighthouse/pull/5137
in order for genesis at capella or deneb to work

**Comment by realbigsean** [comment]
That PR should hopefully be merged soon

**Comment by ferranbt** [comment]
Thank you! Will try that branch tomorrow.

**Comment by ferranbt** [comment]
It works! Feel free to close the issue.
