### ISSUE TITLE
Checkpoint Sync URL (block root does not match & InvalidSsz)

### ISSUE THREAD

**Issue by lrhache** [sigp/lighthouse#5249]
## Description

I'm getting 2 types of errors trying to start beacon node with checkpoint-sync-url.

It's **only** doing this on the particular machine I'm using, Ubuntu server.
- attempted on 22.04 and 22.10, with same results
-  cpu maybe? ryzen 5950x

Error:
```
CRIT Failed to start beacon node reason: Error loading checkpoint state from remote: InvalidSsz(BytesInvalid("Out-of-range for boolean: 216"))
```
or
```
CRIT Failed to start beacon node reason: Snapshot state's most recent block root does not match block, expected: 0xe2553882acf1372ca2dcf74d5d84c23b5fdcfabf4f82db72cbc2013ca5cbe33e, got: 0x1df72f19463c622346f79ff281df8284dc39ec2964c56544415fec2b967688ec
```

I tried:
- both pre-built (`lighthouse-v4.6.0-x86_64-unknown-linux-gnu.tar.gz` & portable) 
- building from source
- Docker image
- purging or deleting data directory before each tries
- different public endpoints

All yield the similar errors.

Any guidance would be highly appreciated. 

## Version
Lighthouse: `stable`
Rust: 1.76.0

## Present Behaviour

```
$ ./lighthouse bn --network mainnet --datadir=/home/xxxx/.lighthouse --disable-deposit-contract-sync --checkpoint-sync-url https://mainnet.checkpoint.sigp.io --execution-endpoint http://127.0.0.1:8551 --execution-jwt /secrets/jwt.hex
...
Feb 15 14:39:42.613 INFO Blob DB initialized                     oldest_blob_slot: None, path: "/home/spider/.lighthouse/beacon/blobs_db", service: freezer_db
Feb 15 14:39:42.619 INFO Starting checkpoint sync                remote_url: https://mainnet.checkpoint.sigp.io/, service: beacon
Feb 15 14:40:00.316 INFO Loaded checkpoint block and state       block_root: 0xe2553882acf1372ca2dcf74d5d84c23b5fdcfabf4f82db72cbc2013ca5cbe33e, state_slot: 8431904, block_slot: 8431904, service: beacon
Feb 15 14:40:01.944 CRIT Failed to start beacon node             reason: Snapshot state's most recent block root does not match block, expected: 0xe2553882acf1372ca2dcf74d5d84c23b5fdcfabf4f82db72cbc2013ca5cbe33e, got: 0x1df72f19463c622346f79ff281df8284dc39ec2964c56544415fec2b967688ec
Feb 15 14:40:01.944 INFO Internal shutdown received              reason: Failed to start beacon node
Feb 15 14:40:01.944 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
Failed to start beacon node
```

**Comment by lrhache** [comment]
```
 ERRO Migrator failed to load state error: Err(SszDecodeError(BytesInvalid("110 is not a valid union index for Option<T>"))), state_root: BeaconStateHash(0x16b27b95688810d977e906825dfc51cea3368cdb6a9c1cce01f2713d4f5209dd), service: beacon
```
```
 WARN Block pruning failed  error: DBError(SszDecodeError(BytesInvalid("Out-of-range for boolean: 212"))), service: beacon
```
I've started getting those errors while syncing without checkpoint

**Comment by michaelsproul** [comment]
@lrhache It seems like your RAM is faulty. The second batch of errors in particular are very esoteric and basically impossible to trigger unless the compiler is buggy or the hardware is faulty.

Run a memtest using memtest86+ and see if it fails.

**Comment by lrhache** [comment]
Thank you so much! I indeed had one faulty stick. I appreciate the help!

**Comment by rahul799** [comment]
Hi @michaelsproul , I am getting the below issue 
`Error loading checkpoint state from remote: InvalidSsz(OffsetSkipsVariableBytes(584))`
It will be great if you can help me out please

**Comment by michaelsproul** [comment]
@rahul799 you've got an old Lighthouse version. Make sure you're running v5.1.3

**Comment by thaitd1234** [comment]
hi @michaelsproul , I'm facing below error
"Error loading checkpoint state from remote: InvalidSsz(OffsetSkipsVariableBytes(2737225))" 

Could you please help? Thanks

**Comment by michaelsproul** [comment]
@thaitd1234 Same issue. Use v8.0.1.
