### ISSUE TITLE
eth2.0-spec-tests submodule removed

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#527]
## Description

[This commit](https://github.com/sigp/lighthouse/commit/9461b5063b3ea9e0af05527af7dacf3d9d13f438) removes the `eth2.0-spec-tests` submodule and introduces a `Makefile` that downloads the files previously supplied by the submodule. The makefile downloads files from the [test releases](https://github.com/ethereum/eth2.0-spec-tests/releases).

Why this was done:
- According to @protolambda, the submodule/git-lfs solution was bad practice. This is because:
  - The downloads via git-lfs are metered by Github and come out of the EF pocket, whilst downloads from the release page are not. Whilst our CI can cache these tests, every user who clones the repo will download these files.
  - We have no need for the git history of the tests when running them, so having a git repository is overkill.
- The tests are huge (order of GB). Downloading the gzipped files from the release pages uses _much_ less bandwidth.

Additionally, I added logic so that if the downloaded files are not present, we just let all the tests pass. This means we don't _require_ all users/developers to download the spec files, only those who want to.

## Steps to resolve

- @michaelsproul please have a look at that commit and let me know you're ok with it.
- Update the CI so that it runs `make ef_tests` before running the tests (perhaps @spble?)

**Comment by michaelsproul** [comment]
Nice, getting rid of that hefty git submodule is great. The makefile looks good on the whole, I just have two comments:

* The `SPEC_VERSION` variable is undefined, should be `TESTS_TAG`?
* Using `gzip` and `tar` separately seems unnecessary, `tar -xvf` should take care of decompression too.

**Comment by michaelsproul** [comment]
I'm going to have a go at setting up Gitlab to run the EF tests
