### ISSUE TITLE
List of known interop issues to correct

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#532]
## Description

This is a listing of known issues that need to be corrected

- Attestations are sent at the start of the slot, not halfway through and can be sent before a block is produced
- RPC request streams are being reset before closed
- Ping requests don't close streams (to be confirmed)
- Timing on new RPC req/resp should be applied per chunk

**Comment by paulhauner** [comment]
Hey @AgeManning is this still relevant?

**Comment by AgeManning** [comment]
These issues have all be resolved independently and we have removed the Ping protocol
