### ISSUE TITLE
Uptime problem

### ISSUE THREAD

**Issue by siavash3441** [sigp/lighthouse#5320]
sigp/lighthouse:v4.6.0         "lighthouse bn --net…"   3 days ago   Up 39 minutes         0.0.0.0:9000->9000/tcp, 0.0.0.0:9000->9000/udp, :::9000->9000/tcp, :::9000->9000/udp                               charon-distributed-validator-node-lighthouse-1

Hello
I have an uptime problem
Our server shuts down the lighthouse every few minutes
please help

**Comment by michaelsproul** [comment]
Please tell us system specs (CPU, RAM, etc) and show us some logs. You can find debug logs in `$datadir/beacon/logs` or you can get info logs from Docker

**Comment by jimmygchen** [comment]
Closing this one as we haven't heard back from the user. Feel free to comment and we'll re-open.
