### ISSUE TITLE
Gossipsub logging

### ISSUE THREAD

**Issue by pawanjay176** [sigp/lighthouse#5389]
## Description

In https://github.com/sigp/lighthouse/pull/4988 , we started writing libp2p logs into a file.

After we moved gossipsub behaviour into lighthouse in https://github.com/sigp/lighthouse/pull/5066, there doesn't seem to be any way to get the gossipsub logs as they aren't under the gossipsub dependency and they use tracing log as opposed to slog as rest of lighthouse.

We should have an option to enable these gossipsub logs somehow. A hacky way to I used to enable this was to use stdout as the tracing_subscriber writer instead of `std::io::sink`.
https://github.com/sigp/lighthouse/blob/10a38a8aae8b4d1b9665828cefabd2e2c534b8b9/common/logging/src/lib.rs#L269-L275

**Comment by ackintosh** [comment]
This issue has been fixed in https://github.com/sigp/lighthouse/pull/5401. 🎉
