### ISSUE TITLE
Beacon Processor's Inbound Event Queue Is Unaffected By a Runtime Argument

### ISSUE THREAD

**Issue by JamesCropcho** [sigp/lighthouse#5390]
## Description

The length of the Beacon Processor's inbound event queue (a.k.a. work queue) is unaffected the by the `--beacon-processor-work-queue-len` runtime argument.

## Version

Multiple versions of Lighthouse are affected.

#### Output of `lighthouse --version`

```
Lighthouse v5.1.0-10a38a8
BLS library: blst-modern
SHA256 hardware acceleration: true
Allocator: jemalloc
Profile: maxperf
Specs: mainnet (true), minimal (false), gnosis (false)
```

#### Output of `lighthouse --version`

```
Lighthouse v5.0.0-b5bae6e
BLS library: blst-modern
SHA256 hardware acceleration: true
Allocator: jemalloc
Profile: maxperf
Specs: mainnet (true), minimal (false), gnosis (false)
```

#### Command Issued for Building
```
CARGO_INSTALL_EXTRA_FLAGS="--no-default-features" PROFILE=maxperf RUSTFLAGS='-C target-cpu=native' FEATURES="modern,slasher-lmdb,jemalloc" make
```

#### Output of `rustc --version`

```
rustc 1.76.0 (07dca489a 2024-02-04)
```

### Runtime Configuration

The Beacon Node service is started with a number of runtime arguments. Here are those which are likely to be relevant:

```
--beacon-processor-work-queue-len      32768
--beacon-processor-reprocess-queue-len 24576 
```

The following are the relevant runtime parameters for which an argument is _not_ declared _(given here for sake of completeness)_:

```
--http-enable-beacon-processor
--beacon-processor-max-workers
```

### Output

Lighthouse's log will include the following:

```
ERRO Attestation queue full                  queue_len: 16384, msg: the system has insufficient resources for load, service: bproc
```

The log entry suggests that the queue length is 16384 (suspiciously, this is the default value).

## Expected Behaviour

I would expect to see log entries like:

```
ERRO Attestation queue full                  queue_len: 32768, msg: the system has insufficient resources for load, service: bproc
```

Note that `queue_len` above matches the declared `--beacon-processor-work-queue-len` value.

#### Output of `$ lighthouse bn --help | grep -i beacon-processor-work-queue-len -A2`:
```
        --beacon-processor-work-queue-len <INTEGER>
            Specifies the length of the inbound event queue. Higher values may prevent messages from being dropped while
            lower values may help protect the node from becoming overwhelmed. [default: 16384]
```

## Steps To Resolve

I do not know.

**Comment by michaelsproul** [comment]
You're right that the `--beacon-processor-work-queue-len` doesn't do anything, but it was never intended to be used by users, and was never intended to modify the length of the attestation queue. There are many many queues in LH, and the attestation queue is just one of them, see:

https://github.com/sigp/lighthouse/blob/10a38a8aae8b4d1b9665828cefabd2e2c534b8b9/beacon_node/beacon_processor/src/lib.rs#L74-L196

We are planning to hide, deprecate and remove these flags.

The solution in your case is to allocate more resources (CPU, RAM, I/O), as queueing more messages is usually not a useful behaviour.

**Comment by JamesCropcho** [comment]
Okay, noted. Thank you for the explanation as well as the advice!

**Comment by JamesCropcho** [comment]
It seems like the "Attestation queue full" error message is **only appearing immediately after** the usual set of "Previous epoch attestation(s)…" info messages.

Is it possible that there is simply a sufficient count of attestation messages broadcast to a sufficient peer count, that a length of 16,384 is guaranteed to be momentarily exceeded?

I'm running a 16-core, 3.5 GHz Intel Xeon Ice Lake CPU (with SHA256 extensions and ADX, and built using "maxperf"). My storage is a Provisioned IOPS network drive. This machine is only running `lighthouse bn` (the other needed machines are physically clustered near it). RAM allocation is a fraction of the total available.

(I _am_ using `--subscribe-all-subnets` and `--import-all-attestations`, just FYI.)

Is it possible that the allocation of more CPU, RAM, or I/O resources is _not_ primarily what is needed? My resource/process monitoring suggests that I am not making use of what is already available.

Sorry if it is a crazy idea, but I've got to ask…

**Comment by dapplion** [comment]
Ethereum mainnet has 977188 active vals, so that's ~30,000 unaggregated attestations per slot max. Maybe we need to review the queue numbers up @paulhauner ?

**Comment by paulhauner** [comment]
> Ethereum mainnet has 977188 active vals, so that's ~30,000 unaggregated attestations per slot max. Maybe we need to review the queue numbers up @paulhauner ?

Totally! Some sort of mechanism to give us a heads up on this would be handy. I'm not sure of the cleanest way to do this, though. It would be nice if it would just alert us devs rather than every user. Adding something to CI which calls an API (beaconcha.in?) could be an option, but it would also be annoying (some random PR would just start failing).

**Comment by dapplion** [comment]
Why not make those values dynamic on the state size on the node starting? Should be good enough even for someone running the same process for 1 year un-interrupted

**Comment by paulhauner** [comment]
> Why not make those values dynamic on the state size on the node starting? Should be good enough even for someone running the same process for 1 year un-interrupted

Yep, dynamic is definitely ideal. I think it'll be the first dynamic queue in the `BeaconProcessor` but it's very achievable.

**Comment by michaelsproul** [comment]
Beacon processor queue sizes are dynamic as of:

- https://github.com/sigp/lighthouse/pull/5573

The beacon processor's scheduler is still sub-optimal, and I am planning to write-up an issue for that after some more investigation. Will close this issue for now, as the issue identified has been resolved.
