### ISSUE TITLE
Deprecate `http-spec-fork` and `http-allow-sync-stalled`

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#5430]
## Description

We should make `http-spec-fork` and `http-allow-sync-stalled` into hidden no-op flags.

The semantics should be:

- Keep the default spec fork, i.e. ignore `http-spec-fork`.
- Remove the boolean for `allow_sync_stalled` and hardcode the logic as if it is `true` (i.e. make `--http-allow-sync-stalled` the new hardcoded default).

The first change is uncontroversial, we are just removing an option that was rarely used.

The second change is more substantial but I believe is in the right direction. We want to prioritise liveness for the HTTP API, and having the BN refuse to serve certain routes risks stalling the chain on small networks. On devnets and testnets the EF routinely add the `--http-allow-sync-stalled` flag, as its behaviour is slightly more reliable than the current default behaviour. Sync rarely enters into the `Stalled` state unless the node has very very few peers, and it's hard for us to tell apart "stalled because my node disconnected from the internet" and "stalled because the network is near death and needs me to continue it", so we may as well choose the safe option (allow) at the risk of producing some crappy blocks & attestations in rare cases.

**Comment by michaelsproul** [comment]
cc @eserilev

**Comment by jimmygchen** [comment]
Completed in #5500 🎉
