### ISSUE TITLE
Eth-mainnet beacon-nodes OOM at 2024-03-27 02:37:20 (UTC) & 2024-03-27 19:09:17 (UTC)

### ISSUE THREAD

**Issue by rekyyang** [sigp/lighthouse#5503]
## Description

Our three Eth-mainnet beacon-nodes OOM at 
2024-03-27 02:37:20 (UTC)
2024-03-27 19:09:17 (UTC)

It's like a spike at these time points, and the mem usage is low at other time.

the limited mem of lighthouse container is 16GB

## Version
5.0.0

## Present Behaviour

lighthouse OOM and this is the log before OOM

Mar 27 02:35:41.001 INFO Synced                                  slot: 8723576, block: 0xecde…eb5f, epoch: 272611, finalized_epoch: 272609, finalized_root: 0x9ef2…2191, exec_hash: 0xf150…c864 (verified), peers: 97, service: slot_notifier
Mar 27 02:35:48.595 INFO New block received                      root: 0xe13c84ea11710bb872b23f62783ea558bfbafc4b55975f38027159bfabc225c0, slot: 8723577
Mar 27 02:35:53.001 INFO Synced                                  slot: 8723577, block: 0xe13c…25c0, epoch: 272611, finalized_epoch: 272609, finalized_root: 0x9ef2…2191, exec_hash: 0x14f2…d018 (verified), peers: 96, service: slot_notifier
Mar 27 02:36:00.434 INFO New block received                      root: 0xecdf66e5842c5f6354f731ca5f1c878472ff5d72dc63d5d6107e831e555649e5, slot: 8723578
Mar 27 02:36:05.002 INFO Synced                                  slot: 8723578, block: 0xecdf…49e5, epoch: 272611, finalized_epoch: 272609, finalized_root: 0x9ef2…2191, exec_hash: 0x8d2d…3329 (verified), peers: 96, service: slot_notifier
Mar 27 02:36:13.005 INFO New block received                      root: 0xce14b5a396d98e5a79b7f4532612f9bf85831cc61339383d0dc44d6975a83df6, slot: 8723579
Mar 27 02:36:17.001 INFO Synced                                  slot: 8723579, block: 0xce14…3df6, epoch: 272611, finalized_epoch: 272609, finalized_root: 0x9ef2…2191, exec_hash: 0xa663…3596 (verified), peers: 96, service: slot_notifier
Mar 27 02:36:19.074 INFO Imported deposit log(s)                 new: 1, total: 1381515, latest_block: 19521233, service: deposit_contract_rpc
Mar 27 02:36:25.332 INFO New block received                      root: 0x2ce67860785382ed19da182ef0238571a913a253bff3b40f195612b48f5423f9, slot: 8723580
Mar 27 02:36:29.001 INFO Synced                                  slot: 8723580, block: 0x2ce6…23f9, epoch: 272611, finalized_epoch: 272609, finalized_root: 0x9ef2…2191, exec_hash: 0xa0f6…9fe7 (verified), peers: 96, service: slot_notifier
Mar 27 02:36:36.391 INFO New block received                      root: 0x7787c617c3c938ed140a7b6b0c3142557b2952839995f6a4f3215b1c65b8819d, slot: 8723581
Mar 27 02:36:36.760 INFO Gossipsub blob processed, imported fully available block, block_root: 0x7787…819d
Mar 27 02:36:41.001 INFO Synced                                  slot: 8723581, block: 0x7787…819d, epoch: 272611, finalized_epoch: 272609, finalized_root: 0x9ef2…2191, exec_hash: 0x8180…dc0e (verified), peers: 98, service: slot_notifier
Mar 27 02:36:48.065 INFO New block received                      root: 0xd0b7e3ef518d862ef8f008c4766eb4945b9a7908045ba74e3e837b92c153273d, slot: 8723582
Mar 27 02:36:53.001 INFO Synced                                  slot: 8723582, block: 0xd0b7…273d, epoch: 272611, finalized_epoch: 272609, finalized_root: 0x9ef2…2191, exec_hash: 0x8830…90a1 (verified), peers: 98, service: slot_notifier
Mar 27 02:37:01.530 INFO New block received                      root: 0x32f040de819549fe2eca8d2c01c15b1bf97fe5dde6e4d7c0e030e04d357bc66f, slot: 8723583
Mar 27 02:37:05.001 INFO Synced                                  slot: 8723583, block:    …  empty, epoch: 272611, finalized_epoch: 272609, finalized_root: 0x9ef2…2191, exec_hash: 0x8830…90a1 (verified), peers: 99, service: slot_notifier
Mar 27 02:37:08.001 WARN Did not advance head state              reason: Err(HeadMissingFromSnapshotCache(0xd0b7e3ef518d862ef8f008c4766eb4945b9a7908045ba74e3e837b92c153273d)), service: state_advance
Mar 27 02:37:16.302 WARN Snapshot cache miss for blob verification, index: 4, block_root: 0x0f2c…7e22, service: beacon
Mar 27 02:37:16.357 WARN Snapshot cache miss for blob verification, index: 5, block_root: 0x0f2c…7e22, service: beacon
Mar 27 02:37:16.361 WARN Snapshot cache miss for blob verification, index: 0, block_root: 0x0f2c…7e22, service: beacon
Mar 27 02:37:16.383 WARN Snapshot cache miss for blob verification, index: 3, block_root: 0x0f2c…7e22, service: beacon
Mar 27 02:37:16.473 WARN Snapshot cache miss for blob verification, index: 2, block_root: 0x0f2c…7e22, service: beacon
Mar 27 02:37:16.518 WARN Snapshot cache miss for blob verification, index: 1, block_root: 0x0f2c…7e22, service: beacon
Mar 27 02:37:17.001 INFO Synced                                  slot: 8723584, block:    …  empty, epoch: 272612, finalized_epoch: 272610, finalized_root: 0xb6cc…d0ff, exec_hash: 0x8830…90a1 (verified), peers: 99, service: slot_notifier
Mar 27 02:37:20.001 WARN Did not advance head state              reason: Err(HeadMissingFromSnapshotCache(0xd0b7e3ef518d862ef8f008c4766eb4945b9a7908045ba74e3e837b92c153273d)), service: state_advance

Mar 27 19:08:41.001 INFO Synced                                  slot: 8728541, block:    …  empty, epoch: 272766, finalized_epoch: 272764, finalized_root: 0x5141…7838, exec_hash: 0x8724…cec5 (verified), peers: 99, service: slot_notifier
Mar 27 19:08:44.001 WARN Did not advance head state              reason: Err(HeadMissingFromSnapshotCache(0x34622cb379ef7ea5b9d123a4a702a6c261a19b38d0f58a0f4ec033586989cfc8)), service: state_advance
Mar 27 19:08:48.114 INFO New block received                      root: 0x3387bd46c1f14b3e705470197ac76da1ee9e0971c5d6b09d97dcaa207aa79616, slot: 8728542
Mar 27 19:08:53.001 INFO Synced                                  slot: 8728542, block:    …  empty, epoch: 272766, finalized_epoch: 272764, finalized_root: 0x5141…7838, exec_hash: 0x8724…cec5 (verified), peers: 99, service: slot_notifier
Mar 27 19:08:56.001 WARN Did not advance head state              reason: Err(HeadMissingFromSnapshotCache(0x34622cb379ef7ea5b9d123a4a702a6c261a19b38d0f58a0f4ec033586989cfc8)), service: state_advance
Mar 27 19:09:02.413 INFO New block received                      root: 0x7ef3f0f0cec4a54d1b88dbc4eb4bec0a774c4c5db9876009cd22aa49385f1746, slot: 8728543
Mar 27 19:09:05.001 INFO Synced                                  slot: 8728543, block:    …  empty, epoch: 272766, finalized_epoch: 272764, finalized_root: 0x5141…7838, exec_hash: 0x8724…cec5 (verified), peers: 100, service: slot_notifier
Mar 27 19:09:08.001 WARN Did not advance head state              reason: Err(HeadMissingFromSnapshotCache(0x34622cb379ef7ea5b9d123a4a702a6c261a19b38d0f58a0f4ec033586989cfc8)), service: state_advance
Mar 27 19:09:17.001 INFO Synced                                  slot: 8728544, block:    …  empty, epoch: 272767, finalized_epoch: 272765, finalized_root: 0xe1b3…1405, exec_hash: 0x8724…cec5 (verified), peers: 98, service: slot_notifier
Mar 27 19:09:24.313 WARN Snapshot cache miss for blob verification, index: 1, block_root: 0x63f5…0c8c, service: beacon
Mar 27 19:09:24.476 WARN Snapshot cache miss for blob verification, index: 3, block_root: 0x63f5…0c8c, service: beacon
Mar 27 19:09:24.476 WARN Snapshot cache miss for blob verification, index: 5, block_root: 0x63f5…0c8c, service: beacon
Mar 27 19:09:24.638 WARN Snapshot cache miss for blob verification, index: 2, block_root: 0x63f5…0c8c, service: beacon
Mar 27 19:09:24.704 WARN Snapshot cache miss for blob verification, index: 0, block_root: 0x63f5…0c8c, service: beacon
Mar 27 19:09:24.779 WARN Snapshot cache miss for blob verification, index: 4, block_root: 0x63f5…0c8c, service: beacon
Mar 27 19:09:26.290 WARN Snapshot cache miss for blob verification, index: 1, block_root: 0x89ce…bb32, service: beacon
Mar 27 19:09:29.115 INFO Synced                                  slot: 8728545, block:    …  empty, epoch: 272767, finalized_epoch: 272765, finalized_root: 0xe1b3…1405, exec_hash: 0x8724…cec5 (verified), peers: 98, service: slot_notifier

**Comment by michaelsproul** [comment]
See:

- https://github.com/sigp/lighthouse/issues/5474

Fix coming soon in v5.1.3, closing as duplicate
