### ISSUE TITLE
Quick sync startup from checkpoint failed

### ISSUE THREAD

**Issue by chengxingxi** [sigp/lighthouse#5505]
## Description

Failed to start beacon node

## Version

version：Lighthouse v4.6.0-1be5253
command：
 ./lighthouse bn
--network mainnet \
  --execution-endpoint http://localhost:8551 \
  --execution-jwt /secrets/jwt.hex \
  --checkpoint-sync-url https://mainnet.checkpoint.sigp.io \
  --http
  --datadir  xxx
![image](https://github.com/sigp/lighthouse/assets/109021530/d692e144-d3d4-4bc5-88f3-e028985482a2)

**Comment by michaelsproul** [comment]
you need Lighthouse v5 or newer for mainnet

**Comment by chengxingxi** [comment]
> you need Lighthouse v5 or newer for mainnet

I upgraded the lighthouse version to 5.1.3, but it still cannot start.
![image](https://github.com/sigp/lighthouse/assets/109021530/85426c6e-1918-4348-8fa6-964bdc44ba2d)

**Comment by michaelsproul** [comment]
how many checkpoint sync URLs have you tried?

could there be something blocking the request, like a firewall?

**Comment by chengxingxi** [comment]
> how many checkpoint sync URLs have you tried?
> 
> could there be something blocking the request, like a firewall?

I tried all mainnets except Nimbus.
![image](https://github.com/sigp/lighthouse/assets/109021530/22c81fb8-f1eb-4a56-8223-7a4f78d320ed)
I have successfully started it before, but after deleting all the previously downloaded data, problems occurred when I started it again. The configuration in the middle has not changed. By the way, I started it in a non-pledged form, and there is the following content in the command line:
--disable-deposit-contract-sync

**Comment by chong-he** [comment]
Can you share the full command you start Lighthouse? The error code is `Unexpected EOF`. Do you see the same error code when you use a different checkpoint link?

**Comment by chengxingxi** [comment]
> Can you share the full command you start Lighthouse? The error code is `Unexpected EOF`. Do you see the same error code when you use a different checkpoint link?

Ok.
version：Lighthouse v5.1.3-3058b96
command：
./lighthouse bn
--network mainnet
--execution-endpoint http://localhost:8551/
--execution-jwt /secrets/jwt.hex
--checkpoint-sync-url https://mainnet.checkpoint.sigp.io/
--disable-deposit-contract-sync
--http
--datadir xxx
I changed the checkpoint link and still got this error, as shown below。The top of the picture is the command I used to start the beacon node.
![image](https://github.com/sigp/lighthouse/assets/109021530/1e45aed6-a977-4cbd-9ce4-7e435e426bc7)


The picture below is the version information
![image](https://github.com/sigp/lighthouse/assets/109021530/6c4bfc19-6a8b-4ee0-80bb-5b314545124b)

**Comment by chong-he** [comment]
Can you try to remove the ending slash in the url? i.e., `--checkpoint-sync-url https://mainnet.checkpoint.sigp.io`

**Comment by chengxingxi** [comment]
> 您可以尝试删除网址中的结尾斜杠吗？ IE，`--checkpoint-sync-url https://mainnet.checkpoint.sigp.io`

There is no slash at the end of my command line, but there is a slash in the error message URL.

**Comment by chong-he** [comment]
That's strange. it should work and I just try that the checkpoint sync works. Do you have firewall blocks the connection as @michaelsproul sproul suggested?

Can you see if a simple command like below still return the same error:
` ./lighthouse bn --network mainnet --checkpoint-sync-url https://beaconstate.ethstaker.cc --purge-db`

**Comment by chengxingxi** [comment]
Yes, still the same error.
![image](https://github.com/sigp/lighthouse/assets/109021530/901305bd-819b-4707-98a0-df15644badc7)

**Comment by chengxingxi** [comment]
> Yes, still the same error. ![image](https://private-user-images.githubusercontent.com/109021530/318438183-901305bd-819b-4707-98a0-df15644badc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzYxMDIsIm5iZiI6MTcxMTk3NTgwMiwicGF0aCI6Ii8xMDkwMjE1MzAvMzE4NDM4MTgzLTkwMTMwNWJkLTgxOWItNDcwNy05OGEwLWRmMTU2NDRiYWRjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMjUwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzliMjg1ZTY1OGJjNDNmMTQ1ZTcwMDk4ZDA0MzIyMjA0MmZkYmVhMjFiNjcyNjQ0NjE5MTkxYTJjYmE3OWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C5hsqTLtdIx8d-KbD717XDXF2WNWLrDEIWjnNkg8hJA)



> That's strange. it should work and I just try that the checkpoint sync works. Do you have firewall blocks the connection as @michaelsproul sproul suggested?
> 
> Can you see if a simple command like below still return the same error: ` ./lighthouse bn --network mainnet --checkpoint-sync-url https://beaconstate.ethstaker.cc --purge-db`

Yes, still the same error.
![image](https://github.com/sigp/lighthouse/assets/109021530/901305bd-819b-4707-98a0-df15644badc7)

**Comment by chengxingxi** [comment]
> That's strange. it should work and I just try that the checkpoint sync works. Do you have firewall blocks the connection as @michaelsproul sproul suggested?
> 
> Can you see if a simple command like below still return the same error: ` ./lighthouse bn --network mainnet --checkpoint-sync-url https://beaconstate.ethstaker.cc --purge-db`

Yes, still the same error.
![image](https://github.com/sigp/lighthouse/assets/109021530/901305bd-819b-4707-98a0-df15644badc7)

**Comment by chong-he** [comment]
It seems to be that something is blocking the connection. Do you have another internet connection option available? Try another ISP option if there is

**Comment by michaelsproul** [comment]
@chengxingxi You can see what `curl` shows with this request, which is similar to what Lighthouse is trying to do.

```
curl -v -H "Accept: application/json" "https://mainnet.checkpoint.sigp.io/eth/v2/beacon/blocks/finalized"
```

As @chong-he says, it looks like a problem with your internet connection.

**Comment by chengxingxi** [comment]
> @chengxingxi您可以看到`curl`此请求显示的内容，这与 Lighthouse 尝试做的类似。
> 
> ```
> curl -v -H "Accept: application/json" "https://mainnet.checkpoint.sigp.io/eth/v2/beacon/blocks/finalized"
> ```
> 
> 作为@chong-he说，您的互联网连接似乎有问题。
The output result is like this：
![image](https://github.com/sigp/lighthouse/assets/109021530/bafd5d35-3cfb-42f3-8218-c0a64d231873)

**Comment by chong-he** [comment]
The connection is stopped. The curl should return a long data with block info. From your screenshot it seems to indicate a connection to localhost (127.0.0.0)?  

Do you have another internet option available? Try that.

**Comment by chengxingxi** [comment]
> The connection is stopped. The curl should return a long data with block info. From your screenshot it seems to indicate a connection to localhost (127.0.0.0)?
> 
> Do you have another internet option available? Try that.

Thank you, the node started normally after I changed the network.
I also want to ask a question. I used snapshot synchronization mode for almost a week, and the geth client kept displaying "Post-merge network, but no beacon client seen. Please launch one to follow the chain!" while the lighthouse client kept outputting. "INFO Searching for peers current_slot: 8768669, head_slot: 8768608, finalized_epoch: 274019, finalized_root: 0x581b…ef7e, peers: 1, service: slot_notifier" and similar content.
When I use the eth.syncing command to check, it shows that the current block is 0, as shown below.And I check that 1.7T of data has been downloaded. I check the Ethereum official website and it shows that using geth to synchronize in snapshot mode requires about 500G of hard disk size. . How should I check the downloaded data and know the progress of synchronization?
![image](https://github.com/sigp/lighthouse/assets/109021530/d9daa0f3-4568-4aa5-85b8-773d37b84203)

**Comment by chong-he** [comment]
Looks like the sync is not progressing. Do you have peers on geth and Lighthouse? If you view the geth and Lighthouse logs you can see the sync progress

**Comment by chengxingxi** [comment]
> Looks like the sync is not progressing. Do you have peers on geth and Lighthouse? If you view the geth and Lighthouse logs you can see the sync progress

The beacon node has two log files,
The content of discv5 is as follows:
![image](https://github.com/sigp/lighthouse/assets/109021530/562d22ea-9307-4477-822f-312be6f0a4ff)
The content of libp2p is as follows:
![image](https://github.com/sigp/lighthouse/assets/109021530/bedef2fa-4887-4982-b9aa-28fd99c8df34)
It seems like they are reporting errors and not synchronizing properly. geth did not find the log file

**Comment by chong-he** [comment]
How did you start Lighthouse and Geth? Please switch over to Discord for troubleshooting: https://discord.gg/cyAszAh

**Comment by chengxingxi** [comment]
> How did you start Lighthouse and Geth? Please switch over to Discord for troubleshooting: https://discord.gg/cyAszAh

The commands to start lighthouse are the same as before.
geth command:
geth --cache 4096
--authrpc.addr localhost
--authrpc.port 8551
--authrpc.vhosts localhost
--authrpc.jwtsecret /secret/jwt.hex
--datadir /private/mux/ethereum

**Comment by chong-he** [comment]
When you start geth it should show you the logs, post some logs and also Lighthouse beacon logs

**Comment by michaelsproul** [comment]
Closing as inactive. Feel free to reopen with more logs
