### ISSUE TITLE
Justified block has an invalid execution payload

### ISSUE THREAD

**Issue by milli** [sigp/lighthouse#5508]
Gave me an unrecoverable error after running fine for weeks on version 5.1.1 release.  Using reth v0.2.0-beta.3 as execution layer.

```
$ git log
commit 2a3c709f8ceec4d47c1934446511660c429fe90a (HEAD -> stable, tag: v5.1.1, origin/stable, origin/maxeb, origin/HEAD)
Author: Michael Sproul <michael@sigmaprime.io>
Date:   Tue Mar 12 14:42:15 2024 +1100

    Release v5.1.1 (#5396)

    * Release v5.1.1
 
```

Log file:
[hardcopy.txt](https://github.com/sigp/lighthouse/files/14831007/hardcopy.txt)

**Comment by michaelsproul** [comment]
This is a Reth issue. Either Reth's database is corrupt (most likely) or there's a bug in Reth's block validation logic. There seems to be some chatter in the Reth Telegram group about issues with v0.2.0-beta.3

If you share Reth logs with them, they should be able to help you debug

**Comment by milli** [comment]
Thanks, abandoning reth for now.
