### ISSUE TITLE
Docker build failing on `x86_64_dev` since moving to the `c-kzg` from crate-io 

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#5572]
## Description

Our docker `x86_64_dev` cross build has been failing since moving to the crate-io version of `c-kzg` (https://github.com/sigp/lighthouse/pull/5542). We should fix this before the next release.

```
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/blst-0.3.11/build.rs:173:25:
Cannot compile with both \`portable\` and \`force-adx\` features
```

https://github.com/sigp/lighthouse/actions/runs/8639102912/job/23684787522

**Comment by pawanjay176** [comment]
We can remove `force-adx` since the portable build should detect it on runtime and use it if available.
cc @michaelsproul

**Comment by michaelsproul** [comment]
Yeah, agreed. We could go full steam ahead with Anton's change:

- https://github.com/sigp/lighthouse/pull/5489

I think the alternative would be to compile czkg with `no-default-features` so that it doesn't turn on `blst/portable`: https://github.com/ethereum/c-kzg-4844/blob/1ef67c17bf659547749750e6ebaaf09563e0149d/Cargo.toml#L21-L23

**Comment by antondlr** [comment]
> Yeah, agreed. We could go full steam ahead with Anton's change:
> 
> * [Use `portable` builds by default  #5489](https://github.com/sigp/lighthouse/pull/5489)
> 
> I think the alternative would be to compile czkg with `no-default-features` so that it doesn't turn on `blst/portable`: https://github.com/ethereum/c-kzg-4844/blob/1ef67c17bf659547749750e6ebaaf09563e0149d/Cargo.toml#L21-L23

fyi I split out the docker and release/binaries parts into PR's #5614 and #5615 
the docker one (#5614) can thus be merged without (too much) worries of breaking the release flow.

**Comment by jimmygchen** [comment]
Fixed in https://github.com/sigp/lighthouse/pull/5614 🎉
