### ISSUE TITLE
[Discv5] Update table connection status every ping

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#560]
## Description

Currently, a Node's status in the routing table is only updated when a new session is established. The status should be updated every time a PING returns to increase it's liveness in the local view of the DHT.

**Comment by b-m-f** [comment]
Hi, can I pick this one up? Would be free to do it on tuesday :)

**Comment by AgeManning** [comment]
Hey,

This was like a placeholder issue to remind myself to add this is. The changes will actually be in our `rust-libp2p` fork on the `discv5` branch here: https://github.com/sigp/rust-libp2p/tree/discv5/misc/discv5

There is a function, `connection_updated` https://github.com/sigp/rust-libp2p/blob/discv5/misc/discv5/src/behaviour.rs#L625
which needs to get called when we receive a successful `PING`. 

When we get at PONG, this function should be called:
https://github.com/sigp/rust-libp2p/blob/discv5/misc/discv5/src/behaviour.rs#L310

I think all we need to do is use the connection_updated function in this function. 

If you are interested in understanding how this all works, it would also be useful to have a few tests to check that PING's update the state in the DHT (which would involve looking at the buckets construction). 

Let me know if you need anything further for this :)

**Comment by b-m-f** [comment]
Hi @AgeManning,

I have opened https://github.com/sigp/rust-libp2p/pull/6 and put two questions in there:
- Should the `connection_updated` also be called when ENR sequence that was received? Or will this be done when the requested new ENR is returned?
- Could it happen that a PING is received for which no ENR can be found?

And Id be happy to learn more and implement some tests. Should these go into the same file with the normal Rust testing methodology?
How would you say I should go about testing this? Set up all the necessary environment and then fake a PING and observe the DHT for the correct change? Or is there an easier way I dont see yet?

**Comment by AgeManning** [comment]
Responded on the rust-libp2p repo :)

**Comment by b-m-f** [comment]
@AgeManning guess this one can be closed now? Or should the revision number in https://github.com/sigp/lighthouse/blob/2399b9bbe0e521fa092fef8bcf592b7b82f7ce3f/beacon_node/eth2-libp2p/Cargo.toml be updated.

**Comment by AgeManning** [comment]
Yep, this is complete. 
There are number of updates in the rust-libp2p crate that we will be updating all in one hit.  We've made some changes to gossipsub also. 
I have a large network update, which will include all of these.

Thanks for the help :)
