### ISSUE TITLE
Add "push_leaf" method to merkle_proof::MerkleTree

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#561]
## Description

Add a method to [`merkle_proof::MerkleTree`](https://github.com/sigp/lighthouse/blob/96a327fe500fa762fd3aa3c70fa2a17eb2c4baed/eth2/utils/merkle_proof/src/lib.rs#L28-L42) to improve efficiency.

## Detail

When we're [producing the deposit contract merkle tree](https://github.com/sigp/lighthouse/blob/7eb82125ef1652871ada2d72649082f33e4a04bd/beacon_node/beacon_chain/src/beacon_chain_builder.rs#L212-L233) we need to capture the state of the merkle tree as each deposit is added.

Presently, we can construct a merkle tree from a list of roots but we cannot add a root/leaf after initialization. This results in creating many mostly-identical trees over and over again.

If we had a `MerkleTree::push_leaf(&mut self, leaf: Hash256, depth: usize)` method, we could avoid re-creating the tree.

## Steps to resolve

- Add the `push_leaf` method to `MerkleTree`, ensuring that the root and internal nodes are updated on each call.

Just adding this method is sufficient for this PR, there's no need to go upstream and try and optimize any uses of `MerkleTree` yet.

**Comment by pscott** [comment]
Oh lol, I was already working on this particular topic. I just finished the PR, and now I see this issue. Welp, there you go : https://github.com/sigp/lighthouse/pull/563

Hope it helps! :)

**Comment by paulhauner** [comment]
Re-opening because #563 has been reverted.

**Comment by pscott** [comment]
@paulhauner this can be closed
