### ISSUE TITLE
Will lighthouse return an empty list when fetching an expired blob?

### ISSUE THREAD

**Issue by zhiqiangxu** [sigp/lighthouse#5640]
We're talking about how should op stack deal with expired blobs [here](https://github.com/ethereum-optimism/optimism/pull/10269). Currently op stack was expecting an error to be returned for expired blobs. `Prysm` will return `empty list/status=200` for expired blobs. What about lighthouse?

I've read the code for `beacon/blob_sidecars/{block_id}`, it seems lighthouse will also return an empty list when fetching an expired blob.

Just wanna confirm with the official team:)

**Comment by michaelsproul** [comment]
Yeah at the moment Lighthouse will also return an empty list.

I don't really like this behaviour though, because it combines the cases for (1) no blobs ever existed at this slot and (2) there were blobs at this slot but we've deleted them.

**Comment by dapplion** [comment]
Worth it to raise the issue in the beacon APIs specs. There has been similar discussions for the case of missed slots. Would having different HTTP status code serve your use case?

**Comment by zhiqiangxu** [comment]
I think so, [here](https://github.com/ethereum-optimism/optimism/blob/54eb4161dc0d2dad7e6840b788ef9704a0f5c721/op-service/sources/l1_beacon_client.go#L69-L93) is how op stack is handling the response.

**Comment by michaelsproul** [comment]
I think we should just return a 404 here. I'll raise a PR.

**Comment by michaelsproul** [comment]
PR here:

- https://github.com/sigp/lighthouse/pull/6331

**Comment by michaelsproul** [comment]
The fix will be in the next release - v6.0.0
