### ISSUE TITLE
UI For Lighthouse

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#576]
## Description

*This is a major task and is listed as a `good-first-issue` mainly to highlight the issue amongst new contributors who may be looking at the project without a rust background*

We are interested in developing a UI that interfaces with the beacon node and validator client. This would have simple functionality, such as creating validator keypairs, exiting validators, reporting the state of local validators (i.e balance, status, active/inactive) and show some metrics from the beacon node (state of the network, connected peers, total validators, etc).

The validator client and beacon node will expose HTTP methods to facilitate all the core functionality, the UI will simply interface with the exposed methods. 

Ideally, this will be written using React native. 

If you are interested in this issue, please reach out to the team :).

**Comment by FawadHa1der** [comment]
I am pretty new to RUST. But I do want to eventually work on it. I have more of a background in Swift, Objective C, C++, Java script etc. I am willing to get started on this. Can I get more details on this?

**Comment by johnsBeharry** [comment]
Would love to collaborate on this also! If you don't mind working together.

@AgeManning react-native would be for mobile iOS and Android though. Do you mean React + Electron as a desktop app?

**Comment by AgeManning** [comment]
Hey guys, 

I was thinking lighthouse could spin up it's own local http server initially, rather than using Electron. 

We currently are in the process of engaging an interested company to help us build this out. So perhaps it would be best to wait to see how this progresses first.

**Comment by johnsBeharry** [comment]
@AgeManning, most of the work would be on the UI anyway so complexity is negligible between Electron or the local server.

Is there a bidding/rfp process then for this if other companies are involved? Cause I'd really really love to work on this and have a team at hand also.

**Comment by AgeManning** [comment]
We are putting together an RFP for this and will post it here as soon as it's complete.

**Comment by AgeManning** [comment]
Hi all, RFP is here: https://lighthouse.sigmaprime.io/ui-rfp.html

**Comment by paulhauner** [comment]
Closing this since the RfP process is complete and we have selected vendors :)
