### ISSUE TITLE
Endpoint `blob_sidecars` returns 200 and empty list for pruned blobs

### ISSUE THREAD

**Issue by sebastianst** [sigp/lighthouse#5807]
## Description

The `/eth/v1/beacon/blob_sidecars/{block_id}` endpoint seems to return 200 and an empty list of blob sidecars, instead of a 404, for pruned blobs. Is that intentional? I see that the [spec](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlobSidecars) doesn't say anything explicit about how to behave for pruned blobs.

## Version

Latest `v5.1.3`

## Present Behaviour

See description.

## Expected Behaviour

I would expect a 404 error when requesting a pruned blob. It isn't explicitly mentioned in the specs though.

## Steps to resolve

Either return 404 instead for pruned blobs, or maybe try to get this behavior explicitly document in the Beacon API specs.

**Comment by chong-he** [comment]
Thanks for raising the issue! 
There is a discussion here: https://github.com/sigp/lighthouse/issues/5640

**Comment by michaelsproul** [comment]
Closing as duplicate
