### ISSUE TITLE
Support Snappy compression to the RPC

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#581]
## Description

Snappy compression needs to be added to the Eth2 rpc as specified in the [networking specification](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/networking/p2p-interface.md). 

This involves adding the extra protocol ids and prioritising the compression protocols over their non-compressed counter-parts.

**Comment by b-m-f** [comment]
I identified https://github.com/sigp/lighthouse/blob/9aedb12bfc092be95880cdbe4500a1c7768ff2d5/beacon_node/network/src/service.rs#L175 as a place to apply the compression.

Every message that is published will then be snappy compressed. If you agree Id open up a PR using the rust-snappy crate for the algorithm

**Comment by AgeManning** [comment]
For the compression, we need to support a new `ProtocolId`. 

We are using libp2p, essentially, how this works, is clients support a number of strings called `ProtocolId`s. Libp2p, based on the supported strings a client supports, will negotiate a protocol to communicate over. 

The [Req/Resp](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/networking/p2p-interface.md#the-reqresp-domain) defines the `ProtocolId` that we want to support. Specifically, the `Encoding` section. 

To support Snappy, we want to support the protocol id, that ends with `ssz_snappy`. 

Let me explain roughly how these work in Lighthouse. 
The Req/Resp "protocol" exists in this directory: https://github.com/sigp/lighthouse/tree/master/beacon_node/eth2-libp2p/src/rpc

The `ProtocolId`'s that we currently support are here (in order that we negotiate them): 
https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/protocol.rs#L38

These are just strings, see the helper struct immediately below. For `snappy` we would need to add the same protocol for each method, replacing the `ssz` string with `ssz_snappy`. The `ssz_snappy` Id's should be placed before their `ssz` counterparts to prioritise the negotiation. This way, we will choose snappy compression if another clients supports it and if not, will fallback to standard ssz encodings. 

Also, we would need to add the extra protocols to this list: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/protocol.rs#L170

Once we have added protocols here, we need to tell Lighthouse what to do when another client is trying to negotiate one of these protocols. 
This happens here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/protocol.rs#L121 (for inbound negotiations)

and here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/protocol.rs#L209 (for outbound requests)

In each of these functions they set up a specific `Codec` (https://docs.rs/tokio-io/0.1.3/tokio_io/codec/index.html) of how to encode/decode packets using these negotiated protocols. 

We only have the ssz codec at the moment, see here: https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/codec/ssz.rs

I know this part can be confusing and I've not got around to documenting the codecs. But these describe how to encode/decode raw bytes, as they stream in from the network. We are UVI-length prefixing bytes. Also the ssz-codec in many parts doesn't actually ssz-encode or decode, because for reason's i won't go into here, we want to do this at another level. 

I imagine we can just copy the ssz-codec and make an `ssz-snappy-codec` or something similar. This should do almost the same functionality as ssz-encoding but with snappy compression. 

After writing this out, I realise that this logic may seem quite complicated and hard to track as some of the logic flows occur in libp2p. If this doesn't make sense, feel free to ask me further questions, or perhaps another issue not so integrated with the libp2p stack may be easier to follow.

**Comment by b-m-f** [comment]
Hi @AgeManning,

started coding on this again and I have a question regarding the stream directions.

There are both Outbound and Inbound en- & decoding on the Codec, which confuses me a bit. 

My idea was to decode only on received traffic and to only encode outbound.

So snappy compression would apply to `SSZSnappyOutboundCode.encode` and `SSZSnappyInboundCode.decode`. 

Or am I missing something here and it should be implemented on all 4 cases?

**Comment by AgeManning** [comment]
Hey, 

Yeah I know this part is confusing. There are updates and comments in the `network-spec-update` branch, which I recommend working from (this will be in master very soon). 

The reason there are four, is because the encoding and decoding is different depending on whether we are receiving an RPC request or sending one. 

More specifically, 

An `InboundCodec` deals with requests from an external peer. The `decode()` decodes an RPC Request coming in and the `encode()` encodes an RPC Response. 

An `OutboundCodec` deals with requests that we send to peers. The `encode()` encodes an RPC Request and the `decode()` decodes an RPC Response. 

There are four because the Requests and Responses are not symmetric in encoding/decoding

**Comment by AgeManning** [comment]
This is resolved in #866
