### ISSUE TITLE
Update Criterion

### ISSUE THREAD

**Issue by eserilev** [sigp/lighthouse#5819]
## Description

Our current version of criterion depends on clap 2.x, the new criterion version (0.5) depends on clap 4.x. In #5273 were upgrading clap to 4.x. We should upgrade Criterion to 0.5 so we can completely remove the clap 2.x dependency from our codebase

**Comment by michaelsproul** [comment]
I've started on this

**Comment by michaelsproul** [comment]
PR here:

- https://github.com/sigp/lighthouse/pull/5886

**Comment by eserilev** [comment]
Closed in #5886
