### ISSUE TITLE
Rebuild `lcli` only when it is updated

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#5861]
## Description
We recently updated CI to rebuild `lcli` every run, which adds ~3 minutes. We should be able to cache it most of the time but any PR that updates `lcli` needs to have it rebuilt, otherwise CI might break. 

Relevant PR: https://github.com/sigp/lighthouse/pull/5860

Issue and solution described here:
https://github.com/sigp/lighthouse/pull/5860#issuecomment-2136935124

**Comment by jimmygchen** [comment]
`lcli` build is no longer required by doppelganger tests (#5865), so we may be able to close this?

**Comment by realbigsean** [comment]
incredible
