### ISSUE TITLE
Potential leak of pending components in overflow cache

### ISSUE THREAD

**Issue by dapplion** [sigp/lighthouse#5892]
## Description

~60% of our fleet holds more than 10 items in the overflow cache

<img width="1517" alt="Screenshot 2024-06-05 at 12 46 20" src="https://github.com/sigp/lighthouse/assets/35266934/e0563187-ff48-4d01-9678-d79e0be90b30">

Some nodes reach the hundreds

<img width="1517" alt="Screenshot 2024-06-05 at 12 45 20" src="https://github.com/sigp/lighthouse/assets/35266934/99b92f9c-7a24-41d8-8953-77763b7b840c">

Pending components should be held at maximum until finality. Since mainnet is finalizing this is indicative of some leak or pruning issue

## Version

5.1.3

**Comment by jimmygchen** [comment]
Closed by #5895
