### ISSUE TITLE
why scripts/local_testnet/start_local_testnet.sh has two ./el_bootnode.sh

### ISSUE THREAD

**Issue by HowHsu** [sigp/lighthouse#5910]
## Description
scripts/local_testnet/start_local_testnet.sh build a local testnet, why booting two el_bootnode? and the second el_bootnode actually doesn't start because error of using same port as the first one...
```bash
execute_command_add_PID el_bootnode.log ./el_bootnode.sh                         
sleeping 3                                                                       
                                                                                 
execute_command_add_PID el_bootnode.log ./el_bootnode.sh                         
sleeping 1  
```

**Comment by michaelsproul** [comment]
The local testnet scripts have been completely overhauled in https://github.com/sigp/lighthouse/pull/5865. We have deleted the old scripts

**Comment by HowHsu** [comment]
> The local testnet scripts have been completely overhauled in #5865. We have deleted the old scripts

Nice work, but as a newbie, I'd like to stick to the old scripts for this period rather than learning a new framework(too much to learn...), just want to make sure: the current script works well and I can remove the second el_bootnode.sh command, right?

**Comment by michaelsproul** [comment]
yeah
