### ISSUE TITLE
Apply eth2.0-specs "config" to ChainSpec

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#592]
## Description

The eth2.0-specs repo has a [`configs`](https://github.com/ethereum/eth2.0-specs/tree/dev/configs) directory, which is represented by our `ChainSpec` and `EthSpec`. Let's call the struct that is inferred from these YAML files as the `SpecConfig` struct.
 
Presently, we do not have the functionality to parse a `SpecConfig`. It would be nice to parse it for:

- Ensuring the configs supplied in `ef_tests` are accurate (presently we only eyeball them).
- Transmitting the `SpecConfig` via the HTTP API, so consumers can know our spec versions (e.g., minimal or mainnet).
- Connecting to testnets that are specified in this format: https://github.com/ethereum/eth2.0-pm/pull/93 (additionally, creating these files when we defining our own testnets in this format).

## Steps to resolve

- Define a `SpecConfig` struct that contains these variables.
- Create a function which applies a `SpecConfig` to a `ChainSpec`
  - E.g., `fn apply_to_chain_spec(spec_config: SpecConfig, chain_spec: ChainSpec) -> ChainSpec`.
  - This function _must_ take into account an `EthSpec` and return an error if any of the variables in `SpecConfig` do not match the statics/constants in `EthSpec`.
- Create a function which derives a `SpecConfig` from a `(ChainSpec, impl EthSpec)`.
  - E.g., `fn spec_config<T: EthSpec>(spec: &ChainSpec) -> SpecConfig`
- Ensure that the `SpecConfig` can be serialized/deserialized to/from a [`configs`](https://github.com/ethereum/eth2.0-specs/tree/dev/configs) file. (Tip: use serde)

**Comment by pscott** [comment]
Working on it!
