### ISSUE TITLE
lighthouse fast sync with --checkpoint-sync-url not working 

### ISSUE THREAD

**Issue by Utatistics** [sigp/lighthouse#5947]
## Description
I am attempting to sync a Lighthouse beacon node on the Sepolia network with the command below, using a checkpoint sync URL for the option. However, I am encountering an error indicating that the content type returned by the checkpoint sync URL is not supported.

```
lighthouse bn \
  --network sepolia \
  --execution-endpoint http://localhost:8551 \
  --execution-jwt ~/geth-tutorial/jwtsecret \
  --checkpoint-sync-url https://sepolia.beaconstate.info \
  --http
```
## Version

Lighthouse Version: v4.0.1-a53830f

## Present Behaviour
Here's the error message mentioned above:

> WARN Remote BN does not support EIP-4881 fast deposit sync, error: Error fetching deposit snapshot from remote: ServerMessage(ErrorMessage { code: 406, message: "unsupported content-type: application/octet-stream", stacktraces: [] }), service: beacon
> CRIT Failed to start beacon node reason: Unable to parse SSZ: OffsetSkipsVariableBytes(392). Ensure the checkpoint-sync-url refers to a node for the correct network
> INFO Internal shutdown received reason: Failed to start beacon node
> INFO Shutting down.. reason: Failure("Failed to start beacon node")
> Failed to start beacon node
> 

Additionally, using `curl -I https://sepolia.beaconstate.info` returns:

> HTTP/2 200
> accept-ranges: bytes
> alt-svc: h3=":443"; ma=2592000
> content-type: text/html; charset=utf-8
> date: Tue, 18 Jun 2024 08:38:50 GMT
> server: Caddy
> content-length: 653
> 

With these, I understood that the URL returns content-type: text/html, which is not a valid format for the checkpoint sync data and therefore lighthouse is having trouble parsing it properly. (Correct me if I'm wrong) Finally, I have tried several other URLs listed [here](https://eth-clients.github.io/checkpoint-sync-endpoints/), but the results were the same.

## Expected Behaviour
The Lighthouse beacon node should successfully parse the checkpoint sync data and start syncing from the provided URL. The checkpoint sync URL should return data in a supported binary format, such as SSZ.

**Comment by michaelsproul** [comment]
Please try a more recent LH release. v4 is too old as it is pre-Deneb

**Comment by Utatistics** [comment]
Sorry, I was using the version embedded in the sample code in the [installation guide]( https://lighthouse-book.sigmaprime.io/installation-binaries.html)

This has fixed the problem, thank you.

**Comment by michaelsproul** [comment]
Oh, interesting. That's meant to just be an example, but we should probably keep that up to date with the major version.

Thanks!
