### ISSUE TITLE
Increase default max value for slasher database size to 512

### ISSUE THREAD

**Issue by jimmygchen** [sigp/lighthouse#5965]
## Description

The default max DB size is specified here:

https://github.com/sigp/lighthouse/blob/b0c374c1cabd7fd960b4dde9ec9b0b26a960ca0c/slasher/src/config.rs#L14

This is now insufficient and needs to be bumped to 512 Gb.

michael on discord:
> 256 is actually too small these days, you need to bump it to ~512ish

In addition to the default value, the docs / book needs to be updated as well.

**Comment by chong-he** [comment]
I have updated the doc since I have a PR on updating the doc now:
https://github.com/sigp/lighthouse/pull/5934/commits/e6890f121fe90b9e47d3488a0c44296b0e8d239a

**Comment by chong-he** [comment]
Also update the default max db size: 
[1c72524](https://github.com/sigp/lighthouse/pull/5934/commits/1c72524464d5e90eed0c49eccf417caccc1e21fe)

**Comment by chong-he** [comment]
Closed by #5934
