### ISSUE TITLE
local-testnet issue

### ISSUE THREAD

**Issue by lzmrd** [sigp/lighthouse#5991]
## Description
I followed the README file of local-testnet and when I run ./start_local_testnet.sh I get the following error:

![image](https://github.com/sigp/lighthouse/assets/84910461/00192a9d-5c66-4c8e-8a32-1cfa8004b147)
## Version

Lighthouse v5.1.3-3058b96+
rustup 1.27.1 (54dd3d00f 2024-04-24)

**Comment by eserilev** [comment]
try restarting your docker service, that should resolve this issue

**Comment by chong-he** [comment]
Facing the same issue, and @jimmygchen pointed out that it is due to the old Kurtosis version used. I was on `0.89.13`.

Can you check the version you are using with `kurtosis version`. If it is old, try updating to `0.90.1`:
https://docs.kurtosis.com/upgrade/#iii-restart-the-engine

**Comment by lzmrd** [comment]
Great! I fixed upgrading Kurtosis version to 0.90.1 as you suggested.
thank you very much!
