### ISSUE TITLE
Tidy Eth2Config generation at runtime

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#602]
## Description

Presently, when the `lighthouse` binary is started an `Environment` is created which contains an `Eth2Config`.

Then, [this code](https://github.com/sigp/lighthouse/blob/bdae7e01a7d2b7cbc9bd760f139e4f1c8e3c4487/beacon_node/src/lib.rs#L59-L65) ignores the `environment.eth2_spec` and replaces the `Eth2Config` in it's local context.

This means that there's no guarantee of consistency of the `Eth2Config` from an `Environment`.

## Steps to resolve

- Pull out the code that generates the `Eth2Config` from CLI args (`ArgMatches`) (see [`config.rs`])(https://github.com/sigp/lighthouse/blob/eth1/beacon_node/src/config.rs) and place it in it's own function in the `environment` crate.

## Notes

This issue is only valid after #542 is merged.

**Comment by ackintosh** [comment]
Hi, I'm addressing this issue, will file a PR to close this. 😃
