### ISSUE TITLE
Deprecate beacon node pre-merge healthy conditions 

### ISSUE THREAD

**Issue by ferranbt** [sigp/lighthouse#6057]
## Description

Deprecate the [pre-merge conditions](https://github.com/sigp/lighthouse/blob/stable/beacon_node/beacon_chain/src/beacon_chain.rs#L6445-L6451) to determine the health of the beacon chain. I am not sure if those checks are useful anymore, specially given that other pre-merge features are being deprecated as well.

For my use case, I am trying to deploy a local devnet for [rbuilder](https://github.com/flashbots/rbuilder) but the proposer waits a few epochs before making the external query to the builder to request the block because the beacon node is waiting for the merge epoch to get finalised.

**Comment by michaelsproul** [comment]
I think this was already meant to be fixed by:

- https://github.com/sigp/lighthouse/pull/5834

Are you running v5.2.x or an older version?

**Comment by ferranbt** [comment]
I am running `v5.1.3`. Let me try with v5.2.

**Comment by michaelsproul** [comment]
v5.2.x should be good, that PR was merged since v5.1.3

**Comment by ferranbt** [comment]
Updated to `v5.2.1` and it works! Thank you very much!
