### ISSUE TITLE
the docs on lighthouse-book have been out date.

### ISSUE THREAD

**Issue by yaanhyy** [sigp/lighthouse#607]
## Description

on the page http://lighthouse-book.sigmaprime.io/simple-testnet.html.

the command is out data, beacom_node and validator_client are merged to lighthouse, so:
./beacon_node testnet -f recent 8
should change to:
./lighthouse bn testnet -f recent 8

./validator_client testnet -b insecure 0 8
should change to:
./lighthouse vc testnet -b insecure 0 8
etc...

**Comment by paulhauner** [comment]
I have updated the website. Thanks for bringing this up!
