### ISSUE TITLE
`lighthouse account validator` subcommands are not displaying CLI help text

### ISSUE THREAD

**Issue by chong-he** [sigp/lighthouse#6075]
## Description

Since 5.2.0, `lighthouse account validator` subcommands are not displaying the help text. For example, `lighthouse account validator exit --help` returned:

`error: unexpected argument '--help' found`

Similar for `lighthouse account validator import --help` and other subcommands

## Version

5.2.0 and 5.2.1

I will look into fixing this

**Comment by eserilev** [comment]
nice catch! if theres anything I can do to help here, please let me know

**Comment by chong-he** [comment]
Closed by #6091
