### ISSUE TITLE
Critical Task Panic with InvalidCertificate Error on Lighthouse v5.2.1-9e12c21+

### ISSUE THREAD

**Issue by 7feilee** [sigp/lighthouse#6088]
### Description

A critical task panic occurs when starting the Lighthouse beacon node. The error message indicates an issue with a certificate, specifically an `InvalidCertificate(Other(OtherError(UnsupportedCriticalExtension)))`.
Here is the link to the similar issue raised on GitHub: [Issue #5487](https://github.com/libp2p/rust-libp2p/issues/5487)
### Version

**Lighthouse Version**: v5.2.1-9e12c21+
**Rust Version**: rustc 1.79.0 (129f3b996 2024-06-10)
**Build Type**: Building from `stable`.

### Present Behaviour

When starting the beacon node with the command:

```sh
./target/maxperf/lighthouse bn \
    --network mainnet \
    --execution-endpoint http://localhost:8551 \
    --execution-jwt /home/test/rust/jwt.hex \
    --checkpoint-sync-url https://mainnet.checkpoint.sigp.io \
    --disable-deposit-contract-sync
```

The node starts initializing but then crashes with a critical task panic due to an invalid certificate error. The relevant log output is as follows:

```
Jul 13 21:35:31.545 CRIT Task panic. This is a bug! advice: Please check above for a backtrace and notify the developers, backtrace: 
0: lighthouse::run::{{closure}}
1: std::panicking::rust_panic_with_hook
2: std::panicking::begin_panic_handler::{{closure}}
3: std::sys_common::backtrace::__rust_end_short_backtrace
4: rust_begin_unwind
5: core::panicking::panic_fmt
6: core::result::unwrap_failed
7: libp2p_quic::config::Config::new
8: lighthouse_network::service::Network<AppReqId,E>::new::{{closure}}
9: network::service::NetworkService<T>::build::{{closure}}
10: beacon_node::ProductionBeaconNode<E>::new::{{closure}}
11: task_executor::TaskExecutor::spawn_handle::{{closure}}
12: tokio::runtime::task::raw::poll
13: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
14: tokio::runtime::task::raw::poll
15: std::sys_common::backtrace::__rust_begin_short_backtrace
16: core::ops::function::FnOnce::call_once{{vtable.shim}}
17: std::sys::pal::unix::thread::Thread::new::thread_start
18: <unknown>
19: <unknown>,
message: Server cert key DER is valid; qed: InvalidCertificate(Other(OtherError(UnsupportedCriticalExtension))), 
location: /home/test/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libp2p-tls-0.4.0/src/lib.rs:80:10
```

### Expected Behaviour

Lighthouse should start without panicking and run the beacon node as expected, handling the certificates correctly without causing a critical task panic.

**Comment by michaelsproul** [comment]
Hmm, that seems bad. Does `--disable-quic` prevent the panic?

Can you give a few more details about the OS that you're on and whether you have any custom certificates installed? We've not seen this on any other machines

**Comment by ackintosh** [comment]
I couldn't reproduce the error with the `stable` branch (building with the `make` command) as the Cargo.lock points to rustls v0.23.8.

Then, I did `cargo update`, built and ran again, the `InvalidCertificate` error was reproduced, because rustls was bumped to v0.23.11.

@7feilee Have you run `cargo update`?

**Comment by michaelsproul** [comment]
Alternatively, make sure you build the binary with `--locked` to use the Cargo.lock file

**Comment by 7feilee** [comment]
> I couldn't reproduce the error with the `stable` branch (building with the `make` command) as the Cargo.lock points to rustls v0.23.8.
> 
> Then, I did `cargo update`, built and ran again, the `InvalidCertificate` error was reproduced, because rustls was bumped to v0.23.11.
> 
> @7feilee Have you run `cargo update`?

I did cargo update, built, and ran again, the InvalidCertificate error was reproduced because rustls was bumped to v0.23.11.

**Comment by 7feilee** [comment]
> Alternatively, make sure you build the binary with `--locked` to use the Cargo.lock file

Great, That solved the newest `rustls` dependence problem.
