### ISSUE TITLE
Support gzip encoding on eth1 http json rpc

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#616]
## Description

Presently we do not handle gzip encoding when connecting to an eth1 peer. Gzip is commonly used by public Ethereum nodes because it significantly reduces the size of resoonses.

## Detail

I provide details in the comments in the code used to communicate with the eth1 node via HTTP:

https://github.com/sigp/lighthouse/blob/24e941d175a7455209c140157bf8d5d588c87ba1/beacon_node/eth1/src/http.rs#L344-L364

Sometime after my first attempt at this I noticed that `reqwest` (the http client library we use) has a [`gzip method`](https://docs.rs/reqwest/0.9.22/reqwest/struct.ClientBuilder.html#method.gzip). I suspect this will solve all our problems.

## Steps to resolve

- Fix gzip encoding.
- Prove that it works, by either;
   - Adding unit tests.
   - If it's too hard to add a test (because you need to build a gzip http server), then provide some details on how one could prove it works (e.g., run some command and it see it communicate with some public server).

**Comment by FawadHa1der** [comment]
I can take a crack at it

**Comment by ezcunn1** [comment]
**** http://www.nutregloproducts.com/
