### ISSUE TITLE
Add Reth to execution clients suggested for installation

### ISSUE THREAD

**Issue by Braqzen** [sigp/lighthouse#6171]
## Description

The [installation](https://lighthouse-book.sigmaprime.io/installation.html) mentions a few execution clients.
Reth is in production and it would be nice to include it as a suggestion for use for a full Rust node.

Edit: there are a few other places that mention the EL so Reth may be added there as well.

## Present Behaviour

Reth is not mentioned in the list of clients in the installation page.

## Expected Behaviour

Hyperlink the GitHub repo to Reth in the installation page among the other execution clients.

**Comment by chong-he** [comment]
Good idea, I will add that to the docs

Edit: just see your PR, I will look into it, thanks

**Comment by Nidacoke** [comment]
#6171

**Comment by chong-he** [comment]
Closed by #6172
