### ISSUE TITLE
Lock validators to a SLOTS_PER_EPOCH value

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#623]
## Description

Current validator slashing protection assumes that `SLOTS_PER_EPOCH` never changes.

If you change this value, you can get validators to sign messages that are slashable.

## To resolve

Ensure that a validator is created with a specific `SLOTS_PER_EPOCH` parameter and they will never sign a message assuming some other value.

**Comment by paulhauner** [comment]
Just to elaborate, it is a "slashable offense" to produce two different attestations in the same epoch ([reference](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#is_slashable_attestation_data)).

If a validator _thinks_ there are 4 slots per epoch, but there are _actually_ 8 slots per epoch, then a vote for slots `0, 4` would be _actually_ slashable, but the validator would not think so.

**Comment by michaelsproul** [comment]
I'm going to close this, as in the latest version of the spec validators are allowed to sign multiple blocks per epoch, just not _per slot_. The code for storing the `slots_per_epoch` in the slashing database has been removed, and I think limiting the slashing protection to do just what is required for security helps keep the code clean.
