### ISSUE TITLE
Blob data missing from slot 9547038

### ISSUE THREAD

**Issue by web3-nodeops** [sigp/lighthouse#6236]
## Description

Querying /eth/v1/beacon/blob_sidecars/9547038 yields an empty data array across all nodes

## Version

lighthouse - v5.1.222-exp
rust - 1.65.0

## Present Behaviour

GET /eth/v1/beacon/blob_sidecars/9547038
Response: {"data":[]}

## Expected Behaviour

Response should return the blob data for slot 9547038

**Comment by michaelsproul** [comment]
There were no blobs in that block:

- https://beaconcha.in/slot/9547038

You can also check this by loading the blinded block from your local node and seeing that the `blob_kzg_commitments` array is empty.

**Comment by michaelsproul** [comment]
Related, we could probably be a bit clearer with our responses on this endpoint, as sometimes Lighthouse will return an `[]` if the blobs have been pruned. See:

- https://github.com/sigp/lighthouse/issues/5640
