### ISSUE TITLE
Make `BeaconChain::kzg` mandatory

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#6260]
## Description

The `kzg` field of the `BeaconChain` is unnecessarily wrapped in an `Option`.

https://github.com/sigp/lighthouse/blob/d6ba8c397557f5c977b70f0d822a9228e98ca214/beacon_node/beacon_chain/src/beacon_chain.rs#L493-L494

Removing this would simplify some error handling because we don't need to handle the case where the `kzg` setup is not initialized.

## Version

Lighthouse v5.3.0

**Comment by eserilev** [comment]
Closed via #6267
