### ISSUE TITLE
Remove naughty peers from the DHT

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#629]
If a peer has performed a malicious action, they become banned for a period of time. 

We should also remove them from the DHT if they exist in a particular bucket so that other nodes also don't find the malicious peer.

**Comment by AgeManning** [comment]
This is a two part issue. 

Firstly, our peer management is quite basic. We ban and kick peers. See here: https://github.com/sigp/lighthouse/blob/enr-v0.2.0/beacon_node/eth2-libp2p/src/service.rs#L168 
and here:
https://github.com/sigp/lighthouse/blob/enr-v0.2.0/beacon_node/eth2-libp2p/src/service.rs#L168

We should implement a method on our behaviour that tells discovery to remove the peer from our local routing table. 

This is fine, but we would also need to modify our discv5 protocol itself to allow the application to remove peers from the local routing table. To do this, we'd need to add a public function to the behaviour not too dis-similar to the `add_enr` function, but instead of adding it we would need to remove it. The add function can be found here: https://github.com/sigp/rust-libp2p/blob/discv5/misc/discv5/src/behaviour.rs#L181

**Comment by AgeManning** [comment]
Discv5 now supports removing nodes from the routing table and adding peers to a ban list.

When a peer gets banned, it should be removed from the local routing table and added to the ban list. 

When a peer becomes unbanned, it should be removed from the discv5 ban list. 

See the `discv5` struct in sigp/discv5 for public functions

**Comment by paulhauner** [comment]
Hey @AgeManning  do you think we need this before the sec review in Oct?

**Comment by AgeManning** [comment]
Yeah, lets add it in. Its a small change

**Comment by divagant-martian** [comment]
closed by #1656
