### ISSUE TITLE
Request reward interface returns 404-【NOT_FOUND: missing state at slot xxxxx】

### ISSUE THREAD

**Issue by azaliasmee** [sigp/lighthouse#6310]
## Description

I requested the lighthouse reward api interface but found that it played 404.please help, thanks

## Version
RUN ENV：Docker

Version：sigp/lighthouse:v5.2.1

## Present Behaviour
<img width="990" alt="image" src="https://github.com/user-attachments/assets/1c1ce429-8139-4d35-9545-a0f7df3fb03c">

## Expected Behaviour

It is expected to return data, as shown in the following example：
<img width="1438" alt="image" src="https://github.com/user-attachments/assets/dce98870-291c-40bc-a624-2c15ae8119d0">

🙏

**Comment by michaelsproul** [comment]
You need to reconstruct historic states to access states older than finalization. See:

https://lighthouse-book.sigmaprime.io/checkpoint-sync.html#reconstructing-states

**Comment by azaliasmee** [comment]
> You need to reconstruct historic states to access states older than finalization. See:
> 
> https://lighthouse-book.sigmaprime.io/checkpoint-sync.html#reconstructing-states

Thank you very much for your help, this flag（`--reconstruct-historic-states`） solved my problem. 🍺

**Comment by michaelsproul** [comment]
great to hear!
