### ISSUE TITLE
`--disable-deposits` flag of validator manager `create` command requires BLS withdrawal credentials with unclear failure message

### ISSUE THREAD

**Issue by ralexstokes** [sigp/lighthouse#6391]
## Description

Conflicting options with unclear docs on how to resolve.

## Version

v5.3.0

## Present Behaviour

This command fails:

`lighthouse vm create --disable-deposits --count 1 --output-path $OUTPUT`

with output
> `--eth1-withdrawal-address is required.`

Upon closer inspection, it looks like the issue is that the tool is trying to make `0x01` withdrawal credentials. But even if you supply `--eth1-withdrawal-address`, we get a conflicting message about use of `--disable-deposits`.

## Expected Behaviour

I should be able to use `--disable-deposits`.

## Steps to resolve

The resolution is to use the `--force-bls-withdrawal-credentials` but this isn't clear from the docs and was only apparent after reading the source code. Could simply add some context to the help message for the `--disable-deposits` flag.

**Comment by chong-he** [comment]
Thanks for reporting! 

Would it make this clear if we add a sentence in the description here: 
`If used, the --force-bls-withdrawal-credentials is also required to ensure users are aware that an --eth1-withdrawal-address is not set` 

https://github.com/sigp/lighthouse/blob/2e0eb6d1b8705bbda2ba56eb195d9cc7c6575e95/validator_manager/src/create_validators.rs#L117-L129

**Comment by chong-he** [comment]
Putting a low hanging fruit tag here for anyone to pick this up

**Comment by hopinheimer** [comment]
@chong-he can I sort this out?

**Comment by chong-he** [comment]
Closed by #6436
