### ISSUE TITLE
Get lockbud running again

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#6413]
## Description

A while ago the author of `lockbud` found a bunch of nice deadlocks in Lighthouse.

- https://github.com/BurtonQin/lockbud

We are still encountering deadlocks occasionally, see:

- https://github.com/sigp/lighthouse/pull/6412

It would be great if we could run `lockbud` on CI to detect them statically.

## Steps to resolve

Last time we tried `lockbud` it had bitrotted and was incapable of compiling Lighthouse.

It seems there have been updates in the last few weeks that might make it work with more recent compiler versions!

**Comment by eserilev** [comment]
Lockbud's github action is still pinned to nightly-2023-04-11

I've opened a PR here to update the github action to the latest supported nightly version (2024-05-21)
https://github.com/BurtonQin/lockbud/pull/68

**Comment by eserilev** [comment]
Closed in #6470
