### ISSUE TITLE
Latest-modern Dockerhub tag not updated

### ISSUE THREAD

**Issue by luarx** [sigp/lighthouse#6508]
## Description

I see that the [`latest-modern` tag](https://hub.docker.com/layers/sigp/lighthouse/latest-modern/images/sha256-58e32ba0a7ef7f8feb9592aff72b413b643cff3a8c425513e187d91542c4fa86?context=explore) in Dockerhub is 4 months old (Jun 29)

In comparison, I see that [other latest tags](https://hub.docker.com/r/sigp/lighthouse/tags) are more updated (Aug 29) 

Does it means that the latest-modern tag is deprecated?

Thanks in advance!

**Comment by chong-he** [comment]
Yes, the `modern` tag is removed, now it is just `latest` (for the latest stable version)

See release note: https://github.com/sigp/lighthouse/releases/tag/v5.3.0
and the related PR: https://github.com/sigp/lighthouse/pull/5489
