### ISSUE TITLE
Persist eth1 cache

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#652]
## Description

The eth1 cache is not persisted between instances of the `lighthouse` process. This means that a full eth1 sync is required each time lighthouse is restarted.

## Steps to resolve

Define a byte-level representation of the eth1 block and deposit caches using SSZ containers (see `SszForkChoice` for a guide).

## Notes

~~There's not much point doing this until #637 has been done, so I've blocked it on that for now.~~

**Comment by paulhauner** [comment]
@pawanjay176 this might be a good one for you? This would be really helpful for when we update the testnet validator nodes, presently they have to re-sync the whole eth1 caches again :(

**Comment by pawanjay176** [comment]
Yup had already started working on it. Will get it done asap.

**Comment by paulhauner** [comment]
Resolved by #760
