### ISSUE TITLE
Nodes missing blob data from slot 8633650

### ISSUE THREAD

**Issue by web3-nodeops** [sigp/lighthouse#6529]
## Description

Blob data missing on nodes in response to /eth/v1/beacon/blob_sidecars/8633650
Verified this block has blob data here - https://beaconcha.in/slot/8633650#blobs

## Version

Multiple
lighthouse - v5.1.222-exp
lighthouse - v5.3.0 (sync'd from scratch)

## Present Behaviour

Response:
```
{
    "data": []
}
```

## Expected Behaviour

Response contains blob data

How _should_ the application behave?

Blob data should be stored and returned in response to the query

## Steps to resolve

Please describe the steps required to resolve this issue, if known.

**Comment by michaelsproul** [comment]
The same problem I mentioned on your previous issue still applies:

- https://github.com/sigp/lighthouse/issues/6236#issuecomment-2272310598

Your node doesn't have the blobs for that slot. In our next release Lighthouse will return a 404 response. It was changed in this PR:

- https://github.com/sigp/lighthouse/pull/6331

If you want to sync old blobs we don't currently have a solution for this (apart from copying the database of a node with all blobs). The work required to support that is being tracked in this issue:

- https://github.com/sigp/lighthouse/issues/5391

**Comment by michaelsproul** [comment]
Closing as duplicate
