### ISSUE TITLE
Add `--http-token-path` flag to the VC

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#6563]
## Description

We considered the issue of VC HTTP token provisioning solved with the closure of:

- https://github.com/sigp/lighthouse/issues/3446
- https://github.com/sigp/lighthouse/issues/5423

However, we didn't add a CLI flag to set the token path. This issue tracks the addition of this flag.

## Present Behaviour

Lighthouse always reads and writes the token from the `$datadir/validators/api-token.txt` path.

## Expected Behaviour

If the user supplies the `--http-token-path` to the VC then the token should be read/written from this path instead. The flag should require the `--http` flag to also have been provided.

**Comment by syjn99** [comment]
Hi, i'd like to take this one for my first contribution

**Comment by michaelsproul** [comment]
Awesome, thanks!

After you've got the code change worked out, you can add a CLI test in `lighthouse/tests/validator_client.rs`

**Comment by cornelpascal** [comment]
Hey, I would like to try and solve this as my first contribution, is it still available or has it been already solved?

**Comment by michaelsproul** [comment]
@cornelpascal already solved, just awaiting review

**Comment by jimmygchen** [comment]
Completed in #6577 🎉  Thanks @syjn99

**Comment by syjn99** [comment]
@michaelsproul @jimmygchen Happy to contribute! Thank you for your help.
