### ISSUE TITLE
Failed to start beacon node

### ISSUE THREAD

**Issue by senkiss** [sigp/lighthouse#6582]
## Description

root@cloud:~# ./lighthouse bn --network mainnet --checkpoint-sync-url=https://sync-mainnet.beaconcha.in --checkpoint-sync-url-timeout=30 --datadir=/root/lgdata --disable-deposit-contract-sync --purge-db
Nov 12 09:06:24.281 INFO Logging to file                         path: "/root/lgdata/beacon/logs/beacon.log"
Nov 12 09:06:24.307 INFO Lighthouse started                      version: Lighthouse/v5.2.0-f1d88ba
Nov 12 09:06:24.309 INFO Configured for network                  name: mainnet
Nov 12 09:06:24.311 INFO Data directory initialised              datadir: /root/lgdata
Nov 12 09:06:24.318 INFO Deposit contract                        address: 0x00000000219ab540356cbb839cbe05303d7705fa, deploy_block: 11184524
Nov 12 09:06:24.338 INFO Blob DB initialized                     oldest_blob_slot: Some(Slot(8626176)), path: "/root/lgdata/beacon/blobs_db", service: freezer_db
Nov 12 09:06:24.343 INFO Starting checkpoint sync                remote_url: https://sync-mainnet.beaconcha.in/, service: beacon
Nov 12 09:06:54.391 CRIT Failed to start beacon node             reason: Error loading checkpoint state from remote: HttpClient(, kind: timeout, detail: operation timed out)
Nov 12 09:06:54.394 INFO Internal shutdown received              reason: Failed to start beacon node
Nov 12 09:06:54.396 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
Failed to start beacon node

**Comment by dapplion** [comment]
You can try to extend the timeout, by using `--checkpoint-sync-url-timeout=300`. If still fails then it should be an issue with the checkpoint server itself.
