### ISSUE TITLE
Support config file 

### ISSUE THREAD

**Issue by eniko1556** [sigp/lighthouse#6601]
## Problem:

Lighthouse lacks support for a dedicated config file, unlike other Ethereum clients. Currently, configurations must be passed through command line flags or wrapper scripts.

## Proposal:
Add support for a config file (e.g., lighthouse.conf/yaml) for both CL and validator clients.

## Benefits:

Cleaner systemd service files
Easier configuration management
Consistent with other client implementations
Easy to share config files
Also easier to start each client (validator/cl)

**Comment by dapplion** [comment]
Supporting a config file is on the roadmap! We need to migrate to clap derive first. This effort is tracked here
- https://github.com/sigp/lighthouse/issues/5900

Then we can easily support a config file

**Comment by chong-he** [comment]
Seems to be related to the issue: 
https://github.com/sigp/lighthouse/issues/4734
https://github.com/sigp/lighthouse/issues/2748

**Comment by dapplion** [comment]
Closing as duplicate of
- https://github.com/sigp/lighthouse/issues/2748
