### ISSUE TITLE
500 Internal Server Error, source: unknown

### ISSUE THREAD

**Issue by changwilling** [sigp/lighthouse#6670]
## Description
I run geth and lighthouse In windows system.
It's always this error:url: http://127.0.0.1:8551/, kind: status, status_code: 500 Internal Server Error, source: unknown

I have start a geth clinet with command:
D:\geth\geth.exe --sepolia --datadir D:\data\ethereum --http --authrpc.addr localhost --authrpc.vhosts localhost --authrpc.port 8551 --authrpc.jwtsecret=D:\path\to\jwtsecret
Then I start the lighthouse with command:
D:\lighthouse\lighthouse.exe beacon_node --network sepolia --datadir D:\data\ethereum --http --execution-endpoint http://127.0.0.1:8551 --execution-jwt D:\path\to\jwtsecret --checkpoint-sync-url=https://sync-sepolia.beaconcha.in --checkpoint-sync-url-timeout=300  --disable-deposit-contract-sync --purge-db

Thanks for your help.

![image](https://github.com/user-attachments/assets/b7e6d1d9-ff80-48b4-b1f1-23713384e64c)

## Version

geth version: 1.14.12
lighthouse version:Lighthouse v6.0.0-c042dc1
I use the newest version of all.

## Present Behaviour

It's always this error:url: http://127.0.0.1:8551/, kind: status, status_code: 500 Internal Server Error, source: unknown

**Comment by michaelsproul** [comment]
what does Geth log?

**Comment by changwilling** [comment]
> what does Geth log?

![image](https://github.com/user-attachments/assets/d929f646-c44b-40dc-bb31-8e3c606315de)
 Post-merge network, but no beacon client seen. Please launch one to follow the chain!

**Comment by michaelsproul** [comment]
Hmm, it kind of looks like a JWT issue.

Does the JWT secret actually exist at the path `D:\path\to\jwtsecret`?

**Comment by changwilling** [comment]
> Hmm, it kind of looks like a JWT issue.
> 
> Does the JWT secret actually exist at the path `D:\path\to\jwtsecret`?

![image](https://github.com/user-attachments/assets/e9cddb5a-9208-4e63-826b-257b387e5e93)
yes, it is there.

**Comment by michaelsproul** [comment]
Try stopping both nodes, then starting Geth followed by Lighthouse. It's possible that the JWT config didn't work the first time because that file didn't exist, and was created by LH after Geth started.

**Comment by changwilling** [comment]
> Try stopping both nodes, then starting Geth followed by Lighthouse. It's possible that the JWT config didn't work the first time because that file didn't exist, and was created by LH after Geth started.

May be not this reason, If there is no jwtsecret file. The lighthouse even can not start. I also do what you have told me. It does not work. But thansk for your help. I need try other ways.

**Comment by michaelsproul** [comment]
Lighthouse should create the JWT if it doesn't already exist.

If you want to debug the JWT, try using one of my scripts:

https://github.com/michaelsproul/eth2-scripts/blob/master/engine_syncing.sh

You need to install the `jwt` CLI from: https://github.com/mike-engel/jwt-cli/releases

**Comment by michaelsproul** [comment]
@changwilling did you fix it?
