### ISSUE TITLE
Missing modern flavor for v6.0.0 in docker hub

### ISSUE THREAD

**Issue by jmcruz1983** [sigp/lighthouse#6693]
## Description

In previous releases a modern flavor was always released 
but in v6.0.0 released seems to be missing in docker hub

Release notes do not mention anything about it,
can you clarify if modern flavor is expected to be produced 
or won't be built as part of future releases 

Thanks

## Version
v6.0.0 stable

**Comment by michaelsproul** [comment]
We deprecated the modern suffix because the default image enables the same optimisations automatically at runtime now.

This was done in v5.3.0 or older so it's not in the release notes for v6.0.0

**Comment by michaelsproul** [comment]
Just checked and we deprecated those images in 5.2, and then stopped producing them in 5.3:

- https://github.com/sigp/lighthouse/releases/tag/v5.3.0

**Comment by jmcruz1983** [comment]
Thanks @michaelsproul
