### ISSUE TITLE
Handle changes to slots_per_restore_point after database initialization

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#673]
## Description

At present, Lighthouse assumes that the `slots_per_restore_point` parameter of the database will remain constant. We should either:

1) Store it in the DB and warn if the user configures it differently from the value in the DB.
2) Store it in the DB, and support changing it (up or down) when the user provides a different value.

Option (1) would be easier.

**Comment by paulhauner** [comment]
Just following up to see if this is still relevant?

**Comment by michaelsproul** [comment]
Yeah it still is. I think implementing (1) as a first step makes the most sense.
