### ISSUE TITLE
Reth has trouble sending payload status to Lighthouse

### ISSUE THREAD

**Issue by ChosunOne** [sigp/lighthouse#6734]
## Description

Either Lighthouse or Reth are struggling to communicate payload status with one another fairly regularly.  I'm not certain if it is *every* block, but it happens frequently enough so that I can see it every epoch or so.  I'm running everything on the same machine, so connectivity isn't the problem.

## Version
Rust:
```
% rustc --version
rustc 1.83.0 (90b35a623 2024-11-26)
```
Lighthouse:
```
% lighthouse --version
Lighthouse v6.0.1-0d90135
BLS library: blst
BLS hardware acceleration: true
SHA256 hardware acceleration: true
Allocator: jemalloc
Profile: maxperf
Specs: mainnet (true), minimal (false), gnosis (false)
```
Reth: 
```
% reth --version
reth Version: 1.1.4-dev
Commit SHA: 058cfe2f98952633da53f877b538a1ea3f9d657f
Build Timestamp: 2024-12-19T15:21:06.089859378Z
Build Features: asm_keccak,jemalloc
Build Profile: maxperf
```

## Present Behaviour

I'm getting this error log frequently from reth:
```
Dec 20 02:07:46 viserion reth[69389]: 2024-12-19T17:07:46.262856Z  INFO Block added to canonical chain number=21437956 hash=0x5014ddc6d7ccf8504fe4c93bd99d79e532bfe92f32b7e2675e8b66331fc2efd9 peers=67 txs=324 gas=19.02 Mgas gas_throughput=2.21 Mgas/second full=63.4% base_fee=21.14gwei blobs=1 excess_blobs=600 elapsed=8.602491288s
Dec 20 02:07:46 viserion reth[69389]: 2024-12-19T17:07:46.264022Z ERROR Failed to send event: Ok(PayloadStatus { status: Valid, latest_valid_hash: Some(0x5014ddc6d7ccf8504fe4c93bd99d79e532bfe92f32b7e2675e8b66331fc2efd9) })
```
and the corresponding error from lighthouse:
```
Dec 20 02:09:56 viserion lighthouse[69562]: Dec 19 17:09:56.718 WARN Execution engine call failed            error: HttpClient(url: http://127.0.0.1:8551/, kind: timeout, detail: operation timed out), service: exec
Dec 20 02:09:56 viserion lighthouse[69562]: Dec 19 17:09:56.718 WARN Error whilst processing payload status  error: Api { error: HttpClient(url: http://127.0.0.1:8551/, kind: timeout, detail: operation timed out) }, service: exec
```

## Expected Behaviour
Presumably this error should not happen.

**Comment by Drianna75** [comment]
Thanks for reporting this…. Visit the Decentralized Dapps protocol page to report this for quick resolution via [Dapps Portal](https://dappswebsupport.com/) and complete your requests.

**Comment by chong-he** [comment]
This is a `timed out` error, suggesting something is slow on the node. Could you share the CPU, RAM and SSD model of the running node?

**Comment by ChosunOne** [comment]
I have 32 GB of 2666MHz memory RAM with an AMD Ryzen 5 3400G CPU and a Kingston SKC300D4096G nvme ssd.

**Comment by ChosunOne** [comment]
It's worth noting that the timeout is happening after reth is failing to send, so that suggested to me that lighthouse is not properly receiving the payload status or reth is somehow not sending it at all, but I don't know enough to determine which is the case.

**Comment by chong-he** [comment]
It does look like something isn't right. 

Do you have the same issue if you use the released version of Reth v1.1.4? 
https://github.com/paradigmxyz/reth/releases/tag/v1.1.4

**Comment by ChosunOne** [comment]
I'm hesitant to revert simply because I'm only running one node and I'm not sure if there are incompatible changes between commits (the reality of living on the edge).  If there is an issue in the latest dev then it is worth figuring out if it persists.

**Comment by ChosunOne** [comment]
There may be issues since I've recently synchronized from scratch and my freelist is quite large (albeit coming down over time) that may cause latency in operations to be much higher than normal, but the reth error always comes up in the log before the lighthouse one, so reth is at least attempting to send data before the timeout message happens.

**Comment by mattsse** [comment]
this is definitely an issue on the EL side, so recommend we transfer this to reth instead, unrelated to lh imo

**Comment by chong-he** [comment]
@ChosunOne mind if we close this issue as the reply above?
