### ISSUE TITLE
Use atomic operations in database to harden against failures

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#692]
## Description

At present, each insert into the store is its own operation, but we often rely on invariants to be maintained between objects inserted at different times (e.g. if we have a block, we expect to have its state too). Through the use of transactions/atomics at the level of the KV store, we should be able to better maintain these invariants under adverse conditions (the process getting SIGKILLed, power outage, etc).

**Comment by adaszko** [comment]
A candidate for using atomic operations:

https://github.com/sigp/lighthouse/blob/cd0b86f1a3de99a779589d721606edcfc32d42ef/beacon_node/store/src/state_batch.rs#L39-L46
