### ISSUE TITLE
API additions required for blockchain explorers

### ISSUE THREAD

**Issue by ppratscher** [sigp/lighthouse#694]
I had a look on your REST API in order to evaluate the feasibility to plug lighthouse into our open source block explorer beaconcha.in. Most of the API already provides most of the information required for the explorer but some crucial details are still missing:

- The blocks object should also include the block root hash alongside the state root hash and parent root hash
- Currently I could not find any call that returns the current balance of a validator, it would be great if it is included in the get_beacon_validators response alongside the effective balance
- The get_beacon_validators should include the validator index alongside the validator public key
- Add a get_beacon_validators_duties that returns the duties of all validators for a given epoch, otherwise we will have to call get_beacon_validator_duties with all public keys which might be not that performant (but I haven't tested this up to now)
- In order to de-aggregate attestations and associate an attestation with the included validators we will need the beacon committees for each epoch. I couldn't find any call that returns the committees by epoch
- In order to show participation statistics for each epoch add a call that shows the eligible ether, voted ether and the participation rate for each epoch

With those few changes we should be able to write a thin compatibility wrapper and have a dedicated instance of the lighthouse testnet available at https://beaconcha.in/

For optimal compatibility see the protobuf definitions provided by prysmaticlabs at https://github.com/prysmaticlabs/ethereumapis/

**Comment by paulhauner** [comment]
Thank you, I will get onto this ASAP.

**Comment by paulhauner** [comment]
Hey, thanks for this @ppratscher! I am starting to work on this over in #702. I have had a quick run though the list and had the following comments. Let me know what you think :)

-----

> The blocks object should also include the block root hash alongside the state root hash and parent root hash

We return `BlockResponse { root: Hash256, beacon_block: BeaconBlock }`. Unless I'm misunderstanding, I think all the info is there. It seems that the [Prysm API](https://github.com/prysmaticlabs/ethereumapis/blob/5287ac0973a9dd56285b8758ef7469705ba12966/eth/v1alpha1/beacon_chain.proto#L286-L292) does the same thing.

> Add a get_beacon_validators_duties that returns the duties of all validators for a given epoch, otherwise we will have to call get_beacon_validator_duties with all public keys which might be not that performant (but I haven't tested this up to now)

This would boil down to a call of "give me all duties for all active validators", which currently would be over 16k. This sounds quite heavy, my first instinct would be to allow a filter by pubkey. If we do filter by pubkey, we end up at the `POST /beacon/validator/duties` endpoint where the request body is a list of pubkeys and the response body is their validators.

**Comment by ppratscher** [comment]
Hm, according to your api docs at https://app.swaggerhub.com/apis-docs/spble/lighthouse_rest_api/0.2.0#/Phase0/get_beacon_blocks the response does not contain the block root or I might have missed it. I did not yet try it with the live api.

For a block explorer we need all duties for a given epoch, otherwise we are unable to identify missed blocks and potentially down validators. We cache the epoch duties locally so as long as the RPC call returns within a few seconds it should not affect our indexer performance.

**Comment by paulhauner** [comment]
> Hm, according to your api docs at https://app.swaggerhub.com/apis-docs/spble/lighthouse_rest_api/0.2.0#/Phase0/get_beacon_blocks the response does not contain the block root or I might have missed it. I did not yet try it with the live api.

Ah yes, we had to stop maintaining the OpenAPI docs because they were too burdensome and fiddly to update as the spec kept changing. Apologies we did not reflect this in the docs.

I have started a refactor of the docs in #702. You can preview the work here:

https://github.com/sigp/lighthouse/blob/7bbc82458a17015a624addcd849a76c0181d82e7/book/src/http_beacon.md

> For a block explorer we need all duties for a given epoch, otherwise we are unable to identify missed blocks and potentially down validators. We cache the epoch duties locally so as long as the RPC call returns within a few seconds it should not affect our indexer performance.

Sure, I will make sure we can do a call to get all validator duties.
