### ISSUE TITLE
Block processing error gets sync in bad state?

### ISSUE THREAD

**Issue by ethers** [sigp/lighthouse#698]
## Description

Syncing was going well, and then a Block processing error appears to have prevented syncing from making progress: the distance starts increasing.

## Present Behaviour

Above.
error: "Block at slot 29828 has an unknown parent."

## Expected Behaviour

After a Block processing error or bad peer, I would expect that the node would still be able to sync from the available peers, without needing any user interaction or restart of the node.

## Steps to resolve

Restart the bn?  Is it necessary?

Dec 10 21:12:18.028 INFO Syncing                                 distance: 284 slots (57 mins), speed: 2.08 slots/sec, est_time: 2 mins, peers: 10, service: slot_notifier
Dec 10 21:12:30.018 INFO Syncing                                 distance: 235 slots (47 mins), speed: 3.13 slots/sec, est_time: 1 mins, peers: 10, service: slot_notifier
Dec 10 21:12:42.047 INFO Syncing                                 distance: 186 slots (37 mins), speed: 3.12 slots/sec, est_time: 1 mins, peers: 10, service: slot_notifier
Dec 10 21:12:53.061 WARN Block processing error                  error: "Block at slot 29828 has an unknown parent.", service: sync, service: network
Dec 10 21:12:53.062 WARN Disconnecting peer (RPC)                peer_id: PeerId("16Uiu2HAmP9XftLpupbPJqGEmVxnsP6xGn45XuKPvJvEAFS7o1U1C"), reason: Fault, service: sync, service: network
Dec 10 21:12:53.063 WARN Disconnecting peer (RPC)                peer_id: PeerId("16Uiu2HAm3bThwnr6GMM3W9pT82ukNMnzieefP5jg4B3twBqdJTck"), reason: Fault, service: sync, service: network
Dec 10 21:12:53.064 WARN Disconnecting peer (RPC)                peer_id: PeerId("16Uiu2HAm8H7k75DyY2s63LuJetxKDHe6ZHN9acaH1H2ew2MqjpQv"), reason: Fault, service: sync, service: network
Dec 10 21:12:53.065 WARN Disconnecting peer (RPC)                peer_id: PeerId("16Uiu2HAkuUVrmoygG3ZSkNwBW2PuQmgHnVoQwL5XE7LmWvza7TBx"), reason: Fault, service: sync, service: network
Dec 10 21:12:53.066 ERRO Disconnecting and banning peer          timeout: 30s, peer_id: PeerId("16Uiu2HAmP9XftLpupbPJqGEmVxnsP6xGn45XuKPvJvEAFS7o1U1C"), service: network
Dec 10 21:12:53.067 ERRO Disconnecting and banning peer          timeout: 30s, peer_id: PeerId("16Uiu2HAm3bThwnr6GMM3W9pT82ukNMnzieefP5jg4B3twBqdJTck"), service: network
Dec 10 21:12:53.067 ERRO Disconnecting and banning peer          timeout: 30s, peer_id: PeerId("16Uiu2HAm8H7k75DyY2s63LuJetxKDHe6ZHN9acaH1H2ew2MqjpQv"), service: network
Dec 10 21:12:53.068 ERRO Disconnecting and banning peer          timeout: 30s, peer_id: PeerId("16Uiu2HAkuUVrmoygG3ZSkNwBW2PuQmgHnVoQwL5XE7LmWvza7TBx"), service: network
Dec 10 21:12:54.026 INFO Syncing                                 distance: 141 slots (28 mins), speed: 3.04 slots/sec, est_time: 1 mins, peers: 6, service: slot_notifier
Dec 10 21:13:06.017 INFO Syncing                                 distance: 142 slots (28 mins), speed: 3.04 slots/sec, est_time: 1 mins, peers: 6, service: slot_notifier
Dec 10 21:13:18.021 INFO Syncing                                 distance: 143 slots (29 mins), speed: 2.00 slots/sec, est_time: 1 mins, peers: 7, service: slot_notifier
Dec 10 21:13:27.568 WARN Block processing error                  error: "Block at slot 29888 has an unknown parent.", service: sync, service: network
Dec 10 21:13:27.570 WARN Disconnecting peer (RPC)                peer_id: PeerId("16Uiu2HAmEpez9kLtgy489JJFKYpCSv3mJdzrJRFca1kpYT8GtcSG"), reason: Fault, service: sync, service: network
Dec 10 21:13:27.576 WARN Disconnecting peer (RPC)                peer_id: PeerId("16Uiu2HAm3bThwnr6GMM3W9pT82ukNMnzieefP5jg4B3twBqdJTck"), reason: Fault, service: sync, service: network
Dec 10 21:13:27.581 ERRO Disconnecting and banning peer          timeout: 30s, peer_id: PeerId("16Uiu2HAmEpez9kLtgy489JJFKYpCSv3mJdzrJRFca1kpYT8GtcSG"), service: network
Dec 10 21:13:27.582 ERRO Disconnecting and banning peer          timeout: 30s, peer_id: PeerId("16Uiu2HAm3bThwnr6GMM3W9pT82ukNMnzieefP5jg4B3twBqdJTck"), service: network
Dec 10 21:13:30.026 INFO Syncing                                 distance: 144 slots (29 mins), speed: 0.96 slots/sec, est_time: 2 mins, peers: 6, service: slot_notifier
Dec 10 21:13:42.017 INFO Syncing                                 distance: 145 slots (29 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:13:54.018 INFO Syncing                                 distance: 146 slots (29 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:14:06.027 INFO Syncing                                 distance: 147 slots (29 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:14:18.024 INFO Syncing                                 distance: 148 slots (30 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:14:30.020 INFO Syncing                                 distance: 149 slots (30 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:14:42.019 INFO Syncing                                 distance: 150 slots (30 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:14:54.024 INFO Syncing                                 distance: 151 slots (30 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:15:06.017 INFO Syncing                                 distance: 152 slots (30 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:15:18.020 INFO Syncing                                 distance: 153 slots (31 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier
Dec 10 21:15:30.019 INFO Syncing                                 distance: 154 slots (31 mins), speed: 0.00 slots/sec, est_time: inf weeks NaN days, peers: 6, service: slot_notifier

**Comment by paulhauner** [comment]
@AgeManning I think you might be best placed to answer this :)

**Comment by AgeManning** [comment]
Yes. The correct logic is to handle these cases (which is being built in the network re-write) see #681. The reason it is not currently implemented, is that this error should never occur in a lighthouse-only network. We want to identify these issues now, address them, rather than have logic that hides these. 

For this particular error, a peer sent you a block that it shouldn't have. There is not enough information here for me figure out why. If possible, could you try re-running with `--debug-level debug` flag, i.e `lighthouse --debug-level debug bn .. ` and post any results if this occurs again.
