### ISSUE TITLE
Missing constant in YamlConfig

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#704]
## Description

It seems we're missing a constant in the `YamlConfig`. See:

See https://lighthouse-book.sigmaprime.io/become-a-validator.html

This might be a good one for @pscott :)

**Comment by pscott** [comment]
For reference: Paul wanted to link [this](https://github.com/eth2-clients/eth2-testnets/). Specifically, I believe we wanted to address [this issue](https://github.com/eth2-clients/eth2-testnets/commit/8f32450e754f44028813d472209b2c1ca1650567) and [this one](https://github.com/eth2-clients/eth2-testnets/commit/04e9070ff75bd55b05731e834553d3d6931ba9ec).
