### ISSUE TITLE
Testnet Documentation suggestions

### ISSUE THREAD

**Issue by Buttaa** [sigp/lighthouse#710]
1. Write separate guides for docker & rust

> ![image](https://user-images.githubusercontent.com/26490734/70663484-ba89f000-1c68-11ea-84cd-a5c708fad0b9.png)

2. https://lighthouse-book.sigmaprime.io/docker.html 
Add next steps to continue with docker 

>docker run -it --name=light-beacon -v $HOME/lighthouse-data:/root/.lighthouse -p >127.0.0.1:10000:10000 lighthouse lighthouse beacon_node --http-address=0.0.0.0 --http-port=10000 ->-http

>docker run --name=light-valid-keygen -v $HOME/lighthouse-data:/root/.lighthouse lighthouse >lighthouse account validator new random

>docker run -it --name=light-valid -v $HOME/lighthouse-data:/root/.lighthouse --network="host" >lighthouse lighthouse validator --server http://0.0.0.0:10000/ 

@agemanning

**Comment by AgeManning** [comment]
Thanks for this, will update
