### ISSUE TITLE
Notifier to get info from sync

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#720]
## Description

Currently the notifier doesn't get syncing information from the sync manager. When no peers are connected, the notifier thinks we are syncing, when we are actually `stalled`. 

Under the hood there are four kinds of sync state:
- Stalled - No peers, no way to progress
- Finalized - We are syncing a finalized chain to reach a peers known finalized slot
- Head - We are syncing head chains to reach a peers head slot
- Regular - We are fully synced (up to a tolerance), and we do block parent lookups from peers when we see unknown blocks. 

At a very minimum the notifier should know about Stalled, and we should decide whether the other states should be relayed to the user

**Comment by divagant-martian** [comment]
With [this line](https://github.com/sigp/lighthouse/blob/6fc2532cfd992a33c7afebccf7d7946205a2e740/beacon_node/client/src/notifier.rs#L61) I think this one can be closed
