### ISSUE TITLE
`lighthouse account validator new random` doesnt respect datadir

### ISSUE THREAD

**Issue by jacobrosenthal** [sigp/lighthouse#726]
I ended up just running it bare and moving the generated validators directory to my datadir manually

**Comment by paulhauner** [comment]
Thanks!

Looks like datadirs need some love, we should try and pick this up with #724.

**Comment by pawanjay176** [comment]
Hi @jacobrosenthal, trying to reproduce the issue. What was the command you used? :)

**Comment by jacobrosenthal** [comment]
Something like
`lighthouse account validator new random --datadir /mnt/storage/lighthouse`
but the validators directory wasnt there
`lighthouse account validator new random` and moved it by hand instead

**Comment by pscott** [comment]
@jacobrosenthal Yup it's because --datadir flag is passed to lighthouse, so the appropriate way of using this would be
`lighthouse --datadir /mnt/storage/lighthouse account validator new random`

Maybe we should warn people when a flag is misplaced, or (better) accept the flag? What do you think @paulhauner ?

**Comment by pscott** [comment]
I just tried running `lighthouse account validator new random --datadir /tmp/test` or `lighthouse --datadir /tmp/test account validator new random` and both worked... trying to reproduce this issue too but I can't manage to have it failed.
I had it failing when pointing to a restricted directory but the log warned me appropriately, saying
```
Dec 15 22:33:21.696 CRIT Account manager failed                  error: Unable to create validator directory: Permission denied (os error 13)
```

**Comment by jacobrosenthal** [comment]
Maybe on my end, Ill check again when the testnet comes back up and reopen if need be
