### ISSUE TITLE
Eth1 node down

### ISSUE THREAD

**Issue by JustinDrake** [sigp/lighthouse#732]
As I understand there's an Eth1 Sigmaprime node from which deposits are fetched. It seems to be down or unreachable as I repeatedly get the following errors.

```
Dec 15 13:37:45.729 ERRO Failed to update eth1 block cache       error: Failed to update eth1 cache: GetDepositRootFailed("Request failed: Error(Hyper(Error(Connect, Custom { kind: Other, error: \"failed to lookup address information: nodename nor servname provided, or not known\" })), \"https://goerli.public.sigp.io/\")"), service: eth1_rpc
Dec 15 13:37:45.729 ERRO Failed to update eth1 genesis cache     error: Failed to update eth1 cache: GetDepositRootFailed("Request failed: Error(Hyper(Error(Connect, Custom { kind: Other, error: \"failed to lookup address information: nodename nor servname provided, or not known\" })), \"https://goerli.public.sigp.io/\")"), retry_millis: 7000, service: eth1_rpc
```

**Comment by wangyinglike1234** [comment]
I have the same question and I think it may be the network question??
Dec 27 11:31:50.117 ERRO Failed to update eth1 deposit cache     error: Failed to update eth1 cache: GetDepositLogsFailed("Failed to get logs in range: Failed to receive body: \"Failed to receive body: Error(Io(Custom { kind: TimedOut, error: \\\"timed out\\\" }))\""), service: eth1_rpc

**Comment by paulhauner** [comment]
Thanks @JustinDrake and @wangyinglike1234.

I think we should restructure the docs to push users to run their own eth1 nodes. Whilst providing a sigp-hosted eth1 node is nice for usability in testnets, it's not an accurate reflection of mainnet. Relying upon some centrally hosted API (e.g., our geth node on AWS) for eth1 -> eth2 linking is a major centralization risk. Whomever controls that eth1 node will control eth2 validator on-boarding. Allowing this corner-cutting is dishonest (for lack of a less harsh word) and gets users in bad habits.

If we _do_ decide to continue to supply a public eth1 node, we should probably spin up a few of them in different zones (US, Europe, Asia) and let users pick one that's close to them. I suspect the

**Comment by paulhauner** [comment]
Closing this since we now encourage users to run their own eth1 nodes (and we do not host a public node)
