### ISSUE TITLE
Implement max number of response chunks

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#754]
## Description

A maximum number of chunks can be read before an RPC stream is considered failed. This needs to be implemented in the RPC handler.

**Comment by b-m-f** [comment]
@AgeManning is this done with #811?

**Comment by AgeManning** [comment]
No, I've left this one out. Still on the old to-do list.

**Comment by b-m-f** [comment]
Thanks for the quick reply. I would like to pick this one up if there is no blocker

**Comment by AgeManning** [comment]
Hey, let me explain this issue a bit more. 
In the discord, there are two ideas which are two distinct issues here. The first is preventing a peer from continuously sending data for ever (eventually the data sent will be invalid and we will kick the peer, but it would be nice to stop the data based on the request we sent). This is this issue. The rate limiting and prioritising streams is dealt with in #1056. 

For this issue. Given a request, for example a BlocksByRange request of 20 blocks, we want to end or close the stream after we have received 20 chunks. For a blocks by root, if we request 3 blocks we want to end the stream after a 3 chunks have been received. RPC requests that don't expect multiple responses are already handled. 

Now in terms of the code, the RPCRequest should only be implemented in protocol.rs no in methods. The Response variant is in `methods` there is a reason for this, but I won't go into it here. 

So when we create a request, if the peer supports the protocol and everything all good with the connection, we create an outbound_substream [here](https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/handler.rs#L310)

We create an `outbound_substream` which is an object that implements `Stream` and `Sink`. We store it in a mapping by its ID, along with a key for when it should expire and the protocol its based on. See [here](https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/handler.rs#L353)

For this issue, along with the protocol and delay key we may want to store number of chunks responded. So that as we receive chunks we increment the count until the maximum is reached and then we end the stream. As the request is stored along with the substream state, we can use the request to determine what the number of expected responses should be. 

A response from the stream appears [here](https://github.com/sigp/lighthouse/blob/master/beacon_node/eth2-libp2p/src/rpc/handler.rs#L663)

I imagine here we can increment the number of chunks received and we can use the available request in this part to determine if we have received the maximum or expected number of chunks. If so transition the stream to the closing state. 

Hopefully this sheds some light on the issue and the surrounding code. 

There is a caveat in that the handler has been modified quite a bit in the `stable-futures` branch. If at all possible, have a look at that branch as I'll be fixing it up and merging down ideally this week. 
It doesn't compile just yet, but will give you an idea of the structure (it still needs a bit of cleaning)

**Comment by divagant-martian** [comment]
Isn't this the same as / included in #909?

**Comment by AgeManning** [comment]
Resolved in #1126
