### ISSUE TITLE
Error 127

### ISSUE THREAD

**Issue by Moelbeck** [sigp/lighthouse#755]
Tried to install Lighthouse running the instructions from this site:
https://lighthouse-book.sigmaprime.io/installation.html
When I run the "make" command, it gives me an error: "[Makefile:9: install] Error 127"

**Comment by paulhauner** [comment]
Thanks @Moelbeck. Do you have more information, please? Code 127 usually means that a command is not found, it would help to know which command is not found.

**Comment by Moelbeck** [comment]
This was my bad, CARGO_HOME was not included in my path. I'll close this, but will open a new one
