### ISSUE TITLE
Clean up `beacon_chain/types::common`

### ISSUE THREAD

**Issue by ralexstokes** [sigp/lighthouse#77]
## Description

It looks like this module is not being used. It does provide duplicate definitions of `AttesterMap` and `ProposerMap` which is confusing. It seems like this module is just dangling after a refactor.

## Present Behaviour

it exists.

## Expected Behaviour

this module should not exist if it is not being used.

## Steps to resolve

Let's just remove it.

Opening this issue to confirm my suspicion that it is just dangling after a refactor. Otherwise just close this :)

**Comment by paulhauner** [comment]
I'm refactoring some stuff around this in #85 so I'll see what the outcome of that is.

Good find though!

**Comment by paulhauner** [comment]
This will be cleaned out by #129

**Comment by paulhauner** [comment]
Resolved in #129
