### ISSUE TITLE
0 peers when following instructions

### ISSUE THREAD

**Issue by macsj200** [sigp/lighthouse#771]
I'm following the [Become a validator](https://lighthouse-book.sigmaprime.io/become-a-validator.html#2-start-your-beacon-node) instructions to start a beacon node, but when I run
```
$ lighthouse beacon --eth1 --http
```
I'm forever stuck with 0 peers. Do I need to update my discovery settings?

**Comment by paulhauner** [comment]
Hi @macsj200, if you're using `master` then you'd be attempting to connect to the old testnet which has been pulled down.

We're planning to announce our new testnet this week, however you can use the `testnet3` branch if you want a sneak peak.

I'll close this for now, assuming that this answers your question. Happy to re-open if not :)
