### ISSUE TITLE
Missing validation of `ancestor_hashes` in block

### ISSUE THREAD

**Issue by ralexstokes** [sigp/lighthouse#79]
## Description

Seems like we are missing a check on the incoming block data during validation.

We want to make sure that the block's `ancestor_hashes` align with our expectations given our local view of the chain.

## Present Behaviour

We deserialized `ancestor_hashes` and just accept the data as given.

## Expected Behaviour

The block should be invalid if we don't derive the expected updates to the `ancestor_hashes`.

## Steps to resolve

We should check that every block updates the `ancestor_hashes` according to spec:

copied here for convenience (double check w/ latest spec before implementing...):

"
Also, check that the block's ancestor_hashes array was correctly updated, using the following algorithm:

```python
def update_ancestor_hashes(parent_ancestor_hashes: List[Hash32],
                           parent_slot_number: int,
                           parent_hash: Hash32) -> List[Hash32]:
    new_ancestor_hashes = copy.copy(parent_ancestor_hashes)
    for i in range(32):
        if parent_slot_number % 2**i == 0:
            new_ancestor_hashes[i] = parent_hash
    return new_ancestor_hashes
```
"

**Comment by paulhauner** [comment]
Good find! I think the spec has updated since we implemented this.

**Comment by paulhauner** [comment]
Block validation has been antiquated and the code is scrapped in #85.

#107 now tracks the task of implementing block processing (we have to write it all again :face_with_head_bandage:)
