### ISSUE TITLE
lighthouse vc testnet -b invalid command

### ISSUE THREAD

**Issue by jacobrosenthal** [sigp/lighthouse#795]
`lighthouse vc testnet -b insecure 0 8`

Book says to use -b for vc, but that doesnt appear to be a valid subcommand currently

**Comment by pawanjay176** [comment]
Hi @jacobrosenthal, The docs on the `Testnets` section seem to be out of date. Will update the docs soon. Thanks for pointing this out :) 

I suggest you use the docs in the simple local testnet section if you are trying to spin up local testnets https://lighthouse-book.sigmaprime.io/simple-testnet.html.

**Comment by AgeManning** [comment]
Closed in #802
