### ISSUE TITLE
Logic error when retrieving attester slashing from op_pool

### ISSUE THREAD

**Issue by pscott** [sigp/lighthouse#805]
## Description
The function `get_slashings` that retrieves attester slashings from the operation pool is currently flawed, as it calls `get_slashable_indices_modular` with an incorrect closure.
https://github.com/sigp/lighthouse/blob/03443c3e5714ae5478173de4a87f92a1c9577549/eth2/operation_pool/src/lib.rs#L224-L225

## Steps to resolve
I believe (idea from @michaelsproul ) that the correct closure should be
```rust
|index, validator| validator.is_slashable_at(state.current_epoch()) && !to_be_slashed.contains(&index)
```

**Comment by michaelsproul** [comment]
Great find! Definitely a nasty bug
