### ISSUE TITLE
How to programmatically detect if node is sync'd.

### ISSUE THREAD

**Issue by timmyers** [sigp/lighthouse#810]
## Description

It would be great if there was a rest API method to detect whether a node is synchronized.

For example, the `prysm` client has a `/eth/v1alpha1/node/syncing` (https://api.prylabs.net/#/Node/GetSyncStatus) which returns a bool.

This is important when orchestrating multiple beacon nodes, and knowing when they are ready to serve traffic.

Potentially related issues: #714 #720

**Comment by AgeManning** [comment]
Yep. Along with #720, I'll add this update in #811. 

I'll document the exact the endpoint once added in.

**Comment by AgeManning** [comment]
Resolved in #994
