### ISSUE TITLE
Parent block lookup over same peer

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#822]
## Description

There appears to be a bug in adding a syncing peer as a peer that can receive unknown gossip blocks. 

Alongside this, a failed attempt at retrieving an unknown block will re-request from the same peer. The requests should be distributed amongst peers and should request from the peer that referenced the unknown block first.

**Comment by paulhauner** [comment]
Hey @AgeManning is this still relevant?

**Comment by AgeManning** [comment]
Yeah. Something still to investigate... still on the list

**Comment by AgeManning** [comment]
This is resolved in #895
