### ISSUE TITLE
Slow API calls for slots that are not synced

### ISSUE THREAD

**Issue by pscott** [sigp/lighthouse#824]
## Description

Slow API calls when trying to fetch data about some slot that is not currently synced but smaller than the current slot (as provided by the slot_clock).

## Present Behaviour

When starting a fresh sync (no DB), the beacon node starts by syncing up the chain. Making an API call that asks for data that is not synced yet, but smaller than the current slot clock will make a call to `state_root_at_slot`, which will in turn start skipping slots until it gets to correct slot.
https://github.com/sigp/lighthouse/blob/8c96739cab62b28d9646d3eb9f61445e81bc96fd/beacon_node/rest_api/src/helpers.rs#L207-L224

This can result in a very, very long API call (I personally witnessed a 19 minutes long API call).
Correct me if I'm wrong but by skipping slots we assume that they were skip slots (i.e they did not contain any block), so it makes the result invalid?

## Expected Behaviour

I see two options here:
1. Return an error saying (slot is higher than current synced head)
2. Keep our present behaviour but log some kind of warning, so that the user knows what's happening.

## Steps to resolve

Choose an option, and implement it, most probably in the piece of code linked earlier in this post.

**Comment by paulhauner** [comment]
Resolved via #1569
