### ISSUE TITLE
Parameters too loose on API calls

### ISSUE THREAD

**Issue by pscott** [sigp/lighthouse#825]
## Description

You can pass some extra useless parameters to some API calls.

## Present Behaviour

A number of API calls allow for useless parameters to be passed in. For example `/beacon/head` doesn't check for any parameters, so you can call `/beacon/head?slot=0`.

I don't think this presents any security issues.
However, from a user perspective, it could be confusing.

## Expected Behaviour

One would expect this to return an error.

## Steps to resolve

Check that API calls do not allow for extra useless parameters to be passed in.

**Comment by paulhauner** [comment]
Resolved via #1569
