### ISSUE TITLE
Keypair file does not exist

### ISSUE THREAD

**Issue by fubuloubu** [sigp/lighthouse#830]
## Description
`beacon validator -d {non-standard directory location}` yells about not being able to find the keypair file:
```bash
ERRO Failed to load a validator directory    path: /media/Ethereum/lighthouse/beacon, error: Unable to get voting keypair: Keypair file does not exist: "/media/Ethereum/lighthouse/beacon/voting_keypair"                                       
ERRO Failed to load a validator directory    path: /media/Ethereum/lighthouse/validators, error: Unable to get voting keypair: Keypair file does not exist: "/media/Ethereum/lighthouse/validators/voting_keypair"   
```

## Present Behaviour
I moved my directory to a non-standard directory, and deleted my `beacon/` folder (as a result of the issue I mentioned in #829), and this error pops up. I solved it by copying the `voting_keypair` file from `lighthouse/validator/{raw-public-key}/voting_keypair` to the locations mentioned in errors.

## Expected Behaviour
Deleting the `beacon/` folder should not have any affect in how the 'validator/` works. Also, should not have to copy any files.

## Steps to resolve
Have lighthouse only recognize keys from `lighthouse/validator/{raw-public-key}/`

**Comment by paulhauner** [comment]
I'm going to close this one since it didn't go anywhere and we've refactored key management since. Sorry we didn't help you on this one @fubuloubu!
