### ISSUE TITLE
Make Lighthouse respect XDG Base Directory Specification

### ISSUE THREAD

**Issue by adaszko** [sigp/lighthouse#875]
## Present Behaviour

Currently, when run outside of a Docker container, Lighthouse uses `~/.lighthouse` as its state directory.  This is an outdated convention which results in hard-to-manage dozens of similar directories in user's home directory.

## Expected Behaviour

Nowadays, it is preferred to adhere to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

## Steps to resolve

To quote the spec:
> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by paulhauner** [comment]
This seems like good practice to me. I recall Parity behaves like this too.

Thoughts @michaelsproul, @AgeManning?

**Comment by paulhauner** [comment]
I'm going to close this one since it doesn't really seem feasible to change this so close to mainnet.
