### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by adaszko** [sigp/lighthouse#878]
## Present Behaviour

`make test-debug` fails with a `Too many open files` error in *various* tests.

More precisely, the error message is: `thread 'tokio-runtime-worker-0' panicked at 'failed to open /dev/urandom: Os { code: 24, kind: Other, message: "Too many open files" }', src/libcore/result.rs:1188:5`.

I only tested on macOS.  File descriptors limit may be lower there.

The tests I've seen failing so far:
 * `eth1_cache::pruning`
 * `eth1_cache::double_update`
* `eth1_cache::big_skip`
* `deposit_tree::updating`
* `fast::deposit_cache_query`
* `test_gossipsub_forward`
* ` fast::deposit_cache_query`

## Expected Behaviour

`make test-debug` tests should be passing.

**Comment by adaszko** [comment]
I'm working on it.

**Comment by adaszko** [comment]
More precise command to reproduce: `cargo test --all --exclude ef_tests -p eth1 --test test`

**Comment by adaszko** [comment]
I've tried adding a macOS executor to GitHub CI and [setting `ulimit -n 256`](https://github.com/adaszko/lighthouse/blob/f11a1f63162d0bb3d96c08dbcc806e6f4cc3058f/.github/workflows/macos.yml#L15) (256 is the default on macOS).  The result is [the job simply hangs](https://github.com/adaszko/lighthouse/runs/480337165).

**Comment by adaszko** [comment]
Attaching `dtruss` run shows it's the `/dev/urandom` file that [gets opened a lot of time](https://gist.github.com/adaszko/1140239814e84f24f703d56ebe6423cc).

**Comment by adaszko** [comment]
I tried gdb on Linux but it crashes with no good reason.  Replacing `random_deposit_data()` with `generate_deterministic_keypair()` did not make any effect either.

Fortunately, [`dtruss` backtraces](https://gist.github.com/bd8f8cd311a156be586f8bf356fba56a) reveal what's going on.  The problem is each instance of `EnvironmentBuilder::minimal().single_thread_tokio_runtime()` uses `std::collections::hash_map::HashMap` underneath, which (too avoid certain attack vectors), uses a strong randomness source in the form of `/dev/urandom` on macOS.

The mio version we use (0.6.21) [uses HashMap](https://github.com/tokio-rs/mio/blob/cd0423c47209a70d6a42cfd500de6ba3052fa8b8/src/sys/unix/kqueue.rs#L229).  The latest version (0.7.0) [doesn't](https://github.com/tokio-rs/mio/blob/5da8c492a794849621b2b60ab0d351d36c1d0b47/src/sys/unix/selector/kqueue.rs#L319).

So I think this issue will be fixed by upgrading mio.

**Comment by realbigsean** [comment]
tokio 0.3 uses mio 0.7 so I'm going to close this for now 🤞  Ran debug tests on my mac and they passed
