### ISSUE TITLE
Out-of-the-box ARM support

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#880]
## Description

Lighthouse can run on ARM (e.g., RasPi 4) however it requires some tweaks to the [leveldb](https://github.com/skade/leveldb) crate.

## To Resolve

- Make our own fork of [skade/leveldb](https://github.com/skade/leveldb) which can compile on x86 and ARM.
- Use that repo in our `store` crate, intead of the crates.io package.
- Push a PR to the skade/leveldb with our fork so that we can eventually switch back to using the crates.io version.

**Comment by realbigsean** [comment]
Made a PR for this in the skade/leveldb, which has been merged to master: 
https://github.com/skade/leveldb/pull/36

**Comment by paulhauner** [comment]
Nice! I guess we need to wait for a release now..
