### ISSUE TITLE
Fork version validator signing handling

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#884]
## Description

The validator client must `subscribe` its validators to future slots in order to determine if it is an aggregator of attestations or not. Currently we sign with the fork_version of the current head. 

It's possible that the fork version changes by the time we are supposed to aggregate. The validator client should detect fork-version changes and update it's duties accordingly. A duties update, should trigger new subscriptions and the beacon node should handle obsolete aggregates via cache pruning (this should already be handled).

**Comment by paulhauner** [comment]
Resolved in the recent Altair PRs.
