### ISSUE TITLE
DHT persistence test failed

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#885]
## Description

CI failed on a DHT persistence test:

```
 thread 'service::tests::test_dht_persistence' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Libp2p(Msg("Discv5 service failed. Error: Os { code: 98, kind: AddrInUse, message: \"Address already in use\" }")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1188:5
```

Detail:

https://github.com/sigp/lighthouse/pull/865/checks?check_run_id=478747946

Perhaps both of the tests are trying to use the same port and there's a race condition where one fails if they both run at the same time.

**Comment by paulhauner** [comment]
@pawanjay176 I think this is your domain :)

**Comment by pawanjay176** [comment]
I think this was fixed in #874.

**Comment by paulhauner** [comment]
Ok, perhaps I'm running an outdated master!

I saw this one too, any idea on what that might be?

```
---- test_secio_noise_fallback stdout ----
thread 'test_secio_noise_fallback' panicked at 'should build a libp2p instance: Error(Msg("Libp2p was unable to listen on the given listen address."), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by pawanjay176** [comment]
Hmm that's odd. Looks like a port clash again :slightly_frowning_face: 
I explicitly specified non-default random(?) port numbers in that test. Not sure what it's clashing with. 

Do you have anything running on port 56010?

**Comment by AgeManning** [comment]
This is resolved now i believe?

**Comment by paulhauner** [comment]
This now exists as #942, so I think it's safe to close this one :)
