### ISSUE TITLE
Discv5 ENR-specific queries

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#887]
## Description

Currently discv5 only has a simplistic `find_peers()` function. This is satisfactory for finding new peers on the network. However with the addition of the `naive_attestation_aggregation` strategy and without discv5 topics, we need to search for peers with specific ENR keys (in this specific case, the subnet bitfield). 

It would be more efficient to implement a search based on ENR's that crawled the DHT looking for a predicate based on an ENR. The query would finish once a specified number of peers matching the predicate were found, or all peers exhausted.

**Comment by divagant-martian** [comment]
If it's ok I would like to work on this

**Comment by AgeManning** [comment]
Hey @divagant-martian, 

I saw you are also interested in #896. This particular issue has quite a few complexities and there are few updates to this section of code I was hoping to implement. 

Currently I think @pawanjay176 had his eye on this, but we always would like the extra help. Perhaps work on #896 first and see where we are at with this issue after that.

**Comment by AgeManning** [comment]
This has been resolved in #975
