### ISSUE TITLE
Add DNS support to discovery

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#889]
## Description

Discovery is currently based on IP. The PING packets update the ENR's IP. 

A configuration should allow the Enr to have a fixed static IP, regardless of the PONG response from other peers. We should allow the static IP to be derived from a DNS name. 

When setting the `--discovery-address` flag, the Enr's IP should remain static and ignore reported IP's from PONG responses. 

We should add a `--discovery-dns-address` flag which can specify the ENR's IP from a DNS name

See https://github.com/ethereum/devp2p/issues/138

**Comment by pawanjay176** [comment]
I'll take this one.
