### ISSUE TITLE
Shift parent chain lookup block processing to dedicated thread

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#896]
## Description

When an unknown block is seen on the gossip channel, lighthouse tries to find a chain of blocks that links it to the current known canonical chain. The depth of the lookup is specified by a constant and can be quite large.

Once a chain can be processed, we process all the downloaded blocks at once. This is currently done in the syncing thread task, which will block the executor. This block processing logic should be shifted to a dedicated thread as was done in the range sync.

**Comment by divagant-martian** [comment]
I'll work on this one

**Comment by AgeManning** [comment]
Awesome! Thanks for the help!

Let me point you at some code to make things a bit clearer (as some parts here are a little convoluted). 

Sometimes we see a block flying over the network that we've not seen before. When this happens, we try and add it into our chain. However, if we don't know it's parent, we can't add it.. we have to recursively lookup the blocks ancestry until it either matches our current chain or becomes too long. 

Each time we find a new parent, we try and process the entire chain of blocks here: https://github.com/sigp/lighthouse/blob/parent-lookup-update/beacon_node/network/src/sync/manager.rs#L583

Apologies for this being on a branch (I'll merge it to master soon). 

Specifically the chained block processing occurs here:
https://github.com/sigp/lighthouse/blob/parent-lookup-update/beacon_node/network/src/sync/manager.rs#L642

Now, block processing isn't exactly a fast task, so we want to shift the chain processing off into it's own OS thread, rather than have it run inside a task on our tokio executor. 

I've done a similar thing when we are syncing. See here to send off a request to process a chunk of blocks:
https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/sync/range_sync/chain.rs#L241

And here is a the code that spawns a block processing thread: 
https://github.com/sigp/lighthouse/blob/master/beacon_node/network/src/sync/range_sync/batch_processing.rs

It's currently called batch processor because I originally built it to process a batch of blocks during sync, we could rename it. 

I imagine we can use the batch processor and similar dispatch logic in the parent lookup case. This might actually be simpler as we don't  necessarily need to check the result of the processing, so don't need to update the logic to being async here. I think in this section of code, it doesn't matter if the blocks get processed or not, as in either case we drop the parent lookup. So in principle we can just send it off to a block processing thread and not wait any response. 
Although the block processing thread may then have to inform the user of success failure and downvote peers in the failure case.

Let me know if I can explain or help further
