### ISSUE TITLE
Typo in docs: /network/peer_id

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#902]
## Description

See: https://lighthouse-book.sigmaprime.io/http_network.html#networkpeer_count

The `/network/peer_count` route has a path of `/network/peer_id`. It should be  `/network/peer_count`.

Source is here: https://github.com/sigp/lighthouse/blob/master/book/src/http_network.md

**Comment by FawadHa1der** [comment]
https://github.com/sigp/lighthouse/pull/903
