### ISSUE TITLE
There is no "domain" for BLS signatures

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#91]
## Description

The spec declares that `BLSVerify` should take a  "domain". 

## Present Behaviour

Our code base has no concept of a domain.

## Expected Behaviour

Match the spec.

## Steps to resolve

I am not aware how domain is implemented, this is a placeholder issue as a `TODO` was created in the code.

1. Figure out what a domain is in a BLS signature verification.
2. Implement it.

**Comment by g-r-a-n-t** [comment]
I see that this relates to a [comment](https://github.com/sigp/lighthouse/pull/116#discussion_r244520952) I made on #116. I'm interested in picking this up, getting into the weeds with BLS sounds fun. Thoughts @paulhauner?

**Comment by paulhauner** [comment]
Yep, this works for me. I noticed @ralexstokes asking about BLS domains on the sharding gitter. Alex could you please confirm there wouldn't be a conflict here?

**Comment by g-r-a-n-t** [comment]
Thanks for the info @ralexstokes. I'll get started on this within the next week and follow up with any questions that may come up.

**Comment by kirk-baird** [comment]
This also applies to #149 which requires the implementation of:
`bls_verify_multiple() `
which allows for one signature over multiple messages (and pub keys) and requires domains.

**Comment by kirk-baird** [comment]
No worries :) 
Not yet, I got plenty to do first.

**Comment by paulhauner** [comment]
I am closing this as domain has been added to signature-schemes as of `v0.4.1`. I'll open up a fresh issue to track it's implementation to Lighthouse. Thank you all <3
