### ISSUE TITLE
Add REST API tests for new API functions

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#914]
## Description

The REST Api functions have been modified for the network upgrade. Unit tests need to be created to ensure they function as expected. 

The new API's are on the `v0.2.0` branch. 

If anyone wants to pick this up, let me know and I can detail this further.

**Comment by ackintosh** [comment]
Hi, I would love to address this issue! 😃

**Comment by b-m-f** [comment]
Hi @ackintosh ,

Did you start on this?

**Comment by AgeManning** [comment]
Hey @ackintosh 
Thanks for your interest.

This issue is about extending our current test suite for the rest api. We are undergoing a refactor to stable futures, but I believe this shouldn't effect this issue too much. 

Currently we have a series of tests here:
https://github.com/sigp/lighthouse/blob/master/beacon_node/rest_api/tests/test.rs

However these are lacking a number of endpoints. The tests use a `remote_beacon_node` which provides public functions for the rest http api endpoints. See this file:
https://github.com/sigp/lighthouse/blob/master/eth2/utils/remote_beacon_node/src/lib.rs

The actual endpoints are listed here: https://github.com/sigp/lighthouse/blob/master/beacon_node/rest_api/src/router.rs#L62

I think a few are not tested. The main ones I was concerned about are:
- "/validator/subscribe"
- "/validator/aggregate_attestation"
- "/validator/attestations"
- "/validator/aggregate_and_proofs"

Hopefully this is enough information to start digging around. Please let me know of any further questions :)

**Comment by ackintosh** [comment]
Thank you for the details! I'll start on this issue on this weekend and will let you know if I have any questions. 😃

**Comment by paulhauner** [comment]
> I think a few are not tested. The main ones I was concerned about are:
> 
>     * "/validator/subscribe"
> 
>     * "/validator/aggregate_attestation"
> 
>     * "/validator/attestations"
> 
>     * "/validator/aggregate_and_proofs"

FYI the test below covers all of these endpoints accept `validator/subscribe`. It could probably do with some more comprehensive coverage but they do have _some_ coverage presently:

https://github.com/sigp/lighthouse/blob/294d007f648db6784b6f93e48990228585f418b8/beacon_node/rest_api/tests/test.rs#L80-L260

**Comment by AgeManning** [comment]
Closed in #1189
