### ISSUE TITLE
Update REST API docs for v0.2.0 update

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#917]
## Description

A number of changes have been made to the REST API. Although this is simply a documentation issue, it will help with understanding how the REST API functions and it's associated methods. 

We need to update the book for the methods in the `v0.2.0` branch. 

More info available on request.

**Comment by EdsonAlcala** [comment]
Hi, I would like to work on this, can you give me more details?

**Comment by AgeManning** [comment]
First draft resolved in #1010
