### ISSUE TITLE
BeaconState::get_beacon_proposer_index should check slot

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#923]
## Description

The `BeaconState::get_beacon_proposer_index` function should check that the `slot` argument lies within sensible bounds before attempting to compute a proposer index. Proposer indices are only known for the current epoch and earlier due to the possibility of a validator's effective balance changing upon the next epoch boundary. The lower bound is likely related to the lower bound for the active validator indices (see #922), but could probably be set to the previous epoch for all current uses.

**Comment by paulhauner** [comment]
I think we don't have a look-back either -- we'd need to have the effective balances from the previous epoch in order to determine which proposer was used then.

**Comment by michaelsproul** [comment]
I'm working on this now
