### ISSUE TITLE
Panic: The next epoch cannot start before now

### ISSUE THREAD

**Issue by q9f** [sigp/lighthouse#938]
## Description

The validator client panicks upon restart.

## Version

```
~/.opt/lighthouse testnet5*
❯ git log -n1
commit 90e456d845bc4b9964f906be59e7a523c998b5c8 (HEAD -> testnet5, origin/testnet5)
Merge: 45e85c8e 394de218
Author: Paul Hauner <paul@paulhauner.com>
Date:   Thu Mar 19 00:30:37 2020 +1100

    Merge branch 'eth1-votes-tree-hash' into testnet5

~/.opt/lighthouse testnet5*
❯ rustc --version
rustc 1.41.1 (f3e1a954d 2020-02-24)
```

## Present Behaviour

```
~/.opt/lighthouse testnet5*
❯ RUST_BACKTRACE=1 ./target/release/lighthouse vc --allow-unsynced
Mar 19 11:05:33.898 WARN Ethereum 2.0 is pre-release. This software is experimental.
Mar 19 11:05:33.899 INFO Starting validator client               datadir: "/home/user/.lighthouse/validators", beacon_node: http://localhost:5052/
Mar 19 11:05:33.915 INFO Connected to beacon node                version: Lighthouse/v0.1.0-unstable/x86_64-linux
Mar 19 11:05:33.916 INFO Genesis has already occurred            seconds_ago: 72333
Mar 19 11:05:33.922 INFO Loaded validator keypair store          voting_validators: 16
thread 'main' panicked at 'The next epoch cannot start before now', src/libcore/option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::option::expect_failed
             at src/libcore/option.rs:1188
  14: slot_clock::manual_slot_clock::ManualSlotClock::duration_to_next_epoch_from
  15: <slot_clock::system_time_slot_clock::SystemTimeSlotClock as slot_clock::SlotClock>::duration_to_next_epoch
  16: validator_client::fork_service::ForkService<T,E>::start_update_service
  17: lighthouse::run
  18: lighthouse::main
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  23: std::panicking::try
             at src/libstd/panicking.rs:270
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Expected Behaviour

It should not panic and start validating.

## Steps to resolve

Unknown.

**Comment by paulhauner** [comment]
Thanks for raising his @q9f.

I've done some looking into this and I can only see the following circumstances where this error can be raised:

### 1. `SECONDS_PER_SLOT == 0`

It seems unlikely that this is the case, I doubt you modified this variable. Furthermore, this check protects against that:

https://github.com/sigp/lighthouse/blob/a5fbaef469df221f16b84601e78a83b009e13247/eth2/utils/slot_clock/src/system_time_slot_clock.rs#L17-L19

### 2. `SLOTS_PER_EPOCH == 0`

Given these are hard-coded into the [`EthSpec`](https://github.com/sigp/lighthouse/blob/master/eth2/types/src/eth_spec.rs) trait, I'll assume they have not been modified.

### 3. Your system time skipped backwards

Perhaps an NTP sync happened _exactly_ at the wrong moment? This seems quite improbable and it's not a satisfying explanation.

Regardless, I've [refactored](https://github.com/sigp/lighthouse/pull/929/commits/6ee07d517731053cdf913aa4d650501e260e6995) the code that triggered the panic such that it no longer does two reads of the system clock and therefore could not panic in the same way.

### 4. `GENESIS_SLOT > 0`

It seems unlikely that this was the case. Regardless, the previous refactor will cover this scenario.

### 5. There's something I missed

The previously mentioned refactor improves some code and adds more tests, so hopefully the thing I've missed has been wiped out.

----

So, I've marked #929 to resolve this issue. It's not completely satisfying, but it seems reasonable.

@q9f it would be good to know if you saw this error more than once. If so, that would make option 3 seem much less likely.

**Comment by q9f** [comment]
> it would be good to know if you saw this error more than once.

yes, it's reproducable. I compiled `clock-disparity` branch and can confirm #929 fixes the issue :+1:

**Comment by paulhauner** [comment]
> yes, it's reproducable.

Seems like this is a (5) then, which is a little concerning! Glad that the new code fixed it though.
