### ISSUE TITLE
Test is failing: test_secio_noise_fallback

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#942]
## Description

Test is raising a `AddrInUse` in a non-deterministic fashion. See: 

https://github.com/sigp/lighthouse/runs/520858059

This is the second time I've seen this in the last few days.

## Version

On `master`, Rust version not relevant.

## Steps to resolve

I assume this is because sometimes two of these network tests run at the same time. If that's the case, they should use different ports.

**Comment by paulhauner** [comment]
@pawanjay176 I think this is relevant to you :)

**Comment by pawanjay176** [comment]
Looking into it

**Comment by pawanjay176** [comment]
I think that the debug and release tests on CI ran at the same time for this particular test which caused the port clash.
@paulhauner did you get this error locally as well? if not, I think the debug release tests running simultaneously is the issue.

**Comment by paulhauner** [comment]
The debug and release tests run on different instances, so I don’t think it’s possible the would cause port conflicts. Are there two sets of networking tests in the whole codebase? If so, Rust runs inter-crate tests concurrently and that might be the issue.

**Comment by AgeManning** [comment]
Should be addressed in #998. It's not entirely rigorous but should suit our needs for the time being. 

If it occurs again, we can address it in more detail.
