### ISSUE TITLE
Improve Syncing Sim to complete on sync

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#943]
## Description

Currently the syncing simulator waits for a particular epoch before ending. I think this mimics the beacon simulator. 

I think the faster and more accurate test should be that a node achieves sync. The test should end once all connected nodes are in sync, rather than waiting for some pre-determined epoch. 

This will also help with dissecting the logs, as sync logs will be closer to the end of the test. There should of-course be a timeout which fails the test if nodes don't reach sync.

**Comment by divagant-martian** [comment]
I'm currently looking into the sync sim, would if be ok for me to check this out?

**Comment by AgeManning** [comment]
Yep, all yours
