### ISSUE TITLE
Handle Fork switching logic in attestation and subnet subscriptions

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#964]
## Description

A client should know about an up-coming fork. When a VC is building subscriptions for a future slot, it should ensure that the subscription does not cross a fork-boundary in which case the signature for a future slot will be invalid. 

This is important in determining whether a validator is an aggregator or not. 
Similarly, when subscribing to subnets and/or deciding on the current number of aggregate validators existing for a subnet on a particular slot, the future fork needs to be taken into account.

**Comment by paulhauner** [comment]
I'm going to close this once since it seems we're certainly going to fix it with Altair in the coming weeks. Feel free to re-open if you want :slightly_smiling_face:
