### ISSUE TITLE
Asynchronous attestation verification

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#980]
## Description

For the time being when we see an attestation over the network that references an unknown block, we drop the attestation. It would be ideal if we temporarily store the attestation whilst we request the requested block. If the block can be found and processed, then we propagate the attestation.

**Comment by divagant-martian** [comment]
I think this is a duplicate of #635

**Comment by AgeManning** [comment]
Ah yes. I keep making issues that I've forgot I've already made issues about. 

Closing in favour of #635 

Thanks for the catch @divagant-martian
