### ISSUE TITLE
Refactor RPC code

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#987]
## Description

A number of modifications have happened since the original writing of the RPC. The code should be refactored for greater readability and to rely on the rust type system more. 

Immediate changes:
- The `RequestId` should be an option as for some methods we do no require the id. 
- More types should be created to srparate the logic of each RPC method. For example, some RPC methods are handled by discovery (i.e Ping and Meta data) and are not propagated to the network crate. Some methods require a single chunk responds whereas others require multiple. Separating these out into individual types should hopefully make the code easier to read, upgrade and maintain.

**Comment by divagant-martian** [comment]
Closed with #1187
