### ISSUE TITLE
RPC Peer Reputation Types/Handling

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#990]
## Description

A variety of Errors can occur in the RPC protocol. They can have a variety of weights when it comes to adjusting the reputation of a peer. This issue, is to more clearly define (likely via enums) specific types of RPC errors, send them to the peer manager and adjust a peer's score based on their type. 

Some things we need to consider:
- A peer should always respond to a PING (it's lightweight and we prioritise it, regardless of processing). We should send/receive these every 30 seconds. If a peer doesn't respond, it should be heavily weighted down (perhaps 2 consecutive pings should disconnect a very reputable peer). It's likely that if a peer is genuinely offline, other rpc methods will be failing and the reputation will be dropping quite fast also. 
- A peer that times-out when trying to negotiate a protocol could mean the peer is offline, or overworked (`clogged`). We should be somewhat lenient with over-worked peers, although we should lower their reputation which will make lighthouse favour them less and request less data. 
- A peer that doesn't support a specific RPC protocol - For now I think we do not downvote a peer, but maybe built it so that we can prioritise specific methods. For example, a peer that doesn't support PING we drop, but we tolerate a peer that doesn't support blocks_by_root. For this case, just build the ability to distinguish, but don't actually modify the reputation. 
- A peer that sends invalid/corrupt data - Should lose reputation. We should punish them pretty heavily. Potentially even disconnect instantly. 

Parts of the code relevant to update this logic. 

For the RPC, when an error occurs, we collect it here: 
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/eth2-libp2p/src/rpc/handler.rs#L436

This will need to be modified, as I'm currently only keeping track of the request_id, where we will need to know the actual request also (for its type, to determine what type of RPC the error occurred for). 

The errors then get processed here: 
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/eth2-libp2p/src/rpc/handler.rs#L451
Note that this returns an RPCError (which can be captured by the peer manager as it passes up to the network crate, i'll explain below). 

So if an peer times-out we could identify the request type and return a more specific RPCError:
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/eth2-libp2p/src/rpc/handler.rs#L470
For example, `RPCError::PingTimeout`

A decoding error should get propagated from the underlying codecs (i.e some of the other RPCError varints will automagically get sent when they occur)

The `RPCError` struct to add variants to is here:
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/eth2-libp2p/src/rpc/protocol.rs#L302

Once we've added sufficient RPCError variants to match with the reputation logic we want, we can capture these in the behaviour and feed them to the peer manager to adjust the reputation, similar to how the Ping and Metadata RPC methods work:
https://github.com/sigp/lighthouse/blob/v0.2.0/beacon_node/eth2-libp2p/src/behaviour.rs#L399

Note that we still want to add the events to the behaviour event list as these will be propagated to other parts of lighthouse to inform various sections an error occured. We just want to also inform the peer manager here about these errors. 

Let me know if further information is required.

**Comment by divagant-martian** [comment]
I'll take this one

**Comment by divagant-martian** [comment]
@AgeManning should we consider this one closed?

**Comment by AgeManning** [comment]
Oh yeah. Resolved by @divagant-martian in #1047
