### ISSUE TITLE
Introduce an error handling library that supports backtraces

### ISSUE THREAD

**Issue by adaszko** [sigp/lighthouse#991]
The candidate: https://crates.io/crates/anyhow

**Comment by paulhauner** [comment]
I found this an appealing justification for the `fehler` way of things:

https://boats.gitlab.io/blog/post/why-ok-wrapping/

I'm not sure I'm fully convinced I'd vote for it though, I'd need to read into it some more.

**Comment by adaszko** [comment]
Claiming this issue

**Comment by michaelsproul** [comment]
I've assigned you! (after accidentally assigning myself -- ignore that)

**Comment by adaszko** [comment]
So the current state of the Rust ecosystem is that there are two kinds of error handling libraries ([1], [2]):

1) Those that use a custom, crate-defined types and traits for error handling
2) Those that use the newer stable incarnation of the stdlib `Error` trait

Of the two, clearly (2) is the more future-proof way.  The problem is that the parts of the standard library that deal with backtraces [haven't been stabilized yet](https://github.com/rust-lang/rust/issues/53487#issuecomment-638878790), so the crates that rely on stdlib (e.g. anyhow) can't take advantage of backtraces on stable rustc yet.  Since [stdlib backtraces have been already proposed for stabilization](https://github.com/rust-lang/rust/issues/53487#issuecomment-638878790), I think the best way is to wait for a new release of anyhow that includes stable backtraces instead of buying into some (1) crate that will soon become deprecated.

[1]: https://blog.yoshuawuyts.com/error-handling-survey/
[2]: https://nick.groenen.me/posts/rust-error-handling/

**Comment by paulhauner** [comment]
I'm going to close this once since it seems unlikely at this point we'll make progress here. If we do start to suffer from lack of backtraces the we can start a new issue (or reopen this).
