### ISSUE TITLE
WARN Peer sent invalid BEACON_BLOCKS response

### ISSUE THREAD

**Issue by Youllneverknow0** [sigp/lighthouse#995]
## Description

When I follow the steps described here: https://lighthouse-book.sigmaprime.io/become-a-validator-source.html

1. geth --goerli --rpc
2. lighthouse beacon --eth1 --http

Then:
Geth seems to be working fine in goerli mode.

But in lighthouse:
I get "WARN Peer sent invalid BEACON_BLOCKS response" over and over and over again.

## Version

lighthouse v0.1.1
geth 1.9.12-stable-b6f1c8dc
Ubuntu 18.04.4 LTS
HW: Raspberry Pi 4 Model B

## Present Behaviour

From lighthouse I get a vast amount of:

Apr 10 16:01:03.499 **WARN Peer sent invalid BEACON_BLOCKS response**, error: OutOfBoundsByte { i: 2634909406 }, peer: PeerId("16Uiu2HAmU4K81niVR49foGL2Tpoh
9MCysZ2LtCXbR5xtmRwFJhpx"), service: msg_handler, service: network                                                                                      
Apr 10 16:01:03.501 **WARN Peer sent invalid BEACON_BLOCKS response**, error: OutOfBoundsByte { i: 991854556 }, peer: PeerId("16Uiu2HAmU4K81niVR49foGL2Tpoh9
MCysZ2LtCXbR5xtmRwFJhpx"), service: msg_handler, service: network                                                                                       
Apr 10 16:01:03.502 **WARN Peer sent invalid BEACON_BLOCKS response**, error: OutOfBoundsByte { i: 2644027138 }, peer: PeerId("16Uiu2HAmB7Ki9YjT4tMckpwE8jCo
5mvcKStJedyPXN82kiyQkBLr"), service: msg_handler, service: network          

## Expected Behaviour

I guess something like:
Dec 09 12:57:18.026 INFO Syncing
est_time: 2 hrs ...

## Steps to resolve

This what I'm asking for

**Comment by paulhauner** [comment]
Thanks for raising the issue @Youllneverknow0. Could you please confirm if you were using the `master` or `testnet5` branch? Or perhaps the docker?

**Comment by AgeManning** [comment]
I imagine this is master connecting to the testnet5 testnet. 

Pretty sure those peer's are ours and the warning is likely that using `master` which has the latest spec isn't compatible with the nodes running on the `testnet`. 

Try using the `testnet5` branch

**Comment by Youllneverknow0** [comment]
I finally managed to recompile with testnet5 and it did the trick.
Thank you paulhauner and AgeManning.

beacon node and validator client running.

Any idea where I can find online stats for testnet5?

https://lighthouse-testnet3.beaconcha.in/ seems to be down and a number5 not available.

**Comment by paulhauner** [comment]
> Any idea where I can find online stats for testnet5?

I'm not sure there's an explorer up anymore. This testnet will likely be dropped within a week and the next one should have something again :)
